function Protocol = CBS_CGAN_cutoff_diagnostic_protocol(rootPath,nWorker)
%CBS_CGAN_CUTOFF_DIAGNOSTIC_PROTOCOL Frozen exact-cutoff experiment design.

    if nargin < 1 || isempty(rootPath)
        rootPath = fileparts(which('platemo'));
    end
    if nargin < 2 || isempty(nWorker)
        nWorker = 10;
    end
    Protocol = struct();
    Protocol.schemaVersion = "CBS-CGAN-cutoff-campaign-v1";
    Protocol.campaignName = "CBS_CGAN_cutoff_diagnostics_runs1_5";
    Protocol.rootPath = char(rootPath);
    Protocol.nWorker = round(double(nWorker));
    Protocol.popSize = 100;
    Protocol.dimension = 30;
    Protocol.maxFE = 200000;
    Protocol.seeds = 1:5;
    Protocol.problems = ["DASCMOP1_BC","DASCMOP5_BC", ...
        "DASCMOP9_BC","LIRCMOP10_BC","LIRCMOP14_BC"];
    Protocol.maxAttempts = 3;
    Protocol.phase1Arms = [ ...
        makeArm("A0","CBS_RegionWGAN_GP_Experiment",{0,100,32,500}), ...
        makeArm("A1","CBS_RegionWGAN_GP_A1",{}), ...
        makeArm("Current","CBS_RegionWGAN_GP",{}), ...
        makeArm("E0","CBS_RegionWGAN_GP_E0_Base", ...
            {0,5,2,5,0,0,0,0,1}), ...
        makeArm("Random20","CBS_RegionWGAN_GP_Random20",{}), ...
        makeArm("DE20","CBS_RegionWGAN_GP_DE20",{}), ...
        makeArm("GA20","CBS_RegionWGAN_GP_GA20",{})];
    Protocol.phase2Arms = [ ...
        makeArm("E1","CBS_RegionWGAN_GP_E1_KeepAnchor", ...
            {1,5,2,5,0,0,0,0,1}), ...
        makeArm("K10","CBS_RegionWGAN_GP_E2_K10", ...
            {0,10,2,5,0,0,0,0,1}), ...
        makeArm("KAll","CBS_RegionWGAN_GP_E2_KAll", ...
            {0,Inf,2,5,0,0,0,0,1}), ...
        makeArm("Cap10","CBS_RegionWGAN_GP_E4_Cap10", ...
            {0,5,2,10,0,0,0,0,1})];
    Protocol.requiredAuditFields = [ ...
        "diagnosticSchemaVersion","cganEndFE","cganEndIGD", ...
        "cganEndHV","cganEndDecs","cganEndObjs","cganEndCons", ...
        "checkpointFE","checkpointIGD","checkpointHV", ...
        "frontHalfIGDAUC","frontHalfHVAUC", ...
        "rawBoundaryDistanceMedian","keptBoundaryDistanceMedian", ...
        "selectedBoundaryDistanceMedian","criticBoundarySpearman"];
end

function Arm = makeArm(label,className,parameters)
    Arm = struct('label',string(label),'className',string(className), ...
        'parameters',{parameters});
end
