function Summary = render_CBS_PairGuide_training_schedule_3d_supplement( ...
        rootPath,campaignName)
%RENDER_CBS_PAIRGUIDE_TRAINING_SCHEDULE_3D_SUPPLEMENT Render readable 3-D sheets.

    if nargin < 1 || isempty(rootPath)
        rootPath = fileparts(which('platemo'));
    end
    if nargin < 2 || strlength(string(campaignName)) == 0
        campaignName = "CBS_PairGuide_training_schedule_v1_20260901";
    end
    rootPath = char(rootPath);
    campaignName = string(campaignName);
    campaignDir = fullfile(rootPath,'Data',char(campaignName));
    problem = "LIRCMOP14_BC";
    stages = ["ratio","epoch"];
    addCBSPaths(rootPath);

    campaignManifest = fullfile(campaignDir,'campaign_manifest.mat');
    requireFile(campaignManifest,'campaign manifest');
    Campaign = load(campaignManifest,'CampaignProtocol');
    if ~isfield(Campaign,'CampaignProtocol') || ...
            ~isfield(Campaign.CampaignProtocol,'sourceFingerprint')
        error('CBSPairGuide:BadSupplementCampaignManifest', ...
            '%s is missing CampaignProtocol.sourceFingerprint.', ...
            campaignManifest);
    end
    Frozen = Campaign.CampaignProtocol.sourceFingerprint;
    assertFrozenSources(rootPath,Frozen);

    sourceFigureDir = fullfile(campaignDir,'figures','training_schedule');
    sourceManifestMAT = fullfile(sourceFigureDir,'figure_manifest.mat');
    sourceManifestCSV = fullfile(sourceFigureDir,'figure_manifest.csv');
    requireFile(sourceManifestMAT,'source figure manifest MAT');
    requireFile(sourceManifestCSV,'source figure manifest CSV');
    Original = load(sourceManifestMAT,'Figures');
    if ~isfield(Original,'Figures') || ~isstruct(Original.Figures)
        error('CBSPairGuide:BadSupplementFigureManifest', ...
            '%s is missing struct array Figures.',sourceManifestMAT);
    end
    SourceFigures = selectSourceFigures(Original.Figures,stages,problem);
    validateSharedView(SourceFigures);

    rendererFile = string(mfilename('fullpath'));
    if ~endsWith(rendererFile,".m")
        rendererFile = rendererFile+".m";
    end
    rendererSHA256 = sha256File(rendererFile);
    sourceManifestMatSHA256 = sha256File(sourceManifestMAT);
    sourceManifestCsvSHA256 = sha256File(sourceManifestCSV);
    frozenFingerprint = string(Frozen.combinedSHA256);

    Bundles = repmat(struct('stage',"",'armName',"", ...
        'armValues',zeros(1,3),'Snapshots',{{}}, ...
        'inputFiles',strings(1,3),'inputSHA256',strings(1,3)),2,1);
    InputRows = repmat(struct('stage',"",'problem',problem,'run',0, ...
        'armName',"",'armValue',0,'reused',false, ...
        'snapshotCount',0,'actualFE',"",'inputFile',"", ...
        'inputSHA256',""),6,1);
    inputRow = 0;
    Problem = [];
    for s = 1 : numel(stages)
        stageDir = fullfile(campaignDir,char(stages(s)));
        stageManifest = fullfile(stageDir,'campaign_manifest.mat');
        requireFile(stageManifest,'stage campaign manifest');
        M = load(stageManifest,'Protocol','Tasks');
        if ~isfield(M,'Protocol') || ~isfield(M,'Tasks')
            error('CBSPairGuide:BadSupplementStageManifest', ...
                '%s must contain Protocol and Tasks.',stageManifest);
        end
        F = SourceFigures(s);
        arms = double(M.Protocol.arms(:)');
        if numel(arms) ~= 3 || ~isequal(arms,double(F.armValues)) || ...
                string(M.Protocol.armName) ~= string(F.armName)
            error('CBSPairGuide:SupplementArmMismatch', ...
                '%s stage arms disagree with the source figure manifest.', ...
                stages(s));
        end
        taskProblems = string({M.Tasks.problem});
        taskRuns = double([M.Tasks.run]);
        taskArms = double([M.Tasks.armValue]);
        snapshots = cell(1,3);
        inputFiles = strings(1,3);
        inputSHA256 = strings(1,3);
        actualFE = zeros(3,10);
        for arm = 1 : 3
            tolerance = 64*eps(max(1,abs(arms(arm))));
            rows = find(taskProblems == problem & taskRuns == F.run & ...
                abs(taskArms-arms(arm)) <= tolerance);
            if numel(rows) ~= 1
                error('CBSPairGuide:SupplementTaskIdentity', ...
                    ['%s needs exactly one %s=%g run %d task; ', ...
                     'found %d.'],problem,F.armName,arms(arm),F.run, ...
                    numel(rows));
            end
            resultFile = resolveResultFile( ...
                char(M.Tasks(rows).outputFile),stageDir);
            Data = loadScheduleResult(resultFile,problem,F.run,F.targetFE);
            if isempty(Problem)
                constructor = str2func(char(problem));
                Problem = constructor('N',double(Data.Record.N), ...
                    'D',double(Data.Record.D),'maxFE',1e9, ...
                    'maxRuntime',Inf);
                if Problem.M ~= 3 || double(Data.Record.M) ~= 3
                    error('CBSPairGuide:SupplementProblemDimension', ...
                        '%s supplement requires exactly three objectives.', ...
                        problem);
                end
            elseif double(Data.Record.M) ~= Problem.M || ...
                    double(Data.Record.N) ~= Problem.N || ...
                    double(Data.Record.D) ~= Problem.D
                error('CBSPairGuide:SupplementDimensionMismatch', ...
                    '%s source results have inconsistent M/N/D.',problem);
            end
            snapshots{arm} = Data.Snapshots;
            inputFiles(arm) = string(resultFile);
            inputSHA256(arm) = sha256File(resultFile);
            actualFE(arm,:) = double([Data.Snapshots.actualFE]);
            inputRow = inputRow+1;
            InputRows(inputRow) = struct( ...
                'stage',stages(s),'problem',problem,'run',F.run, ...
                'armName',string(F.armName),'armValue',arms(arm), ...
                'reused',string(Data.Record.stageName) ~= stages(s), ...
                'snapshotCount',numel(Data.Snapshots), ...
                'actualFE',numberList([Data.Snapshots.actualFE]), ...
                'inputFile',string(resultFile), ...
                'inputSHA256',inputSHA256(arm));
        end
        if any(any(actualFE ~= actualFE(1,:))) || ...
                ~isequal(actualFE,double(F.actualFE))
            error('CBSPairGuide:SupplementActualFEMismatch', ...
                '%s actual FE values disagree across arms or manifest.', ...
                stages(s));
        end
        Bundles(s) = struct('stage',stages(s), ...
            'armName',string(F.armName),'armValues',arms, ...
            'Snapshots',{snapshots},'inputFiles',inputFiles, ...
            'inputSHA256',inputSHA256);
    end

    outputDir = fullfile(campaignDir,'figures', ...
        'training_schedule_3d_supplement');
    ensureFolder(outputDir);
    Figures = repmat(struct('stage',"",'problem',problem,'run',0, ...
        'armName',"",'armValues',zeros(1,3), ...
        'targetFE',zeros(1,10),'actualFE',zeros(3,10), ...
        'viewLower',zeros(1,3),'viewUpper',zeros(1,3), ...
        'snapshotCount',0,'inputFiles',strings(1,3), ...
        'inputSHA256',strings(1,3),'file',"", ...
        'outputSHA256',"",'width',0,'height',0),2,1);
    for s = 1 : numel(stages)
        F = SourceFigures(s);
        B = Bundles(s);
        outputFile = fullfile(outputDir,sprintf( ...
            '%s_%s_run%02d_3x10_readable_v1.png', ...
            stages(s),problem,F.run));
        View = struct('lower',double(F.viewLower), ...
            'upper',double(F.viewUpper));
        renderSheet(Problem,problem,stages(s),B.armName, ...
            B.armValues,F.run,B.Snapshots,View,outputFile);
        Info = imfinfo(outputFile);
        Figures(s) = struct('stage',stages(s),'problem',problem, ...
            'run',F.run,'armName',B.armName, ...
            'armValues',B.armValues,'targetFE',double(F.targetFE), ...
            'actualFE',double(F.actualFE), ...
            'viewLower',View.lower,'viewUpper',View.upper, ...
            'snapshotCount',30,'inputFiles',B.inputFiles, ...
            'inputSHA256',B.inputSHA256,'file',string(outputFile), ...
            'outputSHA256',sha256File(outputFile), ...
            'width',Info.Width,'height',Info.Height);
    end

    finishedAt = string(datetime('now'));
    ManifestRows = repmat(struct('stage',"",'problem',problem, ...
        'run',0,'armName',"",'armValues',"",'targetFE',"", ...
        'snapshotCount',0,'viewLower',"",'viewUpper',"", ...
        'frozenSourceFingerprint',frozenFingerprint, ...
        'sourceFigureManifestMatSHA256',sourceManifestMatSHA256, ...
        'sourceFigureManifestCsvSHA256',sourceManifestCsvSHA256, ...
        'supplementRendererSHA256',rendererSHA256,'inputFiles',"", ...
        'inputSHA256',"",'file',"",'outputSHA256',"", ...
        'width',0,'height',0,'finishedAt',finishedAt),2,1);
    for s = 1 : numel(stages)
        F = Figures(s);
        ManifestRows(s) = struct('stage',F.stage,'problem',F.problem, ...
            'run',F.run,'armName',F.armName, ...
            'armValues',numberList(F.armValues), ...
            'targetFE',numberList(F.targetFE), ...
            'snapshotCount',F.snapshotCount, ...
            'viewLower',numberList(F.viewLower), ...
            'viewUpper',numberList(F.viewUpper), ...
            'frozenSourceFingerprint',frozenFingerprint, ...
            'sourceFigureManifestMatSHA256', ...
                sourceManifestMatSHA256, ...
            'sourceFigureManifestCsvSHA256', ...
                sourceManifestCsvSHA256, ...
            'supplementRendererSHA256',rendererSHA256, ...
            'inputFiles',strjoin(F.inputFiles,';'), ...
            'inputSHA256',strjoin(F.inputSHA256,';'), ...
            'file',F.file,'outputSHA256',F.outputSHA256, ...
            'width',F.width,'height',F.height, ...
            'finishedAt',finishedAt);
    end
    SupplementManifest = struct2table(ManifestRows);
    Inputs = struct2table(InputRows);
    Summary = struct( ...
        'schemaVersion', ...
            "CBS-PairGuide-training-schedule-3d-supplement-v1", ...
        'campaignName',campaignName,'problem',problem,'run',3, ...
        'figureCount',numel(Figures),'expectedFigureCount',2, ...
        'panelsPerFigure',30, ...
        'frozenSourceFingerprint',frozenFingerprint, ...
        'sourceFigureManifestMAT',string(sourceManifestMAT), ...
        'sourceFigureManifestMatSHA256',sourceManifestMatSHA256, ...
        'sourceFigureManifestCSV',string(sourceManifestCSV), ...
        'sourceFigureManifestCsvSHA256',sourceManifestCsvSHA256, ...
        'supplementRenderer',rendererFile, ...
        'supplementRendererSHA256',rendererSHA256, ...
        'finishedAt',finishedAt);
    if Summary.figureCount ~= Summary.expectedFigureCount
        error('CBSPairGuide:SupplementFigureCount', ...
            'Rendered %d figures; expected %d.',Summary.figureCount,2);
    end
    manifestMAT = fullfile(outputDir,'supplement_manifest.mat');
    manifestCSV = fullfile(outputDir,'supplement_manifest.csv');
    writeManifestAtomic(manifestMAT,manifestCSV,Summary,Figures, ...
        SupplementManifest,Inputs);
end

function SourceFigures = selectSourceFigures(Figures,stages,problem)
    SourceFigures = repmat(Figures(1),numel(stages),1);
    figureStages = string({Figures.stage});
    figureProblems = string({Figures.problem});
    for s = 1 : numel(stages)
        rows = find(figureStages == stages(s) & ...
            figureProblems == problem);
        if numel(rows) ~= 1
            error('CBSPairGuide:SupplementSourceFigureIdentity', ...
                'Expected one %s %s source figure; found %d.', ...
                stages(s),problem,numel(rows));
        end
        SourceFigures(s) = Figures(rows);
        if SourceFigures(s).run ~= 3 || ...
                SourceFigures(s).snapshotCount ~= 30 || ...
                numel(SourceFigures(s).targetFE) ~= 10
            error('CBSPairGuide:BadSupplementSourceFigure', ...
                '%s source figure metadata is incomplete.',stages(s));
        end
    end
end

function validateSharedView(Figures)
    if ~isequaln(double(Figures(1).viewLower), ...
            double(Figures(2).viewLower)) || ...
            ~isequaln(double(Figures(1).viewUpper), ...
            double(Figures(2).viewUpper))
        error('CBSPairGuide:SupplementSharedViewMismatch', ...
            'Ratio and epoch LIRCMOP14 source figures do not share axes.');
    end
    lower = double(Figures(1).viewLower);
    upper = double(Figures(1).viewUpper);
    if numel(lower) ~= 3 || numel(upper) ~= 3 || ...
            any(~isfinite([lower,upper])) || any(lower >= upper)
        error('CBSPairGuide:BadSupplementSharedView', ...
            'LIRCMOP14 source view bounds are invalid.');
    end
end

function Data = loadScheduleResult(file,problem,run,targetFE)
    requireFile(file,'training-schedule result');
    variables = string({whos('-file',file).name});
    required = ["Record","Snapshots"];
    missing = required(~ismember(required,variables));
    if ~isempty(missing)
        error('CBSPairGuide:BadSupplementResultVariables', ...
            '%s is missing variables: %s',file,strjoin(missing,', '));
    end
    Data = load(file,'Record','Snapshots');
    R = Data.Record;
    S = Data.Snapshots;
    requiredRecord = {'status','stageName','problem','run', ...
        'M','N','D','snapshotCount'};
    if ~isstruct(R) || ~isscalar(R) || ...
            ~all(isfield(R,requiredRecord)) || string(R.status) ~= "ok" || ...
            string(R.problem) ~= problem || double(R.run) ~= run || ...
            double(R.M) ~= 3 || double(R.snapshotCount) ~= 10
        error('CBSPairGuide:BadSupplementResultRecord', ...
            '%s has invalid Record metadata.',file);
    end
    requiredLayers = {'raw','target','center','guided', ...
        'population1','population2'};
    if ~isstruct(S) || numel(S) ~= 10 || ...
            ~isequal(double([S.targetFE]),double(targetFE(:)')) || ...
            any(~isfinite([S.actualFE])) || any(diff([S.actualFE]) < 0)
        error('CBSPairGuide:BadSupplementSnapshots', ...
            '%s does not contain the expected 10 FE snapshots.',file);
    end
    for snapshot = 1 : numel(S)
        for layer = 1 : numel(requiredLayers)
            name = requiredLayers{layer};
            objs = S(snapshot).([name,'Objs']);
            cons = S(snapshot).([name,'Cons']);
            if ~isnumeric(objs) || size(objs,2) ~= 3 || ...
                    any(~isfinite(objs),'all') || ~isnumeric(cons) || ...
                    size(cons,1) ~= size(objs,1) || ...
                    any(~isfinite(cons),'all')
                error('CBSPairGuide:BadSupplementSnapshotLayer', ...
                    '%s snapshot %d layer %s is invalid.', ...
                    file,snapshot,name);
            end
        end
        if size(S(snapshot).rawObjs,1) ~= 500
            error('CBSPairGuide:BadSupplementRawCount', ...
                '%s snapshot %d does not contain 500 raw points.', ...
                file,snapshot);
        end
    end
end

function renderSheet(Problem,problem,stage,armName,arms,run, ...
        Snapshots,View,outputFile)
    Figure = figure('Visible','off','Color','w', ...
        'Position',[20,50,4200,1800]);
    cleanup = onCleanup(@()close(Figure));
    C = figureColors();
    legendHandles = gobjects(1,0);
    legendAxes = gobjects(1,1);

    left = 0.008;
    right = 0.008;
    bottom = 0.055;
    top = 0.935;
    horizontalGap = 0.003;
    verticalGap = 0.015;
    cellWidth = (1-left-right-9*horizontalGap)/10;
    cellHeight = (top-bottom-2*verticalGap)/3;
    for arm = 1 : 3
        armLabel = sprintf('%s=%g',armName,arms(arm));
        rowTop = top-(arm-1)*(cellHeight+verticalGap);
        cellY = rowTop-cellHeight;
        for snapshot = 1 : 10
            cellX = left+(snapshot-1)*(cellWidth+horizontalGap);
            Ax = axes(Figure,'Units','normalized','Position',[ ...
                cellX+0.075*cellWidth,cellY+0.045*cellHeight, ...
                0.85*cellWidth,0.74*cellHeight]);
            hold(Ax,'on');
            [hFeasible,hInfeasible] = draw_CBS_CGAN_objective_region( ...
                Ax,Problem,problem,C,View);
            H = drawLayers(Ax,Snapshots{arm}(snapshot),C);
            setView(Ax,View);
            styleAxes(Ax,arm,snapshot);
            camzoom(Ax,0.75);
            if snapshot == 1
                timeLabel = 'first use';
            else
                timeLabel = sprintf('%gK target', ...
                    Snapshots{arm}(snapshot).targetFE/1000);
            end
            annotation(Figure,'textbox',[cellX, ...
                cellY+cellHeight-0.040,cellWidth,0.037], ...
                'String',sprintf('%s\n%s | actual FE %s', ...
                armLabel,timeLabel, ...
                commaNumber(Snapshots{arm}(snapshot).actualFE)), ...
                'Interpreter','none','EdgeColor','none', ...
                'HorizontalAlignment','center', ...
                'VerticalAlignment','middle','FontName','Helvetica', ...
                'FontSize',6.5,'FontWeight','normal', ...
                'Margin',0);
            if arm == 1 && snapshot == 1
                legendAxes = Ax;
                legendHandles = [hFeasible,hInfeasible,H];
            end
        end
    end
    annotation(Figure,'textbox',[0.04,0.962,0.92,0.028], ...
        'String',sprintf([ ...
        '%s | %s stage | representative run %d | ', ...
        'shared view across both stages | readable v1'], ...
        problem,stage,run),'Interpreter','none','EdgeColor','none', ...
        'HorizontalAlignment','center','VerticalAlignment','middle', ...
        'FontName','Helvetica','FontWeight','bold','FontSize',15, ...
        'Margin',0);
    labels = {'feasible region','infeasible region','P1','P2', ...
        'raw 500','selected target','selected center','guided child'};
    Legend = legend(legendAxes,legendHandles,labels, ...
        'Orientation','horizontal','NumColumns',8,'FontSize',7, ...
        'Box','off','Interpreter','none');
    Legend.Units = 'normalized';
    drawnow;
    Legend.Position = [0.25,0.010,0.50,0.025];
    drawnow;

    partialFile = [outputFile,'.partial.png'];
    exportgraphics(Figure,partialFile,'Resolution',96, ...
        'BackgroundColor','white');
    if ~validPNG(partialFile)
        error('CBSPairGuide:InvalidSupplementPNG', ...
            'Rendered PNG failed validation: %s',partialFile);
    end
    atomicReplace(partialFile,outputFile, ...
        'CBSPairGuide:SupplementPNGMoveFailed');
    clear cleanup;
end

function H = drawLayers(Ax,S,C)
    hRaw = scatter3(Ax,S.rawObjs(:,1),S.rawObjs(:,2), ...
        S.rawObjs(:,3),3,C.raw,'filled','o', ...
        'MarkerFaceAlpha',0.33,'MarkerEdgeColor','none');
    hP1 = scatter3(Ax,S.population1Objs(:,1), ...
        S.population1Objs(:,2),S.population1Objs(:,3), ...
        7,C.p1,'filled','o','MarkerFaceAlpha',0.72, ...
        'MarkerEdgeColor','none');
    hP2 = scatter3(Ax,S.population2Objs(:,1), ...
        S.population2Objs(:,2),S.population2Objs(:,3), ...
        8,C.p2,'filled','^','MarkerFaceAlpha',0.72, ...
        'MarkerEdgeColor','none');
    hTarget = scatter3(Ax,S.targetObjs(:,1),S.targetObjs(:,2), ...
        S.targetObjs(:,3),17,C.target,'filled','v', ...
        'MarkerEdgeColor',[0.1,0.1,0.1],'LineWidth',0.25);
    hCenter = plot3(Ax,S.centerObjs(:,1),S.centerObjs(:,2), ...
        S.centerObjs(:,3),'x','Color',C.center,'MarkerSize',3.5, ...
        'LineWidth',0.75);
    hGuided = scatter3(Ax,S.guidedObjs(:,1),S.guidedObjs(:,2), ...
        S.guidedObjs(:,3),19,C.guided,'filled','d', ...
        'MarkerEdgeColor',[0.1,0.1,0.1],'LineWidth',0.3);
    H = [hP1,hP2,hRaw,hTarget,hCenter,hGuided];
end

function setView(Ax,View)
    xlim(Ax,[View.lower(1),View.upper(1)]);
    ylim(Ax,[View.lower(2),View.upper(2)]);
    zlim(Ax,[View.lower(3),View.upper(3)]);
    axis(Ax,'vis3d');
    view(Ax,42,25);
    Ax.Projection = 'orthographic';
end

function styleAxes(Ax,arm,snapshot)
    grid(Ax,'on');
    box(Ax,'on');
    Ax.FontName = 'Helvetica';
    Ax.FontSize = 5;
    Ax.LineWidth = 0.45;
    Ax.Clipping = 'on';
    if arm == 3
        xlabel(Ax,'f_1','Interpreter','tex','FontSize',6);
    end
    if snapshot == 1
        ylabel(Ax,'f_2','Interpreter','tex','FontSize',6);
        zlabel(Ax,'f_3','Interpreter','tex','FontSize',6);
    end
end

function C = figureColors()
    C = struct('feasible',[0.36,0.72,0.47], ...
        'infeasible',[0.90,0.43,0.40], ...
        'p1',[0.48,0.20,0.72],'p2',[0.00,0.58,0.62], ...
        'raw',[0.13,0.43,0.82],'target',[0.86,0.20,0.58], ...
        'center',[0.08,0.08,0.08],'guided',[1.00,0.66,0.12]);
end

function Source = resolveResultFile(Source,stageDir)
    if exist(Source,'file') == 2
        return;
    end
    candidate = fullfile(stageDir,Source);
    if exist(candidate,'file') == 2
        Source = candidate;
    end
end

function assertFrozenSources(rootPath,Frozen)
    required = {'files','combinedSHA256'};
    if ~isstruct(Frozen) || ~isscalar(Frozen) || ...
            ~all(isfield(Frozen,required)) || numel(Frozen.files) ~= 7
        error('CBSPairGuide:BadSupplementFrozenFingerprint', ...
            'Campaign source fingerprint is invalid.');
    end
    for i = 1 : numel(Frozen.files)
        source = fullfile(rootPath,char(Frozen.files(i).relativePath));
        requireFile(source,'frozen campaign source');
        if sha256File(source) ~= string(Frozen.files(i).sha256)
            error('CBSPairGuide:SupplementFrozenSourceChanged', ...
                'Frozen campaign source changed: %s',source);
        end
    end
end

function writeManifestAtomic(manifestMAT,manifestCSV,Summary,Figures, ...
        SupplementManifest,Inputs)
    partialMAT = [manifestMAT,'.partial.mat'];
    partialCSV = [manifestCSV,'.partial.csv'];
    save(partialMAT,'Summary','Figures','SupplementManifest','Inputs');
    writetable(SupplementManifest,partialCSV);
    atomicReplace(partialMAT,manifestMAT, ...
        'CBSPairGuide:SupplementManifestMATMoveFailed');
    atomicReplace(partialCSV,manifestCSV, ...
        'CBSPairGuide:SupplementManifestCSVMoveFailed');
end

function atomicReplace(source,destination,errorId)
    [moved,message] = movefile(source,destination,'f');
    if ~moved
        error(errorId,'%s',message);
    end
end

function valid = validPNG(file)
    valid = false;
    if exist(file,'file') ~= 2
        return;
    end
    try
        Info = imfinfo(file);
        valid = strcmpi(Info.Format,'png') && ...
            Info.Width >= 3800 && Info.Height >= 1500;
    catch
        valid = false;
    end
end

function textValue = commaNumber(value)
    textValue = regexprep(sprintf('%.0f',value), ...
        '(?<!\d)(\d{1,3})(?=(\d{3})+(?!\d))','$1,');
end

function value = numberList(values)
    value = strjoin(compose('%.15g',double(values(:)')),',');
end

function digest = sha256File(file)
    engine = java.security.MessageDigest.getInstance('SHA-256');
    fid = fopen(file,'rb');
    if fid < 0
        error('CBSPairGuide:SupplementHashReadFailed', ...
            'Cannot read file for hashing: %s',file);
    end
    cleanup = onCleanup(@()fclose(fid));
    while true
        bytes = fread(fid,1024*1024,'*uint8');
        if isempty(bytes)
            break;
        end
        engine.update(typecast(bytes(:),'int8'));
    end
    clear cleanup;
    bytes = typecast(engine.digest(),'uint8');
    digest = string(lower(reshape(dec2hex(bytes,2).',1,[])));
end

function requireFile(file,description)
    if exist(file,'file') ~= 2
        error('CBSPairGuide:MissingSupplementFile', ...
            'Missing %s: %s',description,file);
    end
end

function ensureFolder(folder)
    if ~isfolder(folder)
        mkdir(folder);
    end
end
