function OutputFile = run_CBS_CGAN_cutoff_diagnostic_task( ...
        rootPath,Task,Protocol)
%RUN_CBS_CGAN_CUTOFF_DIAGNOSTIC_TASK Execute one fixed-seed cutoff task.

    rootPath = char(rootPath);
    cd(rootPath);
    addCBSPaths(rootPath);
    try
        maxNumCompThreads(1);
    catch
    end

    rng(double(Task.seed),'twister');
    problemConstructor = str2func(char(Task.problem));
    Problem = problemConstructor('N',Protocol.popSize, ...
        'D',Protocol.dimension,'maxFE',Protocol.maxFE, ...
        'maxRuntime',Inf);
    algorithmConstructor = str2func(char(Task.className));
    arguments = {'save',1,'run',double(Task.seed), ...
        'outputFcn',@silentOutput};
    if ~isempty(Task.parameters)
        arguments = [{'parameter'},{Task.parameters},arguments];
    end
    Algorithm = algorithmConstructor(arguments{:});
    Algorithm.configureCutoffDiagnostics(struct( ...
        'enabled',true,'stopAtCGANEnd',true, ...
        'disableOracleAudit',true));

    started = datetime('now','TimeZone','local');
    wallClock = tic;
    Algorithm.Solve(Problem);
    elapsed = toc(wallClock);
    terminalRNG = rng;
    Audit = Algorithm.guideExperimentSnapshot();
    if isempty(Algorithm.result)
        error('CBSRegionGAN:MissingCutoffPopulation', ...
            'The cutoff run did not save a population.');
    end
    savedFE = double(Algorithm.result{end,1});
    Population = Algorithm.result{end,2};
    CutoffPopulation = struct('decs',double(Population.decs), ...
        'objs',double(Population.objs),'cons',double(Population.cons));
    validateTaskResult(Task,Protocol,Problem,savedFE, ...
        CutoffPopulation,Audit);

    Record = struct('schemaVersion',Protocol.schemaVersion, ...
        'status',"ok",'phase',string(Task.phase), ...
        'arm',string(Task.arm),'className',string(Task.className), ...
        'parameters',{Task.parameters},'problem',string(Task.problem), ...
        'seed',double(Task.seed),'N',double(Protocol.popSize), ...
        'D',double(Protocol.dimension),'M',double(Problem.M), ...
        'maxFE',double(Protocol.maxFE),'cutoffTarget',0.5*Protocol.maxFE, ...
        'cutoffFE',double(Audit.cganEndFE), ...
        'startedAt',string(started),'finishedAt',string(datetime('now')), ...
        'wallClockSeconds',elapsed, ...
        'algorithmRuntimeSeconds',double(Algorithm.metric.runtime), ...
        'terminalRNG',terminalRNG);

    OutputFile = char(Task.outputFile);
    outputDir = fileparts(OutputFile);
    if ~isfolder(outputDir)
        mkdir(outputDir);
    end
    partialFile = [OutputFile,'.partial.mat'];
    save(partialFile,'Record','Audit','CutoffPopulation','-v7.3');
    [complete,message] = validateSavedFile( ...
        partialFile,Task,Protocol);
    if ~complete
        error('CBSRegionGAN:InvalidCutoffResult', ...
            'Saved cutoff result failed validation: %s',message);
    end
    [moved,message] = movefile(partialFile,OutputFile,'f');
    if ~moved
        error('CBSRegionGAN:CutoffResultMoveFailed','%s',message);
    end
end

function validateTaskResult(Task,Protocol,Problem,savedFE,Population,Audit)
    missing = Protocol.requiredAuditFields( ...
        ~isfield(Audit,Protocol.requiredAuditFields));
    if ~isempty(missing)
        error('CBSRegionGAN:MissingCutoffDiagnostics', ...
            'Missing audit fields: %s',join(missing,','));
    end
    target = 0.5*double(Protocol.maxFE);
    if Problem.maxRuntime ~= Inf || Problem.FE ~= Audit.cganEndFE || ...
            savedFE ~= Audit.cganEndFE || Audit.cganEndFE < target || ...
            Audit.cganEndFE >= Protocol.maxFE
        error('CBSRegionGAN:BadCutoffFE', ...
            'The task did not stop at the first stored CGAN-end population.');
    end
    if size(Population.decs,1) ~= Protocol.popSize || ...
            size(Population.decs,2) ~= Protocol.dimension || ...
            ~isequal(Population.decs,double(Audit.cganEndDecs)) || ...
            ~isequal(Population.objs,double(Audit.cganEndObjs)) || ...
            ~isequal(Population.cons,double(Audit.cganEndCons))
        error('CBSRegionGAN:BadCutoffPopulation', ...
            'Saved and diagnosed cutoff populations differ.');
    end
    if ~isfield(Audit,'rawOracleCount') || Audit.rawOracleCount ~= 0 || ...
            ~isfield(Audit,'selectedTargetCount') || ...
            Audit.selectedTargetCount ~= 0
        error('CBSRegionGAN:OracleAuditLeak', ...
            'A generated decision was oracle-evaluated in the new protocol.');
    end
    if string(Audit.diagnosticSchemaVersion) ~= "CBS-CGAN-cutoff-v1"
        error('CBSRegionGAN:BadDiagnosticSchema', ...
            'Unexpected diagnostic schema version.');
    end
    if string(Task.problem) ~= string(class(Problem))
        error('CBSRegionGAN:WrongProblem','Task problem identity changed.');
    end
end

function [complete,message] = validateSavedFile(file,Task,Protocol)
    complete = false;
    message = "missing";
    if exist(file,'file') ~= 2
        return;
    end
    try
        Data = load(file,'Record','Audit','CutoffPopulation');
        required = {'Record','Audit','CutoffPopulation'};
        if ~all(isfield(Data,required))
            message = "top-level schema";
            return;
        end
        R = Data.Record;
        A = Data.Audit;
        P = Data.CutoffPopulation;
        identity = string(R.schemaVersion) == Protocol.schemaVersion && ...
            string(R.phase) == string(Task.phase) && ...
            string(R.arm) == string(Task.arm) && ...
            string(R.className) == string(Task.className) && ...
            string(R.problem) == string(Task.problem) && ...
            double(R.seed) == double(Task.seed) && ...
            double(R.N) == Protocol.popSize && ...
            double(R.D) == Protocol.dimension && ...
            double(R.maxFE) == Protocol.maxFE;
        diagnosticFields = all(isfield(A,Protocol.requiredAuditFields));
        populationShape = size(P.decs,1) == Protocol.popSize && ...
            size(P.decs,2) == Protocol.dimension && ...
            isequal(double(P.decs),double(A.cganEndDecs)) && ...
            isequal(double(P.objs),double(A.cganEndObjs)) && ...
            isequal(double(P.cons),double(A.cganEndCons));
        cutoff = double(A.cganEndFE) >= 0.5*Protocol.maxFE && ...
            double(A.cganEndFE) < Protocol.maxFE && ...
            double(R.cutoffFE) == double(A.cganEndFE);
        oracleFree = isfield(A,'rawOracleCount') && ...
            A.rawOracleCount == 0 && isfield(A,'selectedTargetCount') && ...
            A.selectedTargetCount == 0;
        complete = identity && diagnosticFields && populationShape && ...
            cutoff && oracleFree;
        if complete
            message = "ok";
        else
            message = "identity, diagnostic, population, cutoff, or oracle check";
        end
    catch err
        message = string(err.message);
    end
end

function silentOutput(~,~)
end
