function BranchSummary = run_CBS_RegionWGAN_GP_qw_plan_branches( ...
        rootOutDir,stageName,branchNames,workerCount)
%RUN_CBS_REGIONWGAN_GP_QW_PLAN_BRANCHES Run no-figure Query/WGAN branches.
%   All branches use: LIRCMOP5_BC..LIRCMOP10_BC, runs=1:3, N=100,
%   default D, maxFE=100000, workerCount workers, capture run=3 stage
%   snapshots at [10000 30000 50000 70000 100000], and draw no figures.

    repoRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
    addpath(genpath(repoRoot));
    if nargin < 1 || isempty(rootOutDir)
        rootOutDir = fullfile(repoRoot,'Data','CBS_RegionGAN_compare', ...
            ['qw_plan_noplot_',char(datetime('now','Format','yyyyMMdd_HHmmss'))]);
    end
    if nargin < 2 || isempty(stageName)
        stageName = "stage1";
    end
    if nargin < 3 || isempty(branchNames)
        branchNames = ["baseline_random_iter50", ...
            "query_boundary_iter50", ...
            "random_iter100", ...
            "query_boundary_iter100"];
    end
    if nargin < 4 || isempty(workerCount)
        workerCount = 8;
    end

    stageName = string(stageName);
    branchNames = string(branchNames(:)');
    stageDir = fullfile(rootOutDir,char(stageName));
    if ~isfolder(stageDir)
        mkdir(stageDir);
    end

    problems = ["LIRCMOP5_BC";"LIRCMOP6_BC";"LIRCMOP7_BC"; ...
        "LIRCMOP8_BC";"LIRCMOP9_BC";"LIRCMOP10_BC"];
    stageTargets = [10000 30000 50000 70000 100000];
    runIds = 1 : 3;
    N = 100;
    D = [];
    maxFE = 100000;

    Branches = branchSpecs();
    Rows = repmat(emptyBranchRow(),numel(branchNames),1);
    for i = 1 : numel(branchNames)
        name = branchNames(i);
        if ~isfield(Branches,char(name))
            error('CBSRegionWGAN:UnknownQWBranch', ...
                'Unknown Query/WGAN branch: %s.',name);
        end
        Branch = Branches.(char(name));
        outDir = fullfile(stageDir,char(name));
        Rows(i) = branchRowFromSpec(Branch,outDir);
        if branchComplete(outDir,numel(problems),numel(runIds), ...
                numel(stageTargets))
            Rows(i).status = "skipped_complete";
            Rows(i) = fillBranchCounts(Rows(i),outDir);
            fprintf('[%s %d/%d] %s already complete, skipped.\n', ...
                char(stageName),i,numel(branchNames),char(name));
            continue;
        end
        fprintf('[%s %d/%d] running %s -> %s\n',char(stageName),i, ...
            numel(branchNames),char(name),outDir);
        try
            Options = struct( ...
                'algorithmClass',"CBS_RegionWGAN_GP", ...
                'queryMode',Branch.queryMode, ...
                'prevBMemMode',"prev1_fair_union", ...
                'bmemBandMode',Branch.bmemBandMode, ...
                'bandMaxAnchorsPerRef',Branch.bandMaxAnchorsPerRef, ...
                'captureRun',3, ...
                'plotRun',0, ...
                'drawFigures',false, ...
                'stageTargets',stageTargets, ...
                'algorithmParams',{wganParams(Branch)}, ...
                'sampleZMode',Branch.sampleZMode, ...
                'trainZMode',Branch.trainZMode, ...
                'sigma',Branch.sigma, ...
                'trainSigma',Branch.trainSigma, ...
                'sampleSigma',Branch.sampleSigma, ...
                'ganIterSchedule',Branch.ganIterSchedule, ...
                'ganIterStart',Branch.ganIterStart, ...
                'ganIterEnd',Branch.ganIterEnd, ...
                'prescreenMultiplier',Branch.prescreenMultiplier);
            run_CBS_RegionCGAN_training_diagnostics(outDir,workerCount, ...
                problems,N,D,maxFE,runIds,Options);
            Rows(i).status = "ok";
            Rows(i) = fillBranchCounts(Rows(i),outDir);
        catch err
            Rows(i).status = "failed";
            Rows(i).error_message = string(getReport(err,'extended', ...
                'hyperlinks','off'));
            fprintf('[%s %d/%d] %s failed:\n%s\n',char(stageName),i, ...
                numel(branchNames),char(name),char(Rows(i).error_message));
        end
        BranchSummary = struct2table(Rows);
        writetable(BranchSummary,fullfile(stageDir,'branch_summary.csv'));
    end
    BranchSummary = struct2table(Rows);
    writetable(BranchSummary,fullfile(stageDir,'branch_summary.csv'));
    fprintf('Query/WGAN branches written to: %s\n',stageDir);
end

function Branches = branchSpecs()
    Defaults = CBS_RegionWGAN_GP.mainlineDefaults();
    Base = struct( ...
        'name',"", ...
        'queryMode',Defaults.queryMode, ...
        'ganIter',Defaults.ganIter, ...
        'zDim',Defaults.zDim, ...
        'nCritic',Defaults.nCritic, ...
        'sampleZMode',"random", ...
        'trainZMode',"random", ...
        'sigma',1.0, ...
        'trainSigma',[], ...
        'sampleSigma',Defaults.sampleSigma, ...
        'ganIterSchedule',"fixed", ...
        'ganIterStart',[], ...
        'ganIterEnd',[], ...
        'prescreenMultiplier',1, ...
        'bmemBandMode',Defaults.bmemBandMode, ...
        'bandMaxAnchorsPerRef',Defaults.bandMaxAnchorsPerRef);

    Branches = struct();
    Branches.baseline_random_iter50 = withFields(Base, ...
        "baseline_random_iter50","random_all_w",50,5);
    Branches.query_boundary_iter50 = withFields(Base, ...
        "query_boundary_iter50","boundary_populated",50,5);
    Branches.query_boundary_iter50_z_zero = withFixedIterZ(Base, ...
        "query_boundary_iter50_z_zero","boundary_populated",50, ...
        "zero",[],Defaults.zDim);
    Branches.query_boundary_iter50_z_sigma025 = withFixedIterZ(Base, ...
        "query_boundary_iter50_z_sigma025","boundary_populated",50, ...
        "random",0.25,Defaults.zDim);
    Branches.query_boundary_iter50_z_sigma03 = withFixedIterZ(Base, ...
        "query_boundary_iter50_z_sigma03","boundary_populated",50, ...
        "random",0.3,Defaults.zDim);
    Branches.query_boundary_iter50_z_sigma015 = withFixedIterZ(Base, ...
        "query_boundary_iter50_z_sigma015","boundary_populated",50, ...
        "random",0.15,Defaults.zDim);
    Branches.query_boundary_iter50_z_sigma05 = withFixedIterZ(Base, ...
        "query_boundary_iter50_z_sigma05","boundary_populated",50, ...
        "random",0.5,Defaults.zDim);
    Branches.query_boundary_iter50_sigma03_zdim4 = withFixedIterZ(Base, ...
        "query_boundary_iter50_sigma03_zdim4","boundary_populated",50, ...
        "random",Defaults.sampleSigma,4);
    Branches.query_boundary_iter50_sigma03_zdim8 = withFixedIterZ(Base, ...
        "query_boundary_iter50_sigma03_zdim8","boundary_populated",50, ...
        "random",Defaults.sampleSigma,8);
    Branches.query_boundary_iter50_zdim2 = withFixedIterZ(Base, ...
        "query_boundary_iter50_zdim2","boundary_populated",50, ...
        "random",1.0,2);
    Branches.query_boundary_iter50_zdim3 = withFixedIterZ(Base, ...
        "query_boundary_iter50_zdim3","boundary_populated",50, ...
        "random",1.0,3);
    Branches.random_iter100 = withFields(Base, ...
        "random_iter100","random_all_w",100,5);
    Branches.query_boundary_iter100 = withFields(Base, ...
        "query_boundary_iter100","boundary_populated",100,5);
    Branches.query_boundary_iter75 = withFields(Base, ...
        "query_boundary_iter75","boundary_populated",75,5);
    Branches.query_boundary_iter150 = withFields(Base, ...
        "query_boundary_iter150","boundary_populated",150,5);
    Branches.bmem_current_random_iter50 = withBMemFields(Base, ...
        "bmem_current_random_iter50","random_all_w",50,5,"current",[]);
    Branches.bmem_pfseed_band_random_iter50 = withBMemFields(Base, ...
        "bmem_pfseed_band_random_iter50","random_all_w",50,5, ...
        "pfseed_band",3);
    Branches.bmem_pfseed_band_mincover_random_iter50 = withBMemFields(Base, ...
        "bmem_pfseed_band_mincover_random_iter50","random_all_w",50,5, ...
        "pfseed_band_mincover",3);
    Branches.bmem_pfseed_multiband_safety_random_iter50 = withBMemFields( ...
        Base,"bmem_pfseed_multiband_safety_random_iter50", ...
        "random_all_w",50,5,"pfseed_multiband_safety",4);
    Branches.linear_iter = withLinearIter(Base, ...
        "linear_iter","boundary_populated");
    Branches.linear_iter_z_sigma025 = withLinearIterZ(Base, ...
        "linear_iter_z_sigma025","random",0.25,Defaults.zDim);
    Branches.linear_iter_z_sigma05 = withLinearIterZ(Base, ...
        "linear_iter_z_sigma05","random",0.5,Defaults.zDim);
    Branches.linear_iter_z_zero = withLinearIterZ(Base, ...
        "linear_iter_z_zero","zero",1.0,Defaults.zDim);
    Branches.linear_iter_zdim2 = withLinearIterZ(Base, ...
        "linear_iter_zdim2","random",1.0,2);
    Branches.linear_iter_zdim3 = withLinearIterZ(Base, ...
        "linear_iter_zdim3","random",1.0,3);
    Branches.linear_iter_prescreen4 = withLinearIter(Base, ...
        "linear_iter_prescreen4","boundary_populated");
    Branches.linear_iter_prescreen4.prescreenMultiplier = 4;
end

function S = withFields(Base,name,queryMode,ganIter,nCritic)
    S = Base;
    S.name = string(name);
    S.queryMode = string(queryMode);
    S.ganIter = double(ganIter);
    S.nCritic = double(nCritic);
end

function S = withBMemFields(Base,name,queryMode,ganIter,nCritic, ...
        bmemBandMode,bandMaxAnchorsPerRef)
    S = withFields(Base,name,queryMode,ganIter,nCritic);
    S.bmemBandMode = string(bmemBandMode);
    S.bandMaxAnchorsPerRef = bandMaxAnchorsPerRef;
end

function S = withLinearIter(Base,name,queryMode)
    S = withFields(Base,name,queryMode,Base.ganIter,Base.nCritic);
    S.ganIterSchedule = "linear_fe";
    S.ganIterStart = 150;
    S.ganIterEnd = 30;
end

function S = withLinearIterZ(Base,name,sampleZMode,sigma,zDim)
    S = withLinearIter(Base,name,"boundary_populated");
    S.sampleZMode = string(sampleZMode);
    S.trainSigma = 1.0;
    S.sampleSigma = double(sigma);
    S.zDim = max(1,round(double(zDim)));
end

function S = withFixedIterZ(Base,name,queryMode,ganIter,sampleZMode, ...
        sampleSigma,zDim)
    S = withFields(Base,name,queryMode,ganIter,Base.nCritic);
    S.trainZMode = "random";
    S.sampleZMode = string(sampleZMode);
    S.trainSigma = 1.0;
    if isempty(sampleSigma)
        S.sampleSigma = [];
    else
        S.sampleSigma = double(sampleSigma);
    end
    S.zDim = max(1,round(double(zDim)));
end

function Params = wganParams(Branch)
    Defaults = CBS_RegionWGAN_GP.mainlineDefaults();
    Params = { ...
        Defaults.trainGap, ...
        Defaults.archiveGap, ...
        Defaults.nGen, ...
        Branch.zDim, ...
        Branch.ganIter, ...
        Defaults.ganMiniBatch, ...
        Defaults.ganLrD, ...
        Defaults.ganLrG, ...
        Defaults.frontDepth, ...
        Defaults.pairNeighborRefRadius, ...
        Defaults.refDivisor, ...
        Defaults.minBoundaryLength, ...
        Defaults.queryPerCondition, ...
        Defaults.gpLambda, ...
        Branch.nCritic, ...
        Defaults.maxAnchorsPerRef, ...
        Defaults.minGANTrainCount};
end

function Row = branchRowFromSpec(Branch,outDir)
    Row = emptyBranchRow();
    Row.branch = Branch.name;
    Row.status = "pending";
    Row.out_dir = string(outDir);
    Row.query_mode = Branch.queryMode;
    Row.gan_iter = double(Branch.ganIter);
    Row.z_dim = double(Branch.zDim);
    Row.n_critic = double(Branch.nCritic);
    Row.sample_z_mode = Branch.sampleZMode;
    Row.train_z_mode = Branch.trainZMode;
    Row.sigma = double(Branch.sigma);
    Row.train_sigma = doubleOrNaN(Branch.trainSigma);
    Row.sample_sigma = doubleOrNaN(Branch.sampleSigma);
    Row.gan_iter_schedule = Branch.ganIterSchedule;
    Row.gan_iter_start = doubleOrNaN(Branch.ganIterStart);
    Row.gan_iter_end = doubleOrNaN(Branch.ganIterEnd);
    Row.prescreen_multiplier = double(Branch.prescreenMultiplier);
    Row.bmem_band_mode = Branch.bmemBandMode;
    if isempty(Branch.bandMaxAnchorsPerRef)
        Row.band_max_anchors_per_ref = NaN;
    else
        Row.band_max_anchors_per_ref = double(Branch.bandMaxAnchorsPerRef);
    end
end

function yes = branchComplete(outDir,problemCount,runCount,stageCount)
    summaryFile = fullfile(outDir,'run_summary.csv');
    stageFile = fullfile(outDir,'stage_snapshots_all.csv');
    yes = isfile(summaryFile) && isfile(stageFile) && ...
        countTableRows(summaryFile) == problemCount*runCount && ...
        countOkRunRows(summaryFile) == problemCount*runCount && ...
        countTableRows(stageFile) == problemCount*stageCount;
end

function Row = fillBranchCounts(Row,outDir)
    Row.run_count = countTableRows(fullfile(outDir,'run_summary.csv'));
    Row.ok_run_count = countOkRunRows(fullfile(outDir,'run_summary.csv'));
    Row.stage_snapshot_count = countTableRows(fullfile(outDir, ...
        'stage_snapshots_all.csv'));
    Row.figure_count = numel(dir(fullfile(outDir,'domain_figures_all', ...
        '*domain_boundary.png')));
end

function n = countTableRows(file)
    n = 0;
    if ~isfile(file)
        return;
    end
    fid = fopen(file,'r');
    cleanup = onCleanup(@()fclose(fid));
    while true
        line = fgetl(fid);
        if ~ischar(line)
            break;
        end
        if strlength(string(strtrim(line))) > 0
            n = n + 1;
        end
    end
    n = max(0,n - 1);
end

function n = countOkRunRows(file)
    n = 0;
    if ~isfile(file)
        return;
    end
    fid = fopen(file,'r');
    cleanup = onCleanup(@()fclose(fid));
    header = fgetl(fid);
    if ~ischar(header)
        return;
    end
    names = split(string(header),",");
    statusIdx = find(strcmpi(names,"status"),1);
    if isempty(statusIdx)
        statusIdx = 11;
    end
    while true
        line = fgetl(fid);
        if ~ischar(line)
            break;
        end
        parts = split(string(line),",");
        if numel(parts) >= statusIdx && parts(statusIdx) == "ok"
            n = n + 1;
        end
    end
end

function Row = emptyBranchRow()
    Row = struct( ...
        'branch',"", ...
        'status',"pending", ...
        'out_dir',"", ...
        'query_mode',"", ...
        'gan_iter',NaN, ...
        'z_dim',NaN, ...
        'n_critic',NaN, ...
        'sample_z_mode',"", ...
        'train_z_mode',"", ...
        'sigma',NaN, ...
        'train_sigma',NaN, ...
        'sample_sigma',NaN, ...
        'gan_iter_schedule',"", ...
        'gan_iter_start',NaN, ...
        'gan_iter_end',NaN, ...
        'prescreen_multiplier',NaN, ...
        'bmem_band_mode',"", ...
        'band_max_anchors_per_ref',NaN, ...
        'run_count',0, ...
        'ok_run_count',0, ...
        'stage_snapshot_count',0, ...
        'figure_count',0, ...
        'error_message',"");
end

function value = doubleOrNaN(x)
    if isempty(x)
        value = NaN;
    else
        value = double(x);
        if isempty(value) || ~isfinite(value(1))
            value = NaN;
        else
            value = value(1);
        end
    end
end
