function [Summary,EventSummaryAll,TrainHistoryAll,outDir, ...
    StageSnapshotsAll] = run_CBS_RegionWGAN_GP_mainline( ...
    outDir,workerCount, ...
    problemNames,N,D,maxFE,runIds,Options)
%RUN_CBS_REGIONWGAN_GP_MAINLINE Run the sole CBS RegionWGAN-GP mainline.
%   The runner is intentionally non-visual. It records reproducibility,
%   training, boundary geometry, query attribution, and final populations.

    rootDir = locateRootDir();
    addpath(genpath(rootDir));
    if nargin < 1 || isempty(outDir)
        outDir = fullfile(rootDir,'Data','CBS_RegionGAN_compare', ...
            ['mainline_', ...
            char(datetime('now','Format','yyyyMMdd_HHmmss'))]);
    end
    if nargin < 2 || isempty(workerCount)
        workerCount = 10;
    end
    if nargin < 3 || isempty(problemNames)
        problemNames = ["LIRCMOP5_BC";"LIRCMOP6_BC";"LIRCMOP7_BC"; ...
            "LIRCMOP8_BC";"LIRCMOP9_BC";"LIRCMOP10_BC"];
    end
    if nargin < 4 || isempty(N)
        N = 100;
    end
    if nargin < 5
        D = [];
    end
    if nargin < 6 || isempty(maxFE)
        maxFE = 100000;
    end
    if nargin < 7 || isempty(runIds)
        runIds = 1 : 3;
    end
    if nargin < 8 || isempty(Options)
        Options = struct();
    end
    Options = normalizeDiagnosticOptions(Options);

    workerCount = max(1,round(double(workerCount)));
    if ischar(problemNames)
        problemNames = string(problemNames);
    else
        problemNames = string(problemNames(:));
    end
    runIds = double(runIds(:)');
    N = max(1,round(double(N)));
    maxFE = max(1,round(double(maxFE)));

    if ~isfolder(outDir)
        mkdir(outDir);
    end
    Provenance = CBS_RegionGAN_Provenance(rootDir,Options,workerCount);
    writetable(provenanceScalarTable(Provenance), ...
        fullfile(outDir,'provenance.csv'));
    writetable(Provenance.source_manifest, ...
        fullfile(outDir,'source_manifest.csv'));
    Tasks = buildDiagnosticTasks(problemNames,runIds);
    taskCount = height(Tasks);
    taskProblems = Tasks.problem;
    taskRuns = Tasks.run;
    Rows = repmat(emptyRunRow(),taskCount,1);

    if workerCount > 1
        ensureDiagnosticParallelPool(workerCount);
        doneCount = 0;
        progressQueue = parallel.pool.DataQueue;
        afterEach(progressQueue,@reportProgress);
        parfor task = 1 : taskCount
            Rows(task) = runOneDiagnosticTask(taskProblems(task), ...
                taskRuns(task),outDir,N,D,maxFE,Options,Provenance);
            send(progressQueue,Rows(task));
        end
    else
        for task = 1 : taskCount
            Rows(task) = runOneDiagnosticTask(taskProblems(task), ...
                taskRuns(task),outDir,N,D,maxFE,Options,Provenance);
            fprintf('[%d/%d] %s run=%d status=%s\n',task,taskCount, ...
                char(Rows(task).problem),Rows(task).run,char(Rows(task).status));
        end
    end

    Summary = struct2table(Rows);
    writetable(Summary,fullfile(outDir,'run_summary.csv'));
    EventSummaryAll = collectDiagnosticTables( ...
        Summary.event_summary_file,emptyEventRow());
    writetable(EventSummaryAll,fullfile(outDir,'event_summary_all.csv'));
    TrainHistoryAll = collectDiagnosticTables( ...
        Summary.train_history_file,emptyTrainRow());
    writetable(TrainHistoryAll,fullfile(outDir,'train_history_all.csv'));
    StageSnapshotsAll = collectDiagnosticTables( ...
        Summary.stage_snapshot_file,emptyStageSnapshotRow());
    writetable(StageSnapshotsAll,fullfile(outDir,'stage_snapshots_all.csv'));
    BMemHistoryAll = collectHomogeneousDiagnosticTables( ...
        Summary.bmem_history_file);
    writetable(BMemHistoryAll,fullfile(outDir,'bmem_history_all.csv'));
    BMemRefHistoryAll = collectHomogeneousDiagnosticTables( ...
        Summary.bmem_ref_history_file);
    writetable(BMemRefHistoryAll, ...
        fullfile(outDir,'bmem_ref_history_all.csv'));
    LatentScaleRefHistoryAll = collectHomogeneousDiagnosticTables( ...
        Summary.latent_scale_ref_history_file);
    writetable(LatentScaleRefHistoryAll, ...
        fullfile(outDir,'latent_scale_ref_history_all.csv'));

    function reportProgress(Row)
        doneCount = doneCount + 1;
        fprintf('[%d/%d] %s run=%d status=%s\n',doneCount,taskCount, ...
            char(Row.problem),Row.run,char(Row.status));
    end
end

function rootDir = locateRootDir()
    rootDir = fileparts(which('platemo'));
    if isempty(rootDir)
        rootDir = pwd;
    end
end

function Options = normalizeDiagnosticOptions(Options)
    Options = defaultOption(Options,'algorithmParams',{});
    Options = defaultOption(Options,'captureRun',0);
    Options = defaultOption(Options,'stageTargets',[]);
    Options = defaultOption(Options,'captureWGANTrainHistory',false);
    Options = defaultOption(Options,'wganMappingDiagnostics',false);
    Options = defaultOption(Options,'bmemLearnabilityDiagnostics',false);
    Options = defaultOption(Options,'bmemMode',"legacy");
    Options = defaultOption(Options,'trainDedupMode',"off");
    Options = defaultOption(Options,'mappingDiagMaxConditions',8);
    Options = defaultOption(Options,'mappingDiagZSamples',8);
    Options = defaultOption(Options,'structuredZMode',"off");
    Options = defaultOption(Options,'structuredZMaxModes',5);
    Options = defaultOption(Options,'structuredZLambda',1.0);
    Options = defaultOption(Options,'schemaVersion', ...
        "cbs_region_wgan_mainline_v1");
    Options.captureRun = unique(round(double(Options.captureRun(:)')), ...
        'stable');
    Options.stageTargets = double(Options.stageTargets(:)');
    Options.captureWGANTrainHistory = logical( ...
        Options.captureWGANTrainHistory);
    Options.wganMappingDiagnostics = logical( ...
        Options.wganMappingDiagnostics);
    Options.bmemLearnabilityDiagnostics = logical( ...
        Options.bmemLearnabilityDiagnostics);
    Options.bmemMode = lower(strip(string(Options.bmemMode)));
    if ~isscalar(Options.bmemMode) || ...
            ~ismember(Options.bmemMode,["legacy","coherent"])
        error('CBSRegionGAN:BadBMemMode', ...
            'Options.bmemMode must be "legacy" or "coherent".');
    end
    Options.trainDedupMode = lower(strip(string(Options.trainDedupMode)));
    if ~isscalar(Options.trainDedupMode) || ...
            ~ismember(Options.trainDedupMode,["off","exact_ref_x"])
        error('CBSRegionGAN:BadTrainDedupMode', ...
            'Options.trainDedupMode must be "off" or "exact_ref_x".');
    end
    Options.mappingDiagMaxConditions = max(1,round(double( ...
        Options.mappingDiagMaxConditions)));
    Options.mappingDiagZSamples = max(2,round(double( ...
        Options.mappingDiagZSamples)));
    Options.structuredZMode = lower(strip(string( ...
        Options.structuredZMode)));
    if ~isscalar(Options.structuredZMode) || ...
            ~ismember(Options.structuredZMode,["off","categorical_mi"])
        error('CBSRegionGAN:BadStructuredZMode', ...
            'Options.structuredZMode must be "off" or "categorical_mi".');
    end
    Options.structuredZMaxModes = max(1,round(double( ...
        Options.structuredZMaxModes)));
    Options.structuredZLambda = double(Options.structuredZLambda);
    if ~isscalar(Options.structuredZLambda) || ...
            ~isfinite(Options.structuredZLambda) || ...
            Options.structuredZLambda < 0
        error('CBSRegionGAN:BadStructuredZLambda', ...
            'Options.structuredZLambda must be finite and nonnegative.');
    end
    Options.schemaVersion = string(Options.schemaVersion);
end

function S = defaultOption(S,name,value)
    if ~isfield(S,name) || isempty(S.(name))
        S.(name) = value;
    end
end

function Tasks = buildDiagnosticTasks(problemNames,runIds)
    Rows = repmat(struct('problem',"",'run',NaN), ...
        numel(problemNames)*numel(runIds),1);
    row = 0;
    for p = 1 : numel(problemNames)
        for r = 1 : numel(runIds)
            row = row + 1;
            Rows(row).problem = problemNames(p);
            Rows(row).run = runIds(r);
        end
    end
    Tasks = struct2table(Rows);
end

function Row = runOneDiagnosticTask(problemName,runId,outDir,N,D,maxFE, ...
        Options,Provenance)
    Row = emptyRunRow();
    Row.problem = string(problemName);
    Row.run = double(runId);
    Row.seed = double(runId);
    Row.N = double(N);
    Row.maxFE = double(maxFE);
    Row.schema_version = string(Provenance.schema_version);
    Row.git_sha = string(Provenance.git_sha);
    Row.git_branch = string(Provenance.git_branch);
    Row.git_dirty = double(Provenance.git_dirty);
    Row.source_tree_sha256 = string(Provenance.source_tree_sha256);
    try
        rootDir = locateRootDir();
        addpath(genpath(rootDir));
        try
            maxNumCompThreads(1);
        catch
        end
        rng(Row.seed,'twister');
        ProblemConstructor = str2func(char(Row.problem));
        if isempty(D)
            Problem = ProblemConstructor('N',N,'maxFE',maxFE);
        else
            Problem = ProblemConstructor('N',N,'D',D,'maxFE',maxFE);
        end
        Row.D = double(Problem.D);
        Row.M = double(Problem.M);
        runFolder = fullfile(outDir,sprintf('%s_run%d', ...
            char(Row.problem),round(Row.run)));
        if ~isfolder(runFolder)
            mkdir(runFolder);
        end
        Row.run_folder = string(runFolder);
        Row.metric_file = string(fullfile(runFolder,'metric.mat'));
        Row.event_summary_file = string(fullfile(runFolder, ...
            'event_summary.csv'));
        Row.train_history_file = string(fullfile(runFolder, ...
            'train_history.csv'));
        Row.bmem_history_file = string(fullfile(runFolder, ...
            'bmem_history.csv'));
        Row.bmem_ref_history_file = string(fullfile(runFolder, ...
            'bmem_ref_history.csv'));
        Row.latent_scale_ref_history_file = string(fullfile(runFolder, ...
            'latent_scale_ref_history.csv'));
        Row.stage_snapshot_file = string(fullfile(runFolder, ...
            'stage_snapshots.csv'));
        Row.final_p1_file = string(fullfile(runFolder,'final_p1.csv'));
        Row.final_p2_file = string(fullfile(runFolder,'final_p2.csv'));
        Row.final_feasible_nd_file = string(fullfile(runFolder, ...
            'final_feasible_nd.csv'));
        Row.query_samples_file = string(fullfile(runFolder, ...
            'query_samples.csv'));
        Row.query_ref_exposure_file = string(fullfile(runFolder, ...
            'query_ref_exposure.csv'));
        Row.query_ref_conversion_file = string(fullfile(runFolder, ...
            'query_ref_conversion.csv'));
        Row.gan_bmem_eligible_samples_file = string(fullfile(runFolder, ...
            'gan_bmem_eligible_samples.csv'));
        Row.direct_gan_bmem_entry_file = string(fullfile(runFolder, ...
            'direct_gan_bmem_entry.csv'));
        Row.provenance_file = string(fullfile(runFolder,'provenance.csv'));
        Row.source_manifest_file = string(fullfile(runFolder, ...
            'source_manifest.csv'));

        Control = struct( ...
            'stageTargets',[], ...
            'captureWGANTrainHistory', ...
                Options.captureWGANTrainHistory, ...
            'wganMappingDiagnostics',Options.wganMappingDiagnostics, ...
            'bmemLearnabilityDiagnostics', ...
                Options.bmemLearnabilityDiagnostics, ...
            'bmemMode',Options.bmemMode, ...
            'trainDedupMode',Options.trainDedupMode, ...
            'mappingDiagMaxConditions', ...
                Options.mappingDiagMaxConditions, ...
            'mappingDiagZSamples',Options.mappingDiagZSamples);
        Control.structuredZMode = Options.structuredZMode;
        Control.structuredZMaxModes = Options.structuredZMaxModes;
        Control.structuredZLambda = Options.structuredZLambda;
        if ismember(Row.run,Options.captureRun)
            Control.stageTargets = Options.stageTargets;
        end
        setappdata(0,'CBS_RegionGAN_ExperimentControl',Control);
        cleanupControl = onCleanup(@()removeRegionGANExperimentControl());
        if isempty(Options.algorithmParams)
            Algorithm = CBS_RegionWGAN_GP('save',0,'run',Row.run, ...
                'outputFcn',@(varargin)[]);
        else
            Algorithm = CBS_RegionWGAN_GP('save',0,'run',Row.run, ...
                'outputFcn',@(varargin)[], ...
                'parameter',Options.algorithmParams);
        end
        Algorithm.Solve(Problem);
        clear cleanupControl

        Row.runtime = double(Algorithm.metric.runtime);
        Row.finalFE = double(Algorithm.result{end,1});
        metric = Algorithm.metric;
        [Final,Tracker,QuerySamples] = regionAttributionExports(metric);
        exportFinalPopulationTables(Final,Row);
        exportTrackerTables(Tracker,QuerySamples,Row,size(Final.p1_dec,2));
        writetable(provenanceScalarTable(Provenance),Row.provenance_file);
        writetable(Provenance.source_manifest,Row.source_manifest_file);
        Row.query_sample_row_count = size(QuerySamples.rows,1);
        Row.ref_exposure_row_count = numel(Tracker.ref_exposure);
        Row.ref_conversion_row_count = numel(Tracker.ref_conversions);
        Row.gan_bmem_eligible_sample_row_count = numel(Tracker.samples);
        Row.direct_bmem_entry_row_count = numel(Tracker.direct_entries);
        problem = Row.problem;
        run = Row.run;
        seed = Row.seed;
        provenance = Provenance;
        source_manifest = Provenance.source_manifest;
        save(Row.metric_file,'metric','problem','run','seed','N','maxFE', ...
            'provenance','source_manifest');

        if isfield(Algorithm.metric,'region_gan_history')
            History = Algorithm.metric.region_gan_history;
        elseif isfield(Algorithm.metric,'region_wgan_gp_history')
            History = Algorithm.metric.region_wgan_gp_history;
        elseif isfield(Algorithm.metric,'region_cgan_history')
            History = Algorithm.metric.region_cgan_history;
        else
            History = struct([]);
        end
        [EventSummary,TrainHistory] = buildDiagnosticTables(History,Row);
        writetable(EventSummary,Row.event_summary_file);
        writetable(TrainHistory,Row.train_history_file);
        Row.event_count = height(EventSummary);
        Row.train_row_count = height(TrainHistory);
        BMemHistory = getMetricCellHistory( ...
            metric,'region_gan_bmem_history');
        BMemHistoryTable = regionBMemHistoryTable(BMemHistory,Row);
        writetable(BMemHistoryTable,Row.bmem_history_file);
        Row.bmem_history_row_count = height(BMemHistoryTable);
        BMemRefHistory = getMetricCellHistory( ...
            metric,'region_gan_bmem_ref_history');
        BMemRefHistoryTable = regionBMemRefHistoryTable( ...
            BMemRefHistory,Row);
        writetable(BMemRefHistoryTable,Row.bmem_ref_history_file);
        Row.bmem_ref_history_row_count = height(BMemRefHistoryTable);
        LatentScaleRefHistory = getMetricCellHistory( ...
            metric,'region_gan_latent_scale_ref_history');
        LatentScaleRefHistoryTable = regionLatentScaleRefHistoryTable( ...
            LatentScaleRefHistory,Row);
        writetable(LatentScaleRefHistoryTable, ...
            Row.latent_scale_ref_history_file);
        Row.latent_scale_ref_history_row_count = ...
            height(LatentScaleRefHistoryTable);
        if isfield(Algorithm.metric,'region_gan_stage_snapshots')
            Snapshots = Algorithm.metric.region_gan_stage_snapshots;
        else
            Snapshots = emptyRegionStageSnapshotStruct();
        end
        StageSnapshots = regionStageSnapshotTable(Snapshots,Row);
        writetable(StageSnapshots,Row.stage_snapshot_file);
        Row.status = "ok";
    catch err
        removeRegionGANExperimentControl();
        Row.status = "failed";
        Row.error_message = string(getReport(err,'extended', ...
            'hyperlinks','off'));
    end
end

function removeRegionGANExperimentControl()
    if isappdata(0,'CBS_RegionGAN_ExperimentControl')
        rmappdata(0,'CBS_RegionGAN_ExperimentControl');
    end
end

function T = provenanceScalarTable(P)
    T = table( ...
        string(P.schema_version),string(P.git_sha), ...
        string(P.git_branch),logical(P.git_dirty), ...
        string(P.matlab_release),string(P.host), ...
        double(P.worker_count),string(P.options_json), ...
        string(P.source_tree_sha256), ...
        'VariableNames',{'schema_version','git_sha','git_branch', ...
            'git_dirty','matlab_release','host','worker_count', ...
            'options_json','source_tree_sha256'});
end

function [Final,Tracker,QuerySamples] = regionAttributionExports(metric)
    if ~isstruct(metric) || ~isfield(metric,'region_gan_final') || ...
            ~isfield(metric,'region_gan_query_tracker') || ...
            ~isfield(metric,'region_gan_query_samples')
        error('CBSRegionDiagnostics:MissingAttributionMetric', ...
            'Algorithm metric is missing final, tracker, or query samples.');
    end
    Final = metric.region_gan_final;
    Tracker = metric.region_gan_query_tracker;
    QuerySamples = metric.region_gan_query_samples;
end

function exportFinalPopulationTables(Final,Row)
    writetable(populationArraysTable( ...
        Final.p1_dec,Final.p1_obj,Final.p1_con),Row.final_p1_file);
    writetable(populationArraysTable( ...
        Final.p2_dec,Final.p2_obj,Final.p2_con),Row.final_p2_file);
    writetable(populationArraysTable(Final.p1_feasible_nd_dec, ...
        Final.p1_feasible_nd_obj,Final.p1_feasible_nd_con), ...
        Row.final_feasible_nd_file);
end

function T = populationArraysTable(Dec,Obj,Con)
    Dec = double(Dec);
    Obj = double(Obj);
    Con = double(Con);
    n = size(Dec,1);
    if size(Obj,1) ~= n || size(Con,1) ~= n
        error('CBSRegionDiagnostics:BadFinalPopulationRows', ...
            'Decision, objective, and constraint arrays must have equal rows.');
    end
    names = [indexedNames("x",size(Dec,2)), ...
        indexedNames("f",size(Obj,2)),indexedNames("c",size(Con,2))];
    T = array2table([Dec,Obj,Con],'VariableNames',cellstr(names));
end

function names = indexedNames(prefix,n)
    names = strings(1,n);
    for i = 1 : n
        names(i) = prefix + string(i);
    end
end

function exportTrackerTables(Tracker,QuerySamples,Row,D)
    required = {'ref_exposure','ref_conversions','samples','direct_entries'};
    if ~isstruct(Tracker) || ~all(isfield(Tracker,required))
        error('CBSRegionDiagnostics:BadTrackerExport', ...
            'Tracker export is missing required row sets.');
    end
    writetable(querySampleTable(QuerySamples),Row.query_samples_file);
    writetable(struct2table(Tracker.ref_exposure), ...
        Row.query_ref_exposure_file);
    writetable(struct2table(Tracker.ref_conversions), ...
        Row.query_ref_conversion_file);
    writetable(trackerSampleTable(Tracker.samples,D), ...
        Row.gan_bmem_eligible_samples_file);
    writetable(trackerSampleTable(Tracker.direct_entries,D), ...
        Row.direct_gan_bmem_entry_file);
end

function T = trackerSampleTable(Rows,D)
    T = struct2table(Rows);
    if ismember('decision',T.Properties.VariableNames)
        T.decision = [];
    end
    if isempty(Rows)
        Dec = zeros(0,D);
    else
        Dec = vertcat(Rows.decision);
    end
    if size(Dec,2) ~= D
        error('CBSRegionDiagnostics:BadTrackerDecisionColumns', ...
            'Tracker decisions must match final population dimension.');
    end
    DecisionTable = array2table(Dec, ...
        'VariableNames',cellstr(indexedNames("x",D)));
    T = [T,DecisionTable];
end

function T = querySampleTable(QuerySamples)
    if ~isstruct(QuerySamples) || ~isfield(QuerySamples,'columns') || ...
            ~isfield(QuerySamples,'rows')
        error('CBSRegionDiagnostics:BadQuerySampleExport', ...
            'Query sample export must contain columns and rows.');
    end
    names = string(QuerySamples.columns(:)');
    rows = double(QuerySamples.rows);
    if size(rows,2) ~= numel(names)
        error('CBSRegionDiagnostics:BadQuerySampleColumns', ...
            'Query sample rows must match exported column names.');
    end
    T = array2table(rows,'VariableNames',cellstr(names));
end

function History = getMetricCellHistory(metric,name)
    History = cell(0,1);
    if isstruct(metric) && isfield(metric,name) && ...
            iscell(metric.(name))
        History = metric.(name);
    end
end

function T = regionBMemHistoryTable(History,RunRow)
    D = max(0,round(double(RunRow.D)));
    M = max(0,round(double(RunRow.M)));
    total = 0;
    for s = 1 : numel(History)
        if isstruct(History{s}) && isfield(History{s},'bmem') && ...
                isstruct(History{s}.bmem) && ...
                isfield(History{s}.bmem,'x_f')
            total = total + size(History{s}.bmem.x_f,1);
        end
    end
    problem = repmat(string(RunRow.problem),total,1);
    run = repmat(double(RunRow.run),total,1);
    seed = repmat(double(RunRow.seed),total,1);
    snapshotIndex = zeros(total,1);
    generation = zeros(total,1);
    fe = zeros(total,1);
    bmemRow = zeros(total,1);
    sampleIdF = strings(total,1);
    sampleIdI = strings(total,1);
    pairId = strings(total,1);
    ref = zeros(total,1);
    gap = nan(total,1);
    sourceF = zeros(total,1);
    sourceLabelF = strings(total,1);
    ageF = zeros(total,1);
    frontRankF = nan(total,1);
    candidateRowF = nan(total,1);
    candidateRowI = nan(total,1);
    Xf = nan(total,D);
    Yf = nan(total,M);
    Xi = nan(total,D);
    Yi = nan(total,M);
    PairNormal = nan(total,M);
    idCache = containers.Map('KeyType','char','ValueType','char');
    row = 0;
    for s = 1 : numel(History)
        Snapshot = History{s};
        if ~isstruct(Snapshot) || ~isfield(Snapshot,'bmem') || ...
                ~isstruct(Snapshot.bmem) || ...
                ~isfield(Snapshot.bmem,'x_f')
            continue;
        end
        BMem = Snapshot.bmem;
        n = size(BMem.x_f,1);
        rows = row + (1:n);
        row = row + n;
        if n == 0
            continue;
        end
        snapshotIndex(rows) = s;
        generation(rows) = snapshotNumeric(Snapshot,'generation');
        fe(rows) = snapshotNumeric(Snapshot,'fe');
        bmemRow(rows) = (1:n)';
        ref(rows) = memoryNumericMatrix(BMem,'ref',n,1,NaN);
        gap(rows) = memoryNumericMatrix(BMem,'gap',n,1,NaN);
        sourceF(rows) = memoryNumericMatrix( ...
            BMem,'source_f',n,1,0);
        ageF(rows) = memoryNumericMatrix(BMem,'age_f',n,1,0);
        frontRankF(rows) = memoryNumericMatrix( ...
            BMem,'front_rank_f',n,1,NaN);
        candidateRowF(rows) = memoryNumericMatrix( ...
            BMem,'candidate_row_f',n,1,NaN);
        candidateRowI(rows) = memoryNumericMatrix( ...
            BMem,'candidate_row_i',n,1,NaN);
        Xf(rows,:) = memoryNumericMatrix(BMem,'x_f',n,D,NaN);
        Yf(rows,:) = memoryNumericMatrix(BMem,'y_f',n,M,NaN);
        Xi(rows,:) = memoryNumericMatrix(BMem,'x_i',n,D,NaN);
        Yi(rows,:) = memoryNumericMatrix(BMem,'y_i',n,M,NaN);
        PairNormal(rows,:) = memoryNumericMatrix( ...
            BMem,'pair_normal',n,M,NaN);
        for i = 1 : n
            outRow = rows(i);
            sampleIdF(outRow) = stableDecisionId(idCache,Xf(outRow,:));
            sampleIdI(outRow) = stableDecisionId(idCache,Xi(outRow,:));
            pairId(outRow) = sampleIdF(outRow) + ":" + ...
                sampleIdI(outRow);
            if sourceF(outRow) == 0
                sourceLabelF(outRow) = "current";
            else
                sourceLabelF(outRow) = "previous";
            end
        end
    end
    Base = table(problem,run,seed,snapshotIndex,generation,fe,bmemRow, ...
        sampleIdF,sampleIdI,pairId,ref,gap,sourceF,sourceLabelF, ...
        ageF,frontRankF,candidateRowF,candidateRowI, ...
        'VariableNames',{'problem','run','seed','snapshot_index', ...
        'generation','fe','bmem_row','sample_id_f','sample_id_i', ...
        'pair_id','ref','gap','source_f','source_label_f', ...
        'age_f','front_rank_f','candidate_row_f', ...
        'candidate_row_i'});
    T = [Base, ...
        array2table(Xf,'VariableNames',cellstr(indexedNames("x_f",D))), ...
        array2table(Yf,'VariableNames',cellstr(indexedNames("y_f",M))), ...
        array2table(Xi,'VariableNames',cellstr(indexedNames("x_i",D))), ...
        array2table(Yi,'VariableNames',cellstr(indexedNames("y_i",M))), ...
        array2table(PairNormal,'VariableNames', ...
            cellstr(indexedNames("pair_normal",M)))];
end

function T = regionBMemRefHistoryTable(History,RunRow)
    total = 0;
    for s = 1 : numel(History)
        if isstruct(History{s}) && isfield(History{s},'rows') && ...
                isstruct(History{s}.rows)
            total = total + numel(History{s}.rows);
        end
    end
    Rows = repmat(emptyBMemRefExportRow(),total,1);
    row = 0;
    for s = 1 : numel(History)
        Snapshot = History{s};
        if ~isstruct(Snapshot) || ~isfield(Snapshot,'rows') || ...
                ~isstruct(Snapshot.rows)
            continue;
        end
        for i = 1 : numel(Snapshot.rows)
            row = row + 1;
            Rows(row).problem = string(RunRow.problem);
            Rows(row).run = double(RunRow.run);
            Rows(row).seed = double(RunRow.seed);
            Rows(row).snapshot_index = double(s);
            Rows(row).generation = snapshotNumeric(Snapshot,'generation');
            Rows(row).fe = snapshotNumeric(Snapshot,'fe');
            Rows(row) = copyMatchingStructFields( ...
                Rows(row),Snapshot.rows(i));
        end
    end
    T = struct2table(Rows(1:row));
end

function Row = copyMatchingStructFields(Row,Source)
    names = intersect(fieldnames(Row),fieldnames(Source),'stable');
    for i = 1 : numel(names)
        Row.(names{i}) = Source.(names{i});
    end
end

function Row = emptyBMemRefExportRow()
    Row = struct( ...
        'problem',"",'run',NaN,'seed',NaN,'snapshot_index',NaN, ...
        'generation',NaN,'fe',NaN,'ref',NaN,'train_count',0, ...
        'current_count',0,'previous_count',0,'previous_ratio',NaN, ...
        'age50',NaN,'age90',NaN,'age_max',NaN, ...
        'front1_count',0,'front2_count',0,'other_front_count',0, ...
        'train_pair_count',0,'train_dec_pair50',NaN, ...
        'train_dec_pair90',NaN,'train_obj_pair50',NaN, ...
        'train_obj_pair90',NaN,'train_dec_obj_ratio50',NaN, ...
        'train_dec_obj_ratio90',NaN,'generated_count',0, ...
        'populated_generated_count',0,'frontier_generated_count',0, ...
        'remote_generated_count',0,'generated_pair_count',0, ...
        'generated_dec_pair50',NaN,'generated_dec_pair90',NaN, ...
        'generated_to_same_ref_train_count',0, ...
        'generated_to_same_ref_train_dec50',NaN, ...
        'generated_to_same_ref_train_dec90',NaN, ...
        'anchor_utilized_count',0,'anchor_utilization_rate',NaN, ...
        'generated_train_diversity_ratio50',NaN, ...
        'generated_train_diversity_ratio90',NaN);
end

function T = regionLatentScaleRefHistoryTable(History,RunRow)
    total = 0;
    for s = 1 : numel(History)
        if isstruct(History{s}) && isfield(History{s},'rows') && ...
                isstruct(History{s}.rows)
            total = total + numel(History{s}.rows);
        end
    end
    Rows = repmat(emptyLatentScaleRefExportRow(),total,1);
    row = 0;
    for s = 1 : numel(History)
        Snapshot = History{s};
        if ~isstruct(Snapshot) || ~isfield(Snapshot,'rows') || ...
                ~isstruct(Snapshot.rows)
            continue;
        end
        for i = 1 : numel(Snapshot.rows)
            row = row + 1;
            Rows(row).problem = string(RunRow.problem);
            Rows(row).run = double(RunRow.run);
            Rows(row).seed = double(RunRow.seed);
            Rows(row).snapshot_index = double(s);
            Rows(row).event_index = snapshotNumeric( ...
                Snapshot,'event_index');
            Rows(row).generation = snapshotNumeric(Snapshot,'generation');
            Rows(row).fe = snapshotNumeric(Snapshot,'fe');
            Rows(row) = copyMatchingStructFields( ...
                Rows(row),Snapshot.rows(i));
        end
    end
    T = struct2table(Rows(1:row));
end

function Row = emptyLatentScaleRefExportRow()
    Row = struct( ...
        'problem',"",'run',NaN,'seed',NaN,'snapshot_index',NaN, ...
        'event_index',NaN,'generation',NaN,'fe',NaN,'ref',NaN, ...
        'train_count',0,'train_dec_pair_count',0, ...
        'train_dec_pair90',NaN,'z_count',0, ...
        'train_sigma',NaN,'sample_sigma',NaN, ...
        'train_scale_generated_dec_pair_count',0, ...
        'train_scale_generated_dec_pair90',NaN, ...
        'train_scale_gen_to_train_dec50',NaN, ...
        'train_scale_gen_to_train_dec90',NaN, ...
        'train_scale_anchor_utilized_count',0, ...
        'train_scale_anchor_utilization_rate',NaN, ...
        'train_scale_diversity_ratio90',NaN, ...
        'sample_scale_generated_dec_pair_count',0, ...
        'sample_scale_generated_dec_pair90',NaN, ...
        'sample_scale_gen_to_train_dec50',NaN, ...
        'sample_scale_gen_to_train_dec90',NaN, ...
        'sample_scale_anchor_utilized_count',0, ...
        'sample_scale_anchor_utilization_rate',NaN, ...
        'sample_scale_diversity_ratio90',NaN);
end

function value = snapshotNumeric(S,name)
    value = NaN;
    if isstruct(S) && isfield(S,name) && ~isempty(S.(name))
        value = double(S.(name));
    end
end

function value = memoryNumericMatrix(S,name,n,width,defaultValue)
    value = repmat(double(defaultValue),n,width);
    if isstruct(S) && isfield(S,name) && ...
            size(S.(name),1) == n && size(S.(name),2) == width
        value = double(S.(name));
    end
end

function value = stableDecisionId(Cache,X)
    X = double(X(:));
    key = reshape(num2hex(X).',1,[]);
    if isKey(Cache,key)
        value = string(Cache(key));
        return;
    end
    digest = java.security.MessageDigest.getInstance('SHA-256');
    digest.update(uint8(key));
    value = lower(string(reshape(dec2hex(typecast( ...
        digest.digest(),'uint8'),2).',1,[])));
    Cache(key) = char(value); %#ok<NASGU>
end

function [EventSummary,TrainHistory] = buildDiagnosticTables(History,RunRow)
    trainRowTotal = 0;
    eventRowTotal = 0;
    for eventIndex = 1 : numel(History)
        Event = History(eventIndex);
        if isfield(Event,'generation') && ~isempty(Event.generation)
            eventRowTotal = eventRowTotal + 1;
        end
        if isfield(Event,'gan_train_history') && ...
                ~isempty(Event.gan_train_history)
            trainRowTotal = trainRowTotal + numel(Event.gan_train_history);
        end
    end
    EventRows = repmat(emptyEventRow(),eventRowTotal,1);
    TrainRows = repmat(emptyTrainRow(),trainRowTotal,1);
    eventRow = 0;
    trainRow = 0;
    for eventIndex = 1 : numel(History)
        Event = History(eventIndex);
        H = struct([]);
        if ~isfield(Event,'gan_train_history') || ...
                isempty(Event.gan_train_history)
            if ~isfield(Event,'generation') || isempty(Event.generation)
                continue;
            end
        else
            H = Event.gan_train_history;
        end
        eventRow = eventRow + 1;
        EventRows(eventRow,1) = summarizeTrainingEvent( ...
            H,Event,RunRow,eventIndex);
        for h = 1 : numel(H)
            trainRow = trainRow + 1;
            TrainRows(trainRow,1) = summarizeTrainingStep( ...
                H(h),Event,RunRow,eventIndex);
        end
    end
    EventRows = EventRows(1:eventRow);
    TrainRows = TrainRows(1:trainRow);
    EventSummary = struct2table(EventRows);
    TrainHistory = struct2table(TrainRows);
end

function Row = summarizeTrainingEvent(H,Event,RunRow,eventIndex)
    Row = emptyEventRow();
    Row.problem = RunRow.problem;
    Row.run = RunRow.run;
    Row.seed = RunRow.seed;
    Row.event_index = double(eventIndex);
    Row.generation = getNumericField(Event,'generation');
    Row.fe = getNumericField(Event,'fe');
    Row.train_count = getNumericField(Event,'train_count');
    Row.train_count_raw = getNumericField(Event,'train_count_raw');
    Row.train_exact_duplicate_count = getNumericField( ...
        Event,'train_exact_duplicate_count');
    Row.train_removed_duplicate_count = getNumericField( ...
        Event,'train_removed_duplicate_count');
    Row.train_duplicate_fraction = getNumericField( ...
        Event,'train_duplicate_fraction');
    Row.train_dedup_enabled = getNumericField(Event,'train_dedup_enabled');
    Row.gan_iter_used = getNumericField(Event,'gan_iter_used');
    Row.train_z_sigma = getNumericField(Event,'train_z_sigma');
    Row.sample_z_sigma = getNumericField(Event,'sample_z_sigma');
    structuredFields = structuredZDiagnosticFields();
    for i = 1 : numel(structuredFields)
        Row.(structuredFields{i}) = getNumericField( ...
            Event,structuredFields{i});
    end
    Row.query_count = getNumericField(Event,'query_count');
    Row.query_sample_count = getNumericField(Event,'query_sample_count');
    Row.query_unique_ref_count = getNumericField(Event, ...
        'query_unique_ref_count');
    Row.raw_generated_count = getNumericField(Event,'raw_generated_count');
    Row.feasible_rate = getNumericField(Event,'feasible_rate');
    Row.history_rows = double(numel(H));
    if isempty(H)
        Row.final_loss_d = getNumericField(Event,'last_critic_loss');
        Row.final_loss_g = getNumericField(Event,'last_generator_loss');
        Row.final_score_real_mean = getNumericField(Event,'last_score_real');
        Row.final_score_fake_mean = getNumericField(Event,'last_score_fake');
    else
        Last = H(end);
        Row.final_loss_d = double(Last.loss_d);
        Row.final_loss_g = double(Last.loss_g);
        Row.final_score_real_mean = double(Last.score_real_mean);
        Row.final_score_fake_mean = double(Last.score_fake_mean);
    end
    Row.score_gap = Row.final_score_real_mean - Row.final_score_fake_mean;
    boundaryFields = generatedBoundaryDiagnosticFields();
    for i = 1 : numel(boundaryFields)
        Row.(boundaryFields{i}) = getNumericField(Event,boundaryFields{i});
    end
    diagFields = mappingDiagnosticFields();
    for i = 1 : numel(diagFields)
        Row.(diagFields{i}) = getNumericField(Event,diagFields{i});
    end
    widthFields = widthDiagnosticFields();
    for i = 1 : numel(widthFields)
        Row.(widthFields{i}) = getNumericField(Event,widthFields{i});
    end
    attributionFields = attributionDiagnosticFields();
    for i = 1 : numel(attributionFields)
        Row.(attributionFields{i}) = getNumericField( ...
            Event,attributionFields{i});
    end
    learnabilityFields = bmemLearnabilityDiagnosticFields();
    for i = 1 : numel(learnabilityFields)
        Row.(learnabilityFields{i}) = getNumericField( ...
            Event,learnabilityFields{i});
    end
    latentScaleFields = latentScaleDiagnosticFields();
    for i = 1 : numel(latentScaleFields)
        Row.(latentScaleFields{i}) = getNumericField( ...
            Event,latentScaleFields{i});
    end
end

function Row = summarizeTrainingStep(H,Event,RunRow,eventIndex)
    Row = emptyTrainRow();
    Row.problem = RunRow.problem;
    Row.run = RunRow.run;
    Row.seed = RunRow.seed;
    Row.event_index = double(eventIndex);
    Row.generation = getNumericField(Event,'generation');
    Row.step = double(H.step);
    Row.loss_d = double(H.loss_d);
    Row.loss_g = double(H.loss_g);
    Row.loss_g_adversarial = getHistoryField(H,'loss_g_adversarial');
    Row.loss_mi = getHistoryField(H,'loss_mi');
    Row.mode_decoder_accuracy = getHistoryField( ...
        H,'mode_decoder_accuracy');
    Row.score_real_mean = double(H.score_real_mean);
    Row.score_fake_mean = double(H.score_fake_mean);
    Row.gradient_penalty = getHistoryField(H,'gradient_penalty');
    Row.elapsed_critic = getHistoryField(H,'elapsed_critic');
    Row.elapsed_generator = getHistoryField(H,'elapsed_generator');
end

function value = getNumericField(S,name)
    if isstruct(S) && isfield(S,name) && ~isempty(S.(name))
        value = double(S.(name));
    else
        value = NaN;
    end
end

function value = getHistoryField(S,name)
    if isstruct(S) && isfield(S,name) && ~isempty(S.(name))
        value = double(S.(name));
    else
        value = NaN;
    end
end

function T = collectDiagnosticTables(files,emptyRow)
    files = string(files(:));
    Schema = struct2table(repmat(emptyRow,0,1));
    Tables = {};
    for i = 1 : numel(files)
        if strlength(files(i)) > 0 && isfile(files(i))
            Ti = readtable(files(i),'TextType','string', ...
                'Delimiter',',','ReadVariableNames',true, ...
                'VariableNamingRule','preserve');
            Tables{end+1,1} = alignTableToSchema(Ti,Schema,emptyRow); %#ok<AGROW>
        end
    end
    if isempty(Tables)
        T = Schema;
    else
        T = vertcat(Tables{:});
    end
end

function T = collectHomogeneousDiagnosticTables(files)
    files = string(files(:));
    Tables = cell(0,1);
    schema = strings(0,1);
    for i = 1 : numel(files)
        if strlength(files(i)) == 0 || ~isfile(files(i))
            continue;
        end
        Ti = readtable(files(i),'TextType','string', ...
            'Delimiter',',','ReadVariableNames',true, ...
            'VariableNamingRule','preserve');
        current = string(Ti.Properties.VariableNames);
        if isempty(schema)
            schema = current;
        elseif ~isequal(current,schema)
            error('CBSRegionDiagnostics:InconsistentBMemSchema', ...
                'BMem diagnostic CSV schemas differ across runs.');
        end
        Tables{end+1,1} = Ti; %#ok<AGROW>
    end
    if isempty(Tables)
        T = table();
    else
        T = vertcat(Tables{:});
    end
end

function T = alignTableToSchema(T,Schema,emptyRow)
    schemaNames = string(Schema.Properties.VariableNames);
    if height(T) == 0
        T = Schema;
        return;
    end
    currentNames = string(T.Properties.VariableNames);
    for i = 1 : numel(schemaNames)
        name = schemaNames(i);
        if ~ismember(name,currentNames)
            T.(name) = defaultTableColumn(emptyRow.(name),height(T));
        end
    end
    extra = setdiff(string(T.Properties.VariableNames),schemaNames, ...
        'stable');
    if ~isempty(extra)
        T(:,cellstr(extra)) = [];
    end
    T = T(:,cellstr(schemaNames));
end

function col = defaultTableColumn(value,n)
    if isstring(value)
        col = repmat(string(value),n,1);
    elseif ischar(value)
        col = repmat(string(value),n,1);
    elseif islogical(value)
        col = false(n,1);
    else
        col = NaN(n,1);
    end
end

function ensureDiagnosticParallelPool(workerCount)
    pool = gcp('nocreate');
    if ~isempty(pool) && pool.NumWorkers ~= workerCount
        delete(pool);
        pool = [];
    end
    if isempty(pool)
        parpool('local',workerCount);
    end
end

function Row = emptyRunRow()
    Row = struct( ...
        'problem',"", ...
        'run',NaN, ...
        'seed',NaN, ...
        'N',NaN, ...
        'D',NaN, ...
        'M',NaN, ...
        'maxFE',NaN, ...
        'finalFE',NaN, ...
        'runtime',NaN, ...
        'schema_version',"", ...
        'git_sha',"", ...
        'git_branch',"", ...
        'git_dirty',NaN, ...
        'source_tree_sha256',"", ...
        'event_count',0, ...
        'train_row_count',0, ...
        'bmem_history_row_count',0, ...
        'bmem_ref_history_row_count',0, ...
        'latent_scale_ref_history_row_count',0, ...
        'query_sample_row_count',0, ...
        'ref_exposure_row_count',0, ...
        'ref_conversion_row_count',0, ...
        'gan_bmem_eligible_sample_row_count',0, ...
        'direct_bmem_entry_row_count',0, ...
        'status',"pending", ...
        'error_message',"", ...
        'run_folder',"", ...
        'metric_file',"", ...
        'event_summary_file',"", ...
        'train_history_file',"", ...
        'bmem_history_file',"", ...
        'bmem_ref_history_file',"", ...
        'latent_scale_ref_history_file',"", ...
        'stage_snapshot_file',"", ...
        'final_p1_file',"", ...
        'final_p2_file',"", ...
        'final_feasible_nd_file',"", ...
        'query_samples_file',"", ...
        'query_ref_exposure_file',"", ...
        'query_ref_conversion_file',"", ...
        'gan_bmem_eligible_samples_file',"", ...
        'direct_gan_bmem_entry_file',"", ...
        'provenance_file',"", ...
        'source_manifest_file',"");
end

function Row = emptyEventRow()
    Row = struct( ...
        'problem',"", ...
        'run',NaN, ...
        'seed',NaN, ...
        'event_index',NaN, ...
        'generation',NaN, ...
        'fe',NaN, ...
        'train_count',NaN, ...
        'train_count_raw',NaN, ...
        'train_exact_duplicate_count',NaN, ...
        'train_removed_duplicate_count',NaN, ...
        'train_duplicate_fraction',NaN, ...
        'train_dedup_enabled',NaN, ...
        'gan_iter_used',NaN, ...
        'train_z_sigma',NaN, ...
        'sample_z_sigma',NaN, ...
        'query_count',NaN, ...
        'query_sample_count',NaN, ...
        'query_unique_ref_count',NaN, ...
        'raw_generated_count',NaN, ...
        'feasible_rate',NaN, ...
        'history_rows',NaN, ...
        'final_loss_d',NaN, ...
        'final_loss_g',NaN, ...
        'final_score_real_mean',NaN, ...
        'final_score_fake_mean',NaN, ...
        'score_gap',NaN);
    fields = structuredZDiagnosticFields();
    for i = 1 : numel(fields)
        Row.(fields{i}) = NaN;
    end
    boundaryFields = generatedBoundaryDiagnosticFields();
    for i = 1 : numel(boundaryFields)
        Row.(boundaryFields{i}) = NaN;
    end
    fields = mappingDiagnosticFields();
    for i = 1 : numel(fields)
        Row.(fields{i}) = NaN;
    end
    fields = widthDiagnosticFields();
    for i = 1 : numel(fields)
        Row.(fields{i}) = NaN;
    end
    fields = attributionDiagnosticFields();
    for i = 1 : numel(fields)
        Row.(fields{i}) = NaN;
    end
    fields = bmemLearnabilityDiagnosticFields();
    for i = 1 : numel(fields)
        Row.(fields{i}) = NaN;
    end
    fields = latentScaleDiagnosticFields();
    for i = 1 : numel(fields)
        Row.(fields{i}) = NaN;
    end
end

function Row = emptyTrainRow()
    Row = struct( ...
        'problem',"", ...
        'run',NaN, ...
        'seed',NaN, ...
        'event_index',NaN, ...
        'generation',NaN, ...
        'step',NaN, ...
        'loss_d',NaN, ...
        'loss_g',NaN, ...
        'loss_g_adversarial',NaN, ...
        'loss_mi',NaN, ...
        'mode_decoder_accuracy',NaN, ...
        'score_real_mean',NaN, ...
        'score_fake_mean',NaN, ...
        'gradient_penalty',NaN, ...
        'elapsed_critic',NaN, ...
        'elapsed_generator',NaN);
end

function fields = structuredZDiagnosticFields()
    fields = { ...
        'structured_z_enabled', ...
        'structured_z_max_modes', ...
        'structured_z_lambda', ...
        'mode_decoder_update_count', ...
        'mode_sample_count', ...
        'mode_multi_active_sample_count', ...
        'mode_sample_decoder_accuracy', ...
        'mode_sample_confidence_mean', ...
        'mode_sample_label_entropy', ...
        'mode_sample_prediction_entropy', ...
        'mode_active_count_mean', ...
        'mode_active_count_max', ...
        'last_generator_adversarial_loss', ...
        'last_mi_loss', ...
        'last_mode_decoder_accuracy'};
end

function fields = generatedBoundaryDiagnosticFields()
    fields = {'dist_to_bmem50', ...
        'dist_to_bmem90', ...
        'dist_to_target_pm2_bmem50', ...
        'dist_to_target_pm2_bmem90', ...
        'segment_dist50', ...
        'segment_dist90', ...
        'gap_ratio50', ...
        'gap_ratio90', ...
        'near_boundary_rate_gap1', ...
        'near_boundary_feasible_rate_gap1', ...
        'random_gap_ratio50', ...
        'random_gap_ratio90', ...
        'random_near_boundary_rate_gap1', ...
        'random_feasible_rate', ...
        'better_than_random_gap_rate', ...
        'bdist50_true', ...
        'bwidth90_10_true', ...
        'bcover_eps_true'};
end

function fields = widthDiagnosticFields()
    fields = {'train_width50', ...
        'train_width90', ...
        'train_width_count', ...
        'gen_width50', ...
        'gen_width90', ...
        'gen_width_count', ...
        'gen_to_train_dist50', ...
        'gen_to_train_dist90', ...
        'gen_to_train_dist_count', ...
        'gen_to_train_dec_dist50', ...
        'gen_to_train_dec_dist90', ...
        'offspringG_count', ...
        'offspringG_survive_count', ...
        'offspringG_survival_rate', ...
        'offspringG_feasible_count', ...
        'offspringG_feasible_survive_count', ...
        'offspringG_feasible_survival_rate', ...
        'critic_train_gap', ...
        'critic_holdout_gap', ...
        'critic_train_real_score_mean', ...
        'critic_train_fake_score_mean', ...
        'critic_holdout_real_score_mean', ...
        'critic_holdout_fake_score_mean', ...
        'critic_train_diag_count', ...
        'critic_holdout_count', ...
        'prequential_new_count', ...
        'prequential_seen_count', ...
        'prequential_pre_critic_gap', ...
        'prequential_post_critic_gap', ...
        'prequential_pre_dec_dist50', ...
        'prequential_pre_dec_dist90', ...
        'prequential_post_dec_dist50', ...
        'prequential_post_dec_dist90', ...
        'generated_critic_score_count', ...
        'generated_critic_score_min', ...
        'generated_critic_score_max', ...
        'generated_critic_score_mean'};
end

function fields = bmemLearnabilityDiagnosticFields()
    fields = { ...
        'bmem_within_ref_dec_pair_count', ...
        'bmem_within_ref_dec_pair50', ...
        'bmem_within_ref_dec_pair90', ...
        'bmem_within_ref_obj_pair50', ...
        'bmem_within_ref_obj_pair90', ...
        'bmem_within_ref_dec_obj_ratio50', ...
        'bmem_within_ref_dec_obj_ratio90', ...
        'bmem_previous_ratio', ...
        'bmem_age50', ...
        'bmem_age90', ...
        'bmem_age_max', ...
        'bmem_front1_ratio', ...
        'bmem_front2_ratio', ...
        'generated_within_ref_dec_pair_count', ...
        'generated_within_ref_dec_pair50', ...
        'generated_within_ref_dec_pair90', ...
        'generated_same_ref_to_train_dec50', ...
        'generated_same_ref_to_train_dec90', ...
        'generated_queried_anchor_utilized_count', ...
        'generated_queried_anchor_count', ...
        'generated_queried_anchor_utilization_rate', ...
        'generated_train_dec_diversity_ratio50', ...
        'generated_train_dec_diversity_ratio90'};
end

function fields = latentScaleDiagnosticFields()
    fields = { ...
        'latent_scale_ref_count', ...
        'latent_scale_z_count', ...
        'latent_scale_train_sigma', ...
        'latent_scale_sample_sigma', ...
        'latent_scale_train_gen_to_train_dec50_median', ...
        'latent_scale_train_gen_to_train_dec90_median', ...
        'latent_scale_sample_gen_to_train_dec50_median', ...
        'latent_scale_sample_gen_to_train_dec90_median', ...
        'latent_scale_train_anchor_utilization_median', ...
        'latent_scale_sample_anchor_utilization_median', ...
        'latent_scale_train_diversity_ratio90_median', ...
        'latent_scale_sample_diversity_ratio90_median'};
end

function fields = mappingDiagnosticFields()
    fields = {'condition_diag_condition_count', ...
        'condition_diag_z_count', ...
        'same_z_diff_c_dec_median', ...
        'same_c_diff_z_dec_median', ...
        'same_c_diff_z_collapse_rate', ...
        'condition_effect_ratio_dec'};
end

function fields = attributionDiagnosticFields()
    fields = {};
    groups = {'populated','frontier','remote'};
    suffixes = {'sample_count','unique_ref_count','feasible_count', ...
        'feasible_rate','survive_P1_count','survive_P1_rate', ...
        'survive_P2_count','survive_P2_rate','survive_union_count', ...
        'survive_union_rate','bdist50_true','bwidth90_10_true', ...
        'bcover_eps_true','gen_to_train_dec_dist50', ...
        'gen_to_train_dec_dist90','gen_to_train_obj_dist50', ...
        'gen_to_train_obj_dist90','pair_normal_abs50', ...
        'pair_normal_abs90','pair_tangent_dist50', ...
        'pair_tangent_dist90'};
    for i = 1 : numel(groups)
        for j = 1 : numel(suffixes)
            fields{end+1} = ['query_',groups{i},'_',suffixes{j}]; %#ok<AGROW>
        end
    end
    fields = [fields,{ ...
        'offspringG_survive_P1_count','offspringG_survive_P1_rate', ...
        'offspringG_survive_P2_count','offspringG_survive_P2_rate', ...
        'offspringG_survive_union_count','offspringG_survive_union_rate', ...
        'bmem_bdist50_true','bmem_bwidth90_10_true','bmem_bcover_eps_true', ...
        'ref_conversion_new_count','ref_conversion_new_lag_gen50', ...
        'ref_conversion_new_lag_fe50','direct_bmem_entry_new_count', ...
        'direct_bmem_entry_new_lag_gen50', ...
        'direct_bmem_entry_new_lag_fe50', ...
        'tracker_ref_exposure_count','tracker_ref_frontier_exposure_count', ...
        'tracker_ref_remote_exposure_count', ...
        'tracker_ref_exposure_event_count','tracker_ref_generated_count', ...
        'tracker_ref_converted_count','tracker_ref_conversion_rate', ...
        'tracker_ref_conversion_lag_gen50', ...
        'tracker_ref_conversion_lag_fe50', ...
        'tracker_direct_eligible_sample_count', ...
        'tracker_direct_bmem_entry_count','tracker_direct_bmem_entry_rate', ...
        'tracker_direct_bmem_entry_lag_gen50', ...
        'tracker_direct_bmem_entry_lag_fe50', ...
        'time_bmem_dataset_query','time_gan_train_sample', ...
        'time_gan_evaluation','time_selection_P1','time_selection_P2', ...
        'time_diagnostics_serialization'}];
    matchedPrefixes = {'frontier_matched_gan_','frontier_matched_de_'};
    matchedSuffixes = {'sample_count','feasible_count','feasible_rate', ...
        'survive_P1_count','survive_P1_rate','survive_P2_count', ...
        'survive_P2_rate','survive_union_count','survive_union_rate', ...
        'bdist50_true','bwidth90_10_true','bcover_eps_true', ...
        'refeq_feasible_rate','refeq_survive_P1_rate', ...
        'refeq_survive_P2_rate','refeq_survive_union_rate', ...
        'refeq_bdist50_true','refeq_bwidth90_10_true', ...
        'refeq_bcover_eps_true'};
    fields = [fields,{'frontier_query_ref_count', ...
        'frontier_matched_de_available', ...
        'frontier_matched_de_available_ref_count', ...
        'frontier_matched_de_unavailable_ref_count'}];
    for i = 1 : numel(matchedPrefixes)
        for j = 1 : numel(matchedSuffixes)
            fields{end+1} = [matchedPrefixes{i},matchedSuffixes{j}]; %#ok<AGROW>
        end
    end
end

function T = regionStageSnapshotTable(Snapshots,RunRow)
    if isempty(Snapshots)
        T = struct2table(repmat(emptyStageSnapshotRow(),0,1));
        return;
    end
    Rows = repmat(emptyStageSnapshotRow(),numel(Snapshots),1);
    for i = 1 : numel(Snapshots)
        S = Snapshots(i);
        Rows(i).problem = RunRow.problem;
        Rows(i).run = RunRow.run;
        Rows(i).seed = RunRow.seed;
        Rows(i).target_FE = getSnapshotNumeric(S,'target_FE');
        Rows(i).actual_FE = getSnapshotNumeric(S,'actual_FE');
        Rows(i).generation = getSnapshotNumeric(S,'generation');
        Rows(i).gan_iter_used = getSnapshotNumeric(S,'gan_iter_used');
        Rows(i).train_z_sigma = getSnapshotNumeric(S, ...
            'train_z_sigma');
        Rows(i).sample_z_sigma = getSnapshotNumeric(S, ...
            'sample_z_sigma');
        Rows(i).train_count = getSnapshotNumeric(S,'train_count');
        Rows(i).prev_bmem_candidate_count = getSnapshotNumeric(S, ...
            'prev_bmem_candidate_count');
        Rows(i).prev_bmem_survivor_count = getSnapshotNumeric(S, ...
            'prev_bmem_survivor_count');
        Rows(i).raw_generated_count = getSnapshotNumeric(S, ...
            'raw_generated_count');
        Rows(i).feasible_rate = getSnapshotNumeric(S,'feasible_rate');
        Rows(i).gap_ratio50 = getSnapshotNumeric(S,'gap_ratio50');
        Rows(i).gap_ratio90 = getSnapshotNumeric(S,'gap_ratio90');
        Rows(i).near_boundary_rate_gap1 = getSnapshotNumeric(S, ...
            'near_boundary_rate_gap1');
        Rows(i).better_than_random_gap_rate = getSnapshotNumeric(S, ...
            'better_than_random_gap_rate');
        Rows(i).bdist50_true = getSnapshotNumeric(S,'bdist50_true');
        Rows(i).bwidth90_10_true = getSnapshotNumeric(S, ...
            'bwidth90_10_true');
        Rows(i).bcover_eps_true = getSnapshotNumeric(S, ...
            'bcover_eps_true');
        Rows(i).train_width50 = getSnapshotNumeric(S,'train_width50');
        Rows(i).train_width90 = getSnapshotNumeric(S,'train_width90');
        Rows(i).gen_width50 = getSnapshotNumeric(S,'gen_width50');
        Rows(i).gen_width90 = getSnapshotNumeric(S,'gen_width90');
        Rows(i).gen_to_train_dist50 = getSnapshotNumeric(S, ...
            'gen_to_train_dist50');
        Rows(i).gen_to_train_dist90 = getSnapshotNumeric(S, ...
            'gen_to_train_dist90');
        Rows(i).offspringG_survival_rate = getSnapshotNumeric(S, ...
            'offspringG_survival_rate');
        Rows(i).critic_train_gap = getSnapshotNumeric(S, ...
            'critic_train_gap');
        Rows(i).critic_holdout_gap = getSnapshotNumeric(S, ...
            'critic_holdout_gap');
        Rows(i).generated_critic_score_mean = getSnapshotNumeric(S, ...
            'generated_critic_score_mean');
        Rows(i).sample_feasible_count = sum(logicalVectorField(S, ...
            'sample_feasible'));
        Rows(i).sample_infeasible_count = sizeField(S,'sample_objs') - ...
            Rows(i).sample_feasible_count;
    end
    T = struct2table(Rows);
end

function values = logicalVectorField(S,name)
    if isstruct(S) && isfield(S,name) && ~isempty(S.(name))
        values = logical(S.(name)(:));
    else
        values = false(0,1);
    end
end

function n = sizeField(S,name)
    if isstruct(S) && isfield(S,name) && ~isempty(S.(name))
        n = size(S.(name),1);
    else
        n = 0;
    end
end

function value = getSnapshotNumeric(S,name)
    if isstruct(S) && isfield(S,name) && ~isempty(S.(name))
        value = double(S.(name));
    else
        value = NaN;
    end
end

function S = emptyRegionStageSnapshotStruct()
    S = struct([]);
end

function Row = emptyStageSnapshotRow()
    Row = struct( ...
        'problem',"", ...
        'run',NaN, ...
        'seed',NaN, ...
        'target_FE',NaN, ...
        'actual_FE',NaN, ...
        'generation',NaN, ...
        'gan_iter_used',NaN, ...
        'train_z_sigma',NaN, ...
        'sample_z_sigma',NaN, ...
        'train_count',NaN, ...
        'prev_bmem_candidate_count',NaN, ...
        'prev_bmem_survivor_count',NaN, ...
        'raw_generated_count',NaN, ...
        'feasible_rate',NaN, ...
        'gap_ratio50',NaN, ...
        'gap_ratio90',NaN, ...
        'near_boundary_rate_gap1',NaN, ...
        'better_than_random_gap_rate',NaN, ...
        'bdist50_true',NaN, ...
        'bwidth90_10_true',NaN, ...
        'bcover_eps_true',NaN, ...
        'train_width50',NaN, ...
        'train_width90',NaN, ...
        'gen_width50',NaN, ...
        'gen_width90',NaN, ...
        'gen_to_train_dist50',NaN, ...
        'gen_to_train_dist90',NaN, ...
        'offspringG_survival_rate',NaN, ...
        'critic_train_gap',NaN, ...
        'critic_holdout_gap',NaN, ...
        'generated_critic_score_mean',NaN, ...
        'sample_feasible_count',NaN, ...
        'sample_infeasible_count',NaN);
end
