function BranchSummary = run_CBS_RegionWGAN_GP_fixmd_branches( ...
        rootOutDir,branchNames,workerCount,problemNames,N,D,maxFE,runIds)
%RUN_CBS_REGIONWGAN_GP_FIXMD_BRANCHES Run fix.md validation branches.
%   All default branches keep the exact CBS_RegionWGAN_GP mainline surface:
%   queryMode=random_all_w, prevBMemMode=prev1_fair_union,
%   sampleSigma=0.3, zDim=6, prescreen=1 unless the branch name says
%   otherwise. Branches only prepare comparison algorithms and diagnostics;
%   they do not promote any candidate into the mainline.

    repoRoot = locateFixmdRepoRoot();
    addpath(genpath(repoRoot));
    if nargin < 1 || isempty(rootOutDir)
        rootOutDir = fullfile(repoRoot,'Data','CBS_RegionGAN_compare', ...
            ['fixmd_branches_',char(datetime('now','Format','yyyyMMdd_HHmmss'))]);
    end
    if nargin < 2 || isempty(branchNames)
        branchNames = defaultFixmdBranchNames();
    end
    if nargin < 3 || isempty(workerCount)
        workerCount = 10;
    end
    if nargin < 4 || isempty(problemNames)
        problemNames = ["LIRCMOP5_BC";"LIRCMOP6_BC";"LIRCMOP7_BC"; ...
            "LIRCMOP8_BC";"LIRCMOP9_BC";"LIRCMOP10_BC"];
    end
    if nargin < 5 || isempty(N)
        N = 100;
    end
    if nargin < 6
        D = [];
    end
    if nargin < 7 || isempty(maxFE)
        maxFE = 100000;
    end
    if nargin < 8 || isempty(runIds)
        runIds = 1 : 3;
    end

    branchNames = string(branchNames(:)');
    if ischar(problemNames)
        problemNames = string(problemNames);
    else
        problemNames = string(problemNames(:));
    end
    stageTargets = [10000 30000 50000 70000 100000];
    if ~isfolder(rootOutDir)
        mkdir(rootOutDir);
    end

    Branches = fixmdBranchSpecs();
    Rows = repmat(emptyFixmdBranchRow(),numel(branchNames),1);
    for i = 1 : numel(branchNames)
        name = branchNames(i);
        if ~isfield(Branches,char(name))
            error('CBSRegionWGAN:UnknownFixmdBranch', ...
                'Unknown FixMD branch: %s.',name);
        end
        Branch = Branches.(char(name));
        outDir = fullfile(rootOutDir,char(name));
        Rows(i) = branchRowFromSpec(Branch,outDir);
        if branchComplete(outDir,numel(problemNames),numel(runIds), ...
                numel(stageTargets))
            Rows(i).status = "skipped_complete";
            Rows(i) = fillBranchCounts(Rows(i),outDir);
            fprintf('[%d/%d] %s already complete, skipped.\n', ...
                i,numel(branchNames),char(name));
            continue;
        end

        fprintf('[%d/%d] running %s -> %s\n',i,numel(branchNames), ...
            char(name),outDir);
        try
            Options = struct( ...
                'algorithmClass',"CBS_RegionWGAN_GP", ...
                'queryMode',"random_all_w", ...
                'prevBMemMode',"prev1_fair_union", ...
                'bmemBandMode',"current", ...
                'bandMaxAnchorsPerRef',[], ...
                'captureRun',3, ...
                'plotRun',0, ...
                'drawFigures',false, ...
                'stageTargets',stageTargets, ...
                'algorithmParams',{wganParams(Branch)}, ...
                'sampleZMode',"random", ...
                'trainZMode',"random", ...
                'sigma',1.0, ...
                'trainSigma',1.0, ...
                'sampleSigma',0.3, ...
                'ganIterSchedule',Branch.ganIterSchedule, ...
                'ganIterStart',Branch.ganIterStart, ...
                'ganIterEnd',Branch.ganIterEnd, ...
                'prescreenMultiplier',Branch.prescreenMultiplier, ...
                'trainTriggerMode',Branch.trainTriggerMode, ...
                'trainTriggerDelta',Branch.trainTriggerDelta);
            run_CBS_RegionCGAN_training_diagnostics(outDir,workerCount, ...
                problemNames,N,D,maxFE,runIds,Options);
            Rows(i).status = "ok";
            Rows(i) = fillBranchCounts(Rows(i),outDir);
        catch err
            Rows(i).status = "failed";
            Rows(i).error_message = string(getReport(err,'extended', ...
                'hyperlinks','off'));
            fprintf('[%d/%d] %s failed:\n%s\n',i,numel(branchNames), ...
                char(name),char(Rows(i).error_message));
        end
        BranchSummary = struct2table(Rows);
        writetable(BranchSummary,fullfile(rootOutDir,'branch_summary.csv'));
    end
    BranchSummary = struct2table(Rows);
    writetable(BranchSummary,fullfile(rootOutDir,'branch_summary.csv'));
    fprintf('FixMD branches written to: %s\n',rootOutDir);
end

function repoRoot = locateFixmdRepoRoot()
    repoRoot = fileparts(mfilename('fullpath'));
    while ~isempty(repoRoot) && ~isfile(fullfile(repoRoot,'platemo.m'))
        parent = fileparts(repoRoot);
        if strcmp(parent,repoRoot)
            break;
        end
        repoRoot = parent;
    end
    if ~isfile(fullfile(repoRoot,'platemo.m'))
        error('CBSRegionWGAN:FixmdRootNotFound', ...
            'Unable to locate PlatEMO root from run_CBS_RegionWGAN_GP_fixmd_branches.m.');
    end
end

function names = defaultFixmdBranchNames()
    names = [ ...
        "fixmd_diag_baseline", ...
        "fixmd_train_gap1_iter50", ...
        "fixmd_train_gap2_iter50", ...
        "fixmd_train_gap1_iter75", ...
        "fixmd_train_gap2_iter75", ...
        "fixmd_train_gap2_delta20_iter50", ...
        "fixmd_train_gap2_delta20_boost75", ...
        "fixmd_prescreen1_fixed50", ...
        "fixmd_prescreen8_fixed50", ...
        "fixmd_prescreen8_delta20_boost75"];
end

function Branches = fixmdBranchSpecs()
    Defaults = CBS_RegionWGAN_GP.mainlineDefaults();
    Base = struct( ...
        'name',"", ...
        'hypothesis',"baseline diagnostics", ...
        'trainGap',Defaults.trainGap, ...
        'ganIter',Defaults.ganIter, ...
        'zDim',Defaults.zDim, ...
        'nCritic',Defaults.nCritic, ...
        'prescreenMultiplier',1, ...
        'trainTriggerMode',"off", ...
        'trainTriggerDelta',0.20, ...
        'ganIterSchedule',"fixed", ...
        'ganIterStart',[], ...
        'ganIterEnd',[]);

    Branches = struct();
    Branches.fixmd_diag_baseline = withFields(Base, ...
        "fixmd_diag_baseline",1,50,1,"off","fixed",[],[], ...
        "experiment0: diagnostics-only exact mainline baseline");
    Branches.fixmd_train_gap1_iter50 = withFields(Base, ...
        "fixmd_train_gap1_iter50",1,50,1,"off","fixed",[],[], ...
        "experiment1 baseline: trainGap=1");
    Branches.fixmd_train_gap2_iter50 = withFields(Base, ...
        "fixmd_train_gap2_iter50",2,50,1,"off","fixed",[],[], ...
        "experiment1 candidate: trainGap=2");
    Branches.fixmd_train_gap1_iter75 = withFields(Base, ...
        "fixmd_train_gap1_iter75",1,75,1,"off","fixed",[],[], ...
        "experiment2 candidate: ganIter=75 with trainGap=1");
    Branches.fixmd_train_gap2_iter75 = withFields(Base, ...
        "fixmd_train_gap2_iter75",2,75,1,"off","fixed",[],[], ...
        "experiment2 candidate: ganIter=75 with trainGap=2");
    Branches.fixmd_train_gap2_delta20_iter50 = withFields(Base, ...
        "fixmd_train_gap2_delta20_iter50",2,50,1, ...
        "deltaTrainCount20","fixed",[],[], ...
        "experiment3: trainGap=2 plus data-change trigger");
    Branches.fixmd_train_gap2_delta20_boost75 = withFields(Base, ...
        "fixmd_train_gap2_delta20_boost75",2,50,1, ...
        "deltaTrainCount20","two_level_data_change",75,50, ...
        "experiment3: data-change trigger plus 75/50 two-level ganIter");
    Branches.fixmd_prescreen1_fixed50 = withFields(Base, ...
        "fixmd_prescreen1_fixed50",1,50,1,"off","fixed",[],[], ...
        "experiment4 control: critic score diagnostics without prescreen");
    Branches.fixmd_prescreen8_fixed50 = withFields(Base, ...
        "fixmd_prescreen8_fixed50",1,50,8,"off","fixed",[],[], ...
        "experiment4: critic prescreen=8 under fixed ganIter=50");
    Branches.fixmd_prescreen8_delta20_boost75 = withFields(Base, ...
        "fixmd_prescreen8_delta20_boost75",2,50,8, ...
        "deltaTrainCount20","two_level_data_change",75,50, ...
        "experiment4 stress branch: prescreen=8 with trigger/two-level training");
end

function S = withFields(Base,name,trainGap,ganIter,prescreenMultiplier, ...
        triggerMode,iterSchedule,iterStart,iterEnd,hypothesis)
    S = Base;
    S.name = string(name);
    S.trainGap = double(trainGap);
    S.ganIter = double(ganIter);
    S.prescreenMultiplier = double(prescreenMultiplier);
    S.trainTriggerMode = string(triggerMode);
    S.ganIterSchedule = string(iterSchedule);
    S.ganIterStart = iterStart;
    S.ganIterEnd = iterEnd;
    S.hypothesis = string(hypothesis);
end

function Params = wganParams(Branch)
    Defaults = CBS_RegionWGAN_GP.mainlineDefaults();
    Params = { ...
        Branch.trainGap, ...
        Defaults.archiveGap, ...
        Defaults.nGen, ...
        Branch.zDim, ...
        Branch.ganIter, ...
        Defaults.ganMiniBatch, ...
        Defaults.ganLrD, ...
        Defaults.ganLrG, ...
        Defaults.frontDepth, ...
        Defaults.pairNeighborRefRadius, ...
        Defaults.refDivisor, ...
        Defaults.minBoundaryLength, ...
        Defaults.queryPerCondition, ...
        Defaults.gpLambda, ...
        Branch.nCritic, ...
        Defaults.maxAnchorsPerRef, ...
        Defaults.minGANTrainCount};
end

function Row = branchRowFromSpec(Branch,outDir)
    Row = emptyFixmdBranchRow();
    Row.branch = Branch.name;
    Row.status = "pending";
    Row.out_dir = string(outDir);
    Row.hypothesis = Branch.hypothesis;
    Row.query_mode = "random_all_w";
    Row.train_gap = double(Branch.trainGap);
    Row.gan_iter = double(Branch.ganIter);
    Row.z_dim = double(Branch.zDim);
    Row.sample_sigma = 0.3;
    Row.prescreen_multiplier = double(Branch.prescreenMultiplier);
    Row.train_trigger_mode = Branch.trainTriggerMode;
    Row.train_trigger_delta = double(Branch.trainTriggerDelta);
    Row.gan_iter_schedule = Branch.ganIterSchedule;
    Row.gan_iter_start = doubleOrNaN(Branch.ganIterStart);
    Row.gan_iter_end = doubleOrNaN(Branch.ganIterEnd);
end

function yes = branchComplete(outDir,problemCount,runCount,stageCount)
    summaryFile = fullfile(outDir,'run_summary.csv');
    stageFile = fullfile(outDir,'stage_snapshots_all.csv');
    yes = isfile(summaryFile) && isfile(stageFile) && ...
        countTableRows(summaryFile) == problemCount*runCount && ...
        countOkRunRows(summaryFile) == problemCount*runCount && ...
        countTableRows(stageFile) == problemCount*stageCount;
end

function Row = fillBranchCounts(Row,outDir)
    Row.run_count = countTableRows(fullfile(outDir,'run_summary.csv'));
    Row.ok_run_count = countOkRunRows(fullfile(outDir,'run_summary.csv'));
    Row.stage_snapshot_count = countTableRows(fullfile(outDir, ...
        'stage_snapshots_all.csv'));
    Row.event_count = countTableRows(fullfile(outDir, ...
        'event_summary_all.csv'));
end

function n = countTableRows(file)
    n = 0;
    if ~isfile(file)
        return;
    end
    fid = fopen(file,'r');
    cleanup = onCleanup(@()fclose(fid));
    while true
        line = fgetl(fid);
        if ~ischar(line)
            break;
        end
        if strlength(string(strtrim(line))) > 0
            n = n + 1;
        end
    end
    n = max(0,n - 1);
end

function n = countOkRunRows(file)
    n = 0;
    if ~isfile(file)
        return;
    end
    T = readtable(file,'TextType','string','Delimiter',',', ...
        'ReadVariableNames',true,'VariableNamingRule','preserve');
    if ismember("status",string(T.Properties.VariableNames))
        n = sum(T.status == "ok");
    end
end

function value = doubleOrNaN(value)
    if isempty(value)
        value = NaN;
    else
        value = double(value);
        if isempty(value) || ~isfinite(value(1))
            value = NaN;
        else
            value = value(1);
        end
    end
end

function Row = emptyFixmdBranchRow()
    Row = struct( ...
        'branch',"", ...
        'status',"pending", ...
        'out_dir',"", ...
        'hypothesis',"", ...
        'query_mode',"", ...
        'train_gap',NaN, ...
        'gan_iter',NaN, ...
        'z_dim',NaN, ...
        'sample_sigma',NaN, ...
        'prescreen_multiplier',NaN, ...
        'train_trigger_mode',"", ...
        'train_trigger_delta',NaN, ...
        'gan_iter_schedule',"", ...
        'gan_iter_start',NaN, ...
        'gan_iter_end',NaN, ...
        'run_count',0, ...
        'ok_run_count',0, ...
        'stage_snapshot_count',0, ...
        'event_count',0, ...
        'error_message',"");
end
