function BranchSummary = run_CBS_RegionWGAN_GP_c_vs_frontdepth1_plot_branches(rootOutDir,workerCount)
%RUN_CBS_REGIONWGAN_GP_C_VS_FRONTDEPTH1_PLOT_BRANCHES Plot C vs frontDepth=1.
%   Runs the current C mainline and the frontDepth=1 branch for run=1 only.
%   Plot settings follow the existing diagnostics: stage targets are
%   10000/30000/50000/70000/100000 and domain-boundary figures are saved.

    repoRoot = locatePlotCompareRepoRoot();
    addpath(genpath(repoRoot));
    if nargin < 1 || isempty(rootOutDir)
        rootOutDir = fullfile(repoRoot,'Data','CBS_RegionGAN_compare', ...
            ['c_vs_frontdepth1_figures_', ...
            char(datetime('now','Format','yyyyMMdd_HHmmss'))]);
    end
    if nargin < 2 || isempty(workerCount)
        workerCount = 10;
    end

    problems = ["LIRCMOP5_BC";"LIRCMOP6_BC";"LIRCMOP7_BC"; ...
        "LIRCMOP8_BC";"LIRCMOP9_BC";"LIRCMOP10_BC"];
    stageTargets = [10000 30000 50000 70000 100000];
    runIds = 1;
    Defaults = CBS_RegionWGAN_GP.mainlineDefaults();
    Branches = [ ...
        makePlotBranch("C_control",Defaults.frontDepth); ...
        makePlotBranch("C_frontDepth1",1)];

    if ~isfolder(rootOutDir)
        mkdir(rootOutDir);
    end

    Rows = repmat(emptyPlotCompareRow(),numel(Branches),1);
    for i = 1 : numel(Branches)
        Branch = Branches(i);
        outDir = fullfile(rootOutDir,char(Branch.name));
        Rows(i) = rowFromPlotBranch(Branch,outDir,Defaults);

        if branchComplete(outDir,numel(problems),numel(runIds), ...
                numel(stageTargets))
            Rows(i).status = "skipped_complete";
            Rows(i) = fillPlotCompareCounts(Rows(i),outDir);
            fprintf('[%d/%d] %s already complete, skipped.\n', ...
                i,numel(Branches),char(Branch.name));
            writePlotCompareSummary(Rows,rootOutDir);
            continue;
        end

        fprintf('[%d/%d] running %s -> %s\n',i,numel(Branches), ...
            char(Branch.name),outDir);
        try
            Options = struct( ...
                'algorithmClass',"CBS_RegionWGAN_GP", ...
                'queryMode',Defaults.queryMode, ...
                'conditionMode',"region", ...
                'prevBMemMode',Defaults.prevBMemMode, ...
                'bmemBandMode',Defaults.bmemBandMode, ...
                'bandMaxAnchorsPerRef',[], ...
                'captureRun',1, ...
                'plotRun',1, ...
                'drawFigures',true, ...
                'stageTargets',stageTargets, ...
                'algorithmParams',{wganPlotParams(Defaults,Branch)}, ...
                'sampleZMode',"random", ...
                'trainZMode',"random", ...
                'sigma',1.0, ...
                'trainSigma',1.0, ...
                'sampleSigma',Defaults.sampleSigma, ...
                'ganIterSchedule',"fixed", ...
                'ganIterStart',[], ...
                'ganIterEnd',[], ...
                'prescreenMultiplier',1, ...
                'trainTriggerMode',"off", ...
                'trainTriggerDelta',0.2);
            run_CBS_RegionCGAN_training_diagnostics(outDir,workerCount, ...
                problems,100,[],100000,runIds,Options);
            redraw_CBS_RegionCGAN_domain_figures(outDir, ...
                fullfile(outDir,'domain_figures_all'));
            Rows(i).status = "ok";
            Rows(i) = fillPlotCompareCounts(Rows(i),outDir);
        catch err
            Rows(i).status = "failed";
            Rows(i).error_message = string(getReport(err,'extended', ...
                'hyperlinks','off'));
            fprintf('[%d/%d] %s failed:\n%s\n',i,numel(Branches), ...
                char(Branch.name),char(Rows(i).error_message));
        end
        writePlotCompareSummary(Rows,rootOutDir);
    end

    BranchSummary = writePlotCompareSummary(Rows,rootOutDir);
    fprintf('C vs frontDepth=1 plot branches written to: %s\n',rootOutDir);
end

function repoRoot = locatePlotCompareRepoRoot()
    repoRoot = fileparts(which('platemo'));
    if ~isempty(repoRoot)
        return;
    end
    repoRoot = fileparts(mfilename('fullpath'));
    while ~isempty(repoRoot) && ~isfile(fullfile(repoRoot,'platemo.m'))
        parent = fileparts(repoRoot);
        if strcmp(parent,repoRoot)
            break;
        end
        repoRoot = parent;
    end
    if ~isfile(fullfile(repoRoot,'platemo.m'))
        error('CBSRegionWGAN:PlotCompareRootNotFound', ...
            'Unable to locate PlatEMO root.');
    end
end

function Branch = makePlotBranch(name,frontDepth)
    Branch = struct( ...
        'name',string(name), ...
        'frontDepth',double(frontDepth));
end

function Params = wganPlotParams(Defaults,Branch)
    Params = { ...
        Defaults.trainGap, ...
        Defaults.archiveGap, ...
        Defaults.nGen, ...
        Defaults.zDim, ...
        Defaults.ganIter, ...
        Defaults.ganMiniBatch, ...
        Defaults.ganLrD, ...
        Defaults.ganLrG, ...
        Branch.frontDepth, ...
        Defaults.pairNeighborRefRadius, ...
        Defaults.refDivisor, ...
        Defaults.minBoundaryLength, ...
        Defaults.queryPerCondition, ...
        Defaults.gpLambda, ...
        Defaults.nCritic, ...
        Defaults.maxAnchorsPerRef, ...
        Defaults.minGANTrainCount};
end

function Row = rowFromPlotBranch(Branch,outDir,Defaults)
    Row = emptyPlotCompareRow();
    Row.branch = Branch.name;
    Row.status = "pending";
    Row.out_dir = string(outDir);
    Row.query_mode = Defaults.queryMode;
    Row.prev_bmem_mode = Defaults.prevBMemMode;
    Row.condition_mode = "region";
    Row.front_depth = double(Branch.frontDepth);
    Row.gan_iter = double(Defaults.ganIter);
    Row.n_critic = double(Defaults.nCritic);
    Row.sample_sigma = double(Defaults.sampleSigma);
    Row.capture_run = 1;
    Row.plot_run = 1;
end

function BranchSummary = writePlotCompareSummary(Rows,rootOutDir)
    BranchSummary = struct2table(Rows);
    writetable(BranchSummary,fullfile(rootOutDir,'branch_summary.csv'));
end

function yes = branchComplete(outDir,expectedRuns,~,expectedStages)
    yes = false;
    runFile = fullfile(outDir,'run_summary.csv');
    stageFile = fullfile(outDir,'stage_snapshots_all.csv');
    figureFile = fullfile(outDir,'figure_manifest.csv');
    domainFigureFile = fullfile(outDir,'domain_figures_all', ...
        'domain_figure_manifest.csv');
    if ~isfile(runFile) || ~isfile(stageFile) || ~isfile(figureFile) || ...
            ~isfile(domainFigureFile)
        return;
    end
    try
        Runs = readCsvTable(runFile);
        Stages = readCsvTable(stageFile);
        Figures = readCsvTable(figureFile);
        DomainFigures = readCsvTable(domainFigureFile);
        yes = height(Runs) == expectedRuns && ...
            all(string(Runs.status) == "ok") && ...
            height(Stages) == expectedRuns*expectedStages && ...
            height(Figures) == expectedRuns*expectedStages && ...
            height(DomainFigures) == expectedRuns*expectedStages;
    catch
        yes = false;
    end
end

function Row = fillPlotCompareCounts(Row,outDir)
    Row.run_count = countRows(fullfile(outDir,'run_summary.csv'));
    Row.ok_run_count = countOkRuns(fullfile(outDir,'run_summary.csv'));
    Row.stage_snapshot_count = countRows(fullfile(outDir, ...
        'stage_snapshots_all.csv'));
    Row.event_count = countRows(fullfile(outDir,'event_summary_all.csv'));
    Row.figure_count = countRows(fullfile(outDir,'figure_manifest.csv'));
    Row.domain_figure_count = countRows(fullfile(outDir,'domain_figures_all', ...
        'domain_figure_manifest.csv'));
    Row.has_true_boundary_metrics = hasTrueBoundaryMetrics(outDir);
end

function yes = hasTrueBoundaryMetrics(outDir)
    yes = false;
    file = fullfile(outDir,'event_summary_all.csv');
    if ~isfile(file)
        return;
    end
    fid = fopen(file,'r');
    if fid < 0
        return;
    end
    cleanup = onCleanup(@()fclose(fid));
    header = fgetl(fid);
    if ~ischar(header)
        return;
    end
    vars = split(string(header),",");
    yes = all(ismember(["bdist50_true","bwidth90_10_true", ...
        "bcover_eps_true"],vars));
end

function n = countRows(file)
    n = 0;
    if ~isfile(file)
        return;
    end
    try
        T = readCsvTable(file);
        n = height(T);
    catch
        n = 0;
    end
end

function n = countOkRuns(file)
    n = 0;
    if ~isfile(file)
        return;
    end
    try
        T = readCsvTable(file);
        if any(strcmp('status',T.Properties.VariableNames))
            n = sum(string(T.status) == "ok");
        end
    catch
        n = 0;
    end
end

function Row = emptyPlotCompareRow()
    Row = struct( ...
        'branch',"", ...
        'status',"pending", ...
        'out_dir',"", ...
        'query_mode',"", ...
        'prev_bmem_mode',"", ...
        'condition_mode',"", ...
        'front_depth',NaN, ...
        'gan_iter',NaN, ...
        'n_critic',NaN, ...
        'sample_sigma',NaN, ...
        'capture_run',NaN, ...
        'plot_run',NaN, ...
        'run_count',0, ...
        'ok_run_count',0, ...
        'stage_snapshot_count',0, ...
        'event_count',0, ...
        'figure_count',0, ...
        'domain_figure_count',0, ...
        'has_true_boundary_metrics',false, ...
        'error_message',"");
end

function T = readCsvTable(file)
    Options = detectImportOptions(file,'Delimiter',',');
    T = readtable(file,Options);
end
