function BranchSummary = run_CBS_RegionWGAN_GP_iter50_ncritic5_plot_branch(rootOutDir,requestedWorkerCount)
%RUN_CBS_REGIONWGAN_GP_ITER50_NCRITIC5_PLOT_BRANCH Plot A_current_50x5.
%   Runs ganIter=50 and nCritic=5 for run=1 only. The requested worker
%   count is treated as an upper bound; with six problems and one run, the
%   actual pool size is capped at six to avoid idle workers.

    repoRoot = locateIter50Ncritic5RepoRoot();
    addpath(genpath(repoRoot));
    if nargin < 1 || isempty(rootOutDir)
        rootOutDir = fullfile(repoRoot,'Data','CBS_RegionGAN_compare', ...
            ['iter50_ncritic5_figures_', ...
            char(datetime('now','Format','yyyyMMdd_HHmmss'))]);
    end
    if nargin < 2 || isempty(requestedWorkerCount)
        requestedWorkerCount = 10;
    end

    problems = ["LIRCMOP5_BC";"LIRCMOP6_BC";"LIRCMOP7_BC"; ...
        "LIRCMOP8_BC";"LIRCMOP9_BC";"LIRCMOP10_BC"];
    runIds = 1;
    stageTargets = [10000 30000 50000 70000 100000];
    taskCount = numel(problems)*numel(runIds);
    actualWorkerCount = min(max(1,round(double(requestedWorkerCount))), ...
        taskCount);

    Defaults = CBS_RegionWGAN_GP.mainlineDefaults();
    branchName = "A_current_50x5";
    outDir = fullfile(rootOutDir,char(branchName));
    if ~isfolder(rootOutDir)
        mkdir(rootOutDir);
    end

    Row = emptyIter50Ncritic5Row();
    Row.branch = branchName;
    Row.status = "pending";
    Row.out_dir = string(outDir);
    Row.query_mode = Defaults.queryMode;
    Row.prev_bmem_mode = Defaults.prevBMemMode;
    Row.condition_mode = "region";
    Row.gan_iter = 50;
    Row.n_critic = 5;
    Row.front_depth = double(Defaults.frontDepth);
    Row.sample_sigma = double(Defaults.sampleSigma);
    Row.requested_worker_count = double(requestedWorkerCount);
    Row.actual_worker_count = double(actualWorkerCount);
    Row.task_count = double(taskCount);
    Row.capture_run = 1;
    Row.plot_run = 1;

    try
        Options = struct( ...
            'algorithmClass',"CBS_RegionWGAN_GP", ...
            'queryMode',Defaults.queryMode, ...
            'conditionMode',"region", ...
            'prevBMemMode',Defaults.prevBMemMode, ...
            'bmemBandMode',Defaults.bmemBandMode, ...
            'bandMaxAnchorsPerRef',[], ...
            'captureRun',1, ...
            'plotRun',1, ...
            'drawFigures',true, ...
            'stageTargets',stageTargets, ...
            'algorithmParams',{wganIter50Ncritic5Params(Defaults)}, ...
            'sampleZMode',"random", ...
            'trainZMode',"random", ...
            'sigma',1.0, ...
            'trainSigma',1.0, ...
            'sampleSigma',Defaults.sampleSigma, ...
            'ganIterSchedule',"fixed", ...
            'ganIterStart',[], ...
            'ganIterEnd',[], ...
            'prescreenMultiplier',1, ...
            'trainTriggerMode',"off", ...
            'trainTriggerDelta',0.2);
        run_CBS_RegionCGAN_training_diagnostics(outDir,actualWorkerCount, ...
            problems,100,[],100000,runIds,Options);
        redraw_CBS_RegionCGAN_domain_figures(outDir, ...
            fullfile(outDir,'domain_figures_all'));
        Row.status = "ok";
        Row = fillIter50Ncritic5Counts(Row,outDir);
    catch err
        Row.status = "failed";
        Row.error_message = string(getReport(err,'extended', ...
            'hyperlinks','off'));
        fprintf('%s failed:\n%s\n',char(branchName),char(Row.error_message));
    end

    BranchSummary = struct2table(Row);
    writetable(BranchSummary,fullfile(rootOutDir,'branch_summary.csv'));
    fprintf('iter50 nCritic5 plot branch written to: %s\n',rootOutDir);
end

function repoRoot = locateIter50Ncritic5RepoRoot()
    repoRoot = fileparts(which('platemo'));
    if ~isempty(repoRoot)
        return;
    end
    repoRoot = fileparts(mfilename('fullpath'));
    while ~isempty(repoRoot) && ~isfile(fullfile(repoRoot,'platemo.m'))
        parent = fileparts(repoRoot);
        if strcmp(parent,repoRoot)
            break;
        end
        repoRoot = parent;
    end
    if ~isfile(fullfile(repoRoot,'platemo.m'))
        error('CBSRegionWGAN:Iter50Ncritic5RootNotFound', ...
            'Unable to locate PlatEMO root.');
    end
end

function Params = wganIter50Ncritic5Params(Defaults)
    Params = { ...
        Defaults.trainGap, ...
        Defaults.archiveGap, ...
        Defaults.nGen, ...
        Defaults.zDim, ...
        50, ...
        Defaults.ganMiniBatch, ...
        Defaults.ganLrD, ...
        Defaults.ganLrG, ...
        Defaults.frontDepth, ...
        Defaults.pairNeighborRefRadius, ...
        Defaults.refDivisor, ...
        Defaults.minBoundaryLength, ...
        Defaults.queryPerCondition, ...
        Defaults.gpLambda, ...
        5, ...
        Defaults.maxAnchorsPerRef, ...
        Defaults.minGANTrainCount};
end

function Row = fillIter50Ncritic5Counts(Row,outDir)
    Row.run_count = countRows(fullfile(outDir,'run_summary.csv'));
    Row.ok_run_count = countOkRuns(fullfile(outDir,'run_summary.csv'));
    Row.stage_snapshot_count = countRows(fullfile(outDir, ...
        'stage_snapshots_all.csv'));
    Row.event_count = countRows(fullfile(outDir,'event_summary_all.csv'));
    Row.figure_count = countRows(fullfile(outDir,'figure_manifest.csv'));
    Row.domain_figure_count = countRows(fullfile(outDir,'domain_figures_all', ...
        'domain_figure_manifest.csv'));
    Row.has_true_boundary_metrics = hasTrueBoundaryMetrics(outDir);
end

function yes = hasTrueBoundaryMetrics(outDir)
    yes = false;
    file = fullfile(outDir,'event_summary_all.csv');
    if ~isfile(file)
        return;
    end
    fid = fopen(file,'r');
    if fid < 0
        return;
    end
    cleanup = onCleanup(@()fclose(fid));
    header = fgetl(fid);
    if ~ischar(header)
        return;
    end
    vars = split(string(header),",");
    yes = all(ismember(["bdist50_true","bwidth90_10_true", ...
        "bcover_eps_true"],vars));
end

function n = countRows(file)
    n = 0;
    if ~isfile(file)
        return;
    end
    try
        T = readCsvTable(file);
        n = height(T);
    catch
        n = 0;
    end
end

function n = countOkRuns(file)
    n = 0;
    if ~isfile(file)
        return;
    end
    try
        T = readCsvTable(file);
        if any(strcmp('status',T.Properties.VariableNames))
            n = sum(string(T.status) == "ok");
        end
    catch
        n = 0;
    end
end

function T = readCsvTable(file)
    Options = detectImportOptions(file,'Delimiter',',');
    T = readtable(file,Options);
end

function Row = emptyIter50Ncritic5Row()
    Row = struct( ...
        'branch',"", ...
        'status',"pending", ...
        'out_dir',"", ...
        'query_mode',"", ...
        'prev_bmem_mode',"", ...
        'condition_mode',"", ...
        'gan_iter',NaN, ...
        'n_critic',NaN, ...
        'front_depth',NaN, ...
        'sample_sigma',NaN, ...
        'requested_worker_count',NaN, ...
        'actual_worker_count',NaN, ...
        'task_count',NaN, ...
        'capture_run',NaN, ...
        'plot_run',NaN, ...
        'run_count',0, ...
        'ok_run_count',0, ...
        'stage_snapshot_count',0, ...
        'event_count',0, ...
        'figure_count',0, ...
        'domain_figure_count',0, ...
        'has_true_boundary_metrics',false, ...
        'error_message',"");
end
