function [outDir,sheetDir,Manifest] = ...
    run_CBS_CGAN_endpoint_epoch50_compare_sheets(outDir)
%RUN_CBS_CGAN_ENDPOINT_EPOCH50_COMPARE_SHEETS Compare thin vs endpoint targets.
%   Runs the retained ref_y adversarial mainline and feasible-endpoint
%   variant, then stitches one comparison sheet per problem.

    rootDir = fileparts(which('platemo'));
    if isempty(rootDir)
        rootDir = pwd;
    end
    addpath(genpath(rootDir));
    if nargin < 1 || isempty(outDir)
        outDir = fullfile(rootDir,'Data','CBS_CGAN', ...
            ['train_quality_endpoint_vs_ref_y_adv_epoch50_', ...
            char(datetime('now','Format','yyyyMMdd_HHmmss'))]);
    end

    Options = struct( ...
        'workerCount',10, ...
        'problemNames',["LIRCMOP5_BC";"LIRCMOP6_BC"; ...
            "LIRCMOP7_BC";"LIRCMOP8_BC";"LIRCMOP9_BC"; ...
            "LIRCMOP10_BC"], ...
        'runIds',1, ...
        'N',100, ...
        'maxFE',100000, ...
        'targets',[10000 30000 50000 70000 100000], ...
        'plotRun',1, ...
        'visualDiagnostics',true, ...
        'plotDiagnosticTrends',false, ...
        'figureKinds',"train_reconstruction", ...
        'settings',[makeMainlineSetting(); makeEndpointSetting()]);

    [Manifest,~,~,~,~] = ...
        run_CBS_CGAN_train_quality_sweep_lir_online(outDir,Options);
    sheetDir = makeEndpointCompareSheets(outDir,true);
end

function S = makeMainlineSetting()
    S = struct( ...
        'setting',"B_ref_y_adv", ...
        'variant',"B_ref_y_adv", ...
        'conditionMode',"ref_y", ...
        'advWeight',1, ...
        'nGen',30, ...
        'zDim',2, ...
        'ganIter',50, ...
        'ganMiniBatch',32, ...
        'trainMode',"iter", ...
        'trainZMode',"zero", ...
        'sampleZMode',"zero", ...
        'maxCandidatePairsPerRef',3, ...
        'boundaryTargetMode',"thin_support", ...
        'networkPreset',"default", ...
        'generatorHidden',[64 64 64], ...
        'discriminatorHidden',[64 64 32]);
end

function S = makeEndpointSetting()
    S = struct( ...
        'setting',"B_ref_y_adv_epoch50_endpoint", ...
        'variant',"B_ref_y_adv_epoch50_endpoint", ...
        'conditionMode',"ref_y", ...
        'advWeight',1, ...
        'nGen',30, ...
        'zDim',2, ...
        'ganIter',50, ...
        'ganMiniBatch',32, ...
        'trainMode',"epoch", ...
        'trainZMode',"zero", ...
        'sampleZMode',"zero", ...
        'maxCandidatePairsPerRef',3, ...
        'boundaryTargetMode',"feasible_endpoint", ...
        'networkPreset',"default", ...
        'generatorHidden',[64 64 64], ...
        'discriminatorHidden',[64 64 32]);
end

function sheetDir = makeEndpointCompareSheets(outDir,cleanupRaw)
    if nargin < 2 || isempty(cleanupRaw)
        cleanupRaw = false;
    end
    manifestFile = fullfile(outDir,'train_quality_sweep_figure_manifest.csv');
    if ~isfile(manifestFile)
        error('CBSEndpointCompare:MissingManifest', ...
            'Endpoint figure manifest not found: %s',manifestFile);
    end
    FigureManifest = readtable(manifestFile,'TextType','string');
    sheetDir = fullfile(outDir,'contact_sheets_endpoint_compare');
    if ~isfolder(sheetDir)
        mkdir(sheetDir);
    end

    problems = unique(string(FigureManifest.problem),'stable');
    targets = unique(double(FigureManifest.target_FE),'stable');
    tileH = 760;
    tileW = 1000;
    gap = 12;
    headerH = 90;
    rowLabelW = 180;
    settings = ["B_ref_y_adv";"B_ref_y_adv_epoch50_endpoint"];
    labels = ["B_ref_y_adv";"feasible endpoint"];
    Rows = repmat(emptySheetRow(),numel(problems),1);

    for p = 1 : numel(problems)
        canvasH = headerH + numel(targets)*tileH + ...
            (numel(targets)+1)*gap;
        canvasW = rowLabelW + numel(settings)*tileW + ...
            (numel(settings)+1)*gap;
        canvas = uint8(255*ones(canvasH,canvasW,3));
        for c = 1 : numel(settings)
            x = rowLabelW + gap + (c-1)*(tileW+gap);
            y = gap;
            canvas = pasteImage(canvas,labelImage(labels(c),tileW, ...
                headerH-gap,20),x,y);
        end
        for r = 1 : numel(targets)
            y = headerH + gap + (r-1)*(tileH+gap);
            canvas = pasteImage(canvas,labelImage("FE="+string(targets(r)), ...
                rowLabelW-gap,tileH,20),gap,y);

            defaultTile = loadSettingTile(FigureManifest,problems(p), ...
                targets(r),settings(1),tileH,tileW);
            x = rowLabelW + gap;
            canvas = pasteImage(canvas,defaultTile,x,y);

            endpointTile = loadSettingTile(FigureManifest,problems(p), ...
                targets(r),settings(2),tileH,tileW);
            x = rowLabelW + gap + tileW + gap;
            canvas = pasteImage(canvas,endpointTile,x,y);
        end
        outFile = fullfile(sheetDir,sprintf( ...
            '%s_default_vs_endpoint_epoch50.png',problems(p)));
        imwrite(canvas,outFile);
        Rows(p).problem = problems(p);
        Rows(p).sheet_file = string(outFile);
        Rows(p).default_source_sheet = string(manifestFile);
        Rows(p).endpoint_manifest_file = string(manifestFile);
    end

    SheetManifest = struct2table(Rows);
    writetable(SheetManifest,fullfile(sheetDir, ...
        'endpoint_compare_sheet_manifest.csv'));

    if cleanupRaw
        rawFiles = unique(string(FigureManifest.figure_file),'stable');
        for i = 1 : numel(rawFiles)
            if isfile(rawFiles(i))
                delete(rawFiles(i));
            end
        end
    end
end

function tile = loadSettingTile(FigureManifest,problem,targetFE,setting,tileH,tileW)
    mask = string(FigureManifest.problem) == problem & ...
        double(FigureManifest.target_FE) == double(targetFE) & ...
        string(FigureManifest.setting) == string(setting);
    files = string(FigureManifest.figure_file(mask));
    if isempty(files) || ~isfile(files(1))
        tile = labelImage("missing "+string(setting),tileW,tileH,28);
    else
        tile = ensureRgb(imread(files(1)));
        tile = imresize(tile,[tileH tileW]);
    end
end

function Row = emptySheetRow()
    Row = struct( ...
        'problem',"", ...
        'sheet_file',"", ...
        'default_source_sheet',"", ...
        'endpoint_manifest_file',"");
end

function img = ensureRgb(img)
    if ndims(img) == 2
        img = repmat(img,1,1,3);
    elseif size(img,3) > 3
        img = img(:,:,1:3);
    end
    if ~isa(img,'uint8')
        img = im2uint8(img);
    end
end

function canvas = pasteImage(canvas,img,x,y)
    [h,w,~] = size(img);
    canvas(y:y+h-1,x:x+w-1,:) = img;
end

function img = labelImage(txt,w,h,fontSize)
    txt = char(txt);
    f = figure('Visible','off','Color','w','Position',[100 100 w h]);
    ax = axes(f,'Position',[0 0 1 1]);
    axis(ax,'off');
    text(ax,0.5,0.5,txt,'Interpreter','none', ...
        'HorizontalAlignment','center','VerticalAlignment','middle', ...
        'FontSize',fontSize,'FontWeight','bold');
    frame = getframe(f);
    img = frame2im(frame);
    close(f);
    img = ensureRgb(img);
    if size(img,1) ~= h || size(img,2) ~= w
        img = imresize(img,[h w]);
    end
end
