function BranchSummary = run_CBS_RegionWGAN_GP_frontier_anneal_branch( ...
        rootOutDir,workerCount,problemNames,N,D,maxFE,runIds,Overrides)
%RUN_CBS_REGIONWGAN_GP_FRONTIER_ANNEAL_BRANCH Run local frontier query branch.
%   This branch keeps the promoted C WGAN-GP mainline unchanged except for
%   queryMode=frontier_anneal. Query conditions are drawn from populated
%   boundary refs and their one-hop unpopulated frontier refs at a 60/40
%   budget split.

    repoRoot = locateRepoRoot();
    addpath(genpath(repoRoot));
    if nargin < 1 || isempty(rootOutDir)
        rootOutDir = fullfile(repoRoot,'Data','CBS_RegionGAN_compare', ...
            ['frontier_anneal_mainline_', ...
            char(datetime('now','Format','yyyyMMdd_HHmmss'))]);
    end
    if nargin < 2 || isempty(workerCount)
        workerCount = 10;
    end
    if nargin < 3 || isempty(problemNames)
        problemNames = ["LIRCMOP5_BC";"LIRCMOP6_BC"; ...
            "LIRCMOP7_BC";"LIRCMOP8_BC";"LIRCMOP9_BC"; ...
            "LIRCMOP10_BC"];
    end
    if nargin < 4 || isempty(N)
        N = 100;
    end
    if nargin < 5
        D = [];
    end
    if nargin < 6 || isempty(maxFE)
        maxFE = 100000;
    end
    if nargin < 7 || isempty(runIds)
        runIds = 1 : 3;
    end
    if nargin < 8 || isempty(Overrides)
        Overrides = struct();
    end

    problemNames = string(problemNames(:));
    Defaults = CBS_RegionWGAN_GP.mainlineDefaults();
    Branch = makeBranch();
    stageTargets = double(overrideValue(Overrides,'stageTargets', ...
        [10000 30000 50000 70000 100000]));
    stageTargets = stageTargets(:)';
    captureRun = overrideValue(Overrides,'captureRun',3);
    plotRun = overrideValue(Overrides,'plotRun',0);
    drawFigures = logical(overrideValue(Overrides,'drawFigures',false));
    redrawDomainFigures = logical(overrideValue(Overrides, ...
        'redrawDomainFigures',drawFigures));

    if ~isfolder(rootOutDir)
        mkdir(rootOutDir);
    end

    outDir = fullfile(rootOutDir,char(Branch.name));
    Row = rowFromBranch(Branch,outDir,Defaults,captureRun,plotRun, ...
        drawFigures);
    if branchComplete(outDir,numel(problemNames),numel(runIds), ...
            numel(stageTargets),drawFigures,Branch.queryMode)
        Row.status = "skipped_complete";
        Row = fillCounts(Row,outDir,Branch.queryMode);
        fprintf('%s already complete, skipped.\n',char(Branch.name));
        BranchSummary = writeSummary(Row,rootOutDir);
        return;
    end

    fprintf('running %s -> %s\n',char(Branch.name),outDir);
    try
        Options = struct( ...
            'algorithmClass',"CBS_RegionWGAN_GP", ...
            'queryMode',Branch.queryMode, ...
            'conditionMode',Branch.conditionMode, ...
            'prevBMemMode',Defaults.prevBMemMode, ...
            'bmemBandMode',Defaults.bmemBandMode, ...
            'bandMaxAnchorsPerRef',Defaults.bandMaxAnchorsPerRef, ...
            'captureRun',captureRun, ...
            'plotRun',plotRun, ...
            'drawFigures',drawFigures, ...
            'stageTargets',stageTargets, ...
            'algorithmParams',{wganParams(Defaults,Overrides)}, ...
            'sampleZMode',"random", ...
            'trainZMode',"random", ...
            'sigma',1.0, ...
            'trainSigma',1.0, ...
            'sampleSigma',Defaults.sampleSigma, ...
            'ganIterSchedule',"fixed", ...
            'ganIterStart',[], ...
            'ganIterEnd',[], ...
            'prescreenMultiplier',1, ...
            'trainTriggerMode',"off", ...
            'trainTriggerDelta',0.2);
        run_CBS_RegionCGAN_training_diagnostics(outDir,workerCount, ...
            problemNames,N,D,maxFE,runIds,Options);
        if redrawDomainFigures
            redraw_CBS_RegionCGAN_domain_figures(outDir, ...
                fullfile(outDir,'domain_figures_all'));
        end
        Row.status = "ok";
        Row = fillCounts(Row,outDir,Branch.queryMode);
    catch err
        Row.status = "failed";
        Row.error_message = string(getReport(err,'extended', ...
            'hyperlinks','off'));
        fprintf('%s failed:\n%s\n',char(Branch.name), ...
            char(Row.error_message));
    end

    BranchSummary = writeSummary(Row,rootOutDir);
    fprintf('frontier-anneal branch written to: %s\n',rootOutDir);
end

function repoRoot = locateRepoRoot()
    repoRoot = fileparts(which('platemo'));
    if ~isempty(repoRoot)
        return;
    end
    repoRoot = fileparts(mfilename('fullpath'));
    while ~isempty(repoRoot) && ~isfile(fullfile(repoRoot,'platemo.m'))
        parent = fileparts(repoRoot);
        if strcmp(parent,repoRoot)
            break;
        end
        repoRoot = parent;
    end
    if ~isfile(fullfile(repoRoot,'platemo.m'))
        error('CBSRegionWGAN:RepoRootNotFound', ...
            'Unable to locate PlatEMO root.');
    end
end

function Branch = makeBranch()
    Branch = struct( ...
        'name',"C_query_frontier_anneal", ...
        'queryMode',"frontier_anneal", ...
        'conditionMode',"region");
end

function Params = wganParams(Defaults,Overrides)
    if isstruct(Overrides) && isfield(Overrides,'algorithmParams') && ...
            ~isempty(Overrides.algorithmParams)
        Params = Overrides.algorithmParams;
        return;
    end
    Params = { ...
        Defaults.trainGap, ...
        Defaults.archiveGap, ...
        Defaults.nGen, ...
        Defaults.zDim, ...
        Defaults.ganIter, ...
        Defaults.ganMiniBatch, ...
        Defaults.ganLrD, ...
        Defaults.ganLrG, ...
        Defaults.frontDepth, ...
        Defaults.pairNeighborRefRadius, ...
        Defaults.refDivisor, ...
        Defaults.minBoundaryLength, ...
        Defaults.queryPerCondition, ...
        Defaults.gpLambda, ...
        Defaults.nCritic, ...
        Defaults.maxAnchorsPerRef, ...
        Defaults.minGANTrainCount};
end

function Row = rowFromBranch(Branch,outDir,Defaults,captureRun,plotRun, ...
        drawFigures)
    Row = emptyBranchRow();
    Row.branch = Branch.name;
    Row.status = "pending";
    Row.out_dir = string(outDir);
    Row.query_mode = Branch.queryMode;
    Row.condition_mode = Branch.conditionMode;
    Row.prev_bmem_mode = Defaults.prevBMemMode;
    Row.bmem_band_mode = Defaults.bmemBandMode;
    Row.front_depth = double(Defaults.frontDepth);
    Row.gan_iter = double(Defaults.ganIter);
    Row.n_critic = double(Defaults.nCritic);
    Row.critic_updates = double(Defaults.ganIter*Defaults.nCritic);
    Row.generator_updates = double(Defaults.ganIter);
    Row.sample_sigma = double(Defaults.sampleSigma);
    Row.capture_run = double(captureRun);
    Row.plot_run = double(plotRun);
    Row.draw_figures = logical(drawFigures);
end

function BranchSummary = writeSummary(Row,rootOutDir)
    BranchSummary = struct2table(Row);
    writetable(BranchSummary,fullfile(rootOutDir,'branch_summary.csv'));
end

function yes = branchComplete(outDir,problemCount,runCount,stageCount, ...
        requireFigures,queryMode)
    runFile = fullfile(outDir,'run_summary.csv');
    stageFile = fullfile(outDir,'stage_snapshots_all.csv');
    eventFile = fullfile(outDir,'event_summary_all.csv');
    yes = isfile(runFile) && isfile(stageFile) && isfile(eventFile) && ...
        countTableRows(runFile) == problemCount*runCount && ...
        countOkRunRows(runFile) == problemCount*runCount && ...
        countTableRows(stageFile) == problemCount*stageCount && ...
        hasTrueBoundaryColumns(stageFile) && ...
        hasTrueBoundaryColumns(eventFile) && ...
        hasQueryMode(stageFile,queryMode) && ...
        hasQueryMode(eventFile,queryMode);
    if yes && requireFigures
        yes = isfile(fullfile(outDir,'figure_manifest.csv')) && ...
            isfile(fullfile(outDir,'domain_figures_all', ...
            'domain_figure_manifest.csv'));
    end
end

function Row = fillCounts(Row,outDir,queryMode)
    Row.run_count = countTableRows(fullfile(outDir,'run_summary.csv'));
    Row.ok_run_count = countOkRunRows(fullfile(outDir,'run_summary.csv'));
    Row.stage_snapshot_count = countTableRows(fullfile(outDir, ...
        'stage_snapshots_all.csv'));
    Row.event_count = countTableRows(fullfile(outDir, ...
        'event_summary_all.csv'));
    Row.figure_count = countTableRows(fullfile(outDir, ...
        'figure_manifest.csv'));
    Row.domain_figure_count = countTableRows(fullfile(outDir, ...
        'domain_figures_all','domain_figure_manifest.csv'));
    Row.has_true_boundary_metrics = hasTrueBoundaryColumns( ...
        fullfile(outDir,'stage_snapshots_all.csv')) && ...
        hasTrueBoundaryColumns(fullfile(outDir,'event_summary_all.csv'));
    Row.has_frontier_anneal_query = hasQueryMode( ...
        fullfile(outDir,'stage_snapshots_all.csv'),queryMode) && ...
        hasQueryMode(fullfile(outDir,'event_summary_all.csv'),queryMode);
end

function n = countTableRows(file)
    n = 0;
    if ~isfile(file)
        return;
    end
    try
        T = readtable(file,'TextType','string');
        n = height(T);
    catch
        n = 0;
    end
end

function n = countOkRunRows(file)
    n = 0;
    if ~isfile(file)
        return;
    end
    try
        T = readtable(file,'TextType','string');
        if ismember("status",string(T.Properties.VariableNames))
            n = sum(string(T.status) == "ok");
        end
    catch
        n = 0;
    end
end

function yes = hasTrueBoundaryColumns(file)
    yes = false;
    if ~isfile(file)
        return;
    end
    try
        opts = detectImportOptions(file);
        vars = string(opts.VariableNames);
        yes = all(ismember(["bdist50_true","bwidth90_10_true", ...
            "bcover_eps_true"],vars));
    catch
        yes = false;
    end
end

function yes = hasQueryMode(file,queryMode)
    yes = false;
    if ~isfile(file)
        return;
    end
    try
        T = readtable(file,'TextType','string');
        if ismember("query_mode",string(T.Properties.VariableNames))
            values = string(T.query_mode);
            values = values(strlength(values) > 0);
            yes = ~isempty(values) && all(values == string(queryMode));
        end
    catch
        yes = false;
    end
end

function value = overrideValue(Overrides,name,defaultValue)
    if isstruct(Overrides) && isfield(Overrides,name) && ...
            ~isempty(Overrides.(name))
        value = Overrides.(name);
    else
        value = defaultValue;
    end
end

function Row = emptyBranchRow()
    Row = struct( ...
        'branch',"", ...
        'status',"pending", ...
        'out_dir',"", ...
        'query_mode',"", ...
        'condition_mode',"", ...
        'prev_bmem_mode',"", ...
        'bmem_band_mode',"", ...
        'front_depth',NaN, ...
        'gan_iter',NaN, ...
        'n_critic',NaN, ...
        'critic_updates',NaN, ...
        'generator_updates',NaN, ...
        'sample_sigma',NaN, ...
        'capture_run',NaN, ...
        'plot_run',NaN, ...
        'draw_figures',false, ...
        'run_count',0, ...
        'ok_run_count',0, ...
        'stage_snapshot_count',0, ...
        'event_count',0, ...
        'figure_count',0, ...
        'domain_figure_count',0, ...
        'has_true_boundary_metrics',false, ...
        'has_frontier_anneal_query',false, ...
        'error_message',"");
end
