function test_CBS_RegionGAN_provenance()
%TEST_CBS_REGIONGAN_PROVENANCE Verify deterministic scoped provenance.

    repoRoot = fileparts(fileparts(fileparts(fileparts(fileparts( ...
        mfilename('fullpath'))))));
    addpath(genpath(repoRoot));
    Options = struct('algorithmParams',{{1,2,3}}, ...
        'nested',struct('enabled',true));

    P = CBS_RegionGAN_Provenance(repoRoot,Options,9);
    requiredFields = [ ...
        "schema_version","git_sha","git_branch","git_dirty", ...
        "matlab_release","host","worker_count","options_json", ...
        "source_tree_sha256","source_manifest"];
    assert(all(isfield(P,cellstr(requiredFields))), ...
        'Provenance is missing required fields.');
    assert(P.schema_version == "cbs_region_wgan_igd_mainline_v2", ...
        'Provenance schema version must match the experiment contract.');
    assert(strlength(P.git_sha) == 40, ...
        'The repository under test must report a full 40-character Git SHA.');
    assert(strlength(P.git_branch) > 0, ...
        'Git branch provenance must not be empty.');
    assert(islogical(P.git_dirty) && isscalar(P.git_dirty), ...
        'Git dirty provenance must be a logical scalar.');
    assert(strlength(P.matlab_release) > 0 && strlength(P.host) > 0, ...
        'MATLAB release and host provenance must not be empty.');
    assert(P.worker_count == 9, ...
        'Worker count must retain the supplied experiment value.');
    assert(P.options_json == string(jsonencode(Options)), ...
        'JSON-encodable options must use MATLAB jsonencode deterministically.');
    assert(strlength(P.source_tree_sha256) == 64, ...
        'Source-tree SHA-256 must contain 64 hexadecimal characters.');

    Manifest = P.source_manifest;
    assert(istable(Manifest) && height(Manifest) > 0, ...
        'Source manifest must be a nonempty table.');
    assert(isequal(string(Manifest.Properties.VariableNames), ...
            ["relative_path","sha256","bytes"]), ...
        'Source manifest columns must follow the public contract.');
    assert(all(strlength(Manifest.sha256) == 64) && ...
            all(Manifest.bytes > 0), ...
        'Every manifest row must contain a SHA-256 and byte count.');
    paths = string(Manifest.relative_path);
    assert(isequal(paths,sort(paths)) && numel(unique(paths)) == numel(paths), ...
        'Manifest paths must be uniquely and stably sorted.');
    assert(~any(contains(paths,"\")), ...
        'Manifest paths must use forward slashes.');
    assert(~any(endsWith(lower(paths),[".zip",".mat",".png"])), ...
        'Manifest must not hash generated data or binary result artifacts.');

    requiredPaths = [ ...
        "Algorithms/Multi-objective optimization/CBS-CGAN/RunRegionGAN_RC.m"; ...
        "Algorithms/Multi-objective optimization/CBS-CGAN/CBS_RegionWGAN_GP.m"; ...
        "Algorithms/Multi-objective optimization/CBS-CGAN/Support/CBS_RegionGAN_Provenance.m"; ...
        "Algorithms/Multi-objective optimization/CBS-CGAN/Support/run_CBS_RegionWGAN_GP_mainline.m"];
    for problem = 5 : 10
        requiredPaths(end+1,1) = "Problems/Multi-objective optimization/" + ...
            "LIR-CMOP_BC/LIRCMOP" + problem + "_BC.m"; %#ok<AGROW>
    end
    assert(all(ismember(requiredPaths,paths)), ...
        'Manifest must include the algorithm, helper, runner, and six problems.');
    assert(any(contains(paths,"/Support/run_")), ...
        'Manifest must include Support runner/wrapper sources.');

    expectedTreeSHA = sha256Text(join(paths + char(9) + ...
        string(Manifest.sha256) + newline,""));
    assert(P.source_tree_sha256 == expectedTreeSHA, ...
        'Source-tree SHA-256 must match the sorted manifest records.');

    P2 = CBS_RegionGAN_Provenance(repoRoot,Options,9);
    assert(isequal(P.source_manifest,P2.source_manifest) && ...
            P.source_tree_sha256 == P2.source_tree_sha256, ...
        'Repeated provenance calls must produce identical source hashes.');
    PWithSeparator = CBS_RegionGAN_Provenance( ...
        string(repoRoot) + filesep,Options,9);
    assert(isequal(P.source_manifest,PWithSeparator.source_manifest) && ...
            P.source_tree_sha256 == PWithSeparator.source_tree_sha256, ...
        'A trailing file separator must not change provenance paths or hashes.');

    PFallback = CBS_RegionGAN_Provenance(repoRoot, ...
        struct('callback',@sin),9);
    assert(startsWith(PFallback.options_json,"jsonencode_failed:"), ...
        'Unsupported options must produce an explicit fallback string.');

    fprintf('CBS RegionGAN provenance test passed.\n');
end

function value = sha256Text(textValue)
    bytes = unicode2native(char(textValue),'UTF-8');
    digest = java.security.MessageDigest.getInstance('SHA-256');
    digest.update(bytes);
    value = lower(string(reshape(dec2hex(typecast( ...
        digest.digest(),'uint8'),2).',1,[])));
end
