function Summary = render_CBS_PairGuide_training_schedule_detail_figures( ...
        rootPath,campaignName)
%RENDER_CBS_PAIRGUIDE_TRAINING_SCHEDULE_DETAIL_FIGURES Redraw zoomed sheets.
%   This post-processing renderer reads the completed campaign MAT files and
%   writes a separate set of lower-left detail views. It never changes the
%   campaign results, the original figures, or their manifests.

    if nargin < 1 || isempty(rootPath)
        rootPath = fileparts(which('platemo'));
    end
    if nargin < 2 || strlength(string(campaignName)) == 0
        campaignName = "CBS_PairGuide_training_schedule_v1_20260901";
    end
    rootPath = char(rootPath);
    campaignName = string(campaignName);
    campaignDir = fullfile(rootPath,'Data',char(campaignName));
    stages = ["ratio","epoch"];
    layerNames = ["P1","P2","raw 500","selected target", ...
        "selected center","guided child"];
    addCBSPaths(rootPath);

    campaignManifest = fullfile(campaignDir,'campaign_manifest.mat');
    requireFile(campaignManifest,'campaign manifest');
    Campaign = load(campaignManifest,'CampaignProtocol');
    if ~isfield(Campaign,'CampaignProtocol') || ...
            ~isfield(Campaign.CampaignProtocol,'sourceFingerprint')
        error('CBSPairGuide:BadDetailCampaignManifest', ...
            '%s is missing CampaignProtocol.sourceFingerprint.', ...
            campaignManifest);
    end
    Frozen = Campaign.CampaignProtocol.sourceFingerprint;
    assertFrozenSources(rootPath,Frozen);

    sourceFigureDir = fullfile(campaignDir,'figures','training_schedule');
    sourceManifestMAT = fullfile(sourceFigureDir,'figure_manifest.mat');
    sourceManifestCSV = fullfile(sourceFigureDir,'figure_manifest.csv');
    requireFile(sourceManifestMAT,'source figure manifest MAT');
    requireFile(sourceManifestCSV,'source figure manifest CSV');
    Original = load(sourceManifestMAT,'Figures');
    if ~isfield(Original,'Figures') || ...
            ~isstruct(Original.Figures) || numel(Original.Figures) ~= 12
        error('CBSPairGuide:BadDetailFigureManifest', ...
            '%s must contain the 12 source Figures.',sourceManifestMAT);
    end
    sourceProblems = string({Original.Figures.problem});
    problems = unique(sourceProblems,'stable');
    if numel(problems) ~= 6
        error('CBSPairGuide:BadDetailProblemCount', ...
            'Source figure manifest must contain six problems.');
    end

    rendererFile = string(mfilename('fullpath'));
    if ~endsWith(rendererFile,".m")
        rendererFile = rendererFile+".m";
    end
    drawFile = string(which('draw_CBS_CGAN_objective_region'));
    requireFile(drawFile,'objective-region renderer');
    rendererSHA256 = sha256File(rendererFile);
    drawSHA256 = sha256File(drawFile);
    sourceManifestMatSHA256 = sha256File(sourceManifestMAT);
    sourceManifestCsvSHA256 = sha256File(sourceManifestCSV);
    frozenFingerprint = string(Frozen.combinedSHA256);

    outputDir = fullfile(campaignDir,'figures', ...
        'training_schedule_detail_v1');
    ensureFolder(outputDir);
    Figures = repmat(emptyFigureRecord(),12,1);
    Inputs = repmat(emptyInputRecord(),36,1);
    figureRow = 0;
    inputRow = 0;
    for p = 1 : numel(problems)
        problem = problems(p);
        Source = repmat(Original.Figures(1),2,1);
        Bundle = repmat(emptyBundle(),2,1);
        Problem = [];
        problemFile = "";
        for s = 1 : numel(stages)
            Source(s) = selectSourceFigure( ...
                Original.Figures,stages(s),problem);
            if s == 2 && (Source(s).run ~= Source(1).run || ...
                    ~isequal(double(Source(s).targetFE), ...
                        double(Source(1).targetFE)))
                error('CBSPairGuide:DetailCrossStageMismatch', ...
                    '%s source stages disagree on run or target FE.',problem);
            end
            [Bundle(s),Rows] = loadBundle(campaignDir,stages(s), ...
                problem,Source(s));
            for r = 1 : numel(Rows)
                inputRow = inputRow+1;
                Inputs(inputRow) = Rows(r);
            end
            if isempty(Problem)
                constructor = str2func(char(problem));
                Problem = constructor('N',Bundle(s).N, ...
                    'D',Bundle(s).D,'maxFE',1e9,'maxRuntime',Inf);
                if Problem.M ~= Bundle(s).M
                    error('CBSPairGuide:DetailProblemDimension', ...
                        '%s constructor and result objective counts differ.', ...
                        problem);
                end
                problemFile = string(which(char(problem)));
                requireFile(problemFile,'problem constructor');
            elseif any([Problem.M,Problem.N,Problem.D] ~= ...
                    [Bundle(s).M,Bundle(s).N,Bundle(s).D])
                error('CBSPairGuide:DetailCrossStageDimension', ...
                    '%s ratio and epoch results disagree on M/N/D.',problem);
            end
        end
        View = detailView(Bundle);
        problemSHA256 = sha256File(problemFile);
        for s = 1 : numel(stages)
            B = Bundle(s);
            F = Source(s);
            outputFile = fullfile(outputDir,sprintf( ...
                '%s_%s_run%02d_3x10_detail_v1.png', ...
                stages(s),problem,F.run));
            renderSheet(Problem,problem,stages(s),B.armName, ...
                B.armValues,F.run,B.Snapshots,View,outputFile);
            Info = imfinfo(outputFile);
            figureRow = figureRow+1;
            Figures(figureRow) = makeFigureRecord(stages(s),problem,F, ...
                B,View,layerNames,problemFile,problemSHA256, ...
                outputFile,Info);
        end
    end
    if figureRow ~= 12 || inputRow ~= 36
        error('CBSPairGuide:DetailOutputCount', ...
            'Built %d figures and %d inputs; expected 12 and 36.', ...
            figureRow,inputRow);
    end

    finishedAt = string(datetime('now'));
    ManifestRows = repmat(emptyManifestRow(),numel(Figures),1);
    for i = 1 : numel(Figures)
        F = Figures(i);
        ManifestRows(i) = struct( ...
            'stage',F.stage,'problem',F.problem,'run',F.run, ...
            'armName',F.armName,'armValues',numberList(F.armValues), ...
            'targetFE',numberList(F.targetFE), ...
            'snapshotCount',F.snapshotCount, ...
            'viewLower',numberList(F.viewLower(1:F.M)), ...
            'viewUpper',numberList(F.viewUpper(1:F.M)), ...
            'focusCoreLower',numberList(F.focusCoreLower(1:F.M)), ...
            'focusCoreUpper',numberList(F.focusCoreUpper(1:F.M)), ...
            'layerNames',strjoin(F.layerNames,';'), ...
            'layerInViewRates',numberList(F.layerInViewRates), ...
            'layerTotalCounts',numberList(F.layerTotalCounts), ...
            'layerInViewCounts',numberList(F.layerInViewCounts), ...
            'layerClippedCounts',numberList(F.layerClippedCounts), ...
            'frozenSourceFingerprint',frozenFingerprint, ...
            'sourceFigureManifestMatSHA256', ...
                sourceManifestMatSHA256, ...
            'sourceFigureManifestCsvSHA256', ...
                sourceManifestCsvSHA256, ...
            'rendererSHA256',rendererSHA256, ...
            'objectiveRegionRendererSHA256',drawSHA256, ...
            'problemConstructorSHA256',F.problemConstructorSHA256, ...
            'inputFiles',strjoin(F.inputFiles,';'), ...
            'inputSHA256',strjoin(F.inputSHA256,';'), ...
            'file',F.file,'outputSHA256',F.outputSHA256, ...
            'width',F.width,'height',F.height, ...
            'finishedAt',finishedAt);
    end
    DetailManifest = struct2table(ManifestRows);
    InputManifest = struct2table(Inputs);
    Summary = struct( ...
        'schemaVersion',"CBS-PairGuide-training-schedule-detail-v1", ...
        'campaignName',campaignName,'figureCount',numel(Figures), ...
        'expectedFigureCount',12,'panelsPerFigure',30, ...
        'viewRule',strjoin([ ...
            "foreground={P1,P2,target,center,guided}; lower=pooled q0.5%, ", ...
            "upper=q75 across per-panel q95; add 5% span padding; ", ...
            "clamp benchmark objective lower bounds to zero"],""), ...
        'outlierPolicy',"points outside the lower-left detail view are clipped", ...
        'frozenSourceFingerprint',frozenFingerprint, ...
        'sourceFigureManifestMAT',string(sourceManifestMAT), ...
        'sourceFigureManifestMatSHA256',sourceManifestMatSHA256, ...
        'sourceFigureManifestCSV',string(sourceManifestCSV), ...
        'sourceFigureManifestCsvSHA256',sourceManifestCsvSHA256, ...
        'renderer',rendererFile,'rendererSHA256',rendererSHA256, ...
        'objectiveRegionRenderer',drawFile, ...
        'objectiveRegionRendererSHA256',drawSHA256, ...
        'finishedAt',finishedAt);
    manifestMAT = fullfile(outputDir,'detail_manifest.mat');
    manifestCSV = fullfile(outputDir,'detail_manifest.csv');
    writeManifestAtomic(manifestMAT,manifestCSV,Summary,Figures, ...
        DetailManifest,InputManifest);
end

function F = emptyFigureRecord()
    F = struct('stage',"",'problem',"",'run',0,'M',0, ...
        'armName',"",'armValues',zeros(1,3), ...
        'targetFE',zeros(1,10),'actualFE',zeros(3,10), ...
        'viewLower',nan(1,3),'viewUpper',nan(1,3), ...
        'focusCoreLower',nan(1,3),'focusCoreUpper',nan(1,3), ...
        'snapshotCount',0,'layerNames',strings(1,6), ...
        'layerInViewRates',nan(1,6), ...
        'layerTotalCounts',zeros(1,6), ...
        'layerInViewCounts',zeros(1,6), ...
        'layerClippedCounts',zeros(1,6), ...
        'inputFiles',strings(1,3), ...
        'inputSHA256',strings(1,3),'problemConstructor',"", ...
        'problemConstructorSHA256',"",'file',"", ...
        'outputSHA256',"",'width',0,'height',0);
end

function R = emptyInputRecord()
    R = struct('stage',"",'problem',"",'run',0,'armName',"", ...
        'armValue',0,'sourceStage',"",'reused',false, ...
        'snapshotCount',0,'targetFE',"",'actualFE',"", ...
        'inputFile',"",'inputSHA256',"");
end

function R = emptyManifestRow()
    R = struct('stage',"",'problem',"",'run',0,'armName',"", ...
        'armValues',"",'targetFE',"",'snapshotCount',0, ...
        'viewLower',"",'viewUpper',"", ...
        'focusCoreLower',"",'focusCoreUpper',"", ...
        'layerNames',"",'layerInViewRates',"", ...
        'layerTotalCounts',"",'layerInViewCounts',"", ...
        'layerClippedCounts',"", ...
        'frozenSourceFingerprint',"", ...
        'sourceFigureManifestMatSHA256',"", ...
        'sourceFigureManifestCsvSHA256',"",'rendererSHA256',"", ...
        'objectiveRegionRendererSHA256',"", ...
        'problemConstructorSHA256',"",'inputFiles',"", ...
        'inputSHA256',"",'file',"",'outputSHA256',"", ...
        'width',0,'height',0,'finishedAt',"");
end

function B = emptyBundle()
    B = struct('armName',"",'armValues',zeros(1,3), ...
        'Snapshots',{{}},'inputFiles',strings(1,3), ...
        'inputSHA256',strings(1,3),'M',0,'N',0,'D',0);
end

function F = selectSourceFigure(Figures,stage,problem)
    rows = find(string({Figures.stage}) == stage & ...
        string({Figures.problem}) == problem);
    if numel(rows) ~= 1
        error('CBSPairGuide:DetailSourceFigureIdentity', ...
            'Expected one %s %s source figure; found %d.', ...
            stage,problem,numel(rows));
    end
    F = Figures(rows);
    if F.snapshotCount ~= 30 || numel(F.targetFE) ~= 10 || ...
            ~isequal(size(F.actualFE),[3,10])
        error('CBSPairGuide:BadDetailSourceFigure', ...
            '%s %s source metadata is incomplete.',stage,problem);
    end
end

function [B,Rows] = loadBundle(campaignDir,stage,problem,F)
    stageDir = fullfile(campaignDir,char(stage));
    stageManifest = fullfile(stageDir,'campaign_manifest.mat');
    requireFile(stageManifest,'stage campaign manifest');
    M = load(stageManifest,'Protocol','Tasks');
    if ~isfield(M,'Protocol') || ~isfield(M,'Tasks')
        error('CBSPairGuide:BadDetailStageManifest', ...
            '%s must contain Protocol and Tasks.',stageManifest);
    end
    arms = double(M.Protocol.arms(:)');
    armName = string(M.Protocol.armName);
    if numel(arms) ~= 3 || ~isequal(arms,double(F.armValues)) || ...
            armName ~= string(F.armName)
        error('CBSPairGuide:DetailArmMismatch', ...
            '%s %s stage arms disagree with the source figure.', ...
            problem,stage);
    end
    taskProblems = string({M.Tasks.problem});
    taskRuns = double([M.Tasks.run]);
    taskArms = double([M.Tasks.armValue]);
    snapshots = cell(1,3);
    inputFiles = strings(1,3);
    inputSHA256 = strings(1,3);
    dimensions = zeros(3,3);
    Rows = repmat(emptyInputRecord(),3,1);
    for arm = 1 : 3
        tolerance = 64*eps(max(1,abs(arms(arm))));
        rows = find(taskProblems == problem & taskRuns == F.run & ...
            abs(taskArms-arms(arm)) <= tolerance);
        if numel(rows) ~= 1
            error('CBSPairGuide:DetailTaskIdentity', ...
                '%s needs one %s=%g run %d task; found %d.', ...
                problem,armName,arms(arm),F.run,numel(rows));
        end
        resultFile = resolveResultFile( ...
            char(M.Tasks(rows).outputFile),stageDir);
        Data = loadDetailResult(resultFile,problem,F.run, ...
            F.targetFE,F.actualFE(arm,:));
        snapshots{arm} = Data.Snapshots;
        inputFiles(arm) = string(resultFile);
        inputSHA256(arm) = sha256File(resultFile);
        dimensions(arm,:) = [double(Data.Record.M), ...
            double(Data.Record.N),double(Data.Record.D)];
        Rows(arm) = struct('stage',stage,'problem',problem, ...
            'run',F.run,'armName',armName,'armValue',arms(arm), ...
            'sourceStage',string(Data.Record.stageName), ...
            'reused',string(Data.Record.stageName) ~= stage, ...
            'snapshotCount',numel(Data.Snapshots), ...
            'targetFE',numberList([Data.Snapshots.targetFE]), ...
            'actualFE',numberList([Data.Snapshots.actualFE]), ...
            'inputFile',string(resultFile), ...
            'inputSHA256',inputSHA256(arm));
    end
    if any(any(dimensions ~= dimensions(1,:)))
        error('CBSPairGuide:DetailDimensionMismatch', ...
            '%s %s arms disagree on M/N/D.',problem,stage);
    end
    B = struct('armName',armName,'armValues',arms, ...
        'Snapshots',{snapshots},'inputFiles',inputFiles, ...
        'inputSHA256',inputSHA256,'M',dimensions(1,1), ...
        'N',dimensions(1,2),'D',dimensions(1,3));
end

function Data = loadDetailResult(file,problem,run,targetFE,actualFE)
    requireFile(file,'training-schedule result');
    variables = string({whos('-file',file).name});
    required = ["Record","Snapshots"];
    missing = required(~ismember(required,variables));
    if ~isempty(missing)
        error('CBSPairGuide:BadDetailResultVariables', ...
            '%s is missing variables: %s',file,strjoin(missing,', '));
    end
    Data = load(file,'Record','Snapshots');
    R = Data.Record;
    S = Data.Snapshots;
    recordFields = {'status','stageName','problem','run', ...
        'M','N','D','snapshotCount'};
    if ~isstruct(R) || ~isscalar(R) || ...
            ~all(isfield(R,recordFields)) || string(R.status) ~= "ok" || ...
            string(R.problem) ~= problem || double(R.run) ~= run || ...
            double(R.snapshotCount) ~= 10 || ~ismember(double(R.M),[2,3])
        error('CBSPairGuide:BadDetailResultRecord', ...
            '%s has invalid Record metadata.',file);
    end
    if ~isstruct(S) || numel(S) ~= 10 || ...
            ~isequal(double([S.targetFE]),double(targetFE(:)')) || ...
            ~isequal(double([S.actualFE]),double(actualFE(:)'))
        error('CBSPairGuide:BadDetailSnapshots', ...
            '%s does not match the source figure FE schedule.',file);
    end
    layers = {'raw','target','center','guided','population1','population2'};
    for snapshot = 1 : numel(S)
        for layer = 1 : numel(layers)
            name = layers{layer};
            objs = S(snapshot).([name,'Objs']);
            cons = S(snapshot).([name,'Cons']);
            if ~isnumeric(objs) || size(objs,2) ~= double(R.M) || ...
                    any(~isfinite(objs),'all') || ~isnumeric(cons) || ...
                    size(cons,1) ~= size(objs,1) || ...
                    any(~isfinite(cons),'all')
                error('CBSPairGuide:BadDetailSnapshotLayer', ...
                    '%s snapshot %d layer %s is invalid.', ...
                    file,snapshot,name);
            end
        end
        if size(S(snapshot).rawObjs,1) ~= 500
            error('CBSPairGuide:BadDetailRawCount', ...
                '%s snapshot %d does not contain 500 raw points.', ...
                file,snapshot);
        end
    end
end

function View = detailView(Bundles)
    M = Bundles(1).M;
    if any([Bundles.M] ~= M)
        error('CBSPairGuide:DetailViewDimensionMismatch', ...
            'Ratio and epoch bundles disagree on objective count.');
    end
    panelUpper = zeros(60,M);
    pooledForeground = zeros(0,M);
    panel = 0;
    for stage = 1 : numel(Bundles)
        for arm = 1 : numel(Bundles(stage).Snapshots)
            S = Bundles(stage).Snapshots{arm};
            for snapshot = 1 : numel(S)
                panel = panel+1;
                foreground = [double(S(snapshot).population1Objs); ...
                    double(S(snapshot).population2Objs); ...
                    double(S(snapshot).targetObjs); ...
                    double(S(snapshot).centerObjs); ...
                    double(S(snapshot).guidedObjs)];
                foreground = foreground(all(isfinite(foreground),2),:);
                if isempty(foreground)
                    error('CBSPairGuide:EmptyDetailForeground', ...
                        'Panel %d has no finite foreground points.',panel);
                end
                pooledForeground = [pooledForeground;foreground]; %#ok<AGROW>
                for objective = 1 : M
                    panelUpper(panel,objective) = empiricalQuantile( ...
                        foreground(:,objective),0.95);
                end
            end
        end
    end
    if panel ~= 60
        error('CBSPairGuide:DetailPanelCount', ...
            'Detail view used %d panels; expected 60.',panel);
    end
    coreLower = zeros(1,M);
    coreUpper = zeros(1,M);
    for objective = 1 : M
        coreLower(objective) = empiricalQuantile( ...
            pooledForeground(:,objective),0.005);
        coreUpper(objective) = empiricalQuantile( ...
            panelUpper(:,objective),0.75);
    end
    span = coreUpper-coreLower;
    if any(span <= eps(max(1,max(abs(pooledForeground),[],1))))
        error('CBSPairGuide:DegenerateDetailForeground', ...
            'Foreground detail extent is degenerate.');
    end
    lower = max(0,coreLower-0.05*span);
    upper = coreUpper+0.05*span;
    View = struct('lower',lower,'upper',upper, ...
        'coreLower',coreLower,'coreUpper',coreUpper);
end

function F = makeFigureRecord(stage,problem,Source,B,View, ...
        layerNames,problemFile,problemSHA256,outputFile,Info)
    paddedLower = nan(1,3);
    paddedUpper = nan(1,3);
    paddedCoreLower = nan(1,3);
    paddedCoreUpper = nan(1,3);
    paddedLower(1:B.M) = View.lower;
    paddedUpper(1:B.M) = View.upper;
    paddedCoreLower(1:B.M) = View.coreLower;
    paddedCoreUpper(1:B.M) = View.coreUpper;
    [layerRates,layerInView,layerTotals] = visibilityStats( ...
        B.Snapshots,View,B.M);
    F = struct('stage',stage,'problem',problem,'run',Source.run, ...
        'M',B.M,'armName',B.armName,'armValues',B.armValues, ...
        'targetFE',double(Source.targetFE), ...
        'actualFE',double(Source.actualFE), ...
        'viewLower',paddedLower,'viewUpper',paddedUpper, ...
        'focusCoreLower',paddedCoreLower, ...
        'focusCoreUpper',paddedCoreUpper, ...
        'snapshotCount',30,'layerNames',layerNames, ...
        'layerInViewRates',layerRates, ...
        'layerTotalCounts',layerTotals, ...
        'layerInViewCounts',layerInView, ...
        'layerClippedCounts',layerTotals-layerInView, ...
        'inputFiles',B.inputFiles,'inputSHA256',B.inputSHA256, ...
        'problemConstructor',problemFile, ...
        'problemConstructorSHA256',problemSHA256, ...
        'file',string(outputFile),'outputSHA256',sha256File(outputFile), ...
        'width',Info.Width,'height',Info.Height);
end

function renderSheet(Problem,problem,stage,armName,arms,run, ...
        Snapshots,View,outputFile)
    Figure = figure('Visible','off','Color','w', ...
        'Position',[20,40,4200,1650]);
    cleanup = onCleanup(@()close(Figure));
    C = figureColors();
    legendHandles = gobjects(1,0);
    legendAxes = gobjects(1,1);
    left = 0.008;
    right = 0.008;
    bottom = 0.060;
    top = 0.935;
    horizontalGap = 0.003;
    verticalGap = 0.017;
    cellWidth = (1-left-right-9*horizontalGap)/10;
    cellHeight = (top-bottom-2*verticalGap)/3;
    for arm = 1 : 3
        armLabel = sprintf('%s=%g',armName,arms(arm));
        rowTop = top-(arm-1)*(cellHeight+verticalGap);
        cellY = rowTop-cellHeight;
        for snapshot = 1 : 10
            cellX = left+(snapshot-1)*(cellWidth+horizontalGap);
            Ax = axes(Figure,'Units','normalized','Position',[ ...
                cellX+0.085*cellWidth,cellY+0.055*cellHeight, ...
                0.86*cellWidth,0.75*cellHeight]);
            hold(Ax,'on');
            [hFeasible,hInfeasible] = draw_CBS_CGAN_objective_region( ...
                Ax,Problem,problem,C,View);
            simplifyBackground(Ax,Problem.M);
            H = drawLayers(Ax,Problem.M,Snapshots{arm}(snapshot),C);
            setView(Ax,View,Problem.M);
            styleAxes(Ax,Problem.M,arm,snapshot);
            if Problem.M == 3
                camzoom(Ax,0.82);
            end
            if snapshot == 1
                timeLabel = 'first use';
            else
                timeLabel = sprintf('%gK target', ...
                    Snapshots{arm}(snapshot).targetFE/1000);
            end
            annotation(Figure,'textbox',[cellX, ...
                cellY+cellHeight-0.042,cellWidth,0.040], ...
                'String',sprintf('%s\n%s | actual FE %s', ...
                    armLabel,timeLabel, ...
                    commaNumber(Snapshots{arm}(snapshot).actualFE)), ...
                'Interpreter','none','EdgeColor','none', ...
                'HorizontalAlignment','center', ...
                'VerticalAlignment','middle','FontName','Helvetica', ...
                'FontSize',6.5,'FontWeight','normal','Margin',0);
            if arm == 1 && snapshot == 1
                legendAxes = Ax;
                legendHandles = [hFeasible,hInfeasible,H];
            end
        end
    end
    annotation(Figure,'textbox',[0.04,0.962,0.92,0.028], ...
        'String',sprintf([ ...
            '%s | %s stage | representative run %d | ', ...
            'lower-left detail | shared view across both stages'], ...
            problem,stage,run),'Interpreter','none','EdgeColor','none', ...
        'HorizontalAlignment','center','VerticalAlignment','middle', ...
        'FontName','Helvetica','FontWeight','bold','FontSize',15, ...
        'Margin',0);
    labels = {'feasible region','infeasible region','P1','P2', ...
        'raw 500','selected target','selected center','guided child'};
    Legend = legend(legendAxes,legendHandles,labels, ...
        'Orientation','horizontal','NumColumns',8,'FontSize',7, ...
        'Box','off','Interpreter','none');
    Legend.Units = 'normalized';
    drawnow;
    Legend.Position = [0.25,0.012,0.50,0.025];
    drawnow;

    partialFile = [outputFile,'.partial.png'];
    partialCleanup = onCleanup(@()deleteIfExists(partialFile));
    exportgraphics(Figure,partialFile,'Resolution',96, ...
        'BackgroundColor','white');
    if ~validPNG(partialFile)
        error('CBSPairGuide:InvalidDetailPNG', ...
            'Rendered PNG failed validation: %s',partialFile);
    end
    atomicReplace(partialFile,outputFile, ...
        'CBSPairGuide:DetailPNGMoveFailed');
    clear partialCleanup cleanup;
end

function H = drawLayers(Ax,M,S,C)
    if M == 2
        hRaw = scatter(Ax,S.rawObjs(:,1),S.rawObjs(:,2),4,C.raw, ...
            'filled','o','MarkerFaceAlpha',0.30,'MarkerEdgeColor','none');
        hP1 = scatter(Ax,S.population1Objs(:,1), ...
            S.population1Objs(:,2),10,C.p1,'filled','o', ...
            'MarkerFaceAlpha',0.76,'MarkerEdgeColor','none');
        hP2 = scatter(Ax,S.population2Objs(:,1), ...
            S.population2Objs(:,2),11,C.p2,'filled','^', ...
            'MarkerFaceAlpha',0.76,'MarkerEdgeColor','none');
        hTarget = scatter(Ax,S.targetObjs(:,1),S.targetObjs(:,2), ...
            23,C.target,'filled','v','MarkerEdgeColor',[0.1,0.1,0.1], ...
            'LineWidth',0.25);
        hCenter = plot(Ax,S.centerObjs(:,1),S.centerObjs(:,2),'x', ...
            'Color',C.center,'MarkerSize',4.2,'LineWidth',0.8);
        hGuided = scatter(Ax,S.guidedObjs(:,1),S.guidedObjs(:,2), ...
            25,C.guided,'filled','d','MarkerEdgeColor',[0.1,0.1,0.1], ...
            'LineWidth',0.3);
    else
        hRaw = scatter3(Ax,S.rawObjs(:,1),S.rawObjs(:,2), ...
            S.rawObjs(:,3),4,C.raw,'filled','o', ...
            'MarkerFaceAlpha',0.30,'MarkerEdgeColor','none');
        hP1 = scatter3(Ax,S.population1Objs(:,1), ...
            S.population1Objs(:,2),S.population1Objs(:,3), ...
            10,C.p1,'filled','o','MarkerFaceAlpha',0.76, ...
            'MarkerEdgeColor','none');
        hP2 = scatter3(Ax,S.population2Objs(:,1), ...
            S.population2Objs(:,2),S.population2Objs(:,3), ...
            11,C.p2,'filled','^','MarkerFaceAlpha',0.76, ...
            'MarkerEdgeColor','none');
        hTarget = scatter3(Ax,S.targetObjs(:,1),S.targetObjs(:,2), ...
            S.targetObjs(:,3),23,C.target,'filled','v', ...
            'MarkerEdgeColor',[0.1,0.1,0.1],'LineWidth',0.25);
        hCenter = plot3(Ax,S.centerObjs(:,1),S.centerObjs(:,2), ...
            S.centerObjs(:,3),'x','Color',C.center,'MarkerSize',4.2, ...
            'LineWidth',0.8);
        hGuided = scatter3(Ax,S.guidedObjs(:,1),S.guidedObjs(:,2), ...
            S.guidedObjs(:,3),25,C.guided,'filled','d', ...
            'MarkerEdgeColor',[0.1,0.1,0.1],'LineWidth',0.3);
    end
    H = [hP1,hP2,hRaw,hTarget,hCenter,hGuided];
end

function [rates,visible,total] = visibilityStats(Snapshots,View,M)
    fields = {'population1Objs','population2Objs','rawObjs', ...
        'targetObjs','centerObjs','guidedObjs'};
    visible = zeros(1,numel(fields));
    total = zeros(1,numel(fields));
    for arm = 1 : numel(Snapshots)
        for snapshot = 1 : numel(Snapshots{arm})
            S = Snapshots{arm}(snapshot);
            for layer = 1 : numel(fields)
                Obj = double(S.(fields{layer}));
                total(layer) = total(layer)+size(Obj,1);
                visible(layer) = visible(layer)+sum(all( ...
                    Obj(:,1:M) >= View.lower & ...
                    Obj(:,1:M) <= View.upper,2));
            end
        end
    end
    rates = visible./max(1,total);
end

function simplifyBackground(Ax,M)
    if M ~= 2
        return;
    end
    Images = findobj(Ax,'Type','image');
    for i = 1 : numel(Images)
        data = Images(i).CData;
        if size(data,1) > 140 || size(data,2) > 140
            rows = unique(round(linspace(1,size(data,1),140)));
            columns = unique(round(linspace(1,size(data,2),140)));
            Images(i).CData = data(rows,columns,:);
            alpha = Images(i).AlphaData;
            if ~isscalar(alpha)
                Images(i).AlphaData = alpha(rows,columns);
            end
        end
    end
end

function setView(Ax,View,M)
    xlim(Ax,[View.lower(1),View.upper(1)]);
    ylim(Ax,[View.lower(2),View.upper(2)]);
    if M == 3
        zlim(Ax,[View.lower(3),View.upper(3)]);
        axis(Ax,'vis3d');
        view(Ax,42,25);
        Ax.Projection = 'orthographic';
    end
end

function styleAxes(Ax,M,arm,snapshot)
    grid(Ax,'on');
    box(Ax,'on');
    Ax.FontName = 'Helvetica';
    Ax.FontSize = 5.5;
    Ax.LineWidth = 0.45;
    Ax.GridAlpha = 0.18;
    Ax.Clipping = 'on';
    if arm == 3
        xlabel(Ax,'f_1','Interpreter','tex','FontSize',6.5);
    end
    if snapshot == 1
        ylabel(Ax,'f_2','Interpreter','tex','FontSize',6.5);
        if M == 3
            zlabel(Ax,'f_3','Interpreter','tex','FontSize',6.5);
        end
    end
end

function C = figureColors()
    C = struct('feasible',[0.36,0.72,0.47], ...
        'infeasible',[0.90,0.43,0.40], ...
        'p1',[0.48,0.20,0.72],'p2',[0.00,0.58,0.62], ...
        'raw',[0.13,0.43,0.82],'target',[0.86,0.20,0.58], ...
        'center',[0.08,0.08,0.08],'guided',[1.00,0.66,0.12]);
end

function Source = resolveResultFile(Source,stageDir)
    if exist(Source,'file') == 2
        return;
    end
    candidate = fullfile(stageDir,Source);
    if exist(candidate,'file') == 2
        Source = candidate;
    end
end

function assertFrozenSources(rootPath,Frozen)
    required = {'files','combinedSHA256'};
    if ~isstruct(Frozen) || ~isscalar(Frozen) || ...
            ~all(isfield(Frozen,required)) || numel(Frozen.files) ~= 7
        error('CBSPairGuide:BadDetailFrozenFingerprint', ...
            'Campaign source fingerprint is invalid.');
    end
    for i = 1 : numel(Frozen.files)
        source = fullfile(rootPath,char(Frozen.files(i).relativePath));
        requireFile(source,'frozen campaign source');
        if sha256File(source) ~= string(Frozen.files(i).sha256)
            error('CBSPairGuide:DetailFrozenSourceChanged', ...
                'Frozen campaign source changed: %s',source);
        end
    end
end

function writeManifestAtomic(manifestMAT,manifestCSV,Summary,Figures, ...
        DetailManifest,InputManifest)
    partialMAT = [manifestMAT,'.partial.mat'];
    partialCSV = [manifestCSV,'.partial.csv'];
    partialCleanup = onCleanup(@()deletePartials(partialMAT,partialCSV));
    save(partialMAT,'Summary','Figures','DetailManifest','InputManifest');
    writetable(DetailManifest,partialCSV);
    atomicReplace(partialMAT,manifestMAT, ...
        'CBSPairGuide:DetailManifestMATMoveFailed');
    atomicReplace(partialCSV,manifestCSV, ...
        'CBSPairGuide:DetailManifestCSVMoveFailed');
    clear partialCleanup;
end

function atomicReplace(source,destination,errorId)
    [moved,message] = movefile(source,destination,'f');
    if ~moved
        error(errorId,'%s',message);
    end
end

function valid = validPNG(file)
    valid = false;
    if exist(file,'file') ~= 2
        return;
    end
    try
        Info = imfinfo(file);
        valid = strcmpi(Info.Format,'png') && ...
            Info.Width >= 3800 && Info.Height >= 1400;
    catch
        valid = false;
    end
end

function textValue = commaNumber(value)
    textValue = regexprep(sprintf('%.0f',value), ...
        '(?<!\d)(\d{1,3})(?=(\d{3})+(?!\d))','$1,');
end

function value = empiricalQuantile(X,probability)
    X = sort(double(X(:)));
    if isempty(X) || probability < 0 || probability > 1
        error('CBSPairGuide:BadDetailQuantile', ...
            'Quantile input or probability is invalid.');
    end
    if isscalar(X)
        value = X;
        return;
    end
    position = 1+(numel(X)-1)*probability;
    lo = floor(position);
    hi = ceil(position);
    fraction = position-lo;
    value = X(lo)+fraction*(X(hi)-X(lo));
end

function value = numberList(values)
    value = strjoin(compose('%.15g',double(values(:)')),',');
end

function digest = sha256File(file)
    engine = java.security.MessageDigest.getInstance('SHA-256');
    fid = fopen(file,'rb');
    if fid < 0
        error('CBSPairGuide:DetailHashReadFailed', ...
            'Cannot read file for hashing: %s',file);
    end
    cleanup = onCleanup(@()fclose(fid));
    while true
        bytes = fread(fid,1024*1024,'*uint8');
        if isempty(bytes)
            break;
        end
        engine.update(typecast(bytes(:),'int8'));
    end
    clear cleanup;
    bytes = typecast(engine.digest(),'uint8');
    digest = string(lower(reshape(dec2hex(bytes,2).',1,[])));
end

function requireFile(file,description)
    if exist(file,'file') ~= 2
        error('CBSPairGuide:MissingDetailFile', ...
            'Missing %s: %s',description,file);
    end
end

function ensureFolder(folder)
    if ~isfolder(folder)
        mkdir(folder);
    end
end

function deletePartials(varargin)
    for i = 1 : nargin
        deleteIfExists(varargin{i});
    end
end

function deleteIfExists(file)
    if exist(file,'file') == 2
        delete(file);
    end
end
