function Summary = run_CBS_PairGuide_epoch_ten_use_campaign(rootPath,nWorker)
%RUN_CBS_PAIRGUIDE_EPOCH_TEN_USE_CAMPAIGN Compare ten trained model uses.

    if nargin < 1 || isempty(rootPath)
        rootPath = fileparts(which('platemo'));
    end
    if nargin < 2 || isempty(nWorker)
        nWorker = 10;
    end
    rootPath = char(rootPath);
    addCBSPaths(rootPath);
    P = campaignProtocol(rootPath,nWorker);
    validateProtocol(P);
    campaignDir = fullfile(rootPath,'Data',char(P.campaignName));
    resultDir = fullfile(campaignDir,'results');
    failureDir = fullfile(campaignDir,'failures');
    ensureFolder(resultDir);
    ensureFolder(failureDir);
    Tasks = buildTasks(P,resultDir);
    manifestFile = fullfile(campaignDir,'campaign_manifest.mat');
    if exist(manifestFile,'file') == 2
        Existing = load(manifestFile,'Protocol','Tasks');
        if ~isequaln(Existing.Protocol,P) || ~isequaln(Existing.Tasks,Tasks)
            error('CBSPairGuide:TenUseManifestMismatch', ...
                'Existing campaign manifest uses another protocol.');
        end
    else
        Protocol = P;
        save(manifestFile,'Protocol','Tasks');
    end

    pending = Tasks(~tasksComplete(Tasks,P));
    pool = [];
    ownsPool = false;
    if ~isempty(pending)
        [pool,ownsPool] = exactPool(P.nWorker);
    end
    cleanup = onCleanup(@()closeOwnedPool(pool,ownsPool));
    for attempt = 1 : P.maxAttempts
        if isempty(pending)
            break;
        end
        [~,order] = sort([pending.epoch],'descend');
        pending = pending(order);
        fprintf('PairGuide ten-use epoch: %d tasks, attempt %d/%d\n', ...
            numel(pending),attempt,P.maxAttempts);
        parfor (i = 1:numel(pending),P.nWorker)
            Task = pending(i);
            try
                runTask(rootPath,Task,P);
            catch err
                writeFailure(failureDir,Task,attempt,err);
            end
        end
        pending = Tasks(~tasksComplete(Tasks,P));
    end
    if ~isempty(pending)
        error('CBSPairGuide:TenUseTasksFailed', ...
            '%d tasks failed after %d attempts.',numel(pending),P.maxAttempts);
    end
    clear cleanup;
    closeOwnedPool(pool,ownsPool);

    Analysis = analyze_CBS_PairGuide_epoch_ten_use_campaign( ...
        rootPath,P.campaignName);
    Figures = render_CBS_PairGuide_epoch_ten_use_figures( ...
        rootPath,P.campaignName);
    Summary = struct('schemaVersion',P.schemaVersion, ...
        'campaignName',P.campaignName,'taskCount',numel(Tasks), ...
        'figureCount',Figures.figureCount, ...
        'recommendedEpoch',Analysis.recommendedEpoch, ...
        'finishedAt',string(datetime('now')));
    save(fullfile(campaignDir,'campaign_summary.mat'), ...
        'Summary','Analysis','Figures');
    writelines("COMPLETE",fullfile(campaignDir,'COMPLETE.txt'));
end

function P = campaignProtocol(rootPath,nWorker)
    P = struct( ...
        'schemaVersion',"CBS-PairGuide-ten-use-epoch-v3", ...
        'campaignName',"CBS_PairGuide_ten_use_epoch_v3_20260901", ...
        'rootPath',string(rootPath), ...
        'algorithm',"CBS_RegionWGAN_GP_PairGuide", ...
        'problems',["LIRCMOP5_BC","LIRCMOP7_BC", ...
            "LIRCMOP8_BC","LIRCMOP10_BC", ...
            "LIRCMOP12_BC","LIRCMOP14_BC"], ...
        'epochs',[50 100 200 400 700 1000], ...
        'runs',1:5,'captureUses',10, ...
        'popSize',100,'dimension',30,'maxFE',500000, ...
        'rawGuideCount',500,'zDim',6,'miniBatch',64,'nCritic',4, ...
        'minGANTrainCount',32,'sampleSigma',1, ...
        'expectedRequestedCount',20,'nWorker',double(nWorker), ...
        'maxAttempts',2);
end

function validateProtocol(P)
    expectedProblems = ["LIRCMOP5_BC","LIRCMOP7_BC", ...
        "LIRCMOP8_BC","LIRCMOP10_BC", ...
        "LIRCMOP12_BC","LIRCMOP14_BC"];
    if P.algorithm ~= "CBS_RegionWGAN_GP_PairGuide" || ...
            ~isequal(P.problems,expectedProblems) || ...
            ~isequal(P.epochs,[50 100 200 400 700 1000]) || ...
            ~isequal(P.runs,1:5) || P.captureUses ~= 10 || ...
            P.popSize ~= 100 || P.dimension ~= 30 || ...
            P.rawGuideCount ~= 500 || P.miniBatch ~= 64 || ...
            P.expectedRequestedCount ~= 20 || ...
            P.nWorker ~= 10
        error('CBSPairGuide:BadTenUseProtocol', ...
            'Fixed ten-use epoch protocol was changed.');
    end
end

function Tasks = buildTasks(P,resultDir)
    template = struct('problem',"",'epoch',0,'run',0,'seed',0, ...
        'sampleSeed',0,'outputFile',"");
    Tasks = repmat(template, ...
        numel(P.problems)*numel(P.epochs)*numel(P.runs),1);
    row = 0;
    for problem = 1 : numel(P.problems)
        for epoch = P.epochs
            for run = P.runs
                row = row+1;
                Tasks(row).problem = P.problems(problem);
                Tasks(row).epoch = epoch;
                Tasks(row).run = run;
                Tasks(row).seed = run;
                Tasks(row).sampleSeed = 200000+1000*problem+run;
                Tasks(row).outputFile = string(fullfile(resultDir, ...
                    sprintf('%s_epoch%04d_run%02d.mat', ...
                    P.problems(problem),epoch,run)));
            end
        end
    end
end

function OutputFile = runTask(rootPath,Task,P)
    cd(rootPath);
    addCBSPaths(rootPath);
    try
        maxNumCompThreads(1);
    catch
    end
    if exist(Task.outputFile,'file') == 2
        if resultComplete(Task,P)
            OutputFile = char(Task.outputFile);
            return;
        end
        error('CBSPairGuide:InvalidExistingTenUseResult', ...
            'Invalid result exists and will not be overwritten: %s', ...
            Task.outputFile);
    end

    rng(Task.seed,'twister');
    constructor = str2func(char(Task.problem));
    Problem = constructor('N',P.popSize,'D',P.dimension, ...
        'maxFE',P.maxFE,'maxRuntime',Inf);
    parameters = {P.rawGuideCount,P.zDim,Task.epoch,P.miniBatch, ...
        P.nCritic,P.minGANTrainCount,P.sampleSigma};
    Algorithm = CBS_RegionWGAN_GP_PairGuide('parameter',parameters, ...
        'save',0,'run',Task.run,'outputFcn',@silentOutput);
    Algorithm.configureFirstPairGuideUseCapture(struct( ...
        'enabled',true,'stopAfterUse',true, ...
        'sampleSeed',Task.sampleSeed,'maxUses',P.captureUses));

    started = datetime('now','TimeZone','local');
    wallClock = tic;
    Algorithm.Solve(Problem);
    elapsed = toc(wallClock);
    Capture = Algorithm.firstPairGuideUseCapture();
    Audit = Algorithm.guideExperimentSnapshot();
    validateCapture(Task,P,Problem,Capture,Audit);

    BCProblem = constructor('N',P.popSize,'D',P.dimension, ...
        'maxFE',1e9,'maxRuntime',Inf);
    baseConstructor = str2func(char(erase(Task.problem,"_BC")));
    ContinuousProblem = baseConstructor('N',P.popSize,'D',P.dimension, ...
        'maxFE',1e9,'maxRuntime',Inf);
    Snapshots = repmat(emptySnapshot(Problem.M),P.captureUses,1);
    Metrics = repmat(emptyMetrics(),P.captureUses,1);
    for event = 1 : P.captureUses
        E = Capture.events(event);
        Raw = BCProblem.Evaluation(E.rawDecs);
        Continuous = ContinuousProblem.Evaluation( ...
            [E.rawDecs;E.childDecs]);
        rawCount = size(E.rawDecs,1);
        rawContinuousCons = double(Continuous.cons(1:rawCount,:));
        childContinuousCons = double(Continuous.cons(rawCount+1:end,:));
        Snapshots(event) = makeSnapshot(E,Raw,rawContinuousCons, ...
            childContinuousCons,Problem.M);
        Metrics(event) = eventMetrics(E,Snapshots(event),elapsed);
    end
    Record = struct('schemaVersion',P.schemaVersion,'status',"ok", ...
        'algorithm',P.algorithm,'problem',Task.problem, ...
        'epoch',Task.epoch,'run',Task.run,'seed',Task.seed, ...
        'sampleSeed',Task.sampleSeed,'N',P.popSize,'D',P.dimension, ...
        'M',Problem.M,'maxFE',P.maxFE,'eventCount',P.captureUses, ...
        'startedAt',string(started), ...
        'finishedAt',string(datetime('now')), ...
        'wallClockSeconds',elapsed, ...
        'algorithmRuntimeSeconds',double(Algorithm.metric.runtime), ...
        'searchFE',double(Problem.FE), ...
        'offlineEvaluationFE',double(BCProblem.FE+ContinuousProblem.FE), ...
        'terminalRNG',rng);

    OutputFile = char(Task.outputFile);
    partialFile = [OutputFile,'.partial.mat'];
    save(partialFile,'Record','Capture','Snapshots','Metrics','Audit','-v7.3');
    PartialTask = Task;
    PartialTask.outputFile = string(partialFile);
    if ~resultComplete(PartialTask,P)
        error('CBSPairGuide:InvalidTenUsePartial', ...
            'Saved partial result failed validation.');
    end
    [moved,message] = movefile(partialFile,OutputFile);
    if ~moved
        error('CBSPairGuide:TenUseResultMoveFailed','%s',message);
    end
end

function validateCapture(Task,P,Problem,C,Audit)
    valid = C.complete && C.eventCount == P.captureUses && ...
        numel(C.events) == P.captureUses && ...
        Problem.FE == C.events(end).useFE && ...
        isfield(Audit,'rawOracleCount') && Audit.rawOracleCount == 0;
    previousFE = -inf;
    for event = 1 : numel(C.events)
        E = C.events(event);
        expectedSeed = mod(Task.sampleSeed+event-1,2^32);
        validTraining = isstruct(E.trainStatus) && ...
            E.trainStatus.trained && ...
            E.trainStatus.useModel && E.trainStatus.epochs == Task.epoch;
        valid = valid && E.complete && E.eventIndex == event && ...
            E.sampleSeed == expectedSeed && validTraining && ...
            E.poolFE > previousFE && E.useFE-E.poolFE == Problem.N && ...
            size(E.rawDecs,1) == P.rawGuideCount && ...
            size(E.rawDecs,2) == Problem.D && ...
            E.requestedCount == P.expectedRequestedCount && ...
            E.selectedCount+E.fallbackCount == E.requestedCount && ...
            size(E.childDecs,1) == E.selectedCount && ...
            size(E.childObjs,1) == E.selectedCount && ...
            size(E.childCons,1) == E.selectedCount;
        previousFE = E.useFE;
    end
    if ~valid
        error('CBSPairGuide:BadTenUseCapture', ...
            '%s epoch %d run %d has an invalid capture.', ...
            Task.problem,Task.epoch,Task.run);
    end
end

function S = emptySnapshot(M)
    S = struct('eventIndex',0,'sampleSeed',NaN,'poolFE',NaN, ...
        'useFE',NaN,'rawCount',0,'requestedCount',0,'guidedCount',0, ...
        'fallbackCount',0,'rawObjs',zeros(0,M),'rawCons',zeros(0,0), ...
        'guidedObjs',zeros(0,M),'guidedCons',zeros(0,0), ...
        'parentObjs',zeros(0,M),'rawContinuousCons',zeros(0,0), ...
        'guidedContinuousCons',zeros(0,0), ...
        'rawFeasible',false(0,1),'guidedFeasible',false(0,1), ...
        'guidedDominating',false(0,1),'guidedUseful',false(0,1));
end

function S = makeSnapshot(E,Raw,rawContinuousCons,childContinuousCons,M)
    parentObjs = double(E.guideTrace.parentObjs);
    if isempty(parentObjs)
        parentObjs = zeros(0,M);
    end
    childObjs = double(E.childObjs);
    childCons = double(E.childCons);
    childFeasible = rowFeasible(childCons);
    childDominating = all(childObjs <= parentObjs+1e-12,2) & ...
        any(childObjs < parentObjs-1e-12,2);
    S = struct('eventIndex',E.eventIndex,'sampleSeed',E.sampleSeed, ...
        'poolFE',E.poolFE,'useFE',E.useFE, ...
        'rawCount',numel(Raw),'requestedCount',E.requestedCount, ...
        'guidedCount',E.selectedCount,'fallbackCount',E.fallbackCount, ...
        'rawObjs',double(Raw.objs),'rawCons',double(Raw.cons), ...
        'guidedObjs',childObjs,'guidedCons',childCons, ...
        'parentObjs',parentObjs,'rawContinuousCons',rawContinuousCons, ...
        'guidedContinuousCons',childContinuousCons, ...
        'rawFeasible',rowFeasible(Raw.cons), ...
        'guidedFeasible',childFeasible, ...
        'guidedDominating',childDominating, ...
        'guidedUseful',childFeasible & childDominating);
end

function M = emptyMetrics()
    M = struct('eventIndex',0,'poolFE',NaN,'useFE',NaN, ...
        'wallClockSeconds',NaN,'trainingPairs',NaN, ...
        'batchesPerEpoch',NaN,'updates',NaN,'pairVisits',NaN, ...
        'candidateValidCount',NaN,'candidateValidRate',NaN, ...
        'requestedCount',NaN,'guidedCount',NaN, ...
        'guidedSelectionRate',NaN,'fallbackCount',NaN, ...
        'rawFeasibleRate',NaN,'rawInfeasibleRate',NaN, ...
        'rawBoundaryMarginMedian',NaN,'rawCVMedian',NaN, ...
        'rawDecisionUniqueRate',NaN,'guidedFeasibleRate',NaN, ...
        'guidedBoundaryMarginMedian',NaN,'guidedCVMedian',NaN, ...
        'guidedDominatingRate',NaN,'guidedUsefulRate',NaN, ...
        'guidedUsefulPerQuota',NaN);
end

function M = eventMetrics(E,S,elapsed)
    rawCV = sum(max(0,S.rawContinuousCons),2);
    guidedCV = sum(max(0,S.guidedContinuousCons),2);
    signature = round(E.rawDecs/1e-6);
    M = struct('eventIndex',E.eventIndex,'poolFE',E.poolFE, ...
        'useFE',E.useFE,'wallClockSeconds',double(elapsed), ...
        'trainingPairs',double(E.trainStatus.trainingPairs), ...
        'batchesPerEpoch',double(E.trainStatus.batchesPerEpoch), ...
        'updates',double(E.trainStatus.updates), ...
        'pairVisits',double(E.trainStatus.pairVisits), ...
        'candidateValidCount',double(E.poolTrace.validCount), ...
        'candidateValidRate',double(E.poolTrace.validCount)/S.rawCount, ...
        'requestedCount',double(S.requestedCount), ...
        'guidedCount',double(S.guidedCount), ...
        'guidedSelectionRate',double(S.guidedCount)/S.requestedCount, ...
        'fallbackCount',double(S.fallbackCount), ...
        'rawFeasibleRate',mean(S.rawFeasible), ...
        'rawInfeasibleRate',mean(rawCV > 0), ...
        'rawBoundaryMarginMedian',constraintMargin(S.rawContinuousCons), ...
        'rawCVMedian',median(rawCV), ...
        'rawDecisionUniqueRate',size(unique(signature,'rows'),1)/S.rawCount, ...
        'guidedFeasibleRate',safeMean(S.guidedFeasible), ...
        'guidedBoundaryMarginMedian', ...
            constraintMargin(S.guidedContinuousCons), ...
        'guidedCVMedian',safeMedian(guidedCV), ...
        'guidedDominatingRate',safeMean(S.guidedDominating), ...
        'guidedUsefulRate',safeMean(S.guidedUseful), ...
        'guidedUsefulPerQuota',sum(S.guidedUseful)/S.requestedCount);
end

function feasible = rowFeasible(Cons)
    if isempty(Cons)
        feasible = false(0,1);
    else
        feasible = sum(max(0,double(Cons)),2) <= 0;
    end
end

function value = constraintMargin(Cons)
    if isempty(Cons)
        value = NaN;
    else
        value = median(min(abs(double(Cons)),[],2));
    end
end

function value = safeMean(X)
    if isempty(X), value = NaN; else, value = mean(double(X)); end
end

function value = safeMedian(X)
    if isempty(X), value = NaN; else, value = median(double(X)); end
end

function mask = tasksComplete(Tasks,P)
    mask = false(numel(Tasks),1);
    for i = 1 : numel(Tasks)
        mask(i) = resultComplete(Tasks(i),P);
    end
end

function complete = resultComplete(Task,P)
    complete = false;
    if exist(Task.outputFile,'file') ~= 2
        return;
    end
    try
        D = load(Task.outputFile,'Record','Capture','Snapshots','Audit');
        R = D.Record;
        C = D.Capture;
        complete = string(R.schemaVersion) == P.schemaVersion && ...
            string(R.status) == "ok" && string(R.problem) == Task.problem && ...
            R.epoch == Task.epoch && R.run == Task.run && ...
            R.seed == Task.seed && R.sampleSeed == Task.sampleSeed && ...
            R.N == P.popSize && R.D == P.dimension && ...
            R.eventCount == P.captureUses && ...
            R.searchFE == C.events(end).useFE && C.complete && ...
            C.eventCount == P.captureUses && ...
            numel(D.Snapshots) == P.captureUses && ...
            D.Audit.rawOracleCount == 0;
        for event = 1 : P.captureUses
            E = C.events(event);
            S = D.Snapshots(event);
            complete = complete && E.eventIndex == event && ...
                E.trainStatus.trained && E.trainStatus.useModel && ...
                E.trainStatus.epochs == Task.epoch && ...
                E.useFE-E.poolFE == P.popSize && ...
                size(E.rawDecs,1) == P.rawGuideCount && ...
                E.requestedCount == P.expectedRequestedCount && ...
                E.selectedCount+E.fallbackCount == E.requestedCount && ...
                S.rawCount == P.rawGuideCount && ...
                S.guidedCount == E.selectedCount;
        end
    catch
        complete = false;
    end
end

function [pool,ownsPool] = exactPool(nWorker)
    pool = gcp('nocreate');
    ownsPool = isempty(pool);
    if ownsPool
        pool = parpool("Processes",nWorker);
    elseif pool.NumWorkers ~= nWorker
        error('CBSPairGuide:TenUseWorkerCount', ...
            'Existing pool must contain exactly %d workers.',nWorker);
    end
end

function closeOwnedPool(pool,ownsPool)
    if ownsPool && ~isempty(pool) && isvalid(pool)
        delete(pool);
    end
end

function writeFailure(folder,Task,attempt,err)
    file = fullfile(folder,sprintf( ...
        '%s_epoch%04d_run%02d_attempt%02d.txt', ...
        Task.problem,Task.epoch,Task.run,attempt));
    writelines(string(getReport(err,'extended','hyperlinks','off')),file);
end

function silentOutput(~,~)
end

function ensureFolder(folder)
    if ~isfolder(folder), mkdir(folder); end
end
