function Summary = run_CBS_PairGuide_training_schedule_campaign( ...
        rootPath,nWorker)
%RUN_CBS_PAIRGUIDE_TRAINING_SCHEDULE_CAMPAIGN Run the locked two-stage study.

    if nargin < 1 || isempty(rootPath)
        rootPath = fileparts(which('platemo'));
    end
    if nargin < 2 || isempty(nWorker)
        nWorker = 10;
    end
    rootPath = char(rootPath);
    addCBSPaths(rootPath);
    Campaign = campaignProtocol(rootPath,nWorker);
    validateCampaignProtocol(Campaign);

    campaignDir = fullfile(rootPath,'Data',char(Campaign.campaignName));
    ensureFolder(campaignDir);
    ensureCampaignManifest(campaignDir,Campaign);
    State = loadCampaignState(campaignDir,Campaign);
    State.status = "running";
    State.currentStage = "ratio";
    State.finishedAt = "";
    State.error = "";
    removeMarker(fullfile(campaignDir,'COMPLETE.txt'));
    removeMarker(fullfile(campaignDir,'FAILED.txt'));
    saveCampaignState(campaignDir,Campaign,State);

    setProcessThreadLimits();
    try
        [pool,ownsPool] = exactProcessPool(Campaign.nWorker);
    catch err
        State.status = "failed";
        State.finishedAt = string(datetime('now'));
        State.error = string(getReport(err,'extended','hyperlinks','off'));
        saveCampaignState(campaignDir,Campaign,State);
        writelines(State.error,fullfile(campaignDir,'FAILED.txt'));
        rethrow(err);
    end
    cleanup = onCleanup(@()closeOwnedPool(pool,ownsPool));
    try
        %% Stage 1: critic/generator update ratio
        ratioDir = fullfile(campaignDir,'ratio');
        RatioProtocol = stageProtocol(Campaign,"ratio",NaN);
        RatioTasks = buildRatioTasks(RatioProtocol,ratioDir);
        ensureStageManifest(ratioDir,RatioProtocol,RatioTasks);
        runStage(rootPath,ratioDir,RatioProtocol,RatioTasks,pool);

        assertSourceFingerprint(rootPath,Campaign.sourceFingerprint);
        State.ratioCompleteTasks = numel(RatioTasks);
        State.currentStage = "ratio_analysis";
        saveCampaignState(campaignDir,Campaign,State);
        RatioAnalysis = analyze_CBS_PairGuide_training_schedule_stage( ...
            rootPath,Campaign.campaignName,"ratio");
        [chosenNCritic,representativeRunMap] = freezeRatioDecision( ...
            ratioDir,RatioProtocol,RatioAnalysis);
        State.chosenNCritic = chosenNCritic;
        State.currentStage = "epoch";
        saveCampaignState(campaignDir,Campaign,State);

        %% Stage 2: subsequent-training epoch budget
        epochDir = fullfile(campaignDir,'epoch');
        EpochProtocol = stageProtocol(Campaign,"epoch",chosenNCritic);
        EpochTasks = buildEpochTasks( ...
            EpochProtocol,epochDir,RatioTasks,chosenNCritic);
        ensureStageManifest(epochDir,EpochProtocol,EpochTasks);
        runStage(rootPath,epochDir,EpochProtocol,EpochTasks,pool);

        assertSourceFingerprint(rootPath,Campaign.sourceFingerprint);
        State.epochCompleteTasks = numel(EpochTasks);
        State.currentStage = "analysis";
        saveCampaignState(campaignDir,Campaign,State);
        EpochAnalysis = analyze_CBS_PairGuide_training_schedule_stage( ...
            rootPath,Campaign.campaignName,"epoch");
        if ~isfield(EpochAnalysis,'selectedRetrainEpoch') || ...
                ~ismember(double(EpochAnalysis.selectedRetrainEpoch), ...
                Campaign.epochArms)
            error('CBSPairGuide:BadEpochDecision', ...
                'The epoch analyzer returned an invalid selected epoch.');
        end

        State.selectedRetrainEpoch = ...
            double(EpochAnalysis.selectedRetrainEpoch);
        State.currentStage = "rendering";
        saveCampaignState(campaignDir,Campaign,State);
        assertSourceFingerprint(rootPath,Campaign.sourceFingerprint);
        Figures = render_CBS_PairGuide_training_schedule_figures( ...
            rootPath,Campaign.campaignName);

        Summary = struct( ...
            'schemaVersion',Campaign.schemaVersion, ...
            'campaignName',Campaign.campaignName, ...
            'sourceFingerprint', ...
                Campaign.sourceFingerprint.combinedSHA256, ...
            'ratioTaskCount',numel(RatioTasks), ...
            'epochTaskCount',numel(EpochTasks), ...
            'epochExecutedTaskCount',nnz(~[EpochTasks.reused]), ...
            'epochReusedTaskCount',nnz([EpochTasks.reused]), ...
            'chosenNCritic',chosenNCritic, ...
            'selectedRetrainEpoch',State.selectedRetrainEpoch, ...
            'representativeRunMap',representativeRunMap, ...
            'figureCount',numel(Figures), ...
            'finishedAt',string(datetime('now')));
        saveSummary(campaignDir,Summary,RatioAnalysis, ...
            EpochAnalysis,Figures);
        State.status = "complete";
        State.currentStage = "complete";
        State.finishedAt = Summary.finishedAt;
        State.error = "";
        saveCampaignState(campaignDir,Campaign,State);
        failedFile = fullfile(campaignDir,'FAILED.txt');
        if isfile(failedFile)
            delete(failedFile);
        end
        writelines("COMPLETE",fullfile(campaignDir,'COMPLETE.txt'));
    catch err
        State.status = "failed";
        State.finishedAt = string(datetime('now'));
        State.error = string(getReport(err,'extended','hyperlinks','off'));
        saveCampaignState(campaignDir,Campaign,State);
        writelines(State.error,fullfile(campaignDir,'FAILED.txt'));
        rethrow(err);
    end
    clear cleanup;
    closeOwnedPool(pool,ownsPool);
end

function P = campaignProtocol(rootPath,nWorker)
%CAMPAIGNPROTOCOL Return the immutable campaign-level contract.

    SourceFingerprint = sourceFingerprint(rootPath);
    P = struct( ...
        'schemaVersion',"CBS-PairGuide-training-schedule-v1", ...
        'campaignName',"CBS_PairGuide_training_schedule_v1_20260901", ...
        'rootPath',string(rootPath), ...
        'sourceFingerprint',SourceFingerprint, ...
        'algorithm',"CBS_RegionWGAN_GP_PairGuide", ...
        'problems',["LIRCMOP5_BC","LIRCMOP7_BC", ...
            "LIRCMOP8_BC","LIRCMOP10_BC", ...
            "LIRCMOP12_BC","LIRCMOP14_BC"], ...
        'runs',1:5,'ratioArms',[1 2 4],'epochArms',[5 10 20], ...
        'initialEpoch',500,'ratioRetrainEpoch',10, ...
        'N',100,'D',30,'maxFE',100000, ...
        'targetFE',[1,20000:10000:100000], ...
        'rawPoolSize',500,'expectedGuidedCount',20, ...
        'zDim',6,'miniBatch',64,'minGANTrainCount',32, ...
        'sampleSigma',1,'nWorker',double(nWorker),'maxAttempts',3);
end

function validateCampaignProtocol(P)
%VALIDATECAMPAIGNPROTOCOL Fail if any locked campaign setting moved.

    expectedProblems = ["LIRCMOP5_BC","LIRCMOP7_BC", ...
        "LIRCMOP8_BC","LIRCMOP10_BC", ...
        "LIRCMOP12_BC","LIRCMOP14_BC"];
    expectedTargets = [1,20000:10000:100000];
    if P.schemaVersion ~= "CBS-PairGuide-training-schedule-v1" || ...
            P.campaignName ~= ...
            "CBS_PairGuide_training_schedule_v1_20260901" || ...
            P.algorithm ~= "CBS_RegionWGAN_GP_PairGuide" || ...
            ~isequal(P.problems,expectedProblems) || ...
            ~isequal(P.runs,1:5) || ~isequal(P.ratioArms,[1 2 4]) || ...
            ~isequal(P.epochArms,[5 10 20]) || ...
            P.initialEpoch ~= 500 || P.ratioRetrainEpoch ~= 10 || ...
            P.N ~= 100 || P.D ~= 30 || P.maxFE ~= 100000 || ...
            ~isequal(P.targetFE,expectedTargets) || ...
            numel(P.targetFE) ~= 10 || P.rawPoolSize ~= 500 || ...
            P.expectedGuidedCount ~= 20 || P.zDim ~= 6 || ...
            P.miniBatch ~= 64 || P.minGANTrainCount ~= 32 || ...
            P.sampleSigma ~= 1 || P.nWorker ~= 10 || ...
            P.maxAttempts < 2 || ...
            ~validSourceFingerprint(P.sourceFingerprint)
        error('CBSPairGuide:BadTrainingScheduleProtocol', ...
            'The fixed training-schedule campaign protocol was changed.');
    end
end

function P = stageProtocol(C,stageName,chosenNCritic)
%STAGEPROTOCOL Derive one immutable paired-stage manifest.

    stageName = string(stageName);
    if stageName == "ratio"
        armName = "nCritic";
        arms = C.ratioArms;
        fixedNCritic = NaN;
        fixedRetrainEpoch = C.ratioRetrainEpoch;
        frozenDecisionFile = "";
        selectedNCriticSource = "";
    elseif stageName == "epoch"
        if ~isscalar(chosenNCritic) || ...
                ~ismember(double(chosenNCritic),C.ratioArms)
            error('CBSPairGuide:BadFrozenNCritic', ...
                'Epoch stage requires one frozen ratio-stage nCritic.');
        end
        armName = "retrainEpoch";
        arms = C.epochArms;
        fixedNCritic = double(chosenNCritic);
        fixedRetrainEpoch = NaN;
        frozenDecisionFile = string(fullfile(char(C.rootPath),'Data', ...
            char(C.campaignName),'ratio','analysis', ...
            'frozen_decision.mat'));
        if ~isfile(frozenDecisionFile)
            error('CBSPairGuide:MissingFrozenRatioDecision', ...
                'Epoch stage requires the frozen ratio decision file.');
        end
        selectedNCriticSource = frozenDecisionFile+"#chosenNCritic";
    else
        error('CBSPairGuide:BadScheduleStage','Unknown stage: %s',stageName);
    end
    P = struct( ...
        'schemaVersion',C.schemaVersion,'campaignName',C.campaignName, ...
        'rootPath',C.rootPath,'sourceFingerprint',C.sourceFingerprint, ...
        'stageName',stageName, ...
        'armName',armName,'arms',arms,'algorithm',C.algorithm, ...
        'problems',C.problems,'runs',C.runs, ...
        'initialEpoch',C.initialEpoch, ...
        'fixedRetrainEpoch',fixedRetrainEpoch, ...
        'fixedNCritic',fixedNCritic,'selectedNCritic',fixedNCritic, ...
        'frozenDecisionFile',frozenDecisionFile, ...
        'selectedNCriticSource',selectedNCriticSource, ...
        'N',C.N,'D',C.D, ...
        'maxFE',C.maxFE,'targetFE',C.targetFE, ...
        'rawPoolSize',C.rawPoolSize, ...
        'expectedRawCount',C.rawPoolSize, ...
        'expectedGuidedCount',C.expectedGuidedCount, ...
        'zDim',C.zDim,'miniBatch',C.miniBatch, ...
        'minGANTrainCount',C.minGANTrainCount, ...
        'sampleSigma',C.sampleSigma,'nWorker',C.nWorker, ...
        'maxAttempts',C.maxAttempts);
end

function Tasks = buildRatioTasks(P,stageDir)
%BUILDRATIOTASKS Build six problems by five runs by three nCritic arms.

    resultDir = fullfile(stageDir,'results');
    ensureFolder(resultDir);
    template = taskTemplate();
    Tasks = repmat(template, ...
        numel(P.problems)*numel(P.runs)*numel(P.arms),1);
    row = 0;
    for problem = 1 : numel(P.problems)
        for run = P.runs
            for arm = P.arms
                row = row+1;
                Tasks(row) = makeTask(P,P.problems(problem),run, ...
                    arm,P.initialEpoch,P.fixedRetrainEpoch,arm, ...
                    "ratio",false,string(fullfile(resultDir,sprintf( ...
                    '%s_nCritic%02d_run%02d.mat', ...
                    P.problems(problem),arm,run))));
            end
        end
    end
end

function Tasks = buildEpochTasks(P,stageDir,RatioTasks,chosenNCritic)
%BUILDEPOCHTASKS Reuse epoch=10 and run only epoch=5/20.

    resultDir = fullfile(stageDir,'results');
    ensureFolder(resultDir);
    template = taskTemplate();
    Tasks = repmat(template, ...
        numel(P.problems)*numel(P.runs)*numel(P.arms),1);
    ratioProblems = string({RatioTasks.problem});
    ratioRuns = double([RatioTasks.run]);
    ratioArms = double([RatioTasks.armValue]);
    row = 0;
    for problem = 1 : numel(P.problems)
        for run = P.runs
            for arm = P.arms
                row = row+1;
                if arm == 10
                    source = find(ratioProblems == P.problems(problem) & ...
                        ratioRuns == run & ratioArms == chosenNCritic);
                    if numel(source) ~= 1
                        error('CBSPairGuide:MissingRatioReuseSource', ...
                            ['Expected one ratio source for %s run %d ', ...
                             'and nCritic=%d.'],P.problems(problem), ...
                             run,chosenNCritic);
                    end
                    outputFile = RatioTasks(source).outputFile;
                    resultStage = "ratio";
                    reused = true;
                else
                    outputFile = string(fullfile(resultDir,sprintf( ...
                        '%s_retrainEpoch%02d_run%02d.mat', ...
                        P.problems(problem),arm,run)));
                    resultStage = "epoch";
                    reused = false;
                end
                Tasks(row) = makeTask(P,P.problems(problem),run,arm, ...
                    P.initialEpoch,arm,chosenNCritic,resultStage, ...
                    reused,outputFile);
            end
        end
    end
    if nnz([Tasks.reused]) ~= numel(P.problems)*numel(P.runs)
        error('CBSPairGuide:BadEpochReuseCount', ...
            'Exactly 30 epoch=10 tasks must be reused from ratio stage.');
    end
end

function T = taskTemplate()
    T = struct('taskId',"",'resultStage',"",'problem',"", ...
        'armName',"",'armValue',NaN,'run',0,'seed',0, ...
        'initialEpoch',0,'retrainEpoch',0,'nCritic',0, ...
        'outputFile',"",'reused',false);
end

function T = makeTask(P,problem,run,armValue,initialEpoch, ...
        retrainEpoch,nCritic,resultStage,reused,outputFile)
    T = taskTemplate();
    T.taskId = string(sprintf('%s_%s_%g_run%02d', ...
        P.stageName,P.armName,armValue,run))+"_"+problem;
    T.resultStage = string(resultStage);
    T.problem = string(problem);
    T.armName = P.armName;
    T.armValue = double(armValue);
    T.run = double(run);
    T.seed = double(run);
    T.initialEpoch = double(initialEpoch);
    T.retrainEpoch = double(retrainEpoch);
    T.nCritic = double(nCritic);
    T.outputFile = string(outputFile);
    T.reused = logical(reused);
end

function runStage(rootPath,stageDir,P,Tasks,pool)
%RUNSTAGE Run/retry one complete paired grid before returning.

    resultDir = fullfile(stageDir,'results');
    failureDir = fullfile(stageDir,'failures');
    ensureFolder(resultDir);
    ensureFolder(failureDir);
    StageState = loadStageState(stageDir,P,Tasks);
    StageState.status = "running";
    StageState.finishedAt = "";
    StageState.error = "";
    removeMarker(fullfile(stageDir,'COMPLETE.txt'));
    complete = tasksComplete(Tasks,P);
    incompleteReused = [Tasks.reused]' & ~complete;
    if any(incompleteReused)
        bad = Tasks(find(incompleteReused,1));
        error('CBSPairGuide:InvalidReusedRatioResult', ...
            'Reused ratio result is missing or invalid: %s',bad.outputFile);
    end
    pending = Tasks(~complete & ~[Tasks.reused]');
    for attempt = 1 : P.maxAttempts
        if isempty(pending)
            break;
        end
        StageState.status = "running";
        StageState.attempt = attempt;
        StageState.error = "";
        StageState = updateStageState( ...
            stageDir,StageState,P,Tasks);
        fprintf('PairGuide training schedule %s: %d tasks, attempt %d/%d\n', ...
            P.stageName,numel(pending),attempt,P.maxAttempts);
        options = parforOptions(pool,'RangePartitionMethod','fixed', ...
            'SubrangeSize',1);
        parfor (i = 1:numel(pending),options)
            Task = pending(i);
            try
                runTask(rootPath,Task,P,failureDir);
            catch err
                writeFailure(failureDir,Task,attempt,err);
            end
        end
        complete = tasksComplete(Tasks,P);
        incompleteReused = [Tasks.reused]' & ~complete;
        if any(incompleteReused)
            error('CBSPairGuide:ReusedResultBecameInvalid', ...
                'A frozen ratio result became invalid during epoch stage.');
        end
        pending = Tasks(~complete & ~[Tasks.reused]');
        StageState = updateStageState( ...
            stageDir,StageState,P,Tasks);
    end
    if ~isempty(pending)
        StageState.status = "failed";
        StageState.error = sprintf('%d tasks failed after %d attempts.', ...
            numel(pending),P.maxAttempts);
        updateStageState(stageDir,StageState,P,Tasks);
        error('CBSPairGuide:TrainingScheduleTasksFailed', ...
            '%s stage: %s',P.stageName,StageState.error);
    end
    StageState.status = "complete";
    StageState.finishedAt = string(datetime('now'));
    StageState.error = "";
    updateStageState(stageDir,StageState,P,Tasks);
    writelines("COMPLETE",fullfile(stageDir,'COMPLETE.txt'));
end

function OutputFile = runTask(rootPath,Task,P,failureDir)
%RUNTASK Run one full PlatEMO task and publish one validated MAT atomically.

    cd(rootPath);
    addCBSPaths(rootPath);
    assertSourceFingerprint(rootPath,P.sourceFingerprint);
    try
        maxNumCompThreads(1);
    catch
    end
    if Task.reused
        error('CBSPairGuide:AttemptedReusedTaskExecution', ...
            'A reused epoch=10 task must never be executed.');
    end
    OutputFile = char(Task.outputFile);
    partialFile = [OutputFile,'.partial.mat'];
    if isfile(OutputFile)
        if resultComplete(Task,P)
            return;
        end
        quarantineFile(OutputFile,failureDir,Task,"invalid_result");
    end
    if isfile(partialFile)
        PartialTask = Task;
        PartialTask.outputFile = string(partialFile);
        if resultComplete(PartialTask,P)
            atomicMove(partialFile,OutputFile, ...
                'CBSPairGuide:PartialRecoveryMoveFailed');
            return;
        end
        quarantineFile(partialFile,failureDir,Task,"invalid_partial");
    end

    rng(Task.seed,'twister');
    constructor = str2func(char(Task.problem));
    Problem = constructor('N',P.N,'D',P.D, ...
        'maxFE',P.maxFE,'maxRuntime',Inf);
    Trajectory = struct('FE',zeros(0,1),'IGD',zeros(0,1), ...
        'FeasibleCount',zeros(0,1));
    parameters = {P.rawPoolSize,P.zDim,P.initialEpoch,P.miniBatch, ...
        Task.nCritic,P.minGANTrainCount,P.sampleSigma};
    Algorithm = CBS_RegionWGAN_GP_PairGuide('parameter',parameters, ...
        'save',0,'run',Task.run,'outputFcn',@captureTrajectory);
    Algorithm.configurePairGuideTrainingExperiment(struct( ...
        'initialEpoch',Task.initialEpoch, ...
        'retrainEpoch',Task.retrainEpoch,'nCritic',Task.nCritic));
    Algorithm.configureCutoffDiagnostics(struct( ...
        'enabled',true,'stopAtCGANEnd',false, ...
        'disableOracleAudit',false));
    Algorithm.configureObjectiveSpaceSnapshots(struct( ...
        'enabled',true,'targetFE',P.targetFE, ...
        'expectedRawCount',P.rawPoolSize, ...
        'expectedGuidedCount',P.expectedGuidedCount));

    started = datetime('now','TimeZone','local');
    wallClock = tic;
    Algorithm.Solve(Problem);
    elapsed = toc(wallClock);
    terminalRNG = rng;
    Snapshots = Algorithm.objectiveSpaceSnapshots();
    Audit = Algorithm.guideExperimentSnapshot();
    Record = struct( ...
        'schemaVersion',P.schemaVersion,'status',"ok", ...
        'campaignName',P.campaignName,'stageName',P.stageName, ...
        'sourceFingerprint',P.sourceFingerprint.combinedSHA256, ...
        'resultStage',Task.resultStage,'armName',P.armName, ...
        'armValue',Task.armValue,'algorithm',P.algorithm, ...
        'problem',Task.problem,'run',Task.run,'seed',Task.seed, ...
        'initialEpoch',Task.initialEpoch, ...
        'retrainEpoch',Task.retrainEpoch,'nCritic',Task.nCritic, ...
        'N',P.N,'D',P.D,'M',double(Problem.M),'maxFE',P.maxFE, ...
        'finalFE',double(Problem.FE),'targetFE',P.targetFE, ...
        'rawPoolSize',P.rawPoolSize, ...
        'expectedGuidedCount',P.expectedGuidedCount, ...
        'configuration',struct( ...
            'initialEpoch',Task.initialEpoch, ...
            'retrainEpoch',Task.retrainEpoch, ...
            'nCritic',Task.nCritic,'rawPoolSize',P.rawPoolSize, ...
            'targetFE',P.targetFE, ...
            'expectedGuidedCount',P.expectedGuidedCount), ...
        'trajectoryCount',numel(Trajectory.FE), ...
        'snapshotCount',numel(Snapshots), ...
        'startedAt',string(started), ...
        'finishedAt',string(datetime('now')), ...
        'wallClockSeconds',elapsed, ...
        'algorithmRuntimeSeconds',double(Algorithm.metric.runtime), ...
        'terminalRNG',terminalRNG);
    validateResultData(Task,P,Record,Trajectory,Snapshots,Audit);

    save(partialFile,'Record','Trajectory','Snapshots','Audit','-v7.3');
    PartialTask = Task;
    PartialTask.outputFile = string(partialFile);
    if ~resultComplete(PartialTask,P)
        error('CBSPairGuide:InvalidTrainingSchedulePartial', ...
            'The saved partial result failed strict validation: %s', ...
            partialFile);
    end
    atomicMove(partialFile,OutputFile, ...
        'CBSPairGuide:TrainingScheduleMoveFailed');

    function captureTrajectory(CurrentAlgorithm,CurrentProblem)
    %CAPTURETRAJECTORY Record one generation without perturbing the search.
        if isempty(CurrentAlgorithm.result)
            error('CBSPairGuide:MissingTrajectoryPopulation', ...
                'The output callback received no current population.');
        end
        Population = CurrentAlgorithm.result{end,2};
        savedFE = CurrentProblem.FE;
        savedRNG = rng;
        try
            igd = CurrentProblem.CalMetric('IGD',Population);
        catch err
            CurrentProblem.FE = savedFE;
            rng(savedRNG);
            rethrow(err);
        end
        CurrentProblem.FE = savedFE;
        rng(savedRNG);
        if ~isscalar(igd) || ~isreal(igd)
            error('CBSPairGuide:BadTrajectoryIGD', ...
                'IGD must be one real scalar at every generation.');
        end
        constraints = double(Population.cons);
        if isempty(constraints)
            feasibleCount = numel(Population);
        else
            feasibleCount = nnz(all(constraints <= 0,2));
        end
        fe = double(savedFE);
        if ~isempty(Trajectory.FE) && fe <= Trajectory.FE(end)
            error('CBSPairGuide:NonIncreasingCallbackFE', ...
                'Output callback FE values must increase strictly.');
        end
        Trajectory.FE(end+1,1) = fe;
        Trajectory.IGD(end+1,1) = double(igd);
        Trajectory.FeasibleCount(end+1,1) = double(feasibleCount);
    end
end

function complete = resultComplete(Task,P)
%RESULTCOMPLETE Validate a result from disk, including reused ratio files.

    complete = false;
    file = char(Task.outputFile);
    if ~isfile(file)
        return;
    end
    try
        variables = string({whos('-file',file).name});
        required = ["Record","Trajectory","Snapshots","Audit"];
        if any(~ismember(required,variables))
            return;
        end
        Data = load(file,'Record','Trajectory','Snapshots','Audit');
        validateResultData(Task,P,Data.Record,Data.Trajectory, ...
            Data.Snapshots,Data.Audit);
        complete = true;
    catch
        complete = false;
    end
end

function validateResultData(Task,P,R,T,S,A)
%VALIDATERESULTDATA Enforce identity, budget, snapshots, and training log.

    requiredRecord = {'schemaVersion','status','campaignName', ...
        'sourceFingerprint','stageName','resultStage','armName', ...
        'armValue','algorithm', ...
        'problem','run','seed','initialEpoch','retrainEpoch','nCritic', ...
        'N','D','M','maxFE','finalFE','targetFE','rawPoolSize', ...
        'expectedGuidedCount','configuration','trajectoryCount', ...
        'snapshotCount'};
    if ~isstruct(R) || ~isscalar(R) || ...
            ~all(isfield(R,requiredRecord))
        error('CBSPairGuide:BadTrainingScheduleRecord', ...
            'Record is missing required identity or configuration fields.');
    end
    exact = string(R.schemaVersion) == P.schemaVersion && ...
        string(R.status) == "ok" && ...
        string(R.campaignName) == P.campaignName && ...
        string(R.sourceFingerprint) == ...
            P.sourceFingerprint.combinedSHA256 && ...
        string(R.stageName) == Task.resultStage && ...
        string(R.resultStage) == Task.resultStage && ...
        string(R.algorithm) == P.algorithm && ...
        string(R.problem) == Task.problem && ...
        double(R.run) == Task.run && double(R.seed) == Task.seed && ...
        double(R.initialEpoch) == Task.initialEpoch && ...
        double(R.retrainEpoch) == Task.retrainEpoch && ...
        double(R.nCritic) == Task.nCritic && ...
        double(R.N) == P.N && double(R.D) == P.D && ...
        isscalar(R.M) && isfinite(double(R.M)) && double(R.M) >= 2 && ...
        double(R.maxFE) == P.maxFE && double(R.finalFE) == P.maxFE && ...
        isequal(double(R.targetFE(:)'),double(P.targetFE(:)')) && ...
        double(R.rawPoolSize) == P.rawPoolSize && ...
        double(R.expectedGuidedCount) == P.expectedGuidedCount;
    if ~Task.reused
        exact = exact && string(R.armName) == P.armName && ...
            double(R.armValue) == Task.armValue;
    end
    if ~exact
        error('CBSPairGuide:TrainingScheduleIdentityMismatch', ...
            'Saved result identity, FE budget, or task config is wrong.');
    end
    validateConfiguration(R.configuration,Task,P);
    validateTrajectory(T,R,P);
    validateSnapshots(S,double(R.M),P);
    validateTrainingAudit(A,Task,P);
    if double(R.trajectoryCount) ~= numel(T.FE) || ...
            double(R.snapshotCount) ~= numel(S)
        error('CBSPairGuide:TrainingScheduleCountMismatch', ...
            'Record counts do not match trajectory or snapshots.');
    end
end

function validateConfiguration(C,Task,P)
    required = {'initialEpoch','retrainEpoch','nCritic', ...
        'rawPoolSize','targetFE','expectedGuidedCount'};
    if ~isstruct(C) || ~isscalar(C) || ~all(isfield(C,required)) || ...
            double(C.initialEpoch) ~= Task.initialEpoch || ...
            double(C.retrainEpoch) ~= Task.retrainEpoch || ...
            double(C.nCritic) ~= Task.nCritic || ...
            double(C.rawPoolSize) ~= P.rawPoolSize || ...
            ~isequal(double(C.targetFE(:)'),double(P.targetFE(:)')) || ...
            double(C.expectedGuidedCount) ~= P.expectedGuidedCount
        error('CBSPairGuide:BadSavedTrainingConfiguration', ...
            'Record.configuration does not reproduce the task.');
    end
end

function validateTrajectory(T,R,P)
    required = {'FE','IGD','FeasibleCount'};
    if ~isstruct(T) || ~isscalar(T) || ~all(isfield(T,required))
        error('CBSPairGuide:BadTrainingScheduleTrajectory', ...
            'Trajectory must be a scalar struct with FE/IGD/FeasibleCount.');
    end
    FE = double(T.FE(:));
    IGD = double(T.IGD(:));
    Feasible = double(T.FeasibleCount(:));
    if numel(FE) < 2 || numel(IGD) ~= numel(FE) || ...
            numel(Feasible) ~= numel(FE) || ...
            any(~isfinite(FE)) || any(FE ~= round(FE)) || ...
            any(diff(FE) <= 0) || FE(end) ~= P.maxFE || ...
            FE(1) < 2*P.N || ~isreal(IGD) || ...
            any(IGD(isfinite(IGD)) < 0) || any(IGD == -Inf) || ...
            any(~isfinite(Feasible) | Feasible < 0 | ...
                Feasible > P.N | Feasible ~= round(Feasible)) || ...
            double(R.finalFE) ~= FE(end)
        error('CBSPairGuide:InvalidTrainingScheduleTrajectory', ...
            'Trajectory values, ordering, or terminal FE are invalid.');
    end
end

function validateSnapshots(S,M,P)
    required = {'targetFE','actualFE','poolFE','rawCount', ...
        'targetCount','centerCount','requestedCount','guidedCount', ...
        'fallbackCount','rawObjs','rawCons','targetObjs','targetCons', ...
        'centerObjs','centerCons','guidedObjs','guidedCons', ...
        'population1Objs','population1Cons', ...
        'population2Objs','population2Cons'};
    if ~isstruct(S) || numel(S) ~= 10 || ~all(isfield(S,required)) || ...
            ~isequal(double([S.targetFE]),double(P.targetFE)) || ...
            any(~isfinite([S.actualFE])) || any(diff([S.actualFE]) < 0) || ...
            any([S.actualFE] > P.maxFE) || any(~isfinite([S.poolFE])) || ...
            any([S.poolFE] >= [S.actualFE])
        error('CBSPairGuide:BadTrainingScheduleSnapshots', ...
            'Snapshot count, targets, or FE alignment is invalid.');
    end
    layers = {'raw','target','center','guided','population1','population2'};
    for i = 1 : numel(S)
        % PairGuide selects one common mapped-row set: each selected row has
        % exactly one raw target, one mapped center, and one DE child.
        % Ordinary-DE fallbacks are counted separately and are not captured
        % as target/center/guided layers.
        if S(i).rawCount ~= P.rawPoolSize || ...
                S(i).requestedCount ~= P.expectedGuidedCount || ...
                S(i).guidedCount+S(i).fallbackCount ~= ...
                P.expectedGuidedCount || ...
                S(i).targetCount ~= S(i).guidedCount || ...
                S(i).centerCount ~= S(i).guidedCount
            error('CBSPairGuide:BadTrainingScheduleSnapshotCounts', ...
                'Snapshot %d has inconsistent raw/guided counts.',i);
        end
        for layer = 1 : numel(layers)
            objs = S(i).([layers{layer},'Objs']);
            cons = S(i).([layers{layer},'Cons']);
            if ~isnumeric(objs) || size(objs,2) ~= M || ...
                    ~isnumeric(cons) || size(cons,1) ~= size(objs,1)
                error('CBSPairGuide:BadTrainingScheduleSnapshotShape', ...
                    'Snapshot %d layer %s has invalid shape.', ...
                    i,layers{layer});
            end
        end
        if size(S(i).rawObjs,1) ~= P.rawPoolSize || ...
                size(S(i).targetObjs,1) ~= S(i).targetCount || ...
                size(S(i).centerObjs,1) ~= S(i).centerCount || ...
                size(S(i).guidedObjs,1) ~= S(i).guidedCount || ...
                size(S(i).population1Objs,1) ~= P.N || ...
                size(S(i).population2Objs,1) ~= P.N
            error('CBSPairGuide:BadTrainingScheduleSnapshotRows', ...
                'Snapshot %d layer row counts are invalid.',i);
        end
    end
end

function validateTrainingAudit(A,Task,P)
    required = {'generationMode','useMode','nCritic','pairInitialEpoch', ...
        'pairRetrainEpoch','diagnosticsEnabled','oracleAuditDisabled', ...
        'pairTrainingEvents','pairTrainingLog'};
    if ~isstruct(A) || ~isscalar(A) || ~all(isfield(A,required)) || ...
            string(A.generationMode) ~= "pair_guide" || ...
            string(A.useMode) ~= "pair_guide" || ...
            double(A.nCritic) ~= Task.nCritic || ...
            double(A.pairInitialEpoch) ~= P.initialEpoch || ...
            double(A.pairRetrainEpoch) ~= Task.retrainEpoch || ...
            ~logical(A.diagnosticsEnabled) || ...
            logical(A.oracleAuditDisabled)
        error('CBSPairGuide:BadTrainingScheduleAuditConfig', ...
            'Audit does not confirm the requested experiment config.');
    end
    Log = A.pairTrainingLog;
    requiredLog = {'fe','kind','nCritic','epochs','trainingPairs', ...
        'updates','pairVisits','batchesPerEpoch'};
    if ~isstruct(Log) || isempty(Log) || ~all(isfield(Log,requiredLog)) || ...
            double(A.pairTrainingEvents) ~= numel(Log)
        error('CBSPairGuide:MissingTrainingScheduleLog', ...
            'Audit must contain at least one complete pair-training event.');
    end
    kinds = string({Log.kind});
    epochs = double([Log.epochs]);
    critics = double([Log.nCritic]);
    pairs = double([Log.trainingPairs]);
    batches = double([Log.batchesPerEpoch]);
    updates = double([Log.updates]);
    visits = double([Log.pairVisits]);
    eventFE = double([Log.fe]);
    if kinds(1) ~= "initial" || epochs(1) ~= P.initialEpoch || ...
            any(kinds(2:end) ~= "retrain") || ...
            any(epochs(2:end) ~= Task.retrainEpoch) || ...
            any(critics ~= Task.nCritic) || ...
            any(~isfinite(eventFE)) || any(diff(eventFE) <= 0) || ...
            any(pairs < P.minGANTrainCount | pairs ~= round(pairs)) || ...
            any(batches < 1 | batches ~= round(batches)) || ...
            any(updates ~= epochs.*batches) || ...
            any(visits ~= epochs.*pairs)
        error('CBSPairGuide:InvalidTrainingScheduleLog', ...
            ['Training log must start at 500 epochs and use only the ', ...
             'candidate retrain epoch thereafter.']);
    end
end

function mask = tasksComplete(Tasks,P)
    mask = false(numel(Tasks),1);
    for i = 1 : numel(Tasks)
        mask(i) = resultComplete(Tasks(i),P);
    end
end

function [chosenNCritic,representativeRunMap] = freezeRatioDecision( ...
        ratioDir,P,Analysis)
%FREEZERATIODECISION Persist the stage-one decision exactly once.

    if ~isfield(Analysis,'selectedNCritic') || ...
            ~ismember(double(Analysis.selectedNCritic),P.arms)
        error('CBSPairGuide:BadRatioDecision', ...
            'Ratio analyzer returned an invalid selected nCritic.');
    end
    representativeFile = fullfile(ratioDir,'analysis', ...
        'representative_runs.mat');
    if ~isfile(representativeFile)
        error('CBSPairGuide:MissingRepresentativeRuns', ...
            'Ratio analysis did not write representative_runs.mat.');
    end
    Data = load(representativeFile,'RepresentativeRuns');
    if ~isfield(Data,'RepresentativeRuns') || ...
            ~istable(Data.RepresentativeRuns) || ...
            ~all(ismember({'problem','run'}, ...
            Data.RepresentativeRuns.Properties.VariableNames))
        error('CBSPairGuide:BadRepresentativeRuns', ...
            'RepresentativeRuns must be a problem/run table.');
    end
    proposedNCritic = double(Analysis.selectedNCritic);
    proposedMap = Data.RepresentativeRuns;
    sourceFingerprint = P.sourceFingerprint.combinedSHA256;
    frozenFile = fullfile(ratioDir,'analysis','frozen_decision.mat');
    if isfile(frozenFile)
        Frozen = load(frozenFile,'chosenNCritic','representativeRunMap', ...
            'sourceFingerprint');
        if ~isfield(Frozen,'chosenNCritic') || ...
                ~isfield(Frozen,'representativeRunMap') || ...
                ~isfield(Frozen,'sourceFingerprint') || ...
                double(Frozen.chosenNCritic) ~= proposedNCritic || ...
                ~isequaln(Frozen.representativeRunMap,proposedMap) || ...
                string(Frozen.sourceFingerprint) ~= sourceFingerprint
            error('CBSPairGuide:FrozenRatioDecisionConflict', ...
                'Existing frozen ratio decision conflicts with analysis.');
        end
        chosenNCritic = double(Frozen.chosenNCritic);
        representativeRunMap = Frozen.representativeRunMap;
    else
        chosenNCritic = proposedNCritic;
        representativeRunMap = proposedMap;
        partial = [frozenFile,'.partial.mat'];
        save(partial,'chosenNCritic','representativeRunMap', ...
            'sourceFingerprint','-v7.3');
        Check = load(partial,'chosenNCritic','representativeRunMap', ...
            'sourceFingerprint');
        if Check.chosenNCritic ~= chosenNCritic || ...
                ~isequaln(Check.representativeRunMap,representativeRunMap) || ...
                string(Check.sourceFingerprint) ~= sourceFingerprint
            error('CBSPairGuide:InvalidFrozenRatioPartial', ...
                'Frozen ratio decision failed read-back validation.');
        end
        atomicMove(partial,frozenFile, ...
            'CBSPairGuide:FrozenRatioDecisionMoveFailed');
    end
    writeFrozenDecisionText(ratioDir,P,chosenNCritic, ...
        representativeRunMap,frozenFile);
end

function writeFrozenDecisionText(ratioDir,P,chosenNCritic,Map,matFile)
    lines = ["schemaVersion="+P.schemaVersion; ...
        "sourceFingerprint="+P.sourceFingerprint.combinedSHA256; ...
        "chosenNCritic="+chosenNCritic; ...
        "sourceFile="+string(matFile)];
    problems = string(Map.problem);
    runs = double(Map.run);
    for i = 1 : height(Map)
        lines(end+1,1) = "representativeRun."+problems(i)+"="+runs(i); %#ok<AGROW>
    end
    writeTextAtomic(lines,fullfile(ratioDir,'analysis', ...
        'frozen_decision.txt'));
end

function ensureCampaignManifest(campaignDir,CampaignProtocol)
    file = fullfile(campaignDir,'campaign_manifest.mat');
    if isfile(file)
        Data = load(file,'CampaignProtocol');
        if ~isfield(Data,'CampaignProtocol') || ...
                ~isequaln(Data.CampaignProtocol,CampaignProtocol)
            error('CBSPairGuide:CampaignManifestConflict', ...
                'Existing root campaign manifest uses another protocol.');
        end
        return;
    end
    partial = [file,'.partial.mat'];
    save(partial,'CampaignProtocol','-v7.3');
    atomicMove(partial,file,'CBSPairGuide:CampaignManifestMoveFailed');
end

function ensureStageManifest(stageDir,Protocol,Tasks)
    ensureFolder(stageDir);
    file = fullfile(stageDir,'campaign_manifest.mat');
    if isfile(file)
        Data = load(file,'Protocol','Tasks');
        if ~isfield(Data,'Protocol') || ~isfield(Data,'Tasks') || ...
                ~isequaln(Data.Protocol,Protocol) || ...
                ~isequaln(Data.Tasks,Tasks)
            error('CBSPairGuide:StageManifestConflict', ...
                'Existing %s stage manifest uses another protocol.', ...
                Protocol.stageName);
        end
        return;
    end
    partial = [file,'.partial.mat'];
    save(partial,'Protocol','Tasks','-v7.3');
    atomicMove(partial,file,'CBSPairGuide:StageManifestMoveFailed');
end

function State = loadCampaignState(campaignDir,P)
    file = fullfile(campaignDir,'campaign_state.mat');
    if isfile(file)
        Data = load(file,'State');
        if ~isfield(Data,'State') || ...
                string(Data.State.schemaVersion) ~= P.schemaVersion
            error('CBSPairGuide:CampaignStateConflict', ...
                'Existing campaign state has another schema.');
        end
        State = Data.State;
        return;
    end
    State = struct('schemaVersion',P.schemaVersion, ...
        'campaignName',P.campaignName,'status',"created", ...
        'currentStage',"",'startedAt',string(datetime('now')), ...
        'finishedAt',"",'ratioCompleteTasks',0, ...
        'epochCompleteTasks',0,'chosenNCritic',NaN, ...
        'selectedRetrainEpoch',NaN,'error',"");
end

function saveCampaignState(campaignDir,Protocol,State)
    file = fullfile(campaignDir,'campaign_state.mat');
    partial = [file,'.partial.mat'];
    save(partial,'State','Protocol','-v7.3');
    atomicReplace(partial,file,'CBSPairGuide:CampaignStateMoveFailed');
    lines = ["schemaVersion="+State.schemaVersion; ...
        "status="+State.status;"currentStage="+State.currentStage; ...
        "ratioCompleteTasks="+State.ratioCompleteTasks; ...
        "epochCompleteTasks="+State.epochCompleteTasks; ...
        "chosenNCritic="+State.chosenNCritic; ...
        "selectedRetrainEpoch="+State.selectedRetrainEpoch];
    writeTextAtomic(lines,fullfile(campaignDir,'campaign_state.txt'));
end

function State = loadStageState(stageDir,P,Tasks)
    file = fullfile(stageDir,'campaign_state.mat');
    if isfile(file)
        Data = load(file,'StageState');
        if ~isfield(Data,'StageState') || ...
                string(Data.StageState.schemaVersion) ~= P.schemaVersion || ...
                string(Data.StageState.stageName) ~= P.stageName
            error('CBSPairGuide:StageStateConflict', ...
                'Existing %s stage state has another protocol.',P.stageName);
        end
        State = Data.StageState;
        return;
    end
    State = struct('schemaVersion',P.schemaVersion, ...
        'campaignName',P.campaignName,'stageName',P.stageName, ...
        'status',"created",'startedAt',string(datetime('now')), ...
        'finishedAt',"",'totalTasks',numel(Tasks), ...
        'completeTasks',0,'remainingTasks',numel(Tasks), ...
        'reusedTasks',nnz([Tasks.reused]),'attempt',0,'error',"");
end

function State = updateStageState(stageDir,State,P,Tasks)
    complete = tasksComplete(Tasks,P);
    State.totalTasks = numel(Tasks);
    State.completeTasks = nnz(complete);
    State.remainingTasks = numel(Tasks)-State.completeTasks;
    StageState = State;
    file = fullfile(stageDir,'campaign_state.mat');
    partial = [file,'.partial.mat'];
    Protocol = P;
    save(partial,'StageState','Protocol','-v7.3');
    atomicReplace(partial,file,'CBSPairGuide:StageStateMoveFailed');
    lines = ["schemaVersion="+State.schemaVersion; ...
        "stageName="+State.stageName;"status="+State.status; ...
        "completeTasks="+State.completeTasks; ...
        "remainingTasks="+State.remainingTasks; ...
        "reusedTasks="+State.reusedTasks;"attempt="+State.attempt];
    writeTextAtomic(lines,fullfile(stageDir,'campaign_state.txt'));
end

function saveSummary(campaignDir,Summary,RatioAnalysis, ...
        EpochAnalysis,Figures)
    file = fullfile(campaignDir,'campaign_summary.mat');
    partial = [file,'.partial.mat'];
    save(partial,'Summary','RatioAnalysis','EpochAnalysis','Figures','-v7.3');
    Check = load(partial,'Summary');
    if ~isfield(Check,'Summary') || ...
            Check.Summary.chosenNCritic ~= Summary.chosenNCritic || ...
            Check.Summary.selectedRetrainEpoch ~= ...
            Summary.selectedRetrainEpoch
        error('CBSPairGuide:InvalidCampaignSummaryPartial', ...
            'Campaign summary failed read-back validation.');
    end
    atomicReplace(partial,file,'CBSPairGuide:CampaignSummaryMoveFailed');
    lines = ["campaignName="+Summary.campaignName; ...
        "sourceFingerprint="+Summary.sourceFingerprint; ...
        "chosenNCritic="+Summary.chosenNCritic; ...
        "selectedRetrainEpoch="+Summary.selectedRetrainEpoch; ...
        "ratioTaskCount="+Summary.ratioTaskCount; ...
        "epochExecutedTaskCount="+Summary.epochExecutedTaskCount; ...
        "epochReusedTaskCount="+Summary.epochReusedTaskCount; ...
        "figureCount="+Summary.figureCount];
    writeTextAtomic(lines,fullfile(campaignDir,'campaign_summary.txt'));
end

function writeFailure(failureDir,Task,attempt,err)
    ensureFolder(failureDir);
    stamp = timestampToken();
    base = sprintf('%s_attempt%02d_%s',char(Task.taskId),attempt,stamp);
    Failure = struct('task',Task,'attempt',attempt, ...
        'identifier',string(err.identifier),'message',string(err.message), ...
        'report',string(getReport(err,'extended','hyperlinks','off')), ...
        'failedAt',string(datetime('now')));
    save(fullfile(failureDir,[base,'.mat']),'Failure','-v7.3');
    writelines(Failure.report,fullfile(failureDir,[base,'.txt']));
end

function quarantineFile(file,failureDir,Task,kind)
    ensureFolder(failureDir);
    stamp = timestampToken();
    [~,name,ext] = fileparts(file);
    destination = fullfile(failureDir,sprintf('%s_%s_%s_%s%s', ...
        char(Task.taskId),char(kind),stamp,name,ext));
    atomicMove(file,destination,'CBSPairGuide:QuarantineMoveFailed');
end

function atomicMove(source,destination,errorId)
    if isfile(destination)
        error(errorId,'Atomic destination already exists: %s',destination);
    end
    [moved,message] = movefile(source,destination);
    if ~moved
        error(errorId,'%s',message);
    end
end

function atomicReplace(source,destination,errorId)
    [moved,message] = movefile(source,destination,'f');
    if ~moved
        error(errorId,'%s',message);
    end
end

function writeTextAtomic(lines,file)
    partial = [file,'.partial.txt'];
    writelines(lines,partial);
    atomicReplace(partial,file,'CBSPairGuide:StateTextMoveFailed');
end

function ensureFolder(folder)
    if ~isfolder(folder)
        mkdir(folder);
    end
end

function Fingerprint = sourceFingerprint(rootPath)
%SOURCEFINGERPRINT Freeze all code that defines or interprets the campaign.

    relativeFiles = [ ...
        "Algorithms/Multi-objective optimization/CBS-CGAN/Core/"+ ...
            "CBS_RegionWGAN_GP_Core.m"; ...
        "Algorithms/Multi-objective optimization/CBS-CGAN/Core/"+ ...
            "PairBoundaryWGAN_RC.m"; ...
        "Algorithms/Multi-objective optimization/CBS-CGAN/Core/"+ ...
            "PairBoundaryArchive_RC.m"; ...
        "Algorithms/Multi-objective optimization/CBS-CGAN-PairGuide/"+ ...
            "CBS_RegionWGAN_GP_PairGuide.m"; ...
        "Algorithms/Multi-objective optimization/CBS-CGAN/Support/"+ ...
            "run_CBS_PairGuide_training_schedule_campaign.m"; ...
        "Algorithms/Multi-objective optimization/CBS-CGAN/Support/"+ ...
            "analyze_CBS_PairGuide_training_schedule_stage.m"; ...
        "Algorithms/Multi-objective optimization/CBS-CGAN/Support/"+ ...
            "render_CBS_PairGuide_training_schedule_figures.m"];
    roles = ["core";"pairWGAN";"pairArchive";"pairGuideEntry"; ...
        "runner";"analyzer";"renderer"];
    Files = repmat(struct('role',"",'relativePath',"", ...
        'sha256',""),numel(relativeFiles),1);
    canonical = "";
    for i = 1 : numel(relativeFiles)
        file = fullfile(rootPath,char(relativeFiles(i)));
        if ~isfile(file)
            error('CBSPairGuide:MissingFingerprintSource', ...
                'Cannot fingerprint missing campaign source: %s',file);
        end
        digest = sha256File(file);
        Files(i) = struct('role',roles(i), ...
            'relativePath',relativeFiles(i),'sha256',digest);
        canonical = canonical+roles(i)+"|"+relativeFiles(i)+"|"+ ...
            digest+newline;
    end
    Fingerprint = struct();
    Fingerprint.algorithm = "SHA-256";
    Fingerprint.files = Files;
    Fingerprint.combinedSHA256 = sha256Bytes( ...
        unicode2native(char(canonical),'UTF-8'));
end

function valid = validSourceFingerprint(F)
    valid = isstruct(F) && isscalar(F) && ...
        all(isfield(F,{'algorithm','files','combinedSHA256'})) && ...
        string(F.algorithm) == "SHA-256" && ...
        isstruct(F.files) && numel(F.files) == 7 && ...
        all(isfield(F.files,{'role','relativePath','sha256'})) && ...
        strlength(string(F.combinedSHA256)) == 64 && ...
        all(strlength(string({F.files.sha256})) == 64);
end

function assertSourceFingerprint(rootPath,expected)
    current = sourceFingerprint(rootPath);
    if ~isequaln(current,expected)
        error('CBSPairGuide:TrainingScheduleSourceChanged', ...
            ['Campaign source changed after the manifest was frozen; ', ...
             'refusing to mix result identities.']);
    end
end

function digest = sha256File(file)
    engine = java.security.MessageDigest.getInstance('SHA-256');
    fid = fopen(file,'rb');
    if fid < 0
        error('CBSPairGuide:FingerprintReadFailed', ...
            'Cannot read campaign source for hashing: %s',file);
    end
    cleanup = onCleanup(@()fclose(fid));
    while true
        bytes = fread(fid,1024*1024,'*uint8');
        if isempty(bytes)
            break;
        end
        engine.update(typecast(bytes(:),'int8'));
    end
    clear cleanup;
    digest = digestHex(engine.digest());
end

function digest = sha256Bytes(bytes)
    engine = java.security.MessageDigest.getInstance('SHA-256');
    engine.update(typecast(uint8(bytes(:)),'int8'));
    digest = digestHex(engine.digest());
end

function digest = digestHex(bytes)
    bytes = typecast(bytes,'uint8');
    digest = string(lower(reshape(dec2hex(bytes,2).',1,[])));
end

function removeMarker(file)
    if isfile(file)
        delete(file);
    end
end

function stamp = timestampToken()
    stamp = char(datetime('now','Format','yyyyMMdd_HHmmss_SSS'));
end

function setProcessThreadLimits()
    names = {'OMP_NUM_THREADS','OPENBLAS_NUM_THREADS', ...
        'MKL_NUM_THREADS','VECLIB_MAXIMUM_THREADS'};
    for i = 1 : numel(names)
        setenv(names{i},'1');
    end
end

function [pool,ownsPool] = exactProcessPool(nWorker)
    pool = gcp('nocreate');
    ownsPool = isempty(pool);
    if ownsPool
        pool = parpool("Processes",nWorker);
    elseif pool.NumWorkers ~= nWorker || contains(class(pool),'ThreadPool')
        error('CBSPairGuide:TrainingScheduleParallelPool', ...
            'The existing pool must contain exactly %d process workers.', ...
            nWorker);
    end
end

function closeOwnedPool(pool,ownsPool)
    if ownsPool && ~isempty(pool) && isvalid(pool)
        delete(pool);
    end
end
