function Summary = run_CBS_PairGuide_quota_sweep(rootPath,nWorker)
%RUN_CBS_PAIRGUIDE_QUOTA_SWEEP Compare 20/30/40/50% PairGuide quotas.

    if nargin < 1 || isempty(rootPath)
        rootPath = fileparts(which('platemo'));
    end
    if nargin < 2 || isempty(nWorker)
        nWorker = 10;
    end
    rootPath = char(rootPath);
    addCBSPaths(rootPath);
    Campaign = campaignProtocol(rootPath,nWorker);
    validateCampaign(Campaign);
    Baseline = validateBaseline(Campaign);
    Campaign.baselineSourceFingerprint = Baseline.sourceFingerprint;

    campaignDir = fullfile(rootPath,'Data',char(Campaign.campaignName));
    resultDir = fullfile(campaignDir,'results');
    failureDir = fullfile(campaignDir,'failures');
    ensureFolder(campaignDir);
    ensureFolder(resultDir);
    ensureFolder(failureDir);
    Tasks = buildTasks(Campaign,resultDir);
    freezeManifest(fullfile(campaignDir,'campaign_manifest.mat'), ...
        Campaign,Baseline,Tasks);

    State = struct('schemaVersion',Campaign.schemaVersion, ...
        'status',"running",'startedAt',string(datetime('now')), ...
        'finishedAt',"",'attempt',0,'totalTasks',numel(Tasks), ...
        'completeTasks',nnz(tasksComplete(Tasks,Campaign)), ...
        'remainingTasks',0,'error',"");
    State.remainingTasks = State.totalTasks-State.completeTasks;
    saveState(State,campaignDir);
    writeRunningMarker(Campaign,State,campaignDir);

    try
        smokeTest(Campaign);
        assertSourceFingerprint(rootPath,Campaign.sourceFingerprint);
        setSingleThreadLibraries();
        [pool,ownsPool] = exactProcessPool(Campaign.nWorker);
        poolCleanup = onCleanup(@()closeOwnedPool(pool,ownsPool));

        pending = Tasks(~tasksComplete(Tasks,Campaign));
        for attempt = 1 : Campaign.maxAttempts
            if isempty(pending)
                break;
            end
            State.attempt = attempt;
            saveState(State,campaignDir);
            fprintf('PairGuide quota sweep: %d tasks, attempt %d/%d.\n', ...
                numel(pending),attempt,Campaign.maxAttempts);
            parfor i = 1 : numel(pending)
                Task = pending(i);
                try
                    runOne(Task,Campaign);
                catch err
                    writeFailure(failureDir,Task,attempt,err);
                end
            end
            pending = pending(~tasksComplete(pending,Campaign));
            State.completeTasks = nnz(tasksComplete(Tasks,Campaign));
            State.remainingTasks = State.totalTasks-State.completeTasks;
            saveState(State,campaignDir);
        end
        clear poolCleanup;
        if ~isempty(pending)
            error('CBSPairGuide:QuotaSweepTasksFailed', ...
                '%d tasks failed after %d attempts.',numel(pending), ...
                Campaign.maxAttempts);
        end

        validateBaseline(Campaign);
        assertSourceFingerprint(rootPath,Campaign.sourceFingerprint);
        Summary = summarizeResults(campaignDir,Tasks,Campaign);
        save(fullfile(campaignDir,'summary.mat'),'Summary','-v7.3');
        State.status = "complete";
        State.finishedAt = string(datetime('now'));
        State.completeTasks = State.totalTasks;
        State.remainingTasks = 0;
        saveState(State,campaignDir);
        writelines(["status=complete"; ...
            "newTaskCount="+State.totalTasks; ...
            "baselineTaskCount=60"; ...
            "pairedObservations="+height(Summary.PairedTrajectory); ...
            "checkpointComparisons="+height(Summary.CheckpointComparison); ...
            "finishedAt="+State.finishedAt], ...
            fullfile(campaignDir,'COMPLETE.txt'));
        removeMarker(fullfile(campaignDir,'RUNNING.txt'));
    catch err
        State.status = "failed";
        State.finishedAt = string(datetime('now'));
        State.completeTasks = nnz(tasksComplete(Tasks,Campaign));
        State.remainingTasks = State.totalTasks-State.completeTasks;
        State.error = string(getReport(err,'extended','hyperlinks','off'));
        saveState(State,campaignDir);
        writelines(State.error,fullfile(campaignDir,'FAILED.txt'));
        removeMarker(fullfile(campaignDir,'RUNNING.txt'));
        rethrow(err);
    end
end

function C = campaignProtocol(rootPath,nWorker)
    C = struct( ...
        'schemaVersion',"CBS-PairGuide-quota-sweep-v1", ...
        'campaignName',"CBS_PairGuide_quota_sweep_v1_20260903", ...
        'rootPath',string(rootPath), ...
        'baselineResultDir',string(fullfile(rootPath,'Data', ...
            'CBS_PairGuide_mainline_vs_DE20_v1_20260902','results')), ...
        'baselineSchemaVersion',"CBS-PairGuide-mainline-vs-DE20-v1", ...
        'baselineSourceFingerprint',"", ...
        'problems',["LIRCMOP5_BC","LIRCMOP7_BC","LIRCMOP8_BC", ...
            "LIRCMOP10_BC","LIRCMOP12_BC","LIRCMOP14_BC"], ...
        'runs',1:10,'baselineShare',0.20, ...
        'shares',[0.30 0.40 0.50], ...
        'armNames',["quota30","quota40","quota50"], ...
        'algorithms',["CBS_RegionWGAN_GP_PairGuide_Quota30", ...
            "CBS_RegionWGAN_GP_PairGuide_Quota40", ...
            "CBS_RegionWGAN_GP_PairGuide_Quota50"], ...
        'N',100,'D',30,'maxFE',100000,'save',10, ...
        'expectedFE',10000:10000:100000,'metric',"IGD", ...
        'initialEpoch',500,'retrainEpoch',10,'nCritic',5, ...
        'gaShare',0.25,'guideGenerationCount',499, ...
        'nWorker',double(nWorker),'maxAttempts',3, ...
        'sourceFingerprint',sourceFingerprint(rootPath));
end

function validateCampaign(C)
    if numel(C.problems) ~= 6 || ~isequal(C.runs,1:10) || ...
            C.baselineShare ~= 0.20 || ...
            ~isequal(C.shares,[0.30 0.40 0.50]) || ...
            ~isequal(C.armNames,["quota30","quota40","quota50"]) || ...
            C.N ~= 100 || C.D ~= 30 || C.maxFE ~= 100000 || ...
            C.save ~= 10 || ~isequal(C.expectedFE,10000:10000:100000) || ...
            C.metric ~= "IGD" || C.initialEpoch ~= 500 || ...
            C.retrainEpoch ~= 10 || C.nCritic ~= 5 || ...
            C.gaShare ~= 0.25 || C.guideGenerationCount ~= 499 || ...
            C.nWorker < 1 || C.nWorker > 10 || C.maxAttempts ~= 3
        error('CBSPairGuide:BadQuotaSweepProtocol', ...
            'The locked quota-sweep protocol was changed.');
    end
end

function Baseline = validateBaseline(C)
    fingerprints = strings(numel(C.problems)*numel(C.runs),1);
    row = 0;
    for problem = C.problems
        for run = C.runs
            row = row+1;
            file = baselineFile(C,problem,run);
            if ~isfile(file)
                error('CBSPairGuide:MissingQuotaBaseline', ...
                    'Missing 20%% baseline result: %s',file);
            end
            Data = load(file,'Record','FE','IGD');
            R = Data.Record;
            valid = string(R.schemaVersion) == C.baselineSchemaVersion && ...
                string(R.arm) == "mainline" && ...
                string(R.algorithm) == "CBS_RegionWGAN_GP_PairGuide" && ...
                string(R.problem) == problem && R.run == run && ...
                R.seed == run && R.N == C.N && R.D == C.D && ...
                R.maxFE == C.maxFE && R.finalFE == C.maxFE && ...
                R.save == C.save && string(R.metric) == C.metric && ...
                R.initialEpoch == C.initialEpoch && ...
                R.retrainEpoch == C.retrainEpoch && ...
                R.nCritic == C.nCritic && R.quotaPerGeneration == 20 && ...
                R.quotaRequested == 20*C.guideGenerationCount && ...
                string(R.guideGenerationMode) == "pair_guide" && ...
                string(R.guideUseMode) == "pair_guide" && ...
                isequal(reshape(double(Data.FE),1,[]),C.expectedFE) && ...
                numel(Data.IGD) == numel(C.expectedFE) && ...
                all(isfinite(double(Data.IGD(:))));
            if ~valid
                error('CBSPairGuide:InvalidQuotaBaseline', ...
                    '20%% baseline violates the locked protocol: %s',file);
            end
            fingerprints(row) = string(R.sourceFingerprint);
        end
    end
    if numel(unique(fingerprints)) ~= 1 || ...
            strlength(fingerprints(1)) ~= 64
        error('CBSPairGuide:MixedQuotaBaselineIdentity', ...
            'All 20%% baseline results must share one source fingerprint.');
    end
    Baseline = struct('schemaVersion',C.baselineSchemaVersion, ...
        'resultCount',row,'sourceFingerprint',fingerprints(1), ...
        'resultDir',C.baselineResultDir);
end

function file = baselineFile(C,problem,run)
    file = fullfile(C.baselineResultDir,sprintf( ...
        '%s_mainline_run%02d.mat',problem,run));
end

function Tasks = buildTasks(C,resultDir)
    template = struct('problem',"",'run',0,'seed',0,'arm',"", ...
        'algorithm',"",'share',0,'quotaPercent',0,'outputFile',"");
    count = numel(C.problems)*numel(C.runs)*numel(C.shares);
    Tasks = repmat(template,count,1);
    row = 0;
    for problem = C.problems
        for run = C.runs
            for arm = 1 : numel(C.shares)
                row = row+1;
                Tasks(row).problem = problem;
                Tasks(row).run = run;
                Tasks(row).seed = run;
                Tasks(row).arm = C.armNames(arm);
                Tasks(row).algorithm = C.algorithms(arm);
                Tasks(row).share = C.shares(arm);
                Tasks(row).quotaPercent = round(100*C.shares(arm));
                Tasks(row).outputFile = string(fullfile(resultDir, ...
                    sprintf('%s_quota%02d_run%02d.mat',problem, ...
                    Tasks(row).quotaPercent,run)));
            end
        end
    end
end

function freezeManifest(file,Campaign,Baseline,Tasks)
    if isfile(file)
        Existing = load(file,'Campaign','Baseline','Tasks');
        if ~isequaln(Existing.Campaign,Campaign) || ...
                ~isequaln(Existing.Baseline,Baseline) || ...
                ~isequaln(Existing.Tasks,Tasks)
            error('CBSPairGuide:QuotaSweepManifestConflict', ...
                'Existing campaign manifest uses another protocol.');
        end
    else
        save(file,'Campaign','Baseline','Tasks','-v7.3');
    end
end

function runOne(Task,C)
    if resultComplete(Task,C)
        return;
    end
    if isfile(Task.outputFile)
        error('CBSPairGuide:InvalidQuotaSweepResult', ...
            'Refusing to overwrite an invalid result: %s',Task.outputFile);
    end

    rng(Task.seed,'twister');
    problemConstructor = str2func(char(Task.problem));
    Problem = problemConstructor('N',C.N,'D',C.D,'maxFE',C.maxFE, ...
        'maxRuntime',Inf);
    algorithmConstructor = str2func(char(Task.algorithm));
    Algorithm = algorithmConstructor('save',C.save,'run',Task.run, ...
        'outputFcn',@(varargin)[]);
    startedAt = string(datetime('now'));
    timer = tic;
    Algorithm.Solve(Problem);
    wallClockSeconds = toc(timer);
    FE = reshape(double(cell2mat(Algorithm.result(:,1))),[],1);
    IGD = reshape(double(Algorithm.CalMetric('IGD')),[],1);
    Audit = Algorithm.guideExperimentSnapshot();
    validateRun(Task,C,Problem,FE,IGD,Audit);

    expectedRequested = expectedQuota(Task,C);
    Record = struct( ...
        'schemaVersion',C.schemaVersion,'sourceFingerprint', ...
            C.sourceFingerprint.combinedSHA256, ...
        'baselineSourceFingerprint',C.baselineSourceFingerprint, ...
        'arm',Task.arm,'algorithm',Task.algorithm, ...
        'problem',Task.problem,'run',Task.run,'seed',Task.seed, ...
        'N',C.N,'D',C.D,'maxFE',C.maxFE, ...
        'finalFE',double(Problem.FE),'save',C.save,'metric',C.metric, ...
        'initialEpoch',C.initialEpoch,'retrainEpoch',C.retrainEpoch, ...
        'nCritic',C.nCritic,'gaShare',C.gaShare, ...
        'ordinaryDEShare',0.75-Task.share, ...
        'guideOffspringShare',Task.share, ...
        'quotaPerGeneration',round(Task.share*C.N), ...
        'guideGenerationCount',C.guideGenerationCount, ...
        'guideGenerationMode',string(Audit.generationMode), ...
        'guideUseMode',string(Audit.useMode), ...
        'pairTrainingEvents',double(Audit.pairTrainingEvents), ...
        'rawCandidates',double(Audit.rawCandidates), ...
        'quotaRequested',double(Audit.guidedRequested), ...
        'quotaSelected',double(Audit.guidedSelected), ...
        'quotaFallback',double(Audit.guidedFallback), ...
        'expectedQuotaRequested',expectedRequested, ...
        'startedAt',startedAt,'finishedAt',string(datetime('now')), ...
        'wallClockSeconds',double(wallClockSeconds), ...
        'algorithmRuntimeSeconds',double(Algorithm.metric.runtime));
    partial = char(Task.outputFile+".partial.mat");
    save(partial,'Record','FE','IGD','-v7.3');
    [ok,message] = movefile(partial,Task.outputFile,'f');
    if ~ok
        error('CBSPairGuide:QuotaSweepMoveFailed','%s',message);
    end
end

function validateRun(Task,C,Problem,FE,IGD,A)
    required = {'generationMode','useMode','nCritic','pairInitialEpoch', ...
        'pairRetrainEpoch','guideOffspringShare','pairTrainingEvents', ...
        'rawCandidates','guidedRequested','guidedSelected','guidedFallback'};
    requested = expectedQuota(Task,C);
    if ~all(isfield(A,required)) || Problem.FE ~= C.maxFE || ...
            ~isequal(reshape(FE,1,[]),C.expectedFE) || ...
            numel(IGD) ~= numel(C.expectedFE) || any(~isfinite(IGD)) || ...
            string(A.generationMode) ~= "pair_guide" || ...
            string(A.useMode) ~= "pair_guide" || ...
            double(A.nCritic) ~= C.nCritic || ...
            double(A.pairInitialEpoch) ~= C.initialEpoch || ...
            double(A.pairRetrainEpoch) ~= C.retrainEpoch || ...
            double(A.guideOffspringShare) ~= Task.share || ...
            double(A.guidedRequested) ~= requested || ...
            double(A.guidedSelected)+double(A.guidedFallback) ~= requested
        error('CBSPairGuide:BadQuotaSweepRun', ...
            'Run violated its FE, IGD, configuration, or quota contract.');
    end
end

function requested = expectedQuota(Task,C)
    requested = round(Task.share*C.N)*C.guideGenerationCount;
end

function complete = tasksComplete(Tasks,C)
    complete = false(size(Tasks));
    for i = 1 : numel(Tasks)
        complete(i) = resultComplete(Tasks(i),C);
    end
end

function complete = resultComplete(Task,C)
    complete = false;
    if ~isfile(Task.outputFile)
        return;
    end
    try
        Data = load(Task.outputFile,'Record','FE','IGD');
        R = Data.Record;
        requested = expectedQuota(Task,C);
        complete = string(R.schemaVersion) == C.schemaVersion && ...
            string(R.sourceFingerprint) == ...
                C.sourceFingerprint.combinedSHA256 && ...
            string(R.baselineSourceFingerprint) == ...
                C.baselineSourceFingerprint && ...
            string(R.arm) == Task.arm && ...
            string(R.algorithm) == Task.algorithm && ...
            string(R.problem) == Task.problem && R.run == Task.run && ...
            R.seed == Task.seed && R.N == C.N && R.D == C.D && ...
            R.maxFE == C.maxFE && R.finalFE == C.maxFE && ...
            R.save == C.save && string(R.metric) == C.metric && ...
            R.initialEpoch == C.initialEpoch && ...
            R.retrainEpoch == C.retrainEpoch && R.nCritic == C.nCritic && ...
            R.gaShare == C.gaShare && ...
            R.guideOffspringShare == Task.share && ...
            R.quotaPerGeneration == round(Task.share*C.N) && ...
            R.quotaRequested == requested && ...
            R.quotaSelected+R.quotaFallback == requested && ...
            string(R.guideGenerationMode) == "pair_guide" && ...
            string(R.guideUseMode) == "pair_guide" && ...
            isequal(reshape(double(Data.FE),1,[]),C.expectedFE) && ...
            numel(Data.IGD) == numel(C.expectedFE) && ...
            all(isfinite(double(Data.IGD(:))));
    catch
        complete = false;
    end
end

function Summary = summarizeResults(campaignDir,Tasks,C)
    totalRuns = numel(C.problems)*numel(C.runs)*(1+numel(C.shares));
    template = struct('problem',"",'run',0,'seed',0, ...
        'quotaPercent',0,'FE',0,'IGD',NaN);
    rows = repmat(template,totalRuns*numel(C.expectedFE),1);
    row = 0;
    for problem = C.problems
        for run = C.runs
            Data = load(baselineFile(C,problem,run),'IGD');
            [rows,row] = appendArmRows(rows,row,problem,run,20, ...
                C.expectedFE,Data.IGD);
        end
    end
    for i = 1 : numel(Tasks)
        Data = load(Tasks(i).outputFile,'IGD');
        [rows,row] = appendArmRows(rows,row,Tasks(i).problem, ...
            Tasks(i).run,Tasks(i).quotaPercent,C.expectedFE,Data.IGD);
    end
    if row ~= numel(rows)
        error('CBSPairGuide:BadQuotaSweepArmRowCount', ...
            'Combined trajectory row count is inconsistent.');
    end
    ArmTrajectory = struct2table(rows);
    PairedTrajectory = pairedTrajectory(ArmTrajectory,C);
    CheckpointComparison = groupedComparison(PairedTrajectory,C);
    OverallCheckpointComparison = overallComparison(PairedTrajectory,C);
    FinalComparison = CheckpointComparison( ...
        CheckpointComparison.FE == C.maxFE,:);

    writetable(ArmTrajectory, ...
        fullfile(campaignDir,'arm_igd_trajectory.csv'));
    writetable(PairedTrajectory, ...
        fullfile(campaignDir,'paired_igd_trajectory.csv'));
    writetable(CheckpointComparison, ...
        fullfile(campaignDir,'problem_checkpoint_comparison.csv'));
    writetable(OverallCheckpointComparison, ...
        fullfile(campaignDir,'overall_checkpoint_comparison.csv'));
    writetable(FinalComparison, ...
        fullfile(campaignDir,'problem_final_comparison.csv'));
    Summary = struct('schemaVersion',C.schemaVersion, ...
        'campaignDir',string(campaignDir), ...
        'sourceFingerprint',C.sourceFingerprint.combinedSHA256, ...
        'baselineSourceFingerprint',C.baselineSourceFingerprint, ...
        'deltaDefinition', ...
            "higher-quota IGD - quota20 IGD; negative favors higher quota", ...
        'ArmTrajectory',ArmTrajectory, ...
        'PairedTrajectory',PairedTrajectory, ...
        'CheckpointComparison',CheckpointComparison, ...
        'OverallCheckpointComparison',OverallCheckpointComparison, ...
        'FinalComparison',FinalComparison);
end

function [rows,row] = appendArmRows(rows,row,problem,run,quota,FE,IGD)
    for checkpoint = 1 : numel(FE)
        row = row+1;
        rows(row).problem = problem;
        rows(row).run = run;
        rows(row).seed = run;
        rows(row).quotaPercent = quota;
        rows(row).FE = FE(checkpoint);
        rows(row).IGD = double(IGD(checkpoint));
    end
end

function Table = pairedTrajectory(Arm,C)
    template = struct('problem',"",'run',0,'seed',0,'FE',0, ...
        'IGD20',NaN,'IGD30',NaN,'IGD40',NaN,'IGD50',NaN, ...
        'delta30Minus20',NaN,'delta40Minus20',NaN, ...
        'delta50Minus20',NaN);
    rows = repmat(template,numel(C.problems)*numel(C.runs)* ...
        numel(C.expectedFE),1);
    row = 0;
    for problem = C.problems
        for run = C.runs
            values = zeros(numel(C.expectedFE),4);
            quotas = [20 30 40 50];
            for q = 1 : numel(quotas)
                keep = Arm.problem == problem & Arm.run == run & ...
                    Arm.quotaPercent == quotas(q);
                Current = sortrows(Arm(keep,{'FE','IGD'}),'FE');
                if height(Current) ~= numel(C.expectedFE) || ...
                        ~isequal(reshape(Current.FE,1,[]),C.expectedFE)
                    error('CBSPairGuide:IncompleteQuotaPair', ...
                        'Each problem/run/quota needs ten checkpoints.');
                end
                values(:,q) = Current.IGD;
            end
            for checkpoint = 1 : numel(C.expectedFE)
                row = row+1;
                rows(row).problem = problem;
                rows(row).run = run;
                rows(row).seed = run;
                rows(row).FE = C.expectedFE(checkpoint);
                rows(row).IGD20 = values(checkpoint,1);
                rows(row).IGD30 = values(checkpoint,2);
                rows(row).IGD40 = values(checkpoint,3);
                rows(row).IGD50 = values(checkpoint,4);
                rows(row).delta30Minus20 = values(checkpoint,2)- ...
                    values(checkpoint,1);
                rows(row).delta40Minus20 = values(checkpoint,3)- ...
                    values(checkpoint,1);
                rows(row).delta50Minus20 = values(checkpoint,4)- ...
                    values(checkpoint,1);
            end
        end
    end
    Table = struct2table(rows);
end

function Table = groupedComparison(Paired,C)
    template = struct('problem',"",'FE',0,'pairedRuns',0, ...
        'quota20Mean',NaN,'quota20Std',NaN,'quota20Median',NaN, ...
        'quota30Mean',NaN,'quota30Std',NaN,'quota30Median',NaN, ...
        'quota40Mean',NaN,'quota40Std',NaN,'quota40Median',NaN, ...
        'quota50Mean',NaN,'quota50Std',NaN,'quota50Median',NaN, ...
        'bestMeanQuota',NaN, ...
        'meanDelta30Minus20',NaN,'quota30Wins',0, ...
        'quota20WinsVs30',0,'ties30',0,'signTestP30Vs20',NaN, ...
        'meanDelta40Minus20',NaN,'quota40Wins',0, ...
        'quota20WinsVs40',0,'ties40',0,'signTestP40Vs20',NaN, ...
        'meanDelta50Minus20',NaN,'quota50Wins',0, ...
        'quota20WinsVs50',0,'ties50',0,'signTestP50Vs20',NaN);
    rows = repmat(template,numel(C.problems)*numel(C.expectedFE),1);
    row = 0;
    for problem = C.problems
        for fe = C.expectedFE
            row = row+1;
            keep = Paired.problem == problem & Paired.FE == fe;
            V = [Paired.IGD20(keep),Paired.IGD30(keep), ...
                Paired.IGD40(keep),Paired.IGD50(keep)];
            if size(V,1) ~= numel(C.runs)
                error('CBSPairGuide:BadQuotaCheckpointPairCount', ...
                    'Every problem/checkpoint requires ten paired runs.');
            end
            rows(row).problem = problem;
            rows(row).FE = fe;
            rows(row).pairedRuns = size(V,1);
            quotas = [20 30 40 50];
            for q = 1 : numel(quotas)
                prefix = "quota"+quotas(q);
                rows(row).(char(prefix+"Mean")) = mean(V(:,q));
                rows(row).(char(prefix+"Std")) = std(V(:,q));
                rows(row).(char(prefix+"Median")) = median(V(:,q));
            end
            [~,best] = min(mean(V,1));
            rows(row).bestMeanQuota = quotas(best);
            for q = 2 : 4
                quota = quotas(q);
                delta = V(:,q)-V(:,1);
                rows(row).(char("meanDelta"+quota+"Minus20")) = ...
                    mean(delta);
                rows(row).(char("quota"+quota+"Wins")) = nnz(delta < 0);
                rows(row).(char("quota20WinsVs"+quota)) = nnz(delta > 0);
                rows(row).(char("ties"+quota)) = nnz(delta == 0);
                rows(row).(char("signTestP"+quota+"Vs20")) = ...
                    exactSignTest(delta);
            end
        end
    end
    Table = struct2table(rows);
end

function Table = overallComparison(Paired,C)
    template = struct('FE',0,'pairedObservations',0, ...
        'quota30Wins',0,'quota20WinsVs30',0, ...
        'meanRelativeDelta30Percent',NaN, ...
        'medianRelativeDelta30Percent',NaN, ...
        'quota40Wins',0,'quota20WinsVs40',0, ...
        'meanRelativeDelta40Percent',NaN, ...
        'medianRelativeDelta40Percent',NaN, ...
        'quota50Wins',0,'quota20WinsVs50',0, ...
        'meanRelativeDelta50Percent',NaN, ...
        'medianRelativeDelta50Percent',NaN);
    rows = repmat(template,numel(C.expectedFE),1);
    for i = 1 : numel(C.expectedFE)
        fe = C.expectedFE(i);
        keep = Paired.FE == fe;
        base = Paired.IGD20(keep);
        V = [Paired.IGD30(keep),Paired.IGD40(keep), ...
            Paired.IGD50(keep)];
        rows(i).FE = fe;
        rows(i).pairedObservations = numel(base);
        for q = 1 : 3
            quota = 20+10*q;
            delta = V(:,q)-base;
            relative = 100*delta./max(base,eps);
            rows(i).(char("quota"+quota+"Wins")) = nnz(delta < 0);
            rows(i).(char("quota20WinsVs"+quota)) = nnz(delta > 0);
            rows(i).(char("meanRelativeDelta"+quota+"Percent")) = ...
                mean(relative);
            rows(i).(char("medianRelativeDelta"+quota+"Percent")) = ...
                median(relative);
        end
    end
    Table = struct2table(rows);
end

function p = exactSignTest(delta)
    positive = nnz(delta > 0);
    negative = nnz(delta < 0);
    n = positive+negative;
    if n == 0
        p = 1;
        return;
    end
    k = min(positive,negative);
    tail = 0;
    for j = 0 : k
        tail = tail+nchoosek(n,j);
    end
    p = min(1,2*tail/(2^n));
end

function smokeTest(C)
    for i = 1 : numel(C.algorithms)
        constructor = str2func(char(C.algorithms(i)));
        Default = constructor('save',0,'outputFcn',@(varargin)[]);
        DefaultProblem = DASCMOP1_BC('N',2,'D',5,'maxFE',1);
        Default.Solve(DefaultProblem);
        A = Default.guideExperimentSnapshot();
        assert(A.generationMode == "pair_guide" && ...
            A.useMode == "pair_guide" && ...
            A.guideOffspringShare == C.shares(i) && ...
            A.pairInitialEpoch == C.initialEpoch && ...
            A.pairRetrainEpoch == C.retrainEpoch && ...
            A.nCritic == C.nCritic);

        rng(1,'twister');
        Probe = constructor('parameter',{20,6,0,64,5,32,1}, ...
            'save',0,'outputFcn',@(varargin)[]);
        ProbeProblem = DASCMOP1_BC('N',10,'D',5,'maxFE',40);
        Probe.Solve(ProbeProblem);
        P = Probe.guideExperimentSnapshot();
        expected = round(C.shares(i)*ProbeProblem.N);
        assert(P.guidedRequested == expected && ...
            P.guidedSelected+P.guidedFallback == expected);
    end
end

function [pool,ownsPool] = exactProcessPool(nWorker)
    pool = gcp('nocreate');
    ownsPool = isempty(pool);
    if ownsPool
        pool = parpool("Processes",nWorker);
    elseif pool.NumWorkers ~= nWorker || contains(class(pool),'ThreadPool')
        error('CBSPairGuide:BadQuotaSweepPool', ...
            'Experiment requires exactly %d process workers.',nWorker);
    end
end

function closeOwnedPool(pool,ownsPool)
    if ownsPool && ~isempty(pool) && isvalid(pool)
        delete(pool);
    end
end

function setSingleThreadLibraries()
    names = {'OMP_NUM_THREADS','OPENBLAS_NUM_THREADS', ...
        'MKL_NUM_THREADS','VECLIB_MAXIMUM_THREADS'};
    for i = 1 : numel(names)
        setenv(names{i},'1');
    end
end

function writeFailure(failureDir,Task,attempt,err)
    Failure = struct('problem',Task.problem,'run',Task.run, ...
        'seed',Task.seed,'arm',Task.arm,'algorithm',Task.algorithm, ...
        'share',Task.share,'attempt',attempt, ...
        'failedAt',string(datetime('now')), ...
        'identifier',string(err.identifier), ...
        'report',string(getReport(err,'extended','hyperlinks','off')));
    file = fullfile(failureDir,sprintf( ...
        '%s_quota%02d_run%02d_attempt%02d.mat',Task.problem, ...
        Task.quotaPercent,Task.run,attempt));
    save(file,'Failure','-v7.3');
end

function saveState(State,campaignDir)
    file = fullfile(campaignDir,'campaign_state.mat');
    partial = char(string(file)+".partial.mat");
    save(partial,'State','-v7.3');
    [ok,message] = movefile(partial,file,'f');
    if ~ok
        error('CBSPairGuide:QuotaSweepStateMoveFailed','%s',message);
    end
end

function writeRunningMarker(C,State,campaignDir)
    writelines(["status=running";"startedAt="+State.startedAt; ...
        "newTasks="+State.totalTasks;"baselineTasks=60"; ...
        "workers="+C.nWorker;"quotas=20,30,40,50"; ...
        "runs=1:10";"maxFE=100000";"save=10"; ...
        "sourceFingerprint="+C.sourceFingerprint.combinedSHA256; ...
        "baselineSourceFingerprint="+C.baselineSourceFingerprint], ...
        fullfile(campaignDir,'RUNNING.txt'));
end

function ensureFolder(folder)
    if ~isfolder(folder)
        mkdir(folder);
    end
end

function removeMarker(file)
    if isfile(file)
        delete(file);
    end
end

function Fingerprint = sourceFingerprint(rootPath)
    relativeFiles = [ ...
        "Algorithms/Multi-objective optimization/CBS-CGAN/Core/"+ ...
            "CBS_RegionWGAN_GP_Core.m"; ...
        "Algorithms/Multi-objective optimization/CBS-CGAN/Core/"+ ...
            "PairBoundaryWGAN_RC.m"; ...
        "Algorithms/Multi-objective optimization/CBS-CGAN/Core/"+ ...
            "PairBoundaryArchive_RC.m"; ...
        "Algorithms/Multi-objective optimization/CBS-CGAN-PairGuide/"+ ...
            "CBS_RegionWGAN_GP_PairGuide.m"; ...
        "Algorithms/Multi-objective optimization/CBS-CGAN-PairGuide/"+ ...
            "CBS_RegionWGAN_GP_PairGuide_Quota30.m"; ...
        "Algorithms/Multi-objective optimization/CBS-CGAN-PairGuide/"+ ...
            "CBS_RegionWGAN_GP_PairGuide_Quota40.m"; ...
        "Algorithms/Multi-objective optimization/CBS-CGAN-PairGuide/"+ ...
            "CBS_RegionWGAN_GP_PairGuide_Quota50.m"; ...
        "Algorithms/Multi-objective optimization/CBS-CGAN/Support/"+ ...
            "run_CBS_PairGuide_quota_sweep.m"; ...
        "Metrics/IGD.m"; ...
        "Problems/Multi-objective optimization/LIR-CMOP_BC/LIRCMOP5_BC.m"; ...
        "Problems/Multi-objective optimization/LIR-CMOP_BC/LIRCMOP7_BC.m"; ...
        "Problems/Multi-objective optimization/LIR-CMOP_BC/LIRCMOP8_BC.m"; ...
        "Problems/Multi-objective optimization/LIR-CMOP_BC/LIRCMOP10_BC.m"; ...
        "Problems/Multi-objective optimization/LIR-CMOP_BC/LIRCMOP12_BC.m"; ...
        "Problems/Multi-objective optimization/LIR-CMOP_BC/LIRCMOP14_BC.m"];
    Files = repmat(struct('relativePath',"",'sha256',""), ...
        numel(relativeFiles),1);
    canonical = "";
    for i = 1 : numel(relativeFiles)
        file = fullfile(rootPath,char(relativeFiles(i)));
        if ~isfile(file)
            error('CBSPairGuide:MissingQuotaSweepSource', ...
                'Cannot fingerprint missing source: %s',file);
        end
        digest = sha256File(file);
        Files(i).relativePath = relativeFiles(i);
        Files(i).sha256 = digest;
        canonical = canonical+relativeFiles(i)+"|"+digest+newline;
    end
    Fingerprint = struct('algorithm',"SHA-256",'files',Files, ...
        'combinedSHA256',sha256Bytes( ...
            unicode2native(char(canonical),'UTF-8')));
end

function assertSourceFingerprint(rootPath,expected)
    current = sourceFingerprint(rootPath);
    if ~isequaln(current,expected)
        error('CBSPairGuide:QuotaSweepSourceChanged', ...
            'Campaign source changed after the manifest was frozen.');
    end
end

function digest = sha256File(file)
    engine = java.security.MessageDigest.getInstance('SHA-256');
    fid = fopen(file,'rb');
    if fid < 0
        error('CBSPairGuide:QuotaSweepFingerprintReadFailed', ...
            'Cannot read source for hashing: %s',file);
    end
    cleanup = onCleanup(@()fclose(fid));
    while true
        bytes = fread(fid,1024*1024,'*uint8');
        if isempty(bytes)
            break;
        end
        engine.update(typecast(bytes(:),'int8'));
    end
    clear cleanup;
    digest = digestHex(engine.digest());
end

function digest = sha256Bytes(bytes)
    engine = java.security.MessageDigest.getInstance('SHA-256');
    engine.update(typecast(uint8(bytes(:)),'int8'));
    digest = digestHex(engine.digest());
end

function digest = digestHex(bytes)
    bytes = typecast(bytes,'uint8');
    digest = string(lower(reshape(dec2hex(bytes,2).',1,[])));
end
