function Analysis = analyze_CBS_PairGuide_epoch_ten_use_campaign( ...
        rootPath,campaignName)
%ANALYZE_CBS_PAIRGUIDE_EPOCH_TEN_USE_CAMPAIGN Score events and select runs.

    if nargin < 1 || isempty(rootPath)
        rootPath = fileparts(which('platemo'));
    end
    if nargin < 2 || isempty(campaignName)
        campaignName = "CBS_PairGuide_ten_use_epoch_v3_20260901";
    end
    campaignDir = fullfile(char(rootPath),'Data',char(campaignName));
    Manifest = load(fullfile(campaignDir,'campaign_manifest.mat'), ...
        'Protocol','Tasks');
    P = Manifest.Protocol;
    Tasks = Manifest.Tasks;
    Rows = repmat(emptyEventRow(),numel(Tasks)*P.captureUses,1);
    row = 0;
    for task = 1 : numel(Tasks)
        Data = load(Tasks(task).outputFile,'Record','Metrics');
        for event = 1 : P.captureUses
            row = row+1;
            M = Data.Metrics(event);
            Rows(row) = eventRow(Tasks(task),M, ...
                Data.Record.wallClockSeconds);
        end
    end
    EventMetrics = struct2table(Rows);
    EventMetrics.qualityScore = qualityScore(EventMetrics,P);
    RunMetrics = aggregateRuns(EventMetrics,P);
    BestRuns = selectBestRuns(RunMetrics,P);
    EventProgress = aggregateProgress(EventMetrics,P);
    OverallEpoch = aggregateEpochs(RunMetrics,P);

    bestQuality = max(OverallEpoch.qualityMeanMedian);
    bestFull = max(OverallEpoch.full20EventRateMedian);
    eligible = OverallEpoch.qualityMeanMedian >= bestQuality-0.03 & ...
        OverallEpoch.full20EventRateMedian >= bestFull-0.05;
    if ~any(eligible)
        eligible = OverallEpoch.qualityMeanMedian == bestQuality;
    end
    recommendedEpoch = min(OverallEpoch.epoch(eligible));
    [~,best] = max(OverallEpoch.qualityMeanMedian);
    bestQualityEpoch = OverallEpoch.epoch(best);

    analysisDir = fullfile(campaignDir,'analysis');
    ensureFolder(analysisDir);
    writetable(EventMetrics,fullfile(analysisDir,'event_metrics.csv'));
    writetable(RunMetrics,fullfile(analysisDir,'run_metrics.csv'));
    writetable(BestRuns,fullfile(analysisDir,'best_runs.csv'));
    writetable(EventProgress,fullfile(analysisDir,'event_progress.csv'));
    writetable(OverallEpoch,fullfile(analysisDir,'overall_epoch.csv'));
    Analysis = struct('schemaVersion',P.schemaVersion, ...
        'campaignName',string(campaignName), ...
        'taskCount',numel(Tasks),'eventCount',height(EventMetrics), ...
        'bestRunCount',height(BestRuns), ...
        'recommendedEpoch',recommendedEpoch, ...
        'bestQualityEpoch',bestQualityEpoch, ...
        'bestRunRule',"highest mean quality across the same ten events", ...
        'recommendationRule', ...
        "smallest epoch within 0.03 quality and 0.05 full-20 rate of best", ...
        'finishedAt',string(datetime('now')));
    save(fullfile(analysisDir,'epoch_analysis.mat'), ...
        'Analysis','EventMetrics','RunMetrics','BestRuns', ...
        'EventProgress','OverallEpoch');
    writelines([ ...
        "PairGuide ten-use epoch analysis"; ...
        "Recommended epoch: "+recommendedEpoch; ...
        "Best median-quality epoch: "+bestQualityEpoch; ...
        "Best-run rule: "+Analysis.bestRunRule; ...
        "Epoch rule: "+Analysis.recommendationRule], ...
        fullfile(analysisDir,'recommendation.txt'));
end

function R = emptyEventRow()
    R = struct('problem',"",'epoch',0,'run',0,'eventIndex',0, ...
        'poolFE',NaN,'useFE',NaN,'wallClockSeconds',NaN, ...
        'trainingPairs',NaN,'batchesPerEpoch',NaN,'updates',NaN, ...
        'pairVisits',NaN,'candidateValidCount',NaN, ...
        'candidateValidRate',NaN,'guidedCount',NaN, ...
        'guidedSelectionRate',NaN,'fallbackCount',NaN, ...
        'rawFeasibleRate',NaN,'rawInfeasibleRate',NaN, ...
        'rawBoundaryMarginMedian',NaN,'rawCVMedian',NaN, ...
        'rawDecisionUniqueRate',NaN,'guidedFeasibleRate',NaN, ...
        'guidedBoundaryMarginMedian',NaN,'guidedCVMedian',NaN, ...
        'guidedDominatingRate',NaN,'guidedUsefulRate',NaN, ...
        'guidedUsefulPerQuota',NaN, ...
        'qualityScore',NaN);
end

function R = eventRow(Task,M,wallClock)
    R = emptyEventRow();
    R.problem = Task.problem;
    R.epoch = Task.epoch;
    R.run = Task.run;
    R.wallClockSeconds = wallClock;
    fields = fieldnames(M);
    for i = 1 : numel(fields)
        if isfield(R,fields{i})
            R.(fields{i}) = M.(fields{i});
        end
    end
end

function score = qualityScore(T,P)
%QUALITYSCORE Preserve prior mechanism weights over all epochs per problem.

    score = nan(height(T),1);
    for problem = P.problems
        rows = T.problem == problem;
        rawBoundary = inverseMinMax(T.rawBoundaryMarginMedian(rows));
        guidedBoundary = inverseMinMax( ...
            T.guidedBoundaryMarginMedian(rows));
        rawInfeasible = finiteOrZero(T.rawInfeasibleRate(rows));
        guidedFeasible = finiteOrZero(T.guidedFeasibleRate(rows));
        guidedBoundary = finiteOrZero(guidedBoundary);
        rawBoundary = finiteOrZero(rawBoundary);
        score(rows) = 0.30*T.guidedSelectionRate(rows)+ ...
            0.20*rawInfeasible+0.20*rawBoundary+ ...
            0.15*guidedFeasible+0.15*guidedBoundary;
    end
end

function value = inverseMinMax(X)
    lo = prctile(X,2);
    hi = prctile(X,98);
    if ~isfinite(lo) || ~isfinite(hi)
        value = nan(size(X));
    elseif hi-lo <= eps(max(1,abs(hi)))
        value = ones(size(X));
    else
        value = 1-min(1,max(0,(X-lo)/(hi-lo)));
    end
end

function X = finiteOrZero(X)
    X(~isfinite(X)) = 0;
end

function T = aggregateRuns(E,P)
    template = runTemplate();
    Rows = repmat(template, ...
        numel(P.problems)*numel(P.epochs)*numel(P.runs),1);
    row = 0;
    for problem = P.problems
        for epoch = P.epochs
            for run = P.runs
                row = row+1;
                X = E(E.problem == problem & E.epoch == epoch & ...
                    E.run == run,:);
                Rows(row) = summarizeRun(X,problem,epoch,run);
            end
        end
    end
    T = struct2table(Rows);
end

function R = runTemplate()
    R = struct('problem',"",'epoch',0,'run',0,'eventCount',0, ...
        'firstUseFE',NaN,'tenthUseFE',NaN,'wallClockSeconds',NaN, ...
        'full20EventRate',NaN,'guidedCountMedian',NaN, ...
        'candidateValidRateMedian',NaN,'rawInfeasibleRateMedian',NaN, ...
        'rawBoundaryMarginMedian',NaN,'guidedFeasibleRateMedian',NaN, ...
        'guidedBoundaryMarginMedian',NaN,'guidedUsefulPerQuotaMean',NaN, ...
        'qualityMean',NaN,'qualityMinimum',NaN);
end

function R = summarizeRun(X,problem,epoch,run)
    R = runTemplate();
    R.problem = problem;
    R.epoch = epoch;
    R.run = run;
    R.eventCount = height(X);
    R.firstUseFE = X.useFE(1);
    R.tenthUseFE = X.useFE(end);
    R.wallClockSeconds = X.wallClockSeconds(1);
    R.full20EventRate = mean(X.guidedCount == 20);
    R.guidedCountMedian = median(X.guidedCount,'omitnan');
    R.candidateValidRateMedian = median(X.candidateValidRate,'omitnan');
    R.rawInfeasibleRateMedian = median(X.rawInfeasibleRate,'omitnan');
    R.rawBoundaryMarginMedian = ...
        median(X.rawBoundaryMarginMedian,'omitnan');
    R.guidedFeasibleRateMedian = median(X.guidedFeasibleRate,'omitnan');
    R.guidedBoundaryMarginMedian = ...
        median(X.guidedBoundaryMarginMedian,'omitnan');
    R.guidedUsefulPerQuotaMean = mean(X.guidedUsefulPerQuota,'omitnan');
    R.qualityMean = mean(X.qualityScore,'omitnan');
    R.qualityMinimum = min(X.qualityScore,[],'omitnan');
end

function Best = selectBestRuns(R,P)
    Rows = repmat(runTemplate(),numel(P.problems)*numel(P.epochs),1);
    row = 0;
    for problem = P.problems
        for epoch = P.epochs
            row = row+1;
            X = R(R.problem == problem & R.epoch == epoch,:);
            X = sortrows(X, ...
                {'qualityMean','full20EventRate','guidedUsefulPerQuotaMean', ...
                 'run'}, ...
                {'descend','descend','descend','ascend'});
            Rows(row) = table2struct(X(1,:));
        end
    end
    Best = struct2table(Rows);
end

function T = aggregateProgress(E,P)
    template = struct('epoch',0,'eventIndex',0,'observationCount',0, ...
        'useFEMedian',NaN,'full20Rate',NaN, ...
        'candidateValidRateMedian',NaN,'rawInfeasibleRateMedian',NaN, ...
        'guidedFeasibleRateMedian',NaN,'qualityScoreMedian',NaN);
    Rows = repmat(template,numel(P.epochs)*P.captureUses,1);
    row = 0;
    for epoch = P.epochs
        for event = 1 : P.captureUses
            row = row+1;
            X = E(E.epoch == epoch & E.eventIndex == event,:);
            Rows(row) = struct('epoch',epoch,'eventIndex',event, ...
                'observationCount',height(X), ...
                'useFEMedian',median(X.useFE,'omitnan'), ...
                'full20Rate',mean(X.guidedCount == 20), ...
                'candidateValidRateMedian', ...
                    median(X.candidateValidRate,'omitnan'), ...
                'rawInfeasibleRateMedian', ...
                    median(X.rawInfeasibleRate,'omitnan'), ...
                'guidedFeasibleRateMedian', ...
                    median(X.guidedFeasibleRate,'omitnan'), ...
                'qualityScoreMedian',median(X.qualityScore,'omitnan'));
        end
    end
    T = struct2table(Rows);
end

function T = aggregateEpochs(R,P)
    template = struct('epoch',0,'taskCount',0, ...
        'full20EventRateMedian',NaN,'candidateValidRateMedian',NaN, ...
        'rawInfeasibleRateMedian',NaN,'guidedFeasibleRateMedian',NaN, ...
        'guidedUsefulPerQuotaMeanMedian',NaN, ...
        'firstUseFEMedian',NaN,'tenthUseFEMedian',NaN, ...
        'wallClockMedian',NaN,'wallClockP90',NaN, ...
        'qualityMeanMedian',NaN,'qualityMeanIQR',NaN);
    Rows = repmat(template,numel(P.epochs),1);
    for i = 1 : numel(P.epochs)
        epoch = P.epochs(i);
        X = R(R.epoch == epoch,:);
        Rows(i) = struct('epoch',epoch,'taskCount',height(X), ...
            'full20EventRateMedian',median(X.full20EventRate,'omitnan'), ...
            'candidateValidRateMedian', ...
                median(X.candidateValidRateMedian,'omitnan'), ...
            'rawInfeasibleRateMedian', ...
                median(X.rawInfeasibleRateMedian,'omitnan'), ...
            'guidedFeasibleRateMedian', ...
                median(X.guidedFeasibleRateMedian,'omitnan'), ...
            'guidedUsefulPerQuotaMeanMedian', ...
                median(X.guidedUsefulPerQuotaMean,'omitnan'), ...
            'firstUseFEMedian',median(X.firstUseFE,'omitnan'), ...
            'tenthUseFEMedian',median(X.tenthUseFE,'omitnan'), ...
            'wallClockMedian',median(X.wallClockSeconds,'omitnan'), ...
            'wallClockP90',prctile(X.wallClockSeconds,90), ...
            'qualityMeanMedian',median(X.qualityMean,'omitnan'), ...
            'qualityMeanIQR',iqr(X.qualityMean));
    end
    T = struct2table(Rows);
end

function ensureFolder(folder)
    if ~isfolder(folder), mkdir(folder); end
end
