function Analysis = analyze_CBS_PairGuide_training_schedule_stage( ...
        rootPath,campaignName,stageName)
%ANALYZE_CBS_PAIRGUIDE_TRAINING_SCHEDULE_STAGE Analyze one paired stage.

    if nargin < 1 || isempty(rootPath)
        rootPath = fileparts(which('platemo'));
    end
    if nargin < 2 || isempty(campaignName)
        error('CBSPairGuide:MissingCampaignName', ...
            'campaignName is required.');
    end
    if nargin < 3 || isempty(stageName)
        error('CBSPairGuide:MissingStageName','stageName is required.');
    end
    rootPath = char(rootPath);
    campaignName = string(campaignName);
    stageName = string(stageName);
    stageDir = fullfile(rootPath,'Data',char(campaignName),char(stageName));
    manifestFile = fullfile(stageDir,'campaign_manifest.mat');
    if ~isfile(manifestFile)
        error('CBSPairGuide:MissingScheduleManifest', ...
            'Missing campaign manifest: %s',manifestFile);
    end
    Manifest = load(manifestFile,'Protocol','Tasks');
    if ~isfield(Manifest,'Protocol') || ~isfield(Manifest,'Tasks')
        error('CBSPairGuide:BadScheduleManifest', ...
            'Manifest must contain Protocol and Tasks.');
    end
    P = Manifest.Protocol;
    Tasks = Manifest.Tasks;
    [arms,problems,runs,factorName] = validateProtocol(P,stageName);
    validateTaskGrid(Tasks,arms,problems,runs);
    IGDPenalties = buildIGDPenalties(Tasks,problems,stageDir,rootPath);

    Rows = repmat(emptyTaskRow(),numel(Tasks),1);
    DiagnosticParts = cell(numel(Tasks),1);
    for i = 1 : numel(Tasks)
        Task = Tasks(i);
        resultFile = resolveResultFile(Task.outputFile,stageDir,rootPath);
        Data = load(resultFile,'Record','Trajectory','Snapshots','Audit');
        required = {'Record','Trajectory','Snapshots','Audit'};
        for field = required
            if ~isfield(Data,field{1})
                error('CBSPairGuide:IncompleteScheduleResult', ...
                    'Result lacks %s: %s',field{1},resultFile);
            end
        end
        validateRecordParameters(Data.Record,Task,resultFile);
        [FE,IGD,FeasibleCount] = trajectoryVectors( ...
            Data.Trajectory,resultFile);
        penaltyRow = IGDPenalties.problem == string(Task.problem);
        penalty = IGDPenalties.penalty(penaltyRow);
        rawIGD100K = valueAtFE(FE,IGD,1e5,resultFile,'IGD');
        nonfinite = ~isfinite(IGD);
        analyzedIGD = IGD;
        analyzedIGD(nonfinite) = penalty;
        gAUC = exp(trapz(FE,log(max(analyzedIGD,realmin))) / ...
            (FE(end)-FE(1)));
        IGD100K = valueAtFE(FE,analyzedIGD,1e5,resultFile,'IGD');
        feasible100K = valueAtFE(FE,FeasibleCount,1e5, ...
            resultFile,'FeasibleCount');

        Row = emptyTaskRow();
        Row.taskIndex = i;
        Row.stageName = stageName;
        Row.factorName = factorName;
        Row.armName = factorName+"="+compose('%g',Task.armValue);
        Row.armValue = double(Task.armValue);
        Row.problem = string(Task.problem);
        Row.run = double(Task.run);
        Row.seed = double(Task.seed);
        Row.initialEpoch = double(Task.initialEpoch);
        Row.retrainEpoch = double(Task.retrainEpoch);
        Row.nCritic = double(Task.nCritic);
        Row.resultStage = string(Task.resultStage);
        Row.reused = logical(Task.reused);
        Row.outputFile = string(resultFile);
        Row.sourceStageName = recordString(Data.Record,'stageName');
        Row.sourceArmName = recordString(Data.Record,'armName');
        Row.sourceArmValue = recordNumber(Data.Record,'armValue');
        Row.trajectoryPoints = numel(FE);
        Row.firstFE = FE(1);
        Row.lastFE = FE(end);
        Row.igdPenalty = penalty;
        Row.nonfiniteIGDCount = nnz(nonfinite);
        Row.gAUC = gAUC;
        Row.rawIGD100K = rawIGD100K;
        Row.IGD100K = IGD100K;
        Row.feasibleCount100K = feasible100K;
        Row.snapshotCount = numel(Data.Snapshots);
        Row.auditPresent = ~isempty(Data.Audit);
        Row.wallClockSeconds = recordNumber(Data.Record, ...
            'wallClockSeconds');
        [DiagnosticParts{i},TrainingSummary] = ...
            expandTrainingDiagnostics(Data.Audit,Task,Row,resultFile);
        Row.trainingEventCount = TrainingSummary.trainingEventCount;
        Row.retrainEventCount = TrainingSummary.retrainEventCount;
        Row.medianPostAllRelationRMSE = ...
            TrainingSummary.medianPostAllRelationRMSE;
        Row.medianPostChangedRelationRMSE = ...
            TrainingSummary.medianPostChangedRelationRMSE;
        Row.medianPostCriticGap = TrainingSummary.medianPostCriticGap;
        Row.medianPostGeneratedNearest = ...
            TrainingSummary.medianPostGeneratedNearest;
        Row.medianPostGeneratedSpread = ...
            TrainingSummary.medianPostGeneratedSpread;
        Rows(i) = Row;
    end
    TaskMetrics = struct2table(Rows);
    TrainingDiagnostics = struct2table(vertcat(DiagnosticParts{:}));
    [TaskMetrics,blockCount] = addBlockScores( ...
        TaskMetrics,arms,problems,runs);
    [numericalBestArm,numericalScores] = numericalBest( ...
        TaskMetrics,arms);
    TaskMetrics = addBestRatios(TaskMetrics,numericalBestArm);
    ProblemSummary = summarizeProblems(TaskMetrics,arms,problems);
    ArmSummary = summarizeArms(TaskMetrics,ProblemSummary,arms, ...
        numericalScores,numericalBestArm);
    DiagnosticSummary = summarizeTrainingDiagnostics( ...
        TrainingDiagnostics,arms);
    selectedArm = min(ArmSummary.armValue(ArmSummary.eligible));
    ArmSummary.selected = ArmSummary.armValue == selectedArm;

    analysisDir = fullfile(stageDir,'analysis');
    if ~isfolder(analysisDir), mkdir(analysisDir); end
    writetable(TaskMetrics,fullfile(analysisDir,'task_metrics.csv'));
    writetable(ArmSummary,fullfile(analysisDir,'arm_summary.csv'));
    writetable(ProblemSummary,fullfile(analysisDir, ...
        'problem_summary.csv'));
    writetable(TrainingDiagnostics,fullfile(analysisDir, ...
        'training_diagnostics.csv'));

    isRatioStage = strcmpi(factorName,"nCritic") || ...
        contains(lower(stageName),"ratio");
    RepresentativeRuns = table();
    representativeRule = "";
    if isRatioStage
        RepresentativeRuns = selectRepresentativeRuns( ...
            TaskMetrics,selectedArm,problems);
        writetable(RepresentativeRuns,fullfile(analysisDir, ...
            'representative_runs.csv'));
        save(fullfile(analysisDir,'representative_runs.mat'), ...
            'RepresentativeRuns');
        representativeRule = ...
            "second-lowest sqrt((gAUC/within-problem median gAUC)*"+ ...
            "(IGD100K/within-problem median IGD100K)) for selected arm";
    end

    Analysis = struct( ...
        'schemaVersion',P.schemaVersion, ...
        'campaignName',campaignName, ...
        'stageName',stageName, ...
        'factorName',factorName, ...
        'arms',arms(:)', ...
        'problems',problems(:)', ...
        'runs',runs(:)', ...
        'maxFE',double(P.maxFE), ...
        'taskCount',height(TaskMetrics), ...
        'blockCount',blockCount, ...
        'numericalBestArm',numericalBestArm, ...
        'recommendedArm',selectedArm, ...
        'selectedNCritic',NaN, ...
        'selectedRetrainEpoch',NaN, ...
        'overallMedianRatioLimit',1.05, ...
        'perProblemMedianRatioLimit',1.10, ...
        'igdPenaltyRule', ...
        "replace nonfinite IGD with 10 times that problem's maximum finite IGD", ...
        'problemIGDPenalties',IGDPenalties, ...
        'trainingEventCount',height(TrainingDiagnostics), ...
        'retrainEventCount',nnz(TrainingDiagnostics.kind == "retrain"), ...
        'trainingDiagnosticsAffectSelection',false, ...
        'trainingDiagnosticSummary',DiagnosticSummary, ...
        'trainingDiagnosticNote', ...
        "descriptive overfit/collapse evidence; arm gate remains gAUC and IGD100K only", ...
        'recommendationRule', ...
        "smallest arm passing both metric ratio gates", ...
        'representativeRule',representativeRule, ...
        'finishedAt',string(datetime('now')));
    if isRatioStage
        Analysis.selectedNCritic = selectedArm;
    elseif strcmpi(factorName,"retrainEpoch")
        Analysis.selectedRetrainEpoch = selectedArm;
    end
    save(fullfile(analysisDir,'stage_analysis.mat'), ...
        'Analysis','TaskMetrics','ArmSummary','ProblemSummary', ...
        'RepresentativeRuns','IGDPenalties','TrainingDiagnostics', ...
        'DiagnosticSummary');
    writeRecommendation(analysisDir,Analysis,ArmSummary);
end

function [arms,problems,runs,factorName] = validateProtocol(P,stageName)
    required = {'schemaVersion','stageName','armName','arms','problems', ...
        'runs','maxFE'};
    for field = required
        if ~isfield(P,field{1})
            error('CBSPairGuide:BadScheduleProtocol', ...
                'Protocol lacks %s.',field{1});
        end
    end
    if string(P.stageName) ~= stageName
        error('CBSPairGuide:ScheduleStageMismatch', ...
            'Requested stage %s, manifest contains %s.', ...
            stageName,string(P.stageName));
    end
    arms = double(P.arms(:));
    problems = string(P.problems(:));
    runs = double(P.runs(:));
    factorName = string(P.armName);
    if isempty(arms) || any(~isfinite(arms)) || numel(unique(arms)) ~= numel(arms)
        error('CBSPairGuide:BadScheduleArms', ...
            'Protocol.arms must be unique finite numeric values.');
    end
    if isempty(problems) || any(strlength(problems) == 0) || ...
            numel(unique(problems)) ~= numel(problems)
        error('CBSPairGuide:BadScheduleProblems', ...
            'Protocol.problems must be unique nonempty names.');
    end
    if isempty(runs) || any(~isfinite(runs)) || ...
            numel(unique(runs)) ~= numel(runs)
        error('CBSPairGuide:BadScheduleRuns', ...
            'Protocol.runs must be unique finite values.');
    end
    if numel(problems)*numel(runs) ~= 30
        error('CBSPairGuide:BadScheduleBlockCount', ...
            'Schedule decision requires six problems by five runs (30 blocks).');
    end
    if ~isscalar(P.maxFE) || P.maxFE < 1e5
        error('CBSPairGuide:InsufficientScheduleFE', ...
            'Protocol.maxFE must reach 100000.');
    end
end

function validateTaskGrid(Tasks,arms,problems,runs)
    required = {'problem','armValue','run','seed','initialEpoch', ...
        'retrainEpoch','nCritic','outputFile','resultStage','reused'};
    for field = required
        if ~isfield(Tasks,field{1})
            error('CBSPairGuide:BadScheduleTasks', ...
                'Tasks lack %s.',field{1});
        end
    end
    expected = numel(arms)*numel(problems)*numel(runs);
    if numel(Tasks) ~= expected
        error('CBSPairGuide:IncompleteScheduleGrid', ...
            'Expected %d paired tasks, found %d.',expected,numel(Tasks));
    end
    taskProblems = string({Tasks.problem})';
    taskArms = double([Tasks.armValue])';
    taskRuns = double([Tasks.run])';
    for problem = problems'
        for run = runs'
            for arm = arms'
                count = nnz(taskProblems == problem & taskRuns == run & ...
                    taskArms == arm);
                if count ~= 1
                    error('CBSPairGuide:UnpairedScheduleGrid', ...
                        'Expected one task for problem=%s, run=%g, arm=%g; found %d.', ...
                        problem,run,arm,count);
                end
            end
        end
    end
end

function Row = emptyTaskRow()
    Row = struct( ...
        'taskIndex',0,'stageName',"",'factorName',"",'armName',"", ...
        'armValue',NaN,'problem',"",'run',NaN,'seed',NaN, ...
        'initialEpoch',NaN,'retrainEpoch',NaN,'nCritic',NaN, ...
        'resultStage',"",'reused',false,'outputFile',"", ...
        'sourceStageName',"",'sourceArmName',"", ...
        'sourceArmValue',NaN,'trajectoryPoints',0,'firstFE',NaN, ...
        'lastFE',NaN,'igdPenalty',NaN,'nonfiniteIGDCount',0, ...
        'gAUC',NaN,'rawIGD100K',NaN,'IGD100K',NaN, ...
        'feasibleCount100K',NaN,'snapshotCount',0, ...
        'auditPresent',false,'wallClockSeconds',NaN, ...
        'trainingEventCount',0,'retrainEventCount',0, ...
        'medianPostAllRelationRMSE',NaN, ...
        'medianPostChangedRelationRMSE',NaN, ...
        'medianPostCriticGap',NaN, ...
        'medianPostGeneratedNearest',NaN, ...
        'medianPostGeneratedSpread',NaN);
end

function resultFile = resolveResultFile(outputFile,stageDir,rootPath)
    outputFile = char(outputFile);
    candidates = {outputFile,fullfile(stageDir,outputFile), ...
        fullfile(rootPath,outputFile)};
    resultFile = '';
    for i = 1 : numel(candidates)
        if isfile(candidates{i})
            resultFile = candidates{i};
            break;
        end
    end
    if isempty(resultFile)
        error('CBSPairGuide:MissingScheduleResult', ...
            'Missing result file: %s',outputFile);
    end
end

function validateRecordParameters(Record,Task,resultFile)
    if ~isstruct(Record) || ~isscalar(Record)
        error('CBSPairGuide:BadScheduleRecord', ...
            'Record must be a scalar struct: %s',resultFile);
    end
    fields = {'initialEpoch','retrainEpoch','nCritic'};
    for field = fields
        name = field{1};
        if ~isfield(Record,name) || ~isnumeric(Record.(name)) || ...
                ~isscalar(Record.(name)) || ...
                double(Record.(name)) ~= double(Task.(name))
            error('CBSPairGuide:ScheduleParameterMismatch', ...
                'Record.%s does not match task: %s',name,resultFile);
        end
    end
    if isfield(Record,'stageName') && ...
            string(Record.stageName) ~= string(Task.resultStage)
        error('CBSPairGuide:ScheduleResultStageMismatch', ...
            'Record.stageName does not match task.resultStage: %s', ...
            resultFile);
    end
end

function [FE,IGD,FeasibleCount] = trajectoryVectors(T,resultFile)
    required = {'FE','IGD','FeasibleCount'};
    if istable(T)
        names = T.Properties.VariableNames;
        for field = required
            if ~ismember(field{1},names)
                error('CBSPairGuide:BadScheduleTrajectory', ...
                    'Trajectory lacks %s: %s',field{1},resultFile);
            end
        end
        FE = double(T.FE(:));
        IGD = double(T.IGD(:));
        FeasibleCount = double(T.FeasibleCount(:));
    elseif isstruct(T) && all(isfield(T,required))
        if isscalar(T)
            FE = double(T.FE(:));
            IGD = double(T.IGD(:));
            FeasibleCount = double(T.FeasibleCount(:));
        else
            FE = double(reshape([T.FE],[],1));
            IGD = double(reshape([T.IGD],[],1));
            FeasibleCount = double(reshape([T.FeasibleCount],[],1));
        end
    else
        error('CBSPairGuide:BadScheduleTrajectory', ...
            'Trajectory must expose FE, IGD, and FeasibleCount: %s', ...
            resultFile);
    end
    if numel(FE) < 2 || numel(IGD) ~= numel(FE) || ...
            numel(FeasibleCount) ~= numel(FE) || ...
            any(~isfinite(FE)) || any(IGD(isfinite(IGD)) < 0) || ...
            any(~isfinite(FeasibleCount))
        error('CBSPairGuide:InvalidScheduleTrajectory', ...
            'Trajectory values are incomplete or invalid: %s',resultFile);
    end
    [FE,order] = sort(FE);
    IGD = IGD(order);
    FeasibleCount = FeasibleCount(order);
    if any(diff(FE) <= 0)
        error('CBSPairGuide:NonIncreasingScheduleFE', ...
            'Trajectory FE values must be unique and increasing: %s', ...
            resultFile);
    end
end

function S = buildIGDPenalties(Tasks,problems,stageDir,rootPath)
    template = struct('problem',"",'finiteValueCount',0, ...
        'nonfiniteValueCount',0,'maximumFiniteIGD',NaN,'penalty',NaN);
    Rows = repmat(template,numel(problems),1);
    taskProblems = string({Tasks.problem})';
    for i = 1 : numel(problems)
        maximum = -Inf;
        finiteCount = 0;
        nonfiniteCount = 0;
        taskRows = find(taskProblems == problems(i));
        for j = taskRows'
            resultFile = resolveResultFile( ...
                Tasks(j).outputFile,stageDir,rootPath);
            Data = load(resultFile,'Trajectory');
            if ~isfield(Data,'Trajectory')
                error('CBSPairGuide:IncompleteScheduleResult', ...
                    'Result lacks Trajectory: %s',resultFile);
            end
            [~,IGD,~] = trajectoryVectors(Data.Trajectory,resultFile);
            finite = IGD(isfinite(IGD));
            finiteCount = finiteCount+numel(finite);
            nonfiniteCount = nonfiniteCount+nnz(~isfinite(IGD));
            if ~isempty(finite)
                maximum = max(maximum,max(finite));
            end
        end
        if finiteCount == 0
            error('CBSPairGuide:NoFiniteScheduleIGD', ...
                'Problem %s has no finite IGD in any arm, run, or FE.', ...
                problems(i));
        end
        penalty = 10*max(maximum,realmin);
        Rows(i) = struct('problem',problems(i), ...
            'finiteValueCount',finiteCount, ...
            'nonfiniteValueCount',nonfiniteCount, ...
            'maximumFiniteIGD',maximum,'penalty',penalty);
    end
    S = struct2table(Rows);
end

function value = valueAtFE(FE,Y,targetFE,resultFile,name)
    tolerance = 16*eps(max(targetFE,FE(end)));
    if FE(1) > targetFE+tolerance || FE(end) < targetFE-tolerance
        error('CBSPairGuide:ScheduleTrajectoryTooShort', ...
            'Trajectory does not cover FE=%g for %s: %s', ...
            targetFE,name,resultFile);
    end
    exact = find(abs(FE-targetFE) <= tolerance,1,'last');
    if isempty(exact)
        value = interp1(FE,Y,targetFE,'linear');
    else
        value = Y(exact);
    end
end

function value = recordString(Record,name)
    if isfield(Record,name)
        value = string(Record.(name));
    else
        value = "";
    end
end

function value = recordNumber(Record,name)
    if isfield(Record,name) && isnumeric(Record.(name)) && ...
            isscalar(Record.(name))
        value = double(Record.(name));
    else
        value = NaN;
    end
end

function [Rows,Summary] = expandTrainingDiagnostics( ...
        Audit,Task,Identity,resultFile)
    requiredAudit = {'pairTrainingLog','pairInitialEpoch', ...
        'pairRetrainEpoch','nCritic'};
    if ~isstruct(Audit) || ~isscalar(Audit) || ...
            ~all(isfield(Audit,requiredAudit))
        error('CBSPairGuide:BadTrainingDiagnosticsAudit', ...
            'Audit lacks the pair training schedule/log: %s',resultFile);
    end
    if double(Audit.pairInitialEpoch) ~= double(Task.initialEpoch) || ...
            double(Audit.pairRetrainEpoch) ~= double(Task.retrainEpoch) || ...
            double(Audit.nCritic) ~= double(Task.nCritic)
        error('CBSPairGuide:TrainingDiagnosticsScheduleMismatch', ...
            'Audit training schedule does not match task: %s',resultFile);
    end
    Log = Audit.pairTrainingLog(:);
    if isempty(Log) || ~isstruct(Log)
        error('CBSPairGuide:MissingTrainingDiagnostics', ...
            'Audit.pairTrainingLog is empty: %s',resultFile);
    end
    requiredEvent = {'fe','kind','nCritic','epochs','trainingPairs', ...
        'changedPairs','newRegions','updates','pairVisits', ...
        'batchesPerEpoch','preAllRelationRMSE', ...
        'preChangedRelationRMSE','preCriticGap', ...
        'preGeneratedNearestMedian','preGeneratedSpread', ...
        'postAllRelationRMSE','postChangedRelationRMSE', ...
        'postCriticGap','postGeneratedNearestMedian', ...
        'postGeneratedSpread'};
    if ~all(isfield(Log,requiredEvent))
        error('CBSPairGuide:IncompleteTrainingDiagnostics', ...
            'Training log fields are incomplete: %s',resultFile);
    end
    if isfield(Audit,'pairTrainingEvents') && ...
            double(Audit.pairTrainingEvents) ~= numel(Log)
        error('CBSPairGuide:TrainingDiagnosticsCountMismatch', ...
            'Audit training-event count does not match its log: %s', ...
            resultFile);
    end
    Rows = repmat(emptyDiagnosticRow(),numel(Log),1);
    eventFE = nan(numel(Log),1);
    for i = 1 : numel(Log)
        Event = Log(i);
        kind = string(Event.kind);
        expectedKind = "retrain";
        expectedEpochs = double(Task.retrainEpoch);
        if i == 1
            expectedKind = "initial";
            expectedEpochs = double(Task.initialEpoch);
        end
        if ~isscalar(kind) || kind ~= expectedKind || ...
                ~numericScalarEquals(Event.epochs,expectedEpochs) || ...
                ~numericScalarEquals(Event.nCritic,double(Task.nCritic))
            error('CBSPairGuide:TrainingDiagnosticsEventMismatch', ...
                'Event %d must be %s with epochs=%g and nCritic=%g: %s', ...
                i,expectedKind,expectedEpochs,Task.nCritic,resultFile);
        end
        numericFields = {'fe','nCritic','epochs','trainingPairs', ...
            'changedPairs','newRegions','updates','pairVisits', ...
            'batchesPerEpoch'};
        for field = numericFields
            value = Event.(field{1});
            if ~isnumeric(value) || ~isscalar(value) || ...
                    ~isfinite(double(value)) || double(value) < 0
                error('CBSPairGuide:InvalidTrainingDiagnosticValue', ...
                    'Event %d has invalid %s: %s', ...
                    i,field{1},resultFile);
            end
        end
        diagnosticFields = requiredEvent(11:end);
        for field = diagnosticFields
            value = Event.(field{1});
            if ~isnumeric(value) || ~isscalar(value)
                error('CBSPairGuide:InvalidTrainingDiagnosticValue', ...
                    'Event %d has invalid %s: %s', ...
                    i,field{1},resultFile);
            end
        end
        eventFE(i) = double(Event.fe);
        Row = emptyDiagnosticRow();
        Row.taskIndex = Identity.taskIndex;
        Row.stageName = Identity.stageName;
        Row.factorName = Identity.factorName;
        Row.armName = Identity.armName;
        Row.armValue = Identity.armValue;
        Row.problem = Identity.problem;
        Row.run = Identity.run;
        Row.seed = Identity.seed;
        Row.resultStage = Identity.resultStage;
        Row.reused = Identity.reused;
        Row.outputFile = Identity.outputFile;
        Row.eventIndex = i;
        Row.FE = double(Event.fe);
        Row.kind = kind;
        Row.nCritic = double(Event.nCritic);
        Row.epochs = double(Event.epochs);
        Row.trainingPairs = double(Event.trainingPairs);
        Row.changedPairs = double(Event.changedPairs);
        Row.newRegions = double(Event.newRegions);
        Row.updates = double(Event.updates);
        Row.pairVisits = double(Event.pairVisits);
        Row.batchesPerEpoch = double(Event.batchesPerEpoch);
        names = ["AllRelationRMSE","ChangedRelationRMSE", ...
            "CriticGap","GeneratedNearestMedian","GeneratedSpread"];
        for name = names
            preName = char("pre"+name);
            postName = char("post"+name);
            deltaName = char("delta"+name);
            Row.(preName) = double(Event.(preName));
            Row.(postName) = double(Event.(postName));
            Row.(deltaName) = Row.(postName)-Row.(preName);
        end
        Rows(i) = Row;
    end
    if any(diff(eventFE) <= 0)
        error('CBSPairGuide:NonIncreasingTrainingDiagnosticFE', ...
            'Training-event FE must be strictly increasing: %s',resultFile);
    end
    Summary = struct( ...
        'trainingEventCount',numel(Log), ...
        'retrainEventCount',numel(Log)-1, ...
        'medianPostAllRelationRMSE', ...
            finiteMedian([Rows.postAllRelationRMSE]), ...
        'medianPostChangedRelationRMSE', ...
            finiteMedian([Rows.postChangedRelationRMSE]), ...
        'medianPostCriticGap',finiteMedian([Rows.postCriticGap]), ...
        'medianPostGeneratedNearest', ...
            finiteMedian([Rows.postGeneratedNearestMedian]), ...
        'medianPostGeneratedSpread', ...
            finiteMedian([Rows.postGeneratedSpread]));
end

function Row = emptyDiagnosticRow()
    Row = struct( ...
        'taskIndex',0,'stageName',"",'factorName',"",'armName',"", ...
        'armValue',NaN,'problem',"",'run',NaN,'seed',NaN, ...
        'resultStage',"",'reused',false,'outputFile',"", ...
        'eventIndex',0,'FE',NaN,'kind',"",'nCritic',NaN, ...
        'epochs',NaN,'trainingPairs',NaN,'changedPairs',NaN, ...
        'newRegions',NaN,'updates',NaN,'pairVisits',NaN, ...
        'batchesPerEpoch',NaN, ...
        'preAllRelationRMSE',NaN,'postAllRelationRMSE',NaN, ...
        'deltaAllRelationRMSE',NaN, ...
        'preChangedRelationRMSE',NaN,'postChangedRelationRMSE',NaN, ...
        'deltaChangedRelationRMSE',NaN, ...
        'preCriticGap',NaN,'postCriticGap',NaN,'deltaCriticGap',NaN, ...
        'preGeneratedNearestMedian',NaN, ...
        'postGeneratedNearestMedian',NaN, ...
        'deltaGeneratedNearestMedian',NaN, ...
        'preGeneratedSpread',NaN,'postGeneratedSpread',NaN, ...
        'deltaGeneratedSpread',NaN);
end

function tf = numericScalarEquals(value,expected)
    tf = isnumeric(value) && isscalar(value) && ...
        isfinite(double(value)) && double(value) == expected;
end

function value = finiteMedian(X)
    X = double(X(isfinite(X)));
    if isempty(X)
        value = NaN;
    else
        value = median(X);
    end
end

function [T,blockCount] = addBlockScores(T,arms,problems,runs)
    T.blockIndex = zeros(height(T),1);
    T.blockCombinedScore = nan(height(T),1);
    block = 0;
    for problem = problems'
        for run = runs'
            block = block+1;
            rows = find(T.problem == problem & T.run == run);
            if numel(rows) ~= numel(arms)
                error('CBSPairGuide:UnpairedScheduleMetrics', ...
                    'Incomplete metric block for %s run %g.',problem,run);
            end
            minGAUC = min(T.gAUC(rows));
            minEndpoint = min(T.IGD100K(rows));
            T.blockIndex(rows) = block;
            T.blockCombinedScore(rows) = sqrt( ...
                safeRatio(T.gAUC(rows),minGAUC) .* ...
                safeRatio(T.IGD100K(rows),minEndpoint));
        end
    end
    blockCount = block;
end

function [bestArm,scores] = numericalBest(T,arms)
    scores = nan(numel(arms),1);
    for i = 1 : numel(arms)
        scores(i) = median(T.blockCombinedScore(T.armValue == arms(i)));
    end
    order = sortrows([scores,arms],[1 2]);
    bestArm = order(1,2);
end

function T = addBestRatios(T,bestArm)
    T.gAUCRatioToBest = nan(height(T),1);
    T.IGD100KRatioToBest = nan(height(T),1);
    for block = unique(T.blockIndex)'
        rows = find(T.blockIndex == block);
        reference = rows(T.armValue(rows) == bestArm);
        if numel(reference) ~= 1
            error('CBSPairGuide:MissingNumericalBestPair', ...
                'Numerical-best arm missing from block %d.',block);
        end
        T.gAUCRatioToBest(rows) = safeRatio( ...
            T.gAUC(rows),T.gAUC(reference));
        T.IGD100KRatioToBest(rows) = safeRatio( ...
            T.IGD100K(rows),T.IGD100K(reference));
    end
end

function ratio = safeRatio(value,reference)
    denominator = max(reference,realmin);
    ratio = value./denominator;
    ratio(value == 0 & reference == 0) = 1;
end

function S = summarizeProblems(T,arms,problems)
    template = struct('stageName',"",'factorName',"",'armName',"", ...
        'armValue',NaN,'problem',"",'runCount',0,'igdPenalty',NaN, ...
        'gAUCMedian',NaN,'IGD100KMedian',NaN, ...
        'blockCombinedScoreMedian',NaN, ...
        'gAUCRatioToBestMedian',NaN, ...
        'IGD100KRatioToBestMedian',NaN,'withinTenPercent',false);
    Rows = repmat(template,numel(arms)*numel(problems),1);
    row = 0;
    for i = 1 : numel(arms)
        for problem = problems'
            row = row+1;
            X = T(T.armValue == arms(i) & T.problem == problem,:);
            Rows(row) = struct( ...
                'stageName',X.stageName(1), ...
                'factorName',X.factorName(1), ...
                'armName',X.armName(1), ...
                'armValue',arms(i), ...
                'problem',problem, ...
                'runCount',height(X), ...
                'igdPenalty',X.igdPenalty(1), ...
                'gAUCMedian',median(X.gAUC), ...
                'IGD100KMedian',median(X.IGD100K), ...
                'blockCombinedScoreMedian', ...
                    median(X.blockCombinedScore), ...
                'gAUCRatioToBestMedian', ...
                    median(X.gAUCRatioToBest), ...
                'IGD100KRatioToBestMedian', ...
                    median(X.IGD100KRatioToBest), ...
                'withinTenPercent', ...
                    median(X.gAUCRatioToBest) <= 1.10 && ...
                    median(X.IGD100KRatioToBest) <= 1.10);
        end
    end
    S = struct2table(Rows);
end

function S = summarizeArms(T,ProblemSummary,arms,numericalScores,bestArm)
    template = struct('stageName',"",'factorName',"",'armName',"", ...
        'armValue',NaN,'blockCount',0,'gAUCMedian',NaN, ...
        'IGD100KMedian',NaN,'numericalScore',NaN, ...
        'gAUCRatioToBestMedian',NaN,'gAUCRatioCILow',NaN, ...
        'gAUCRatioCIHigh',NaN,'IGD100KRatioToBestMedian',NaN, ...
        'IGD100KRatioCILow',NaN,'IGD100KRatioCIHigh',NaN, ...
        'overallWithinFivePercent',false, ...
        'allProblemsWithinTenPercent',false,'signrankP',NaN, ...
        'holmP',NaN,'eligible',false,'selected',false);
    Rows = repmat(template,numel(arms),1);
    for i = 1 : numel(arms)
        X = T(T.armValue == arms(i),:);
        PX = ProblemSummary(ProblemSummary.armValue == arms(i),:);
        gRatio = median(X.gAUCRatioToBest);
        endpointRatio = median(X.IGD100KRatioToBest);
        [gLow,gHigh] = bootstrapMedianCI(X.gAUCRatioToBest, ...
            20260901+2*i);
        [eLow,eHigh] = bootstrapMedianCI(X.IGD100KRatioToBest, ...
            20260902+2*i);
        overallGate = gRatio <= 1.05 && endpointRatio <= 1.05;
        problemGate = all(PX.withinTenPercent);
        Rows(i) = struct( ...
            'stageName',X.stageName(1), ...
            'factorName',X.factorName(1), ...
            'armName',X.armName(1), ...
            'armValue',arms(i), ...
            'blockCount',height(X), ...
            'gAUCMedian',median(X.gAUC), ...
            'IGD100KMedian',median(X.IGD100K), ...
            'numericalScore',numericalScores(i), ...
            'gAUCRatioToBestMedian',gRatio, ...
            'gAUCRatioCILow',gLow, ...
            'gAUCRatioCIHigh',gHigh, ...
            'IGD100KRatioToBestMedian',endpointRatio, ...
            'IGD100KRatioCILow',eLow, ...
            'IGD100KRatioCIHigh',eHigh, ...
            'overallWithinFivePercent',overallGate, ...
            'allProblemsWithinTenPercent',problemGate, ...
            'signrankP',pairedSignrank(T,arms(i),bestArm), ...
            'holmP',NaN, ...
            'eligible',overallGate && problemGate, ...
            'selected',false);
    end
    S = struct2table(Rows);
    S.holmP = holmAdjust(S.signrankP,S.armValue ~= bestArm);
end

function S = summarizeTrainingDiagnostics(T,arms)
    template = struct('stageName',"",'factorName',"",'armName',"", ...
        'armValue',NaN,'taskCount',0,'trainingEventCount',0, ...
        'retrainEventCount',0,'postAllRelationRMSEMedian',NaN, ...
        'deltaAllRelationRMSEMedian',NaN, ...
        'postChangedRelationRMSEMedian',NaN, ...
        'deltaChangedRelationRMSEMedian',NaN, ...
        'postCriticGapMedian',NaN,'deltaCriticGapMedian',NaN, ...
        'postGeneratedNearestMedian',NaN, ...
        'deltaGeneratedNearestMedian',NaN, ...
        'postGeneratedSpreadMedian',NaN, ...
        'deltaGeneratedSpreadMedian',NaN);
    Rows = repmat(template,numel(arms),1);
    for i = 1 : numel(arms)
        X = T(T.armValue == arms(i),:);
        Rows(i) = struct( ...
            'stageName',X.stageName(1), ...
            'factorName',X.factorName(1), ...
            'armName',X.armName(1), ...
            'armValue',arms(i), ...
            'taskCount',numel(unique(X.taskIndex)), ...
            'trainingEventCount',height(X), ...
            'retrainEventCount',nnz(X.kind == "retrain"), ...
            'postAllRelationRMSEMedian', ...
                finiteMedian(X.postAllRelationRMSE), ...
            'deltaAllRelationRMSEMedian', ...
                finiteMedian(X.deltaAllRelationRMSE), ...
            'postChangedRelationRMSEMedian', ...
                finiteMedian(X.postChangedRelationRMSE), ...
            'deltaChangedRelationRMSEMedian', ...
                finiteMedian(X.deltaChangedRelationRMSE), ...
            'postCriticGapMedian',finiteMedian(X.postCriticGap), ...
            'deltaCriticGapMedian',finiteMedian(X.deltaCriticGap), ...
            'postGeneratedNearestMedian', ...
                finiteMedian(X.postGeneratedNearestMedian), ...
            'deltaGeneratedNearestMedian', ...
                finiteMedian(X.deltaGeneratedNearestMedian), ...
            'postGeneratedSpreadMedian', ...
                finiteMedian(X.postGeneratedSpread), ...
            'deltaGeneratedSpreadMedian', ...
                finiteMedian(X.deltaGeneratedSpread));
    end
    S = struct2table(Rows);
end

function [low,high] = bootstrapMedianCI(X,seed)
    X = X(isfinite(X));
    if isempty(X)
        low = NaN;
        high = NaN;
        return;
    end
    stream = RandStream('mt19937ar','Seed',seed);
    indices = randi(stream,numel(X),numel(X),2000);
    estimates = sort(median(X(indices),1));
    low = percentile(estimates,0.025);
    high = percentile(estimates,0.975);
end

function value = percentile(sortedValues,p)
    position = 1+(numel(sortedValues)-1)*p;
    lower = floor(position);
    upper = ceil(position);
    if lower == upper
        value = sortedValues(lower);
    else
        weight = position-lower;
        value = sortedValues(lower)*(1-weight)+sortedValues(upper)*weight;
    end
end

function p = pairedSignrank(T,arm,bestArm)
    p = NaN;
    if arm == bestArm || exist('signrank','file') == 0
        return;
    end
    A = sortrows(T(T.armValue == arm,:), 'blockIndex');
    B = sortrows(T(T.armValue == bestArm,:), 'blockIndex');
    if height(A) ~= height(B) || any(A.blockIndex ~= B.blockIndex)
        return;
    end
    scoreA = 0.5*(log(max(A.gAUC,realmin))+ ...
        log(max(A.IGD100K,realmin)));
    scoreB = 0.5*(log(max(B.gAUC,realmin))+ ...
        log(max(B.IGD100K,realmin)));
    try
        p = signrank(scoreA,scoreB);
    catch
        p = NaN;
    end
end

function adjusted = holmAdjust(p,include)
    adjusted = nan(size(p));
    indices = find(include & isfinite(p));
    if isempty(indices), return; end
    [ordered,order] = sort(p(indices));
    count = numel(ordered);
    values = min(1,(count-(1:count)'+1).*ordered);
    values = cummax(values);
    adjusted(indices(order)) = values;
end

function R = selectRepresentativeRuns(T,selectedArm,problems)
    template = struct('stageName',"",'factorName',"",'armName',"", ...
        'armValue',NaN,'problem',"",'run',NaN, ...
        'rankWithinProblem',2,'representativeScore',NaN, ...
        'gAUC',NaN,'IGD100K',NaN,'seed',NaN,'outputFile',"", ...
        'snapshotCount',0);
    Rows = repmat(template,numel(problems),1);
    for i = 1 : numel(problems)
        X = T(T.armValue == selectedArm & T.problem == problems(i),:);
        if height(X) < 2
            error('CBSPairGuide:InsufficientRepresentativeRuns', ...
                'Need at least two runs for %s.',problems(i));
        end
        medianGAUC = median(X.gAUC);
        medianEndpoint = median(X.IGD100K);
        score = sqrt(safeRatio(X.gAUC,medianGAUC) .* ...
            safeRatio(X.IGD100K,medianEndpoint));
        X.representativeScore = score;
        X = sortrows(X,{'representativeScore','IGD100K','run'}, ...
            {'ascend','ascend','ascend'});
        chosen = X(2,:);
        Rows(i) = struct( ...
            'stageName',chosen.stageName, ...
            'factorName',chosen.factorName, ...
            'armName',chosen.armName, ...
            'armValue',chosen.armValue, ...
            'problem',chosen.problem, ...
            'run',chosen.run, ...
            'rankWithinProblem',2, ...
            'representativeScore',chosen.representativeScore, ...
            'gAUC',chosen.gAUC, ...
            'IGD100K',chosen.IGD100K, ...
            'seed',chosen.seed, ...
            'outputFile',chosen.outputFile, ...
            'snapshotCount',chosen.snapshotCount);
    end
    R = struct2table(Rows);
end

function writeRecommendation(analysisDir,A,S)
    selected = S(S.armValue == A.recommendedArm,:);
    numerical = S(S.armValue == A.numericalBestArm,:);
    lines = [ ...
        "PairGuide training-schedule analysis"; ...
        "Stage: "+A.stageName; ...
        "Factor: "+A.factorName; ...
        "Paired blocks: "+A.blockCount; ...
        "Numerical-best arm: "+compose('%g',A.numericalBestArm); ...
        "Recommended arm: "+compose('%g',A.recommendedArm); ...
        "Recommended gAUC median ratio: "+ ...
            compose('%.6g',selected.gAUCRatioToBestMedian); ...
        "Recommended IGD100K median ratio: "+ ...
            compose('%.6g',selected.IGD100KRatioToBestMedian); ...
        "Numerical-best paired score: "+ ...
            compose('%.6g',numerical.numericalScore); ...
        "Gate: both overall median ratios <= 1.05"; ...
        "Gate: both five-run problem median ratios <= 1.10"; ...
        "Decision: smallest arm passing both gates"; ...
        "Training diagnostics: descriptive only; selection gate unchanged"; ...
        "IGD penalty: "+A.igdPenaltyRule];
    Penalties = A.problemIGDPenalties;
    penaltyLines = "Penalty "+Penalties.problem+": "+ ...
        compose('%.9g',Penalties.penalty)+ ...
        " (nonfinite values="+Penalties.nonfiniteValueCount+")";
    lines = [lines;penaltyLines];
    if strlength(A.representativeRule) > 0
        lines(end+1) = "Representative run: "+A.representativeRule;
    end
    writelines(lines,fullfile(analysisDir,'recommendation.txt'));
end
