function Summary = render_CBS_PairGuide_epoch_first_use_figures( ...
        rootPath,campaignName)
%RENDER_CBS_PAIRGUIDE_EPOCH_FIRST_USE_FIGURES Render one six-layer plot/run.

    if nargin < 1 || isempty(rootPath)
        rootPath = fileparts(which('platemo'));
    end
    if nargin < 2 || isempty(campaignName)
        campaignName = "CBS_PairGuide_first_use_epoch_v4_20260901";
    end
    rootPath = char(rootPath);
    campaignDir = fullfile(rootPath,'Data',char(campaignName));
    Manifest = load(fullfile(campaignDir,'campaign_manifest.mat'), ...
        'Protocol','Tasks');
    P = Manifest.Protocol;
    Tasks = Manifest.Tasks;
    addCBSPaths(rootPath);

    Index = repmat(struct('problem',"",'epoch',0,'run',0, ...
        'poolFE',NaN,'useFE',NaN,'guidedCount',0, ...
        'constrainedPopulationCount',0, ...
        'unconstrainedPopulationCount',0, ...
        'rawVisibleCount',0,'rawOutsideView',0, ...
        'viewLower1',NaN,'viewUpper1',NaN, ...
        'viewLower2',NaN,'viewUpper2',NaN, ...
        'viewLower3',NaN,'viewUpper3',NaN,'file',""), ...
        numel(Tasks),1);
    for i = 1 : numel(Tasks)
        Task = Tasks(i);
        Data = load(Task.outputFile,'Snapshot');
        S = Data.Snapshot;
        problemConstructor = str2func(char(Task.problem));
        Problem = problemConstructor('N',P.popSize,'D',P.dimension, ...
            'maxFE',1e9,'maxRuntime',Inf);
        View = informativeView(S,Problem.M);
        outputDir = fullfile(campaignDir,'figures',char(Task.problem), ...
            sprintf('epoch_%04d',Task.epoch));
        ensureFolder(outputDir);
        outputFile = fullfile(outputDir,sprintf( ...
            '%s_epoch%04d_run%02d.png', ...
            Task.problem,Task.epoch,Task.run));
        if ~validPNG(outputFile)
            if exist(outputFile,'file') == 2
                error('CBSPairGuide:InvalidExistingEpochFigure', ...
                    'An invalid figure exists and will not be overwritten: %s', ...
                    outputFile);
            end
            renderOne(Problem,Task,S,View,outputFile);
        end
        Index(i) = struct('problem',Task.problem,'epoch',Task.epoch, ...
            'run',Task.run,'poolFE',S.poolFE,'useFE',S.useFE, ...
            'guidedCount',S.guidedCount, ...
            'constrainedPopulationCount', ...
                S.constrainedPopulationCount, ...
            'unconstrainedPopulationCount', ...
                S.unconstrainedPopulationCount, ...
            'rawVisibleCount',S.rawCount-View.rawOutside, ...
            'rawOutsideView',View.rawOutside, ...
            'viewLower1',View.lower(1),'viewUpper1',View.upper(1), ...
            'viewLower2',View.lower(2),'viewUpper2',View.upper(2), ...
            'viewLower3',View.lower(3),'viewUpper3',View.upper(3), ...
            'file',string(outputFile));
    end
    FigureIndex = struct2table(Index);
    writetable(FigureIndex,fullfile(campaignDir,'figure_index.csv'));
    Summary = struct('schemaVersion',P.schemaVersion, ...
        'campaignName',string(campaignName), ...
        'viewPolicy',"central 98% raw plus all P1, P2, and guided points", ...
        'figureCount',height(FigureIndex), ...
        'expectedFigureCount',numel(P.problems)*numel(P.epochs)* ...
            numel(P.runs), ...
        'finishedAt',string(datetime('now')));
    if Summary.figureCount ~= Summary.expectedFigureCount
        error('CBSPairGuide:EpochFigureCount', ...
            'Rendered %d figures; expected %d.',Summary.figureCount, ...
            Summary.expectedFigureCount);
    end
    save(fullfile(campaignDir,'figure_summary.mat'), ...
        'Summary','FigureIndex');
end

function renderOne(Problem,Task,S,L,outputFile)
    Figure = figure('Visible','off','Color','w', ...
        'Position',[100,100,1400,1050]);
    cleanup = onCleanup(@()close(Figure));
    Ax = axes(Figure,'Position',[0.075,0.105,0.70,0.80]);
    hold(Ax,'on');
    C = figureColors();
    [hFeasible,hInfeasible] = draw_CBS_CGAN_objective_region( ...
        Ax,Problem,Task.problem,C,L);
    if Problem.M == 2
        hRaw = scatter(Ax,S.rawObjs(:,1),S.rawObjs(:,2),18, ...
            C.raw,'filled','o','MarkerFaceAlpha',0.42, ...
            'MarkerEdgeColor','none');
        hConstrained = scatter(Ax,S.constrainedPopulationObjs(:,1), ...
            S.constrainedPopulationObjs(:,2),48,C.constrained, ...
            'filled','o','MarkerEdgeColor',[0.12,0.12,0.12], ...
            'LineWidth',0.55);
        hUnconstrained = scatter(Ax, ...
            S.unconstrainedPopulationObjs(:,1), ...
            S.unconstrainedPopulationObjs(:,2),54,C.unconstrained, ...
            'filled','^','MarkerEdgeColor',[0.12,0.12,0.12], ...
            'LineWidth',0.55);
        hGuided = scatter(Ax,S.guidedObjs(:,1),S.guidedObjs(:,2),82, ...
            C.guided,'filled','d','MarkerEdgeColor',[0.12,0.12,0.12], ...
            'LineWidth',0.8);
        xlabel(Ax,'f_1','Interpreter','tex');
        ylabel(Ax,'f_2','Interpreter','tex');
    else
        hRaw = scatter3(Ax,S.rawObjs(:,1),S.rawObjs(:,2), ...
            S.rawObjs(:,3),15,C.raw,'filled','o', ...
            'MarkerFaceAlpha',0.42,'MarkerEdgeColor','none');
        hConstrained = scatter3(Ax, ...
            S.constrainedPopulationObjs(:,1), ...
            S.constrainedPopulationObjs(:,2), ...
            S.constrainedPopulationObjs(:,3),44,C.constrained, ...
            'filled','o','MarkerEdgeColor',[0.12,0.12,0.12], ...
            'LineWidth',0.45);
        hUnconstrained = scatter3(Ax, ...
            S.unconstrainedPopulationObjs(:,1), ...
            S.unconstrainedPopulationObjs(:,2), ...
            S.unconstrainedPopulationObjs(:,3),50,C.unconstrained, ...
            'filled','^','MarkerEdgeColor',[0.12,0.12,0.12], ...
            'LineWidth',0.45);
        hGuided = scatter3(Ax,S.guidedObjs(:,1),S.guidedObjs(:,2), ...
            S.guidedObjs(:,3),88,C.guided,'filled','d', ...
            'MarkerEdgeColor',[0.12,0.12,0.12],'LineWidth',0.8);
        xlabel(Ax,'f_1','Interpreter','tex');
        ylabel(Ax,'f_2','Interpreter','tex');
        zlabel(Ax,'f_3','Interpreter','tex');
        xlim(Ax,[L.lower(1),L.upper(1)]);
        ylim(Ax,[L.lower(2),L.upper(2)]);
        zlim(Ax,[L.lower(3),L.upper(3)]);
        axis(Ax,'vis3d');
        view(Ax,42,25);
        Ax.Position = [0.08,0.18,0.64,0.62];
    end
    if Problem.M == 2
        xlim(Ax,[L.lower(1),L.upper(1)]);
        ylim(Ax,[L.lower(2),L.upper(2)]);
    end
    grid(Ax,'on');
    box(Ax,'on');
    Ax.FontName = 'Helvetica';
    Ax.FontSize = 13;
    Ax.LineWidth = 0.9;
    titleLine = sprintf('%s  |  Epoch %d  |  run %d  |  first-use FE %s', ...
        Task.problem,Task.epoch,Task.run,commaNumber(S.useFE));
    annotation(Figure,'textbox',[0.05,0.95,0.90,0.035], ...
        'String',titleLine,'Interpreter','none','EdgeColor','none', ...
        'HorizontalAlignment','center','VerticalAlignment','middle', ...
        'FontName','Helvetica','FontWeight','bold','FontSize',15);
    annotation(Figure,'textbox',[0.05,0.915,0.90,0.03], ...
        'String',sprintf( ...
        ['P1 constrained: %d     P2 unconstrained: %d     ', ...
         'raw CGAN: %d (%d visible, %d outside zoom)     guided: %d / %d'], ...
        S.constrainedPopulationCount,S.unconstrainedPopulationCount, ...
        S.rawCount,S.rawCount-L.rawOutside,L.rawOutside, ...
        S.guidedCount,S.requestedCount), ...
        'Interpreter','none','EdgeColor','none', ...
        'HorizontalAlignment','center','VerticalAlignment','middle', ...
        'FontName','Helvetica','FontSize',12);
    Legend = legend(Ax,[hFeasible,hInfeasible,hConstrained, ...
        hUnconstrained,hRaw,hGuided], ...
        {'Feasible objective region','Infeasible objective region', ...
         sprintf('Constrained population P1 (%d)', ...
            S.constrainedPopulationCount), ...
         sprintf('Unconstrained population P2 (%d)', ...
            S.unconstrainedPopulationCount), ...
         sprintf('Raw CGAN candidates (%d)',S.rawCount), ...
         sprintf('Truly guided offspring (%d/%d)', ...
         S.guidedCount,S.requestedCount)}, ...
        'Location','northeastoutside','FontSize',11);
    if Problem.M == 3
        Legend.Units = 'normalized';
        Legend.Position = [0.745,0.665,0.245,0.22];
    end
    partialFile = [outputFile,'.partial.png'];
    exportgraphics(Figure,partialFile,'Resolution',180, ...
        'BackgroundColor','white');
    if ~validPNG(partialFile)
        error('CBSPairGuide:InvalidEpochPNG', ...
            'Rendered PNG failed validation: %s',partialFile);
    end
    [moved,message] = movefile(partialFile,outputFile);
    if ~moved
        error('CBSPairGuide:EpochPNGMoveFailed','%s',message);
    end
    clear cleanup;
end

function View = informativeView(S,M)
%INFORMATIVEVIEW Zoom each run without letting rare raw outliers dominate.

    Raw = double(S.rawObjs(:,1:M));
    Guided = double(S.guidedObjs(:,1:M));
    Constrained = double(S.constrainedPopulationObjs(:,1:M));
    Unconstrained = double(S.unconstrainedPopulationObjs(:,1:M));
    Required = [Guided;Constrained;Unconstrained];
    lower = nan(1,3);
    upper = nan(1,3);
    for objective = 1 : M
        raw = Raw(isfinite(Raw(:,objective)),objective);
        required = Required(isfinite(Required(:,objective)),objective);
        if isempty(raw) && isempty(required)
            lo = 0;
            hi = 1;
        elseif isempty(raw)
            lo = min(required);
            hi = max(required);
        else
            lo = empiricalQuantile(raw,0.01);
            hi = empiricalQuantile(raw,0.99);
            if ~isempty(required)
                lo = min(lo,min(required));
                hi = max(hi,max(required));
            end
        end
        span = hi-lo;
        if span <= eps(max(1,max(abs([lo,hi]))))
            span = max(1,max(abs([lo,hi])));
        end
        lower(objective) = max(0,lo-0.05*span);
        upper(objective) = hi+0.05*span;
    end
    finiteRaw = all(isfinite(Raw),2);
    outside = ~finiteRaw;
    if any(finiteRaw)
        outside(finiteRaw) = any( ...
            Raw(finiteRaw,:) < lower(1:M) | ...
            Raw(finiteRaw,:) > upper(1:M),2);
    end
    View = struct('lower',lower,'upper',upper, ...
        'rawOutside',sum(outside));
end

function value = empiricalQuantile(X,probability)
    X = sort(X(:));
    if isscalar(X)
        value = X;
        return;
    end
    position = 1+(numel(X)-1)*probability;
    lo = floor(position);
    hi = ceil(position);
    fraction = position-lo;
    value = X(lo)+fraction*(X(hi)-X(lo));
end

function C = figureColors()
    C = struct('feasible',[0.36,0.72,0.47], ...
        'infeasible',[0.90,0.43,0.40], ...
        'constrained',[0.48,0.20,0.72], ...
        'unconstrained',[0.00,0.58,0.62], ...
        'raw',[0.13,0.43,0.82], ...
        'guided',[1.00,0.66,0.12]);
end

function textValue = commaNumber(value)
    textValue = regexprep(sprintf('%.0f',value), ...
        '(?<!\d)(\d{1,3})(?=(\d{3})+(?!\d))','$1,');
end

function valid = validPNG(file)
    valid = false;
    if exist(file,'file') ~= 2
        return;
    end
    try
        Info = imfinfo(file);
        valid = strcmpi(Info.Format,'png') && ...
            Info.Width >= 1000 && Info.Height >= 700;
    catch
        valid = false;
    end
end

function ensureFolder(folder)
    if ~isfolder(folder)
        mkdir(folder);
    end
end
