function Summary = run_CBS_PairGuide_epoch_first_use_campaign( ...
        rootPath,nWorker)
%RUN_CBS_PAIRGUIDE_EPOCH_FIRST_USE_CAMPAIGN Compare first-use epoch effects.

    if nargin < 1 || isempty(rootPath)
        rootPath = fileparts(which('platemo'));
    end
    if nargin < 2 || isempty(nWorker)
        nWorker = 10;
    end
    rootPath = char(rootPath);
    addCBSPaths(rootPath);
    Protocol = campaignProtocol(rootPath,nWorker);
    validateProtocol(Protocol);
    campaignDir = fullfile(rootPath,'Data',char(Protocol.campaignName));
    resultDir = fullfile(campaignDir,'results');
    failureDir = fullfile(campaignDir,'failures');
    ensureFolder(resultDir);
    ensureFolder(failureDir);
    Tasks = buildTasks(Protocol,resultDir);
    manifestFile = fullfile(campaignDir,'campaign_manifest.mat');
    if exist(manifestFile,'file') == 2
        Existing = load(manifestFile,'Protocol','Tasks');
        exact = protocolsMatch(Existing.Protocol,Protocol) && ...
            isequal(Existing.Tasks,Tasks);
        extension = protocolExtensionCompatible( ...
            Existing.Protocol,Protocol,Existing.Tasks,resultDir);
        if extension
            save(manifestFile,'Protocol','Tasks');
        elseif ~exact
            error('CBSPairGuide:EpochCampaignManifestMismatch', ...
                'The existing campaign manifest uses another protocol.');
        end
    else
        save(manifestFile,'Protocol','Tasks');
    end

    pending = Tasks(~tasksComplete(Tasks,Protocol));
    pool = [];
    ownsPool = false;
    if ~isempty(pending)
        [pool,ownsPool] = exactPool(Protocol.nWorker);
    end
    cleanup = onCleanup(@()closeOwnedPool(pool,ownsPool));
    for attempt = 1 : Protocol.maxAttempts
        if isempty(pending)
            break;
        end
        [~,order] = sort([pending.epoch],'descend');
        pending = pending(order);
        fprintf('PairGuide epoch first-use: %d tasks, attempt %d/%d\n', ...
            numel(pending),attempt,Protocol.maxAttempts);
        parfor (i = 1:numel(pending),Protocol.nWorker)
            Task = pending(i);
            try
                runTask(rootPath,Task,Protocol);
            catch err
                writeFailure(failureDir,Task,attempt,err);
            end
        end
        pending = Tasks(~tasksComplete(Tasks,Protocol));
    end
    if ~isempty(pending)
        error('CBSPairGuide:EpochCampaignTasksFailed', ...
            '%d epoch tasks failed after %d attempts.', ...
            numel(pending),Protocol.maxAttempts);
    end
    clear cleanup;
    closeOwnedPool(pool,ownsPool);

    Analysis = analyze_CBS_PairGuide_epoch_first_use_campaign( ...
        rootPath,Protocol.campaignName);
    Figures = render_CBS_PairGuide_epoch_first_use_figures( ...
        rootPath,Protocol.campaignName);
    Summary = struct('schemaVersion',Protocol.schemaVersion, ...
        'campaignName',Protocol.campaignName,'taskCount',numel(Tasks), ...
        'figureCount',Figures.figureCount, ...
        'recommendedEpoch',Analysis.recommendedEpoch, ...
        'finishedAt',string(datetime('now')));
    save(fullfile(campaignDir,'campaign_summary.mat'), ...
        'Summary','Analysis','Figures');
    writelines("COMPLETE",fullfile(campaignDir,'COMPLETE.txt'));
end

function P = campaignProtocol(rootPath,nWorker)
    P = struct( ...
        'schemaVersion',"CBS-PairGuide-first-use-epoch-v4", ...
        'campaignName',"CBS_PairGuide_first_use_epoch_v4_20260901", ...
        'rootPath',string(rootPath), ...
        'algorithm',"CBS_RegionWGAN_GP_PairGuide", ...
        'problems',["LIRCMOP5_BC","LIRCMOP7_BC", ...
            "LIRCMOP8_BC","LIRCMOP10_BC", ...
            "LIRCMOP12_BC","LIRCMOP14_BC"], ...
        'epochs',[400 600 800 1000 1200], ...
        'runs',1:2,'popSize',100,'dimension',30, ...
        'maxFE',200000,'rawGuideCount',500,'zDim',6, ...
        'miniBatch',64,'nCritic',4,'minGANTrainCount',32, ...
        'sampleSigma',1,'expectedRequestedCount',20, ...
        'nWorker',double(nWorker),'maxAttempts',2);
end

function validateProtocol(P)
    expectedProblems = ["LIRCMOP5_BC","LIRCMOP7_BC", ...
        "LIRCMOP8_BC","LIRCMOP10_BC", ...
        "LIRCMOP12_BC","LIRCMOP14_BC"];
    if P.algorithm ~= "CBS_RegionWGAN_GP_PairGuide" || ...
            ~isequal(P.problems,expectedProblems) || ...
            ~isequal(P.epochs,[400 600 800 1000 1200]) || ...
            ~isequal(P.runs,1:2) || P.popSize ~= 100 || ...
            P.dimension ~= 30 || P.maxFE ~= 200000 || ...
            P.rawGuideCount ~= 500 || P.miniBatch ~= 64 || ...
            P.expectedRequestedCount ~= 20 || ...
            P.nWorker ~= 10
        error('CBSPairGuide:BadEpochCampaignProtocol', ...
            'The fixed first-use epoch protocol was changed.');
    end
end

function compatible = protocolExtensionCompatible(A,B,OldTasks,resultDir)
%PROTOCOLEXTENSIONCOMPATIBLE Permit only an append-only epoch refinement.

    fields = {'schemaVersion','campaignName','rootPath','algorithm', ...
        'problems','runs','popSize','dimension','maxFE', ...
        'rawGuideCount','zDim','miniBatch','nCritic', ...
        'minGANTrainCount','sampleSigma','expectedRequestedCount'};
    compatible = all(isfield(A,[fields,{'epochs'}])) && ...
        all(isfield(B,[fields,{'epochs'}]));
    for i = 1 : numel(fields)
        compatible = compatible && isequaln(A.(fields{i}),B.(fields{i}));
    end
    compatible = compatible && numel(A.epochs) < numel(B.epochs) && ...
        isequal(A.epochs,B.epochs(1:numel(A.epochs))) && ...
        isequal(OldTasks,buildTasks(A,resultDir));
end

function same = protocolsMatch(A,B)
    fields = {'schemaVersion','campaignName','rootPath','algorithm', ...
        'problems','epochs','runs','popSize','dimension','maxFE', ...
        'rawGuideCount','zDim','miniBatch','nCritic', ...
        'minGANTrainCount','sampleSigma','expectedRequestedCount'};
    same = all(isfield(A,fields)) && all(isfield(B,fields));
    for i = 1 : numel(fields)
        same = same && isequaln(A.(fields{i}),B.(fields{i}));
    end
end

function Tasks = buildTasks(P,resultDir)
    template = struct('problem',"",'epoch',0,'run',0,'seed',0, ...
        'sampleSeed',0,'outputFile',"");
    Tasks = repmat(template, ...
        numel(P.problems)*numel(P.epochs)*numel(P.runs),1);
    row = 0;
    for problem = 1 : numel(P.problems)
        for epoch = P.epochs
            for run = P.runs
                row = row+1;
                Tasks(row).problem = P.problems(problem);
                Tasks(row).epoch = epoch;
                Tasks(row).run = run;
                Tasks(row).seed = run;
                Tasks(row).sampleSeed = 100000+1000*problem+run;
                Tasks(row).outputFile = string(fullfile(resultDir, ...
                    sprintf('%s_epoch%04d_run%02d.mat', ...
                    P.problems(problem),epoch,run)));
            end
        end
    end
end

function OutputFile = runTask(rootPath,Task,P)
    cd(rootPath);
    addCBSPaths(rootPath);
    try
        maxNumCompThreads(1);
    catch
    end
    if exist(Task.outputFile,'file') == 2
        if resultComplete(Task,P)
            OutputFile = char(Task.outputFile);
            return;
        end
        error('CBSPairGuide:ExistingInvalidEpochResult', ...
            'An invalid result exists and will not be overwritten: %s', ...
            Task.outputFile);
    end

    rng(Task.seed,'twister');
    problemConstructor = str2func(char(Task.problem));
    Problem = problemConstructor('N',P.popSize,'D',P.dimension, ...
        'maxFE',P.maxFE,'maxRuntime',Inf);
    parameters = {P.rawGuideCount,P.zDim,Task.epoch,P.miniBatch, ...
        P.nCritic,P.minGANTrainCount,P.sampleSigma};
    Algorithm = CBS_RegionWGAN_GP_PairGuide('parameter',parameters, ...
        'save',0,'run',Task.run,'outputFcn',@silentOutput);
    Algorithm.configureFirstPairGuideUseCapture(struct( ...
        'enabled',true,'stopAfterUse',true, ...
        'sampleSeed',Task.sampleSeed));

    started = datetime('now','TimeZone','local');
    wallClock = tic;
    Algorithm.Solve(Problem);
    elapsed = toc(wallClock);
    Capture = Algorithm.firstPairGuideUseCapture();
    Audit = Algorithm.guideExperimentSnapshot();
    validateCapture(Task,P,Problem,Capture,Audit);

    EvalProblem = problemConstructor('N',P.popSize,'D',P.dimension, ...
        'maxFE',1e9,'maxRuntime',Inf);
    Raw = EvalProblem.Evaluation(Capture.rawDecs);
    rawObjs = double(Raw.objs);
    rawCons = double(Raw.cons);
    childObjs = double(Capture.childObjs);
    childCons = double(Capture.childCons);
    constrainedPopulationObjs = ...
        double(Capture.constrainedPopulationObjs);
    constrainedPopulationCons = ...
        double(Capture.constrainedPopulationCons);
    unconstrainedPopulationObjs = ...
        double(Capture.unconstrainedPopulationObjs);
    unconstrainedPopulationCons = ...
        double(Capture.unconstrainedPopulationCons);
    parentObjs = double(Capture.guideTrace.parentObjs);
    if isempty(parentObjs)
        parentObjs = zeros(0,Problem.M);
    end
    childFeasible = rowFeasible(childCons);
    childDominating = all(childObjs <= parentObjs+1e-12,2) & ...
        any(childObjs < parentObjs-1e-12,2);
    Snapshot = struct( ...
        'poolFE',Capture.poolFE,'useFE',Capture.useFE, ...
        'rawCount',size(rawObjs,1), ...
        'constrainedPopulationCount', ...
            size(constrainedPopulationObjs,1), ...
        'unconstrainedPopulationCount', ...
            size(unconstrainedPopulationObjs,1), ...
        'requestedCount',Capture.requestedCount, ...
        'guidedCount',Capture.selectedCount, ...
        'fallbackCount',Capture.fallbackCount, ...
        'rawObjs',rawObjs,'rawCons',rawCons, ...
        'constrainedPopulationObjs',constrainedPopulationObjs, ...
        'constrainedPopulationCons',constrainedPopulationCons, ...
        'unconstrainedPopulationObjs',unconstrainedPopulationObjs, ...
        'unconstrainedPopulationCons',unconstrainedPopulationCons, ...
        'guidedObjs',childObjs,'guidedCons',childCons, ...
        'parentObjs',parentObjs, ...
        'rawFeasible',rowFeasible(rawCons), ...
        'guidedFeasible',childFeasible, ...
        'guidedDominating',childDominating, ...
        'guidedUseful',childFeasible & childDominating);
    Metrics = taskMetrics(Capture,Snapshot,elapsed);
    Record = struct('schemaVersion',P.schemaVersion,'status',"ok", ...
        'algorithm',P.algorithm,'problem',Task.problem, ...
        'epoch',Task.epoch,'run',Task.run,'seed',Task.seed, ...
        'sampleSeed',Task.sampleSeed,'N',P.popSize,'D',P.dimension, ...
        'M',Problem.M,'maxFE',P.maxFE, ...
        'startedAt',string(started), ...
        'finishedAt',string(datetime('now')), ...
        'wallClockSeconds',elapsed, ...
        'algorithmRuntimeSeconds',double(Algorithm.metric.runtime), ...
        'searchFE',double(Problem.FE),'offlineEvaluationFE', ...
        double(EvalProblem.FE),'terminalRNG',rng);

    OutputFile = char(Task.outputFile);
    partialFile = [OutputFile,'.partial.mat'];
    save(partialFile,'Record','Capture','Snapshot','Metrics','Audit','-v7.3');
    PartialTask = Task;
    PartialTask.outputFile = string(partialFile);
    if ~resultComplete(PartialTask,P)
        error('CBSPairGuide:InvalidEpochPartial', ...
            'The saved partial epoch result failed validation.');
    end
    [moved,message] = movefile(partialFile,OutputFile);
    if ~moved
        error('CBSPairGuide:EpochResultMoveFailed','%s',message);
    end
end

function validateCapture(Task,P,Problem,C,Audit)
    validTraining = isstruct(C.trainStatus) && ...
        C.trainStatus.trained && C.trainStatus.useModel && ...
        C.trainStatus.epochs == Task.epoch;
    if ~C.complete || ~validTraining || Problem.FE ~= C.useFE || ...
            C.useFE-C.poolFE ~= Problem.N || ...
            size(C.rawDecs,1) ~= P.rawGuideCount || ...
            size(C.rawDecs,2) ~= Problem.D || ...
            C.requestedCount ~= P.expectedRequestedCount || ...
            C.selectedCount+C.fallbackCount ~= C.requestedCount || ...
            size(C.childDecs,1) ~= C.selectedCount || ...
            size(C.childObjs,1) ~= C.selectedCount || ...
            size(C.childCons,1) ~= C.selectedCount || ...
            size(C.constrainedPopulationObjs,1) ~= P.popSize || ...
            size(C.constrainedPopulationObjs,2) ~= Problem.M || ...
            size(C.constrainedPopulationCons,1) ~= P.popSize || ...
            size(C.unconstrainedPopulationObjs,1) ~= P.popSize || ...
            size(C.unconstrainedPopulationObjs,2) ~= Problem.M || ...
            size(C.unconstrainedPopulationCons,1) ~= P.popSize || ...
            ~isfield(Audit,'rawOracleCount') || Audit.rawOracleCount ~= 0
        error('CBSPairGuide:BadEpochFirstUseCapture', ...
            '%s epoch %d run %d has an invalid first-use capture.', ...
            Task.problem,Task.epoch,Task.run);
    end
end

function M = taskMetrics(C,S,elapsed)
    pool = C.poolTrace;
    signature = round(C.rawDecs/1e-6);
    M = struct( ...
        'wallClockSeconds',double(elapsed), ...
        'poolFE',double(C.poolFE),'useFE',double(C.useFE), ...
        'trainingPairs',double(C.trainStatus.trainingPairs), ...
        'batchesPerEpoch',double(C.trainStatus.batchesPerEpoch), ...
        'updates',double(C.trainStatus.updates), ...
        'pairVisits',double(C.trainStatus.pairVisits), ...
        'candidateValidCount',double(pool.validCount), ...
        'candidateValidRate',double(pool.validCount)/S.rawCount, ...
        'requestedCount',double(S.requestedCount), ...
        'guidedCount',double(S.guidedCount), ...
        'guidedSelectionRate',double(S.guidedCount)/S.requestedCount, ...
        'fallbackCount',double(S.fallbackCount), ...
        'rawFeasibleRate',mean(S.rawFeasible), ...
        'rawDecisionUniqueRate',size(unique(signature,'rows'),1)/S.rawCount, ...
        'guidedFeasibleRate',safeMean(S.guidedFeasible), ...
        'guidedDominatingRate',safeMean(S.guidedDominating), ...
        'guidedUsefulRate',safeMean(S.guidedUseful), ...
        'guidedUsefulPerQuota',sum(S.guidedUseful)/S.requestedCount);
end

function feasible = rowFeasible(Cons)
    if isempty(Cons)
        feasible = false(0,1);
    else
        feasible = sum(max(0,double(Cons)),2) <= 0;
    end
end

function value = safeMean(X)
    if isempty(X)
        value = NaN;
    else
        value = mean(double(X));
    end
end

function mask = tasksComplete(Tasks,P)
    mask = false(numel(Tasks),1);
    for i = 1 : numel(Tasks)
        mask(i) = resultComplete(Tasks(i),P);
    end
end

function complete = resultComplete(Task,P)
    complete = false;
    if exist(Task.outputFile,'file') ~= 2
        return;
    end
    try
        Data = load(Task.outputFile,'Record','Capture','Snapshot','Audit');
        R = Data.Record;
        C = Data.Capture;
        S = Data.Snapshot;
        complete = string(R.schemaVersion) == P.schemaVersion && ...
            string(R.status) == "ok" && string(R.problem) == Task.problem && ...
            R.epoch == Task.epoch && R.run == Task.run && ...
            R.seed == Task.seed && R.sampleSeed == Task.sampleSeed && ...
            R.N == P.popSize && R.D == P.dimension && ...
            R.searchFE == C.useFE && C.complete && ...
            C.useFE-C.poolFE == P.popSize && ...
            size(C.rawDecs,1) == P.rawGuideCount && ...
            C.requestedCount == P.expectedRequestedCount && ...
            C.selectedCount+C.fallbackCount == C.requestedCount && ...
            C.trainStatus.trained && C.trainStatus.useModel && ...
            C.trainStatus.epochs == Task.epoch && ...
            S.rawCount == P.rawGuideCount && ...
            S.constrainedPopulationCount == P.popSize && ...
            S.unconstrainedPopulationCount == P.popSize && ...
            size(S.constrainedPopulationObjs,1) == P.popSize && ...
            size(S.unconstrainedPopulationObjs,1) == P.popSize && ...
            S.requestedCount == P.expectedRequestedCount && ...
            S.guidedCount == C.selectedCount && ...
            Data.Audit.rawOracleCount == 0;
    catch
        complete = false;
    end
end

function [pool,ownsPool] = exactPool(nWorker)
    pool = gcp('nocreate');
    ownsPool = isempty(pool);
    if ownsPool
        pool = parpool("Processes",nWorker);
    elseif pool.NumWorkers ~= nWorker
        error('CBSPairGuide:EpochWorkerCount', ...
            'The existing pool must contain exactly %d workers.',nWorker);
    end
end

function closeOwnedPool(pool,ownsPool)
    if ownsPool && ~isempty(pool) && isvalid(pool)
        delete(pool);
    end
end

function writeFailure(folder,Task,attempt,err)
    file = fullfile(folder,sprintf('%s_epoch%04d_run%02d_attempt%02d.txt', ...
        Task.problem,Task.epoch,Task.run,attempt));
    writelines(string(getReport(err,'extended','hyperlinks','off')),file);
end

function silentOutput(~,~)
end

function ensureFolder(folder)
    if ~isfolder(folder)
        mkdir(folder);
    end
end
