function test_CBS_region_wgan_mainline()
%TEST_CBS_REGION_WGAN_MAINLINE Verify the sole production algorithm.

    repoRoot = fileparts(which('platemo'));
    addCBSPaths(repoRoot);
    assert(exist('CBS_RegionWGAN_GP','class') == 8);
    assert(exist('CBS_RegionWGAN_GP_Core','class') == 8);
    assert(exist('CBS_RegionWGAN_GP_PairGuide','class') == 8);
    removed = {'CBS_RegionWGAN_GP_Experiment','CBS_RegionWGAN_GP_A1', ...
        'CBS_RegionWGAN_GP_E0_Base','CBS_RegionWGAN_GP_DE20', ...
        'CBS_RegionWGAN_GP_FullCGAN'};
    assert(all(cellfun(@(name)exist(name,'class') == 0,removed)));

    Defaults = CBS_RegionWGAN_GP.mainlineDefaults();
    assert(~isfield(Defaults,'calibrationBudget') && ...
        exist('RefineBoundaryObservations_RC','file') == 0);
    assert(Defaults.rawGuideCount == 500 && ...
        Defaults.criticKeepCount == 200 && ...
        Defaults.legacyGuideSlots == 20 && ...
        Defaults.legacyCandidatesPerSlot == 5 && Defaults.zDim == 6 && ...
        Defaults.ganIter == 100 && Defaults.ganMiniBatch == 32 && ...
        Defaults.nCritic == 4 && Defaults.minGANTrainCount == 32 && ...
        Defaults.sampleSigma == 0.3 && Defaults.ganStopFraction == 0.5 && ...
        Defaults.guideOffspringShare == 0.20);

    source = string(fileread(which('CBS_RegionWGAN_GP_Core')));
    dataSource = string(fileread(which('BuildBoundaryDataset_RC')));
    querySource = string(fileread(which('RunRegionGAN_RC')));
    selectionSource = string(fileread(which('EnvironmentalSelection_CBS')));
    assert(contains(dataSource,'ones(numel(refs),1)') && ...
        contains(dataSource,'zeros(sum(keepI),1)'));
    assert(contains(source,'QueryC = [SampleC,ones') && ...
        contains(querySource,'0.3*totalBudget') && ...
        contains(querySource,'balancedQuerySamples') && ...
        contains(querySource,'conditionCriticFilter') && ...
        contains(source,'localTargetGuideDecisions') && ...
        contains(source,'vacancyWeightedMaximin') && ...
        contains(source,'OperatorDE(Problem,A,T,A,{1,1,1,20})') && ...
        contains(source,'ladder = [0.4,0.65,0.85]') && ...
        contains(source,['Union = [Population1,Population2,', ...
            'Offspring1, ...']) && ...
        contains(selectionSource,'truncateByObjectiveDistance') && ...
        contains(selectionSource, ...
            'Distance = pairDistance(PopObj,PopObj);'));
    forbidden = ["operatorMode","p2Operator","generatorMode", ...
        "trainData","scoutMode","metricsMode","guideRecord", ...
        "guideMode","guideAlloc","guideSelect","blsWindow", ...
        "blsFeed","initDecs","copynoise", ...
        "consensusshuffle","gapseed","guideFPolicy", ...
        "PlanGuideF_CBS","LateDifference","CutoffState", ...
        "pbestOrdinaryDE","randomGuideSlots", ...
        "calibrationBudget","RefineBoundaryObservations_RC", ...
        "BoundaryTargetXf","BoundaryTargetYf"];
    sourceTree = source+newline+dataSource+newline+querySource+newline+ ...
        string(fileread(which('BoundaryWGAN_RC')));
    assert(~any(contains(sourceTree,forbidden)));
    Parameters = {0,7,50,8,5,9,0.2};
    Algorithm = CBS_RegionWGAN_GP('parameter',Parameters,'save',0, ...
        'outputFcn',@(varargin)[]);
    assert(isequal(Algorithm.parameter,Parameters));
    Problem = DASCMOP1_BC('N',10,'D',5,'maxFE',100);
    Algorithm.Solve(Problem);
    assert(Algorithm.result{end,1} == Problem.maxFE);
    testProductionMechanismSmoke();
    testDistinctOrdinaryDE();
    fprintf('CBS sole-mainline structure passed.\n');
end

function testProductionMechanismSmoke()
    rng(17,'twister');
    Problem = LIRCMOP5_BC('N',20,'D',5,'maxFE',400);
    Algorithm = CBS_RegionWGAN_GP('parameter', ...
        {500,2,1,4,1,2,0.1},'save',0,'outputFcn',@(varargin)[]);
    Algorithm.Solve(Problem);
    Snapshot = Algorithm.guideExperimentSnapshot();
    assert(Problem.FE == 400 && Snapshot.arm == -1 && ...
        Snapshot.generationMode == "global_critic" && ...
        Snapshot.useMode == "local_target" && ...
        Snapshot.generationEvents > 0 && ...
        Snapshot.rawCandidates == 500*Snapshot.generationEvents && ...
        Snapshot.criticKept == 200*Snapshot.generationEvents && ...
        Snapshot.guidedSelected > 0 && Snapshot.guidedFallback >= 0 && ...
        Snapshot.mappedValid > 0 && ...
        isfinite(Snapshot.meanCenterStep) && ...
        isfinite(Snapshot.meanActualStep));
end

function testDistinctOrdinaryDE()
    rng(73,'twister');
    Problem = DASCMOP1_BC('N',6,'D',5,'maxFE',20);
    Population = Problem.Initialization();
    Fitness = (1:numel(Population))';
    [Offspring,Parents] = OperatorDEDistinct_CBS( ...
        Problem,Population,Fitness,4,{1,0.5,0,20});

    assert(all(Parents(:,1) ~= Parents(:,2)) && ...
        all(Parents(:,1) ~= Parents(:,3)) && ...
        all(Parents(:,2) ~= Parents(:,3)));
    Decs = Population.decs;
    expected = Decs(Parents(:,1),:) + ...
        0.5*(Decs(Parents(:,2),:)-Decs(Parents(:,3),:));
    expected = min(max(expected,Problem.lower),Problem.upper);
    assert(isequal(Offspring.decs,expected));
end
