function test_CBS_pair_guide_training_observation
%TEST_CBS_PAIR_GUIDE_TRAINING_OBSERVATION Verify formal-run observers.

    rootPath = fileparts(fileparts(fileparts(fileparts(fileparts( ...
        mfilename('fullpath'))))));
    addpath(fullfile(rootPath,'Algorithms','Multi-objective optimization', ...
        'CBS-CGAN','Support'),'-begin');
    addCBSPaths(rootPath);

    seed = 1901;
    schedule = struct('initialEpoch',2,'retrainEpoch',1,'nCritic',2);
    parameters = {500,6,2,64,4,32,1};
    rng(seed,'twister');
    PlainProblem = LIRCMOP5_BC('N',40,'D',10,'maxFE',20000, ...
        'maxRuntime',Inf);
    Plain = CBS_RegionWGAN_GP_PairGuide('parameter',parameters, ...
        'save',1,'run',1,'outputFcn',@silentOutput);
    Plain.configurePairGuideTrainingExperiment(schedule);
    Plain.Solve(PlainProblem);
    plainRNG = rng;

    metricFE = zeros(0,1);
    metricIGD = zeros(0,1);
    feasibleCount = zeros(0,1);
    rng(seed,'twister');
    ObservedProblem = LIRCMOP5_BC('N',40,'D',10,'maxFE',20000, ...
        'maxRuntime',Inf);
    Observed = CBS_RegionWGAN_GP_PairGuide('parameter',parameters, ...
        'save',1,'run',1,'outputFcn',@recordMetric);
    Observed.configurePairGuideTrainingExperiment(schedule);
    Observed.configureCutoffDiagnostics(struct('enabled',true, ...
        'stopAtCGANEnd',false,'disableOracleAudit',false));
    Observed.configureObjectiveSpaceSnapshots(struct('enabled',true, ...
        'targetFE',[1 10000 20000],'expectedRawCount',500, ...
        'expectedGuidedCount',8));
    Observed.Solve(ObservedProblem);
    observedRNG = rng;

    assert(PlainProblem.FE == 20000 && ObservedProblem.FE == 20000);
    assert(isequaln(plainRNG,observedRNG), ...
        'Metric/snapshot observation changed the terminal RNG.');
    assert(isequaln(double(Plain.result{end,2}.decs), ...
        double(Observed.result{end,2}.decs)) && ...
        isequaln(double(Plain.result{end,2}.objs), ...
        double(Observed.result{end,2}.objs)) && ...
        isequaln(double(Plain.result{end,2}.cons), ...
        double(Observed.result{end,2}.cons)), ...
        'Metric/snapshot observation changed the final population.');
    assert(~isempty(metricFE) && metricFE(end) == 20000 && ...
        all(diff(metricFE) > 0) && numel(metricIGD) == numel(metricFE) && ...
        numel(feasibleCount) == numel(metricFE));
    Snapshots = Observed.objectiveSpaceSnapshots();
    assert(numel(Snapshots) == 3 && ...
        isequal([Snapshots.targetFE],[1 10000 20000]) && ...
        all([Snapshots.rawCount] == 500) && ...
        all([Snapshots.requestedCount] == 8) && ...
        all([Snapshots.guidedCount]+[Snapshots.fallbackCount] == 8));
    Audit = Observed.guideExperimentSnapshot();
    assert(Audit.pairInitialEpoch == 2 && ...
        Audit.pairRetrainEpoch == 1 && Audit.nCritic == 2 && ...
        ~isempty(Audit.pairTrainingLog) && ...
        Audit.pairTrainingLog(1).kind == "initial" && ...
        Audit.pairTrainingLog(1).epochs == 2 && ...
        isfinite(Audit.pairTrainingLog(1).postAllRelationRMSE) && ...
        all([Audit.pairTrainingLog(2:end).epochs] == 1));
    fprintf('CBS PairGuide formal observation smoke test passed.\n');

    function recordMetric(Algorithm,Problem)
        savedFE = Problem.FE;
        savedRNG = rng;
        cleanup = onCleanup(@()restoreSearchState( ...
            Problem,savedFE,savedRNG));
        Population = Algorithm.result{end,2};
        if isempty(metricFE) || metricFE(end) ~= Problem.FE
            metricFE(end+1,1) = double(Problem.FE);
            metricIGD(end+1,1) = double( ...
                Problem.CalMetric('IGD',Population));
            feasibleCount(end+1,1) = nnz(all(Population.cons <= 0,2));
        end
        clear cleanup;
    end
end

function restoreSearchState(Problem,FE,RNG)
%RESTORESEARCHSTATE Keep diagnostic callbacks behavior neutral.

    Problem.FE = FE;
    rng(RNG);
end

function silentOutput(~,~)
end
