for i = 1:9
    prob = str2func(sprintf('DASCMOP%d_BC', i));
    platemo( ...
        'algorithm', @PRBCCMO1, ...
        'problem',   prob, ...
        'N',         100, ...
        'maxFE',     200000);
end

for i = 4:9
    prob = str2func(sprintf('DASCMOP%d_BC', i));
    platemo( ...
        'algorithm', @PRBCCMO1, ...
        'problem',   prob, ...
        'N',         100, ...
        'maxFE',     200000);
end

platemo('algorithm', @PRBCCMO1, 'problem',@DASCMOP1_BC,'N',100, 'maxFE',200000);
