function [RunManifest,outRoot] = run_CCMO_GAN_BDG_cgan_retained_run3( ...
        outRoot,workerCount,problemNames,N,D,maxFE,runIds,selectedVariants)
% Run the retained C0 CGAN mainline for the current K=4 branch.

    rootDir = fileparts(which('platemo'));
    if nargin < 1 || isempty(outRoot)
        stamp = char(datetime('now','Format','yyyyMMdd_HHmmss'));
        outRoot = fullfile(rootDir,'Data','CCMO_GAN_BDG', ...
            ['cgan_retained_run3_n100_fe100000_7w_',stamp]);
    end
    if nargin < 2 || isempty(workerCount)
        workerCount = 7;
    end
    if nargin < 3 || isempty(problemNames)
        problemNames = {'DASCMOP1_BC','DASCMOP2_BC','DASCMOP4_BC', ...
            'DASCMOP5_BC','LIRCMOP5_BC','LIRCMOP6_BC', ...
            'LIRCMOP7_BC','LIRCMOP8_BC','LIRCMOP9_BC', ...
            'LIRCMOP10_BC'};
    end
    if nargin < 4 || isempty(N)
        N = 100;
    end
    if nargin < 5
        D = [];
    end
    if nargin < 6 || isempty(maxFE)
        maxFE = 100000;
    end
    if nargin < 7 || isempty(runIds)
        runIds = 1 : 3;
    end
    if nargin < 8
        selectedVariants = [];
    end

    addpath(genpath(rootDir));
    if ~isfolder(outRoot)
        mkdir(outRoot);
    end

    specs = cganRetainedSpecs();
    if ~isempty(selectedVariants)
        selectedVariants = string(selectedVariants(:));
        keep = ismember([specs.variant]',selectedVariants);
        specs = specs(keep);
        assert(~isempty(specs), ...
            'run_CCMO_GAN_BDG_cgan_retained_run3:NoSelectedVariants', ...
            'No requested selectedVariants matched the retained CGAN specs.');
    end
    Rows = repmat(emptyManifestRow(),numel(specs),1);
    plotOptions = struct('enable',false,'targets',[], ...
        'plotRuns',[],'plotVariants',[],'ganN',0);

    for i = 1 : numel(specs)
        spec = specs(i);
        variants = table( ...
            string(spec.variant), ...
            "ref_af_nd", ...
            "af_not_dominates_ai", ...
            "none", ...
            "neighbor4", ...
            "objective_target_conditioned", ...
            "target_conditioned", ...
            "conditional_adversarial", ...
            'VariableNames',{'variant','archiveParetoFilterMode', ...
            'archivePairDirectionMode','archiveSourceCapMode', ...
            'archivePairRefMode','generatorMode','ganCriticMode', ...
            'generatorLossMode'});

        outDir = fullfile(outRoot,char(spec.variant));
        fprintf('Running %s -> %s\n',spec.variant,outDir);
        fprintf('  zDim=%g, ganIter=%g, ganGSteps=%g\n', ...
            spec.params.zDim,spec.params.ganIter, ...
            spec.params.ganGSteps);

        [Summary,actualOutDir] = ...
            run_CCMO_GAN_BDG_archive_pareto_filters_fullscope( ...
            outDir,workerCount,problemNames,N,D,maxFE,runIds, ...
            variants,spec.params,plotOptions);

        Rows(i).variant = string(spec.variant);
        Rows(i).purpose = string(spec.purpose);
        Rows(i).out_dir = string(actualOutDir);
        Rows(i).summary_file = string(fullfile(actualOutDir, ...
            'archive_pareto_filter_run_summary.csv'));
        Rows(i).overall_file = string(fullfile(actualOutDir, ...
            'archive_pareto_filter_overall.csv'));
        Rows(i).ok_count = sum(Summary.status == "ok");
        Rows(i).failed_count = sum(Summary.status ~= "ok");
        Rows(i).zDim = double(spec.params.zDim);
        Rows(i).ganIter = double(spec.params.ganIter);
        Rows(i).ganGSteps = double(spec.params.ganGSteps);
        Rows(i).generatorLossMode = "conditional_adversarial";
    end

    RunManifest = struct2table(Rows);
    writetable(RunManifest,fullfile(outRoot, ...
        'cgan_retained_manifest.csv'));
end

function specs = cganRetainedSpecs()
    base = struct( ...
        'trainGap',1, ...
        'nGen',50, ...
        'zDim',4, ...
        'perRef',5, ...
        'nearTau',0.20, ...
        'ganIter',50, ...
        'probeRawN',0, ...
        'stageProbeN',200, ...
        'ganDPretrainIter',0, ...
        'ganDSteps',1, ...
        'ganGSteps',1, ...
        'archiveGap',1, ...
        'ganArchMode',"g2sl", ...
        'ganMiniBatch',64, ...
        'ganRealLabel',0.9, ...
        'ganLrD',1e-4, ...
        'ganLrG',1e-4, ...
        'ganTrainMode',"epoch");

    specs = repmat(struct( ...
        'variant',"", ...
        'purpose',"", ...
        'params',base),1,1);

    specs(1).variant = "C0_z4_iter50_g1_full";
    specs(1).purpose = "Retained current best CGAN mainline.";
end

function Row = emptyManifestRow()
    Row = struct( ...
        'variant',"", ...
        'purpose',"", ...
        'out_dir',"", ...
        'summary_file',"", ...
        'overall_file',"", ...
        'ok_count',NaN, ...
        'failed_count',NaN, ...
        'zDim',NaN, ...
        'ganIter',NaN, ...
        'ganGSteps',NaN, ...
        'generatorLossMode',"");
end
