function test_CCMO_GAN_BDG_target_conditioned()
% Regression tests for explicit objective-target-conditioned BDG GAN.

    rootDir = fileparts(which('platemo'));
    addpath(genpath(rootDir));

    assertBoundaryTargetTriplesUseObjectivePairs();
    assertBoundaryTargetTriplesAppendRefVectorToken();
    assertConditionKNNFilterKeepsConsistentTriples();
    assertLocalMADWeightDownweightsDecisionOutlier();
    assertRandomKeepFilterIsSeededAndKeepsConfiguredRatio();
    assertAIDominatesOnlyTrainingFilterKeepsPurePairs();
    assertTargetConditionedGANSmoke();
    assertTargetConditionedGANAcceptsRealLabelVector();
    assertTargetConditionedGANSamplesStoredConditionsByWeight();
    assertTargetConditionedGANDiagnosticSampleAcceptsFixedConditionsAndZ();
    assertTargetUnconditionedGANSmoke();
    assertG2SLUnconditionedGANOptionsSmoke();
    assertG2SLExperimentParametersReachRunMeta();
    assertGlobalNDCoverageGateSkipsCGANTraining();
    assertTargetUnconditionedVariantUsesUnconditionalGAN(rootDir);
    assertFullscopeRunnerAllowsOnlyCurrentTargetModes(rootDir);
end

function assertBoundaryTargetTriplesAppendRefVectorToken()
    Problem = struct('D',2,'M',2);
    W = [1.00 0.00;0.50 0.50;0.00 1.00];
    AF = struct( ...
        'decs',[0.20 0.30;0.40 0.50], ...
        'objs',[2 4;4 2], ...
        'ref',[1;3], ...
        'score',[0;0]);
    AI = struct( ...
        'decs',[0.10 0.20;0.30 0.40], ...
        'objs',[1 3;3 1], ...
        'ref',[1;3], ...
        'score',[0;0]);
    Options = struct('conditionMode',"yt_dt_ref");

    [~,C,Diag] = BuildBoundaryTargetTriples_BDG(AF,AI,Problem,W,Options);

    assert(isequal(size(C),[2 6]), ...
        'test_CCMO_GAN_BDG_target_conditioned:BadRefTokenConditionSize', ...
        'Ref-token conditionData must be [y_t,d_t,w_ref] with 3*M columns.');
    assert(max(abs(double(C(:,5:6)) - W([1;3],:)),[],'all') < 1e-12, ...
        'test_CCMO_GAN_BDG_target_conditioned:BadRefTokenValues', ...
        'Ref-token conditionData must append the AF.ref reference vector.');
    assert(Diag.target_condition_dim == 6, ...
        'test_CCMO_GAN_BDG_target_conditioned:BadRefTokenDiagDim', ...
        'Ref-token diagnostics must record the expanded condition dimension.');
end

function assertLocalMADWeightDownweightsDecisionOutlier()
    Problem = struct('D',2,'M',2,'lower',[0 0],'upper',[1 1]);
    W = [1 0;0 1;0.5 0.5];
    X = [0.10 0.10;0.11 0.10;0.10 0.11;0.12 0.11; ...
         0.09 0.12;0.90 0.90];
    C = single([0.50 0.50;0.51 0.50;0.50 0.51;0.49 0.50; ...
                0.50 0.49;0.505 0.505]);
    AITrain = X + 0.01;
    AF = struct('decs',X,'objs',C,'ref',[1;1;1;1;1;1], ...
        'score',zeros(6,1));
    AI = struct('decs',AITrain,'objs',C + 0.05,'ref',AF.ref, ...
        'score',zeros(6,1));
    TripleDiag = struct('target_keep_index',(1:6)');
    Options = struct( ...
        'trainFilterMode',"local_mad_weight", ...
        'conditionKNNK',5, ...
        'conditionKNNMinCount',2, ...
        'lower',Problem.lower, ...
        'upper',Problem.upper);

    [XOut,COut,AIOut,weights,Diag] = FilterBoundaryTargetTriples_BDG( ...
        X,C,AITrain,AF,AI,W,TripleDiag,Options);

    assert(size(XOut,1) == 6 && size(COut,1) == 6 && size(AIOut,1) == 6, ...
        'test_CCMO_GAN_BDG_target_conditioned:LocalMADShouldNotHardDelete', ...
        'local_mad_weight must keep all triples and downweight local decision outliers.');
    assert(numel(weights) == 6 && weights(6) < 0.25*median(weights(1:5)), ...
        'test_CCMO_GAN_BDG_target_conditioned:LocalMADBadOutlierWeight', ...
        'local_mad_weight must assign a much smaller weight to a same-condition decision outlier.');
    assert(Diag.target_filter_post_count == 6 && ...
            Diag.train_weight_count == 6 && ...
            Diag.train_weight_min == weights(6), ...
        'test_CCMO_GAN_BDG_target_conditioned:LocalMADBadDiagnostics', ...
        'local_mad_weight must report unchanged count and emitted training weights.');
end

function assertConditionKNNFilterKeepsConsistentTriples()
    Problem = struct('D',2,'M',2,'lower',[0 0],'upper',[1 1]);
    W = [1 0;0 1;0.5 0.5];
    X = [0.10 0.10;0.11 0.10;0.12 0.10; ...
         0.20 0.20;0.80 0.80;0.50 0.50];
    C = single([0.10 0.10;0.11 0.10;0.12 0.10; ...
                0.70 0.70;0.71 0.70;0.72 0.70]);
    AITrain = X + 0.01;
    AF = struct('decs',X,'objs',C,'ref',[1;1;1;2;2;2],'score',zeros(6,1));
    AI = struct('decs',AITrain,'objs',C + 0.05,'ref',AF.ref,'score',zeros(6,1));
    TripleDiag = struct('target_keep_index',(1:6)');
    Options = struct( ...
        'trainFilterMode',"condition_knn", ...
        'conditionKNNK',2, ...
        'conditionKNNRetainRatio',0.50, ...
        'conditionKNNMinCount',2);

    [XOut,COut,AIOut,weights,Diag] = FilterBoundaryTargetTriples_BDG( ...
        X,C,AITrain,AF,AI,W,TripleDiag,Options);

    assert(size(XOut,1) == 3 && size(COut,1) == 3 && size(AIOut,1) == 3, ...
        'test_CCMO_GAN_BDG_target_conditioned:BadCondKNNRetainCount', ...
        'condition-kNN filtering must retain the configured lowest-spread triples.');
    assert(isempty(weights), ...
        'test_CCMO_GAN_BDG_target_conditioned:UnexpectedCondKNNWeights', ...
        'condition-kNN filtering must be a hard training-set filter.');
    assert(Diag.target_filter_pre_count == 6 && ...
            Diag.target_filter_post_count == 3 && ...
            abs(Diag.target_filter_retain_ratio - 0.5) < 1e-12, ...
        'test_CCMO_GAN_BDG_target_conditioned:BadCondKNNDiagCounts', ...
        'condition-kNN filtering must report pre/post counts and retain ratio.');
    assert(isfinite(Diag.condition_knn_decision_spread_p90), ...
        'test_CCMO_GAN_BDG_target_conditioned:MissingCondKNNSpreadDiag', ...
        'condition-kNN filtering must report decision-spread diagnostics.');
end

function assertRandomKeepFilterIsSeededAndKeepsConfiguredRatio()
    W = [1 0;0 1;0.5 0.5];
    X = [(1:10)'/20,(1:10)'/30];
    C = single([(1:10)'/10,flipud((1:10)'/10)]);
    AITrain = X + 0.01;
    AF = struct('decs',X,'objs',[C,C],'ref',[1;1;1;2;2;2;3;3;3;3], ...
        'score',zeros(10,1));
    AI = struct('decs',AITrain,'objs',[C,C] + 0.05,'ref',AF.ref, ...
        'score',zeros(10,1));
    TripleDiag = struct('target_keep_index',(1:10)');
    Options = struct( ...
        'trainFilterMode',"random_keep", ...
        'conditionKNNRetainRatio',0.70, ...
        'randomSeed',12345);

    [XOut1,~,~,~,Diag1] = FilterBoundaryTargetTriples_BDG( ...
        X,C,AITrain,AF,AI,W,TripleDiag,Options);
    [XOut2,~,~,~,Diag2] = FilterBoundaryTargetTriples_BDG( ...
        X,C,AITrain,AF,AI,W,TripleDiag,Options);

    assert(size(XOut1,1) == 7 && size(XOut2,1) == 7, ...
        'test_CCMO_GAN_BDG_target_conditioned:BadRandomKeepCount', ...
        'random_keep must retain ceil(retainRatio*n) training triples.');
    assert(isequal(XOut1,XOut2) && ...
            isequal(Diag1.target_keep_index,Diag2.target_keep_index), ...
        'test_CCMO_GAN_BDG_target_conditioned:RandomKeepNotSeeded', ...
        'random_keep must be reproducible for the same random seed.');
    assert(Diag1.target_filter_pre_count == 10 && ...
            Diag1.target_filter_post_count == 7 && ...
            abs(Diag1.target_filter_retain_ratio - 0.7) < 1e-12 && ...
            Diag1.target_filter_mode_code == 3, ...
        'test_CCMO_GAN_BDG_target_conditioned:BadRandomKeepDiag', ...
        'random_keep must report pre/post counts, retain ratio, and mode code.');
end

function assertAIDominatesOnlyTrainingFilterKeepsPurePairs()
    Problem = struct('D',2,'M',2,'lower',[0 0],'upper',[1 1]);
    W = [1 0;0 1];
    X = [0.10 0.10;0.20 0.20;0.30 0.30;0.40 0.40];
    C = single([0.1 0.1;0.2 0.2;0.3 0.3;0.4 0.4]);
    AITrain = X + 0.01;
    AF = struct( ...
        'decs',X, ...
        'objs',[2 2;2 1;1 2;2 2], ...
        'ref',[1;1;2;2], ...
        'score',zeros(4,1));
    AI = struct( ...
        'decs',AITrain, ...
        'objs',[1 1;1 2;2 1;1.5 1.5], ...
        'ref',AF.ref, ...
        'score',zeros(4,1));
    TripleDiag = struct('target_keep_index',(1:4)');
    Options = struct('trainFilterMode',"ai_dom_only",'aiDomMinCount',2);

    [XOut,~,AIOut,weights,Diag] = FilterBoundaryTargetTriples_BDG( ...
        X,C,AITrain,AF,AI,W,TripleDiag,Options);

    assert(size(XOut,1) == 2 && size(AIOut,1) == 2 && isempty(weights), ...
        'test_CCMO_GAN_BDG_target_conditioned:BadAIDomHardFilter', ...
        'AI-dominates training mode must hard-filter to AI-dominates pairs when enough exist.');
    assert(Diag.pair_ai_dom_count == 2 && Diag.pair_mutual_nd_count == 2 && ...
            Diag.train_direction_mode_code == 1, ...
        'test_CCMO_GAN_BDG_target_conditioned:BadAIDomDiag', ...
        'AI-dominates training mode must report pair direction counts and hard-filter mode.');
end

function assertBoundaryTargetTriplesUseObjectivePairs()
    Problem = struct('D',2,'M',2);
    AF = struct( ...
        'decs',[0.20 0.30;0.40 0.50], ...
        'objs',[2 4;4 2], ...
        'ref',[1;2], ...
        'score',[0;0]);
    AI = struct( ...
        'decs',[0.10 0.20;0.30 0.40], ...
        'objs',[1 3;3 1], ...
        'ref',[1;2], ...
        'score',[0;0]);

    [X,C,Diag] = BuildBoundaryTargetTriples_BDG(AF,AI,Problem);

    expectedY = [1/3 1;1 1/3];
    expectedD = [-1/3 -1/3;-1/3 -1/3];
    assert(isequal(size(X),[2 2]), ...
        'test_CCMO_GAN_BDG_target_conditioned:BadTripleDecisionSize', ...
        'Boundary target triples must expose one AF decision per archive pair.');
    assert(isequal(size(C),[2 4]), ...
        'test_CCMO_GAN_BDG_target_conditioned:BadConditionSize', ...
        'Boundary target conditionData must be [y_t,d_t] with 2*M columns.');
    assert(max(abs(double(C(:,1:2)) - expectedY),[],'all') < 1e-6, ...
        'test_CCMO_GAN_BDG_target_conditioned:BadObjectiveTarget', ...
        'The first M condition columns must be normalized AF objective targets.');
    assert(max(abs(double(C(:,3:4)) - expectedD),[],'all') < 1e-6, ...
        'test_CCMO_GAN_BDG_target_conditioned:BadDirectionTarget', ...
        'The last M condition columns must be normalized objective directions AI-AF.');
    assert(Diag.target_triple_ready == 1 && Diag.target_triple_count == 2, ...
        'test_CCMO_GAN_BDG_target_conditioned:BadTripleDiag', ...
        'Boundary target triple diagnostics must report ready finite pairs.');
end

function assertTargetConditionedGANAcceptsRealLabelVector()
    Problem = DASCMOP1_BC('N',20,'D',30,'maxFE',1000);
    XAF = repmat(0.20,4,Problem.D);
    XAI = repmat(0.10,4,Problem.D);
    PAF = Problem.Evaluation(XAF);
    PAI = Problem.Evaluation(XAI);
    AF = struct('decs',PAF.decs,'objs',PAF.objs);
    AI = struct('decs',PAI.decs,'objs',PIAObjsDominating(PAF.objs,PAI.objs));
    [XTrain,CTrain] = BuildBoundaryTargetTriples_BDG(AF,AI,Problem);
    realLabels = single([0.20;0.40;0.80;1.00]);
    Options = struct( ...
        'generatorMode',"objective_target_conditioned", ...
        'criticMode',"target_conditioned", ...
        'generatorLossMode',"conditional_adversarial", ...
        'conditionData',CTrain, ...
        'realLabels',realLabels, ...
        'miniBatch',4, ...
        'dPretrainIter',0, ...
        'dSteps',1, ...
        'gSteps',1, ...
        'archMode',"small");

    GAN = BoundaryGAN_BDG('traindirectboundary',XTrain,AI.decs, ...
        Problem.lower,Problem.upper,2,1,[],Options);

    assert(GAN.trainRealLabelCount == 4 && ...
            abs(GAN.trainRealLabelMean - mean(double(realLabels))) < 1e-12, ...
        'test_CCMO_GAN_BDG_target_conditioned:MissingRealLabelVectorDiag', ...
        'Target-conditioned GAN must accept and report evaluated real-label vectors.');
end

function assertTargetConditionedGANSmoke()
    Problem = DASCMOP1_BC('N',20,'D',30,'maxFE',1000);
    XAF = repmat(0.20,4,Problem.D);
    XAI = repmat(0.10,4,Problem.D);
    PAF = Problem.Evaluation(XAF);
    PAI = Problem.Evaluation(XAI);
    AF = struct('decs',PAF.decs,'objs',PAF.objs);
    AI = struct('decs',PAI.decs,'objs',PIAObjsDominating(PAF.objs,PAI.objs));
    [XTrain,CTrain] = BuildBoundaryTargetTriples_BDG(AF,AI,Problem);
    Options = struct( ...
        'generatorMode',"objective_target_conditioned", ...
        'criticMode',"target_conditioned", ...
        'generatorLossMode',"conditional_adversarial", ...
        'conditionData',CTrain, ...
        'miniBatch',4, ...
        'dPretrainIter',1, ...
        'dSteps',1, ...
        'gSteps',1, ...
        'archMode',"small");

    GAN = BoundaryGAN_BDG('traindirectboundary',XTrain,AI.decs, ...
        Problem.lower,Problem.upper,2,1,[],Options);
    [Offspring,Diag] = BoundaryGAN_BDG('sample',Problem,GAN,3);

    assert(GAN.conditionDim == 2*Problem.M, ...
        'test_CCMO_GAN_BDG_target_conditioned:BadGANConditionDim', ...
        'Target-conditioned GAN must store conditionDim=2*M.');
    assert(numel(Offspring) == 3 && Diag.rawgen_count == 3, ...
        'test_CCMO_GAN_BDG_target_conditioned:BadTargetGANSample', ...
        'Target-conditioned GAN must sample complete decision offspring.');
    assert(isfield(GAN,'targetConditionedDiag') && ...
            GAN.targetConditionedDiag.target_mismatch_count > 0, ...
        'test_CCMO_GAN_BDG_target_conditioned:MissingMismatchDiag', ...
        'Target-conditioned GAN must train with mismatched real conditions.');
end

function assertTargetConditionedGANSamplesStoredConditionsByWeight()
    Problem = DASCMOP1_BC('N',20,'D',30,'maxFE',1000);
    XAF = repmat(0.20,4,Problem.D);
    XAI = repmat(0.10,4,Problem.D);
    PAF = Problem.Evaluation(XAF);
    PAI = Problem.Evaluation(XAI);
    AF = struct('decs',PAF.decs,'objs',PAF.objs);
    AI = struct('decs',PAI.decs,'objs',PIAObjsDominating(PAF.objs,PAI.objs));
    [XTrain,CTrain] = BuildBoundaryTargetTriples_BDG(AF,AI,Problem);
    sampleWeights = [0;0;1;0];
    Options = struct( ...
        'generatorMode',"objective_target_conditioned", ...
        'criticMode',"target_conditioned", ...
        'generatorLossMode',"conditional_adversarial", ...
        'conditionData',CTrain, ...
        'sampleWeights',sampleWeights, ...
        'miniBatch',4, ...
        'dPretrainIter',0, ...
        'dSteps',1, ...
        'gSteps',1, ...
        'archMode',"small");

    rng(42,'twister');
    GAN = BoundaryGAN_BDG('traindirectboundary',XTrain,AI.decs, ...
        Problem.lower,Problem.upper,2,0,[],Options);
    [~,Diag] = BoundaryGAN_BDG('sample',Problem,GAN,8);

    assert(isfield(GAN,'conditionSamplingWeights') && ...
            abs(GAN.conditionSamplingWeights(3) - 1) < 1e-12, ...
        'test_CCMO_GAN_BDG_target_conditioned:MissingConditionSamplingWeights', ...
        'Target-conditioned GAN must retain normalized condition sampling weights.');
    assert(isfield(Diag,'rawgen_condition_index') && ...
            all(Diag.rawgen_condition_index(:) == 3), ...
        'test_CCMO_GAN_BDG_target_conditioned:UnweightedGeneratedConditionSampling', ...
        'Generated target-conditioned samples must draw stored conditions according to sampleWeights.');
end

function assertTargetConditionedGANDiagnosticSampleAcceptsFixedConditionsAndZ()
    Problem = DASCMOP1_BC('N',20,'D',30,'maxFE',1000);
    XAF = repmat(0.20,4,Problem.D);
    XAI = repmat(0.10,4,Problem.D);
    PAF = Problem.Evaluation(XAF);
    PAI = Problem.Evaluation(XAI);
    AF = struct('decs',PAF.decs,'objs',PAF.objs);
    AI = struct('decs',PAI.decs,'objs',PIAObjsDominating(PAF.objs,PAI.objs));
    [XTrain,CTrain] = BuildBoundaryTargetTriples_BDG(AF,AI,Problem);
    Options = struct( ...
        'generatorMode',"objective_target_conditioned", ...
        'criticMode',"target_conditioned", ...
        'generatorLossMode',"conditional_adversarial", ...
        'conditionData',CTrain, ...
        'miniBatch',4, ...
        'dPretrainIter',0, ...
        'dSteps',1, ...
        'gSteps',1, ...
        'archMode',"small");

    GAN = BoundaryGAN_BDG('traindirectboundary',XTrain,AI.decs, ...
        Problem.lower,Problem.upper,2,0,[],Options);
    conditionIndex = [2;2;3];
    fixedZ = zeros(numel(conditionIndex),GAN.zDim);
    [Offspring,Diag] = BoundaryGAN_BDG('diagnosesample',Problem,GAN, ...
        conditionIndex,fixedZ);

    assert(numel(Offspring) == 3 && Diag.rawgen_count == 3, ...
        'test_CCMO_GAN_BDG_target_conditioned:BadDiagnosticSampleCount', ...
        'Diagnostic GAN sampling must evaluate one solution per requested condition/Z row.');
    assert(isequal(Diag.rawgen_condition_index(:),conditionIndex(:)), ...
        'test_CCMO_GAN_BDG_target_conditioned:BadDiagnosticConditionIndex', ...
        'Diagnostic GAN sampling must preserve requested condition indices.');
    Decs = Offspring.decs;
    assert(max(abs(Decs(1,:) - Decs(2,:)),[],'all') < 1e-12, ...
        'test_CCMO_GAN_BDG_target_conditioned:FixedConditionZNotDeterministic', ...
        'The same condition and the same z must produce the same generated decision.');
end

function assertTargetUnconditionedGANSmoke()
    Problem = DASCMOP1_BC('N',20,'D',30,'maxFE',1000);
    XAF = repmat(0.20,4,Problem.D);
    XAI = repmat(0.10,4,Problem.D);
    PAF = Problem.Evaluation(XAF);
    PAI = Problem.Evaluation(XAI);
    AF = struct('decs',PAF.decs,'objs',PAF.objs);
    AI = struct('decs',PAI.decs,'objs',PIAObjsDominating(PAF.objs,PAI.objs));
    [XTrain,~,TripleDiag] = BuildBoundaryTargetTriples_BDG(AF,AI,Problem);
    Options = struct( ...
        'generatorMode',"objective_target_unconditioned", ...
        'criticMode',"af_like", ...
        'generatorLossMode',"adversarial", ...
        'conditionData',[], ...
        'miniBatch',4, ...
        'dPretrainIter',1, ...
        'dSteps',1, ...
        'gSteps',1, ...
        'archMode',"small");

    GAN = BoundaryGAN_BDG('traindirectboundary',XTrain,AI.decs, ...
        Problem.lower,Problem.upper,2,1,[],Options);
    [Offspring,Diag] = BoundaryGAN_BDG('sample',Problem,GAN,3);

    assert(TripleDiag.target_triple_ready == 1, ...
        'test_CCMO_GAN_BDG_target_conditioned:BadUnconditionedTargetTriples', ...
        'Target-unconditioned smoke must still train from boundary target decisions.');
    assert(string(GAN.criticMode) == "af_like" && ...
            string(GAN.generatorLossMode) == "adversarial", ...
        'test_CCMO_GAN_BDG_target_conditioned:BadUnconditionedGANModes', ...
        'Target-unconditioned GAN must use D(x) with adversarial loss.');
    assert(GAN.conditionDim == 0 && isempty(GAN.conditionData), ...
        'test_CCMO_GAN_BDG_target_conditioned:BadUnconditionedConditionData', ...
        'Target-unconditioned GAN must not store conditionData.');
    assert(isfield(GAN,'generatorConditionDim') && ...
            GAN.generatorConditionDim == 0, ...
        'test_CCMO_GAN_BDG_target_conditioned:BadUnconditionedGeneratorConditionDim', ...
        'Target-unconditioned branch must feed only z to the generator.');
    assert(numel(Offspring) == 3 && Diag.rawgen_count == 3, ...
        'test_CCMO_GAN_BDG_target_conditioned:BadTargetUnconditionedSample', ...
        'Target-unconditioned GAN must sample complete decision offspring.');
    assert(isfield(GAN,'targetConditionedDiag') && ...
            GAN.targetConditionedDiag.target_mismatch_count == 0 && ...
            GAN.targetConditionedDiag.target_mismatch_batch_count == 0, ...
        'test_CCMO_GAN_BDG_target_conditioned:UnexpectedUnconditionedMismatchDiag', ...
        'Target-unconditioned GAN must not train mismatched real conditions.');
end

function assertG2SLUnconditionedGANOptionsSmoke()
    Problem = DASCMOP1_BC('N',20,'D',30,'maxFE',1000);
    XAF = repmat(0.20,4,Problem.D);
    XAI = repmat(0.10,4,Problem.D);
    PAF = Problem.Evaluation(XAF);
    PAI = Problem.Evaluation(XAI);
    AF = struct('decs',PAF.decs,'objs',PAF.objs);
    AI = struct('decs',PAI.decs,'objs',PIAObjsDominating(PAF.objs,PAI.objs));
    [XTrain,~,TripleDiag] = BuildBoundaryTargetTriples_BDG(AF,AI,Problem);
    Options = struct( ...
        'generatorMode',"objective_target_unconditioned", ...
        'criticMode',"af_like", ...
        'generatorLossMode',"adversarial", ...
        'conditionData',[], ...
        'miniBatch',4, ...
        'dPretrainIter',0, ...
        'dSteps',1, ...
        'gSteps',1, ...
        'archMode',"g2sl", ...
        'realLabel',0.9, ...
        'lrD',1e-4, ...
        'lrG',1e-4, ...
        'trainMode',"epoch");

    GAN = BoundaryGAN_BDG('traindirectboundary',XTrain,AI.decs, ...
        Problem.lower,Problem.upper,8,1,[],Options);

    assert(TripleDiag.target_triple_ready == 1, ...
        'test_CCMO_GAN_BDG_target_conditioned:BadG2SLTriples', ...
        'G2SL smoke must train from ready target-unconditioned AF decisions.');
    assert(string(GAN.archMode) == "g2sl" && ...
            string(GAN.trainMode) == "epoch", ...
        'test_CCMO_GAN_BDG_target_conditioned:MissingG2SLGANModes', ...
        'G2SL smoke must retain archMode=g2sl and trainMode=epoch.');
    assert(abs(double(GAN.realLabel) - 0.9) < 1e-12 && ...
            abs(double(GAN.lrD) - 1e-4) < 1e-12 && ...
            abs(double(GAN.lrG) - 1e-4) < 1e-12, ...
        'test_CCMO_GAN_BDG_target_conditioned:MissingG2SLGANScalars', ...
        'G2SL smoke must retain realLabel and learning-rate options.');
end

function assertG2SLExperimentParametersReachRunMeta()
    controlName = 'CCMO_GAN_BDG_ExperimentControl';
    oldControl = [];
    hadOldControl = isappdata(0,controlName);
    if hadOldControl
        oldControl = getappdata(0,controlName);
    end
    cleaner = onCleanup(@()restoreExperimentControl( ...
        controlName,hadOldControl,oldControl)); %#ok<NASGU>
    setappdata(0,controlName,struct( ...
        'variant',"U4_Epoch10", ...
        'archiveParetoFilterMode',"global_af_nd", ...
        'archivePairDirectionMode',"ai_dominates_af", ...
        'archiveSourceCapMode',"limited", ...
        'archivePairRefMode',"none", ...
        'ganCriticMode',"af_like", ...
        'generatorMode',"objective_target_unconditioned", ...
        'generatorLossMode',"adversarial"));

    rng(921,'twister');
    Algorithm = CCMO_GAN_BDG( ...
        'save',0, ...
        'run',921, ...
        'outputFcn',@(varargin)[], ...
        'parameter',{1,4,8,5,1,1,0,4,0,1,1,1, ...
        "g2sl",4,0.9,1e-4,1e-4,"epoch"});
    Problem = DASCMOP1_BC('N',20,'D',30,'maxFE',760);
    Algorithm.Solve(Problem);
    Meta = readtable(Algorithm.metric.analysis_meta_csv,'TextType','string');

    assert(Meta.ganArchMode(1) == "g2sl" && ...
            Meta.ganTrainMode(1) == "epoch", ...
        'test_CCMO_GAN_BDG_target_conditioned:MissingG2SLRunMetaModes', ...
        'Run meta must record g2sl GAN architecture and epoch training mode.');
    assert(abs(Meta.ganRealLabel(1) - 0.9) < 1e-12 && ...
            abs(Meta.ganLrD(1) - 1e-4) < 1e-12 && ...
            abs(Meta.ganLrG(1) - 1e-4) < 1e-12, ...
        'test_CCMO_GAN_BDG_target_conditioned:MissingG2SLRunMetaScalars', ...
        'Run meta must record real label smoothing and learning rates.');
end

function assertGlobalNDCoverageGateSkipsCGANTraining()
    controlName = 'CCMO_GAN_BDG_ExperimentControl';
    oldControl = [];
    hadOldControl = isappdata(0,controlName);
    if hadOldControl
        oldControl = getappdata(0,controlName);
    end
    cleaner = onCleanup(@()restoreExperimentControl( ...
        controlName,hadOldControl,oldControl)); %#ok<NASGU>
    setappdata(0,controlName,struct( ...
        'variant',"GND_keep80_covGate", ...
        'archiveParetoFilterMode',"global_af_nd", ...
        'archivePairDirectionMode',"af_not_dominates_ai", ...
        'archiveSourceCapMode',"none", ...
        'archivePairRefMode',"neighbor4", ...
        'trainFilterMode',"condition_knn", ...
        'conditionKNNRetainRatio',0.80, ...
        'cganTrainMinRefCov',0.50, ...
        'cganTrainMinTargetTriples',50, ...
        'conditionMode',"yt_dt", ...
        'targetRealLabelMode',"binary", ...
        'ganCriticMode',"target_conditioned", ...
        'generatorMode',"objective_target_conditioned", ...
        'generatorLossMode',"conditional_adversarial"));

    rng(923,'twister');
    Algorithm = CCMO_GAN_BDG( ...
        'save',0, ...
        'run',923, ...
        'outputFcn',@(varargin)[], ...
        'parameter',{1,4,4,1,1,1,0,4,0,1,1,1, ...
        "g2sl",4,0.9,1e-4,1e-4,"epoch"});
    Problem = DASCMOP1_BC('N',20,'D',30,'maxFE',1200);
    Algorithm.Solve(Problem);

    Meta = readtable(Algorithm.metric.analysis_meta_csv,'TextType','string');
    assert(Meta.variant(1) == "GND_keep80_covGate" && ...
            Meta.archiveParetoFilterMode(1) == "global_af_nd" && ...
            abs(Meta.cganTrainMinRefCov(1) - 0.50) < 1e-12 && ...
            Meta.cganTrainMinTargetTriples(1) == 50, ...
        'test_CCMO_GAN_BDG_target_conditioned:MissingCoverageGateRunMeta', ...
        'Run meta must record the global-ND coverage-gate experiment controls.');

    Core = readtable(Algorithm.metric.analysis_core_csv,'TextType','string');
    assert(any(Core.skip_reason == "target_coverage_gate"), ...
        'test_CCMO_GAN_BDG_target_conditioned:MissingCoverageGateSkipReason', ...
        'Coverage-gated global-ND variant must skip trainable but under-covered CGAN generations.');
    gated = Core.skip_reason == "target_coverage_gate";
    assert(all(Core.refresh_flag(gated) == 0), ...
        'test_CCMO_GAN_BDG_target_conditioned:BadCoverageGateRefreshFlag', ...
        'Coverage-gated skipped generations must not refresh the GAN.');
end

function Obj = PIAObjsDominating(AFObj,AIObj)
    Obj = min(double(AIObj),double(AFObj) - 1e-3);
end

function restoreExperimentControl(controlName,hadOldControl,oldControl)
    if hadOldControl
        setappdata(0,controlName,oldControl);
    elseif isappdata(0,controlName)
        rmappdata(0,controlName);
    end
end

function assertFullscopeRunnerAllowsOnlyCurrentTargetModes(rootDir)
    mainFile = fullfile(rootDir,'Algorithms', ...
        'Multi-objective optimization','CCMO-GAN-BDG','CCMO_GAN_BDG.m');
    ganFile = fullfile(rootDir,'Algorithms', ...
        'Multi-objective optimization','CCMO-GAN-BDG','BoundaryGAN_BDG.m');
    runnerFile = fullfile(rootDir,'Algorithms', ...
        'Multi-objective optimization','CCMO-GAN-BDG','Support', ...
        'run_CCMO_GAN_BDG_archive_pareto_filters_fullscope.m');
    joined = string(fileread(mainFile)) + newline + ...
        string(fileread(ganFile)) + newline + string(fileread(runnerFile));

    required = ["C0_z4_iter50_g1_full", ...
        "C4_condFilter", ...
        "C4_keep90", ...
        "C4_keep80", ...
        "C4_keep60", ...
        "GND_keep80", ...
        "GND_keep80_nGen50", ...
        "GND_keep80_nGen20", ...
        "GND_keep80_localMAD_nGen50", ...
        "GND_keep80_localMAD_nGen20", ...
        "GND_keep80_covGate", ...
        "Rand_keep70", ...
        "Rand_keep80", ...
        "C5_aiDomOnlyTrain", ...
        "C6_refToken", ...
        "C7_boundaryQualityEval", ...
        "U4_noCap_dir_neighbor4", ...
        "U4_noCap_dir_neighbor4_cgan", ...
        "objective_target_conditioned", ...
        "objective_target_unconditioned", ...
        "target_conditioned", ...
        "conditional_adversarial", ...
        "condition_knn", ...
        "local_mad_weight", ...
        "random_keep", ...
        "Control.conditionKNNRetainRatio", ...
        "Control.cganTrainMinRefCov", ...
        "Control.cganTrainMinTargetTriples", ...
        "target_coverage_gate", ...
        "ai_dom_only", ...
        "yt_dt_ref", ...
        "boundary_quality_eval"];
    for i = 1 : numel(required)
        assert(contains(joined,required(i)), ...
            'test_CCMO_GAN_BDG_target_conditioned:MissingTargetModeToken', ...
            'Target-conditioned mode token "%s" must be wired.',required(i));
    end

    forbidden = ["pair_boundary_generated_labeled", ...
        "pair_boundary_generated_outside_penalty", ...
        "pair_boundary_quality", ...
        "pair_boundary_quality_generated", ...
        "critic_regression", ...
        "decision_segment", ...
        "decisionSegmentWeight", ...
        "criticGeneratedLabelData"];
    for i = 1 : numel(forbidden)
        assert(~contains(joined,forbidden(i)), ...
            'test_CCMO_GAN_BDG_target_conditioned:DeprecatedScalarBranchStillReachable', ...
            'Deprecated scalar target branch token "%s" must be removed.', ...
            forbidden(i));
    end
end

function assertTargetUnconditionedVariantUsesUnconditionalGAN(rootDir)
    runnerFile = fullfile(rootDir,'Algorithms', ...
        'Multi-objective optimization','CCMO-GAN-BDG','Support', ...
        'run_CCMO_GAN_BDG_archive_pareto_filters_fullscope.m');
    runnerText = fileread(runnerFile);
    expected = ["U4_noCap_dir_neighbor4", ...
        "ref_af_nd", ...
        "af_not_dominates_ai", ...
        "none", ...
        "neighbor4", ...
        "objective_target_unconditioned", ...
        "af_like", ...
        "adversarial"];

    assert(all(contains(string(runnerText),expected)), ...
        'test_CCMO_GAN_BDG_target_conditioned:BadTargetUnconditionedVariant', ...
        ['U4_noCap_dir_neighbor4 must configure a true target-unconditioned ', ...
        'GAN: G(z), D(x), adversarial loss, and no conditionData.']);
end
