function test_CCMO_GAN_BDG_metrics()
% Regression test for CCMO_GAN_BDG boundary/GAN metric persistence.

    rootDir = fileparts(which('platemo'));
    addpath(genpath(rootDir));

    rng(1,'twister');
    Algorithm = CCMO_GAN_BDG( ...
        'save',0, ...
        'run',1, ...
        'outputFcn',@(varargin)[], ...
        'parameter',{1,4,1,1,1,2,1,1,0.15,1,4,4,0.25,1,1,20,0.45,4,0.25,1,30});
    Problem = DASCMOP1_BC('N',10,'D',30,'maxFE',180);
    Algorithm.Solve(Problem);

    assert(isfield(Algorithm.metric,'analysis_folder'), ...
        'test_CCMO_GAN_BDG_metrics:MissingAnalysisFolder', ...
        'Algorithm.metric.analysis_folder is required.');
    assert(isfield(Algorithm.metric,'analysis_core_csv'), ...
        'test_CCMO_GAN_BDG_metrics:MissingCoreCsv', ...
        'Algorithm.metric.analysis_core_csv is required.');
    assert(isfile(Algorithm.metric.analysis_core_csv), ...
        'test_CCMO_GAN_BDG_metrics:CoreCsvMissing', ...
        'core_metrics.csv was not written.');
    assert(isfile(fullfile(Algorithm.metric.analysis_folder,'run_meta.csv')), ...
        'test_CCMO_GAN_BDG_metrics:MetaCsvMissing', ...
        'run_meta.csv was not written.');

    Core = readtable(Algorithm.metric.analysis_core_csv,'TextType','string');
    Required = {'gen','FE','AF_size','AI_size','Gap_obj_med','Gap_dec_med', ...
        'Ref_cov','refresh_flag','skip_reason', ...
        'AF_candidate_count','AF_retention_ratio', ...
        'AF_front1_count','AF_front1_ratio','AF_kept_front1_ratio', ...
        'score_gap_obj_med','score_gap_dec_med','score_conv_med','score_rank_med', ...
        'pair_count_flip','pair_count_cross','pair_count_self', ...
        'pair_eval_count','pair_eval_FE', ...
        'Raw_count','Raw_feasible_count','Raw_hit_count', ...
        'Raw_minAI_dist_med','Raw_minAI_dist_p10', ...
        'Raw_minAF_dist_med','Raw_FR','Raw_BHR','Raw_BHR_cond','Repair_rate', ...
        'AF_core_train_mode','AF_core_size','AF_core_ref_cov', ...
        'AF_core_gap_obj_med','AF_core_gap_dec_med','AF_core_score_med', ...
        'AF_core_front1_ratio','AF_core_dec_weight', ...
        'AF_bank_mode','AF_bank_size','AF_bank_ref_cov', ...
        'AF_bank_gap_obj_med','AF_bank_gap_dec_med','AF_bank_score_med', ...
        'AF_bank_front1_ratio','AF_bank_cap', ...
        'AF_replay_count','AF_replay_hit1','AF_replay_hit2','AF_replay_hit3', ...
        'AF_replay_BHR1','AF_replay_BHR2','AF_replay_BHR3', ...
        'AF_replay_minAI_obj_med', ...
        'AF_oracle_count','AF_oracle_FE','AF_oracle_FR', ...
        'AF_oracle_hit1','AF_oracle_hit2','AF_oracle_hit3', ...
        'AF_oracle_BHR1','AF_oracle_BHR2','AF_oracle_BHR3', ...
        'AF_oracle_BHR_cond1','AF_oracle_BHR_cond2','AF_oracle_BHR_cond3', ...
        'AF_oracle_minAI_obj_med','AF_oracle_minAI_dec_med', ...
        'AF_oracle_minAF_dec_med', ...
        'AF_jitter_count','AF_jitter_FE','AF_jitter_FR', ...
        'AF_jitter_hit1','AF_jitter_hit2','AF_jitter_hit3', ...
        'AF_jitter_BHR_cond1','AF_jitter_BHR_cond2','AF_jitter_BHR_cond3', ...
        'AF_jitter_minAI_obj_med', ...
        'Probe_Raw_count','Probe_Raw_FE','Probe_Raw_FR', ...
        'Probe_Raw_hit1','Probe_Raw_hit2','Probe_Raw_hit3', ...
        'Probe_Raw_BHR_cond1','Probe_Raw_BHR_cond2','Probe_Raw_BHR_cond3', ...
        'Probe_Raw_minAI_dist_obj_med','Probe_Raw_minAI_dist_dec_med', ...
        'Probe_Raw_minAF_dist_dec_med'};
    Missing = setdiff(Required,Core.Properties.VariableNames);
    assert(isempty(Missing), ...
        'test_CCMO_GAN_BDG_metrics:MissingColumns', ...
        'Missing metric columns: %s', strjoin(Missing, ', '));
    assert(height(Core) >= 1, ...
        'test_CCMO_GAN_BDG_metrics:NoMetricRows', ...
        'At least one metric row is expected.');
    RefreshCore = Core(Core.refresh_flag == 1,:);
    SkippedCore = Core(Core.refresh_flag == 0,:);
    assert(all(Core.AF_size >= 0), ...
        'test_CCMO_GAN_BDG_metrics:InvalidAFSize', ...
        'AF_size must be nonnegative.');
    assert(all(Core.Ref_cov >= 0 & Core.Ref_cov <= 1), ...
        'test_CCMO_GAN_BDG_metrics:InvalidRefCov', ...
        'Ref_cov must be in [0,1].');
    assert(~isempty(RefreshCore), ...
        'test_CCMO_GAN_BDG_metrics:NoRefreshRows', ...
        'At least one row should correspond to an actual GAN refresh.');
    assert(all(RefreshCore.Raw_FR >= 0 & RefreshCore.Raw_FR <= 1), ...
        'test_CCMO_GAN_BDG_metrics:InvalidRawFR', ...
        'Raw_FR must be in [0,1] on refresh rows.');
    assert(all(RefreshCore.Raw_BHR >= 0 & RefreshCore.Raw_BHR <= 1), ...
        'test_CCMO_GAN_BDG_metrics:InvalidRawBHR', ...
        'Raw_BHR must be in [0,1] on refresh rows.');
    assert(all(RefreshCore.Repair_rate >= 0 & RefreshCore.Repair_rate <= 1), ...
        'test_CCMO_GAN_BDG_metrics:InvalidRepairRate', ...
        'Repair_rate must be in [0,1] on refresh rows.');
    assert(all(Core.pair_eval_FE >= 0), ...
        'test_CCMO_GAN_BDG_metrics:InvalidPairEvalFE', ...
        'pair_eval_FE must be nonnegative.');
    assert(all(Core.AF_candidate_count >= 0), ...
        'test_CCMO_GAN_BDG_metrics:InvalidAFCandidateCount', ...
        'AF_candidate_count must be nonnegative.');
    assert(all(Core.AF_front1_count >= 0), ...
        'test_CCMO_GAN_BDG_metrics:InvalidAFFront1Count', ...
        'AF_front1_count must be nonnegative.');
    assert(all(Core.AF_front1_count <= Core.AF_candidate_count), ...
        'test_CCMO_GAN_BDG_metrics:AFFront1ExceedsCandidate', ...
        'AF_front1_count must not exceed AF_candidate_count.');
    finiteRetention = Core.AF_retention_ratio(isfinite(Core.AF_retention_ratio));
    assert(all(finiteRetention >= 0 & finiteRetention <= 1), ...
        'test_CCMO_GAN_BDG_metrics:InvalidAFRetentionRatio', ...
        'AF_retention_ratio must be in [0,1] when finite.');
    assertFiniteUnitColumn(Core,'AF_front1_ratio');
    assertFiniteUnitColumn(Core,'AF_kept_front1_ratio');
    assertFiniteNonnegativeColumn(Core,'score_gap_obj_med');
    assertFiniteNonnegativeColumn(Core,'score_gap_dec_med');
    assertFiniteNonnegativeColumn(Core,'score_conv_med');
    assertFiniteNonnegativeColumn(Core,'score_rank_med');
    assert(all(Core.Raw_feasible_count >= 0), ...
        'test_CCMO_GAN_BDG_metrics:InvalidRawFeasibleCount', ...
        'Raw_feasible_count must be nonnegative.');
    assert(all(Core.Raw_feasible_count <= Core.Raw_count), ...
        'test_CCMO_GAN_BDG_metrics:RawFeasibleExceedsRawCount', ...
        'Raw_feasible_count must not exceed Raw_count.');
    assert(all(Core.Raw_hit_count >= 0), ...
        'test_CCMO_GAN_BDG_metrics:InvalidRawHitCount', ...
        'Raw_hit_count must be nonnegative.');
    assert(all(Core.Raw_hit_count <= Core.Raw_count), ...
        'test_CCMO_GAN_BDG_metrics:RawHitExceedsRawCount', ...
        'Raw_hit_count must not exceed Raw_count.');
    assert(all(Core.Raw_hit_count <= Core.Raw_feasible_count), ...
        'test_CCMO_GAN_BDG_metrics:RawHitExceedsRawFeasible', ...
        'Raw_hit_count must not exceed Raw_feasible_count.');
    assert(all(Core.AF_core_train_mode == 1), ...
        'test_CCMO_GAN_BDG_metrics:InvalidAFCoreTrainMode', ...
        'AF_core_train_mode should record enabled AF-core training.');
    assertNonnegativeIntegerColumn(Core,'AF_core_size');
    assert(all(Core.AF_core_size <= Core.AF_size), ...
        'test_CCMO_GAN_BDG_metrics:AFCoreExceedsAF', ...
        'AF_core_size must not exceed AF_size.');
    assertFiniteUnitColumn(Core,'AF_core_ref_cov');
    assertFiniteUnitColumn(Core,'AF_core_front1_ratio');
    assertFiniteNonnegativeColumn(Core,'AF_core_gap_obj_med');
    assertFiniteNonnegativeColumn(Core,'AF_core_gap_dec_med');
    assertFiniteNonnegativeColumn(Core,'AF_core_score_med');
    assert(all(Core.AF_core_dec_weight == 0.45), ...
        'test_CCMO_GAN_BDG_metrics:InvalidAFCoreDecWeight', ...
        'AF_core_dec_weight should record the configured decision-gap weight.');
    assert(all(Core.AF_bank_mode == 1), ...
        'test_CCMO_GAN_BDG_metrics:InvalidAFBankMode', ...
        'AF_bank_mode should record enabled AF-core bank training.');
    assertNonnegativeIntegerColumn(Core,'AF_bank_size');
    assert(all(Core.AF_bank_size <= 30), ...
        'test_CCMO_GAN_BDG_metrics:AFBankExceedsCap', ...
        'AF_bank_size must not exceed the configured AF_bank_cap.');
    assertFiniteUnitColumn(Core,'AF_bank_ref_cov');
    assertFiniteUnitColumn(Core,'AF_bank_front1_ratio');
    assertFiniteNonnegativeColumn(Core,'AF_bank_gap_obj_med');
    assertFiniteNonnegativeColumn(Core,'AF_bank_gap_dec_med');
    assertFiniteNonnegativeColumn(Core,'AF_bank_score_med');
    assert(all(Core.AF_bank_cap == 30), ...
        'test_CCMO_GAN_BDG_metrics:InvalidAFBankCap', ...
        'AF_bank_cap should record the configured bank capacity.');
    finiteRawBHRCond = RefreshCore.Raw_BHR_cond(isfinite(RefreshCore.Raw_BHR_cond));
    assert(all(finiteRawBHRCond >= 0 & finiteRawBHRCond <= 1), ...
        'test_CCMO_GAN_BDG_metrics:InvalidRawBHRCond', ...
        'Raw_BHR_cond must be in [0,1] when finite.');
    assertNonnegativeIntegerColumn(Core,'AF_replay_count');
    assertNonnegativeIntegerColumn(Core,'AF_replay_hit1');
    assertNonnegativeIntegerColumn(Core,'AF_replay_hit2');
    assertNonnegativeIntegerColumn(Core,'AF_replay_hit3');
    assertMonotoneHitColumns(Core,'AF_replay_hit1','AF_replay_hit2','AF_replay_hit3');
    assertFiniteUnitColumn(Core,'AF_replay_BHR1');
    assertFiniteUnitColumn(Core,'AF_replay_BHR2');
    assertFiniteUnitColumn(Core,'AF_replay_BHR3');
    assertNonnegativeIntegerColumn(Core,'AF_oracle_count');
    assertNonnegativeIntegerColumn(Core,'AF_oracle_FE');
    assertNonnegativeIntegerColumn(Core,'AF_oracle_hit1');
    assertNonnegativeIntegerColumn(Core,'AF_oracle_hit2');
    assertNonnegativeIntegerColumn(Core,'AF_oracle_hit3');
    assertMonotoneHitColumns(Core,'AF_oracle_hit1','AF_oracle_hit2','AF_oracle_hit3');
    assertFiniteUnitColumn(Core,'AF_oracle_FR');
    assertFiniteUnitColumn(Core,'AF_oracle_BHR1');
    assertFiniteUnitColumn(Core,'AF_oracle_BHR2');
    assertFiniteUnitColumn(Core,'AF_oracle_BHR3');
    assertFiniteUnitColumn(Core,'AF_oracle_BHR_cond1');
    assertFiniteUnitColumn(Core,'AF_oracle_BHR_cond2');
    assertFiniteUnitColumn(Core,'AF_oracle_BHR_cond3');
    assertNonnegativeIntegerColumn(Core,'AF_jitter_count');
    assertNonnegativeIntegerColumn(Core,'AF_jitter_FE');
    assertNonnegativeIntegerColumn(Core,'AF_jitter_hit1');
    assertNonnegativeIntegerColumn(Core,'AF_jitter_hit2');
    assertNonnegativeIntegerColumn(Core,'AF_jitter_hit3');
    assertMonotoneHitColumns(Core,'AF_jitter_hit1','AF_jitter_hit2','AF_jitter_hit3');
    assertFiniteUnitColumn(Core,'AF_jitter_FR');
    assertFiniteUnitColumn(Core,'AF_jitter_BHR_cond1');
    assertFiniteUnitColumn(Core,'AF_jitter_BHR_cond2');
    assertFiniteUnitColumn(Core,'AF_jitter_BHR_cond3');
    assertNonnegativeIntegerColumn(Core,'Probe_Raw_count');
    assertNonnegativeIntegerColumn(Core,'Probe_Raw_FE');
    assertNonnegativeIntegerColumn(Core,'Probe_Raw_hit1');
    assertNonnegativeIntegerColumn(Core,'Probe_Raw_hit2');
    assertNonnegativeIntegerColumn(Core,'Probe_Raw_hit3');
    assertMonotoneHitColumns(Core,'Probe_Raw_hit1','Probe_Raw_hit2','Probe_Raw_hit3');
    assertFiniteUnitColumn(Core,'Probe_Raw_FR');
    assertFiniteUnitColumn(Core,'Probe_Raw_BHR_cond1');
    assertFiniteUnitColumn(Core,'Probe_Raw_BHR_cond2');
    assertFiniteUnitColumn(Core,'Probe_Raw_BHR_cond3');
    assert(any(RefreshCore.AF_jitter_count > 0), ...
        'test_CCMO_GAN_BDG_metrics:MissingAFJitterProbe', ...
        'Enabled diagnostic run should record AF jitter samples.');
    assert(any(RefreshCore.AF_oracle_count > 0), ...
        'test_CCMO_GAN_BDG_metrics:MissingAFOracleProbe', ...
        'Enabled diagnostic run should record AF oracle samples.');
    assert(any(RefreshCore.Probe_Raw_count > 0), ...
        'test_CCMO_GAN_BDG_metrics:MissingRawProbe', ...
        'Enabled diagnostic run should record GAN raw probe samples.');
    assert(all(Core.pair_eval_count == Core.pair_eval_FE), ...
        'test_CCMO_GAN_BDG_metrics:PairEvalMismatch', ...
        'pair_eval_count and pair_eval_FE should match for scalar bisection evaluations.');
    assertNonnegativeIntegerColumn(Core,'pair_count_flip');
    assertNonnegativeIntegerColumn(Core,'pair_count_cross');
    assertNonnegativeIntegerColumn(Core,'pair_count_self');
    if ~isempty(SkippedCore)
        assert(all(SkippedCore.Raw_count == 0), ...
            'test_CCMO_GAN_BDG_metrics:SkippedRowsHaveRawCount', ...
            'Skipped rows should have Raw_count == 0.');
        assert(all(SkippedCore.Raw_hit_count == 0), ...
            'test_CCMO_GAN_BDG_metrics:SkippedRowsHaveRawHits', ...
            'Skipped rows should have Raw_hit_count == 0.');
        assert(all(SkippedCore.Raw_feasible_count == 0), ...
            'test_CCMO_GAN_BDG_metrics:SkippedRowsHaveRawFeasible', ...
            'Skipped rows should have Raw_feasible_count == 0.');
        assert(all(strlength(SkippedCore.skip_reason) > 0), ...
            'test_CCMO_GAN_BDG_metrics:SkippedRowsMissingReason', ...
            'Skipped rows should include a skip_reason.');
        assert(all(isnan(SkippedCore.Raw_FR) & isnan(SkippedCore.Raw_BHR) & ...
                isnan(SkippedCore.Raw_BHR_cond) & isnan(SkippedCore.Repair_rate)), ...
            'test_CCMO_GAN_BDG_metrics:SkippedRowsHaveRawRates', ...
            'Skipped rows should leave raw rate metrics as NaN.');
    end

    rng(2,'twister');
    SkipAlgorithm = CCMO_GAN_BDG( ...
        'save',0, ...
        'run',2, ...
        'outputFcn',@(varargin)[], ...
        'parameter',{1,4,999,1,1,2,1,1,0.15,1});
    SkipProblem = DASCMOP1_BC('N',10,'D',30,'maxFE',80);
    SkipAlgorithm.Solve(SkipProblem);

    SkipCore = readtable(SkipAlgorithm.metric.analysis_core_csv,'TextType','string');
    Missing = setdiff(Required,SkipCore.Properties.VariableNames);
    assert(isempty(Missing), ...
        'test_CCMO_GAN_BDG_metrics:MissingSkipColumns', ...
        'Missing skip metric columns: %s', strjoin(Missing, ', '));
    assert(height(SkipCore) >= 1, ...
        'test_CCMO_GAN_BDG_metrics:NoSkipRows', ...
        'Rows must be written even when GAN training is skipped.');
    assert(all(SkipCore.refresh_flag == 0), ...
        'test_CCMO_GAN_BDG_metrics:UnexpectedSkipRefresh', ...
        'High minTrain test should only write skipped rows.');
    assert(any(SkipCore.skip_reason == "AF_below_minTrain"), ...
        'test_CCMO_GAN_BDG_metrics:MissingSkipReason', ...
        'Skipped rows should explain that AF is below minTrain.');
    assert(all(SkipCore.Raw_count == 0 & SkipCore.Raw_feasible_count == 0 & ...
            SkipCore.Raw_hit_count == 0), ...
        'test_CCMO_GAN_BDG_metrics:InvalidSkipRawCounts', ...
        'Forced skipped rows should not contain raw GAN samples.');
    assert(all(SkipCore.AF_core_size <= SkipCore.AF_size), ...
        'test_CCMO_GAN_BDG_metrics:InvalidSkipAFCoreSize', ...
        'Skipped rows should still keep AF_core_size within AF_size.');
    assert(all(SkipCore.AF_oracle_count == 0 & SkipCore.AF_jitter_count == 0 & ...
            SkipCore.Probe_Raw_count == 0), ...
        'test_CCMO_GAN_BDG_metrics:InvalidSkipProbeCounts', ...
        'Forced skipped rows should not contain oracle, jitter, or GAN probe samples.');
    assert(all(isnan(SkipCore.Raw_FR) & isnan(SkipCore.Raw_BHR) & ...
            isnan(SkipCore.Raw_BHR_cond) & isnan(SkipCore.Repair_rate)), ...
        'test_CCMO_GAN_BDG_metrics:InvalidSkipRawRates', ...
        'Forced skipped rows should leave raw rate metrics as NaN.');
end

function assertNonnegativeIntegerColumn(T,name)
    values = T.(name);
    assert(all(values >= 0 & floor(values) == values), ...
        'test_CCMO_GAN_BDG_metrics:InvalidIntegerColumn', ...
        '%s must contain nonnegative integers.', name);
end

function assertFiniteUnitColumn(T,name)
    values = T.(name);
    values = values(isfinite(values));
    assert(all(values >= 0 & values <= 1), ...
        'test_CCMO_GAN_BDG_metrics:InvalidUnitColumn', ...
        '%s must be in [0,1] when finite.', name);
end

function assertFiniteNonnegativeColumn(T,name)
    values = T.(name);
    values = values(isfinite(values));
    assert(all(values >= 0), ...
        'test_CCMO_GAN_BDG_metrics:InvalidNonnegativeColumn', ...
        '%s must be nonnegative when finite.', name);
end

function assertMonotoneHitColumns(T,name1,name2,name3)
    hit1 = T.(name1);
    hit2 = T.(name2);
    hit3 = T.(name3);
    assert(all(hit1 <= hit2 & hit2 <= hit3), ...
        'test_CCMO_GAN_BDG_metrics:InvalidHitMonotonicity', ...
        '%s <= %s <= %s is required.', name1, name2, name3);
end
