function test_CBS_pair_guide()
%TEST_CBS_PAIR_GUIDE Verify the PairGuide mechanism contract.

    repoRoot = fileparts(which('platemo'));
    addCBSPaths(repoRoot);
    addpath(fullfile(repoRoot,'Problems','Multi-objective optimization', ...
        'LIR-CMOP_BC'),'-begin');

    %% Own identity, locked schedule, and stable schema
    Algorithm = PairGuide( ...
        'save',0,'outputFcn',@(varargin)[]);
    Problem = DASCMOP1_BC('N',2,'D',5,'maxFE',1);
    rng(910,'twister');
    Algorithm.Solve(Problem);
    Snapshot = Algorithm.guideExperimentSnapshot();
    assert(Snapshot.arm == 7 && ...
        Snapshot.generationMode == "pair_guide" && ...
        Snapshot.useMode == "pair_guide" && ...
        Snapshot.pairGanEpoch == 500 && ...
        Snapshot.pairInitialEpoch == 500 && ...
        Snapshot.pairRetrainEpoch == 20 && ...
        Snapshot.nCritic == 5 && ...
        Snapshot.guideOffspringShare == 0.20 && ...
        Snapshot.pairGuideSchema == "PairGuide" && ...
        isinf(Snapshot.cganEndTarget) && isa(Algorithm,'PairGuide'));

    %% Archive: globally illegal xi is excluded; every ref owns one pair
    Problem = LIRCMOP5_BC('N',4,'D',2,'maxFE',100);
    W = twoObjectiveWeights(5);
    Options = pairOptions(2,10);
    xf = [0.10 0.10;0.90 0.90];
    yf = [0 1;1 0];
    legalXi = [0.45 0.55];
    legalYi = [0.50 0.50];
    dominatedXi = [0.11 0.10;0.89 0.90];
    dominatedYi = [2 2;1.5 1.5];
    P1 = SOLUTION(xf,yf,zeros(2,1));
    Infeasible = SOLUTION([dominatedXi;legalXi], ...
        [dominatedYi;legalYi],ones(3,1));
    [Archive,~] = PairBoundaryArchive_RC('update',[],P1, ...
        [P1,Infeasible],W,Problem,Options,struct(),100);
    assert(~isempty(Archive.id) && all(Archive.active) && ...
        all(Archive.resumeEligible));
    assert(numel(unique(Archive.ref)) == numel(Archive.ref));
    assert(~containsDecision(Archive.xi,dominatedXi(1,:)) && ...
        ~containsDecision(Archive.xi,dominatedXi(2,:)) && ...
        containsDecision(Archive.xi,legalXi));
    for row = 1 : size(Archive.yi,1)
        assert(~any(rowDominates(yf,repmat(Archive.yi(row,:),2,1))));
    end
    [Data,Gate,TrainC,QueryRefs,BMem] = ...
        PairBoundaryArchive_RC('trainingdata', ...
        Archive,W,Problem,Options);
    assert(Data.count == numel(unique(Data.ref)) && ...
        Data.count == Gate.regions && Gate.eligible && ...
        isequal(QueryRefs,Data.ref) && ...
        size(TrainC,1) == 2*Data.count && ...
        all(TrainC(1:Data.count,end) == 1) && ...
        all(TrainC(Data.count+1:end,end) == 0) && ...
        numel(unique(BMem.ref)) == numel(BMem.ref));

    % A historical xi dominated by a current feasible elite cannot remain
    % active or enter training, even when its xf still has local support.
    Illegal = makeArchive(xf(1,:),dominatedXi(1,:), ...
        yf(1,:),dominatedYi(1,:),1);
    [Illegal,~] = PairBoundaryArchive_RC('update',Illegal,P1,P1, ...
        W,Problem,Options,struct(),200);
    [IllegalData,IllegalGate] = PairBoundaryArchive_RC( ...
        'trainingdata',Illegal,W,Problem,Options);
    assert(~any(Illegal.active) && IllegalData.count == 0 && ...
        ~IllegalGate.eligible);

    % Local P1 support alone keeps a legal pair active without pretending
    % that a new endpoint observation arrived.
    Stable = makeArchive(xf(1,:),legalXi,yf(1,:),legalYi,1);
    Stable.lastFE = 123;
    StableP1 = SOLUTION(xf(1,:),yf(1,:),0);
    StableUnion = [StableP1,SOLUTION(legalXi,legalYi,1)];
    [Stable,~] = PairBoundaryArchive_RC('update',Stable,StableP1, ...
        StableUnion,W,Problem,Options,struct(),999);
    assert(isscalar(Stable.id) && Stable.active && ...
        Stable.lastFE == 123);

    % A legal exact pair may pause for lack of P1 support and later resume
    % under the same ID without pretending that its endpoints changed.
    LifecycleW = twoObjectiveWeights(11);
    lifecycleXf = [0.10 0.10];
    lifecycleXi = [0.45 0.55];
    lifecycleYf = [0 1];
    lifecycleYi = [0.10 0.90];
    Paused = makeArchive(lifecycleXf,lifecycleXi, ...
        lifecycleYf,lifecycleYi,1);
    Paused.lastFE = 123;
    FarP1 = SOLUTION([0.95 0.95],[1 0],0);
    VerticalInfeasible = SOLUTION([1 1],[0 1],1);
    [Paused,~] = PairBoundaryArchive_RC('update',Paused,FarP1, ...
        [FarP1,VerticalInfeasible],LifecycleW,Problem,Options,struct(),200);
    assert(isscalar(Paused.id) && Paused.id == 1 && ...
        ~Paused.active && Paused.resumeEligible && Paused.age == 1 && ...
        Paused.nextId == 2);
    ResumingP1 = SOLUTION(lifecycleXf,lifecycleYf,0);
    HorizontalInfeasible = SOLUTION([1 1],[1 0],1);
    [Resumed,~] = PairBoundaryArchive_RC('update',Paused,ResumingP1, ...
        [ResumingP1,HorizontalInfeasible],LifecycleW,Problem,Options, ...
        struct(),300);
    assert(isscalar(Resumed.id) && Resumed.id == 1 && ...
        Resumed.active && Resumed.resumeEligible && ...
        Resumed.lastFE == 123 && Resumed.nextId == 2);

    % Once objective legality is lost, the retained row cannot resume in
    % place. A later reconstruction receives a new ID and observation FE.
    Invalidated = makeArchive(lifecycleXf,lifecycleXi, ...
        lifecycleYf,lifecycleYi,1);
    Invalidated.lastFE = 123;
    DominatingP1 = SOLUTION([0.20 0.20],[0 0],0);
    [Invalidated,~] = PairBoundaryArchive_RC('update',Invalidated, ...
        DominatingP1,DominatingP1,LifecycleW,Problem,Options,struct(),400);
    assert(isscalar(Invalidated.id) && Invalidated.id == 1 && ...
        ~Invalidated.active && ~Invalidated.resumeEligible && ...
        Invalidated.nextId == 2);
    [Rebuilt,~] = PairBoundaryArchive_RC('update',Invalidated, ...
        ResumingP1,[ResumingP1,HorizontalInfeasible],LifecycleW,Problem, ...
        Options,struct(),500);
    assert(isscalar(Rebuilt.id) && Rebuilt.id == 2 && Rebuilt.active && ...
        Rebuilt.resumeEligible && Rebuilt.lastFE == 500 && ...
        Rebuilt.nextId == 3);

    % A condition reassociation without a new endpoint observation also
    % starts a new ID rather than silently changing an old CGAN condition.
    Reassociated = makeArchive(lifecycleXf,lifecycleXi, ...
        lifecycleYf,lifecycleYi,size(LifecycleW,1));
    Reassociated.lastFE = 123;
    [Reassociated,~] = PairBoundaryArchive_RC('update',Reassociated, ...
        ResumingP1,[ResumingP1,HorizontalInfeasible],LifecycleW,Problem, ...
        Options,struct(),600);
    assert(isscalar(Reassociated.id) && Reassociated.id == 2 && ...
        Reassociated.ref == 1 && Reassociated.active && ...
        Reassociated.lastFE == 600 && Reassociated.nextId == 3);

    %% Query metadata: 500 randomized rows, balanced and ID/ref aligned
    rng(913,'twister');
    [QueryC,Info] = PairBoundaryArchive_RC( ...
        'querycontexts',Archive,W,Options,500);
    assert(size(QueryC,1) == 500 && all(QueryC(:,end) == 0) && ...
        numel(Info.refs) == 500 && numel(Info.pairIds) == 500);
    archiveRows = arrayfun(@(id)find(Archive.id == id,1),Info.pairIds);
    assert(isequal(Info.refs,Archive.ref(archiveRows)) && ...
        max(abs(QueryC(:,1:end-1)-W(Info.refs,:)),[],'all') <= 1e-12);
    queryIds = unique(Info.pairIds,'stable');
    queryCounts = arrayfun(@(id)nnz(Info.pairIds == id),queryIds);
    assert(numel(queryIds) == nnz(Archive.active) && ...
        max(queryCounts)-min(queryCounts) <= 1 && ...
        nnz(diff(Info.pairIds) ~= 0) > 1);

    %% Angular neighborhood is exactly five; midpoint is deterministic
    theta = linspace(0,pi/2,7)';
    W7 = [cos(theta),sin(theta)];
    pairRef = 4;
    order = angularOrder(W7,pairRef);
    allowedRef = order(5);
    excludedRef = order(6);
    assert(~ismember(excludedRef,order(1:5)));
    pairXf = [0.20 0.20];
    pairXi = [0.80 0.80];
    FeasDecs = [0.25 0.20;pairXf];
    feasRefs = [allowedRef;excludedRef];
    feasFitness = [0.1;0.1];
    PairBMem = struct('id',1,'x_b',pairXf,'x_i',pairXi, ...
        'y_b',[0 1],'y_i',[1 0],'ref',pairRef, ...
        'gap',norm(pairXi-pairXf),'active',true,'lastFE',0);
    Config = PairGuideCore.mainlineDefaults();
    Config.pairNeighborRefCount = 5;
    Config.pairDuplicateTolerance = 1e-8;
    expectedChild = 0.5*(FeasDecs(1,:)+pairXi);
    rng(914,'twister');
    beforeRNG = rng;
    [ChildDecs,parentRows,selectedRefs,Map,matchedIds] = ...
        PairGuideCore.pairGuideDecisionTestHook( ...
        Problem,FeasDecs,feasRefs,feasFitness,pairXi,pairRef,1, ...
        W7,1,PairBMem,Config,FeasDecs);
    afterRNG = rng;
    pairGap = norm(pairXi-pairXf);
    assert(isequaln(beforeRNG,afterRNG) && parentRows == 1 && ...
        selectedRefs == pairRef && matchedIds == 1 && ...
        max(abs(ChildDecs-expectedChild),[],'all') <= 1e-12 && ...
        Map.rho < 1 && ...
        norm(ChildDecs-pairXf) < pairGap && ...
        norm(ChildDecs-pairXi) < pairGap && ...
        abs(Map.centerStep-Map.actualStep) <= 1e-12 && ...
        abs(Map.directionCosine-1) <= 1e-12);

    % Duplicate filtering occurs only after midpoint construction, against P1.
    [DuplicateChild,~,~,DuplicateMap,~] = ...
        PairGuideCore.pairGuideDecisionTestHook( ...
        Problem,FeasDecs,feasRefs,feasFitness,pairXi,pairRef,1, ...
        W7,1,PairBMem,Config,[FeasDecs;expectedChild]);
    assert(isempty(DuplicateChild) && DuplicateMap.validCount == 0);

    %% Candidate gates: raw G may equal xi; no global feasible filter for G
    CandidateProblem = LIRCMOP5_BC('N',10,'D',2,'maxFE',100);
    g = [0.80 0.80];
    gObj = CandidateProblem.CalObj(g);
    globallyDominatingElite = gObj-[1 1];
    assert(rowDominates(globallyDominatingElite,gObj));
    [Selected,~,Matched,Trace] = selectSingleCandidate( ...
        CandidateProblem,g,gObj,gObj,globallyDominatingElite, ...
        pairOptions(1,2));
    assert(isequal(Selected,g) && Matched == 1 && ...
        Trace.keptCount == 1 && Trace.objectiveFE == 1 && ...
        Trace.constraintFE == 0 && Trace.selectedRho == 0);

    % Local rule 1: g must not dominate paired xi.
    [Selected,~,~,Trace] = selectSingleCandidate( ...
        CandidateProblem,g,gObj,gObj+[1 1],[],pairOptions(1,2));
    assert(isempty(Selected) && Trace.localDominancePass == 0 && ...
        Trace.corridorPass == 1);

    % Local rule 2: paired xf must not dominate g.
    [Selected,~,~,Trace] = selectSingleCandidate( ...
        CandidateProblem,g,gObj-[1 1],gObj,[],pairOptions(1,2));
    assert(isempty(Selected) && Trace.localDominancePass == 0 && ...
        Trace.corridorPass == 1);

    % Neither local dominance relation is enough: Pareto corridor is required.
    corridorYf = gObj+[-2 1];
    corridorYi = gObj+[-1 -1];
    [Selected,~,~,Trace] = selectSingleCandidate( ...
        CandidateProblem,g,corridorYf,corridorYi,[],pairOptions(1,2));
    assert(isempty(Selected) && Trace.localDominancePass == 1 && ...
        Trace.corridorPass == 0);

    %% One minimum-rho representative per pair, 2Q objective checks, Q donors
    pairCount = 5;
    W5 = twoObjectiveWeights(pairCount);
    Xf = [linspace(0.10,0.50,pairCount)',0.20*ones(pairCount,1)];
    Xi = Xf+0.25;
    Y = CandidateProblem.CalObj(Xi);
    ManyArchive = makeArchive(Xf,Xi,Y,Y,(1:pairCount)');
    Population = SOLUTION(Xf,W5,zeros(pairCount,1));
    Fitness = zeros(pairCount,1);
    Raw = zeros(2*pairCount,2);
    ManyInfo = struct('refs',zeros(2*pairCount,1), ...
        'pairIds',zeros(2*pairCount,1));
    for pair = 1 : pairCount
        Raw(2*pair-1,:) = Xi(pair,:)+[0.05 0];
        Raw(2*pair,:) = Xi(pair,:);
        ManyInfo.refs(2*pair-1:2*pair) = pair;
        ManyInfo.pairIds(2*pair-1:2*pair) = pair;
    end
    Scale = struct('minimum',[0 0],'span',[1 1]);
    ManyOptions = pairOptions(2,10);
    feBefore = CandidateProblem.FE;
    [Selected,SelectedRefs,Matched,Trace] = ...
        PairBoundaryArchive_RC('selectcandidates',Raw,ManyInfo, ...
        ManyArchive,Population,Fitness,W5,Scale, ...
        CandidateProblem,ManyOptions);
    assert(CandidateProblem.FE == feBefore);
    assert(Trace.pairRepresentativeCount == pairCount);
    assert(Trace.objectiveCandidateCount == 4 && Trace.objectiveFE == 4);
    assert(Trace.keptCount == 2 && all(Trace.selectedRho == 0));
    assert(numel(unique(Matched)) == 2 && ...
        isequal(SelectedRefs,ManyArchive.ref(Matched)));
    assert(max(abs(Selected-Xi(Matched,:)),[],'all') <= 1e-12);
    assert(all(mod(Trace.keepIdx,2) == 0));
    LimitedOptions = pairOptions(2,3);
    [~,~,~,LimitedTrace] = PairBoundaryArchive_RC( ...
        'selectcandidates',Raw,ManyInfo,ManyArchive,Population,Fitness, ...
        W5,Scale,CandidateProblem,LimitedOptions);
    assert(LimitedTrace.objectiveCandidateCount == 3 && ...
        LimitedTrace.objectiveFE == 3 && LimitedTrace.keptCount == 2);
    OneObjectiveOptions = pairOptions(2,1);
    [OneSelected,~,~,OneTrace] = PairBoundaryArchive_RC( ...
        'selectcandidates',Raw,ManyInfo,ManyArchive,Population,Fitness, ...
        W5,Scale,CandidateProblem,OneObjectiveOptions);
    assert(size(OneSelected,1) == 1 && ...
        OneTrace.objectiveCandidateCount == 1 && OneTrace.objectiveFE == 1);

    % CalObj itself is deliberately FE-neutral; production consumes Trace.ObjFE.
    coreSource = char(fileread(which('PairGuideCore')));
    assert(~isempty(regexp(coreSource, ...
        'Problem\.FE\s*=\s*Problem\.FE\s*\+\s*PoolTrace\.objectiveFE', ...
        'once')) && contains(coreSource,'withObjectiveBudget'));

    %% Six BC problems: CalObj/CalCon are FE-neutral; Evaluation is consistent
    problemNames = ["LIRCMOP5_BC","LIRCMOP7_BC","LIRCMOP8_BC", ...
        "LIRCMOP10_BC","LIRCMOP12_BC","LIRCMOP14_BC"];
    X = reshape(mod(0:17,10)/10,3,6);
    for name = problemNames
        constructor = str2func(char(name));
        BCProblem = constructor('N',3,'D',6,'maxFE',20);
        startFE = BCProblem.FE;
        expectedObj = BCProblem.CalObj(X);
        expectedCon = BCProblem.CalCon(X);
        assert(BCProblem.FE == startFE && size(expectedObj,1) == 3 && ...
            isequal(size(expectedCon),[3 1]) && ...
            all(expectedCon == 0 | expectedCon == 1,'all'));
        Evaluated = BCProblem.Evaluation(X);
        assert(BCProblem.FE == startFE+3 && ...
            max(abs(double(Evaluated.objs)-expectedObj),[],'all') <= 1e-12 && ...
            isequal(double(Evaluated.cons),expectedCon));
    end

    %% WGAN uses only geometry loss and exposes the new diagnostics
    wganSource = string(fileread(which('PairBoundaryWGAN_RC')));
    removed = ["pairRelationWeight","pairLatentWeight", ...
        "pairLatentThreshold","energyDistanceDL","modeSeeking"];
    for token = removed
        assert(~contains(wganSource,token));
    end
    required = ["pairGeometryWeight","allEndpointRMSE", ...
        "changedEndpointRMSE","pairDifferenceRMSE", ...
        "sameConditionThickness"];
    for token = required
        assert(contains(wganSource,token));
    end
    [~,BlockedStatus] = PairBoundaryWGAN_RC('trainifneeded',[],Data, ...
        struct('eligible',false),Problem,struct('pairMinPairs',1));
    assert(all(isfield(BlockedStatus.preDiagnostics, ...
        {'allEndpointRMSE','changedEndpointRMSE','pairDifferenceRMSE', ...
        'sameConditionThickness','criticGap'})));

    % Execute one tiny autodiff update so the paired geometry loss and
    % repeated-condition thickness diagnostic are covered at runtime.
    SmokeOptions = struct('initialEpoch',1,'retrainEpoch',1, ...
        'miniBatch',4,'nCritic',1,'pairMinPairs',1, ...
        'collectDiagnostics',true,'generatorHidden',[4 4], ...
        'criticHidden',[4 4]);
    [SmokeModel,SmokeStatus] = PairBoundaryWGAN_RC( ...
        'trainifneeded',[],Data,Gate,Problem,SmokeOptions);
    [~,RepeatStatus] = PairBoundaryWGAN_RC( ...
        'trainifneeded',SmokeModel,Data,Gate,Problem,SmokeOptions);
    [SmokeSample,~] = PairBoundaryWGAN_RC('sample',SmokeModel, ...
        Data.cI(1:min(2,Data.count),:),Problem,SmokeOptions);
    Diagnostics = SmokeStatus.postDiagnostics;
    diagnosticValues = [Diagnostics.allEndpointRMSE, ...
        Diagnostics.changedEndpointRMSE, ...
        Diagnostics.pairDifferenceRMSE, ...
        Diagnostics.sameConditionThickness,Diagnostics.criticGap];
    assert(SmokeModel.ready && SmokeStatus.trained && ...
        SmokeStatus.epochs == 1 && ...
        SmokeStatus.pairVisits == Data.count && ...
        SmokeStatus.criticUpdates == SmokeStatus.updates && ...
        ~RepeatStatus.trained && RepeatStatus.reason == "current" && ...
        isequal(size(SmokeSample),[min(2,Data.count),Problem.D]) && ...
        all(isfinite(SmokeSample),'all') && ...
        all(isfinite(diagnosticValues)));

    fprintf('PairGuide mechanism test passed.\n');
end

function Options = pairOptions(quota,objectiveBudget)
%PAIROPTIONS Minimal final PairGuide settings for deterministic unit tests.

    Options = struct('pairArchivePerRef',1,'pairInactiveMaxAge',10, ...
        'pairNeighborRefCount',5,'pairMinPairs',1, ...
        'pairDuplicateTolerance',1e-8, ...
        'pairImprovementTolerance',1e-12, ...
        'guideQuota',quota,'objectiveBudget',objectiveBudget);
end

function W = twoObjectiveWeights(count)
%TWOOBJECTIVEWEIGHTS Ordered nonzero directions on the positive quadrant.

    first = linspace(0,1,count)';
    W = [first,1-first];
end

function Archive = makeArchive(xf,xi,yf,yi,refs)
%MAKEARCHIVE Construct complete pair rows without hiding test intent.

    count = size(xf,1);
    refs = reshape(double(refs),[],1);
    Archive = struct('id',(1:count)','xf',double(xf),'xi',double(xi), ...
        'yf',double(yf),'yi',double(yi),'ref',refs, ...
        'gap',sqrt(sum((double(xi)-double(xf)).^2,2)), ...
        'rank',ones(count,1),'fitness',zeros(count,1), ...
        'age',zeros(count,1),'lastFE',zeros(count,1), ...
        'active',true(count,1),'resumeEligible',true(count,1), ...
        'nextId',count+1);
end

function yes = containsDecision(X,x)
%CONTAINSDECISION Exact-enough row membership for fixed unit-test values.

    yes = ~isempty(X) && any(all(abs(double(X)-double(x)) <= 1e-12,2));
end

function dominates = rowDominates(A,B)
%ROWDOMINATES Rowwise minimization dominance with the locked tolerance.

    dominates = all(double(A) <= double(B)+1e-12,2) & ...
        any(double(A) < double(B)-1e-12,2);
end

function order = angularOrder(W,ref)
%ANGULARORDER Independent expected ordering for the five-neighbor test.

    Wn = double(W)./max(sqrt(sum(double(W).^2,2)),eps);
    angle = 1-Wn*Wn(ref,:)';
    [~,order] = sortrows([angle,(1:size(W,1))'],[1 2]);
end

function [Selected,SelectedRefs,Matched,Trace] = selectSingleCandidate( ...
        Problem,g,yf,yi,otherEliteObjective,Options)
%SELECTSINGLECANDIDATE Exercise local objective gates independently.

    xf = [0.20 0.20];
    xi = [0.80 0.80];
    Archive = makeArchive(xf,xi,yf,yi,1);
    if isempty(otherEliteObjective)
        PopX = xf;
        PopY = yf;
    else
        PopX = [xf;0.95 0.95];
        PopY = [yf;otherEliteObjective];
    end
    Population = SOLUTION(PopX,PopY,zeros(size(PopX,1),1));
    Fitness = zeros(size(PopX,1),1);
    W = [1 0];
    gObj = Problem.CalObj(g);
    allObjectives = [PopY;yf;yi;gObj];
    minimum = min(allObjectives,[],1)-1;
    span = max(allObjectives,[],1)-minimum+1;
    RefScale = struct('minimum',minimum,'span',span);
    Info = struct('refs',1,'pairIds',1);
    [Selected,SelectedRefs,Matched,Trace] = ...
        PairBoundaryArchive_RC('selectcandidates',g,Info,Archive, ...
        Population,Fitness,W,RefScale,Problem,Options);
end
