function test_CBS_cutoff_diagnostics
%TEST_CBS_CUTOFF_DIAGNOSTICS Verify exact, behavior-neutral CGAN-end data.

    rootPath = fileparts(fileparts(fileparts(fileparts(fileparts( ...
        mfilename('fullpath'))))));
    addpath(fullfile(rootPath,'Algorithms','Multi-objective optimization', ...
        'CBS-CGAN','Support'),'-begin');
    addCBSPaths(rootPath);

    seed = 8803;
    rng(seed,'twister');
    PlainProblem = LIRCMOP6_BC('N',20,'D',10,'maxFE',2400);
    Plain = CBS_RegionWGAN_GP_Experiment( ...
        'parameter',{2,2,2,40},'save',1,'outputFcn',@silentOutput);
    Plain.Solve(PlainProblem);
    PlainRNG = rng;

    rng(seed,'twister');
    AuditProblem = LIRCMOP6_BC('N',20,'D',10,'maxFE',2400);
    Audit = CBS_RegionWGAN_GP_Experiment( ...
        'parameter',{2,2,2,40},'save',1,'outputFcn',@silentOutput);
    Audit.configureCutoffDiagnostics(struct( ...
        'enabled',true,'stopAtCGANEnd',false, ...
        'disableOracleAudit',true));
    Audit.Solve(AuditProblem);
    AuditRNG = rng;

    assert(PlainProblem.FE == AuditProblem.FE && ...
        PlainProblem.FE == PlainProblem.maxFE, ...
        'Diagnostics changed the evaluation budget.');
    assert(isequal(double(Plain.result{end,2}.decs), ...
        double(Audit.result{end,2}.decs)) && ...
        isequal(double(Plain.result{end,2}.objs), ...
        double(Audit.result{end,2}.objs)) && ...
        isequal(double(Plain.result{end,2}.cons), ...
        double(Audit.result{end,2}.cons)), ...
        'Diagnostics changed the deterministic population trajectory.');
    assert(isequal(PlainRNG,AuditRNG), ...
        'Diagnostics changed the terminal random-number state.');

    Snapshot = Audit.guideExperimentSnapshot();
    required = ["cganEndFE","cganEndIGD","cganEndHV", ...
        "cganEndDecs","cganEndObjs","cganEndCons", ...
        "checkpointIGD","checkpointHV", ...
        "rawBoundaryDistanceMedian","keptBoundaryDistanceMedian", ...
        "selectedBoundaryDistanceMedian","criticBoundarySpearman"];
    assert(all(isfield(Snapshot,required)), ...
        'Exact cutoff or candidate-boundary diagnostics are missing.');
    assert(isfinite(Snapshot.cganEndFE) && ...
        Snapshot.cganEndFE >= 0.5*AuditProblem.maxFE && ...
        isfinite(Snapshot.cganEndIGD) && isfinite(Snapshot.cganEndHV), ...
        'Exact cutoff metrics were not captured.');
    assert(Snapshot.rawOracleCount == 0 && ...
        Snapshot.selectedTargetCount == 0, ...
        'Disabled oracle diagnostics still evaluated generated decisions.');
    assert(Snapshot.generationEvents > 0 && ...
        isfinite(Snapshot.rawBoundaryDistanceMedian) && ...
        isfinite(Snapshot.keptBoundaryDistanceMedian) && ...
        Snapshot.rawBoundarySupportRate > 0 && ...
        Snapshot.rawBoundaryBandRate >= 0 && ...
        Snapshot.rawBoundaryBandRate <= 1, ...
        'Candidate-to-boundary geometry was not observed.');

    rng(seed,'twister');
    StopProblem = LIRCMOP6_BC('N',20,'D',10,'maxFE',2400);
    Stop = CBS_RegionWGAN_GP_Experiment( ...
        'parameter',{2,2,2,40},'save',1,'outputFcn',@silentOutput);
    Stop.configureCutoffDiagnostics(struct( ...
        'enabled',true,'stopAtCGANEnd',true, ...
        'disableOracleAudit',true));
    Stop.Solve(StopProblem);
    StopSnapshot = Stop.guideExperimentSnapshot();
    assert(StopProblem.FE == StopSnapshot.cganEndFE && ...
        StopProblem.FE >= 0.5*StopProblem.maxFE && ...
        StopProblem.FE < StopProblem.maxFE, ...
        'Cutoff-only run did not stop at the exact front-half endpoint.');
    assert(isequal(double(Stop.result{end,2}.decs), ...
        double(StopSnapshot.cganEndDecs)), ...
        'Saved cutoff population does not match the diagnosed population.');

    fprintf('CBS exact cutoff diagnostics passed.\n');
end

function silentOutput(~,~)
end
