function test_CBS_region_wgan_mainline()
%TEST_CBS_REGION_WGAN_MAINLINE Verify the sole production algorithm.

    repoRoot = fileparts(which('platemo'));
    addCBSPaths(repoRoot);
    algorithmFile = which('CBS_RegionWGAN_GP');
    assert(exist('CBS_RegionWGAN_GP','class') == 8);
    assert(exist('CBS_RegionWGAN_GP_Core','class') == 8);
    assert(exist('CBS_RegionWGAN_GP_Experiment','class') == 8, ...
        'The three-arm experiment wrapper must remain available.');
    assert(exist('CBS_RegionWGAN_GP_A1','class') == 8 && ...
        exist('CBS_RegionWGAN_GP_A2','class') == 8, ...
        'The fixed A1/A2 launch wrappers must remain available.');
    assert(exist('CBS_RegionWGAN_GP_Random20','class') == 8, ...
        'The Random20 ablation must remain available.');
    assert(exist('CBS_RegionWGAN_GP_DE20','class') == 8 && ...
        exist('CBS_RegionWGAN_GP_GA20','class') == 8, ...
        'The DE20/GA20 ablations must remain available.');

    Defaults = CBS_RegionWGAN_GP.mainlineDefaults();
    assert(Defaults.rawGuideCount == 500 && ...
        Defaults.criticKeepCount == 200 && ...
        Defaults.legacyGuideSlots == 20 && ...
        Defaults.legacyCandidatesPerSlot == 5 && Defaults.zDim == 6 && ...
        Defaults.ganIter == 100 && Defaults.ganMiniBatch == 32 && ...
        Defaults.nCritic == 4 && Defaults.minGANTrainCount == 32 && ...
        Defaults.sampleSigma == 0.3 && Defaults.ganStopFraction == 0.5 && ...
        Defaults.calibrationBudget == 20);

    source = string(fileread(which('CBS_RegionWGAN_GP_Core')));
    dataSource = string(fileread(which('BuildBoundaryDataset_RC')));
    querySource = string(fileread(which('RunRegionGAN_RC')));
    selectionSource = string(fileread(which('EnvironmentalSelection_CBS')));
    assert(contains(dataSource,'ones(numel(refs),1)') && ...
        contains(dataSource,'zeros(sum(keepI),1)'));
    assert(contains(source,'QueryC = [SampleC,ones') && ...
        contains(querySource,'0.3*totalBudget') && ...
        contains(querySource,'balancedQuerySamples') && ...
        contains(querySource,'conditionCriticFilter') && ...
        contains(source,'localTargetGuideDecisions') && ...
        contains(source,'vacancyWeightedMaximin') && ...
        contains(source,'OperatorDE(Problem,A,T,A,{1,1,1,20})') && ...
        contains(source,'ladder = [0.4,0.65,0.85]') && ...
        contains(source,['Union = [Population1,Population2,', ...
            'Offspring1, ...']) && ...
        contains(selectionSource,'truncateByObjectiveDistance') && ...
        contains(selectionSource, ...
            'Distance = pairDistance(PopObj,PopObj);'));
    forbidden = ["operatorMode","p2Operator","generatorMode", ...
        "trainData","scoutMode","metricsMode","guideRecord", ...
        "guideMode","guideAlloc","guideSelect","blsWindow", ...
        "blsFeed","initDecs","copynoise", ...
        "consensusshuffle","gapseed","guideFPolicy", ...
        "PlanGuideF_CBS","LateDifference","CutoffState", ...
        "pbestOrdinaryDE","randomGuideSlots"];
    sourceTree = source+newline+dataSource+newline+querySource+newline+ ...
        string(fileread(which('BoundaryWGAN_RC')));
    assert(~any(contains(sourceTree,forbidden)));
    Parameters = {0,7,50,8,5,9,0.2};
    Algorithm = CBS_RegionWGAN_GP('parameter',Parameters,'save',0, ...
        'outputFcn',@(varargin)[]);
    assert(isequal(Algorithm.parameter,Parameters));
    Problem = DASCMOP1_BC('N',10,'D',5,'maxFE',100);
    Algorithm.Solve(Problem);
    assert(Algorithm.result{end,1} == Problem.maxFE);
    testExperimentArms();
    testFixedArmWrappers();
    testFrontQuotaAblations();
    testExperimentalMechanismSmoke();
    testProductionMechanismSmoke();
    testMechanismAudit();
    testDistinctOrdinaryDE();
    testFrozenPathIsolation(repoRoot,algorithmFile);
    fprintf('CBS sole-mainline structure passed.\n');
end

function testMechanismAudit()
    rng(19,'twister');
    Problem = LIRCMOP5_BC('N',20,'D',5,'maxFE',400);
    Algorithm = CBS_RegionWGAN_GP_MechanismAudit('parameter', ...
        {0,1,2,500},'save',0,'outputFcn',@(varargin)[]);
    Algorithm.Solve(Problem);
    Snapshot = Algorithm.guideExperimentSnapshot();
    assert(Problem.FE == 400 && Snapshot.rawOracleCount > 0 && ...
        Snapshot.selectedTargetCount == Snapshot.guidedChildren && ...
        Snapshot.rawOracleFeasible <= Snapshot.rawOracleCount && ...
        Snapshot.selectedTargetFeasible <= Snapshot.selectedTargetCount && ...
        Snapshot.centerFeasible <= Snapshot.selectedTargetCount && ...
        Snapshot.childUseful <= Snapshot.guidedFeasible);
end

function testFrontQuotaAblations()
    Wrappers = {@CBS_RegionWGAN_GP_Random20, ...
        @CBS_RegionWGAN_GP_DE20,@CBS_RegionWGAN_GP_GA20};
    modes = ["random","traditional_de","traditional_ga"];
    for branch = 1 : numel(Wrappers)
        rng(28+branch,'twister');
        Problem = LIRCMOP5_BC('N',20,'D',5,'maxFE',100);
        Algorithm = Wrappers{branch}('save',0,'outputFcn',@(varargin)[]);
        Algorithm.Solve(Problem);
        Snapshot = Algorithm.guideExperimentSnapshot();
        assert(Problem.FE == 100 && Snapshot.arm == branch+2 && ...
            Snapshot.generationMode == modes(branch) && ...
            Snapshot.useMode == modes(branch) && ...
            Snapshot.generationEvents == 0 && ...
            Snapshot.rawCandidates == 0 && Snapshot.criticKept == 0 && ...
            Snapshot.guidedRequested == 4 && Snapshot.guidedSelected == 4 && ...
            Snapshot.guidedChildren == 4 && Snapshot.guidedFallback == 0 && ...
            Snapshot.selectionRate == 1 && ...
            isnan(Snapshot.guidedDominanceRate));
    end
end

function testFixedArmWrappers()
    Wrappers = {@CBS_RegionWGAN_GP_A1,@CBS_RegionWGAN_GP_A2};
    expectedGeneration = ["global_critic","global_critic"];
    expectedUse = ["legacy","local_target"];
    for arm = 1 : 2
        Algorithm = Wrappers{arm}('parameter',{0},'save',0, ...
            'outputFcn',@(varargin)[]);
        Problem = DASCMOP1_BC('N',10,'D',5,'maxFE',1);
        Algorithm.Solve(Problem);
        Snapshot = Algorithm.guideExperimentSnapshot();
        assert(Snapshot.arm == arm && ...
            Snapshot.generationMode == expectedGeneration(arm) && ...
            Snapshot.useMode == expectedUse(arm));
    end
end

function testExperimentalMechanismSmoke()
    for arm = 0 : 1
        rng(23,'twister');
        Problem = LIRCMOP5_BC('N',20,'D',5,'maxFE',400);
        Algorithm = CBS_RegionWGAN_GP_Experiment('parameter', ...
            {arm,1,2,500},'save',0,'outputFcn',@(varargin)[]);
        Algorithm.Solve(Problem);
        Snapshot = Algorithm.guideExperimentSnapshot();
        assert(Snapshot.generationEvents > 0 && Snapshot.useEvents > 0 && ...
            Snapshot.guidedSelected > 0);
        if arm == 0
            assert(Snapshot.rawCandidates == ...
                100*Snapshot.generationEvents && ...
                Snapshot.criticKept == Snapshot.rawCandidates);
        else
            assert(Snapshot.rawCandidates == ...
                500*Snapshot.generationEvents && ...
                Snapshot.criticKept == 200*Snapshot.generationEvents);
        end
    end
end

function testExperimentArms()
    expectedGeneration = ["legacy","global_critic","global_critic"];
    expectedUse = ["legacy","legacy","local_target"];
    for arm = 0 : 2
        Algorithm = CBS_RegionWGAN_GP_Experiment( ...
            'parameter',{arm},'save',0,'outputFcn',@(varargin)[]);
        Problem = DASCMOP1_BC('N',10,'D',5,'maxFE',1);
        Algorithm.Solve(Problem);
        Snapshot = Algorithm.guideExperimentSnapshot();
        assert(Snapshot.arm == arm && ...
            Snapshot.generationMode == expectedGeneration(arm+1) && ...
            Snapshot.useMode == expectedUse(arm+1));
    end
end

function testProductionMechanismSmoke()
    rng(17,'twister');
    Problem = LIRCMOP5_BC('N',20,'D',5,'maxFE',400);
    Algorithm = CBS_RegionWGAN_GP('parameter', ...
        {500,2,1,4,1,2,0.1},'save',0,'outputFcn',@(varargin)[]);
    Algorithm.Solve(Problem);
    Snapshot = Algorithm.guideExperimentSnapshot();
    assert(Problem.FE == 400 && Snapshot.arm == -1 && ...
        Snapshot.generationMode == "global_critic" && ...
        Snapshot.useMode == "local_target" && ...
        Snapshot.generationEvents > 0 && ...
        Snapshot.rawCandidates == 500*Snapshot.generationEvents && ...
        Snapshot.criticKept == 200*Snapshot.generationEvents && ...
        Snapshot.guidedSelected > 0 && Snapshot.guidedFallback >= 0 && ...
        Snapshot.mappedValid > 0 && ...
        isfinite(Snapshot.meanCenterStep) && ...
        isfinite(Snapshot.meanActualStep));
end

function testFrozenPathIsolation(repoRoot,algorithmFile)
    frozenDir = fullfile(repoRoot,'Data', ...
        'CBS_bt0_vs_nobt_gate_source_snapshot','Algorithms', ...
        'Multi-objective optimization','CBS-CGAN','Experimental');
    if ~isfolder(frozenDir)
        return;
    end
    addpath(frozenDir,'-begin');
    assert(~isempty(which('CBS_RegionWGAN_GP_BT0F0')), ...
        'Frozen-source isolation fixture is not visible.');
    addCBSPaths(repoRoot);
    assert(isempty(which('CBS_RegionWGAN_GP_BT0F0')) && ...
        isempty(which('CBS_RegionWGAN_GP_NoBT')) && ...
        strcmp(which('CBS_RegionWGAN_GP'),algorithmFile), ...
        'addCBSPaths must expose only the live CBS mainline.');
end

function testDistinctOrdinaryDE()
    rng(73,'twister');
    Problem = DASCMOP1_BC('N',6,'D',5,'maxFE',20);
    Population = Problem.Initialization();
    Fitness = (1:numel(Population))';
    [Offspring,Parents] = OperatorDEDistinct_CBS( ...
        Problem,Population,Fitness,4,{1,0.5,0,20});

    assert(all(Parents(:,1) ~= Parents(:,2)) && ...
        all(Parents(:,1) ~= Parents(:,3)) && ...
        all(Parents(:,2) ~= Parents(:,3)));
    Decs = Population.decs;
    expected = Decs(Parents(:,1),:) + ...
        0.5*(Decs(Parents(:,2),:)-Decs(Parents(:,3),:));
    expected = min(max(expected,Problem.lower),Problem.upper);
    assert(isequal(Offspring.decs,expected));
end
