function test_CBS_region_wgan_mainline()
%TEST_CBS_REGION_WGAN_MAINLINE Verify two independent retained algorithms.

    repoRoot = fileparts(which('platemo'));
    addCBSPaths(repoRoot);

    assert(exist('PairGuide','class') == 8);
    assert(exist('PairGuideCore','class') == 8);
    assert(exist('CBS_RegionWGAN_GP','class') == 8);
    assert(exist('CBS_RegionWGAN_GP_Core','class') == 8);
    assert(exist('RefineBoundaryObservations_RC','file') == 2);

    removed = {'CBS_RegionWGAN_GP_PairGuide', ...
        'CBS_RegionWGAN_GP_Experiment','CBS_RegionWGAN_GP_A1', ...
        'CBS_RegionWGAN_GP_E0_Base','CBS_RegionWGAN_GP_DE20', ...
        'CBS_RegionWGAN_GP_FullCGAN', ...
        'CBS_RegionWGAN_GP_PairGuide_DE20', ...
        'CBS_RegionWGAN_GP_PairGuide_Quota30', ...
        'CBS_RegionWGAN_GP_PairGuide_Quota40', ...
        'CBS_RegionWGAN_GP_PairGuide_Quota50'};
    assert(all(cellfun(@(name)exist(name,'class') == 0,removed)));

    pairEntry = string(fileread(which('PairGuide')));
    pairCore = string(fileread(which('PairGuideCore')));
    previousEntry = string(fileread(which('CBS_RegionWGAN_GP')));
    previousCore = string(fileread(which('CBS_RegionWGAN_GP_Core')));
    assert(contains(pairEntry,'classdef PairGuide < PairGuideCore') && ...
        ~contains(pairEntry,'CBS_RegionWGAN_GP') && ...
        ~contains(pairCore,'CBS_RegionWGAN_GP') && ...
        contains(previousEntry, ...
            'classdef CBS_RegionWGAN_GP < CBS_RegionWGAN_GP_Core') && ...
        ~contains(previousEntry,'PairGuide') && ...
        ~contains(previousCore,'PairGuide'));

    PairDefaults = PairGuide.mainlineDefaults();
    assert(PairDefaults.rawGuideCount == 500 && ...
        PairDefaults.zDim == 6 && PairDefaults.ganIter == 500 && ...
        PairDefaults.ganMiniBatch == 64 && PairDefaults.nCritic == 5 && ...
        PairDefaults.sampleSigma == 1 && ...
        isinf(PairDefaults.ganStopFraction) && ...
        PairDefaults.pairGanEpoch == 500 && ...
        PairDefaults.pairRetrainEpoch == 20 && ...
        PairDefaults.pairArchivePerRef == 1 && ...
        PairDefaults.pairNeighborRefCount == 5 && ...
        PairDefaults.pairMinPairs == 32);

    PreviousDefaults = CBS_RegionWGAN_GP.mainlineDefaults();
    assert(PreviousDefaults.rawGuideCount == 500 && ...
        PreviousDefaults.criticKeepCount == 200 && ...
        PreviousDefaults.ganIter == 100 && ...
        PreviousDefaults.ganMiniBatch == 32 && ...
        PreviousDefaults.nCritic == 4 && ...
        PreviousDefaults.sampleSigma == 0.3 && ...
        PreviousDefaults.ganStopFraction == 0.5 && ...
        PreviousDefaults.calibrationBudget == 20);

    assert(contains(pairCore,"PairBoundaryArchive_RC('update'") && ...
        contains(pairCore,'PairBoundaryWGAN_RC(') && ...
        contains(pairCore,'withObjectiveBudget') && ...
        ~contains(pairCore,'RefineBoundaryObservations_RC') && ...
        contains(previousCore,'RunRegionGAN_RC') && ...
        contains(previousCore,'localTargetGuideDecisions') && ...
        contains(previousCore,'RefineBoundaryObservations_RC'));

    pairParameters = {500,6,0,64,5,32,1};
    Current = PairGuide('parameter',pairParameters,'save',0, ...
        'outputFcn',@(varargin)[]);
    PairProblem = DASCMOP1_BC('N',10,'D',5,'maxFE',100);
    Current.Solve(PairProblem);
    PairSnapshot = Current.guideExperimentSnapshot();
    assert(PairProblem.FE == PairProblem.maxFE && ...
        PairSnapshot.arm == 7 && ...
        PairSnapshot.generationMode == "pair_guide" && ...
        PairSnapshot.useMode == "pair_guide" && ...
        PairSnapshot.pairGanEpoch == 0 && ...
        PairSnapshot.pairGuideSchema == "PairGuide");

    previousParameters = {0,7,50,8,5,9,0.2};
    Previous = CBS_RegionWGAN_GP('parameter',previousParameters, ...
        'save',0,'outputFcn',@(varargin)[]);
    PreviousProblem = DASCMOP1_BC('N',10,'D',5,'maxFE',100);
    Previous.Solve(PreviousProblem);
    PreviousSnapshot = Previous.guideExperimentSnapshot();
    assert(PreviousProblem.FE == PreviousProblem.maxFE && ...
        PreviousSnapshot.arm == -1 && ...
        PreviousSnapshot.generationMode == "global_critic" && ...
        PreviousSnapshot.useMode == "local_target");

    testDistinctOrdinaryDE();
    fprintf('Independent PairGuide and previous-mainline structure passed.\n');
end

function testDistinctOrdinaryDE()
    rng(73,'twister');
    Problem = DASCMOP1_BC('N',6,'D',5,'maxFE',20);
    Population = Problem.Initialization();
    Fitness = (1:numel(Population))';
    [Offspring,Parents] = OperatorDEDistinct_CBS( ...
        Problem,Population,Fitness,4,{1,0.5,0,20});

    assert(all(Parents(:,1) ~= Parents(:,2)) && ...
        all(Parents(:,1) ~= Parents(:,3)) && ...
        all(Parents(:,2) ~= Parents(:,3)));
    Decs = Population.decs;
    expected = Decs(Parents(:,1),:) + ...
        0.5*(Decs(Parents(:,2),:)-Decs(Parents(:,3),:));
    expected = min(max(expected,Problem.lower),Problem.upper);
    assert(isequal(Offspring.decs,expected));
end
