function test_CBS_screening_branches()
%TEST_CBS_SCREENING_BRANCHES Verify sequential factors and their primitives.

    repoRoot = fileparts(which('platemo'));
    addCBSPaths(repoRoot);
    testWrapperConfigurations();
    testUnpairedAnchorAndDirectionRange();
    testFrontDepthAndReferenceCap();
    testBalancedBatchTraining();
    fprintf('CBS sequential-screening branch tests passed.\n');
end

function testWrapperConfigurations()
    names = ["CBS_RegionWGAN_GP_E0_Base", ...
        "CBS_RegionWGAN_GP_E1_KeepAnchor", ...
        "CBS_RegionWGAN_GP_E2_K10", ...
        "CBS_RegionWGAN_GP_E2_KAll", ...
        "CBS_RegionWGAN_GP_E3_AllFeasible", ...
        "CBS_RegionWGAN_GP_E4_Cap10", ...
        "CBS_RegionWGAN_GP_E4_CapAll", ...
        "CBS_RegionWGAN_GP_E5_SplitGate", ...
        "CBS_RegionWGAN_GP_E5b_KeepWithSplit", ...
        "CBS_RegionWGAN_GP_E6_BalancedBatch", ...
        "CBS_RegionWGAN_GP_E7_MemoryParent", ...
        "CBS_RegionWGAN_GP_E8_GlobalCritic"];
    expected = [ ...
        0 5   2   5   0 0 0 0 1; ...
        1 5   2   5   0 0 0 0 1; ...
        0 10  2   5   0 0 0 0 1; ...
        0 Inf 2   5   0 0 0 0 1; ...
        0 5   Inf 5   0 0 0 0 1; ...
        0 5   2   10  0 0 0 0 1; ...
        0 5   2   Inf 0 0 0 0 1; ...
        0 5   2   5   1 0 0 0 1; ...
        1 5   2   5   1 0 0 0 1; ...
        0 5   2   5   0 1 0 0 1; ...
        0 5   2   5   0 0 1 0 1; ...
        0 5   2   5   0 0 0 1 1];
    for i = 1 : numel(names)
        Algorithm = feval(char(names(i)),'save',0, ...
            'outputFcn',@(varargin)[]);
        Config = Algorithm.screeningConfigurationSnapshot();
        assert(isequaln(configurationVector(Config),expected(i,:)));
    end

    override = {1,Inf,Inf,Inf,1,1,1,1,0};
    Algorithm = CBS_RegionWGAN_GP_E0_Base('parameter',override, ...
        'save',0,'outputFcn',@(varargin)[]);
    Config = Algorithm.screeningConfigurationSnapshot();
    assert(isequaln(configurationVector(Config),cell2mat(override)));

    Problem = DASCMOP1_BC('N',10,'D',5,'maxFE',1);
    Algorithm.Solve(Problem);
    assert(isfield(Algorithm.metric,'CBSAudit'));
    Audit = Algorithm.metric.CBSAudit;
    assert(Audit.keepUnpairedAnchors && ...
        Audit.generationMode == "global_critic" && ...
        Audit.trainGateMode == "split" && ...
        Audit.batchSamplingMode == "pairflag_balanced" && ...
        Audit.parentSourceMode == "memory_fallback");
end

function values = configurationVector(Config)
    values = [double(Config.keepUnpairedAnchors), ...
        Config.pairNeighborRefCount,Config.frontDepth, ...
        Config.maxAnchorsPerRef, ...
        double(Config.trainGateMode == "split"), ...
        double(Config.batchSamplingMode == "pairflag_balanced"), ...
        double(Config.parentSourceMode == "memory_fallback"), ...
        double(Config.guideGenerationMode == "global_critic"), ...
        double(Config.mechanismAudit)];
end

function testUnpairedAnchorAndDirectionRange()
    Problem = DASCMOP1_BC('N',8,'D',5,'maxFE',100);
    W = [1 0;0 1];
    X = makeDecisionRows(Problem,2);
    Y = [1 10;0.5 11];
    Population = SOLUTION(X,Y,[0;1]);
    Empty = Population([]);
    base = struct('frontDepth',Inf,'pairNeighborRefCount',1, ...
        'keepUnpairedAnchors',false,'minBoundaryLength',100, ...
        'maxAnchorsPerRef',Inf);

    [Dropped,~,DropTrace] = UpdateBoundaryMemory_RC([],Population, ...
        Empty,Empty,Empty,W,base);
    assert(isempty(Dropped.x_b) && DropTrace.legalAny == 1 && ...
        DropTrace.legalWithin5 == 1);

    keep = base;
    keep.keepUnpairedAnchors = true;
    [Unpaired,~,KeepTrace] = UpdateBoundaryMemory_RC([],Population, ...
        Empty,Empty,Empty,W,keep);
    assert(size(Unpaired.x_b,1) == 1 && ...
        all(isnan(Unpaired.x_i),'all') && KeepTrace.unpaired == 1);
    [TrainX,TrainC,QueryRefs] = ...
        BuildBoundaryDataset_RC(Unpaired,W,Problem);
    assert(isequal(TrainX,Unpaired.x_b) && ...
        isequal(TrainC,[W(Unpaired.ref,:),1]) && ...
        isequal(QueryRefs,Unpaired.ref));

    unrestricted = base;
    unrestricted.pairNeighborRefCount = Inf;
    [Paired,~,PairTrace] = UpdateBoundaryMemory_RC([],Population, ...
        Empty,Empty,Empty,W,unrestricted);
    assert(size(Paired.x_b,1) == 1 && ...
        all(isfinite(Paired.x_i),'all') && PairTrace.paired == 1);

    onlyInfeasible = Population(2);
    [Converted,~,ConversionTrace] = UpdateBoundaryMemory_RC( ...
        Unpaired,onlyInfeasible,Empty,Empty,Empty,W,unrestricted);
    assert(size(Converted.x_b,1) == 1 && ...
        ConversionTrace.previousUnpaired == 1 && ...
        ConversionTrace.previousUnpairedPaired == 1);

    dominated = SOLUTION(X,[1 10;2 11],[0;1]);
    keep.pairNeighborRefCount = Inf;
    [Excluded,~,ExcludedTrace] = UpdateBoundaryMemory_RC([],dominated, ...
        Empty,Empty,Empty,W,keep);
    assert(size(Excluded.x_b,1) == 1 && ...
        all(isnan(Excluded.x_i),'all') && ...
        ExcludedTrace.dominanceRejected >= 1);
end

function testFrontDepthAndReferenceCap()
    Problem = DASCMOP1_BC('N',12,'D',5,'maxFE',100);
    W = [0.5 0.5];
    X = makeDecisionRows(Problem,3);
    Population = SOLUTION(X,[1 1;2 2;3 3],zeros(3,1));
    Empty = Population([]);
    Options = struct('frontDepth',2,'pairNeighborRefCount',1, ...
        'keepUnpairedAnchors',true,'minBoundaryLength',100, ...
        'maxAnchorsPerRef',Inf);
    [FrontTwo,~,TraceTwo] = UpdateBoundaryMemory_RC([],Population, ...
        Empty,Empty,Empty,W,Options);
    Options.frontDepth = Inf;
    [AllFronts,~,TraceAll] = UpdateBoundaryMemory_RC([],Population, ...
        Empty,Empty,Empty,W,Options);
    assert(size(FrontTwo.x_b,1) == 2 && TraceTwo.frontDropped == 1 && ...
        size(AllFronts.x_b,1) == 3 && TraceAll.frontDropped == 0);

    Y = [(1:10)' (10:-1:1)'];
    Population = SOLUTION(makeDecisionRows(Problem,10),Y,zeros(10,1));
    Empty = Population([]);
    Options.frontDepth = 2;
    Options.maxAnchorsPerRef = 5;
    [CapFive,~,TraceFive] = UpdateBoundaryMemory_RC([],Population, ...
        Empty,Empty,Empty,W,Options);
    Options.maxAnchorsPerRef = 10;
    [CapTen,~,TraceTen] = UpdateBoundaryMemory_RC([],Population, ...
        Empty,Empty,Empty,W,Options);
    assert(size(CapFive.x_b,1) == 5 && TraceFive.capDropped == 5 && ...
        size(CapTen.x_b,1) == 10 && TraceTen.capDropped == 0);
end

function testBalancedBatchTraining()
    Problem = LIRCMOP5_BC('N',10,'D',5,'maxFE',100);
    TrainX = makeDecisionRows(Problem,6);
    TrainC = [repmat([0.25 0.75 1],5,1);0.75 0.25 0];
    Options = struct('minTrainCount',2,'zDim',2,'iter',1, ...
        'miniBatch',4,'nCritic',1,'generatorHidden',[4 4], ...
        'criticHidden',[4 4],'sampleSigma',0.1, ...
        'batchSamplingMode',"uniform");
    rng(971,'twister');
    Uniform = BoundaryWGAN_RC('train',[],TrainX,TrainC,Problem,Options);
    Options.batchSamplingMode = "pairflag_balanced";
    rng(971,'twister');
    Balanced = BoundaryWGAN_RC('train',[],TrainX,TrainC,Problem,Options);
    probeX = makeDecisionRows(Problem,1);
    probeC = [0.5 0.5 1];
    uniformScore = BoundaryWGAN_RC( ...
        'scorebycondition',Uniform,probeX,probeC);
    balancedScore = BoundaryWGAN_RC( ...
        'scorebycondition',Balanced,probeX,probeC);
    assert(Uniform.iterG == 1 && Balanced.iterG == 1 && ...
        Uniform.iterC == 1 && Balanced.iterC == 1 && ...
        uniformScore ~= balancedScore);
end

function X = makeDecisionRows(Problem,n)
    X = Problem.lower+rand(n,Problem.D).*(Problem.upper-Problem.lower);
end
