function test_CBS_objective_space_snapshots
%TEST_CBS_OBJECTIVE_SPACE_SNAPSHOTS Verify behavior-neutral point capture.

    rootPath = fileparts(fileparts(fileparts(fileparts(fileparts( ...
        mfilename('fullpath'))))));
    addpath(fullfile(rootPath,'Algorithms','Multi-objective optimization', ...
        'CBS-CGAN','Support'),'-begin');
    addCBSPaths(rootPath);

    seed = 8817;
    parameters = {20,2,2,8,1,2,0.3};
    rng(seed,'twister');
    PlainProblem = LIRCMOP6_BC('N',20,'D',10,'maxFE',2400);
    Plain = CBS_RegionWGAN_GP('parameter',parameters,'save',1, ...
        'outputFcn',@silentOutput);
    Plain.Solve(PlainProblem);
    plainRNG = rng;

    rng(seed,'twister');
    CaptureProblem = LIRCMOP6_BC('N',20,'D',10,'maxFE',2400);
    Capture = CBS_RegionWGAN_GP('parameter',parameters,'save',1, ...
        'outputFcn',@silentOutput);
    Capture.configureObjectiveSpaceSnapshots(struct( ...
        'enabled',true,'targetFE',[800,1200], ...
        'expectedRawCount',20,'expectedGuidedCount',4));
    Capture.Solve(CaptureProblem);
    captureRNG = rng;

    assert(PlainProblem.FE == CaptureProblem.FE && ...
        PlainProblem.FE == PlainProblem.maxFE, ...
        'Snapshot capture changed the evaluation budget.');
    assert(isequal(double(Plain.result{end,2}.decs), ...
        double(Capture.result{end,2}.decs)) && ...
        isequal(double(Plain.result{end,2}.objs), ...
        double(Capture.result{end,2}.objs)) && ...
        isequal(double(Plain.result{end,2}.cons), ...
        double(Capture.result{end,2}.cons)), ...
        'Snapshot capture changed the deterministic population trajectory.');
    assert(isequal(plainRNG,captureRNG), ...
        'Snapshot capture changed the terminal random-number state.');

    Snapshots = Capture.objectiveSpaceSnapshots();
    assert(numel(Snapshots) == 2 && ...
        isequal([Snapshots.targetFE],[800,1200]), ...
        'Configured target FE snapshots are missing.');
    assert(all([Snapshots.rawCount] == 20) && ...
        all([Snapshots.guidedCount] == 4), ...
        'Raw or guided point counts are incorrect.');
    assert(all(arrayfun(@(S)size(S.rawObjs,1) == 20 && ...
        size(S.guidedObjs,1) == 4 && size(S.rawObjs,2) == 2 && ...
        size(S.guidedObjs,2) == 2,Snapshots)), ...
        'Objective-space snapshot shapes are incorrect.');
    assert(all(isfinite([Snapshots.actualFE])) && ...
        all(isfinite([Snapshots.poolFE])), ...
        'Snapshot event FE metadata are missing.');

    fprintf('CBS objective-space snapshot capture passed.\n');
end

function silentOutput(~,~)
end
