function test_CBS_pair_guide()
%TEST_CBS_PAIR_GUIDE Verify the locked pair archive, WGAN, and identity.

    repoRoot = fileparts(which('platemo'));
    addCBSPaths(repoRoot);
    assert(exist('CBS_RegionWGAN_GP_PairGuide','class') == 8 && ...
        exist('CBS_RegionWGAN_GP_PairGuide_Quota30','class') == 8 && ...
        exist('CBS_RegionWGAN_GP_PairGuide_Quota40','class') == 8 && ...
        exist('CBS_RegionWGAN_GP_PairGuide_Quota50','class') == 8);

    %% Public comparator identity and no permanent cutoff
    Algorithm = CBS_RegionWGAN_GP_PairGuide('parameter', ...
        {20,6,0,64,5,32,1},'save',0,'outputFcn',@(varargin)[]);
    Algorithm.configureObjectiveSpaceSnapshots(struct( ...
        'enabled',true,'targetFE',1));
    Problem = DASCMOP1_BC('N',10,'D',5,'maxFE',1);
    Algorithm.Solve(Problem);
    Snapshot = Algorithm.guideExperimentSnapshot();
    assert(Snapshot.arm == 7 && ...
        Snapshot.generationMode == "pair_guide" && ...
        Snapshot.useMode == "pair_guide" && Snapshot.nCritic == 5 && ...
        Snapshot.pairGanEpoch == 0 && ...
        Snapshot.pairGuideSchemaVersion == "CBS-CGAN-pair-guide-v4" && ...
        isinf(Snapshot.cganEndTarget) && ...
        isempty(Algorithm.objectiveSpaceSnapshots()));
    pairGuideSource = string(fileread(which('CBS_RegionWGAN_GP_PairGuide')));
    assert(contains(pairGuideSource,'% ganEpoch') && ...
        ~contains(pairGuideSource,'% ganIter'));
    DefaultAlgorithm = CBS_RegionWGAN_GP_PairGuide( ...
        'save',0,'outputFcn',@(varargin)[]);
    DefaultProblem = DASCMOP1_BC('N',2,'D',5,'maxFE',1);
    DefaultAlgorithm.Solve(DefaultProblem);
    DefaultSnapshot = DefaultAlgorithm.guideExperimentSnapshot();
    assert(DefaultSnapshot.pairGanEpoch == 500 && ...
        DefaultSnapshot.pairInitialEpoch == 500 && ...
        DefaultSnapshot.pairRetrainEpoch == 10 && ...
        DefaultSnapshot.nCritic == 5 && ...
        DefaultSnapshot.guideOffspringShare == 0.20);
    ExperimentAlgorithm = CBS_RegionWGAN_GP_PairGuide( ...
        'save',0,'outputFcn',@(varargin)[]);
    ExperimentAlgorithm.configurePairGuideTrainingExperiment(struct( ...
        'initialEpoch',3,'retrainEpoch',1,'nCritic',2));
    ExperimentProblem = DASCMOP1_BC('N',2,'D',5,'maxFE',1);
    ExperimentAlgorithm.Solve(ExperimentProblem);
    ExperimentSnapshot = ExperimentAlgorithm.guideExperimentSnapshot();
    assert(ExperimentSnapshot.pairInitialEpoch == 3 && ...
        ExperimentSnapshot.pairRetrainEpoch == 1 && ...
        ExperimentSnapshot.nCritic == 2 && ...
        DefaultSnapshot.pairInitialEpoch == 500);

    %% Guide quota remains a population proportion, not a fixed count
    RatioAlgorithms = ["CBS_RegionWGAN_GP_PairGuide", ...
        "CBS_RegionWGAN_GP_PairGuide_Quota30", ...
        "CBS_RegionWGAN_GP_PairGuide_Quota40", ...
        "CBS_RegionWGAN_GP_PairGuide_Quota50"];
    RatioShares = [0.20 0.30 0.40 0.50];
    for i = 1 : numel(RatioAlgorithms)
        constructor = str2func(RatioAlgorithms(i));
        RatioAlgorithm = constructor('parameter', ...
            {0,6,0,64,5,32,1},'save',0,'outputFcn',@(varargin)[]);
        % N=10 exposes independent-rounding errors while ordinary DE must
        % absorb only the residue left by the explicit guide quota.
        RatioProblem = DASCMOP1_BC('N',10,'D',5,'maxFE',40);
        RatioAlgorithm.Solve(RatioProblem);
        RatioSnapshot = RatioAlgorithm.guideExperimentSnapshot();
        requested = round(RatioShares(i)*RatioProblem.N);
        assert(RatioSnapshot.guideOffspringShare == RatioShares(i) && ...
            RatioSnapshot.guidedRequested == requested && ...
            RatioSnapshot.guidedFallback == requested);
    end

    %% Explicit epoch probe stops after first Pop1 use, before Pop2 evaluation
    rng(771,'twister');
    CaptureProblem = LIRCMOP5_BC('N',40,'D',10,'maxFE',20000);
    CaptureAlgorithm = CBS_RegionWGAN_GP_PairGuide('parameter', ...
        {500,6,1,64,5,32,1},'save',0,'outputFcn',@(varargin)[]);
    CaptureAlgorithm.configureFirstPairGuideUseCapture(struct( ...
        'enabled',true,'stopAfterUse',true,'sampleSeed',77101, ...
        'sampleSigmas',[1 0.5]));
    CaptureAlgorithm.Solve(CaptureProblem);
    Capture = CaptureAlgorithm.firstPairGuideUseCapture();
    CaptureAudit = CaptureAlgorithm.guideExperimentSnapshot();
    pairedFinalRng = rng;
    assert(Capture.complete && Capture.eventCount == 1 && ...
        isscalar(Capture.events) && ...
        Capture.events(1).complete && ...
        Capture.events(1).useFE == Capture.useFE && ...
        Capture.trainingSigma == 1 && ...
        Capture.events(1).trainingSigma == 1 && ...
        Capture.trainStatus.trained && Capture.trainStatus.useModel && ...
        Capture.trainStatus.trainingSigma == 1 && ...
        ~isfield(Capture.trainStatus,'accepted') && ...
        CaptureProblem.FE == Capture.useFE && ...
        Capture.useFE-Capture.poolFE == CaptureProblem.N && ...
        size(Capture.rawDecs,1) == 500 && ...
        Capture.requestedCount == round(0.2*CaptureProblem.N) && ...
        Capture.selectedCount+Capture.fallbackCount == ...
            Capture.requestedCount && ...
        size(Capture.childDecs,1) == Capture.selectedCount && ...
        size(Capture.childObjs,1) == Capture.selectedCount && ...
        size(Capture.childCons,1) == Capture.selectedCount && ...
        isequal(size(Capture.constrainedPopulationObjs), ...
            [CaptureProblem.N,CaptureProblem.M]) && ...
        size(Capture.constrainedPopulationCons,1) == CaptureProblem.N && ...
        isequal(size(Capture.unconstrainedPopulationObjs), ...
            [CaptureProblem.N,CaptureProblem.M]) && ...
        size(Capture.unconstrainedPopulationCons,1) == CaptureProblem.N && ...
        isequal(Capture.events(1).constrainedPopulationObjs, ...
            Capture.constrainedPopulationObjs) && ...
        isequal(Capture.events(1).unconstrainedPopulationObjs, ...
            Capture.unconstrainedPopulationObjs) && ...
        Capture.pairedSampling && numel(Capture.sigmaArms) == 2 && ...
        isequal([Capture.sigmaArms.sigma],[1 0.5]) && ...
        isequaln(Capture.sigmaArms(1).rawDecs,Capture.rawDecs) && ...
        isequaln(Capture.sigmaArms(1).childDecs,Capture.childDecs) && ...
        Capture.sigmaArms(1).selectedCount == Capture.selectedCount && ...
        Capture.sigmaArms(1).fallbackCount == Capture.fallbackCount && ...
        CaptureAudit.rawOracleCount == 0);

    % Paired replay must leave the exact production trajectory and RNG intact.
    rng(771,'twister');
    BaselineProblem = LIRCMOP5_BC('N',40,'D',10,'maxFE',20000);
    BaselineAlgorithm = CBS_RegionWGAN_GP_PairGuide('parameter', ...
        {500,6,1,64,5,32,1},'save',0,'outputFcn',@(varargin)[]);
    BaselineAlgorithm.configureFirstPairGuideUseCapture(struct( ...
        'enabled',true,'stopAfterUse',true,'sampleSeed',77101));
    BaselineAlgorithm.Solve(BaselineProblem);
    Baseline = BaselineAlgorithm.firstPairGuideUseCapture();
    baselineFinalRng = rng;
    assert(isequaln(Capture.rawDecs,Baseline.rawDecs) && ...
        isequaln(Capture.selectedCandidateDecs, ...
            Baseline.selectedCandidateDecs) && ...
        isequaln(Capture.childDecs,Baseline.childDecs) && ...
        Capture.useFE == Baseline.useFE && ...
        isequaln(pairedFinalRng,baselineFinalRng));

    %% Atomic archive: real endpoints, unified pairs, monotone tightening
    rng(731,'twister');
    Problem = DASCMOP1_BC('N',40,'D',5,'maxFE',100);
    [W,~] = UniformPoint(20,2);
    n = 40;
    t = linspace(0.02,0.98,n)';
    yf = [t,1-t];
    xf = 0.2+0.5*rand(n,Problem.D);
    xi = min(1,max(0,xf+0.12*randn(n,Problem.D)));
    yi = yf+0.05;
    P1 = SOLUTION(xf,yf,zeros(n,1));
    Infeasible = SOLUTION(xi,yi,ones(n,1));
    Evaluated = [P1,Infeasible];
    Options = struct('pairMinPairs',32,'pairMinRegions',4, ...
        'pairArchivePerRef',5,'pairNeighborRefCount',5);
    [Archive,~,Trace] = PairBoundaryArchive_RC('update',[],P1, ...
        Evaluated,W,Problem,Options,struct(),100);
    [Data,Gate,TrainC,QueryRefs,BMem] = ...
        PairBoundaryArchive_RC('trainingdata',Archive,W,Problem,Options);
    assert(Trace.strong == 0 && Trace.weak == 0 && ...
        Data.count == Gate.active && size(TrainC,1) == 2*Data.count && ...
        all(TrainC(1:Data.count,end) == 1) && ...
        all(TrainC(Data.count+1:end,end) == 0) && ...
        Gate.eligible && numel(QueryRefs) >= 4 && ...
        all(BMem.active));
    oldIds = Archive.id;
    oldGap = Archive.gap;
    closerXi = (xf+xi)/2;
    Closer = SOLUTION(closerXi,yi,ones(n,1));
    [Archive,~,Trace2] = PairBoundaryArchive_RC('update',Archive,P1, ...
        [P1,Closer],W,Problem,Options,struct(),200);
    assert(isequal(Archive.id,oldIds) && ...
        all(Archive.gap <= oldGap+1e-12) && ...
        Trace2.tightenedInfeasible > 0);

    testArchiveLifecycleAndReferenceFreedom();

    %% Formal query is s=0; post-hoc matching has no critic truncation
    [QueryC,Info] = PairBoundaryArchive_RC( ...
        'querycontexts',Archive,W,Options,500);
    assert(size(QueryC,1) == 500 && all(QueryC(:,end) == 0));
    active = find(Archive.active);
    rawRows = active(mod((0:499)',numel(active))+1);
    Raw = Archive.xi(rawRows,:)+0.002*randn(500,Problem.D);
    Raw = min(max(Raw,Problem.lower),Problem.upper);
    Info.refs = Archive.ref(rawRows);
    Info.projectionRate = zeros(500,1);
    [Kept,KeptRefs,Matched,PoolTrace] = ...
        PairBoundaryArchive_RC('selectcandidates',Raw,Info,Archive,P1, ...
        ones(n,1),W,[],Problem,Options);
    assert(size(Kept,1) == numel(KeptRefs) && ...
        size(Kept,1) == numel(Matched) && ...
        size(Kept,1) == PoolTrace.keptCount && ...
        size(Kept,1) > 20 && all(ismember(Matched,Archive.id)));

    %% Duplicate-only mapped targets return empty so ordinary DE can fill
    TinyFeas = zeros(2,Problem.D);
    TinyFeas(2,1) = 5e-7;
    TinyBMem = struct('id',1,'x_b',TinyFeas(1,:), ...
        'ref',1,'active',true);
    PairConfig = CBS_RegionWGAN_GP_Core.mainlineDefaults();
    [EmptyChildren,EmptyParents,EmptyRefs,EmptyMap,EmptyPairIds] = ...
        CBS_RegionWGAN_GP_Core.pairGuideDecisionTestHook( ...
        Problem,TinyFeas,ones(2,1),zeros(2,1), ...
        0.8*ones(1,Problem.D),1,1,W,1,TinyBMem,PairConfig);
    assert(isempty(EmptyChildren) && isempty(EmptyParents) && ...
        isempty(EmptyRefs) && isempty(EmptyPairIds) && ...
        EmptyMap.validCount == 1);

    %% Every full epoch covers every training pair once, including tail batch
    WGANOptions = struct('epochs',2,'initialEpoch',2, ...
        'retrainEpoch',1,'miniBatch',64,'zDim',6, ...
        'nCritic',1,'pairMinPairs',32);
    [Model,Status] = PairBoundaryWGAN_RC('trainifneeded',[], ...
        Data,Gate,Problem,WGANOptions);
    assert(Status.trained && Status.epochs == 2 && ...
        Status.trainingPairs == Data.count && ...
        Status.pairVisits == Status.epochs*Status.trainingPairs && ...
        Status.updates == Status.epochs*Status.batchesPerEpoch && ...
        Status.trainingKind == "initial" && Status.nCritic == 1 && ...
        Status.criticUpdates == Status.updates && ...
        Status.criticPairVisits == Status.pairVisits && ...
        Status.batchesPerEpoch == ceil(Status.trainingPairs/32) && ...
        Status.trainingSigma == 1 && ...
        all(structfun(@isnan,Status.preDiagnostics)) && ...
        all(structfun(@isnan,Status.postDiagnostics)) && ...
        Status.useModel && Status.reason == "trained" && ...
        ~isfield(Status,'accepted') && ~isfield(Status,'validation'));

    %% Training sigma scales every Gaussian latent draw, not RNG consumption
    TrainingOneOptions = WGANOptions;
    TrainingOneOptions.epochs = 1;
    TrainingOneOptions.initialEpoch = 1;
    rng(1811,'twister');
    [TrainingOne,TrainingOneStatus] = PairBoundaryWGAN_RC( ...
        'trainifneeded',[],Data,Gate,Problem,TrainingOneOptions);
    trainingOneRng = rng;
    TrainingHalfOptions = TrainingOneOptions;
    TrainingHalfOptions.trainingSigma = 0.5;
    rng(1811,'twister');
    [TrainingHalf,TrainingHalfStatus] = PairBoundaryWGAN_RC( ...
        'trainifneeded',[],Data,Gate,Problem,TrainingHalfOptions);
    trainingHalfRng = rng;
    CompareSampleOptions = TrainingHalfOptions;
    CompareSampleOptions.sampleSigma = 0.5;
    rng(1812,'twister');
    TrainingOneSample = PairBoundaryWGAN_RC('sample',TrainingOne, ...
        QueryC(1:8,:),Problem,CompareSampleOptions);
    rng(1812,'twister');
    TrainingHalfSample = PairBoundaryWGAN_RC('sample',TrainingHalf, ...
        QueryC(1:8,:),Problem,CompareSampleOptions);
    assert(TrainingOneStatus.trainingSigma == 1 && ...
        TrainingHalfStatus.trainingSigma == 0.5 && ...
        isequaln(trainingOneRng,trainingHalfRng) && ...
        any(abs(TrainingOneSample-TrainingHalfSample) > 0,'all'));

    %% The exact 32-pair threshold is one complete 64-endpoint batch
    ThresholdData = Data;
    rowFields = {'xF','xI','delta','w','ref','id','lastFE','cF','cI'};
    for i = 1 : numel(rowFields)
        name = rowFields{i};
        ThresholdData.(name) = ThresholdData.(name)(1:32,:);
    end
    ThresholdData.count = 32;
    ThresholdGate = struct('eligible',true);
    ThresholdOptions = WGANOptions;
    ThresholdOptions.epochs = 1;
    ThresholdOptions.initialEpoch = 1;
    [~,ThresholdStatus] = PairBoundaryWGAN_RC('trainifneeded',[], ...
        ThresholdData,ThresholdGate,Problem,ThresholdOptions);
    assert(ThresholdStatus.trained && ThresholdStatus.useModel && ...
        ThresholdStatus.trainingPairs == 32 && ...
        ThresholdStatus.batchesPerEpoch == 1 && ...
        ThresholdStatus.pairVisits == 32 && ...
        ThresholdStatus.updates == 1);

    %% Removing a previously trained active pair counts as a data change
    Probe = struct('ready',true, ...
        'lastPairIds',[Data.id;max(Data.id)+1], ...
        'lastPairFE',[Data.lastFE;0], ...
        'lastRefs',unique(Data.ref,'stable'));
    TriggerOptions = WGANOptions;
    TriggerOptions.pairRetrainChanges = 8;
    TriggerOptions.pairNewRegionChanges = 2;
    [~,RemovalStatus] = PairBoundaryWGAN_RC('trainifneeded',Probe, ...
        Data,Gate,Problem,TriggerOptions);
    assert(RemovalStatus.changedPairs == 1 && ...
        RemovalStatus.reason == "current");
    [Generated,SampleTrace] = PairBoundaryWGAN_RC( ...
        'sample',Model,QueryC(1:8,:),Problem,WGANOptions);
    assert(isequal(size(Generated),[8 Problem.D]) && ...
        all(SampleTrace.projectionRate == 0) && ...
        SampleTrace.sampleSigma == 1);
    rng(991,'twister');
    [SigmaOne,~] = PairBoundaryWGAN_RC( ...
        'sample',Model,QueryC(1:8,:),Problem,WGANOptions);
    HalfOptions = WGANOptions;
    HalfOptions.sampleSigma = 0.5;
    rng(991,'twister');
    [SigmaHalf,HalfTrace] = PairBoundaryWGAN_RC( ...
        'sample',Model,QueryC(1:8,:),Problem,HalfOptions);
    rng(991,'twister');
    [SigmaOneReplay,~] = PairBoundaryWGAN_RC( ...
        'sample',Model,QueryC(1:8,:),Problem,WGANOptions);
    assert(isequaln(SigmaOne,SigmaOneReplay) && ...
        HalfTrace.sampleSigma == 0.5 && ...
        any(abs(SigmaOne-SigmaHalf) > 0,'all'));

    %% Later events continue weights and Adam state, then use them directly
    UpdatedData = Data;
    UpdatedData.lastFE(1:8) = UpdatedData.lastFE(1:8)+1;
    ContinueOptions = WGANOptions;
    ContinueOptions.pairRetrainChanges = 8;
    previousIterG = Model.iterG;
    [Continued,ContinueStatus] = PairBoundaryWGAN_RC( ...
        'trainifneeded',Model,UpdatedData,Gate,Problem,ContinueOptions);
    assert(ContinueStatus.trained && ContinueStatus.useModel && ...
        ContinueStatus.trainingPairs == UpdatedData.count && ...
        Continued.iterG == previousIterG+ContinueStatus.updates && ...
        ContinueStatus.trainingKind == "retrain" && ...
        ContinueStatus.epochs == 1 && ...
        ContinueStatus.reason == "trained");
    fprintf('CBS PairGuide comparator test passed.\n');
end

function testArchiveLifecycleAndReferenceFreedom()
%TESTARCHIVELIFECYCLEANDREFERENCEFREEDOM Lock the persistent-pair rules.

    Problem = DASCMOP1_BC('N',2,'D',5,'maxFE',100);
    W = [1 0;0 1];
    xf = [0.20*ones(1,Problem.D);0.80*ones(1,Problem.D)];
    yf = [0 1;1 0];
    cross = xf(1,:)+0.02;
    sameRef = xf(1,:)+0.25;
    second = xf(2,:)-0.02;
    xi = [cross;sameRef;second];
    yi = [1 0;0 1;0 1];
    P1 = SOLUTION(xf,yf,zeros(2,1));
    Infeasible = SOLUTION(xi,yi,ones(3,1));
    Options = struct('pairMinPairs',1,'pairMinRegions',1, ...
        'pairArchivePerRef',5,'pairNeighborRefCount',0, ...
        'pairInactiveMaxAge',10,'pairSupportMultiplier',2);

    % New pair uses globally nearest real xi even when its ref differs.
    [Archive,~] = PairBoundaryArchive_RC('update',[],P1, ...
        [P1,Infeasible],W,Problem,Options,struct(),100);
    row = find(all(abs(Archive.xf-xf(1,:)) <= 1e-12,2),1);
    assert(~isempty(row) && ...
        norm(Archive.xi(row,:)-cross) <= 1e-12 && ...
        Archive.ref(row) == 2);
    pairId = Archive.id(row);

    % A feasible attributed child need not survive in P1 or share ref.
    zF = (Archive.xf(row,:)+Archive.xi(row,:))/2;
    Feedback = feedbackStruct(zF,[1 0],0,pairId);
    Guided = SOLUTION(zF,[1 0],0);
    [Archive,RefScale,TraceF] = PairBoundaryArchive_RC('update', ...
        Archive,P1,[P1,Guided],W,Problem,Options,Feedback,200);
    row = find(Archive.id == pairId,1);
    assert(TraceF.tightenedFeasible > 0 && ...
        norm(Archive.xf(row,:)-zF) <= 1e-12 && ...
        ~any(all(abs(double(P1.decs)-zF) <= 1e-12,2)) && ...
        Archive.ref(row) == AssignReferenceVectors_CBS([1 0],W,RefScale));

    % An infeasible attributed child may cross ref; xi never owns pair.ref.
    oldRef = Archive.ref(row);
    zI = (Archive.xf(row,:)+Archive.xi(row,:))/2;
    Feedback = feedbackStruct(zI,[0 1],1,pairId);
    Guided = SOLUTION(zI,[0 1],1);
    [Archive,~,TraceI] = PairBoundaryArchive_RC('update',Archive,P1, ...
        [P1,Guided],W,Problem,Options,Feedback,300);
    row = find(Archive.id == pairId,1);
    assert(TraceI.tightenedInfeasible > 0 && ...
        norm(Archive.xi(row,:)-zI) <= 1e-12 && ...
        Archive.ref(row) == oldRef);

    Single = archiveRow(Archive,row);
    fixedXf = Single.xf;
    [Single,~] = PairBoundaryArchive_RC('update',Single,[],[], ...
        W,Problem,Options,struct(),400);
    assert(~Single.active && Single.age == 1);

    % Nearby, nonidentical P1 elites support the stored xf without owning it.
    supportX = [fixedXf+0.01;fixedXf-0.01];
    SupportP1 = SOLUTION(supportX,[0 1;1 0],zeros(2,1));
    [Single,~] = PairBoundaryArchive_RC('update',Single,SupportP1,[], ...
        W,Problem,Options,struct(),500);
    assert(Single.active && Single.age == 0 && ...
        norm(Single.xf-fixedXf) <= 1e-12 && ...
        ~any(all(abs(supportX-fixedXf) <= 1e-12,2)));

    % Inactive pairs remain updateable and revive on strict real tightening.
    [Single,~] = PairBoundaryArchive_RC('update',Single,[],[], ...
        W,Problem,Options,struct(),600);
    closer = (Single.xf+Single.xi)/2;
    Closer = SOLUTION(closer,[0 1],1);
    [Single,~,Revive] = PairBoundaryArchive_RC('update',Single,[],Closer, ...
        W,Problem,Options,struct(),700);
    assert(Single.active && Single.age == 0 && ...
        Revive.tightenedInfeasible > 0);

    % Exactly ten consecutive generations without evidence delete the pair.
    for generation = 1 : 9
        [Single,~] = PairBoundaryArchive_RC('update',Single,[],[], ...
            W,Problem,Options,struct(),700+generation);
    end
    assert(isscalar(Single.id) && ~Single.active && Single.age == 9);
    [Single,~] = PairBoundaryArchive_RC('update',Single,[],[], ...
        W,Problem,Options,struct(),710);
    assert(isempty(Single.id));
end

function Feedback = feedbackStruct(X,Y,C,id)
%FEEDBACKSTRUCT Construct one attributed, truly evaluated guide result.

    Feedback = struct('childDecs',X,'childObjs',Y,'childCons',C, ...
        'matchedPairIds',id);
end

function Archive = archiveRow(Archive,row)
%ARCHIVEROW Keep one persistent pair without changing the next ID.

    fields = {'id','xf','xi','yf','yi','ref','gap','age','lastFE','active'};
    for field = fields
        name = field{1};
        Archive.(name) = Archive.(name)(row,:);
    end
end
