function [FamilySummary,ProblemSummary] = analyze_PRBCCMO_t_suite(baseFolder)
% Analyze traced PRBCCMO suite outputs and export compact CSV summaries.

    if nargin < 1 || isempty(baseFolder)
        rootDir = fileparts(which('platemo'));
        baseFolder = fullfile(rootDir,'Data','PRBCCMO_t');
    end

    summaryFile = fullfile(baseFolder,'suite_summary.csv');
    summarize_PRBCCMO_t_data(baseFolder,summaryFile);
    familySummaryFile = fullfile(baseFolder,'suite_family_summary.csv');
    problemSummaryFile = fullfile(baseFolder,'suite_problem_ranked.csv');

    Summary = readtable(summaryFile);
    if isempty(Summary)
        FamilySummary = makeEmptyFamilySummaryTable();
        ProblemSummary = makeEmptyProblemSummaryTable();
        writetable(FamilySummary,familySummaryFile);
        writetable(ProblemSummary,problemSummaryFile);
        return;
    end

    requireColumns(Summary.Properties.VariableNames,{ ...
        'final_b_size','final_b_trusted_sector_coverage','final_b_trusted_lowmargin_count', ...
        'final_boundary_bal_acc','final_b_bal_acc','final_b_brier', ...
        'final_train_bal_acc_after','final_train_minus_boundary_bal_gap','final_train_minus_b_bal_gap', ...
        'mean_helper_real_opp_ratio','mean_helper_skip_no_helper','mean_boundary_attempts'}, ...
        'analyze_PRBCCMO_t_suite:SummaryColumns');

    targetMaxFE = max(Summary.maxFE);
    Summary = Summary(Summary.maxFE == targetMaxFE,:);
    [~,ord] = sort(Summary.run_datenum,'ascend');
    Summary = Summary(ord,:);
    [~,latestIdx] = unique(Summary.problem,'last');
    Summary = Summary(sort(latestIdx),:);

    family = repmat("Other",height(Summary),1);
    family(startsWith(string(Summary.problem),"DASCMOP")) = "DASCMOP_BC";
    family(startsWith(string(Summary.problem),"LIRCMOP")) = "LIRCMOP_BC";
    Summary.family = family;

    families = unique(family,'stable');
    rows = cell(numel(families),14);
    for i = 1 : numel(families)
        mask = family == families(i);
        rows(i,:) = { ...
            families(i), ...
            sum(mask), ...
            mean(Summary.final_b_size(mask),'omitnan'), ...
            mean(Summary.final_b_trusted_sector_coverage(mask),'omitnan'), ...
            mean(Summary.final_b_trusted_lowmargin_count(mask),'omitnan'), ...
            mean(Summary.final_boundary_bal_acc(mask),'omitnan'), ...
            mean(Summary.final_b_bal_acc(mask),'omitnan'), ...
            mean(Summary.final_b_brier(mask),'omitnan'), ...
            mean(Summary.final_train_bal_acc_after(mask),'omitnan'), ...
            mean(Summary.final_train_minus_boundary_bal_gap(mask),'omitnan'), ...
            mean(Summary.final_train_minus_b_bal_gap(mask),'omitnan'), ...
            mean(Summary.mean_helper_real_opp_ratio(mask),'omitnan'), ...
            mean(Summary.mean_helper_skip_no_helper(mask),'omitnan'), ...
            mean(Summary.mean_boundary_attempts(mask),'omitnan')};
    end

    FamilySummary = cell2table(rows,'VariableNames',{ ...
        'family','problem_count','mean_final_b_size', ...
        'mean_final_b_trusted_sector_coverage','mean_final_b_trusted_lowmargin_count', ...
        'mean_final_boundary_bal_acc','mean_final_b_bal_acc','mean_final_b_brier', ...
        'mean_final_train_bal_acc_after', ...
        'mean_final_train_minus_boundary_bal_gap','mean_final_train_minus_b_bal_gap', ...
        'mean_helper_real_opp_ratio','mean_helper_skip_no_helper','mean_boundary_attempts'});

    [~,ord] = sort(Summary.final_boundary_bal_acc,'ascend','MissingPlacement','last');
    ProblemSummary = Summary(ord,{ ...
        'family','problem','final_b_size','final_b_trusted_count', ...
        'final_b_trusted_sector_coverage','final_b_trusted_lowmargin_count', ...
        'final_lowmargin_count','final_boundary_bal_acc','final_b_bal_acc','final_b_brier', ...
        'final_train_bal_acc_after','final_train_minus_boundary_bal_gap', ...
        'final_train_minus_b_bal_gap', ...
        'mean_helper_real_opp_ratio','mean_helper_skip_no_helper','mean_boundary_attempts'});

    writetable(FamilySummary,familySummaryFile);
    writetable(ProblemSummary,problemSummaryFile);
end

function requireColumns(names,required,identifier)
    missing = required(~ismember(required,names));
    assert(isempty(missing),identifier, ...
        'Missing expected summary columns: %s', strjoin(missing,', '));
end

function T = makeEmptyFamilySummaryTable()
    names = { ...
        'family','problem_count','mean_final_b_size', ...
        'mean_final_b_trusted_sector_coverage','mean_final_b_trusted_lowmargin_count', ...
        'mean_final_boundary_bal_acc','mean_final_b_bal_acc','mean_final_b_brier', ...
        'mean_final_train_bal_acc_after','mean_final_train_minus_boundary_bal_gap', ...
        'mean_final_train_minus_b_bal_gap','mean_helper_real_opp_ratio', ...
        'mean_helper_skip_no_helper','mean_boundary_attempts'};
    types = { ...
        'string','double','double', ...
        'double','double', ...
        'double','double','double', ...
        'double','double', ...
        'double','double', ...
        'double','double'};
    T = table('Size',[0,numel(names)],'VariableTypes',types,'VariableNames',names);
end

function T = makeEmptyProblemSummaryTable()
    names = { ...
        'family','problem','final_b_size','final_b_trusted_count', ...
        'final_b_trusted_sector_coverage','final_b_trusted_lowmargin_count', ...
        'final_lowmargin_count','final_boundary_bal_acc','final_b_bal_acc','final_b_brier', ...
        'final_train_bal_acc_after','final_train_minus_boundary_bal_gap', ...
        'final_train_minus_b_bal_gap','mean_helper_real_opp_ratio', ...
        'mean_helper_skip_no_helper','mean_boundary_attempts'};
    types = { ...
        'string','string','double','double', ...
        'double','double', ...
        'double','double','double','double', ...
        'double','double', ...
        'double','double', ...
        'double','double'};
    T = table('Size',[0,numel(names)],'VariableTypes',types,'VariableNames',names);
end
