function [AllRuns,ScopeSummary,ProblemSummary] = analyze_PRBCCMO_t_innovation_suite(suiteDir)
% Analyze PRBCCMO_t benchmark shards with only core innovation observations.

    if nargin < 1 || isempty(suiteDir)
        rootDir = fileparts(which('platemo'));
        suiteDir = fullfile(rootDir,'Data','PRBCCMO_t','innovation_runs');
    end
    suiteDir = char(string(suiteDir));
    assert(isfolder(suiteDir), ...
        'analyze_PRBCCMO_t_innovation_suite:MissingSuiteDir', ...
        'Suite directory not found: %s', suiteDir);

    files = dir(fullfile(suiteDir,'run_*.csv'));
    assert(~isempty(files), ...
        'analyze_PRBCCMO_t_innovation_suite:MissingCsv', ...
        'No run_*.csv benchmark shards found in %s.', suiteDir);

    tables = arrayfun(@(f)readtable(fullfile(f.folder,f.name),'TextType','string'), ...
        files,'UniformOutput',false);
    AllRuns = vertcat(tables{:});
    AllRuns = appendCoreSummaries(AllRuns);
    if all(ismember({'family','problem','run'},AllRuns.Properties.VariableNames))
        AllRuns = sortrows(AllRuns,{'family','problem','run'});
    end
    writetable(AllRuns,fullfile(suiteDir,'benchmark_all.csv'));
    writetable(AllRuns,fullfile(suiteDir,'innovation_trace_runs.csv'));

    ScopeSummary = buildScopeSummary(AllRuns);
    writetable(ScopeSummary,fullfile(suiteDir,'innovation_summary.csv'));

    ProblemSummary = buildProblemSummary(AllRuns);
    writetable(ProblemSummary,fullfile(suiteDir,'innovation_problem_summary.csv'));
end

function Runs = appendCoreSummaries(Runs)
    assert(ismember('analysis_folder',Runs.Properties.VariableNames), ...
        'analyze_PRBCCMO_t_innovation_suite:MissingAnalysisFolder', ...
        'Benchmark shards must contain analysis_folder.');

    folders = cellstr(string(Runs.analysis_folder));
    summaries = cellfun(@summarize_PRBCCMO_t_run,folders,'UniformOutput',false);
    SummaryTable = struct2table([summaries{:}]');
    addNames = setdiff(SummaryTable.Properties.VariableNames,Runs.Properties.VariableNames,'stable');
    Runs = [Runs,SummaryTable(:,addNames)];
end

function Summary = buildScopeSummary(AllRuns)
    rows = summarizeRows(AllRuns,"overall","all");
    if ismember('family',AllRuns.Properties.VariableNames)
        families = unique(string(AllRuns.family),'stable')';
        familyRows = cell(numel(families),1);
        for i = 1 : numel(families)
            mask = string(AllRuns.family) == families(i);
            familyRows{i} = summarizeRows(AllRuns(mask,:),"family",families(i));
        end
        rows = [rows;vertcat(familyRows{:})];
    end
    Summary = rowsToSummaryTable(rows);
end

function Summary = buildProblemSummary(AllRuns)
    problems = unique(string(AllRuns.problem),'stable')';
    rows = cell(numel(problems),1);
    for i = 1 : numel(problems)
        mask = string(AllRuns.problem) == problems(i);
        rows{i} = summarizeRows(AllRuns(mask,:),"problem",problems(i));
    end
    Summary = rowsToSummaryTable(vertcat(rows{:}));
end

function Row = summarizeRows(T,Scope,Name)
    Row = { ...
        string(Scope),string(Name),height(T), ...
        meanColumn(T,'final_b_mean_pair_gap'), ...
        meanColumn(T,'mean_b_mean_pair_gap'), ...
        meanColumn(T,'p90_b_mean_pair_gap'), ...
        meanColumn(T,'final_b_p90_pair_gap'), ...
        meanColumn(T,'mlp_trained_events'), ...
        meanColumn(T,'final_mlp_train_acc'), ...
        meanColumn(T,'mean_mlp_train_acc'), ...
        meanColumn(T,'final_train_size'), ...
        meanColumn(T,'mean_train_size'), ...
        meanColumn(T,'final_train_src_refinement'), ...
        meanColumn(T,'final_train_src_boundary_band'), ...
        meanColumn(T,'inf_selection_generations'), ...
        meanColumn(T,'inf_selected_total'), ...
        meanColumn(T,'mean_inf_prob_gain'), ...
        meanColumn(T,'pos_rate_inf_prob_gain'), ...
        meanColumn(T,'inf_carry_generations'), ...
        meanColumn(T,'inf_carry_selected_total'), ...
        meanColumn(T,'mean_inf_carry_prob_gain'), ...
        meanColumn(T,'pos_rate_inf_carry_prob_gain')};
end

function Summary = rowsToSummaryTable(Rows)
    names = { ...
        'scope','name','n_runs', ...
        'mean_final_b_mean_pair_gap','mean_mean_b_mean_pair_gap','mean_p90_b_mean_pair_gap', ...
        'mean_final_b_p90_pair_gap','mean_mlp_trained_events', ...
        'mean_final_mlp_train_acc','mean_mean_mlp_train_acc', ...
        'mean_final_train_size','mean_mean_train_size', ...
        'mean_final_train_src_refinement','mean_final_train_src_boundary_band', ...
        'mean_inf_selection_generations','mean_inf_selected_total', ...
        'mean_inf_prob_gain','mean_pos_rate_inf_prob_gain', ...
        'mean_inf_carry_generations','mean_inf_carry_selected_total', ...
        'mean_inf_carry_prob_gain','mean_pos_rate_inf_carry_prob_gain'};
    Summary = cell2table(Rows,'VariableNames',names);
end

function value = meanColumn(T,Name)
    if ~ismember(Name,T.Properties.VariableNames)
        value = NaN;
        return;
    end
    values = double(T.(Name));
    values = values(isfinite(values));
    if isempty(values)
        value = NaN;
    else
        value = mean(values);
    end
end
