classdef PRBCCMO < ALGORITHM
% <2026> <multi> <real> <constrained>
% PRBCCMO
% MLP-driven boundary-information dual-population CCMO redesigned from fix.md
%
% type    --- 1    --- 1.GA, 2.DE
% hidden  --- 20   --- Hidden neurons of the boundary MLP
% epoch   --- 20   --- Training epochs per update
% lr      --- 0.01 --- Learning rate
% minPos  --- 5    --- Reserved compatibility parameter (unused by fix.md)
% minNeg  --- 20   --- Reserved compatibility parameter (unused by fix.md)
% kappa   --- 3    --- Maximum boundary-archive size per sector
% rhoPre  --- 0.08 --- Boundary-evaluation ratio before the MLP is ready
% rhoPost --- 0.15 --- Boundary-evaluation ratio after the MLP is ready
% gapMin  --- 3    --- Minimum model update gap
% gapMax  --- 10   --- Maximum model update gap
%
% PRBCCMO follows fix.md strictly:
%   1) P_C approaches CPF and P_U approaches UPF with shared offspring;
%   2) B stores top-k boundary-information samples per sector with soft
%      minority reservation;
%   3) the boundary MLP is warm-start updated from feasible anchors and
%      their local opposite infeasible pairs, while sectors no longer act
%      as training/archive/probe eligibility gates;
%   4) boundary offspring are generated by a single anchor-helper-probe
%      chain with fixed probe betas and helper candidates drawn only from
%      P_C union P_U;
%   5) archive update, model training, and probe ranking share the same
%      uncertainty + opposite-side support + objective relevance score,
%      while the MLP batch keeps a 1:1 replay-balanced class mix.

%------------------------------- Copyright --------------------------------
% Copyright (c) 2026 BIMK Group. You are free to use the PlatEMO for
% research purposes. All publications which use this platform or any code
% in the platform should acknowledge the use of "PlatEMO" and reference "Ye
% Tian, Ran Cheng, Xingyi Zhang, and Yaochu Jin, PlatEMO: A MATLAB platform
% for evolutionary multi-objective optimization [educational forum], IEEE
% Computational Intelligence Magazine, 2017, 12(4): 73-87".
%--------------------------------------------------------------------------

    methods
        function main(Algorithm,Problem)
            [W,Problem.N] = UniformPoint(Problem.N,Problem.M);
            [type,hidden,epoch,lr,minPos,minNeg,kappa, ...
                rhoPre,rhoPost,gapMin,gapMax] = ...
                Algorithm.ParameterSet(1,20,20,0.01,5,20,3,0.08,0.15,3,10);

            kappa = max(1,round(kappa));
            MaxTrain = max(6*Problem.N,4*size(W,1));
            ProbeBeta = [0.25;0.50;0.75;1.05];

            PopulationC = Problem.Initialization();
            PopulationU = Problem.Initialization();
            B           = PopulationC([]);
            Model       = [];
            RecentBoundaryOff = PopulationC([]);

            SectorNeighbors = BuildSectorNeighbors(W,min(max(3,2*Problem.M),max(size(W,1)-1,0)));
            TrainArchive    = InitTrainArchive(Problem.D);
            TrainArchive    = UpdateTrainArchive( ...
                TrainArchive,B,PopulationC,PopulationU,RecentBoundaryOff, ...
                W,SectorNeighbors,MaxTrain,0);
            Model           = UpdateBoundaryModelIfDue( ...
                Model,TrainArchive,minPos,minNeg,hidden,epoch,lr, ...
                ResolveModelUpdateGap(gapMin,gapMax,Problem.FE/max(Problem.maxFE,1)), ...
                0,SectorNeighbors,size(W,1),Problem.M);

            while Algorithm.NotTerminated(PopulationC)
                OffspringC = GenerateWithinOffspring(Problem,PopulationC,type,true);
                OffspringU = GenerateWithinOffspring(Problem,PopulationU,type,false);

                RemainingFE = max(0,Problem.maxFE-Problem.FE);

                SeedPool = KeepUniquePopulation([B,OffspringC,OffspringU]);
                [SeedB,~] = UpdateBoundaryArchive( ...
                    SeedPool,W,Model,PopulationC,PopulationU, ...
                    TrainArchive,SectorNeighbors,kappa);

                BoundaryBudget = ResolveBoundaryBudget( ...
                    Problem.N,rhoPre,rhoPost,RemainingFE,HasBoundaryModel(Model));
                BoundaryOff = GenerateBoundaryOffspringModelDriven( ...
                    Problem,PopulationC,PopulationU,SeedB,W,SectorNeighbors,Model, ...
                    TrainArchive,BoundaryBudget,ProbeBeta);
                BoundaryOff = KeepUniquePopulation(BoundaryOff);

                CandidateB = KeepUniquePopulation([SeedPool,BoundaryOff]);
                [B,~] = UpdateBoundaryArchive( ...
                    CandidateB,W,Model,PopulationC,PopulationU, ...
                    TrainArchive,SectorNeighbors,kappa);

                QC = KeepUniquePopulation([PopulationC,OffspringC,OffspringU,BoundaryOff]);
                QU = KeepUniquePopulation([PopulationU,OffspringC,OffspringU,BoundaryOff]);
                PopulationC = EnvironmentalSelectionC(QC,Problem.N,W);
                PopulationU = EnvironmentalSelectionU(QU,Problem.N,W);

                RecentBoundaryOff = BoundaryOff;
                TrainArchive = UpdateTrainArchive( ...
                    TrainArchive,B,PopulationC,PopulationU,RecentBoundaryOff, ...
                    W,SectorNeighbors,MaxTrain,Problem.FE);
                Model = UpdateBoundaryModelIfDue( ...
                    Model,TrainArchive,minPos,minNeg,hidden,epoch,lr, ...
                    ResolveModelUpdateGap(gapMin,gapMax,Problem.FE/max(Problem.maxFE,1)), ...
                    Problem.FE,SectorNeighbors,size(W,1),Problem.M);
            end
        end
    end
end

%% ========== Main-population offspring ==========

function Offspring = GenerateWithinOffspring(Problem,Population,type,isConstraintSide)
    if isempty(Population)
        Offspring = [];
        return;
    end

    N = numel(Population);
    if isConstraintSide
        [Flag,FrontNo,CrowdDis] = ConstraintSideIndicator(Population);
        MatingPool = TournamentSelection(2,2*N,Flag,FrontNo,-CrowdDis);
    else
        [FrontNo,CrowdDis] = ObjectiveSideIndicator(Population);
        MatingPool = TournamentSelection(2,2*N,FrontNo,-CrowdDis);
    end

    if type == 1
        Offspring = OperatorGAhalf(Problem,Population(MatingPool));
    else
        Offspring = OperatorDE(Problem,Population, ...
            Population(MatingPool(1:N)),Population(MatingPool(N+1:end)));
    end
end

%% ========== Main loop helpers ==========

function Budget = ResolveBoundaryBudget(N,rhoPre,rhoPost,RemainingFE,ModelReady)
    if ModelReady
        Ratio = rhoPost;
    else
        Ratio = rhoPre;
    end
    Ratio  = max(0,min(0.5,double(Ratio)));
    Budget = floor(Ratio*N);
    Budget = min(max(0,Budget),max(0,RemainingFE));
end

function Gap = ResolveModelUpdateGap(gapMin,gapMax,FERatio)
    Gap = floor(double(gapMin) + (double(gapMax)-double(gapMin))*FERatio);
    Gap = max(1,Gap);
end

function Model = UpdateBoundaryModelIfDue( ...
    Model,TrainArchive,minPos,minNeg,hidden,epoch,lr,Gap,Tick, ...
    SectorNeighbors,K,M)
    if ~CanTrainBoundaryModel(TrainArchive,minPos,minNeg,SectorNeighbors,K,M)
        return;
    end

    if isempty(Model) || mod(Tick,Gap) == 0
        Model = TrainBoundaryMLP( ...
            TrainArchive,hidden,epoch,lr,Model);
    end
end

function Flag = HasBoundaryModel(Model)
    Flag = ~isempty(Model) && isfield(Model,'Mu');
end

%% ========== Boundary archive and generation ==========

function [B,Meta] = UpdateBoundaryArchive( ...
    CandidateB,W,Model,PopulationC,PopulationU,TrainArchive,SectorNeighbors,kappa)
    if isempty(CandidateB)
        B    = CandidateB;
        Meta = InitBoundaryMeta(0);
        return;
    end

    CandidateB = KeepUniquePopulation(CandidateB);
    Meta       = BuildBoundaryMeta( ...
        CandidateB,W,Model,PopulationC,PopulationU,TrainArchive,SectorNeighbors);
    BridgeMask = ResolveBridgeBoundaryMask(Meta,TrainArchive,SectorNeighbors,size(W,1));
    B          = SelectTopKPerSector(CandidateB,Meta,BridgeMask,kappa);
end

function Meta = BuildBoundaryMeta( ...
    Candidates,W,Model,PopulationC,PopulationU,TrainArchive,SectorNeighbors)
    N = numel(Candidates);
    Meta = InitBoundaryMeta(N);
    if isempty(Candidates)
        return;
    end

    RefObj = BuildReferenceObj(Candidates,PopulationC,PopulationU);
    [Sector,~] = AssociateSectorsLocal(Candidates.objs,W,RefObj);
    [Prob,~]   = PredictBoundaryMLP(Model,Candidates.decs);
    Margin     = 2*abs(Prob(:)-0.5);
    ObjScore   = ComputeBoundaryObjectiveScore(Candidates,PopulationC,W,RefObj,Sector);
    Support = BuildBoundarySupportSet(TrainArchive);
    Label = double(all(Candidates.cons<=0,2));
    OppDist = ComputeOppositeDistanceByLabel( ...
        Candidates.decs,Label,Sector,Support.Dec,Support.Label, ...
        Support.Sector,SectorNeighbors);
    TauD = ResolveDistanceScale(Support.Dec);
    OppSupport = exp(-OppDist./max(TauD,1e-6));
    OppSupport(~isfinite(OppDist)) = 0;
    OppSupport = max(0,min(1,OppSupport));

    Meta.sector     = Sector(:);
    Meta.prob       = Prob(:);
    Meta.margin     = Margin(:);
    Meta.objScore   = ObjScore(:);
    Meta.oppSupport = OppSupport(:);
    Meta.oppDist    = OppDist(:);
    Meta.feasible   = Label(:);
    Meta.trusted    = true(N,1);
    Meta.bridgeGrowth = false(N,1);
    Meta.score      = 0.50*Margin(:) + 0.30*(1-OppSupport(:)) + 0.20*ObjScore(:);
end

function Meta = InitBoundaryMeta(N)
    Meta = struct( ...
        'sector',zeros(N,1), ...
        'prob',0.5*ones(N,1), ...
        'margin',zeros(N,1), ...
        'objScore',zeros(N,1), ...
        'oppSupport',zeros(N,1), ...
        'oppDist',inf(N,1), ...
        'feasible',zeros(N,1), ...
        'trusted',false(N,1), ...
        'bridgeGrowth',false(N,1), ...
        'score',zeros(N,1));
end

function BridgeMask = ResolveBridgeBoundaryMask(Meta,~,~,~)
    BridgeMask = true(numel(Meta.sector),1);
end

function Flag = HasRealLocalOppositeSupport(Meta,idx)
    Flag = idx > 0 && idx <= numel(Meta.oppDist) && ...
           isfinite(Meta.oppDist(idx));
end

function B = SelectTopKPerSector(Candidates,Meta,BridgeMask,kappa)
    if isempty(Candidates)
        B = Candidates;
        return;
    end

    Pick = zeros(0,1);
    for s = unique(Meta.sector(Meta.sector > 0))'
        idx = find(Meta.sector == s & BridgeMask(:));
        if isempty(idx)
            continue;
        end
        Key = BuildSupportAwareBoundaryKey(Meta,idx);
        [~,ord] = sortrows(Key,1:size(Key,2));
        Sel = idx(ord(1:min(kappa,numel(idx))));

        Label = Meta.feasible(idx);
        if any(Label == 1) && any(Label == 0)
            SelLabel = Meta.feasible(Sel);
            if isscalar(unique(SelLabel))
                Majority = SelLabel(1);
                OppIdx = idx(Label ~= Majority);
                if ~isempty(OppIdx)
                    AltKey = BuildSupportAwareBoundaryKey(Meta,OppIdx);
                    [~,altOrd] = sortrows(AltKey,1:size(AltKey,2));
                    Alt = OppIdx(altOrd(1));

                    WorstKey = BuildSupportAwareBoundaryKey(Meta,Sel);
                    [~,worstOrd] = sortrows(WorstKey,-1:-1:-size(WorstKey,2));
                    if ShouldReserveOppositeSide(Meta,Alt,Sel(worstOrd(1)))
                        Sel(worstOrd(1)) = Alt;
                    end
                end
            end
        end
        Pick = [Pick;Sel(:)]; %#ok<AGROW>
    end

    if isempty(Pick)
        B = Candidates([]);
    else
        B = Candidates(unique(Pick,'stable'));
    end
end

function Key = BuildSupportAwareBoundaryKey(Meta,idx)
    idx = idx(:);
    if isempty(idx)
        Key = zeros(0,6);
        return;
    end

    bestOpp = max(Meta.oppSupport(idx));
    supportGap = max(0,bestOpp-Meta.oppSupport(idx));
    Key = [ ...
        Meta.score(idx), ...
        supportGap(:), ...
        1-Meta.oppSupport(idx), ...
        Meta.margin(idx), ...
        Meta.objScore(idx), ...
        idx];
end

function Flag = ShouldReserveOppositeSide(Meta,AltIdx,WorstIdx)
    scoreGap = Meta.score(AltIdx) - Meta.score(WorstIdx);
    supportGain = Meta.oppSupport(AltIdx) - Meta.oppSupport(WorstIdx);
    Flag = HasRealLocalOppositeSupport(Meta,AltIdx) && ...
        (scoreGap <= 0.20 || supportGain >= 0.15);
end

function Offspring = GenerateBoundaryOffspringModelDriven( ...
    Problem,PopulationC,PopulationU,B,W,SectorNeighbors,Model,TrainArchive, ...
    Budget,ProbeBeta)

    if isempty(B)
        Offspring = PopulationC([]);
        return;
    end
    if Budget <= 0
        Offspring = B([]);
        return;
    end

    ArchiveMeta = BuildBoundaryMeta( ...
        B,W,Model,PopulationC,PopulationU,TrainArchive,SectorNeighbors);
    Pool        = KeepUniquePopulation([PopulationC,PopulationU]);
    PoolMeta    = BuildBoundaryMeta( ...
        Pool,W,Model,PopulationC,PopulationU,TrainArchive,SectorNeighbors);
    Support     = BuildBoundarySupportSet(TrainArchive);
    CoreSupport = Support;
    SectorOrder = RankBoundarySectors(ArchiveMeta);
    if isempty(SectorOrder)
        Offspring = B([]);
        return;
    end

    ProbeDecAll = zeros(0,Problem.D);
    MaxAttempt  = max(Budget,1)*max(numel(SectorOrder),1)*3;
    Attempt     = 0;
    PoolDec     = zeros(0,Problem.D);
    if ~isempty(Pool)
        PoolDec = [PoolDec;Pool.decs];
    end
    if ~isempty(B)
        PoolDec = [PoolDec;B.decs];
    end

    while size(ProbeDecAll,1) < Budget && Attempt < MaxAttempt
        s = SectorOrder(mod(Attempt,numel(SectorOrder))+1);
        Attempt = Attempt + 1;

        [Anchor,AnchorMeta,HasAnchor] = SelectBoundaryAnchor(B,ArchiveMeta,s);
        if ~HasAnchor
            continue;
        end

        [Helper,HelperMeta,HasHelper] = SelectBoundaryHelper( ...
            Anchor,AnchorMeta,Pool,PoolMeta,s,SectorNeighbors,Model);
        if ~HasHelper
            continue;
        end

        [ProbeDec,Beta] = BuildBoundaryProbeDecisions( ...
            Problem,Anchor.decs,Helper.decs,ProbeBeta);
        Support = CoreSupport;
        Support = AppendSupportPair(Support,Anchor,AnchorMeta,Helper,HelperMeta);
        [~,Score] = RankBoundaryProbeCandidates( ...
            Model,ProbeDec,Beta,Anchor,AnchorMeta,Helper,HelperMeta,Support,SectorNeighbors);
        [~,best]  = min(Score);
        Candidate = ProbeDec(best,:);

        if ~isempty(PoolDec) && ismember(Candidate,PoolDec,'rows')
            continue;
        end
        if ~isempty(ProbeDecAll) && ismember(Candidate,ProbeDecAll,'rows')
            continue;
        end
        ProbeDecAll(end+1,:) = Candidate; %#ok<AGROW>
    end

    if isempty(ProbeDecAll)
        Offspring = B([]);
    else
        Offspring = Problem.Evaluation(ProbeDecAll);
    end
end

function SectorOrder = RankBoundarySectors(Meta)
    SectorOrder = zeros(1,0);
    Sectors = unique(Meta.sector(Meta.sector > 0))';
    if isempty(Sectors)
        return;
    end

    Key = zeros(numel(Sectors),3);
    for i = 1 : numel(Sectors)
        idx      = find(Meta.sector == Sectors(i));
        Key(i,1) = min(Meta.score(idx));
        Key(i,2) = min(Meta.margin(idx));
        Key(i,3) = Sectors(i);
    end
    [~,ord]  = sortrows(Key,[1 2 3]);
    SectorOrder = Sectors(ord);
end

function [Anchor,AnchorMeta,Found] = SelectBoundaryAnchor(B,Meta,sector)
    Empty = B([]);
    idx   = find(Meta.sector == sector);
    if isempty(idx)
        Anchor     = Empty;
        AnchorMeta = InitBoundaryMeta(0);
        Found      = false;
        return;
    end

    Key = BuildSupportAwareBoundaryKey(Meta,idx);
    [~,ord] = sortrows(Key,1:size(Key,2));
    Pick    = idx(ord(1));
    Anchor  = B(Pick);
    AnchorMeta = ExtractBoundaryMetaRow(Meta,Pick);
    Found   = true;
end

function [Helper,HelperMeta,Found] = SelectBoundaryHelper( ...
    Anchor,AnchorMeta,Pool,PoolMeta,sector,SectorNeighbors,Model)
    %#ok<INUSD>

    Empty    = Pool([]);
    Allowed  = ~ismember(Pool.decs,Anchor.decs,'rows');
    idx = find(Allowed);
    if isempty(idx)
        Helper     = Empty;
        HelperMeta = InitBoundaryMeta(0);
        Found      = false;
        return;
    end

    AnchorLabel = double(all(Anchor.cons<=0,2));
    Label       = double(all(Pool.cons<=0,2));
    OppReal     = idx(Label(idx) ~= AnchorLabel);
    if ~isempty(OppReal)
        Pick = PickBestHelper(OppReal,PoolMeta);
        Helper     = Pool(Pick);
        HelperMeta = ExtractBoundaryMetaRow(PoolMeta,Pick);
        Found      = true;
        return;
    end

    Helper     = Empty;
    HelperMeta = InitBoundaryMeta(0);
    Found      = false;
end

function Pick = PickBestHelper(idx,Meta)
    Key = BuildSupportAwareBoundaryKey(Meta,idx);
    [~,ord] = sortrows(Key,1:size(Key,2));
    Pick    = idx(ord(1));
end

function Row = ExtractBoundaryMetaRow(Meta,idx)
    Row = InitBoundaryMeta(1);
    Row.sector     = Meta.sector(idx);
    Row.prob       = Meta.prob(idx);
    Row.margin     = Meta.margin(idx);
    Row.objScore   = Meta.objScore(idx);
    Row.oppSupport = Meta.oppSupport(idx);
    Row.oppDist    = Meta.oppDist(idx);
    Row.feasible   = Meta.feasible(idx);
    Row.trusted    = Meta.trusted(idx);
    Row.score      = Meta.score(idx);
end

function [ProbeDec,Beta] = BuildBoundaryProbeDecisions( ...
    Problem,AnchorDec,HelperDec,FixedBeta)

    Beta = FixedBeta(:);
    Span     = double(Problem.upper - Problem.lower);
    Span(Span < 1e-12) = 1;
    RealIdx  = find(Problem.encoding <= 2);
    OtherIdx = setdiff(1:Problem.D,RealIdx);

    ProbeDec = zeros(numel(Beta),Problem.D);
    for i = 1 : numel(Beta)
        Base = AnchorDec + Beta(i)*(HelperDec-AnchorDec);
        Dec  = Base;
        if ~isempty(RealIdx)
            Dec(RealIdx) = Base(RealIdx) + 0.05*randn(1,numel(RealIdx)).*Span(RealIdx);
        end
        if ~isempty(OtherIdx)
            if Beta(i) <= 0.5
                Dec(OtherIdx) = AnchorDec(OtherIdx);
            else
                Dec(OtherIdx) = HelperDec(OtherIdx);
            end
        end
        ProbeDec(i,:) = Problem.CalDec(Dec);
    end
end

function [Prob,Score] = RankBoundaryProbeCandidates( ...
    Model,ProbeDec,Beta,Anchor,AnchorMeta,Helper,HelperMeta,Support,SectorNeighbors)
    if isempty(ProbeDec)
        Prob  = zeros(0,1);
        Score = zeros(0,1);
        return;
    end

    [Prob,~] = PredictBoundaryMLP(Model,ProbeDec);
    Margin = 2*abs(Prob(:)-0.5);
    Sector = AnchorMeta.sector*ones(size(ProbeDec,1),1);
    AnchorLabel = double(all(Anchor.cons<=0,2));
    HelperLabel = double(all(Helper.cons<=0,2));
    ProxyLabel  = BuildProbeProxyLabels(Beta,AnchorLabel,HelperLabel);

    OppDist = ComputeOppositeDistanceByLabel( ...
        ProbeDec,ProxyLabel,Sector,Support.Dec,Support.Label, ...
        Support.Sector,SectorNeighbors);
    TauD = ResolveDistanceScale(Support.Dec);
    OppSupport = exp(-OppDist./max(TauD,1e-6));
    OppSupport(~isfinite(OppDist)) = 0;
    OppSupport = max(0,min(1,OppSupport));

    Mix = min(max(Beta(:),0),1);
    ObjScore = (1-Mix)*AnchorMeta.objScore + Mix*HelperMeta.objScore;
    ObjScore = max(0,min(1,ObjScore));
    Score = 0.50*Margin(:) + 0.30*(1-OppSupport(:)) + 0.20*ObjScore(:);
end

function ProxyLabel = BuildProbeProxyLabels(Beta,AnchorLabel,HelperLabel)
    ProxyLabel = AnchorLabel*ones(numel(Beta),1);
    ProxyLabel(Beta(:) >= 0.5) = HelperLabel;
end

%% ========== Training archive ==========

function TrainArchive = InitTrainArchive(D)
    TrainArchive = struct( ...
        'Dec',zeros(0,D), ...
        'Label',zeros(0,1), ...
        'Source',zeros(0,1), ...
        'Sector',zeros(0,1), ...
        'Time',zeros(0,1), ...
        'Weight',zeros(0,1)); % 1:B evidence, 2:recent boundary evidence, 3:P_C feasible anchor, 4:P_U paired infeasible
end

function TrainArchive = UpdateTrainArchive( ...
    TrainArchive,B,PopulationC,PopulationU,RecentBoundaryOff,W, ...
    ~,MaxTrain,Stamp)

    RefObj = BuildReferenceObj(B,PopulationC,PopulationU,RecentBoundaryOff);
    if isempty(RefObj)
        RefObj = BuildReferenceObj(PopulationC,PopulationU,B);
    end

    kNeg      = 2;
    MinAnchor = max(2,size(W,2));
    [Candidates,Source,Weight] = BuildAnchorPairTrainPopulation( ...
        B,RecentBoundaryOff,PopulationC,PopulationU,W,RefObj,kNeg,MinAnchor);
    Meta = BuildTrainMeta(Candidates,Source,W,RefObj,Stamp,Weight);
    TrainArchive = AppendTrainArchiveWithMeta(TrainArchive,Candidates,Meta);
    TrainArchive = TrimTrainArchiveByAnchorPairs(TrainArchive,MaxTrain,kNeg);
end

function TrainArchive = AppendTrainArchiveWithMeta(TrainArchive,Population,Meta)
    if isempty(Population)
        return;
    end

    TrainArchive.Dec         = [TrainArchive.Dec;Population.decs];
    TrainArchive.Label       = [TrainArchive.Label;double(all(Population.cons<=0,2))];
    TrainArchive.Source      = [TrainArchive.Source;Meta.source(:)];
    TrainArchive.Sector      = [TrainArchive.Sector;Meta.sector(:)];
    TrainArchive.Time        = [TrainArchive.Time;Meta.time(:)];
    TrainArchive.Weight      = [TrainArchive.Weight;Meta.weight(:)];

    Keep = KeepLatestDecisionRowsLocal(TrainArchive.Dec);
    TrainArchive.Dec         = TrainArchive.Dec(Keep,:);
    TrainArchive.Label       = TrainArchive.Label(Keep);
    TrainArchive.Source      = TrainArchive.Source(Keep);
    TrainArchive.Sector      = TrainArchive.Sector(Keep);
    TrainArchive.Time        = TrainArchive.Time(Keep);
    TrainArchive.Weight      = TrainArchive.Weight(Keep);
end

function Meta = BuildTrainMeta(Candidates,Source,W,RefObj,Stamp,Weight)
    N = numel(Candidates);
    Meta = struct( ...
        'source',Source(:), ...
        'sector',zeros(N,1), ...
        'time',Stamp*ones(N,1), ...
        'weight',Weight(:));
    if isempty(Candidates)
        return;
    end

    Sector = AssociateSectorsLocal(Candidates.objs,W,RefObj);
    Meta.sector = Sector(:);
end

function TrainArchive = TrimTrainArchiveByAnchorPairs(TrainArchive,MaxTrain,kNeg)
    Count = size(TrainArchive.Dec,1);
    if Count <= MaxTrain
        return;
    end

    Keep = ReserveAnchorPairs(TrainArchive,MaxTrain,kNeg);
    TrainArchive.Dec         = TrainArchive.Dec(Keep,:);
    TrainArchive.Label       = TrainArchive.Label(Keep);
    TrainArchive.Source      = TrainArchive.Source(Keep);
    TrainArchive.Sector      = TrainArchive.Sector(Keep);
    TrainArchive.Time        = TrainArchive.Time(Keep);
    TrainArchive.Weight      = TrainArchive.Weight(Keep);
end

function Pick = ReserveAnchorPairs(TrainArchive,MaxTrain,kNeg)
    Pick = zeros(0,1);
    Count = size(TrainArchive.Dec,1);
    if Count == 0 || MaxTrain <= 0
        return;
    end
    if Count <= MaxTrain
        Pick = (1:Count)';
        return;
    end

    AnchorIdx = find(TrainArchive.Label == 1);
    if isempty(AnchorIdx) || ~any(TrainArchive.Label == 0)
        Pick = AnchorIdx(:);
        return;
    end

    AnchorPick = AnchorIdx(:);
    NegPick    = SelectNearestNegativeRows(TrainArchive,AnchorPick,kNeg, ...
        max(0,MaxTrain-numel(AnchorPick)));
    Pick       = unique([AnchorPick(:);NegPick(:)],'stable');
end

function Flag = CanTrainBoundaryModel(TrainArchive,~,~,~,~,M)
    if isempty(TrainArchive.Dec)
        Flag = false;
        return;
    end

    AnchorCnt = sum(TrainArchive.Label == 1);
    PairCnt   = sum(TrainArchive.Weight(TrainArchive.Label == 0));
    Flag = AnchorCnt >= max(2,M) && PairCnt >= max(4,2*M);
end

%% ========== Boundary MLP ==========

function Model = TrainBoundaryMLP(TrainArchive,Hidden,Epoch,LR,PrevModel)
    if nargin < 5
        PrevModel = [];
    end
    Model = PrevModel;

    X = double(TrainArchive.Dec);
    Y = double(TrainArchive.Label(:) > 0);
    if isempty(X) || size(X,1) < 4
        return;
    end
    if numel(unique(Y)) < 2
        return;
    end

    Hidden    = max(2,round(Hidden));
    Epoch     = max(1,round(Epoch));
    LR        = max(double(LR),1e-4);
    [~,D]     = size(X);
    LambdaReg = 1e-4;

    Weight = ones(size(X,1),1);
    if isfield(TrainArchive,'Weight') && numel(TrainArchive.Weight) == size(X,1)
        Weight = max(1,round(TrainArchive.Weight(:)));
    end

    PosIdx = find(Y > 0);
    NegIdx = ExpandWeightedTrainRows(find(Y == 0),Weight(Y == 0));
    if isempty(PosIdx) || isempty(NegIdx)
        return;
    end

    Mu    = mean(X,1);
    Sigma = std(X,0,1);
    Sigma(Sigma < 1e-12) = 1;

    if ~isempty(PrevModel) && IsWarmStartCompatible(PrevModel,D,Hidden)
        W1 = PrevModel.W1;
        b1 = PrevModel.b1;
        W2 = PrevModel.W2;
        b2 = PrevModel.b2;
    else
        W1 = 0.1*randn(D,Hidden);
        b1 = zeros(1,Hidden);
        W2 = 0.1*randn(Hidden,1);
        b2 = 0;
    end

    Xn = (X-Mu)./Sigma;
    for e = 1 : Epoch
        BatchIdx = BuildBalancedReplayBatch(PosIdx,NegIdx);
        if isempty(BatchIdx)
            return;
        end

        Xb = Xn(BatchIdx,:);
        Yb = Y(BatchIdx);
        Nb = size(Xb,1);

        H = tanh(Xb*W1 + repmat(b1,Nb,1));
        Z = H*W2 + b2;
        P = 1./(1+exp(-Z));

        Delta2 = (P-Yb)./max(Nb,1);
        dW2 = H'*Delta2 + LambdaReg*W2;
        db2 = sum(Delta2);

        D1  = (Delta2*W2').*(1-H.^2);
        dW1 = Xb'*D1 + LambdaReg*W1;
        db1 = sum(D1,1);

        Step = LR/sqrt(e);
        W1 = W1 - Step*dW1;
        b1 = b1 - Step*db1;
        W2 = W2 - Step*dW2;
        b2 = b2 - Step*db2;
    end

    Model = struct('Mu',Mu,'Sigma',Sigma,'W1',W1,'b1',b1,'W2',W2,'b2',b2);
end

function [Prob,Stats] = PredictBoundaryMLP(Model,X)
    if nargin < 2 || isempty(X)
        Prob  = zeros(0,1);
        Stats = struct('logit',zeros(0,1));
        return;
    end
    if isempty(Model) || ~isfield(Model,'Mu')
        Prob  = 0.5*ones(size(X,1),1);
        Stats = struct('logit',zeros(size(X,1),1));
        return;
    end

    Xn = (double(X)-Model.Mu)./Model.Sigma;
    H  = tanh(Xn*Model.W1 + repmat(Model.b1,size(Xn,1),1));
    Z = H*Model.W2 + Model.b2;
    Prob = 1./(1+exp(-Z));
    Prob = min(max(Prob,1e-6),1-1e-6);
    Stats = struct('logit',Z(:));
end

function Flag = IsWarmStartCompatible(Model,D,Hidden)
    Flag = ~isempty(Model) && isfield(Model,'W1') && isfield(Model,'W2') && ...
           size(Model.W1,1) == D && size(Model.W1,2) == Hidden && ...
           size(Model.W2,1) == Hidden;
end

function Expanded = ExpandWeightedTrainRows(Index,Weight)
    Expanded = zeros(0,1);
    if isempty(Index)
        return;
    end

    Weight = max(1,round(Weight(:)));
    Expanded = repelem(Index(:),Weight);
end

function BatchIdx = BuildBalancedReplayBatch(PosIdx,NegIdx)
    BatchIdx = zeros(0,1);
    if isempty(PosIdx) || isempty(NegIdx)
        return;
    end

    Target = max(1,numel(PosIdx));
    PosPick = PosIdx(randi(numel(PosIdx),Target,1));
    if numel(NegIdx) >= Target
        NegPick = NegIdx(randperm(numel(NegIdx),Target));
    else
        NegPick = NegIdx(randi(numel(NegIdx),Target,1));
    end
    BatchIdx = [PosPick(:);NegPick(:)];
    BatchIdx = BatchIdx(randperm(numel(BatchIdx)));
end

%% ========== Boundary geometry helpers ==========

function ObjScore = ComputeBoundaryObjectiveScore(Candidates,PopulationC,W,RefObj,Sector)
    N = numel(Candidates);
    ObjScore = zeros(N,1);
    if isempty(Candidates)
        return;
    end

    Scalar = ComputeSectorScalar(Candidates.objs,W,RefObj,Sector);
    [FrontNo,~] = NDSort(Candidates.objs,numel(Candidates));
    if isempty(FrontNo) || max(FrontNo) <= 1
        FrontScore = zeros(N,1);
    else
        FrontScore = (FrontNo(:)-1)/max(max(FrontNo)-1,1);
    end

    ScalarScore = zeros(N,1);
    for s = unique(Sector(:))'
        idx = find(Sector == s);
        if isempty(idx)
            continue;
        end
        Value = Scalar(idx);
        Denom = max(Value) - min(Value);
        if Denom > 1e-12
            ScalarScore(idx) = (Value-min(Value))/Denom;
        end
    end

    Dominated = false(N,1);
    RepC = BuildSectorRepresentatives(PopulationC,W,RefObj,[]);
    for i = 1 : N
        s = Sector(i);
        if s > 0 && s <= numel(RepC.has) && RepC.has(s)
            Dominated(i) = DominatesObjectiveRow( ...
                PopulationC(RepC.idx(s)).objs,Candidates(i).objs);
        end
    end

    ObjScore = 0.4*FrontScore + 0.4*ScalarScore + 0.2*double(Dominated);
    ObjScore = max(0,min(1,ObjScore));
end

function Support = BuildBoundarySupportSet(TrainArchive)
    D = size(TrainArchive.Dec,2);
    Support = struct( ...
        'Dec',zeros(0,D), ...
        'Label',zeros(0,1), ...
        'Sector',zeros(0,1));
    if isempty(TrainArchive.Dec)
        return;
    end

    Support.Dec    = TrainArchive.Dec;
    Support.Label  = TrainArchive.Label;
    Support.Sector = TrainArchive.Sector;
end

function Support = AppendSupportPair(Support,Anchor,AnchorMeta,Helper,HelperMeta)
    PairDec = [Anchor.decs;Helper.decs];
    PairLabel = [double(all(Anchor.cons<=0,2));double(all(Helper.cons<=0,2))];
    PairSector = [AnchorMeta.sector;HelperMeta.sector];

    Support.Dec    = [Support.Dec;PairDec];
    Support.Label  = [Support.Label;PairLabel];
    Support.Sector = [Support.Sector;PairSector];

    Keep = KeepLatestDecisionRowsLocal(Support.Dec);
    Support.Dec    = Support.Dec(Keep,:);
    Support.Label  = Support.Label(Keep);
    Support.Sector = Support.Sector(Keep);
end

function OppDist = ComputeOppositeDistanceByLabel( ...
    CandDec,CandLabel,CandSector,RefDec,RefLabel,RefSector,SectorNeighbors)
    OppDist = inf(size(CandDec,1),1);
    if isempty(CandDec) || isempty(RefDec)
        return;
    end

    for i = 1 : size(CandDec,1)
        Allowed = ResolveReferenceMask(CandSector(i),RefSector,SectorNeighbors);
        Opp = find(Allowed & RefLabel(:) ~= CandLabel(i));
        if isempty(Opp)
            continue;
        end
        Dist = sqrt(sum((RefDec(Opp,:) - CandDec(i,:)).^2,2));
        OppDist(i) = min(Dist);
    end
end

function Mask = ResolveReferenceMask(Sector,RefSector,SectorNeighbors)
    %#ok<INUSD>
    if isempty(RefSector)
        Mask = true(0,1);
        return;
    end
    Mask = true(numel(RefSector),1);
end

function Scale = ResolveDistanceScale(Dec)
    if isempty(Dec)
        Scale = 1;
        return;
    end
    Range = max(Dec,[],1) - min(Dec,[],1);
    Scale = norm(Range)/sqrt(max(size(Dec,2),1));
    if ~isfinite(Scale) || Scale < 1e-6
        Scale = 1;
    end
end

%% ========== Sector / representative tools ==========

function [Core,Source] = BuildCoreTrainPopulation(B,RecentBoundaryOff)
    Core = B([]);
    Source = zeros(0,1);
    if ~isempty(B)
        Core = [Core,B];
        Source = [Source;ones(numel(B),1)];
    end
    if ~isempty(RecentBoundaryOff)
        Core = [Core,RecentBoundaryOff];
        Source = [Source;2*ones(numel(RecentBoundaryOff),1)];
    end
    if isempty(Core)
        return;
    end
    Keep = KeepLatestDecisionRowsLocal(Core.decs);
    Core = Core(Keep);
    Source = Source(Keep);
end

function [Candidates,Source,Weight] = BuildAnchorPairTrainPopulation( ...
    B,RecentBoundaryOff,PopulationC,PopulationU,W,RefObj,kNeg,MinAnchor)
    [Core,CoreSource] = BuildCoreTrainPopulation(B,RecentBoundaryOff);
    CoreLabel = double(all(Core.cons<=0,2));

    AnchorPop    = Core(CoreLabel == 1);
    AnchorSource = CoreSource(CoreLabel == 1);
    NeedAnchor   = max(0,MinAnchor-numel(AnchorPop));
    if NeedAnchor > 0
        if ~isempty(AnchorPop)
            ExistingDec = AnchorPop.decs;
        elseif ~isempty(PopulationC)
            ExistingDec = zeros(0,size(PopulationC.decs,2));
        elseif ~isempty(Core)
            ExistingDec = zeros(0,size(Core.decs,2));
        elseif ~isempty(PopulationU)
            ExistingDec = zeros(0,size(PopulationU.decs,2));
        else
            ExistingDec = zeros(0,0);
        end
        ExtraAnchor = SelectFeasibleAnchorSupplements( ...
            PopulationC,W,RefObj,ExistingDec,NeedAnchor);
        if ~isempty(ExtraAnchor)
            AnchorPop    = [AnchorPop,PopulationC(ExtraAnchor)];
            AnchorSource = [AnchorSource;3*ones(numel(ExtraAnchor),1)];
        end
    end

    if isempty(AnchorPop)
        Candidates = Core([]);
        Source     = zeros(0,1);
        Weight     = zeros(0,1);
        return;
    end

    CoreNeg       = Core(CoreLabel == 0);
    CoreNegSource = CoreSource(CoreLabel == 0);
    [PairNeg,PairSource,PairWeight] = SelectAnchorOppositeShell( ...
        AnchorPop,CoreNeg,CoreNegSource,PopulationU,kNeg);

    Candidates = [AnchorPop,PairNeg];
    Source     = [AnchorSource;PairSource];
    Weight     = [ones(numel(AnchorPop),1);PairWeight];
    [Candidates,Source,Weight] = CollapseTrainPopulationEntries( ...
        Candidates,Source,Weight);
end

function AnchorIdx = SelectFeasibleAnchorSupplements( ...
    PopulationC,W,RefObj,ExistingDec,Need)
    AnchorIdx = zeros(0,1);
    if Need <= 0 || isempty(PopulationC)
        return;
    end

    FeasibleMask = all(PopulationC.cons<=0,2);
    if ~any(FeasibleMask)
        return;
    end

    Taken = false(numel(PopulationC),1);
    if ~isempty(ExistingDec)
        Taken = ismember(PopulationC.decs,ExistingDec,'rows');
    end

    Sector = AssociateSectorsLocal(PopulationC.objs,W,RefObj);
    Scalar = ComputeSectorScalar(PopulationC.objs,W,RefObj,Sector);
    Rep    = BuildSectorRepresentatives(PopulationC,W,RefObj,FeasibleMask);
    RepIdx = Rep.idx(Rep.has);
    RepIdx = RepIdx(~Taken(RepIdx));
    if ~isempty(RepIdx)
        Key = [Scalar(RepIdx), RepIdx(:)];
        [~,ord] = sortrows(Key,[1 2]);
        Use = RepIdx(ord(1:min(Need,numel(ord))));
        AnchorIdx = [AnchorIdx;Use(:)]; %#ok<AGROW>
        Taken(Use) = true;
    end

    if numel(AnchorIdx) >= Need
        return;
    end

    Rest = find(FeasibleMask & ~Taken);
    if isempty(Rest)
        return;
    end
    Key = [Scalar(Rest), ResolveTrainSourcePriority(3*ones(numel(Rest),1)), Rest(:)];
    [~,ord] = sortrows(Key,[1 2 3]);
    NeedMore = min(Need-numel(AnchorIdx),numel(ord));
    AnchorIdx = [AnchorIdx;Rest(ord(1:NeedMore))]; %#ok<AGROW>
end

function [PairNeg,PairSource,PairWeight] = SelectAnchorOppositeShell( ...
    AnchorPop,CoreNeg,CoreNegSource,PopulationU,kNeg)
    PairNeg    = AnchorPop([]);
    PairSource = zeros(0,1);
    PairWeight = zeros(0,1);
    if isempty(AnchorPop) || kNeg <= 0
        return;
    end

    SupplementNeg = PopulationU(any(PopulationU.cons>0,2));
    NegPool       = [CoreNeg,SupplementNeg];
    NegSource     = [CoreNegSource;4*ones(numel(SupplementNeg),1)];
    if isempty(NegPool)
        return;
    end

    NegDec   = NegPool.decs;
    UseCount = zeros(numel(NegPool),1);
    for i = 1 : numel(AnchorPop)
        Need = kNeg;
        AnchorDec = AnchorPop(i).decs;
        for src = [1 2 4]
            if Need <= 0
                break;
            end
            Local = find(NegSource == src);
            if isempty(Local)
                continue;
            end
            Dist = sqrt(sum((NegDec(Local,:) - AnchorDec).^2,2));
            Key  = [Dist(:), Local(:)];
            [~,ord] = sortrows(Key,[1 2]);
            Use = Local(ord(1:min(Need,numel(ord))));
            UseCount(Use) = UseCount(Use) + 1;
            Need = Need - numel(Use);
        end
    end

    Pick       = find(UseCount > 0);
    PairNeg    = NegPool(Pick);
    PairSource = NegSource(Pick);
    PairWeight = UseCount(Pick);
end

function [Population,Source,Weight] = CollapseTrainPopulationEntries( ...
    Population,Source,Weight)
    if isempty(Population)
        Source = zeros(0,1);
        Weight = zeros(0,1);
        return;
    end

    [~,Keep,Group] = unique(double(Population.decs),'rows','stable');
    Population = Population(Keep);
    Source     = Source(Keep);
    Weight     = accumarray(Group,Weight(:),[numel(Keep),1],@sum,0);

    Label = double(all(Population.cons<=0,2));
    Weight(Label == 1) = 1;
end

function Pick = SelectNearestNegativeRows(TrainArchive,AnchorPick,kNeg,MaxPick)
    Pick = zeros(0,1);
    if isempty(AnchorPick) || kNeg <= 0 || MaxPick <= 0
        return;
    end

    NegIdx = find(TrainArchive.Label == 0);
    if isempty(NegIdx)
        return;
    end

    NegDec = TrainArchive.Dec(NegIdx,:);
    Taken  = false(numel(NegIdx),1);
    for i = 1 : numel(AnchorPick)
        if numel(Pick) >= MaxPick
            return;
        end
        Need = min(kNeg,MaxPick-numel(Pick));
        AnchorDec = TrainArchive.Dec(AnchorPick(i),:);
        for src = [1 2 4]
            if Need <= 0
                break;
            end
            Local = find(TrainArchive.Source(NegIdx) == src & ~Taken);
            if isempty(Local)
                continue;
            end
            Dist = sqrt(sum((NegDec(Local,:) - AnchorDec).^2,2));
            Key = [Dist(:), -TrainArchive.Time(NegIdx(Local)), ...
                   -TrainArchive.Weight(NegIdx(Local)), Local(:)];
            [~,ord] = sortrows(Key,[1 2 3 4]);
            Use = Local(ord(1:min(Need,numel(ord))));
            Pick = [Pick;NegIdx(Use)]; %#ok<AGROW>
            Taken(Use) = true;
            Need = Need - numel(Use);
        end
    end
end

function Priority = ResolveTrainSourcePriority(Source)
    Priority = 5*ones(numel(Source),1);
    Priority(Source == 1) = 1;
    Priority(Source == 2) = 2;
    Priority(Source == 3) = 3;
    Priority(Source == 4) = 4;
end

function Allowed = ResolveLocalSectorSet(Sector,SectorNeighbors)
    if Sector <= 0 || Sector > numel(SectorNeighbors)
        Allowed = Sector;
        return;
    end
    Allowed = unique([Sector;SectorNeighbors{Sector}(:)]);
end

function Rep = BuildSectorRepresentatives(Population,W,RefObj,Mask)
    K   = size(W,1);
    Rep = struct('has',false(K,1), ...
                 'idx',zeros(K,1), ...
                 'scalar',inf(K,1));
    if isempty(Population) || isempty(RefObj)
        return;
    end
    if nargin < 4 || isempty(Mask)
        Mask = true(numel(Population),1);
    end

    Sector = AssociateSectorsLocal(Population.objs,W,RefObj);
    Scalar = ComputeSectorScalar(Population.objs,W,RefObj,Sector);
    for s = 1 : K
        idx = find(Sector == s & Mask(:));
        if isempty(idx)
            continue;
        end
        [Rep.scalar(s),loc] = min(Scalar(idx));
        Rep.idx(s) = idx(loc);
        Rep.has(s) = true;
    end
end

function RefObj = BuildReferenceObj(varargin)
    RefObj = [];
    for i = 1 : nargin
        Population = varargin{i};
        if ~isempty(Population)
            RefObj = [RefObj;Population.objs]; %#ok<AGROW>
        end
    end
end

function [Sector,Count] = AssociateSectorsLocal(PopObj,W,RefObj)
    if nargin < 3 || isempty(RefObj)
        RefObj = PopObj;
    end
    if isempty(PopObj)
        Sector = zeros(0,1);
        Count  = zeros(size(W,1),1);
        return;
    end
    if isempty(W)
        Sector = ones(size(PopObj,1),1);
        Count  = size(PopObj,1);
        return;
    end

    MinObj = min(RefObj,[],1);
    MaxObj = max(RefObj,[],1);
    Range  = MaxObj - MinObj;
    Range(Range < 1e-12) = 1;

    Obj = (PopObj - MinObj)./Range;
    ObjNorm = sqrt(sum(Obj.^2,2));
    ZeroMask = ObjNorm < 1e-12;
    Obj(ZeroMask,:) = 1;
    ObjNorm(ZeroMask) = sqrt(size(Obj,2));
    Obj = Obj./ObjNorm(:,ones(1,size(Obj,2)));

    WNorm = sqrt(sum(W.^2,2));
    WNorm(WNorm < 1e-12) = 1;
    Wn = W./WNorm(:,ones(1,size(W,2)));

    Cosine = Obj*Wn';
    [~,Sector] = max(Cosine,[],2);
    Count = accumarray(Sector,1,[size(W,1),1]);
end

function Value = ComputeSectorScalar(Obj,W,RefObj,Sector)
    if isempty(Obj)
        Value = zeros(0,1);
        return;
    end
    if nargin < 2 || isempty(W)
        W = ones(1,size(Obj,2));
    end
    if nargin < 3 || isempty(RefObj)
        RefObj = Obj;
    end
    if nargin < 4 || isempty(Sector)
        Weight = repmat(W(1,:),size(Obj,1),1);
    else
        Weight = W(Sector,:);
    end

    MinObj  = min(RefObj,[],1);
    MaxObj  = max(RefObj,[],1);
    Range   = MaxObj - MinObj;
    Range(Range < 1e-12) = 1;
    NormObj = (Obj-MinObj)./Range;
    Value   = sum(NormObj.*Weight,2);
end

function Neighbors = BuildSectorNeighbors(W,NeighborCount)
    K = size(W,1);
    Neighbors = cell(K,1);
    if K <= 1 || NeighborCount <= 0
        return;
    end

    WNorm = sqrt(sum(W.^2,2));
    WNorm(WNorm < 1e-12) = 1;
    Wn = W./WNorm(:,ones(1,size(W,2)));
    Cosine = Wn*Wn';
    Cosine(1:K+1:end) = -inf;

    for i = 1 : K
        [~,ord] = sort(Cosine(i,:),'descend');
        Neighbors{i} = ord(1:min(NeighborCount,K-1));
    end
end

%% ========== Environmental selection ==========

function Population = EnvironmentalSelectionC(Population,N,W)
    Population = KeepUniquePopulation(Population);
    if isempty(Population)
        return;
    end

    Feasible = FilterFeasiblePopulation(Population);
    if numel(Feasible) >= N
        Population = ObjectiveSelectionWithLastSectorTruncation(Feasible,N,W);
    else
        Next   = Feasible;
        Need   = N - numel(Next);
        Remain = RemovePopulationByDecision(Population,Next);
        if Need > 0 && ~isempty(Remain)
            Next = [Next,ObjectiveSelectionWithLastSectorTruncation( ...
                Remain,min(Need,numel(Remain)),W)];
        end
        Population = PadPopulation(Next,N);
    end
end

function Population = EnvironmentalSelectionU(Population,N,W)
    Population = KeepUniquePopulation(Population);
    Population = ObjectiveSelectionWithLastSectorTruncation( ...
        Population,min(N,numel(Population)),W);
    Population = PadPopulation(Population,N);
end

function Population = ObjectiveSelectionWithLastSectorTruncation(Population,N,W)
    if isempty(Population)
        return;
    end
    if N <= 0
        Population = Population([]);
        return;
    end

    N = min(N,numel(Population));
    if numel(Population) <= N
        return;
    end

    [FrontNo,MaxFNo] = NDSort(Population.objs,N);
    Next = FrontNo < MaxFNo;
    Last = find(FrontNo == MaxFNo);
    Need = N - sum(Next);
    if Need > 0 && ~isempty(Last)
        PickLast = SelectLastFrontBySector(Population(Last),Need,W,Population.objs);
        Next(Last(PickLast)) = true;
    end
    Population = Population(Next);
end

function Pick = SelectLastFrontBySector(LastPopulation,N,W,RefObj)
    Pick = zeros(0,1);
    if isempty(LastPopulation) || N <= 0
        return;
    end

    N = min(N,numel(LastPopulation));
    if isempty(W)
        CrowdDis = CrowdingDistance(LastPopulation.objs,ones(1,numel(LastPopulation)));
        [~,ord]  = sort(CrowdDis,'descend');
        Pick     = ord(1:N);
        return;
    end

    Sector   = AssociateSectorsLocal(LastPopulation.objs,W,RefObj);
    Scalar   = ComputeSectorScalar(LastPopulation.objs,W,RefObj,Sector);
    CrowdDis = CrowdingDistance(LastPopulation.objs,ones(1,numel(LastPopulation)));
    Ranked   = cell(size(W,1),1);
    for s = 1 : size(W,1)
        idx = find(Sector == s);
        if isempty(idx)
            continue;
        end
        Key = [-CrowdDis(idx)', Scalar(idx), idx];
        [~,ord] = sortrows(Key,[1 2 3]);
        Ranked{s} = idx(ord);
    end
    Order = SectorRoundRobinPick(Ranked,N);
    Pick  = Order(:,2);
end

function Population = PadPopulation(Population,N)
    if isempty(Population)
        return;
    end

    if numel(Population) < N
        Population = [Population,Population(mod(0:N-numel(Population)-1,numel(Population))+1)];
    else
        Population = Population(1:N);
    end
end

%% ========== Parent-selection indicators ==========

function [Flag,FrontNo,CrowdDis] = ConstraintSideIndicator(Population)
    [FrontNo,CrowdDis] = ObjectiveSideIndicator(Population);
    Flag = double(~all(Population.cons<=0,2));
end

function [FrontNo,CrowdDis] = ObjectiveSideIndicator(Population)
    [FrontNo,~] = NDSort(Population.objs,numel(Population));
    CrowdDis    = CrowdingDistance(Population.objs,FrontNo);
end

%% ========== Population utilities ==========

function Population = FilterFeasiblePopulation(Population)
    if isempty(Population)
        return;
    end
    Population = Population(all(Population.cons<=0,2));
end

function Population = KeepUniquePopulation(Population)
    if isempty(Population)
        return;
    end
    Keep = KeepLatestDecisionRowsLocal(Population.decs);
    Population = Population(Keep);
end

function Population = RemovePopulationByDecision(Population,Remove)
    if isempty(Population) || isempty(Remove)
        return;
    end
    Keep = ~ismember(Population.decs,Remove.decs,'rows');
    Population = Population(Keep);
end

function Keep = KeepLatestDecisionRowsLocal(Dec)
    if isempty(Dec)
        Keep = zeros(0,1);
        return;
    end
    [~,Keep] = unique(double(Dec),'rows','last');
    Keep = sort(Keep);
end

%% ========== Round-robin picker ==========

function Pick = SectorRoundRobinPick(Ranked,MaxPick)
    Pick = zeros(0,2);
    if isempty(Ranked) || MaxPick <= 0
        return;
    end

    Ptr = ones(numel(Ranked),1);
    while size(Pick,1) < MaxPick
        Changed = false;
        for s = 1 : numel(Ranked)
            if Ptr(s) <= numel(Ranked{s})
                Pick(end+1,:) = [s,Ranked{s}(Ptr(s))]; %#ok<AGROW>
                Ptr(s) = Ptr(s) + 1;
                Changed = true;
                if size(Pick,1) >= MaxPick
                    break;
                end
            end
        end
        if ~Changed
            break;
        end
    end
end

%% ========== Objective dominance ==========

function Flag = DominatesObjectiveRow(A,B)
    Tol  = 1e-12;
    Flag = all(A <= B + Tol) && any(A < B - Tol);
end
