classdef PRBCCMO_t < ALGORITHM
% <2026> <multi> <real> <constrained>
% PRBCCMO_t
% Traced PRBCCMO with CSV diagnostics for fix.md module validation
%
% type    --- 1    --- 1.GA, 2.DE
% hidden  --- 20   --- Hidden neurons of the boundary MLP
% epoch   --- 20   --- Training epochs per update
% lr      --- 0.01 --- Learning rate
% minPos  --- 5    --- Minimum feasible samples before first training
% minNeg  --- 20   --- Minimum infeasible samples before first training
% kappa   --- 3    --- Maximum boundary-archive size per sector
% rhoPre  --- 0.08 --- Boundary-evaluation ratio before the MLP is ready
% rhoPost --- 0.15 --- Boundary-evaluation ratio after the MLP is ready
% gapMin  --- 3    --- Minimum model update gap
% gapMax  --- 10   --- Maximum model update gap
%
% PRBCCMO_t keeps PRBCCMO logic unchanged and records CSV diagnostics under
% Data/PRBCCMO_t/<run-folder>. No analysis MAT files are generated.
%
% PRBCCMO follows fix.md strictly:
%   1) P_C approaches CPF and P_U approaches UPF with shared offspring;
%   2) B stores top-k boundary-information samples per sector with soft
%      minority reservation;
%   3) the boundary MLP is warm-start updated from a core set made of B and
%      recent boundary offspring, plus sector anchors from P_C or P_U only
%      when the local core misses one side;
%   4) boundary offspring are generated by a single anchor-helper-probe
%      chain with fixed probe betas and helper candidates drawn only from
%      P_C union P_U;
%   5) archive update, model training, and probe ranking share the same
%      uncertainty + opposite-side support + objective relevance score.

%------------------------------- Copyright --------------------------------
% Copyright (c) 2026 BIMK Group. You are free to use the PlatEMO for
% research purposes. All publications which use this platform or any code
% in the platform should acknowledge the use of "PlatEMO" and reference "Ye
% Tian, Ran Cheng, Xingyi Zhang, and Yaochu Jin, PlatEMO: A MATLAB platform
% for evolutionary multi-objective optimization [educational forum], IEEE
% Computational Intelligence Magazine, 2017, 12(4): 73-87".
%--------------------------------------------------------------------------

    methods
        function main(Algorithm,Problem)
            [W,Problem.N] = UniformPoint(Problem.N,Problem.M);
            [type,hidden,epoch,lr,minPos,minNeg,kappa, ...
                rhoPre,rhoPost,gapMin,gapMax] = ...
                Algorithm.ParameterSet(1,20,20,0.01,5,20,3,0.08,0.15,3,10);

            kappa = max(1,round(kappa));
            MaxTrain = max(6*Problem.N,4*size(W,1));
            ProbeBeta = [0.25;0.50;0.75;1.05];

            PopulationC = Problem.Initialization();
            PopulationU = Problem.Initialization();
            B           = PopulationC([]);
            Model       = [];
            RecentBoundaryOff = PopulationC([]);

            SectorNeighbors = BuildSectorNeighbors(W,min(max(3,2*Problem.M),max(size(W,1)-1,0)));
            Generation = 0;
            Observer   = InitObserver( ...
                Algorithm,Problem,[type,hidden,epoch,lr,minPos,minNeg,kappa, ...
                rhoPre,rhoPost,gapMin,gapMax],ProbeBeta,MaxTrain);
            Algorithm.metric.analysis_folder          = Observer.folder;
            Algorithm.metric.analysis_meta_csv        = Observer.meta_file;
            Algorithm.metric.analysis_summary_csv     = Observer.summary_file;
            Algorithm.metric.analysis_boundary_csv    = Observer.boundary_file;
            Algorithm.metric.analysis_archive_csv     = Observer.archive_file;
            Algorithm.metric.analysis_mlp_csv         = Observer.mlp_file;

            TrainArchive = InitTrainArchive(Problem.D);
            [TrainArchive,TrainDiag] = UpdateTrainArchiveWithDiagnostics( ...
                TrainArchive,B,PopulationC,PopulationU,RecentBoundaryOff, ...
                W,SectorNeighbors,MaxTrain,0);
            [Model,MLPDiag] = UpdateBoundaryModelWithDiagnostics( ...
                Model,TrainArchive,minPos,minNeg,hidden,epoch,lr, ...
                ResolveModelUpdateGap(gapMin,gapMax,Problem.FE/max(Problem.maxFE,1)),0);
            Observer = LogMLPEvent(Observer,MLPDiag);

            while Algorithm.NotTerminated(PopulationC)
                Generation = Generation + 1;
                OffspringC = GenerateWithinOffspring(Problem,PopulationC,type,true);
                OffspringU = GenerateWithinOffspring(Problem,PopulationU,type,false);

                FERatio     = Problem.FE/max(Problem.maxFE,1);
                RemainingFE = max(0,Problem.maxFE-Problem.FE);

                SeedPool = KeepUniquePopulation([B,PopulationC,PopulationU,OffspringC,OffspringU]);
                [SeedB,~] = UpdateBoundaryArchive( ...
                    SeedPool,W,Model,PopulationC,PopulationU, ...
                    TrainArchive,SectorNeighbors,kappa);
                SeedMeta = BuildBoundaryMeta( ...
                    SeedB,W,Model,PopulationC,PopulationU,TrainArchive,SectorNeighbors);

                BoundaryBudget = ResolveBoundaryBudget( ...
                    Problem.N,rhoPre,rhoPost,RemainingFE,HasBoundaryModel(Model));
                [BoundaryOff,BoundaryDiag] = GenerateBoundaryOffspringModelDriven( ...
                    Problem,PopulationC,PopulationU,SeedB,W,SectorNeighbors,Model, ...
                    TrainArchive,BoundaryBudget,ProbeBeta,Generation,Problem.FE);
                BoundaryOff = KeepUniquePopulation(BoundaryOff);

                CandidateB = KeepUniquePopulation([SeedPool,BoundaryOff]);
                [B,~] = UpdateBoundaryArchive( ...
                    CandidateB,W,Model,PopulationC,PopulationU, ...
                    TrainArchive,SectorNeighbors,kappa);

                QC = KeepUniquePopulation([PopulationC,OffspringC,OffspringU,BoundaryOff]);
                QU = KeepUniquePopulation([PopulationU,OffspringC,OffspringU,BoundaryOff]);
                PopulationC = EnvironmentalSelectionC(QC,Problem.N,W);
                PopulationU = EnvironmentalSelectionU(QU,Problem.N,W);
                BoundarySurvival = ComputeBoundarySurvival(BoundaryOff,PopulationC,PopulationU);

                RecentBoundaryOff = BoundaryOff;
                [TrainArchive,TrainDiag] = UpdateTrainArchiveWithDiagnostics( ...
                    TrainArchive,B,PopulationC,PopulationU,RecentBoundaryOff, ...
                    W,SectorNeighbors,MaxTrain,Problem.FE);
                [Model,MLPDiag] = UpdateBoundaryModelWithDiagnostics( ...
                    Model,TrainArchive,minPos,minNeg,hidden,epoch,lr, ...
                    ResolveModelUpdateGap(gapMin,gapMax,Problem.FE/max(Problem.maxFE,1)), ...
                    Problem.FE);
                Observer = LogMLPEvent(Observer,MLPDiag);
                ArchiveMeta = BuildBoundaryMeta( ...
                    B,W,Model,PopulationC,PopulationU,TrainArchive,SectorNeighbors);
                Observer = LogGenerationDiagnostics( ...
                    Observer,Generation,Problem,PopulationC,PopulationU, ...
                    OffspringC,OffspringU,BoundaryBudget,SeedB,SeedMeta,BoundaryOff,BoundaryDiag, ...
                    BoundarySurvival,B,ArchiveMeta,TrainArchive,TrainDiag,MLPDiag,Model);
            end
        end
    end
end

%% ========== Main-population offspring ==========

function Offspring = GenerateWithinOffspring(Problem,Population,type,isConstraintSide)
    if isempty(Population)
        Offspring = [];
        return;
    end

    N = numel(Population);
    if isConstraintSide
        [Flag,FrontNo,CrowdDis] = ConstraintSideIndicator(Population);
        MatingPool = TournamentSelection(2,2*N,Flag,FrontNo,-CrowdDis);
    else
        [FrontNo,CrowdDis] = ObjectiveSideIndicator(Population);
        MatingPool = TournamentSelection(2,2*N,FrontNo,-CrowdDis);
    end

    if type == 1
        Offspring = OperatorGAhalf(Problem,Population(MatingPool));
    else
        Offspring = OperatorDE(Problem,Population, ...
            Population(MatingPool(1:N)),Population(MatingPool(N+1:end)));
    end
end

%% ========== Main loop helpers ==========

function Budget = ResolveBoundaryBudget(N,rhoPre,rhoPost,RemainingFE,ModelReady)
    if ModelReady
        Ratio = rhoPost;
    else
        Ratio = rhoPre;
    end
    Ratio  = max(0,min(0.5,double(Ratio)));
    Budget = floor(Ratio*N);
    Budget = min(max(0,Budget),max(0,RemainingFE));
end

function Gap = ResolveModelUpdateGap(gapMin,gapMax,FERatio)
    Gap = floor(double(gapMin) + (double(gapMax)-double(gapMin))*FERatio);
    Gap = max(1,Gap);
end

function [Model,Diag] = UpdateBoundaryModelWithDiagnostics( ...
    Model,TrainArchive,minPos,minNeg,hidden,epoch,lr,Gap,Tick)

    Diag = InitMLPDiag(Model,TrainArchive,Gap,Tick,minPos,minNeg);
    if ~Diag.can_train
        return;
    end

    if isempty(Model) || mod(Tick,Gap) == 0
        Diag.warm_start = double(HasBoundaryModel(Model));
        Model = TrainBoundaryMLP(TrainArchive,hidden,epoch,lr,Model);
        Diag.trained           = 1;
        Diag.model_ready_after = double(HasBoundaryModel(Model));
        Diag.stats_after       = EvaluateBinaryPredictions(Model,TrainArchive.Dec,TrainArchive.Label);
    end
end

function Model = UpdateBoundaryModelIfDue( ...
    Model,TrainArchive,minPos,minNeg,hidden,epoch,lr,Gap,Tick)
    [Model,~] = UpdateBoundaryModelWithDiagnostics( ...
        Model,TrainArchive,minPos,minNeg,hidden,epoch,lr,Gap,Tick);
end

function Flag = HasBoundaryModel(Model)
    Flag = ~isempty(Model) && isfield(Model,'Mu');
end

%% ========== Boundary archive and generation ==========

function [B,Meta] = UpdateBoundaryArchive( ...
    CandidateB,W,Model,PopulationC,PopulationU,TrainArchive,SectorNeighbors,kappa)
    if isempty(CandidateB)
        B    = CandidateB;
        Meta = InitBoundaryMeta(0);
        return;
    end

    CandidateB = KeepUniquePopulation(CandidateB);
    Meta       = BuildBoundaryMeta( ...
        CandidateB,W,Model,PopulationC,PopulationU,TrainArchive,SectorNeighbors);
    BridgeMask = ResolveBridgeBoundaryMask(Meta,TrainArchive,SectorNeighbors,size(W,1));
    B          = SelectTopKPerSector(CandidateB,Meta,BridgeMask,kappa);
end

function Meta = BuildBoundaryMeta( ...
    Candidates,W,Model,PopulationC,PopulationU,TrainArchive,SectorNeighbors)
    N = numel(Candidates);
    Meta = InitBoundaryMeta(N);
    if isempty(Candidates)
        return;
    end

    RefObj = BuildReferenceObj(Candidates,PopulationC,PopulationU);
    [Sector,~] = AssociateSectorsLocal(Candidates.objs,W,RefObj);
    [Prob,~]   = PredictBoundaryMLP(Model,Candidates.decs);
    Margin     = 2*abs(Prob(:)-0.5);
    ObjScore   = ComputeBoundaryObjectiveScore(Candidates,PopulationC,W,RefObj,Sector);
    TrustedSector = ResolveTrustedSectorsFromTrainArchive( ...
        TrainArchive,SectorNeighbors,size(W,1));
    TrustedMask   = IsTrustedSector(Sector,TrustedSector);
    Margin(~TrustedMask) = 1;

    Support = BuildBoundarySupportSet( ...
        Candidates,PopulationC,PopulationU,TrainArchive,W,RefObj);
    Label = double(all(Candidates.cons<=0,2));
    OppDist = ComputeOppositeDistanceByLabel( ...
        Candidates.decs,Label,Sector,Support.Dec,Support.Label, ...
        Support.Sector,SectorNeighbors);
    TauD = ResolveDistanceScale(Support.Dec);
    OppSupport = exp(-OppDist./max(TauD,1e-6));
    OppSupport(~isfinite(OppDist)) = 0;
    OppSupport = max(0,min(1,OppSupport));

    Meta.sector     = Sector(:);
    Meta.prob       = Prob(:);
    Meta.margin     = Margin(:);
    Meta.objScore   = ObjScore(:);
    Meta.oppSupport = OppSupport(:);
    Meta.oppDist    = OppDist(:);
    Meta.feasible   = Label(:);
    Meta.trusted    = TrustedMask(:);
    Meta.score      = 0.50*Margin(:) + 0.30*(1-OppSupport(:)) + 0.20*ObjScore(:);
end

function Meta = InitBoundaryMeta(N)
    Meta = struct( ...
        'sector',zeros(N,1), ...
        'prob',0.5*ones(N,1), ...
        'margin',zeros(N,1), ...
        'objScore',zeros(N,1), ...
        'oppSupport',zeros(N,1), ...
        'oppDist',inf(N,1), ...
        'feasible',zeros(N,1), ...
        'trusted',false(N,1), ...
        'score',zeros(N,1));
end

function BridgeMask = ResolveBridgeBoundaryMask(Meta,TrainArchive,SectorNeighbors,K)
    BridgeMask = Meta.trusted(:);
    CoreMask   = IsCoreTrainSource(TrainArchive.Source);
    CoreLabel  = TrainArchive.Label(CoreMask);
    CoreSector = TrainArchive.Sector(CoreMask);
    for i = 1 : numel(Meta.sector)
        if BridgeMask(i) || Meta.sector(i) <= 0 || Meta.sector(i) > K
            continue;
        end
        Allowed = ResolveLocalSectorSet(Meta.sector(i),SectorNeighbors);
        Local = CoreLabel(ismember(CoreSector,Allowed));
        if any(Local == 1-Meta.feasible(i))
            BridgeMask(i) = true;
            continue;
        end
        BridgeMask(i) = HasRealLocalOppositeSupport(Meta,i);
    end
end

function Flag = HasRealLocalOppositeSupport(Meta,idx)
    Flag = idx > 0 && idx <= numel(Meta.oppDist) && ...
           isfinite(Meta.oppDist(idx));
end

function B = SelectTopKPerSector(Candidates,Meta,BridgeMask,kappa)
    if isempty(Candidates)
        B = Candidates;
        return;
    end

    Pick = zeros(0,1);
    for s = unique(Meta.sector(Meta.sector > 0))'
        idx = find(Meta.sector == s & BridgeMask(:));
        if isempty(idx)
            continue;
        end
        Key = [Meta.score(idx), Meta.margin(idx), Meta.objScore(idx), idx(:)];
        [~,ord] = sortrows(Key,[1 2 3 4]);
        Sel = idx(ord(1:min(kappa,numel(idx))));

        Label = Meta.feasible(idx);
        if any(Label == 1) && any(Label == 0)
            SelLabel = Meta.feasible(Sel);
            if isscalar(unique(SelLabel))
                Majority = SelLabel(1);
                OppIdx = idx(Label ~= Majority);
                if ~isempty(OppIdx)
                    AltKey = [Meta.score(OppIdx), Meta.margin(OppIdx), Meta.objScore(OppIdx), OppIdx(:)];
                    [~,altOrd] = sortrows(AltKey,[1 2 3 4]);
                    Alt = OppIdx(altOrd(1));

                    WorstKey = [Meta.score(Sel), Meta.margin(Sel), Meta.objScore(Sel), Sel(:)];
                    [~,worstOrd] = sortrows(WorstKey,[-1 -2 -3 -4]);
                    if Meta.score(Alt) <= Meta.score(Sel(worstOrd(1))) + 0.08
                        Sel(worstOrd(1)) = Alt;
                    end
                end
            end
        end
        Pick = [Pick;Sel(:)]; %#ok<AGROW>
    end

    if isempty(Pick)
        B = Candidates([]);
    else
        B = Candidates(unique(Pick,'stable'));
    end
end

function [Offspring,Diag] = GenerateBoundaryOffspringModelDriven( ...
    Problem,PopulationC,PopulationU,B,W,SectorNeighbors,Model,TrainArchive, ...
    Budget,ProbeBeta,Generation,FE)

    Diag = InitBoundaryDiag(Generation,FE,Budget);

    if isempty(B)
        Offspring = PopulationC([]);
        return;
    end
    if Budget <= 0
        Offspring = B([]);
        return;
    end

    RefObj      = BuildReferenceObj(B,PopulationC,PopulationU);
    ArchiveMeta = BuildBoundaryMeta( ...
        B,W,Model,PopulationC,PopulationU,TrainArchive,SectorNeighbors);
    Pool        = KeepUniquePopulation([PopulationC,PopulationU]);
    PoolMeta    = BuildBoundaryMeta( ...
        Pool,W,Model,PopulationC,PopulationU,TrainArchive,SectorNeighbors);
    Support     = BuildBoundarySupportSet( ...
        B,PopulationC,PopulationU,TrainArchive,W,RefObj);
    SectorOrder = RankBoundarySectors(ArchiveMeta);
    if isempty(SectorOrder)
        Offspring = B([]);
        return;
    end

    ProbeDecAll = zeros(0,Problem.D);
    MaxAttempt  = max(Budget,1)*max(numel(SectorOrder),1)*3;
    Attempt     = 0;
    PoolDec     = zeros(0,Problem.D);
    if ~isempty(Pool)
        PoolDec = [PoolDec;Pool.decs]; %#ok<AGROW>
    end
    if ~isempty(B)
        PoolDec = [PoolDec;B.decs]; %#ok<AGROW>
    end

    while size(ProbeDecAll,1) < Budget && Attempt < MaxAttempt
        s = SectorOrder(mod(Attempt,numel(SectorOrder))+1);
        Attempt = Attempt + 1;
        Diag.attempts = Attempt;

        [Anchor,AnchorMeta,HasAnchor] = SelectBoundaryAnchor(B,ArchiveMeta,s);
        if ~HasAnchor
            continue;
        end

        [Helper,HelperMeta,HasHelper,HelperInfo] = SelectBoundaryHelper( ...
            Anchor,AnchorMeta,Pool,PoolMeta,s,SectorNeighbors,Model);
        if ~HasHelper
            Diag.skipped_no_helper = Diag.skipped_no_helper + 1;
            continue;
        end

        [ProbeDec,Beta] = BuildBoundaryProbeDecisions( ...
            Problem,Anchor.decs,Helper.decs,ProbeBeta);
        [Prob,Score,ProbeMeta] = RankBoundaryProbeCandidates( ...
            Model,ProbeDec,Beta,Anchor,AnchorMeta,Helper,HelperMeta,Support,SectorNeighbors);
        [~,best]  = min(Score);
        Candidate = ProbeDec(best,:);

        if ~isempty(PoolDec) && ismember(Candidate,PoolDec,'rows')
            Diag.skipped_duplicate = Diag.skipped_duplicate + 1;
            continue;
        end
        if ~isempty(ProbeDecAll) && ismember(Candidate,ProbeDecAll,'rows')
            Diag.skipped_duplicate = Diag.skipped_duplicate + 1;
            continue;
        end
        ProbeDecAll(end+1,:) = Candidate; %#ok<AGROW>
        chosenPred = double(Prob(best) >= 0.5);
        Diag.events = [Diag.events; { ...
            Generation,FE,Attempt,s,HelperInfo.type,HelperInfo.feasible, ...
            AnchorMeta.trusted,AnchorMeta.margin,AnchorMeta.oppSupport,AnchorMeta.objScore, ...
            Beta(best),Prob(best),chosenPred,ProbeMeta.margin(best),ProbeMeta.oppSupport(best), ...
            ProbeMeta.oppDist(best),ProbeMeta.objScore(best),Score(best),NaN,NaN}]; %#ok<AGROW>
        Diag.helper_real_opp = Diag.helper_real_opp + double(strcmp(HelperInfo.type,'real_opposite'));
    end

    if isempty(ProbeDecAll)
        Offspring = B([]);
    else
        Offspring = Problem.Evaluation(ProbeDecAll);
        Feasible = double(all(Offspring.cons<=0,2));
        for i = 1 : min(numel(Feasible),size(Diag.events,1))
            Diag.events{i,end-1} = Feasible(i);
            Diag.events{i,end} = double(Diag.events{i,13} == Feasible(i));
        end
        Diag.selected = numel(Offspring);
        Diag.feasible = sum(Feasible == 1);
        Diag.infeasible = sum(Feasible == 0);
    end
end

function SectorOrder = RankBoundarySectors(Meta)
    SectorOrder = zeros(1,0);
    TrustedMask = Meta.sector > 0 & Meta.trusted(:);
    Sectors = unique(Meta.sector(TrustedMask))';
    if isempty(Sectors)
        return;
    end

    Key = zeros(numel(Sectors),3);
    for i = 1 : numel(Sectors)
        idx      = find(Meta.sector == Sectors(i));
        Key(i,1) = min(Meta.score(idx));
        Key(i,2) = min(Meta.margin(idx));
        Key(i,3) = Sectors(i);
    end
    [~,ord]  = sortrows(Key,[1 2 3]);
    SectorOrder = Sectors(ord);
end

function [Anchor,AnchorMeta,Found] = SelectBoundaryAnchor(B,Meta,sector)
    Empty = B([]);
    idx   = find(Meta.sector == sector);
    if isempty(idx)
        Anchor     = Empty;
        AnchorMeta = InitBoundaryMeta(0);
        Found      = false;
        return;
    end

    Key = [Meta.score(idx), Meta.margin(idx), Meta.objScore(idx), idx(:)];
    [~,ord] = sortrows(Key,[1 2 3 4]);
    Pick    = idx(ord(1));
    Anchor  = B(Pick);
    AnchorMeta = ExtractBoundaryMetaRow(Meta,Pick);
    Found   = true;
end

function [Helper,HelperMeta,Found,Info] = SelectBoundaryHelper( ...
    Anchor,AnchorMeta,Pool,PoolMeta,sector,SectorNeighbors,Model)

    Empty    = Pool([]);
    Info     = struct('type','none','feasible',NaN);
    Neighbor = [sector,SectorNeighbors{sector}(:)'];
    Allowed  = ismember(PoolMeta.sector,unique(Neighbor)) & ...
               ~ismember(Pool.decs,Anchor.decs,'rows');
    idx = find(Allowed);
    if isempty(idx)
        Helper     = Empty;
        HelperMeta = InitBoundaryMeta(0);
        Found      = false;
        return;
    end

    AnchorLabel = double(all(Anchor.cons<=0,2));
    Label       = double(all(Pool.cons<=0,2));
    OppReal     = idx(Label(idx) ~= AnchorLabel);
    if ~isempty(OppReal)
        Pick = PickBestHelper(OppReal,PoolMeta);
        Helper     = Pool(Pick);
        HelperMeta = ExtractBoundaryMetaRow(PoolMeta,Pick);
        Info.type  = 'real_opposite';
        Info.feasible = Label(Pick);
        Found      = true;
        return;
    end
    %#ok<INUSD> Model AnchorMeta

    Helper     = Empty;
    HelperMeta = InitBoundaryMeta(0);
    Found      = false;
end

function Pick = PickBestHelper(idx,Meta)
    Key = [Meta.score(idx), Meta.margin(idx), Meta.objScore(idx), idx(:)];
    [~,ord] = sortrows(Key,[1 2 3 4]);
    Pick    = idx(ord(1));
end

function Row = ExtractBoundaryMetaRow(Meta,idx)
    Row = InitBoundaryMeta(1);
    Row.sector     = Meta.sector(idx);
    Row.prob       = Meta.prob(idx);
    Row.margin     = Meta.margin(idx);
    Row.objScore   = Meta.objScore(idx);
    Row.oppSupport = Meta.oppSupport(idx);
    Row.oppDist    = Meta.oppDist(idx);
    Row.feasible   = Meta.feasible(idx);
    Row.trusted    = Meta.trusted(idx);
    Row.score      = Meta.score(idx);
end

function [ProbeDec,Beta] = BuildBoundaryProbeDecisions( ...
    Problem,AnchorDec,HelperDec,FixedBeta)

    Beta = FixedBeta(:);
    Span     = double(Problem.upper - Problem.lower);
    Span(Span < 1e-12) = 1;
    RealIdx  = find(Problem.encoding <= 2);
    OtherIdx = setdiff(1:Problem.D,RealIdx);

    ProbeDec = zeros(numel(Beta),Problem.D);
    for i = 1 : numel(Beta)
        Base = AnchorDec + Beta(i)*(HelperDec-AnchorDec);
        Dec  = Base;
        if ~isempty(RealIdx)
            Dec(RealIdx) = Base(RealIdx) + 0.05*randn(1,numel(RealIdx)).*Span(RealIdx);
        end
        if ~isempty(OtherIdx)
            if Beta(i) <= 0.5
                Dec(OtherIdx) = AnchorDec(OtherIdx);
            else
                Dec(OtherIdx) = HelperDec(OtherIdx);
            end
        end
        ProbeDec(i,:) = Problem.CalDec(Dec);
    end
end

function [Prob,Score,Meta] = RankBoundaryProbeCandidates( ...
    Model,ProbeDec,Beta,Anchor,AnchorMeta,Helper,HelperMeta,Support,SectorNeighbors)
    if isempty(ProbeDec)
        Prob  = zeros(0,1);
        Score = zeros(0,1);
        Meta = struct('margin',zeros(0,1),'oppSupport',zeros(0,1), ...
            'oppDist',zeros(0,1),'objScore',zeros(0,1));
        return;
    end

    [Prob,~] = PredictBoundaryMLP(Model,ProbeDec);
    Margin = 2*abs(Prob(:)-0.5);
    if AnchorMeta.trusted <= 0
        Margin(:) = 1;
    end
    Sector = AnchorMeta.sector*ones(size(ProbeDec,1),1);
    AnchorLabel = double(all(Anchor.cons<=0,2));
    HelperLabel = double(all(Helper.cons<=0,2));
    ProxyLabel  = BuildProbeProxyLabels(Beta,AnchorLabel,HelperLabel);

    OppDist = ComputeOppositeDistanceByLabel( ...
        ProbeDec,ProxyLabel,Sector,Support.Dec,Support.Label, ...
        Support.Sector,SectorNeighbors);
    TauD = ResolveDistanceScale(Support.Dec);
    OppSupport = exp(-OppDist./max(TauD,1e-6));
    OppSupport(~isfinite(OppDist)) = 0;
    OppSupport = max(0,min(1,OppSupport));

    Mix = min(max(Beta(:),0),1);
    ObjScore = (1-Mix)*AnchorMeta.objScore + Mix*HelperMeta.objScore;
    ObjScore = max(0,min(1,ObjScore));
    Score = 0.50*Margin(:) + 0.30*(1-OppSupport(:)) + 0.20*ObjScore(:);
    Meta = struct('margin',Margin(:),'oppSupport',OppSupport(:), ...
        'oppDist',OppDist(:),'objScore',ObjScore(:));
end

function ProxyLabel = BuildProbeProxyLabels(Beta,AnchorLabel,HelperLabel)
    ProxyLabel = AnchorLabel*ones(numel(Beta),1);
    ProxyLabel(Beta(:) >= 0.5) = HelperLabel;
end

%% ========== Training archive ==========

function TrainArchive = InitTrainArchive(D)
    TrainArchive = struct( ...
        'Dec',zeros(0,D), ...
        'Label',zeros(0,1), ...
        'Source',zeros(0,1), ...
        'Sector',zeros(0,1), ...
        'Time',zeros(0,1));   % 1:B core, 2:recent boundary core, 3:P_C feasible anchor, 4:P_U infeasible anchor
end

function TrainArchive = UpdateTrainArchive( ...
    TrainArchive,B,PopulationC,PopulationU,RecentBoundaryOff,W, ...
    SectorNeighbors,MaxTrain,Stamp)

    RefObj = BuildReferenceObj(B,PopulationC,PopulationU,RecentBoundaryOff);
    if isempty(RefObj)
        RefObj = BuildReferenceObj(PopulationC,PopulationU,B);
    end

    [Core,CoreSource] = BuildCoreTrainPopulation(B,RecentBoundaryOff);
    Candidates = Core;
    Source     = CoreSource;
    if ~isempty(Core)
        CoreSector = AssociateSectorsLocal(Core.objs,W,RefObj);
        CoreLabel  = double(all(Core.cons<=0,2));

        RepC = BuildSectorRepresentatives( ...
            PopulationC,W,RefObj,all(PopulationC.cons<=0,2));
        RepU = BuildSectorRepresentatives( ...
            PopulationU,W,RefObj,any(PopulationU.cons>0,2));

        AnchorC = SelectMissingSideAnchors( ...
            Core,CoreSector,CoreLabel,PopulationC,RepC,SectorNeighbors,1);
        AnchorU = SelectMissingSideAnchors( ...
            Core,CoreSector,CoreLabel,PopulationU,RepU,SectorNeighbors,0);
        if ~isempty(AnchorC)
            Candidates = [Candidates,PopulationC(AnchorC)];
            Source = [Source;3*ones(numel(AnchorC),1)];
        end
        if ~isempty(AnchorU)
            Candidates = [Candidates,PopulationU(AnchorU)];
            Source = [Source;4*ones(numel(AnchorU),1)];
        end
    end

    Meta = BuildTrainMeta(Candidates,Source,W,RefObj,Stamp);
    TrainArchive = AppendTrainArchiveWithMeta(TrainArchive,Candidates,Meta);
    TrainArchive = TrimTrainArchiveBySectorQuota(TrainArchive,MaxTrain);
end

function [TrainArchive,Diag] = UpdateTrainArchiveWithDiagnostics( ...
    TrainArchive,B,PopulationC,PopulationU,RecentBoundaryOff,W, ...
    SectorNeighbors,MaxTrain,Stamp)
    TrainArchive = UpdateTrainArchive( ...
        TrainArchive,B,PopulationC,PopulationU,RecentBoundaryOff,W, ...
        SectorNeighbors,MaxTrain,Stamp);
    Diag = struct( ...
        'size',size(TrainArchive.Dec,1), ...
        'pos_count',sum(TrainArchive.Label == 1), ...
        'neg_count',sum(TrainArchive.Label == 0), ...
        'src_b',sum(TrainArchive.Source == 1), ...
        'src_recent_boundary',sum(TrainArchive.Source == 2), ...
        'src_rep_c',sum(TrainArchive.Source == 3), ...
        'src_rep_u',sum(TrainArchive.Source == 4));
end

function TrainArchive = AppendTrainArchiveWithMeta(TrainArchive,Population,Meta)
    if isempty(Population)
        return;
    end

    TrainArchive.Dec         = [TrainArchive.Dec;Population.decs];
    TrainArchive.Label       = [TrainArchive.Label;double(all(Population.cons<=0,2))];
    TrainArchive.Source      = [TrainArchive.Source;Meta.source(:)];
    TrainArchive.Sector      = [TrainArchive.Sector;Meta.sector(:)];
    TrainArchive.Time        = [TrainArchive.Time;Meta.time(:)];

    Keep = KeepLatestDecisionRowsLocal(TrainArchive.Dec);
    TrainArchive.Dec         = TrainArchive.Dec(Keep,:);
    TrainArchive.Label       = TrainArchive.Label(Keep);
    TrainArchive.Source      = TrainArchive.Source(Keep);
    TrainArchive.Sector      = TrainArchive.Sector(Keep);
    TrainArchive.Time        = TrainArchive.Time(Keep);
end

function Meta = BuildTrainMeta(Candidates,Source,W,RefObj,Stamp)
    N = numel(Candidates);
    Meta = struct( ...
        'source',Source(:), ...
        'sector',zeros(N,1), ...
        'time',Stamp*ones(N,1));
    if isempty(Candidates)
        return;
    end

    Sector = AssociateSectorsLocal(Candidates.objs,W,RefObj);
    Meta.sector = Sector(:);
end

function TrainArchive = TrimTrainArchiveBySectorQuota(TrainArchive,MaxTrain)
    Count = size(TrainArchive.Dec,1);
    if Count <= MaxTrain
        return;
    end

    Keep = SelectArchiveRowsBySectorQuota(TrainArchive,MaxTrain);
    TrainArchive.Dec         = TrainArchive.Dec(Keep,:);
    TrainArchive.Label       = TrainArchive.Label(Keep);
    TrainArchive.Source      = TrainArchive.Source(Keep);
    TrainArchive.Sector      = TrainArchive.Sector(Keep);
    TrainArchive.Time        = TrainArchive.Time(Keep);
end

function Pick = SelectArchiveRowsBySectorQuota(TrainArchive,MaxTrain)
    CandidateIdx = (1:size(TrainArchive.Dec,1))';
    if isempty(CandidateIdx) || MaxTrain <= 0
        Pick = zeros(0,1);
        return;
    end

    CandidateIdx = CandidateIdx(:);
    Quota = [2 2 1 1];
    Key = [-TrainArchive.Time(CandidateIdx), CandidateIdx];
    [~,ord] = sortrows(Key,[1 2]);
    Sorted = CandidateIdx(ord);
    Pick = zeros(0,1);
    SectorCount = zeros(max([TrainArchive.Sector(:);0]),numel(Quota));
    for i = 1 : numel(Sorted)
        idx = Sorted(i);
        sec = TrainArchive.Sector(idx);
        src = TrainArchive.Source(idx);
        if sec <= 0 || src < 1 || src > numel(Quota)
            continue;
        end
        if SectorCount(sec,src) < Quota(src)
            Pick(end+1,1) = idx; %#ok<AGROW>
            SectorCount(sec,src) = SectorCount(sec,src) + 1;
            if numel(Pick) >= MaxTrain
                return;
            end
        end
    end
end

function Flag = CanTrainBoundaryModel(TrainArchive,minPos,minNeg)
    Flag = sum(TrainArchive.Label == 1) >= minPos && ...
           sum(TrainArchive.Label == 0) >= minNeg;
end

%% ========== Boundary MLP ==========

function Model = TrainBoundaryMLP(TrainArchive,Hidden,Epoch,LR,PrevModel)
    if nargin < 5
        PrevModel = [];
    end
    Model = PrevModel;

    X = double(TrainArchive.Dec);
    Y = double(TrainArchive.Label(:) > 0);
    if isempty(X) || size(X,1) < 4
        return;
    end
    if numel(unique(Y)) < 2
        return;
    end

    Hidden    = max(2,round(Hidden));
    Epoch     = max(1,round(Epoch));
    LR        = max(double(LR),1e-4);
    [N,D]     = size(X);
    LambdaReg = 1e-4;

    Mu    = mean(X,1);
    Sigma = std(X,0,1);
    Sigma(Sigma < 1e-12) = 1;

    if ~isempty(PrevModel) && IsWarmStartCompatible(PrevModel,D,Hidden)
        W1 = PrevModel.W1;
        b1 = PrevModel.b1;
        W2 = PrevModel.W2;
        b2 = PrevModel.b2;
    else
        W1 = 0.1*randn(D,Hidden);
        b1 = zeros(1,Hidden);
        W2 = 0.1*randn(Hidden,1);
        b2 = 0;
    end

    Xn = (X-Mu)./Sigma;
    for e = 1 : Epoch
        H = tanh(Xn*W1 + repmat(b1,N,1));
        Z = H*W2 + b2;
        P = 1./(1+exp(-Z));

        Delta2 = (P-Y)./max(N,1);
        dW2 = H'*Delta2 + LambdaReg*W2;
        db2 = sum(Delta2);

        D1  = (Delta2*W2').*(1-H.^2);
        dW1 = Xn'*D1 + LambdaReg*W1;
        db1 = sum(D1,1);

        Step = LR/sqrt(e);
        W1 = W1 - Step*dW1;
        b1 = b1 - Step*db1;
        W2 = W2 - Step*dW2;
        b2 = b2 - Step*db2;
    end

    Model = struct('Mu',Mu,'Sigma',Sigma,'W1',W1,'b1',b1,'W2',W2,'b2',b2);
end

function [Prob,Stats] = PredictBoundaryMLP(Model,X)
    if nargin < 2 || isempty(X)
        Prob  = zeros(0,1);
        Stats = struct('logit',zeros(0,1));
        return;
    end
    if isempty(Model) || ~isfield(Model,'Mu')
        Prob  = 0.5*ones(size(X,1),1);
        Stats = struct('logit',zeros(size(X,1),1));
        return;
    end

    Xn = (double(X)-Model.Mu)./Model.Sigma;
    H  = tanh(Xn*Model.W1 + repmat(Model.b1,size(Xn,1),1));
    Z = H*Model.W2 + Model.b2;
    Prob = 1./(1+exp(-Z));
    Prob = min(max(Prob,1e-6),1-1e-6);
    Stats = struct('logit',Z(:));
end

function Flag = IsWarmStartCompatible(Model,D,Hidden)
    Flag = ~isempty(Model) && isfield(Model,'W1') && isfield(Model,'W2') && ...
           size(Model.W1,1) == D && size(Model.W1,2) == Hidden && ...
           size(Model.W2,1) == Hidden;
end

function Diag = InitMLPDiag(Model,TrainArchive,Gap,Tick,minPos,minNeg)
    Diag = struct( ...
        'gap',Gap, ...
        'tick',Tick, ...
        'train_size',size(TrainArchive.Dec,1), ...
        'pos_count',sum(TrainArchive.Label == 1), ...
        'neg_count',sum(TrainArchive.Label == 0), ...
        'src_b',sum(TrainArchive.Source == 1), ...
        'src_recent_boundary',sum(TrainArchive.Source == 2), ...
        'src_rep_c',sum(TrainArchive.Source == 3), ...
        'src_rep_u',sum(TrainArchive.Source == 4), ...
        'can_train',double(CanTrainBoundaryModel(TrainArchive,minPos,minNeg)), ...
        'trained',0, ...
        'warm_start',0, ...
        'model_ready_before',double(HasBoundaryModel(Model)), ...
        'model_ready_after',double(HasBoundaryModel(Model)), ...
        'stats_before',EvaluateBinaryPredictions(Model,TrainArchive.Dec,TrainArchive.Label), ...
        'stats_after',EvaluateBinaryPredictions(Model,TrainArchive.Dec,TrainArchive.Label));
end

function Stats = EvaluateBinaryPredictions(Model,Dec,Label)
    Stats = InitPredictionStats();
    if isempty(Dec) || isempty(Label) || ~HasBoundaryModel(Model)
        return;
    end

    [Prob,~] = PredictBoundaryMLP(Model,Dec);
    Prob = min(max(Prob(:),1e-6),1-1e-6);
    Label = double(Label(:) > 0);
    Pred = double(Prob >= 0.5);

    TP = sum(Pred == 1 & Label == 1);
    TN = sum(Pred == 0 & Label == 0);
    FP = sum(Pred == 1 & Label == 0);
    FN = sum(Pred == 0 & Label == 1);

    Stats.acc = mean(Pred == Label);
    Rec = SafeDivide(TP,TP+FN);
    Spe = SafeDivide(TN,TN+FP);
    Stats.bal_acc = mean([Rec,Spe],'omitnan');
    Stats.brier = mean((Prob-Label).^2);
    Stats.logloss = -mean(Label.*log(Prob) + (1-Label).*log(1-Prob));
    Stats.precision = SafeDivide(TP,TP+FP);
    Stats.recall = Rec;
    Stats.specificity = Spe;
end

function Stats = InitPredictionStats()
    Stats = struct( ...
        'acc',NaN, ...
        'bal_acc',NaN, ...
        'brier',NaN, ...
        'logloss',NaN, ...
        'precision',NaN, ...
        'recall',NaN, ...
        'specificity',NaN);
end

function Value = SafeDivide(A,B)
    if B <= 0
        Value = NaN;
    else
        Value = A/B;
    end
end

function Value = MeanOrNaN(X)
    if isempty(X)
        Value = NaN;
    else
        Value = mean(X,'omitnan');
    end
end

%% ========== Diagnostics / logging ==========

function Observer = InitObserver(Algorithm,Problem,Params,ProbeBeta,MaxTrain)
    RootDir    = fileparts(which('platemo'));
    BaseFolder = fullfile(RootDir,'Data','PRBCCMO_t');
    [~,~]      = mkdir(BaseFolder);
    [~,Token]  = fileparts(tempname(BaseFolder));
    RunFolder  = fullfile(BaseFolder,sprintf('%s_%s_N%d_FE%d_%s', ...
        class(Algorithm),class(Problem),Problem.N,Problem.maxFE,Token));
    [~,~]      = mkdir(RunFolder);

    Observer = struct( ...
        'folder',RunFolder, ...
        'meta_file',fullfile(RunFolder,'run_meta.csv'), ...
        'summary_file',fullfile(RunFolder,'generation_summary.csv'), ...
        'boundary_file',fullfile(RunFolder,'boundary_event.csv'), ...
        'archive_file',fullfile(RunFolder,'archive_members.csv'), ...
        'mlp_file',fullfile(RunFolder,'mlp_events.csv'));

    WriteCsvHeader(Observer.meta_file,{ ...
        'algorithm','problem','M','D','N','maxFE','maxTrain', ...
        'type','hidden','epoch','lr','minPos','minNeg','kappa', ...
        'rhoPre','rhoPost','gapMin','gapMax','probe_beta','output_folder'});
    AppendCsvRows(Observer.meta_file,{ ...
        class(Algorithm),class(Problem),Problem.M,Problem.D,Problem.N,Problem.maxFE, ...
        MaxTrain,Params(1),Params(2),Params(3),Params(4),Params(5), ...
        Params(6),Params(7),Params(8),Params(9),Params(10),Params(11), ...
        ProbeBeta(:)',RunFolder});

    WriteCsvHeader(Observer.summary_file,{ ...
        'generation','fe','fe_ratio', ...
        'popc_feasible_ratio','popu_feasible_ratio', ...
        'offspringc_feasible_ratio','offspringu_feasible_ratio', ...
        'boundary_budget','boundary_attempts','boundary_selected','boundary_feasible_ratio', ...
        'boundary_survive_c','boundary_survive_u', ...
        'helper_real_opp_ratio','helper_skip_no_helper', ...
        'seed_b_size','seed_b_sector_coverage','seed_b_mixed_sectors', ...
        'b_size','b_feasible_ratio','b_sector_coverage','b_mixed_sectors', ...
        'b_trusted_count','b_trusted_sector_coverage','b_trusted_lowmargin_count', ...
        'b_mean_margin','b_mean_opp_support','b_mean_oppdist','b_mean_score', ...
        'lowmargin_count','lowmargin_feasible_ratio','lowmargin_mix_score','lowmargin_oppdist', ...
        'boundary_bal_acc','b_bal_acc','b_brier', ...
        'train_size','train_pos','train_neg', ...
        'train_src_b','train_src_recent_boundary','train_src_rep_c','train_src_rep_u', ...
        'model_ready_before','model_trained','model_ready_after', ...
        'train_bal_acc_after','train_minus_boundary_bal_gap','train_minus_b_bal_gap'});
    WriteCsvHeader(Observer.boundary_file,{ ...
        'generation','fe','attempt','sector','helper_type','helper_feasible', ...
        'anchor_trusted', ...
        'anchor_margin','anchor_opp_support','anchor_obj_score', ...
        'beta','chosen_prob','chosen_pred_label','chosen_margin','chosen_opp_support','chosen_oppdist', ...
        'chosen_obj_score','chosen_score','chosen_feasible','chosen_correct'});
    WriteCsvHeader(Observer.archive_file,{ ...
        'generation','fe','member_index','sector','feasible','trusted','prob','pred_label','correct', ...
        'margin','obj_score','opp_support','opp_dist','score'});
    WriteCsvHeader(Observer.mlp_file,{ ...
        'tick','gap','can_train','trained','warm_start', ...
        'model_ready_before','model_ready_after', ...
        'train_size','pos_count','neg_count', ...
        'src_b','src_recent_boundary','src_rep_c','src_rep_u', ...
        'acc_before','bal_acc_before','brier_before','logloss_before', ...
        'acc_after','bal_acc_after','brier_after','logloss_after'});
end

function Observer = LogMLPEvent(Observer,Diag)
    AppendCsvRows(Observer.mlp_file,{ ...
        Diag.tick,Diag.gap,Diag.can_train,Diag.trained,Diag.warm_start, ...
        Diag.model_ready_before,Diag.model_ready_after, ...
        Diag.train_size,Diag.pos_count,Diag.neg_count, ...
        Diag.src_b,Diag.src_recent_boundary,Diag.src_rep_c,Diag.src_rep_u, ...
        Diag.stats_before.acc,Diag.stats_before.bal_acc,Diag.stats_before.brier,Diag.stats_before.logloss, ...
        Diag.stats_after.acc,Diag.stats_after.bal_acc,Diag.stats_after.brier,Diag.stats_after.logloss});
end

function Observer = LogGenerationDiagnostics( ...
    Observer,Generation,Problem,PopulationC,PopulationU,OffspringC,OffspringU, ...
    BoundaryBudget,SeedB,SeedMeta,BoundaryOff,BoundaryDiag,BoundarySurvival,B,ArchiveMeta, ...
    TrainArchive,TrainDiag,MLPDiag,Model)

    SeedStats = SummarizeArchive(SeedB,SeedMeta);
    ArchiveStats = SummarizeArchive(B,ArchiveMeta);
    if isempty(BoundaryOff)
        BoundaryPred = InitPredictionStats();
    else
        BoundaryPred = EvaluateBinaryPredictions( ...
            Model,BoundaryOff.decs,double(all(BoundaryOff.cons<=0,2)));
    end
    ArchivePred = EvaluateBinaryPredictions(Model,B.decs,double(all(B.cons<=0,2)));

    PopCFea = SafeDivide(sum(all(PopulationC.cons<=0,2)),max(numel(PopulationC),1));
    PopUFea = SafeDivide(sum(all(PopulationU.cons<=0,2)),max(numel(PopulationU),1));
    OffCFea = SafeDivide(sum(all(OffspringC.cons<=0,2)),max(numel(OffspringC),1));
    OffUFea = SafeDivide(sum(all(OffspringU.cons<=0,2)),max(numel(OffspringU),1));
    BoundaryFea = SafeDivide(BoundaryDiag.feasible,BoundaryDiag.selected);
    HelperReal = SafeDivide(BoundaryDiag.helper_real_opp,BoundaryDiag.selected);
    TrainMinusBoundaryGap = MLPDiag.stats_after.bal_acc - BoundaryPred.bal_acc;
    TrainMinusArchiveGap  = MLPDiag.stats_after.bal_acc - ArchivePred.bal_acc;

    AppendCsvRows(Observer.summary_file,{ ...
        Generation,Problem.FE,Problem.FE/max(Problem.maxFE,1), ...
        PopCFea,PopUFea,OffCFea,OffUFea, ...
        BoundaryBudget,BoundaryDiag.attempts,BoundaryDiag.selected,BoundaryFea, ...
        BoundarySurvival.selected_c,BoundarySurvival.selected_u, ...
        HelperReal,BoundaryDiag.skipped_no_helper, ...
        SeedStats.size,SeedStats.sector_coverage,SeedStats.mixed_sectors, ...
        ArchiveStats.size,ArchiveStats.feasible_ratio,ArchiveStats.sector_coverage,ArchiveStats.mixed_sectors, ...
        ArchiveStats.trusted_count,ArchiveStats.trusted_sector_coverage,ArchiveStats.trusted_lowmargin_count, ...
        ArchiveStats.mean_margin,ArchiveStats.mean_opp_support,ArchiveStats.mean_oppdist,ArchiveStats.mean_score, ...
        ArchiveStats.lowmargin_count,ArchiveStats.lowmargin_feasible_ratio, ...
        ArchiveStats.lowmargin_mix_score,ArchiveStats.lowmargin_oppdist, ...
        BoundaryPred.bal_acc,ArchivePred.bal_acc,ArchivePred.brier, ...
        TrainDiag.size,TrainDiag.pos_count,TrainDiag.neg_count, ...
        TrainDiag.src_b,TrainDiag.src_recent_boundary,TrainDiag.src_rep_c,TrainDiag.src_rep_u, ...
        MLPDiag.model_ready_before,MLPDiag.trained,MLPDiag.model_ready_after, ...
        MLPDiag.stats_after.bal_acc,TrainMinusBoundaryGap,TrainMinusArchiveGap});

    Observer = LogBoundaryEvents(Observer,BoundaryDiag);
    Observer = LogArchiveMembers(Observer,Generation,Problem.FE,B,ArchiveMeta);
end

function Observer = LogBoundaryEvents(Observer,Diag)
    if isempty(Diag.events)
        return;
    end
    AppendCsvRows(Observer.boundary_file,Diag.events);
end

function Observer = LogArchiveMembers(Observer,Generation,FE,B,Meta)
    if isempty(B)
        return;
    end
    Rows = cell(numel(B),14);
    for i = 1 : numel(B)
        predLabel = double(Meta.prob(i) >= 0.5);
        Rows(i,:) = { ...
            Generation,FE,i,Meta.sector(i),Meta.feasible(i),Meta.trusted(i),Meta.prob(i), ...
            predLabel,double(predLabel == Meta.feasible(i)),Meta.margin(i), ...
            Meta.objScore(i),Meta.oppSupport(i),Meta.oppDist(i),Meta.score(i)};
    end
    AppendCsvRows(Observer.archive_file,Rows);
end

function Stats = SummarizeArchive(B,Meta)
    Stats = struct( ...
        'size',numel(B), ...
        'feasible_ratio',NaN, ...
        'sector_coverage',0, ...
        'mixed_sectors',0, ...
        'trusted_count',0, ...
        'trusted_sector_coverage',0, ...
        'mean_margin',NaN, ...
        'mean_opp_support',NaN, ...
        'mean_oppdist',NaN, ...
        'mean_score',NaN, ...
        'lowmargin_count',0, ...
        'trusted_lowmargin_count',0, ...
        'lowmargin_feasible_ratio',NaN, ...
        'lowmargin_mix_score',NaN, ...
        'lowmargin_oppdist',NaN);
    if isempty(B)
        return;
    end

    Stats.feasible_ratio = SafeDivide(sum(Meta.feasible == 1),numel(B));
    Stats.sector_coverage = numel(unique(Meta.sector(Meta.sector > 0)));
    Stats.trusted_count = sum(Meta.trusted > 0);
    Stats.trusted_sector_coverage = numel(unique(Meta.sector(Meta.sector > 0 & Meta.trusted(:) > 0)));
    Stats.mean_margin = MeanOrNaN(Meta.margin);
    Stats.mean_opp_support = MeanOrNaN(Meta.oppSupport);
    Stats.mean_oppdist = MeanOrNaN(Meta.oppDist(isfinite(Meta.oppDist)));
    Stats.mean_score = MeanOrNaN(Meta.score);

    Sectors = unique(Meta.sector(Meta.sector > 0))';
    Mixed = 0;
    for s = Sectors
        idx = find(Meta.sector == s);
        if any(Meta.feasible(idx) == 1) && any(Meta.feasible(idx) == 0)
            Mixed = Mixed + 1;
        end
    end
    Stats.mixed_sectors = Mixed;

    LowMask = Meta.margin <= 0.10;
    Stats.lowmargin_count = sum(LowMask);
    Stats.trusted_lowmargin_count = sum(LowMask & Meta.trusted(:) > 0);
    if any(LowMask)
        Stats.lowmargin_feasible_ratio = SafeDivide(sum(Meta.feasible(LowMask) == 1),sum(LowMask));
        Stats.lowmargin_mix_score = MeanOrNaN(Meta.oppSupport(LowMask));
        Stats.lowmargin_oppdist = MeanOrNaN(Meta.oppDist(LowMask & isfinite(Meta.oppDist)));
    end
end

function Diag = InitBoundaryDiag(Generation,FE,Budget)
    Diag = struct( ...
        'generation',Generation, ...
        'fe',FE, ...
        'budget',Budget, ...
        'attempts',0, ...
        'selected',0, ...
        'feasible',0, ...
        'infeasible',0, ...
        'helper_real_opp',0, ...
        'skipped_no_helper',0, ...
        'skipped_duplicate',0, ...
        'events',{cell(0,20)});
end

function Stats = ComputeBoundarySurvival(BoundaryOff,PopulationC,PopulationU)
    Stats = struct('selected_c',0,'selected_u',0);
    if isempty(BoundaryOff)
        return;
    end
    Stats.selected_c = sum(ismember(BoundaryOff.decs,PopulationC.decs,'rows'));
    Stats.selected_u = sum(ismember(BoundaryOff.decs,PopulationU.decs,'rows'));
end

function WriteCsvHeader(FilePath,Header)
    fid = fopen(FilePath,'w');
    Cleaner = onCleanup(@() fclose(fid)); %#ok<NASGU>
    fprintf(fid,'%s\n',strjoin(Header,','));
end

function AppendCsvRows(FilePath,Rows)
    if isempty(Rows)
        return;
    end
    if ~iscell(Rows)
        Rows = num2cell(Rows);
    end
    if isvector(Rows)
        Rows = reshape(Rows,1,[]);
    end
    fid = fopen(FilePath,'a');
    Cleaner = onCleanup(@() fclose(fid)); %#ok<NASGU>
    for i = 1 : size(Rows,1)
        Line = cell(1,size(Rows,2));
        for j = 1 : size(Rows,2)
            Line{j} = ToCsvValue(Rows{i,j});
        end
        fprintf(fid,'%s\n',strjoin(Line,','));
    end
end

function S = ToCsvValue(Value)
    if isstring(Value)
        Value = char(Value);
    end
    if ischar(Value)
        Value = strrep(Value,'"','""');
        S = ['"' Value '"'];
    elseif isempty(Value)
        S = '';
    elseif isnumeric(Value) || islogical(Value)
        if isscalar(Value)
            if isnan(Value)
                S = 'NaN';
            elseif isinf(Value)
                S = Ternary(Value > 0,'Inf','-Inf');
            else
                S = sprintf('%.15g',double(Value));
            end
        else
            Flat = Value(:)';
            Parts = arrayfun(@(x)sprintf('%.15g',double(x)),Flat,'UniformOutput',false);
            S = ['"' strjoin(Parts,';') '"'];
        end
    else
        S = ['"' char(string(Value)) '"'];
    end
end

function Out = Ternary(Cond,A,B)
    if Cond
        Out = A;
    else
        Out = B;
    end
end

%% ========== Boundary geometry helpers ==========

function ObjScore = ComputeBoundaryObjectiveScore(Candidates,PopulationC,W,RefObj,Sector)
    N = numel(Candidates);
    ObjScore = zeros(N,1);
    if isempty(Candidates)
        return;
    end

    Scalar = ComputeSectorScalar(Candidates.objs,W,RefObj,Sector);
    [FrontNo,~] = NDSort(Candidates.objs,numel(Candidates));
    if isempty(FrontNo) || max(FrontNo) <= 1
        FrontScore = zeros(N,1);
    else
        FrontScore = (FrontNo(:)-1)/max(max(FrontNo)-1,1);
    end

    ScalarScore = zeros(N,1);
    for s = unique(Sector(:))'
        idx = find(Sector == s);
        if isempty(idx)
            continue;
        end
        Value = Scalar(idx);
        Denom = max(Value) - min(Value);
        if Denom > 1e-12
            ScalarScore(idx) = (Value-min(Value))/Denom;
        end
    end

    Dominated = false(N,1);
    RepC = BuildSectorRepresentatives(PopulationC,W,RefObj,[]);
    for i = 1 : N
        s = Sector(i);
        if s > 0 && s <= numel(RepC.has) && RepC.has(s)
            Dominated(i) = DominatesObjectiveRow( ...
                PopulationC(RepC.idx(s)).objs,Candidates(i).objs);
        end
    end

    ObjScore = 0.4*FrontScore + 0.4*ScalarScore + 0.2*double(Dominated);
    ObjScore = max(0,min(1,ObjScore));
end

function Support = BuildBoundarySupportSet( ...
    Candidates,PopulationC,PopulationU,TrainArchive,W,RefObj)
    D = size(Candidates.decs,2);
    Support = struct( ...
        'Dec',zeros(0,D), ...
        'Label',zeros(0,1), ...
        'Sector',zeros(0,1));
    if ~isempty(TrainArchive.Dec)
        CoreMask = IsCoreTrainSource(TrainArchive.Source);
        Support.Dec    = TrainArchive.Dec(CoreMask,:);
        Support.Label  = TrainArchive.Label(CoreMask);
        Support.Sector = TrainArchive.Sector(CoreMask);
    end
    Support = AppendSupportPopulation(Support,Candidates,W,RefObj);
    Support = AppendSupportPopulation(Support,PopulationC,W,RefObj);
    Support = AppendSupportPopulation(Support,PopulationU,W,RefObj);
end

function Support = AppendSupportPopulation(Support,Population,W,RefObj)
    if isempty(Population)
        return;
    end

    Support.Dec    = [Support.Dec;Population.decs];
    Support.Label  = [Support.Label;double(all(Population.cons<=0,2))];
    Support.Sector = [Support.Sector;AssociateSectorsLocal(Population.objs,W,RefObj)];
    Keep = KeepLatestDecisionRowsLocal(Support.Dec);
    Support.Dec    = Support.Dec(Keep,:);
    Support.Label  = Support.Label(Keep);
    Support.Sector = Support.Sector(Keep);
end

function OppDist = ComputeOppositeDistanceByLabel( ...
    CandDec,CandLabel,CandSector,RefDec,RefLabel,RefSector,SectorNeighbors)
    OppDist = inf(size(CandDec,1),1);
    if isempty(CandDec) || isempty(RefDec)
        return;
    end

    for i = 1 : size(CandDec,1)
        Allowed = ResolveReferenceMask(CandSector(i),RefSector,SectorNeighbors);
        Opp = find(Allowed & RefLabel(:) ~= CandLabel(i));
        if isempty(Opp)
            continue;
        end
        Dist = sqrt(sum((RefDec(Opp,:) - CandDec(i,:)).^2,2));
        OppDist(i) = min(Dist);
    end
end

function Mask = ResolveReferenceMask(Sector,RefSector,SectorNeighbors)
    if isempty(RefSector)
        Mask = true(0,1);
        return;
    end
    if Sector <= 0 || Sector > numel(SectorNeighbors)
        Mask = true(numel(RefSector),1);
        return;
    end
    Allowed = unique([Sector;SectorNeighbors{Sector}(:)]);
    Mask = ismember(RefSector(:),Allowed);
end

function Scale = ResolveDistanceScale(Dec)
    if isempty(Dec)
        Scale = 1;
        return;
    end
    Range = max(Dec,[],1) - min(Dec,[],1);
    Scale = norm(Range)/sqrt(max(size(Dec,2),1));
    if ~isfinite(Scale) || Scale < 1e-6
        Scale = 1;
    end
end

%% ========== Sector / representative tools ==========

function [Core,Source] = BuildCoreTrainPopulation(B,RecentBoundaryOff)
    Core = B([]);
    Source = zeros(0,1);
    if ~isempty(B)
        Core = [Core,B];
        Source = [Source;ones(numel(B),1)];
    end
    if ~isempty(RecentBoundaryOff)
        Core = [Core,RecentBoundaryOff];
        Source = [Source;2*ones(numel(RecentBoundaryOff),1)];
    end
    if isempty(Core)
        return;
    end
    Keep = KeepLatestDecisionRowsLocal(Core.decs);
    Core = Core(Keep);
    Source = Source(Keep);
end

function AnchorIdx = SelectMissingSideAnchors( ...
    Core,CoreSector,CoreLabel,Population,Rep,SectorNeighbors,NeededLabel)
    AnchorIdx = zeros(0,1);
    if isempty(Core) || isempty(Population) || isempty(Rep.has)
        return;
    end

    for s = 1 : numel(Rep.has)
        Allowed = ResolveLocalSectorSet(s,SectorNeighbors);
        CoreIdx = find(ismember(CoreSector,Allowed));
        if isempty(CoreIdx)
            continue;
        end

        LocalLabel = unique(CoreLabel(CoreIdx));
        if numel(LocalLabel) > 1 || LocalLabel(1) == NeededLabel
            continue;
        end

        RepSector = Allowed(Rep.has(Allowed));
        if isempty(RepSector)
            continue;
        end

        CandidateIdx = Rep.idx(RepSector);
        Dist = ComputeRepresentativeToCoreDistance( ...
            Population(CandidateIdx),Core(CoreIdx));
        [~,ord] = sortrows([Dist(:),RepSector(:)],[1 2]);
        best = ord(1);
        AnchorIdx(end+1,1) = CandidateIdx(best); %#ok<AGROW>
    end

    AnchorIdx = unique(AnchorIdx,'stable');
end

function Dist = ComputeRepresentativeToCoreDistance(Representatives,Core)
    Dist = inf(numel(Representatives),1);
    if isempty(Representatives) || isempty(Core)
        return;
    end

    CoreDec = Core.decs;
    for i = 1 : numel(Representatives)
        Delta = CoreDec - Representatives(i).decs;
        Dist(i) = min(sqrt(sum(Delta.^2,2)));
    end
end

function Trusted = ResolveTrustedSectorsFromTrainArchive(TrainArchive,SectorNeighbors,K)
    if nargin < 3 || isempty(K)
        K = numel(SectorNeighbors);
    end
    CoreMask = IsCoreTrainSource(TrainArchive.Source);
    Trusted = ResolveTrustedSectors( ...
        TrainArchive.Label(CoreMask),TrainArchive.Sector(CoreMask), ...
        SectorNeighbors,K);
end

function Trusted = ResolveTrustedSectors(Label,Sector,SectorNeighbors,K)
    if nargin < 4 || isempty(K)
        K = max(numel(SectorNeighbors),max([0;Sector(:)]));
    end
    Trusted = false(K,1);
    if isempty(Label) || isempty(Sector)
        return;
    end

    for s = 1 : K
        Allowed = ResolveLocalSectorSet(s,SectorNeighbors);
        Local = Label(ismember(Sector(:),Allowed));
        Trusted(s) = any(Local == 0) && any(Local == 1);
    end
end

function Allowed = ResolveLocalSectorSet(Sector,SectorNeighbors)
    if Sector <= 0 || Sector > numel(SectorNeighbors)
        Allowed = Sector;
        return;
    end
    Allowed = unique([Sector;SectorNeighbors{Sector}(:)]);
end

function Mask = IsTrustedSector(Sector,TrustedSector)
    Mask = false(size(Sector));
    Valid = Sector > 0 & Sector <= numel(TrustedSector);
    Mask(Valid) = TrustedSector(Sector(Valid));
end

function Mask = IsCoreTrainSource(Source)
    Mask = Source(:) == 1 | Source(:) == 2;
end

function Rep = BuildSectorRepresentatives(Population,W,RefObj,Mask)
    K   = size(W,1);
    Rep = struct('has',false(K,1), ...
                 'idx',zeros(K,1), ...
                 'scalar',inf(K,1));
    if isempty(Population) || isempty(RefObj)
        return;
    end
    if nargin < 4 || isempty(Mask)
        Mask = true(numel(Population),1);
    end

    Sector = AssociateSectorsLocal(Population.objs,W,RefObj);
    Scalar = ComputeSectorScalar(Population.objs,W,RefObj,Sector);
    for s = 1 : K
        idx = find(Sector == s & Mask(:));
        if isempty(idx)
            continue;
        end
        [Rep.scalar(s),loc] = min(Scalar(idx));
        Rep.idx(s) = idx(loc);
        Rep.has(s) = true;
    end
end

function RefObj = BuildReferenceObj(varargin)
    RefObj = [];
    for i = 1 : nargin
        Population = varargin{i};
        if ~isempty(Population)
            RefObj = [RefObj;Population.objs]; %#ok<AGROW>
        end
    end
end

function [Sector,Count] = AssociateSectorsLocal(PopObj,W,RefObj)
    if nargin < 3 || isempty(RefObj)
        RefObj = PopObj;
    end
    if isempty(PopObj)
        Sector = zeros(0,1);
        Count  = zeros(size(W,1),1);
        return;
    end
    if isempty(W)
        Sector = ones(size(PopObj,1),1);
        Count  = size(PopObj,1);
        return;
    end

    MinObj = min(RefObj,[],1);
    MaxObj = max(RefObj,[],1);
    Range  = MaxObj - MinObj;
    Range(Range < 1e-12) = 1;

    Obj = (PopObj - MinObj)./Range;
    ObjNorm = sqrt(sum(Obj.^2,2));
    ZeroMask = ObjNorm < 1e-12;
    Obj(ZeroMask,:) = 1;
    ObjNorm(ZeroMask) = sqrt(size(Obj,2));
    Obj = Obj./ObjNorm(:,ones(1,size(Obj,2)));

    WNorm = sqrt(sum(W.^2,2));
    WNorm(WNorm < 1e-12) = 1;
    Wn = W./WNorm(:,ones(1,size(W,2)));

    Cosine = Obj*Wn';
    [~,Sector] = max(Cosine,[],2);
    Count = accumarray(Sector,1,[size(W,1),1]);
end

function Value = ComputeSectorScalar(Obj,W,RefObj,Sector)
    if isempty(Obj)
        Value = zeros(0,1);
        return;
    end
    if nargin < 2 || isempty(W)
        W = ones(1,size(Obj,2));
    end
    if nargin < 3 || isempty(RefObj)
        RefObj = Obj;
    end
    if nargin < 4 || isempty(Sector)
        Weight = repmat(W(1,:),size(Obj,1),1);
    else
        Weight = W(Sector,:);
    end

    MinObj  = min(RefObj,[],1);
    MaxObj  = max(RefObj,[],1);
    Range   = MaxObj - MinObj;
    Range(Range < 1e-12) = 1;
    NormObj = (Obj-MinObj)./Range;
    Value   = sum(NormObj.*Weight,2);
end

function Neighbors = BuildSectorNeighbors(W,NeighborCount)
    K = size(W,1);
    Neighbors = cell(K,1);
    if K <= 1 || NeighborCount <= 0
        return;
    end

    WNorm = sqrt(sum(W.^2,2));
    WNorm(WNorm < 1e-12) = 1;
    Wn = W./WNorm(:,ones(1,size(W,2)));
    Cosine = Wn*Wn';
    Cosine(1:K+1:end) = -inf;

    for i = 1 : K
        [~,ord] = sort(Cosine(i,:),'descend');
        Neighbors{i} = ord(1:min(NeighborCount,K-1));
    end
end

%% ========== Environmental selection ==========

function Population = EnvironmentalSelectionC(Population,N,W)
    Population = KeepUniquePopulation(Population);
    if isempty(Population)
        return;
    end

    Feasible = FilterFeasiblePopulation(Population);
    if numel(Feasible) >= N
        Population = ObjectiveSelectionWithLastSectorTruncation(Feasible,N,W);
    else
        Next   = Feasible;
        Need   = N - numel(Next);
        Remain = RemovePopulationByDecision(Population,Next);
        if Need > 0 && ~isempty(Remain)
            Next = [Next,ObjectiveSelectionWithLastSectorTruncation( ...
                Remain,min(Need,numel(Remain)),W)]; %#ok<AGROW>
        end
        Population = PadPopulation(Next,N);
    end
end

function Population = EnvironmentalSelectionU(Population,N,W)
    Population = KeepUniquePopulation(Population);
    Population = ObjectiveSelectionWithLastSectorTruncation( ...
        Population,min(N,numel(Population)),W);
    Population = PadPopulation(Population,N);
end

function Population = ObjectiveSelectionWithLastSectorTruncation(Population,N,W)
    if isempty(Population)
        return;
    end
    if N <= 0
        Population = Population([]);
        return;
    end

    N = min(N,numel(Population));
    if numel(Population) <= N
        return;
    end

    [FrontNo,MaxFNo] = NDSort(Population.objs,N);
    Next = FrontNo < MaxFNo;
    Last = find(FrontNo == MaxFNo);
    Need = N - sum(Next);
    if Need > 0 && ~isempty(Last)
        PickLast = SelectLastFrontBySector(Population(Last),Need,W,Population.objs);
        Next(Last(PickLast)) = true;
    end
    Population = Population(Next);
end

function Pick = SelectLastFrontBySector(LastPopulation,N,W,RefObj)
    Pick = zeros(0,1);
    if isempty(LastPopulation) || N <= 0
        return;
    end

    N = min(N,numel(LastPopulation));
    if isempty(W)
        CrowdDis = CrowdingDistance(LastPopulation.objs,ones(1,numel(LastPopulation)));
        [~,ord]  = sort(CrowdDis,'descend');
        Pick     = ord(1:N);
        return;
    end

    Sector   = AssociateSectorsLocal(LastPopulation.objs,W,RefObj);
    Scalar   = ComputeSectorScalar(LastPopulation.objs,W,RefObj,Sector);
    CrowdDis = CrowdingDistance(LastPopulation.objs,ones(1,numel(LastPopulation)));
    Ranked   = cell(size(W,1),1);
    for s = 1 : size(W,1)
        idx = find(Sector == s);
        if isempty(idx)
            continue;
        end
        Key = [-CrowdDis(idx)', Scalar(idx), idx];
        [~,ord] = sortrows(Key,[1 2 3]);
        Ranked{s} = idx(ord);
    end
    Order = SectorRoundRobinPick(Ranked,N);
    Pick  = Order(:,2);
end

function Population = PadPopulation(Population,N)
    if isempty(Population)
        return;
    end

    if numel(Population) < N
        Population = [Population,Population(mod(0:N-numel(Population)-1,numel(Population))+1)];
    else
        Population = Population(1:N);
    end
end

%% ========== Parent-selection indicators ==========

function [Flag,FrontNo,CrowdDis] = ConstraintSideIndicator(Population)
    [FrontNo,CrowdDis] = ObjectiveSideIndicator(Population);
    Flag = double(~all(Population.cons<=0,2));
end

function [FrontNo,CrowdDis] = ObjectiveSideIndicator(Population)
    [FrontNo,~] = NDSort(Population.objs,numel(Population));
    CrowdDis    = CrowdingDistance(Population.objs,FrontNo);
end

%% ========== Population utilities ==========

function Population = FilterFeasiblePopulation(Population)
    if isempty(Population)
        return;
    end
    Population = Population(all(Population.cons<=0,2));
end

function Population = KeepUniquePopulation(Population)
    if isempty(Population)
        return;
    end
    Keep = KeepLatestDecisionRowsLocal(Population.decs);
    Population = Population(Keep);
end

function Population = RemovePopulationByDecision(Population,Remove)
    if isempty(Population) || isempty(Remove)
        return;
    end
    Keep = ~ismember(Population.decs,Remove.decs,'rows');
    Population = Population(Keep);
end

function Keep = KeepLatestDecisionRowsLocal(Dec)
    if isempty(Dec)
        Keep = zeros(0,1);
        return;
    end
    [~,Keep] = unique(double(Dec),'rows','last');
    Keep = sort(Keep);
end

%% ========== Round-robin picker ==========

function Pick = SectorRoundRobinPick(Ranked,MaxPick)
    Pick = zeros(0,2);
    if isempty(Ranked) || MaxPick <= 0
        return;
    end

    Ptr = ones(numel(Ranked),1);
    while size(Pick,1) < MaxPick
        Changed = false;
        for s = 1 : numel(Ranked)
            if Ptr(s) <= numel(Ranked{s})
                Pick(end+1,:) = [s,Ranked{s}(Ptr(s))]; %#ok<AGROW>
                Ptr(s) = Ptr(s) + 1;
                Changed = true;
                if size(Pick,1) >= MaxPick
                    break;
                end
            end
        end
        if ~Changed
            break;
        end
    end
end

%% ========== Objective dominance ==========

function Flag = DominatesObjectiveRow(A,B)
    Tol  = 1e-12;
    Flag = all(A <= B + Tol) && any(A < B - Tol);
end
