classdef PRBCCMO1_t < ALGORITHM
% <2026> <multi> <real> <constrained>
% PRBCCMO1_t
% PRBCCMO1 with runtime diagnostics for boundary/archive behavior analysis
%
% type      --- 2    --- 1.GA, 2.DE
% hidden    --- 20   --- Hidden neurons of the boundary MLP
% epoch     --- 20   --- Training epochs per update
% lr        --- 0.01 --- Learning rate
% minClass  --- 20   --- Minimum samples of each class before first training
% earlyGap  --- 5    --- Model update gap in early stage
% lateGap   --- 15   --- Model update gap in late stage
% switchRho --- 0.5  --- Early/late switch FE ratio
%
% Diagnostic outputs:
%   Data/PRBCCMO1_t_analysis/<run-folder>/*.csv
% No analysis MAT files are generated by this tracer.

    methods
        function main(Algorithm,Problem)
            [W,Problem.N] = UniformPoint(Problem.N,Problem.M);
            [type,hidden,epoch,lr,minClass,earlyGap,lateGap,switchRho] = ...
                Algorithm.ParameterSet(2,20,20,0.01,20,5,15,0.5);

            MaxB         = 2*Problem.N;
            MaxTrain     = 6*Problem.N;
            Generation   = 0;
            Observer     = InitObserver(Algorithm,Problem,W,[type,hidden,epoch,lr,minClass,earlyGap,lateGap,switchRho],MaxB,MaxTrain);

            PopulationC  = Problem.Initialization();
            PopulationU  = Problem.Initialization();
            B            = [];
            Model        = [];
            TrainArchive = InitTrainArchive(Problem.D);

            PoolC = PopulationC;
            PoolU = PopulationU;

            SeedB     = GenerateCrossBoundaryOffspring(Problem,PopulationC,PopulationU,W,type);
            SeedDiag   = BuildBoundaryDiagnostics(SeedB,PopulationC,PopulationU,W,Model,'seed_cross',Generation,Problem.FE);
            Observer   = LogBoundaryDiagnostics(Observer,SeedDiag);

            [B,ArchiveDiag] = UpdateBoundaryArchive([B,SeedB],PopulationC,PopulationU,W,Model,MaxB,Generation,Problem.FE,'seed_archive');
            Observer        = LogBoundaryDiagnostics(Observer,ArchiveDiag);

            TrainArchive = UpdateTrainArchive(TrainArchive,B,PopulationC,PopulationU,W,MaxTrain);
            [Model,MLPEvent] = UpdateBoundaryModelIfNeeded(Model,TrainArchive,minClass,hidden,epoch,lr,Problem,Generation,earlyGap,lateGap,switchRho);
            Observer = LogMLPEvent(Observer,MLPEvent);
            Observer = LogArchiveMembers(Observer,B,PopulationC,PopulationU,W,Model,Generation,Problem.FE);
            Observer = LogGenerationSummary(Observer,Generation,Problem.FE,Problem.maxFE,PoolC,PoolU,PopulationC,PopulationU,B,W, ...
                SeedDiag,InitEmptyBoundaryDiag('search_parent',Generation,Problem.FE),InitEmptyBoundaryDiag('search',Generation,Problem.FE), ...
                SeedDiag,ArchiveDiag,InitMigrantStats(0),TrainArchive,MLPEvent);

            while Algorithm.NotTerminated(PopulationC)
                Generation = Generation + 1;

                OffspringC = GenerateWithinOffspring(Problem,PopulationC,type,true);
                OffspringU = GenerateWithinOffspring(Problem,PopulationU,type,false);

                PoolC = KeepUniquePopulation([PopulationC,OffspringC]);
                PoolU = KeepUniquePopulation([PopulationU,OffspringU]);

                CrossB    = GenerateCrossBoundaryOffspring(Problem,PoolC,PoolU,W,type);
                CrossDiag = BuildBoundaryDiagnostics(CrossB,PoolC,PoolU,W,Model,'cross',Generation,Problem.FE);
                Observer  = LogBoundaryDiagnostics(Observer,CrossDiag);

                [SearchB,SearchParentDiag] = GenerateArchiveBoundaryOffspring(Problem,B,PoolC,PoolU,W,Model,type,Generation,Problem.FE);
                SearchDiag = BuildBoundaryDiagnostics(SearchB,PoolC,PoolU,W,Model,'search',Generation,Problem.FE);
                Observer   = LogBoundaryDiagnostics(Observer,SearchParentDiag);
                Observer   = LogBoundaryDiagnostics(Observer,SearchDiag);

                BoundaryOff  = KeepUniquePopulation([CrossB,SearchB]);
                BoundaryDiag = BuildBoundaryDiagnostics(BoundaryOff,PoolC,PoolU,W,Model,'boundary_unique',Generation,Problem.FE);
                Observer     = LogBoundaryDiagnostics(Observer,BoundaryDiag);

                [Migrants,MigrantStats] = ExtractBoundaryMigrants(BoundaryOff,PoolC,W);

                [B,ArchiveDiag] = UpdateBoundaryArchive([B,BoundaryOff],PoolC,PoolU,W,Model,MaxB,Generation,Problem.FE,'archive_update');
                Observer        = LogBoundaryDiagnostics(Observer,ArchiveDiag);

                PopulationC = EnvironmentalSelectionC([PopulationC,OffspringC,Migrants],Problem.N);
                PopulationU = EnvironmentalSelectionU([PopulationU,OffspringU],Problem.N);

                TrainArchive = UpdateTrainArchive(TrainArchive,B,PopulationC,PopulationU,W,MaxTrain);
                [Model,MLPEvent] = UpdateBoundaryModelIfNeeded(Model,TrainArchive,minClass,hidden,epoch,lr,Problem,Generation,earlyGap,lateGap,switchRho);
                Observer = LogMLPEvent(Observer,MLPEvent);
                Observer = LogArchiveMembers(Observer,B,PopulationC,PopulationU,W,Model,Generation,Problem.FE);
                Observer = LogGenerationSummary(Observer,Generation,Problem.FE,Problem.maxFE,PoolC,PoolU,PopulationC,PopulationU,B,W, ...
                    CrossDiag,SearchParentDiag,SearchDiag,BoundaryDiag,ArchiveDiag,MigrantStats,TrainArchive,MLPEvent);
            end
        end
    end
end

%% ========== Offspring generation ==========

function Offspring = GenerateWithinOffspring(Problem,Population,type,isConstraintSide)
    if isempty(Population)
        Offspring = [];
        return;
    end
    N = numel(Population);
    if isConstraintSide
        [Flag,FrontNo,CrowdDis] = ConstraintSideIndicator(Population);
        MatingPool = TournamentSelection(2,2*N,Flag,FrontNo,-CrowdDis);
    else
        [FrontNo,CrowdDis] = ObjectiveSideIndicator(Population);
        MatingPool = TournamentSelection(2,2*N,FrontNo,-CrowdDis);
    end

    if type == 1
        Offspring = OperatorGAhalf(Problem,Population(MatingPool));
    else
        Offspring = OperatorDE(Problem,Population, ...
            Population(MatingPool(1:N)),Population(MatingPool(N+1:end)));
    end
end

function Offspring = GenerateCrossBoundaryOffspring(Problem,PopulationC,PopulationU,W,type)
    if isempty(PopulationC) || isempty(PopulationU)
        Offspring = [];
        return;
    end
    RefObj = [PopulationC.objs;PopulationU.objs];
    RepC   = BuildSectorRepresentatives(PopulationC,W,RefObj,true);
    RepU   = BuildSectorRepresentatives(PopulationU,W,RefObj,false);
    Shared = find(RepC.has & RepU.has);

    if isempty(Shared)
        Offspring = PopulationC([]);
        return;
    end

    ParentC   = PopulationC(RepC.idx(Shared));
    ParentU   = PopulationU(RepU.idx(Shared));
    Offspring = CrossTwoSets(Problem,ParentC,ParentU,type);
end

function [Offspring,Diag] = GenerateArchiveBoundaryOffspring(Problem,B,PopulationC,PopulationU,W,Model,type,Generation,FE)
    Diag = InitEmptyBoundaryDiag('search_parent',Generation,FE);
    if isempty(B) || isempty(PopulationC) || isempty(PopulationU)
        Offspring = [];
        return;
    end

    RefObj   = [B.objs;PopulationC.objs;PopulationU.objs];
    SectorB  = AssociateSectorsLocal(B.objs,W,RefObj);
    ScalarB  = ComputeSectorScalar(B.objs,W,RefObj,SectorB);
    RepC     = BuildSectorRepresentatives(PopulationC,W,RefObj,true);
    RepU     = BuildSectorRepresentatives(PopulationU,W,RefObj,false);
    [ProbB,~] = PredictBoundaryMLP(Model,B.decs);

    Diag = BuildBoundaryDiagnostics(B,PopulationC,PopulationU,W,Model,'search_parent',Generation,FE);

    ParentB   = B([]);
    Opposite  = PopulationC([]);

    for s = 1 : size(W,1)
        if ~RepC.has(s) || ~RepU.has(s)
            continue;
        end
        idx = find(SectorB == s);
        if isempty(idx)
            continue;
        end

        BetweenMask = IsBetween(ScalarB(idx),RepC.scalar(s),RepU.scalar(s));
        idxBetween  = idx(BetweenMask);
        if isempty(idxBetween)
            continue;
        end

        Mid    = 0.5*(RepC.scalar(s) + RepU.scalar(s));
        Span   = max(abs(RepC.scalar(s) - RepU.scalar(s)),1e-12);
        Score1 = abs(ProbB(idxBetween) - 0.5);
        Score2 = abs(ScalarB(idxBetween) - Mid)./Span;
        [~,order] = sortrows([Score1(:),Score2(:)],[1 2]);
        OrderIdx  = idxBetween(order);

        Diag.rank_in_sector(OrderIdx) = (1:numel(OrderIdx))';
        pick = OrderIdx(1);

        ParentB(end+1) = B(pick); %#ok<AGROW>
        Diag.selected(pick) = 1;
        if all(B(pick).cons <= 0,2)
            Opposite(end+1)          = PopulationU(RepU.idx(s)); %#ok<AGROW>
            Diag.opposite_side{pick} = 'U';
        else
            Opposite(end+1)          = PopulationC(RepC.idx(s)); %#ok<AGROW>
            Diag.opposite_side{pick} = 'C';
        end
    end

    if isempty(ParentB)
        Offspring = B([]);
    else
        Offspring = CrossTwoSets(Problem,ParentB,Opposite,type);
    end
end

function Offspring = CrossTwoSets(Problem,Parent1,Parent2,type)
    if isempty(Parent1) || isempty(Parent2)
        Offspring = [];
        return;
    end
    K = min(numel(Parent1),numel(Parent2));
    Parent1 = Parent1(1:K);
    Parent2 = Parent2(1:K);

    if type == 1
        Offspring = OperatorGAhalf(Problem,[Parent1,Parent2]);
    else
        Offspring = OperatorDE(Problem,Parent1,Parent2,Parent1);
    end
end

%% ========== Boundary archive ==========

function [B,Diag] = UpdateBoundaryArchive(CandidateB,PopulationC,PopulationU,W,Model,MaxB,Generation,FE,Phase)
    if nargin < 9
        Phase = 'archive_update';
    end
    if isempty(CandidateB)
        B    = CandidateB;
        Diag = InitEmptyBoundaryDiag(Phase,Generation,FE);
        return;
    end

    CandidateB = KeepUniquePopulation(CandidateB);
    Diag       = BuildBoundaryDiagnostics(CandidateB,PopulationC,PopulationU,W,Model,Phase,Generation,FE);

    RefObj  = [CandidateB.objs;PopulationC.objs;PopulationU.objs];
    SectorB = AssociateSectorsLocal(CandidateB.objs,W,RefObj);
    ScalarB = ComputeSectorScalar(CandidateB.objs,W,RefObj,SectorB);
    RepC    = BuildSectorRepresentatives(PopulationC,W,RefObj,true);
    RepU    = BuildSectorRepresentatives(PopulationU,W,RefObj,false);
    [Prob,~] = PredictBoundaryMLP(Model,CandidateB.decs);

    Ranked = cell(size(W,1),1);
    for s = 1 : size(W,1)
        if ~RepC.has(s) || ~RepU.has(s)
            continue;
        end
        idx = find(SectorB == s);
        if isempty(idx)
            continue;
        end

        idx = idx(IsBetween(ScalarB(idx),RepC.scalar(s),RepU.scalar(s)));
        if isempty(idx)
            continue;
        end

        Mid    = 0.5*(RepC.scalar(s) + RepU.scalar(s));
        Span   = max(abs(RepC.scalar(s) - RepU.scalar(s)),1e-12);
        Score1 = abs(Prob(idx) - 0.5);
        Score2 = abs(ScalarB(idx) - Mid)./Span;
        [~,order] = sortrows([Score1(:),Score2(:)],[1 2]);
        Ranked{s} = idx(order);
        Diag.rank_in_sector(Ranked{s}) = (1:numel(Ranked{s}))';
    end

    Pick  = zeros(0,1);
    Round = 1;
    while numel(Pick) < MaxB
        Changed = false;
        for s = 1 : numel(Ranked)
            if numel(Ranked{s}) >= Round
                Pick(end+1,1) = Ranked{s}(Round); %#ok<AGROW>
                Changed = true;
                if numel(Pick) >= MaxB
                    break;
                end
            end
        end
        if ~Changed
            break;
        end
        Round = Round + 1;
    end

    if isempty(Pick)
        B = CandidateB([]);
    else
        Pick            = unique(Pick,'stable');
        Diag.selected(Pick) = 1;
        B               = CandidateB(Pick);
    end
end

function [Migrants,Stats] = ExtractBoundaryMigrants(BoundaryOff,PopulationC,W)
    Stats = InitMigrantStats(numel(BoundaryOff));
    if isempty(BoundaryOff)
        Migrants = [];
        return;
    end

    BoundaryOff      = FilterFeasiblePopulation(BoundaryOff);
    Stats.feasible_total = numel(BoundaryOff);
    if isempty(BoundaryOff)
        Migrants = BoundaryOff;
        return;
    end

    RefObj    = [BoundaryOff.objs;PopulationC.objs];
    SectorOff = AssociateSectorsLocal(BoundaryOff.objs,W,RefObj);
    ScalarOff = ComputeSectorScalar(BoundaryOff.objs,W,RefObj,SectorOff);
    RepC      = BuildSectorRepresentatives(PopulationC,W,RefObj,true);

    Pick = zeros(0,1);
    for s = unique(SectorOff(:))'
        idx = find(SectorOff == s);
        [bestScalar,loc] = min(ScalarOff(idx));
        bestIdx = idx(loc);
        if ~RepC.has(s) || bestScalar < RepC.scalar(s)
            Pick(end+1,1) = bestIdx; %#ok<AGROW>
        end
    end

    if isempty(Pick)
        Migrants = BoundaryOff([]);
    else
        Migrants = BoundaryOff(Pick);
    end
    Stats.selected = numel(Migrants);
end

%% ========== Environmental selection ==========

function Population = EnvironmentalSelectionC(Population,N)
    Population = KeepUniquePopulation(Population);
    if isempty(Population)
        return;
    end

    Feasible = FilterFeasiblePopulation(Population);
    if numel(Feasible) >= N
        Population = SelectByObjective(Feasible,N);
    else
        Next   = Feasible;
        Need   = N - numel(Next);
        Remain = RemovePopulationByDecision(Population,Next);
        if Need > 0 && ~isempty(Remain)
            Next = [Next,SelectByObjective(Remain,min(Need,numel(Remain)))];
        end
        Population = PadPopulation(Next,N);
    end
end

function Population = EnvironmentalSelectionU(Population,N)
    Population = KeepUniquePopulation(Population);
    Population = SelectByObjective(Population,min(N,numel(Population)));
    Population = PadPopulation(Population,N);
end

function Population = SelectByObjective(Population,N)
    if isempty(Population)
        return;
    end
    if N <= 0
        Population = Population([]);
        return;
    end

    N = min(N,numel(Population));
    [FrontNo,MaxFNo] = NDSort(Population.objs,N);
    Next     = FrontNo < MaxFNo;
    CrowdDis = CrowdingDistance(Population.objs,FrontNo);
    Last     = find(FrontNo == MaxFNo);
    Need     = N - sum(Next);
    if Need > 0
        [~,Rank] = sort(CrowdDis(Last),'descend');
        Next(Last(Rank(1:Need))) = true;
    end
    Population = Population(Next);
end

function Population = PadPopulation(Population,N)
    if isempty(Population)
        return;
    end
    if numel(Population) < N
        Population = [Population,Population(mod(0:N-numel(Population)-1,numel(Population))+1)];
    else
        Population = Population(1:N);
    end
end

%% ========== Parent-selection indicators ==========

function [Flag,FrontNo,CrowdDis] = ConstraintSideIndicator(Population)
    [FrontNo,CrowdDis] = ObjectiveSideIndicator(Population);
    Flag = double(~all(Population.cons<=0,2));
end

function [FrontNo,CrowdDis] = ObjectiveSideIndicator(Population)
    [FrontNo,~] = NDSort(Population.objs,numel(Population));
    CrowdDis    = CrowdingDistance(Population.objs,FrontNo);
end

%% ========== Training archive ==========

function TrainArchive = InitTrainArchive(D)
    TrainArchive = struct( ...
        'Dec',zeros(0,D), ...
        'Label',zeros(0,1), ...
        'Source',zeros(0,1));
end

function TrainArchive = UpdateTrainArchive(TrainArchive,B,PopulationC,PopulationU,W,MaxTrain)
    RefObj = [PopulationC.objs;PopulationU.objs];
    if ~isempty(B)
        RefObj = [RefObj;B.objs];
    end

    RepC = BuildSectorRepresentatives(PopulationC,W,RefObj,true);
    RepU = BuildSectorRepresentatives(PopulationU,W,RefObj,false);

    TrainArchive = AppendTrainArchive(TrainArchive,B,1);
    if any(RepC.has)
        TrainArchive = AppendTrainArchive(TrainArchive,PopulationC(RepC.idx(RepC.has)),2);
    end
    if any(RepU.has)
        TrainArchive = AppendTrainArchive(TrainArchive,PopulationU(RepU.idx(RepU.has)),3);
    end
    TrainArchive = TrimTrainArchive(TrainArchive,MaxTrain);
end

function TrainArchive = AppendTrainArchive(TrainArchive,Population,Source)
    if isempty(Population)
        return;
    end
    TrainArchive.Dec    = [TrainArchive.Dec;Population.decs];
    TrainArchive.Label  = [TrainArchive.Label;double(all(Population.cons<=0,2))];
    TrainArchive.Source = [TrainArchive.Source;Source*ones(numel(Population),1)];

    Keep = KeepLatestDecisionRowsLocal(TrainArchive.Dec);
    TrainArchive.Dec    = TrainArchive.Dec(Keep,:);
    TrainArchive.Label  = TrainArchive.Label(Keep);
    TrainArchive.Source = TrainArchive.Source(Keep);
end

function TrainArchive = TrimTrainArchive(TrainArchive,MaxTrain)
    Count = size(TrainArchive.Dec,1);
    if Count <= MaxTrain
        return;
    end

    BQuota   = min(round(0.7*MaxTrain),sum(TrainArchive.Source==1));
    KeepB    = SelectLatestBalancedIndices(find(TrainArchive.Source==1),TrainArchive.Label,BQuota);
    RemQuota = MaxTrain - numel(KeepB);
    KeepO    = SelectLatestBalancedIndices(find(TrainArchive.Source~=1),TrainArchive.Label,RemQuota);

    Keep = unique([KeepB;KeepO],'stable');
    if numel(Keep) < MaxTrain
        Rest = setdiff((1:Count)',Keep,'stable');
        Need = min(MaxTrain-numel(Keep),numel(Rest));
        if Need > 0
            Keep = [Keep;Rest(end-Need+1:end)];
        end
    elseif numel(Keep) > MaxTrain
        Keep = Keep(end-MaxTrain+1:end);
    end

    Keep = sort(Keep);
    TrainArchive.Dec    = TrainArchive.Dec(Keep,:);
    TrainArchive.Label  = TrainArchive.Label(Keep);
    TrainArchive.Source = TrainArchive.Source(Keep);
end

function Idx = SelectLatestBalancedIndices(CandidateIdx,Label,Count)
    Idx = zeros(0,1);
    if isempty(CandidateIdx) || Count <= 0
        return;
    end

    CandidateIdx = CandidateIdx(:);
    Pos = CandidateIdx(Label(CandidateIdx)==1);
    Neg = CandidateIdx(Label(CandidateIdx)==0);

    Quota = floor(Count/2);
    if Quota > 0
        KeepPos = Pos(max(1,numel(Pos)-Quota+1):end);
        KeepNeg = Neg(max(1,numel(Neg)-Quota+1):end);
        Idx = unique([KeepPos;KeepNeg],'stable');
    end

    if numel(Idx) < Count
        Rest = setdiff(CandidateIdx,Idx,'stable');
        Need = min(Count-numel(Idx),numel(Rest));
        if Need > 0
            Idx = [Idx;Rest(end-Need+1:end)];
        end
    elseif numel(Idx) > Count
        Idx = Idx(end-Count+1:end);
    end

    Idx = sort(Idx);
end

function Flag = CanTrainBoundaryModel(TrainArchive,minClass)
    Flag = sum(TrainArchive.Label==1) >= minClass && ...
           sum(TrainArchive.Label==0) >= minClass;
end

function [Model,Event] = UpdateBoundaryModelIfNeeded(Model,TrainArchive,minClass,hidden,epoch,lr,Problem,Generation,earlyGap,lateGap,switchRho)
    Pos      = sum(TrainArchive.Label==1);
    Neg      = sum(TrainArchive.Label==0);
    CanTrain = CanTrainBoundaryModel(TrainArchive,minClass);
    Event    = InitMLPEvent(Generation,Problem.FE,Problem.maxFE,size(TrainArchive.Dec,1),Pos,Neg,CanTrain,HasBoundaryModel(Model));

    if ~CanTrain
        Event.action = 'not_ready';
        Event.reason = 'minclass_not_met';
        return;
    end

    if Problem.FE/max(Problem.maxFE,1) < switchRho
        Event.gap   = earlyGap;
        Event.stage = 'early';
    else
        Event.gap   = lateGap;
        Event.stage = 'late';
    end

    if isempty(Model) || mod(Generation,Event.gap) == 0
        [Model,TrainStats] = TrainBoundaryMLP(TrainArchive.Dec,TrainArchive.Label,hidden,epoch,lr,Model);
        Event.action            = 'train';
        Event.reason            = TrainStats.reason;
        Event.trained           = TrainStats.trained;
        Event.warm_start        = TrainStats.warm_start;
        Event.loss_before       = TrainStats.loss_before;
        Event.loss_after        = TrainStats.loss_after;
        Event.acc_before        = TrainStats.acc_before;
        Event.acc_after         = TrainStats.acc_after;
        Event.pos_prob_before   = TrainStats.pos_prob_before;
        Event.pos_prob_after    = TrainStats.pos_prob_after;
        Event.neg_prob_before   = TrainStats.neg_prob_before;
        Event.neg_prob_after    = TrainStats.neg_prob_after;
        Event.model_after       = HasBoundaryModel(Model);
    else
        Event.action      = 'wait_gap';
        Event.reason      = 'gap_not_reached';
        Event.model_after = HasBoundaryModel(Model);
    end
end

%% ========== Boundary MLP ==========

function [Model,Stats] = TrainBoundaryMLP(X,Y,Hidden,Epoch,LR,PrevModel)
    if nargin < 6
        PrevModel = [];
    end
    Model = PrevModel;
    Stats = InitTrainStats();

    if isempty(X) || size(X,1) < 4
        Stats.reason = 'insufficient_rows';
        return;
    end

    X = double(X);
    Y = double(Y(:) > 0);
    Stats.sample_count = size(X,1);
    Stats.pos_count    = sum(Y==1);
    Stats.neg_count    = sum(Y==0);
    if numel(unique(Y)) < 2
        Stats.reason = 'single_class';
        return;
    end

    Hidden    = max(2,round(Hidden));
    Epoch     = max(1,round(Epoch));
    LR        = max(double(LR),1e-4);
    [N,D]     = size(X);
    LambdaReg = 1e-4;

    PrevEvalModel    = [];
    Stats.warm_start = ~isempty(PrevModel) && IsWarmStartCompatible(PrevModel,D,Hidden);
    if Stats.warm_start
        PrevEvalModel = PrevModel;
    end
    BeforeStats = EvaluateBoundaryModel(PrevEvalModel,X,Y);
    Stats.loss_before     = BeforeStats.loss;
    Stats.acc_before      = BeforeStats.acc;
    Stats.pos_prob_before = BeforeStats.pos_prob;
    Stats.neg_prob_before = BeforeStats.neg_prob;

    Mu    = mean(X,1);
    Sigma = std(X,0,1);
    Sigma(Sigma<1e-12) = 1;

    if Stats.warm_start
        W1 = PrevModel.W1;  b1 = PrevModel.b1;
        W2 = PrevModel.W2;  b2 = PrevModel.b2;
    else
        W1 = 0.1*randn(D,Hidden);
        b1 = zeros(1,Hidden);
        W2 = 0.1*randn(Hidden,1);
        b2 = 0;
    end

    Xn = (X-Mu)./Sigma;
    [Weight,NormWeight] = BuildClassWeights(Y);

    for e = 1 : Epoch
        H = tanh(Xn*W1 + repmat(b1,N,1));
        Z = H*W2 + b2;
        P = 1./(1+exp(-Z));

        Delta2 = Weight.*(P-Y)./NormWeight;
        dW2 = H'*Delta2 + LambdaReg*W2;
        db2 = sum(Delta2);

        D1  = (Delta2*W2').*(1-H.^2);
        dW1 = Xn'*D1 + LambdaReg*W1;
        db1 = sum(D1,1);

        Step = LR/sqrt(e);
        W1 = W1 - Step*dW1;
        b1 = b1 - Step*db1;
        W2 = W2 - Step*dW2;
        b2 = b2 - Step*db2;
    end

    Model = struct();
    Model.Mu    = Mu;
    Model.Sigma = Sigma;
    Model.W1    = W1;
    Model.b1    = b1;
    Model.W2    = W2;
    Model.b2    = b2;

    AfterStats = EvaluateBoundaryModel(Model,X,Y);
    Stats.trained         = true;
    Stats.reason          = 'trained';
    Stats.loss_after      = AfterStats.loss;
    Stats.acc_after       = AfterStats.acc;
    Stats.pos_prob_after  = AfterStats.pos_prob;
    Stats.neg_prob_after  = AfterStats.neg_prob;
end

function [Prob,Stats] = PredictBoundaryMLP(Model,X)
    if nargin < 2 || isempty(X)
        Prob  = zeros(0,1);
        Stats = struct('logit',zeros(0,1));
        return;
    end
    if isempty(Model) || ~isfield(Model,'Mu')
        Prob  = 0.5*ones(size(X,1),1);
        Stats = struct('logit',zeros(size(X,1),1));
        return;
    end

    Xn = (double(X)-Model.Mu)./Model.Sigma;
    H  = tanh(Xn*Model.W1 + repmat(Model.b1,size(Xn,1),1));
    Z  = H*Model.W2 + Model.b2;
    Prob = 1./(1+exp(-Z));
    Prob = min(max(Prob,1e-6),1-1e-6);
    Stats = struct('logit',Z(:));
end

function Flag = HasBoundaryModel(Model)
    Flag = ~isempty(Model) && isfield(Model,'Mu') && isfield(Model,'W1') && isfield(Model,'W2');
end

function Flag = IsWarmStartCompatible(Model,D,Hidden)
    Flag = HasBoundaryModel(Model) && ...
           size(Model.W1,1) == D && size(Model.W1,2) == Hidden && ...
           size(Model.W2,1) == Hidden;
end

function [Weight,NormWeight] = BuildClassWeights(Y)
    N    = numel(Y);
    Pos  = sum(Y==1);
    Neg  = N - Pos;
    WPos = N/(2*max(1,Pos));
    WNeg = N/(2*max(1,Neg));
    Weight     = WNeg + (WPos-WNeg).*Y;
    NormWeight = max(sum(Weight),1);
end

function Stats = EvaluateBoundaryModel(Model,X,Y)
    Stats = struct('loss',NaN,'acc',NaN,'pos_prob',NaN,'neg_prob',NaN);
    if isempty(X) || isempty(Y)
        return;
    end
    [Prob,~] = PredictBoundaryMLP(Model,X);
    Prob = min(max(Prob(:),1e-6),1-1e-6);
    Y    = double(Y(:) > 0);
    Stats.loss = -mean(Y.*log(Prob) + (1-Y).*log(1-Prob));
    Stats.acc  = mean(double(Prob>=0.5) == Y);
    if any(Y==1)
        Stats.pos_prob = mean(Prob(Y==1));
    end
    if any(Y==0)
        Stats.neg_prob = mean(Prob(Y==0));
    end
end

%% ========== Sector tools ==========

function Rep = BuildSectorRepresentatives(Population,W,RefObj,PreferFeasible)
    K   = size(W,1);
    Rep = struct('has',false(K,1), ...
                 'idx',zeros(K,1), ...
                 'scalar',inf(K,1), ...
                 'feasible',false(K,1));
    if isempty(Population)
        return;
    end

    Sector = AssociateSectorsLocal(Population.objs,W,RefObj);
    Scalar = ComputeSectorScalar(Population.objs,W,RefObj,Sector);
    Fea    = all(Population.cons<=0,2);

    for s = 1 : K
        idx = find(Sector == s);
        if isempty(idx)
            continue;
        end
        if PreferFeasible
            idxF = idx(Fea(idx));
            if ~isempty(idxF)
                idx = idxF;
            end
        end
        [Rep.scalar(s),loc] = min(Scalar(idx));
        Rep.idx(s)      = idx(loc);
        Rep.has(s)      = true;
        Rep.feasible(s) = Fea(Rep.idx(s));
    end
end

function Flag = IsBetween(Value,A,B)
    lower = min(A,B) - 1e-12;
    upper = max(A,B) + 1e-12;
    Flag  = Value >= lower & Value <= upper;
end

function [Sector,Count] = AssociateSectorsLocal(PopObj,W,RefObj)
    if nargin < 3 || isempty(RefObj)
        RefObj = PopObj;
    end
    if isempty(PopObj)
        Sector = zeros(0,1);
        Count  = zeros(size(W,1),1);
        return;
    end
    if isempty(W)
        Sector = ones(size(PopObj,1),1);
        Count  = size(PopObj,1);
        return;
    end

    MinObj = min(RefObj,[],1);
    MaxObj = max(RefObj,[],1);
    Range  = MaxObj - MinObj;
    Range(Range<1e-12) = 1;

    Obj = (PopObj - MinObj)./Range;
    ObjNorm = sqrt(sum(Obj.^2,2));
    ZeroMask = ObjNorm < 1e-12;
    Obj(ZeroMask,:) = 1;
    ObjNorm(ZeroMask) = sqrt(size(Obj,2));
    Obj = Obj./ObjNorm(:,ones(1,size(Obj,2)));

    WNorm = sqrt(sum(W.^2,2));
    WNorm(WNorm<1e-12) = 1;
    Wn = W./WNorm(:,ones(1,size(W,2)));

    Cosine = Obj*Wn';
    [~,Sector] = max(Cosine,[],2);
    Count = accumarray(Sector,1,[size(W,1),1]);
end

function Value = ComputeSectorScalar(Obj,W,RefObj,Sector)
    if isempty(Obj)
        Value = zeros(0,1);
        return;
    end
    if nargin < 2 || isempty(W)
        W = ones(1,size(Obj,2));
    end
    if nargin < 3 || isempty(RefObj)
        RefObj = Obj;
    end
    if nargin < 4 || isempty(Sector)
        Weight = repmat(W(1,:),size(Obj,1),1);
    else
        Weight = W(Sector,:);
    end

    MinObj = min(RefObj,[],1);
    MaxObj = max(RefObj,[],1);
    Range  = MaxObj - MinObj;
    Range(Range<1e-12) = 1;
    NormObj = (Obj-MinObj)./Range;

    Value = sum(NormObj.*Weight,2);
end

%% ========== Diagnostics ==========

function Diag = BuildBoundaryDiagnostics(Candidates,PopulationC,PopulationU,W,Model,Phase,Generation,FE)
    N    = numel(Candidates);
    Diag = InitEmptyBoundaryDiag(Phase,Generation,FE);
    if N <= 0
        return;
    end

    RefObj   = [Candidates.objs;PopulationC.objs;PopulationU.objs];
    Sector    = AssociateSectorsLocal(Candidates.objs,W,RefObj);
    Scalar    = ComputeSectorScalar(Candidates.objs,W,RefObj,Sector);
    RepC      = BuildSectorRepresentatives(PopulationC,W,RefObj,true);
    RepU      = BuildSectorRepresentatives(PopulationU,W,RefObj,false);
    [Prob,~]  = PredictBoundaryMLP(Model,Candidates.decs);
    Feasible  = all(Candidates.cons<=0,2);

    Diag.count           = N;
    Diag.phase           = repmat({Phase},N,1);
    Diag.generation      = Generation*ones(N,1);
    Diag.fe              = FE*ones(N,1);
    Diag.candidate_index = (1:N)';
    Diag.sector          = Sector(:);
    Diag.feasible        = double(Feasible(:));
    Diag.scalar          = Scalar(:);
    Diag.prob            = Prob(:);
    Diag.abs_p05         = abs(Prob(:)-0.5);
    Diag.rank_in_sector  = nan(N,1);
    Diag.selected        = zeros(N,1);
    Diag.repC_has        = zeros(N,1);
    Diag.repU_has        = zeros(N,1);
    Diag.rep_gate_ok     = zeros(N,1);
    Diag.repC_index      = nan(N,1);
    Diag.repU_index      = nan(N,1);
    Diag.repC_scalar     = nan(N,1);
    Diag.repU_scalar     = nan(N,1);
    Diag.repC_feasible   = nan(N,1);
    Diag.repU_feasible   = nan(N,1);
    Diag.rep_pair_type   = repmat({''},N,1);
    Diag.scalar_lower    = nan(N,1);
    Diag.scalar_upper    = nan(N,1);
    Diag.scalar_mid      = nan(N,1);
    Diag.scalar_span     = nan(N,1);
    Diag.between_ok      = zeros(N,1);
    Diag.dist_to_c       = nan(N,1);
    Diag.dist_to_u       = nan(N,1);
    Diag.lambda_u_to_c   = nan(N,1);
    Diag.closer_to_c     = zeros(N,1);
    Diag.closer_to_u     = zeros(N,1);
    Diag.side_expected   = repmat({''},N,1);
    Diag.side_ok         = zeros(N,1);
    Diag.first_fail      = repmat({''},N,1);
    Diag.mid_dist_norm   = nan(N,1);
    Diag.opposite_side   = repmat({''},N,1);

    for i = 1 : N
        s = Sector(i);
        Diag.side_expected{i} = Ternary(Feasible(i),'C','U');
        if s <= 0 || s > numel(RepC.has)
            Diag.first_fail{i} = 'representative';
            continue;
        end

        Diag.repC_has(i)    = double(RepC.has(s));
        Diag.repU_has(i)    = double(RepU.has(s));
        Diag.rep_gate_ok(i) = double(RepC.has(s) && RepU.has(s));
        if ~Diag.rep_gate_ok(i)
            Diag.first_fail{i} = 'representative';
            continue;
        end

        Diag.repC_index(i)    = RepC.idx(s);
        Diag.repU_index(i)    = RepU.idx(s);
        Diag.repC_scalar(i)   = RepC.scalar(s);
        Diag.repU_scalar(i)   = RepU.scalar(s);
        Diag.repC_feasible(i) = double(RepC.feasible(s));
        Diag.repU_feasible(i) = double(RepU.feasible(s));
        Diag.rep_pair_type{i} = BuildPairType(RepC.feasible(s),RepU.feasible(s));

        Diag.scalar_lower(i)  = min(RepC.scalar(s),RepU.scalar(s));
        Diag.scalar_upper(i)  = max(RepC.scalar(s),RepU.scalar(s));
        Diag.scalar_mid(i)    = 0.5*(RepC.scalar(s)+RepU.scalar(s));
        Diag.scalar_span(i)   = max(abs(RepC.scalar(s)-RepU.scalar(s)),1e-12);
        Diag.mid_dist_norm(i) = abs(Scalar(i)-Diag.scalar_mid(i))/Diag.scalar_span(i);
        Diag.between_ok(i)    = double(IsBetween(Scalar(i),RepC.scalar(s),RepU.scalar(s)));
        if ~Diag.between_ok(i)
            Diag.first_fail{i} = 'scalar';
        end

        Diag.dist_to_c(i)     = abs(Scalar(i)-RepC.scalar(s));
        Diag.dist_to_u(i)     = abs(Scalar(i)-RepU.scalar(s));
        Diag.closer_to_c(i)   = double(Diag.dist_to_c(i) <= Diag.dist_to_u(i)+1e-12);
        Diag.closer_to_u(i)   = double(Diag.dist_to_u(i) <= Diag.dist_to_c(i)+1e-12);
        if abs(RepC.scalar(s)-RepU.scalar(s)) < 1e-12
            Diag.lambda_u_to_c(i) = 0.5;
        else
            Diag.lambda_u_to_c(i) = (Scalar(i)-RepU.scalar(s))/(RepC.scalar(s)-RepU.scalar(s));
        end

        if Feasible(i)
            Diag.side_ok(i) = double(Diag.between_ok(i) && Diag.closer_to_c(i));
        else
            Diag.side_ok(i) = double(Diag.between_ok(i) && Diag.closer_to_u(i));
        end

        if isempty(Diag.first_fail{i})
            if Diag.side_ok(i)
                Diag.first_fail{i} = 'pass';
            else
                Diag.first_fail{i} = 'relative_side';
            end
        end
    end
end

function Diag = InitEmptyBoundaryDiag(Phase,Generation,FE)
    Diag = struct( ...
        'count',0, ...
        'phase',{{}}, ...
        'generation',zeros(0,1), ...
        'fe',zeros(0,1), ...
        'candidate_index',zeros(0,1), ...
        'sector',zeros(0,1), ...
        'feasible',zeros(0,1), ...
        'scalar',zeros(0,1), ...
        'prob',zeros(0,1), ...
        'abs_p05',zeros(0,1), ...
        'rank_in_sector',zeros(0,1), ...
        'selected',zeros(0,1), ...
        'repC_has',zeros(0,1), ...
        'repU_has',zeros(0,1), ...
        'rep_gate_ok',zeros(0,1), ...
        'repC_index',zeros(0,1), ...
        'repU_index',zeros(0,1), ...
        'repC_scalar',zeros(0,1), ...
        'repU_scalar',zeros(0,1), ...
        'repC_feasible',zeros(0,1), ...
        'repU_feasible',zeros(0,1), ...
        'rep_pair_type',{{}}, ...
        'scalar_lower',zeros(0,1), ...
        'scalar_upper',zeros(0,1), ...
        'scalar_mid',zeros(0,1), ...
        'scalar_span',zeros(0,1), ...
        'between_ok',zeros(0,1), ...
        'dist_to_c',zeros(0,1), ...
        'dist_to_u',zeros(0,1), ...
        'lambda_u_to_c',zeros(0,1), ...
        'closer_to_c',zeros(0,1), ...
        'closer_to_u',zeros(0,1), ...
        'side_expected',{{}}, ...
        'side_ok',zeros(0,1), ...
        'first_fail',{{}}, ...
        'mid_dist_norm',zeros(0,1), ...
        'opposite_side',{{}});
    if nargin > 0
        Diag.phase      = repmat({Phase},0,1);
        Diag.generation = Generation*zeros(0,1);
        Diag.fe         = FE*zeros(0,1);
    end
end

function Summary = SummarizeBoundaryDiagnostics(Diag)
    Summary = struct('total',0,'feasible',0,'infeasible',0, ...
        'rep_ok',0,'between_ok',0,'side_ok',0,'pass_all',0, ...
        'fail_rep',0,'fail_scalar',0,'fail_side',0,'selected',0);
    if Diag.count <= 0
        return;
    end
    Summary.total      = Diag.count;
    Summary.feasible   = sum(Diag.feasible == 1);
    Summary.infeasible = Summary.total - Summary.feasible;
    Summary.rep_ok     = sum(Diag.rep_gate_ok == 1);
    Summary.between_ok = sum(Diag.between_ok == 1);
    Summary.side_ok    = sum(Diag.side_ok == 1);
    Summary.pass_all   = sum(strcmp(Diag.first_fail,'pass'));
    Summary.fail_rep   = sum(strcmp(Diag.first_fail,'representative'));
    Summary.fail_scalar = sum(strcmp(Diag.first_fail,'scalar'));
    Summary.fail_side   = sum(strcmp(Diag.first_fail,'relative_side'));
    Summary.selected    = sum(Diag.selected == 1);
end

function PairType = BuildPairType(CFea,UFea)
    PairType = sprintf('%s_%s',Ternary(CFea,'F','I'),Ternary(UFea,'F','I'));
end

function Stats = SummarizeRepresentativePairs(PopulationC,PopulationU,W,ExtraRef)
    Stats = struct('shared',0,'ff',0,'fi',0,'if',0,'ii',0);
    if nargin < 4
        ExtraRef = [];
    end
    if isempty(PopulationC) || isempty(PopulationU)
        return;
    end
    RefObj = [PopulationC.objs;PopulationU.objs];
    if ~isempty(ExtraRef)
        RefObj = [RefObj;ExtraRef];
    end
    RepC = BuildSectorRepresentatives(PopulationC,W,RefObj,true);
    RepU = BuildSectorRepresentatives(PopulationU,W,RefObj,false);
    Shared = find(RepC.has & RepU.has);
    Stats.shared = numel(Shared);
    for s = Shared(:)'
        PairType = BuildPairType(RepC.feasible(s),RepU.feasible(s));
        switch PairType
            case 'F_F'
                Stats.ff = Stats.ff + 1;
            case 'F_I'
                Stats.fi = Stats.fi + 1;
            case 'I_F'
                Stats.if = Stats.if + 1;
            case 'I_I'
                Stats.ii = Stats.ii + 1;
        end
    end
end

function Stats = SummarizePopulation(Population)
    Stats = struct('size',0,'feasible',0,'infeasible',0);
    if isempty(Population)
        return;
    end
    Stats.size       = numel(Population);
    Stats.feasible   = sum(all(Population.cons<=0,2));
    Stats.infeasible = Stats.size - Stats.feasible;
end

function Stats = SummarizeArchive(B,PopulationC,PopulationU,W)
    Stats = struct('size',0,'feasible',0,'infeasible',0, ...
        'occupied_sectors',0,'max_sector_load',0,'mean_sector_load',0);
    if isempty(B)
        return;
    end

    Stats.size       = numel(B);
    Stats.feasible   = sum(all(B.cons<=0,2));
    Stats.infeasible = Stats.size - Stats.feasible;

    RefObj = [B.objs];
    if ~isempty(PopulationC)
        RefObj = [RefObj;PopulationC.objs];
    end
    if ~isempty(PopulationU)
        RefObj = [RefObj;PopulationU.objs];
    end
    Sector = AssociateSectorsLocal(B.objs,W,RefObj);
    Count  = accumarray(Sector,1,[size(W,1),1]);
    Occupied = Count(Count>0);
    Stats.occupied_sectors = numel(Occupied);
    if ~isempty(Occupied)
        Stats.max_sector_load  = max(Occupied);
        Stats.mean_sector_load = mean(Occupied);
    end
end

function Stats = InitMigrantStats(Total)
    Stats = struct('total',Total,'feasible_total',0,'selected',0);
end

function Event = InitMLPEvent(Generation,FE,MaxFE,TrainSize,Pos,Neg,CanTrain,ModelBefore)
    Event = struct( ...
        'generation',Generation, ...
        'fe',FE, ...
        'fe_ratio',FE/max(MaxFE,1), ...
        'train_size',TrainSize, ...
        'pos_count',Pos, ...
        'neg_count',Neg, ...
        'can_train',double(CanTrain), ...
        'model_before',double(ModelBefore), ...
        'model_after',double(ModelBefore), ...
        'stage','none', ...
        'gap',NaN, ...
        'action','none', ...
        'reason','none', ...
        'trained',0, ...
        'warm_start',0, ...
        'loss_before',NaN, ...
        'loss_after',NaN, ...
        'acc_before',NaN, ...
        'acc_after',NaN, ...
        'pos_prob_before',NaN, ...
        'pos_prob_after',NaN, ...
        'neg_prob_before',NaN, ...
        'neg_prob_after',NaN);
end

function Stats = InitTrainStats()
    Stats = struct( ...
        'trained',false, ...
        'warm_start',false, ...
        'reason','not_called', ...
        'sample_count',0, ...
        'pos_count',0, ...
        'neg_count',0, ...
        'loss_before',NaN, ...
        'loss_after',NaN, ...
        'acc_before',NaN, ...
        'acc_after',NaN, ...
        'pos_prob_before',NaN, ...
        'pos_prob_after',NaN, ...
        'neg_prob_before',NaN, ...
        'neg_prob_after',NaN);
end

%% ========== Logging ==========

function Observer = InitObserver(Algorithm,Problem,W,Params,MaxB,MaxTrain)
    RootDir    = fileparts(which('platemo'));
    BaseFolder = fullfile(RootDir,'Data','PRBCCMO1_t_analysis');
    [~,~]      = mkdir(BaseFolder);
    [~,Token]  = fileparts(tempname(BaseFolder));
    RunFolder  = fullfile(BaseFolder,sprintf('%s_%s_N%d_FE%d_%s',class(Algorithm),class(Problem),Problem.N,Problem.maxFE,Token));
    [~,~]      = mkdir(RunFolder);

    Observer = struct();
    Observer.folder          = RunFolder;
    Observer.meta_file       = fullfile(RunFolder,'run_meta.csv');
    Observer.summary_file    = fullfile(RunFolder,'generation_summary.csv');
    Observer.detail_file     = fullfile(RunFolder,'candidate_diagnostics.csv');
    Observer.archive_file    = fullfile(RunFolder,'archive_members.csv');
    Observer.mlp_file        = fullfile(RunFolder,'mlp_events.csv');

    WriteCsvHeader(Observer.meta_file,{ ...
        'algorithm','problem','M','D','N','maxFE','maxB','maxTrain', ...
        'type','hidden','epoch','lr','minClass','earlyGap','lateGap','switchRho','output_folder'});
    WriteCsvHeader(Observer.summary_file,{ ...
        'generation','fe','fe_ratio', ...
        'poolc_size','poolc_feasible','poolc_infeasible', ...
        'poolu_size','poolu_feasible','poolu_infeasible', ...
        'popc_size','popc_feasible','popc_infeasible', ...
        'popu_size','popu_feasible','popu_infeasible', ...
        'b_size','b_feasible','b_infeasible','b_occupied_sectors','b_max_sector_load','b_mean_sector_load', ...
        'shared_sectors','pair_ff','pair_fi','pair_if','pair_ii', ...
        'cross_total','cross_rep_ok','cross_between_ok','cross_side_ok','cross_pass_all', ...
        'search_parent_total','search_parent_rep_ok','search_parent_between_ok','search_parent_side_ok','search_parent_selected', ...
        'search_total','search_rep_ok','search_between_ok','search_side_ok','search_pass_all', ...
        'boundary_total','boundary_rep_ok','boundary_between_ok','boundary_side_ok','boundary_pass_all', ...
        'archive_total','archive_rep_ok','archive_between_ok','archive_side_ok','archive_pass_all','archive_selected', ...
        'migrant_total','migrant_feasible_total','migrant_selected', ...
        'train_size','train_pos','train_neg','mlp_can_train','mlp_model_before','mlp_model_after','mlp_action','mlp_reason','mlp_trained'});
    WriteCsvHeader(Observer.detail_file,{ ...
        'phase','generation','fe','candidate_index','sector','feasible', ...
        'repC_has','repU_has','rep_gate_ok','repC_index','repU_index','repC_scalar','repU_scalar', ...
        'repC_feasible','repU_feasible','rep_pair_type', ...
        'scalar','scalar_lower','scalar_upper','scalar_mid','scalar_span','between_ok', ...
        'dist_to_c','dist_to_u','lambda_u_to_c','closer_to_c','closer_to_u', ...
        'side_expected','side_ok','first_fail', ...
        'prob','abs_p05','mid_dist_norm','rank_in_sector','selected','opposite_side'});
    WriteCsvHeader(Observer.archive_file,{ ...
        'generation','fe','member_index','sector','feasible','scalar','prob','abs_p05', ...
        'repC_scalar','repU_scalar','between_ok','side_ok','lambda_u_to_c','rep_pair_type'});
    WriteCsvHeader(Observer.mlp_file,{ ...
        'generation','fe','fe_ratio','train_size','pos_count','neg_count','can_train', ...
        'model_before','model_after','stage','gap','action','reason','trained','warm_start', ...
        'loss_before','loss_after','acc_before','acc_after', ...
        'pos_prob_before','pos_prob_after','neg_prob_before','neg_prob_after'});

    AppendCsvRows(Observer.meta_file,{ ...
        class(Algorithm),class(Problem),Problem.M,Problem.D,Problem.N,Problem.maxFE,MaxB,MaxTrain, ...
        Params(1),Params(2),Params(3),Params(4),Params(5),Params(6),Params(7),Params(8),RunFolder});
end

function Observer = LogBoundaryDiagnostics(Observer,Diag)
    if Diag.count <= 0
        return;
    end
    Rows = cell(Diag.count,36);
    for i = 1 : Diag.count
        Rows(i,:) = { ...
            Diag.phase{i},Diag.generation(i),Diag.fe(i),Diag.candidate_index(i),Diag.sector(i),Diag.feasible(i), ...
            Diag.repC_has(i),Diag.repU_has(i),Diag.rep_gate_ok(i),Diag.repC_index(i),Diag.repU_index(i),Diag.repC_scalar(i),Diag.repU_scalar(i), ...
            Diag.repC_feasible(i),Diag.repU_feasible(i),Diag.rep_pair_type{i}, ...
            Diag.scalar(i),Diag.scalar_lower(i),Diag.scalar_upper(i),Diag.scalar_mid(i),Diag.scalar_span(i),Diag.between_ok(i), ...
            Diag.dist_to_c(i),Diag.dist_to_u(i),Diag.lambda_u_to_c(i),Diag.closer_to_c(i),Diag.closer_to_u(i), ...
            Diag.side_expected{i},Diag.side_ok(i),Diag.first_fail{i}, ...
            Diag.prob(i),Diag.abs_p05(i),Diag.mid_dist_norm(i),Diag.rank_in_sector(i),Diag.selected(i),Diag.opposite_side{i}};
    end
    AppendCsvRows(Observer.detail_file,Rows);
end

function Observer = LogArchiveMembers(Observer,B,PopulationC,PopulationU,W,Model,Generation,FE)
    if isempty(B)
        return;
    end
    Diag = BuildBoundaryDiagnostics(B,PopulationC,PopulationU,W,Model,'archive_member',Generation,FE);
    Rows = cell(Diag.count,14);
    for i = 1 : Diag.count
        Rows(i,:) = { ...
            Generation,FE,i,Diag.sector(i),Diag.feasible(i),Diag.scalar(i),Diag.prob(i),Diag.abs_p05(i), ...
            Diag.repC_scalar(i),Diag.repU_scalar(i),Diag.between_ok(i),Diag.side_ok(i),Diag.lambda_u_to_c(i),Diag.rep_pair_type{i}};
    end
    AppendCsvRows(Observer.archive_file,Rows);
end

function Observer = LogMLPEvent(Observer,Event)
    AppendCsvRows(Observer.mlp_file,{ ...
        Event.generation,Event.fe,Event.fe_ratio,Event.train_size,Event.pos_count,Event.neg_count,Event.can_train, ...
        Event.model_before,Event.model_after,Event.stage,Event.gap,Event.action,Event.reason,Event.trained,Event.warm_start, ...
        Event.loss_before,Event.loss_after,Event.acc_before,Event.acc_after, ...
        Event.pos_prob_before,Event.pos_prob_after,Event.neg_prob_before,Event.neg_prob_after});
end

function Observer = LogGenerationSummary(Observer,Generation,FE,MaxFE,PoolC,PoolU,PopulationC,PopulationU,B,W,CrossDiag,SearchParentDiag,SearchDiag,BoundaryDiag,ArchiveDiag,MigrantStats,TrainArchive,MLPEvent)
    PoolCStats = SummarizePopulation(PoolC);
    PoolUStats = SummarizePopulation(PoolU);
    PopCStats  = SummarizePopulation(PopulationC);
    PopUStats  = SummarizePopulation(PopulationU);
    BStats     = SummarizeArchive(B,PopulationC,PopulationU,W);
    PairStats  = SummarizeRepresentativePairs(PoolC,PoolU,W,GetObjectiveMatrix(B));

    CrossSum       = SummarizeBoundaryDiagnostics(CrossDiag);
    SearchParentSum = SummarizeBoundaryDiagnostics(SearchParentDiag);
    SearchSum      = SummarizeBoundaryDiagnostics(SearchDiag);
    BoundarySum    = SummarizeBoundaryDiagnostics(BoundaryDiag);
    ArchiveSum     = SummarizeBoundaryDiagnostics(ArchiveDiag);

    AppendCsvRows(Observer.summary_file,{ ...
        Generation,FE,FE/max(MaxFE,1), ...
        PoolCStats.size,PoolCStats.feasible,PoolCStats.infeasible, ...
        PoolUStats.size,PoolUStats.feasible,PoolUStats.infeasible, ...
        PopCStats.size,PopCStats.feasible,PopCStats.infeasible, ...
        PopUStats.size,PopUStats.feasible,PopUStats.infeasible, ...
        BStats.size,BStats.feasible,BStats.infeasible,BStats.occupied_sectors,BStats.max_sector_load,BStats.mean_sector_load, ...
        PairStats.shared,PairStats.ff,PairStats.fi,PairStats.if,PairStats.ii, ...
        CrossSum.total,CrossSum.rep_ok,CrossSum.between_ok,CrossSum.side_ok,CrossSum.pass_all, ...
        SearchParentSum.total,SearchParentSum.rep_ok,SearchParentSum.between_ok,SearchParentSum.side_ok,SearchParentSum.selected, ...
        SearchSum.total,SearchSum.rep_ok,SearchSum.between_ok,SearchSum.side_ok,SearchSum.pass_all, ...
        BoundarySum.total,BoundarySum.rep_ok,BoundarySum.between_ok,BoundarySum.side_ok,BoundarySum.pass_all, ...
        ArchiveSum.total,ArchiveSum.rep_ok,ArchiveSum.between_ok,ArchiveSum.side_ok,ArchiveSum.pass_all,ArchiveSum.selected, ...
        MigrantStats.total,MigrantStats.feasible_total,MigrantStats.selected, ...
        size(TrainArchive.Dec,1),sum(TrainArchive.Label==1),sum(TrainArchive.Label==0),MLPEvent.can_train,MLPEvent.model_before,MLPEvent.model_after,MLPEvent.action,MLPEvent.reason,MLPEvent.trained});
end

function Obj = GetObjectiveMatrix(Population)
    if isempty(Population)
        Obj = zeros(0,0);
    else
        Obj = Population.objs;
    end
end

function WriteCsvHeader(FilePath,Header)
    fid = fopen(FilePath,'w');
    Cleaner = onCleanup(@() fclose(fid));
    fprintf(fid,'%s\n',strjoin(Header,','));
end

function AppendCsvRows(FilePath,Rows)
    if isempty(Rows)
        return;
    end
    if ~iscell(Rows)
        Rows = num2cell(Rows);
    end
    if isvector(Rows)
        Rows = reshape(Rows,1,[]);
    end
    fid = fopen(FilePath,'a');
    Cleaner = onCleanup(@() fclose(fid)); %#ok<NASGU>
    for i = 1 : size(Rows,1)
        Line = cell(1,size(Rows,2));
        for j = 1 : size(Rows,2)
            Line{j} = ToCsvValue(Rows{i,j});
        end
        fprintf(fid,'%s\n',strjoin(Line,','));
    end
end

function S = ToCsvValue(Value)
    if isstring(Value)
        Value = char(Value);
    end
    if ischar(Value)
        Value = strrep(Value,'"','""');
        S = ['"' Value '"'];
    elseif isempty(Value)
        S = '';
    elseif isnumeric(Value) || islogical(Value)
        if isscalar(Value)
            if isnan(Value)
                S = 'NaN';
            elseif isinf(Value)
                if Value > 0
                    S = 'Inf';
                else
                    S = '-Inf';
                end
            else
                S = sprintf('%.15g',double(Value));
            end
        else
            Flat = Value(:)';
            Parts = arrayfun(@(x)sprintf('%.15g',double(x)),Flat,'UniformOutput',false);
            S = ['"' strjoin(Parts,';') '"'];
        end
    else
        S = ['"' char(string(Value)) '"'];
    end
end

function Out = Ternary(Cond,A,B)
    if Cond
        Out = A;
    else
        Out = B;
    end
end

%% ========== Population utilities ==========

function Population = FilterFeasiblePopulation(Population)
    if isempty(Population)
        return;
    end
    Population = Population(all(Population.cons<=0,2));
end

function Population = KeepUniquePopulation(Population)
    if isempty(Population)
        return;
    end
    Keep = KeepLatestDecisionRowsLocal(Population.decs);
    Population = Population(Keep);
end

function Population = RemovePopulationByDecision(Population,Remove)
    if isempty(Population) || isempty(Remove)
        return;
    end
    Keep = ~ismember(Population.decs,Remove.decs,'rows');
    Population = Population(Keep);
end

function Keep = KeepLatestDecisionRowsLocal(Dec)
    if isempty(Dec)
        Keep = zeros(0,1);
        return;
    end
    [~,Keep] = unique(double(Dec),'rows','last');
    Keep = sort(Keep);
end
