function Suite = run_PRBCCMO_module_ablation_suite_dascmop9(varargin)
% Run the current BoundaryCore ablation suite on DASCMOP1_BC~DASCMOP9_BC.
%
% The suite covers the ablations that are currently implemented in the
% mainline codebase:
%   bridge  : BridgeTopK {1,3} and BridgeActivationGap {0,0.02}
%   finder  : MidpointOnly / Probe3Only / BoundaryCore-noTrust / mainline
%   selector: ParetoOnly / BoundaryOnly / RandomWithinShortlist / mainline
%   refine  : FeasibleForwardOff / InfeasibleShrinkOff
%   model   : beta vs raw calibrator
%   final   : NoBoundary (bRho = 0)
%
% Optional name-value pairs:
%   'Runs'        : independent runs per problem, default 5
%   'RunSeeds'    : explicit run seeds, default 1001:1005
%   'Population'  : population size, default 100
%   'MaxFE'       : max function evaluations, default 200000
%   'ProblemNames': explicit problem list, default DASCMOP1_BC~9_BC
%   'Workers'     : parallel workers used inside each ablation run, default 9
%   'UseParallel' : whether to enable parfor inside each run, default true
%   'OutputDir'   : output directory for CSV summaries, default timestamped dir
%   'Verbose'     : print per-variant progress, default true
%
% Output CSV files:
%   suite_manifest.csv
%   suite_run_summary.csv
%   suite_problem_summary.csv
%   suite_family_summary.csv
%   suite_pooled_summary.csv
%   variant_*_summary.csv for each ablation

    Params = struct( ...
        'Runs',5, ...
        'RunSeeds',[], ...
        'Population',100, ...
        'MaxFE',200000, ...
        'ProblemNames',{{}}, ...
        'Workers',9, ...
        'UseParallel',true, ...
        'OutputDir','', ...
        'Verbose',true);
    Params = ParseInputs(Params,varargin{:});
    Params.ProblemNames = NormalizeProblemNames(Params.ProblemNames);
    Params.RunSeeds = NormalizeRunSeeds(Params.RunSeeds,Params.Runs);
    Params.OutputDir = ResolveOutputDir(Params.OutputDir);
    EnsureDirectory(Params.OutputDir);

    Variants = ResolveSuiteVariants();
    Manifest = BuildVariantManifest(Variants);
    writetable(Manifest,fullfile(Params.OutputDir,'suite_manifest.csv'));

    RunSummaryTable = table();
    ProblemSummaryTable = table();
    FamilySummaryTable = table();
    PooledSummaryTable = table();

    if logical(Params.Verbose)
        fprintf('[AblationSuite] outputDir=%s\n',Params.OutputDir);
        fprintf('[AblationSuite] problems=%d runs=%d workers=%d variants=%d\n', ...
            numel(Params.ProblemNames),numel(Params.RunSeeds),Params.Workers,numel(Variants));
    end

    Suite = struct();
    Suite.params = Params;
    Suite.variantManifest = Manifest;
    Suite.variantResults = repmat(struct( ...
        'variant','', ...
        'description','', ...
        'calibrator','', ...
        'elapsedSeconds',NaN, ...
        'runSummary',table(), ...
        'problemSummary',table(), ...
        'familySummary',table(), ...
        'pooledSummary',table()),numel(Variants),1);

    for i = 1 : numel(Variants)
        Variant = Variants(i);
        VariantDir = fullfile(Params.OutputDir,Variant.id);
        EnsureDirectory(VariantDir);
        if logical(Params.Verbose)
            fprintf('[AblationSuite] (%d/%d) start %s\n',i,numel(Variants),Variant.id);
        end

        ticVariant = tic;
        Results = benchmark_PRBCCMO_module_validation( ...
            'Runs',Params.Runs, ...
            'RunSeeds',Params.RunSeeds, ...
            'Population',Params.Population, ...
            'MaxFE',Params.MaxFE, ...
            'ProblemNames',Params.ProblemNames, ...
            'UseParallel',Params.UseParallel, ...
            'Workers',Params.Workers, ...
            'Calibrator',Variant.calibrator, ...
            'AlgorithmOverride',Variant.algorithmOverride, ...
            'RuntimeOverride',Variant.runtimeOverride, ...
            'SavePrefix','', ...
            'SaveMat',false, ...
            'Verbose',false);
        Elapsed = toc(ticVariant);

        RunTable = AddVariantColumns( ...
            struct2table(Results.runSummary,'AsArray',true),Variant,Elapsed);
        ProblemTable = AddVariantColumns( ...
            struct2table(Results.problemSummary,'AsArray',true),Variant,Elapsed);
        FamilyTable = AddVariantColumns( ...
            struct2table(Results.familySummary,'AsArray',true),Variant,Elapsed);
        PooledTable = AddVariantColumns( ...
            struct2table(Results.pooledSummary,'AsArray',true),Variant,Elapsed);

        writetable(RunTable,fullfile(VariantDir,'variant_run_summary.csv'));
        writetable(ProblemTable,fullfile(VariantDir,'variant_problem_summary.csv'));
        writetable(FamilyTable,fullfile(VariantDir,'variant_family_summary.csv'));
        writetable(PooledTable,fullfile(VariantDir,'variant_pooled_summary.csv'));

        RunSummaryTable = AppendTables(RunSummaryTable,RunTable);
        ProblemSummaryTable = AppendTables(ProblemSummaryTable,ProblemTable);
        FamilySummaryTable = AppendTables(FamilySummaryTable,FamilyTable);
        PooledSummaryTable = AppendTables(PooledSummaryTable,PooledTable);

        Suite.variantResults(i).variant = Variant.id;
        Suite.variantResults(i).description = Variant.description;
        Suite.variantResults(i).calibrator = Variant.calibrator;
        Suite.variantResults(i).elapsedSeconds = Elapsed;
        Suite.variantResults(i).runSummary = RunTable;
        Suite.variantResults(i).problemSummary = ProblemTable;
        Suite.variantResults(i).familySummary = FamilyTable;
        Suite.variantResults(i).pooledSummary = PooledTable;

        if logical(Params.Verbose)
            fprintf('[AblationSuite] done %s elapsed=%.1fs pooledM1=%.4f pooledM2=%.4f pooledM5valid=%d\n', ...
                Variant.id,Elapsed,PooledTable.M1_mean(1),PooledTable.M2_mean(1),PooledTable.M5_validRunCount(1));
        end

        clear Results RunTable ProblemTable FamilyTable PooledTable;
    end

    writetable(RunSummaryTable,fullfile(Params.OutputDir,'suite_run_summary.csv'));
    writetable(ProblemSummaryTable,fullfile(Params.OutputDir,'suite_problem_summary.csv'));
    writetable(FamilySummaryTable,fullfile(Params.OutputDir,'suite_family_summary.csv'));
    writetable(PooledSummaryTable,fullfile(Params.OutputDir,'suite_pooled_summary.csv'));

    Suite.runSummary = RunSummaryTable;
    Suite.problemSummary = ProblemSummaryTable;
    Suite.familySummary = FamilySummaryTable;
    Suite.pooledSummary = PooledSummaryTable;
end

function Params = ParseInputs(Params,varargin)
    if mod(numel(varargin),2) ~= 0
        error('run_PRBCCMO_module_ablation_suite_dascmop9:InvalidInput', ...
            'Inputs must be name-value pairs.');
    end
    for i = 1 : 2 : numel(varargin)
        Name = varargin{i};
        if ~(ischar(Name) || (isstring(Name) && isscalar(Name)))
            error('run_PRBCCMO_module_ablation_suite_dascmop9:InvalidInputName', ...
                'Input names must be character vectors or scalar strings.');
        end
        Name = char(Name);
        if ~isfield(Params,Name)
            error('run_PRBCCMO_module_ablation_suite_dascmop9:UnknownOption', ...
                'Unknown option ''%s''.',Name);
        end
        Params.(Name) = varargin{i+1};
    end
end

function ProblemNames = NormalizeProblemNames(ProblemNames)
    if isempty(ProblemNames)
        ProblemNames = arrayfun(@(i)sprintf('DASCMOP%d_BC',i),1:9,'UniformOutput',false);
        return;
    end
    if ischar(ProblemNames) || (isstring(ProblemNames) && isscalar(ProblemNames))
        ProblemNames = {char(ProblemNames)};
    end
    ProblemNames = cellfun(@char,ProblemNames(:)','UniformOutput',false);
end

function RunSeeds = NormalizeRunSeeds(RunSeeds,Runs)
    if isempty(RunSeeds)
        RunSeeds = 1000 + (1:Runs);
        return;
    end
    RunSeeds = round(double(RunSeeds(:)'));
    RunSeeds = RunSeeds(isfinite(RunSeeds));
    if isempty(RunSeeds)
        error('run_PRBCCMO_module_ablation_suite_dascmop9:InvalidRunSeeds', ...
            'RunSeeds must contain at least one finite integer.');
    end
end

function OutputDir = ResolveOutputDir(OutputDir)
    if nargin >= 1 && ~isempty(OutputDir)
        OutputDir = char(OutputDir);
        return;
    end
    Stamp = char(string(datetime('now','Format','yyyyMMdd_HHmmss')));
    OutputDir = fullfile(pwd,['results_prbccmo_module_ablation_dascmop9_r5_',Stamp]);
end

function EnsureDirectory(PathStr)
    if exist(PathStr,'dir') ~= 7
        mkdir(PathStr);
    end
end

function Variants = ResolveSuiteVariants()
    Variants = repmat(struct( ...
        'id','', ...
        'description','', ...
        'calibrator','beta', ...
        'algorithmOverride',struct(), ...
        'runtimeOverride',struct()),15,1);

    Variants(1) = MakeVariant( ...
        'boundarycore_beta', ...
        'BoundaryCore mainline with beta calibrator', ...
        'beta',struct(),struct());
    Variants(2) = MakeVariant( ...
        'boundarycore_raw', ...
        'BoundaryCore mainline with raw calibrator', ...
        'raw',struct(),struct());
    Variants(3) = MakeVariant( ...
        'bridge_topk_1', ...
        'Bridge ablation with BridgeTopK = 1', ...
        'beta',struct(),struct('BridgeTopK',1));
    Variants(4) = MakeVariant( ...
        'bridge_topk_3', ...
        'Bridge ablation with BridgeTopK = 3', ...
        'beta',struct(),struct('BridgeTopK',3));
    Variants(5) = MakeVariant( ...
        'bridge_gap_0', ...
        'Bridge ablation with BridgeActivationGap = 0', ...
        'beta',struct(),struct('BridgeActivationGap',0));
    Variants(6) = MakeVariant( ...
        'bridge_gap_0p02', ...
        'Bridge ablation with BridgeActivationGap = 0.02', ...
        'beta',struct(),struct('BridgeActivationGap',0.02));
    Variants(7) = MakeVariant( ...
        'midpoint_only', ...
        'Finder ablation: midpoint only, no trust refine', ...
        'beta',struct(),struct( ...
            'BridgeScanLambda',0.5, ...
            'BridgeRefineStep',0, ...
            'DisableTrust',true));
    Variants(8) = MakeVariant( ...
        'probe3_only', ...
        'Finder ablation: three probes only, no local refine', ...
        'beta',struct(),struct( ...
            'BridgeScanLambda',[0.25 0.5 0.75], ...
            'BridgeRefineStep',0, ...
            'DisableTrust',true));
    Variants(9) = MakeVariant( ...
        'boundarycore_no_trust', ...
        'Trust ablation: disable trust but force placement refine', ...
        'beta',struct(),struct( ...
            'BridgeScanLambda',[0.25 0.5 0.75], ...
            'BridgeRefineStep',0.125, ...
            'DisableTrust',true, ...
            'ForcePlacementRefine',true));
    Variants(10) = MakeVariant( ...
        'selector_pareto_only', ...
        'Selector ablation: Pareto-only ordering', ...
        'beta',struct(),struct('SelectorMode','pareto_only'));
    Variants(11) = MakeVariant( ...
        'selector_boundary_only', ...
        'Selector ablation: boundary-only ordering', ...
        'beta',struct(),struct('SelectorMode','boundary_only'));
    Variants(12) = MakeVariant( ...
        'selector_random_shortlist', ...
        'Selector ablation: random selection within Pareto shortlist', ...
        'beta',struct(),struct('SelectorMode','random_within_shortlist'));
    Variants(13) = MakeVariant( ...
        'feasible_forward_off', ...
        'Refinement ablation: disable feasible forward exploit', ...
        'beta',struct(),struct('DisableFeasibleForward',true));
    Variants(14) = MakeVariant( ...
        'infeasible_shrink_off', ...
        'Refinement ablation: disable infeasible bracket shrink', ...
        'beta',struct(),struct('DisableInfeasibleShrink',true));
    Variants(15) = MakeVariant( ...
        'no_boundary', ...
        'Final-effect ablation: boundary budget disabled via bRho = 0', ...
        'beta',struct('bRho',0),struct());
end

function Variant = MakeVariant(Id,Description,Calibrator,AlgorithmOverride,RuntimeOverride)
    Variant = struct( ...
        'id',Id, ...
        'description',Description, ...
        'calibrator',Calibrator, ...
        'algorithmOverride',AlgorithmOverride, ...
        'runtimeOverride',RuntimeOverride);
end

function Manifest = BuildVariantManifest(Variants)
    Count = numel(Variants);
    Manifest = table('Size',[Count 5], ...
        'VariableTypes',{'string','string','string','string','string'}, ...
        'VariableNames',{'variant','description','calibrator','algorithmOverride','runtimeOverride'});
    for i = 1 : Count
        Manifest.variant(i) = string(Variants(i).id);
        Manifest.description(i) = string(Variants(i).description);
        Manifest.calibrator(i) = string(Variants(i).calibrator);
        Manifest.algorithmOverride(i) = string(StructToJson(Variants(i).algorithmOverride));
        Manifest.runtimeOverride(i) = string(StructToJson(Variants(i).runtimeOverride));
    end
end

function Text = StructToJson(Value)
    if isempty(Value)
        Text = '{}';
        return;
    end
    Text = jsonencode(Value);
end

function TableOut = AddVariantColumns(TableIn,Variant,Elapsed)
    TableOut = TableIn;
    Rows = height(TableOut);
    TableOut.variant = repmat(string(Variant.id),Rows,1);
    TableOut.variantDescription = repmat(string(Variant.description),Rows,1);
    TableOut.requestedCalibrator = repmat(string(Variant.calibrator),Rows,1);
    TableOut.variantElapsedSeconds = repmat(Elapsed,Rows,1);
end

function Result = AppendTables(Result,NewRows)
    if isempty(NewRows)
        return;
    end
    if isempty(Result)
        Result = NewRows;
        return;
    end
    Result = [Result;NewRows];
end
