function Results = run_PRBCCMO_step2_selector_acceptance_shard(RunIndex,varargin)
% Run one selector-acceptance shard for a single paired seed without MAT outputs.

    if nargin < 1 || isempty(RunIndex)
        error('PRBCCMO:SelectorAcceptanceShardInput', ...
            'RunIndex must be provided.');
    end

    Params = struct( ...
        'BaseDir',DefaultBaseDir(), ...
        'Problems',{{}}, ...
        'Runs',8, ...
        'Population',100, ...
        'MaxFE',200000, ...
        'Verbose',true);
    Params = ParseInputs(Params,varargin{:});

    RunIndex = round(double(RunIndex));
    if ~isfinite(RunIndex) || RunIndex < 1
        error('PRBCCMO:SelectorAcceptanceShardInput', ...
            'RunIndex must be a positive integer.');
    end

    BaseDir = char(Params.BaseDir);
    ShardDir = fullfile(BaseDir,sprintf('shard_%02d',RunIndex));
    if exist(ShardDir,'dir') ~= 7
        mkdir(ShardDir);
    end

    CheckArgs = { ...
        'Runs',Params.Runs, ...
        'RunIndices',RunIndex, ...
        'Population',Params.Population, ...
        'MaxFE',Params.MaxFE, ...
        'QueryVariants',{'ParetoOnly','FullSoftTrust'}, ...
        'CalibratorVariants',{'raw','beta'}, ...
        'SavePath','', ...
        'QueryCsv',fullfile(ShardDir,'step2_query_runs.csv'), ...
        'QueryUpdateCsv',fullfile(ShardDir,'step2_query_updates.csv'), ...
        'CalibratorCsv',fullfile(ShardDir,'step2_calibrator_runs.csv'), ...
        'QueryPairedCsv',fullfile(ShardDir,'step2_query_paired.csv'), ...
        'CalibratorPairedCsv',fullfile(ShardDir,'step2_calibrator_paired.csv'), ...
        'StopGoTargetVariant','FullSoftTrust', ...
        'StopGoSelectionDiffRateMin',0.05, ...
        'Verbose',logical(Params.Verbose)};
    if ~isempty(Params.Problems)
        CheckArgs = [CheckArgs, {'Problems',Params.Problems}]; %#ok<AGROW>
    end
    Results = check_PRBCCMO_step2_query_trust(CheckArgs{:});

    writetable(struct2table(Results.querySummary,'AsArray',true), ...
        fullfile(ShardDir,'step2_query_summary.csv'));
    writetable(struct2table(Results.calibratorSummary,'AsArray',true), ...
        fullfile(ShardDir,'step2_calibrator_summary.csv'));
    WriteDone(fullfile(ShardDir,'DONE.txt'),RunIndex);
end

function BaseDir = DefaultBaseDir()
    Here = fileparts(mfilename('fullpath'));
    BaseDir = fullfile(Here,'results_step2_selector_acceptance_r8_20260326');
end

function Params = ParseInputs(Params,varargin)
    if mod(numel(varargin),2) ~= 0
        error('PRBCCMO:SelectorAcceptanceShardInput', ...
            'Inputs must be provided as name-value pairs.');
    end
    for i = 1 : 2 : numel(varargin)
        Name = varargin{i};
        if ~isfield(Params,Name)
            error('PRBCCMO:SelectorAcceptanceShardInput', ...
                'Unknown parameter ''%s''.',Name);
        end
        Params.(Name) = varargin{i+1};
    end
end

function WriteDone(FilePath,RunIndex)
    FID = fopen(FilePath,'w');
    if FID < 0
        error('PRBCCMO:SelectorAcceptanceShardIO', ...
            'Unable to open DONE file: %s',FilePath);
    end
    Cleanup = onCleanup(@() fclose(FID));
    fprintf(FID,'run=%d\ncompleted=%s\n',RunIndex,datestr(now,31));
    clear Cleanup;
end
