function Results = run_PRBCCMO_step2_selector_diagnostic(varargin)
% Run the selector-only Step-2 diagnostic without saving MAT artifacts.

    Params = struct( ...
        'BaseDir',DefaultBaseDir(), ...
        'Problems',{{}}, ...
        'Runs',10, ...
        'RunIndices',[], ...
        'Population',100, ...
        'MaxFE',200000, ...
        'Verbose',true);
    Params = ParseInputs(Params,varargin{:});

    BaseDir = char(Params.BaseDir);
    if exist(BaseDir,'dir') ~= 7
        mkdir(BaseDir);
    end

    CheckArgs = { ...
        'Runs',Params.Runs, ...
        'RunIndices',Params.RunIndices, ...
        'Population',Params.Population, ...
        'MaxFE',Params.MaxFE, ...
        'QueryVariants',{'ParetoOnly','FullV2Current','FullNoTrust','FullSoftTrust'}, ...
        'CalibratorVariants',{'raw','beta'}, ...
        'SavePath','', ...
        'QueryCsv',fullfile(BaseDir,'step2_query_runs.csv'), ...
        'QueryUpdateCsv',fullfile(BaseDir,'step2_query_updates.csv'), ...
        'CalibratorCsv',fullfile(BaseDir,'step2_calibrator_runs.csv'), ...
        'QueryPairedCsv',fullfile(BaseDir,'step2_query_paired.csv'), ...
        'CalibratorPairedCsv',fullfile(BaseDir,'step2_calibrator_paired.csv'), ...
        'StopGoTargetVariant','FullSoftTrust', ...
        'StopGoSelectionDiffRateMin',0.05, ...
        'Verbose',logical(Params.Verbose)};
    if ~isempty(Params.Problems)
        CheckArgs = [CheckArgs, {'Problems',Params.Problems}]; %#ok<AGROW>
    end
    Results = check_PRBCCMO_step2_query_trust(CheckArgs{:});

    writetable(struct2table(Results.querySummary,'AsArray',true), ...
        fullfile(BaseDir,'step2_query_summary.csv'));
    writetable(struct2table(Results.calibratorSummary,'AsArray',true), ...
        fullfile(BaseDir,'step2_calibrator_summary.csv'));
    writetable(struct2table(BuildSelectorBoard(Results.querySummary),'AsArray',true), ...
        fullfile(BaseDir,'step2_selector_board.csv'));
end

function BaseDir = DefaultBaseDir()
    Here = fileparts(mfilename('fullpath'));
    BaseDir = fullfile(Here,'results_step2_selector_diag_20260326');
end

function Params = ParseInputs(Params,varargin)
    if mod(numel(varargin),2) ~= 0
        error('PRBCCMO:SelectorDiagnosticInput', ...
            'Inputs must be provided as name-value pairs.');
    end
    for i = 1 : 2 : numel(varargin)
        Name = varargin{i};
        if ~isfield(Params,Name)
            error('PRBCCMO:SelectorDiagnosticInput', ...
                'Unknown parameter ''%s''.',Name);
        end
        Params.(Name) = varargin{i+1};
    end
end

function Rows = BuildSelectorBoard(QuerySummary)
    Rows = repmat(InitSelectorBoardRow(),0,1);
    for i = 1 : numel(QuerySummary)
        Row = InitSelectorBoardRow();
        Row.calibratorVariant = QuerySummary(i).calibratorVariant;
        Row.queryVariant = QuerySummary(i).queryVariant;
        Row.selectionDiffPoolRate = QuerySummary(i).selectionDiffPoolRate;
        Row.oracleAuditEnabledRate = QuerySummary(i).oracleAuditEnabledRate;
        Row.passSelectionDiff = isfinite(Row.selectionDiffPoolRate) && Row.selectionDiffPoolRate > 0.05;
        Row.passOracleAudit = isfinite(Row.oracleAuditEnabledRate) && Row.oracleAuditEnabledRate > 0.30;
        Row.medianDB = QuerySummary(i).medianDB;
        Row.QPTau = QuerySummary(i).QPTau;
        Row.rhoUtilityNegDB = QuerySummary(i).rhoUtilityNegDB;
        Rows(end+1,1) = Row; %#ok<AGROW>
    end
end

function Row = InitSelectorBoardRow()
    Row = struct( ...
        'calibratorVariant','', ...
        'queryVariant','', ...
        'selectionDiffPoolRate',NaN, ...
        'oracleAuditEnabledRate',NaN, ...
        'passSelectionDiff',false, ...
        'passOracleAudit',false, ...
        'medianDB',NaN, ...
        'QPTau',NaN, ...
        'rhoUtilityNegDB',NaN);
end
