function Summary = summarize_PRBCCMO_t_run(runFolder)
% Summarize a single PRBCCMO_t trace folder without creating MAT files.

    arguments
        runFolder {mustBeTextScalar}
    end

    runFolder = char(string(runFolder));
    assert(isfolder(runFolder), ...
        'summarize_PRBCCMO_t_run:MissingFolder', ...
        'Run folder not found: %s', runFolder);

    metaFile    = fullfile(runFolder,'run_meta.csv');
    summaryFile = fullfile(runFolder,'generation_summary.csv');
    mlpFile     = fullfile(runFolder,'mlp_events.csv');
    assert(isfile(metaFile) && isfile(summaryFile) && isfile(mlpFile), ...
        'summarize_PRBCCMO_t_run:MissingCsv', ...
        'Run folder %s does not contain the required PRBCCMO_t CSV files.', runFolder);

    Meta = readtable(metaFile,'TextType','string');
    Gen  = readtable(summaryFile);
    MLP  = readtable(mlpFile);
    Gen = numericizeTable(Gen);
    MLP = numericizeTable(MLP);

    requireColumns(Gen,{ ...
        'generation','fe','boundary_selected','boundary_sector_coverage', ...
        'boundary_mean_pair_dist','boundary_lowmargin_pair_hit','boundary_seg_cross_dist', ...
        'boundary_margin_oppdist_corr','boundary_lowmargin_mean_opp_dist','boundary_highmargin_mean_opp_dist', ...
        'boundary_lowmargin_oppdist_gain','boundary_lowmargin_mean_opp_support','boundary_highmargin_mean_opp_support', ...
        'boundary_survive_c_rate','boundary_survive_u_rate', ...
        'b_size','b_sector_coverage','b_mean_pair_dist','b_lowmargin_pair_hit', ...
        'b_margin_oppdist_corr','b_lowmargin_mean_opp_dist','b_highmargin_mean_opp_dist', ...
        'b_lowmargin_oppdist_gain','b_lowmargin_mean_opp_support','b_highmargin_mean_opp_support', ...
        'train_size','train_anchor_count','train_pair_count','train_mean_pair_dist', ...
        'train_can_train','train_bal_acc_after','train_brier_after','train_logloss_after', ...
        'inf_pool_mean_margin','inf_selected_mean_margin','inf_margin_gain', ...
        'inf_pool_mean_obj_score','inf_selected_mean_obj_score','inf_obj_score_gain', ...
        'inf_pool_lowmargin_ratio','inf_selected_lowmargin_ratio','inf_lowmargin_ratio_gain', ...
        'model_trained','model_ready'},summaryFile);
    requireColumns(MLP,{ ...
        'trained','anchor_count','pair_count','mean_pair_dist'},mlpFile);

    Summary = struct( ...
        'problem',string(Meta.problem(1)), ...
        'family',string(Meta.family(1)), ...
        'analysis_folder',string(runFolder), ...
        'analysis_objective_csv',string(fullfile(runFolder,'objective_snapshot.csv')), ...
        'final_generation',NaN, ...
        'final_fe',NaN, ...
        'final_boundary_selected',NaN, ...
        'final_boundary_sector_coverage',NaN, ...
        'final_boundary_mean_pair_dist',NaN, ...
        'final_boundary_lowmargin_pair_hit',NaN, ...
        'final_boundary_seg_cross_dist',NaN, ...
        'final_boundary_margin_oppdist_corr',NaN, ...
        'final_boundary_lowmargin_mean_opp_dist',NaN, ...
        'final_boundary_highmargin_mean_opp_dist',NaN, ...
        'final_boundary_lowmargin_oppdist_gain',NaN, ...
        'final_boundary_lowmargin_mean_opp_support',NaN, ...
        'final_boundary_highmargin_mean_opp_support',NaN, ...
        'final_boundary_survive_c_rate',NaN, ...
        'final_boundary_survive_u_rate',NaN, ...
        'final_b_size',NaN, ...
        'final_b_sector_coverage',NaN, ...
        'final_b_mean_pair_dist',NaN, ...
        'final_b_lowmargin_pair_hit',NaN, ...
        'final_b_margin_oppdist_corr',NaN, ...
        'final_b_lowmargin_mean_opp_dist',NaN, ...
        'final_b_highmargin_mean_opp_dist',NaN, ...
        'final_b_lowmargin_oppdist_gain',NaN, ...
        'final_b_lowmargin_mean_opp_support',NaN, ...
        'final_b_highmargin_mean_opp_support',NaN, ...
        'final_train_size',NaN, ...
        'final_train_anchor_count',NaN, ...
        'final_train_pair_count',NaN, ...
        'final_train_mean_pair_dist',NaN, ...
        'final_train_can_train',NaN, ...
        'final_train_bal_acc',NaN, ...
        'final_train_brier',NaN, ...
        'final_train_logloss',NaN, ...
        'final_inf_pool_mean_margin',NaN, ...
        'final_inf_selected_mean_margin',NaN, ...
        'final_inf_margin_gain',NaN, ...
        'final_inf_pool_mean_obj_score',NaN, ...
        'final_inf_selected_mean_obj_score',NaN, ...
        'final_inf_obj_score_gain',NaN, ...
        'final_inf_pool_lowmargin_ratio',NaN, ...
        'final_inf_selected_lowmargin_ratio',NaN, ...
        'final_inf_lowmargin_ratio_gain',NaN, ...
        'first_can_train_generation',NaN, ...
        'first_can_train_fe',NaN, ...
        'first_trained_generation',NaN, ...
        'first_trained_fe',NaN, ...
        'stable3_generation',NaN, ...
        'stable3_fe',NaN, ...
        'trained_events',0);

    if isempty(Gen)
        return;
    end

    Last = Gen(end,:);
    Summary.final_generation = Last.generation;
    Summary.final_fe = Last.fe;
    Summary.final_boundary_selected = Last.boundary_selected;
    Summary.final_boundary_sector_coverage = Last.boundary_sector_coverage;
    Summary.final_boundary_mean_pair_dist = Last.boundary_mean_pair_dist;
    Summary.final_boundary_lowmargin_pair_hit = Last.boundary_lowmargin_pair_hit;
    Summary.final_boundary_seg_cross_dist = Last.boundary_seg_cross_dist;
    Summary.final_boundary_margin_oppdist_corr = Last.boundary_margin_oppdist_corr;
    Summary.final_boundary_lowmargin_mean_opp_dist = Last.boundary_lowmargin_mean_opp_dist;
    Summary.final_boundary_highmargin_mean_opp_dist = Last.boundary_highmargin_mean_opp_dist;
    Summary.final_boundary_lowmargin_oppdist_gain = Last.boundary_lowmargin_oppdist_gain;
    Summary.final_boundary_lowmargin_mean_opp_support = Last.boundary_lowmargin_mean_opp_support;
    Summary.final_boundary_highmargin_mean_opp_support = Last.boundary_highmargin_mean_opp_support;
    Summary.final_boundary_survive_c_rate = Last.boundary_survive_c_rate;
    Summary.final_boundary_survive_u_rate = Last.boundary_survive_u_rate;
    Summary.final_b_size = Last.b_size;
    Summary.final_b_sector_coverage = Last.b_sector_coverage;
    Summary.final_b_mean_pair_dist = Last.b_mean_pair_dist;
    Summary.final_b_lowmargin_pair_hit = Last.b_lowmargin_pair_hit;
    Summary.final_b_margin_oppdist_corr = Last.b_margin_oppdist_corr;
    Summary.final_b_lowmargin_mean_opp_dist = Last.b_lowmargin_mean_opp_dist;
    Summary.final_b_highmargin_mean_opp_dist = Last.b_highmargin_mean_opp_dist;
    Summary.final_b_lowmargin_oppdist_gain = Last.b_lowmargin_oppdist_gain;
    Summary.final_b_lowmargin_mean_opp_support = Last.b_lowmargin_mean_opp_support;
    Summary.final_b_highmargin_mean_opp_support = Last.b_highmargin_mean_opp_support;
    Summary.final_train_size = Last.train_size;
    Summary.final_train_anchor_count = Last.train_anchor_count;
    Summary.final_train_pair_count = Last.train_pair_count;
    Summary.final_train_mean_pair_dist = Last.train_mean_pair_dist;
    Summary.final_train_can_train = Last.train_can_train;
    Summary.final_train_bal_acc = Last.train_bal_acc_after;
    Summary.final_train_brier = Last.train_brier_after;
    Summary.final_train_logloss = Last.train_logloss_after;
    Summary.final_inf_pool_mean_margin = Last.inf_pool_mean_margin;
    Summary.final_inf_selected_mean_margin = Last.inf_selected_mean_margin;
    Summary.final_inf_margin_gain = Last.inf_margin_gain;
    Summary.final_inf_pool_mean_obj_score = Last.inf_pool_mean_obj_score;
    Summary.final_inf_selected_mean_obj_score = Last.inf_selected_mean_obj_score;
    Summary.final_inf_obj_score_gain = Last.inf_obj_score_gain;
    Summary.final_inf_pool_lowmargin_ratio = Last.inf_pool_lowmargin_ratio;
    Summary.final_inf_selected_lowmargin_ratio = Last.inf_selected_lowmargin_ratio;
    Summary.final_inf_lowmargin_ratio_gain = Last.inf_lowmargin_ratio_gain;
    Summary.first_can_train_generation = firstValue(Gen.generation,Gen.train_can_train > 0);
    Summary.first_can_train_fe = firstValue(Gen.fe,Gen.train_can_train > 0);
    Summary.first_trained_generation = firstValue(Gen.generation,Gen.model_trained > 0);
    Summary.first_trained_fe = firstValue(Gen.fe,Gen.model_trained > 0);
    [Summary.stable3_generation,Summary.stable3_fe] = firstConsecutiveWindow( ...
        Gen.generation,Gen.fe, ...
        Gen.train_can_train > 0 & Gen.model_ready > 0 & ...
        Gen.boundary_lowmargin_pair_hit >= 0.60 & ...
        (isnan(Gen.boundary_seg_cross_dist) | Gen.boundary_seg_cross_dist <= 5) & ...
        (isnan(Gen.boundary_lowmargin_oppdist_gain) | Gen.boundary_lowmargin_oppdist_gain >= 0) & ...
        (isnan(Gen.inf_lowmargin_ratio_gain) | Gen.inf_lowmargin_ratio_gain >= 0), ...
        3);
    Summary.trained_events = sum(MLP.trained > 0);
end

function value = firstValue(series,mask)
    idx = find(mask,1,'first');
    if isempty(idx)
        value = NaN;
    else
        value = series(idx);
    end
end

function [generation,fe] = firstConsecutiveWindow(generationSeries,feSeries,mask,window)
    generation = NaN;
    fe = NaN;
    if nargin < 4
        window = 3;
    end
    if isempty(mask) || window <= 0
        return;
    end

    count = 0;
    for i = 1 : numel(mask)
        if mask(i)
            count = count + 1;
            if count >= window
                idx = i - window + 1;
                generation = generationSeries(idx);
                fe = feSeries(idx);
                return;
            end
        else
            count = 0;
        end
    end
end

function requireColumns(T,Names,filePath)
    Missing = setdiff(string(Names),string(T.Properties.VariableNames));
    assert(isempty(Missing), ...
        'summarize_PRBCCMO_t_run:MissingColumns', ...
        'Missing columns in %s: %s', filePath, strjoin(cellstr(Missing), ', '));
end

function T = numericizeTable(T)
    Names = T.Properties.VariableNames;
    for i = 1 : numel(Names)
        Name = Names{i};
        Value = T.(Name);
        if iscell(Value)
            Num = cellfun(@str2double,Value);
            if any(~isnan(Num))
                T.(Name) = Num;
            end
        elseif isstring(Value)
            Num = str2double(Value);
            if any(~isnan(Num))
                T.(Name) = Num;
            end
        end
    end
end

function mustBeTextScalar(value)
    if ~(ischar(value) || (isstring(value) && isscalar(value)))
        error('summarize_PRBCCMO_t_run:InvalidRunFolder', ...
            'runFolder must be a character vector or string scalar.');
    end
end
