function Summary = summarize_PRBCCMO_t_run(runFolder)
% Summarize a single PRBCCMO_t trace folder without creating MAT files.

    arguments
        runFolder {mustBeTextScalar}
    end

    runFolder = char(string(runFolder));
    assert(isfolder(runFolder), ...
        'summarize_PRBCCMO_t_run:MissingFolder', ...
        'Run folder not found: %s', runFolder);

    metaFile    = fullfile(runFolder,'run_meta.csv');
    summaryFile = fullfile(runFolder,'generation_summary.csv');
    mlpFile     = fullfile(runFolder,'mlp_events.csv');
    assert(isfile(metaFile) && isfile(summaryFile) && isfile(mlpFile), ...
        'summarize_PRBCCMO_t_run:MissingCsv', ...
        'Run folder %s does not contain the required PRBCCMO_t CSV files.', runFolder);

    Meta = readtable(metaFile,'TextType','string');
    Gen  = readtable(summaryFile,'TextType','string');
    MLP  = readtable(mlpFile,'TextType','string');

    requireColumns(Gen,{ ...
        'generation','fe','boundary_selected','boundary_feasible_ratio', ...
        'boundary_sector_coverage','boundary_mean_pair_dist','boundary_lowmargin_pair_hit','boundary_seg_cross_dist', ...
        'b_size','b_feasible_ratio','b_sector_coverage','b_mixed_sectors','b_mean_pair_dist', ...
        'b_lowmargin_pair_hit','train_size','train_anchor_count','train_pair_count', ...
        'train_mean_pair_dist', ...
        'train_can_train','train_bal_acc_after','train_brier_after','train_minus_boundary_bal_gap', ...
        'train_minus_b_bal_gap','model_trained','model_ready_after','helper_real_opp_ratio', ...
        'helper_skip_no_helper','helper_skip_duplicate','boundary_attempts'},summaryFile);
    requireColumns(MLP,{ ...
        'trained','warm_start','can_train','anchor_count','pair_count','mean_pair_dist'},mlpFile);

    problem = char(string(Meta.problem(1)));
    family  = familyOfProblem(problem);

    Summary = struct( ...
        'problem',string(problem), ...
        'family',string(family), ...
        'analysis_folder',string(runFolder), ...
        'final_generation',NaN, ...
        'final_fe',NaN, ...
        'final_boundary_selected',NaN, ...
        'final_boundary_feasible_ratio',NaN, ...
        'final_boundary_sector_coverage',NaN, ...
        'final_boundary_mean_pair_dist',NaN, ...
        'final_boundary_lowmargin_pair_hit',NaN, ...
        'final_boundary_seg_cross_dist',NaN, ...
        'final_b_size',NaN, ...
        'final_b_feasible_ratio',NaN, ...
        'final_b_sector_coverage',NaN, ...
        'final_b_mixed_sectors',NaN, ...
        'final_b_mean_pair_dist',NaN, ...
        'final_b_lowmargin_pair_hit',NaN, ...
        'final_train_size',NaN, ...
        'final_train_anchor_count',NaN, ...
        'final_train_pair_count',NaN, ...
        'final_train_mean_pair_dist',NaN, ...
        'final_train_can_train',NaN, ...
        'final_train_bal_acc',NaN, ...
        'final_train_brier',NaN, ...
        'final_train_minus_boundary_bal_gap',NaN, ...
        'final_train_minus_b_bal_gap',NaN, ...
        'first_can_train_generation',NaN, ...
        'first_can_train_fe',NaN, ...
        'first_trained_generation',NaN, ...
        'first_trained_fe',NaN, ...
        'first_model_ready_generation',NaN, ...
        'first_model_ready_fe',NaN, ...
        'first_pair_hit_ge55_generation',NaN, ...
        'first_pair_hit_ge60_generation',NaN, ...
        'stable3_generation',NaN, ...
        'stable3_fe',NaN, ...
        'trained_events',0, ...
        'warm_start_events',0, ...
        'mean_helper_real_opp_ratio',NaN, ...
        'mean_helper_skip_no_helper',NaN, ...
        'mean_helper_skip_duplicate',NaN, ...
        'mean_boundary_attempts',NaN);

    if isempty(Gen)
        return;
    end

    Last = Gen(end,:);
    Summary.final_generation                 = Last.generation;
    Summary.final_fe                         = Last.fe;
    Summary.final_boundary_selected          = Last.boundary_selected;
    Summary.final_boundary_feasible_ratio    = Last.boundary_feasible_ratio;
    Summary.final_boundary_sector_coverage   = Last.boundary_sector_coverage;
    Summary.final_boundary_mean_pair_dist    = Last.boundary_mean_pair_dist;
    Summary.final_boundary_lowmargin_pair_hit = Last.boundary_lowmargin_pair_hit;
    Summary.final_boundary_seg_cross_dist    = Last.boundary_seg_cross_dist;
    Summary.final_b_size                     = Last.b_size;
    Summary.final_b_feasible_ratio           = Last.b_feasible_ratio;
    Summary.final_b_sector_coverage          = Last.b_sector_coverage;
    Summary.final_b_mixed_sectors            = Last.b_mixed_sectors;
    Summary.final_b_mean_pair_dist           = Last.b_mean_pair_dist;
    Summary.final_b_lowmargin_pair_hit       = Last.b_lowmargin_pair_hit;
    Summary.final_train_size                 = Last.train_size;
    Summary.final_train_anchor_count         = Last.train_anchor_count;
    Summary.final_train_pair_count           = Last.train_pair_count;
    Summary.final_train_mean_pair_dist       = Last.train_mean_pair_dist;
    Summary.final_train_can_train            = Last.train_can_train;
    Summary.final_train_bal_acc              = Last.train_bal_acc_after;
    Summary.final_train_brier                = Last.train_brier_after;
    Summary.final_train_minus_boundary_bal_gap = Last.train_minus_boundary_bal_gap;
    Summary.final_train_minus_b_bal_gap      = Last.train_minus_b_bal_gap;

    Summary.first_can_train_generation = firstValue(Gen.generation,Gen.train_can_train > 0);
    Summary.first_can_train_fe         = firstValue(Gen.fe,Gen.train_can_train > 0);
    Summary.first_trained_generation   = firstValue(Gen.generation,Gen.model_trained > 0);
    Summary.first_trained_fe           = firstValue(Gen.fe,Gen.model_trained > 0);
    Summary.first_model_ready_generation = firstValue(Gen.generation,Gen.model_ready_after > 0);
    Summary.first_model_ready_fe         = firstValue(Gen.fe,Gen.model_ready_after > 0);
    Summary.first_pair_hit_ge55_generation = firstValue(Gen.generation,Gen.boundary_lowmargin_pair_hit >= 0.55);
    Summary.first_pair_hit_ge60_generation = firstValue(Gen.generation,Gen.boundary_lowmargin_pair_hit >= 0.60);
    [Summary.stable3_generation,Summary.stable3_fe] = firstConsecutiveWindow( ...
        Gen.generation,Gen.fe, ...
        Gen.train_can_train > 0 & Gen.model_ready_after > 0 & ...
        Gen.boundary_lowmargin_pair_hit >= 0.60 & ...
        (isnan(Gen.boundary_seg_cross_dist) | Gen.boundary_seg_cross_dist <= 0.25), ...
        3);

    Summary.trained_events              = sum(MLP.trained > 0);
    Summary.warm_start_events           = sum(MLP.warm_start > 0);
    Summary.mean_helper_real_opp_ratio  = mean(Gen.helper_real_opp_ratio,'omitnan');
    Summary.mean_helper_skip_no_helper  = mean(Gen.helper_skip_no_helper,'omitnan');
    Summary.mean_helper_skip_duplicate  = mean(Gen.helper_skip_duplicate,'omitnan');
    Summary.mean_boundary_attempts      = mean(Gen.boundary_attempts,'omitnan');
end

function value = firstValue(series,mask)
    idx = find(mask,1,'first');
    if isempty(idx)
        value = NaN;
    else
        value = series(idx);
    end
end

function [generation,fe] = firstConsecutiveWindow(generationSeries,feSeries,mask,window)
    generation = NaN;
    fe = NaN;
    if nargin < 4
        window = 3;
    end
    if isempty(mask) || window <= 0
        return;
    end

    count = 0;
    for i = 1 : numel(mask)
        if mask(i)
            count = count + 1;
            if count >= window
                idx = i - window + 1;
                generation = generationSeries(idx);
                fe = feSeries(idx);
                return;
            end
        else
            count = 0;
        end
    end
end

function family = familyOfProblem(problem)
    if startsWith(problem,"DASCMOP")
        family = "DASCMOP_BC";
    elseif startsWith(problem,"LIRCMOP")
        family = "LIRCMOP_BC";
    else
        family = "OTHER";
    end
end

function requireColumns(T,Names,filePath)
    Missing = setdiff(string(Names),string(T.Properties.VariableNames));
    assert(isempty(Missing), ...
        'summarize_PRBCCMO_t_run:MissingColumns', ...
        'Missing columns in %s: %s', filePath, strjoin(cellstr(Missing), ', '));
end

function mustBeTextScalar(value)
    if ~(ischar(value) || (isstring(value) && isscalar(value)))
        error('summarize_PRBCCMO_t_run:InvalidRunFolder', ...
            'runFolder must be a character vector or string scalar.');
    end
end
