function Summary = summarize_PRBCCMO_t_data(baseFolder,outputCsv)
% Summarize PRBCCMO_t CSV runs into a single table.

    if nargin < 1 || isempty(baseFolder)
        rootDir = fileparts(which('platemo'));
        baseFolder = fullfile(rootDir,'Data','PRBCCMO_t');
    end
    if nargin < 2
        outputCsv = '';
    end

    runs = dir(fullfile(baseFolder,'PRBCCMO_t_*'));
    runs = runs([runs.isdir]);
    [~,ord] = sort([runs.datenum]);
    runs = runs(ord);

    rowsByKey = containers.Map('KeyType','char','ValueType','any');
    requiredCols = { ...
        'helper_real_opp_ratio','helper_skip_no_helper', ...
        'seed_b_size','seed_b_sector_coverage','seed_b_mixed_sectors', ...
        'b_trusted_count','b_trusted_sector_coverage','b_trusted_lowmargin_count', ...
        'b_bal_acc','b_brier','train_minus_boundary_bal_gap','train_minus_b_bal_gap', ...
        'boundary_attempts'};
    for i = 1 : numel(runs)
        runFolder = fullfile(baseFolder,runs(i).name);
        summaryFile = fullfile(runFolder,'generation_summary.csv');
        mlpFile = fullfile(runFolder,'mlp_events.csv');
        metaFile = fullfile(runFolder,'run_meta.csv');
        if ~exist(summaryFile,'file') || ~exist(mlpFile,'file') || ~exist(metaFile,'file')
            continue;
        end

        gen = readtable(summaryFile);
        mlp = readtable(mlpFile);
        meta = readtable(metaFile);
        if isempty(gen) || ~all(ismember(requiredCols,gen.Properties.VariableNames))
            continue;
        end

        last = gen(end,:);
        if last.fe_ratio < 0.99
            continue;
        end
        row = { ...
            string(meta.problem{1}), ...
            string(runFolder), ...
            runs(i).datenum, ...
            meta.N(1), ...
            meta.maxFE(1), ...
            last.fe, ...
            last.fe_ratio, ...
            last.popc_feasible_ratio, ...
            last.popu_feasible_ratio, ...
            last.seed_b_size, ...
            last.seed_b_sector_coverage, ...
            last.seed_b_mixed_sectors, ...
            last.b_size, ...
            last.b_sector_coverage, ...
            last.b_mixed_sectors, ...
            last.b_trusted_count, ...
            last.b_trusted_sector_coverage, ...
            last.b_trusted_lowmargin_count, ...
            last.lowmargin_count, ...
            last.lowmargin_feasible_ratio, ...
            last.lowmargin_mix_score, ...
            last.lowmargin_oppdist, ...
            LastNonMissing(gen.boundary_bal_acc), ...
            LastNonMissing(gen.b_bal_acc), ...
            LastNonMissing(gen.b_brier), ...
            LastNonMissing(gen.train_bal_acc_after), ...
            LastNonMissing(gen.train_minus_boundary_bal_gap), ...
            LastNonMissing(gen.train_minus_b_bal_gap), ...
            mean(gen.helper_real_opp_ratio,'omitnan'), ...
            mean(gen.helper_skip_no_helper,'omitnan'), ...
            mean(gen.boundary_attempts,'omitnan'), ...
            sum(mlp.trained > 0), ...
            sum(mlp.model_ready_after > 0)};
        key = sprintf('%s__%d__%d',meta.problem{1},meta.N(1),meta.maxFE(1));
        rowsByKey(key) = row;
    end

    keys = sort(rowsByKey.keys);
    rows = cell(numel(keys),33);
    for i = 1 : numel(keys)
        rows(i,:) = rowsByKey(keys{i});
    end

    Summary = cell2table(rows, ...
        'VariableNames',{ ...
            'problem','run_folder','run_datenum','N','maxFE','final_fe','final_fe_ratio', ...
            'final_popc_feasible_ratio','final_popu_feasible_ratio', ...
            'final_seed_b_size','final_seed_b_sector_coverage','final_seed_b_mixed_sectors', ...
            'final_b_size','final_b_sector_coverage','final_b_mixed_sectors', ...
            'final_b_trusted_count','final_b_trusted_sector_coverage','final_b_trusted_lowmargin_count', ...
            'final_lowmargin_count','final_lowmargin_feasible_ratio', ...
            'final_lowmargin_mix_score','final_lowmargin_oppdist', ...
            'final_boundary_bal_acc','final_b_bal_acc','final_b_brier', ...
            'final_train_bal_acc_after','final_train_minus_boundary_bal_gap','final_train_minus_b_bal_gap', ...
            'mean_helper_real_opp_ratio','mean_helper_skip_no_helper', ...
            'mean_boundary_attempts', ...
            'trained_generations','model_ready_generations'});

    if nargin >= 2 && ~isempty(outputCsv)
        writetable(Summary,outputCsv);
    end
end

function value = LastNonMissing(column)
    value = NaN;
    if isempty(column)
        return;
    end

    idx = find(~isnan(column),1,'last');
    if ~isempty(idx)
        value = column(idx);
    end
end
