function Summary = summarize_PRBCCMO_t_run(runFolder)
% Summarize one PRBCCMO_t run from the minimal core_metrics.csv contract.

    if nargin < 1 || isempty(runFolder)
        error('summarize_PRBCCMO_t_run:MissingRunFolder','runFolder is required.');
    end

    runFolder = char(string(runFolder));
    metaFile = fullfile(runFolder,'run_meta.csv');
    coreFile = fullfile(runFolder,'core_metrics.csv');
    assert(isfolder(runFolder) && isfile(metaFile) && isfile(coreFile), ...
        'summarize_PRBCCMO_t_run:MissingCsv', ...
        'Run folder must contain run_meta.csv and core_metrics.csv: %s', runFolder);

    Meta = readtable(metaFile,'TextType','string');
    Core = numericizeTable(readtable(coreFile,'TextType','string'));
    requireColumns(Core,coreMetricColumns(),coreFile);

    Summary = emptySummary(Meta,runFolder,metaFile,coreFile);
    if isempty(Core)
        return;
    end

    Last = Core(end,:);
    Trained = Core(Core.mlp_trained > 0,:);

    Summary.generation_count = height(Core);
    Summary.final_generation = scalarValue(Last,'generation');
    Summary.final_fe = scalarValue(Last,'fe');
    Summary.final_fe_ratio = scalarValue(Last,'fe_ratio');

    Summary.final_b_pair_count = scalarValue(Last,'b_pair_count');
    Summary.final_b_mean_pair_gap = scalarValue(Last,'b_mean_pair_gap');
    Summary.mean_b_mean_pair_gap = meanFinite(Core.b_mean_pair_gap);
    Summary.p90_b_mean_pair_gap = percentileFinite(Core.b_mean_pair_gap,90);
    Summary.final_b_p90_pair_gap = scalarValue(Last,'b_p90_pair_gap');
    Summary.final_b_mean_front_gap = scalarValue(Last,'b_mean_front_gap');
    Summary.mean_b_mean_front_gap = meanFinite(Core.b_mean_front_gap);
    Summary.final_b_mean_infeasible_boundary_dist = scalarValue(Last,'b_mean_infeasible_boundary_dist');
    Summary.mean_b_mean_infeasible_boundary_dist = meanFinite(Core.b_mean_infeasible_boundary_dist);
    Summary.final_b_p90_infeasible_boundary_dist = scalarValue(Last,'b_p90_infeasible_boundary_dist');
    Summary.final_b_max_infeasible_boundary_dist = scalarValue(Last,'b_max_infeasible_boundary_dist');
    Summary.final_b_far_infeasible_boundary_ratio = scalarValue(Last,'b_far_infeasible_boundary_ratio');
    Summary.mean_b_far_infeasible_boundary_ratio = meanFinite(Core.b_far_infeasible_boundary_ratio);
    Summary.final_b_inf_unconstrained_src_ratio = scalarValue(Last,'b_inf_unconstrained_src_ratio');
    Summary.mean_b_inf_unconstrained_src_ratio = meanFinite(Core.b_inf_unconstrained_src_ratio);
    Summary.final_b_overlap_popc_ratio = scalarValue(Last,'b_overlap_popc_ratio');
    Summary.mean_b_overlap_popc_ratio = meanFinite(Core.b_overlap_popc_ratio);
    Summary.final_b_overlap_popu_ratio = scalarValue(Last,'b_overlap_popu_ratio');
    Summary.mean_b_overlap_popu_ratio = meanFinite(Core.b_overlap_popu_ratio);
    Summary.final_b_inf_src_popu = scalarValue(Last,'b_inf_src_popu');
    Summary.final_b_inf_src_offu = scalarValue(Last,'b_inf_src_offu');
    Summary.final_b_inf_src_refinement = scalarValue(Last,'b_inf_src_refinement');
    Summary.final_b_active_sector_ratio = scalarValue(Last,'b_active_sector_ratio');
    Summary.mean_b_active_sector_ratio = meanFinite(Core.b_active_sector_ratio);
    Summary.mean_b_changed_pair_count = meanFinite(Core.b_changed_pair_count);
    Summary.mean_b_changed_pair_ratio = meanFinite(Core.b_changed_pair_ratio);
    Summary.mean_b_added_pair_count = meanFinite(Core.b_added_pair_count);
    Summary.mean_b_replaced_pair_count = meanFinite(Core.b_replaced_pair_count);
    Summary.mean_b_dropped_pair_count = meanFinite(Core.b_dropped_pair_count);
    Summary.mean_b_contracted_pair_count = meanFinite(Core.b_contracted_pair_count);
    Summary.mean_b_global_change_pair_ratio = meanFinite(Core.b_global_change_pair_ratio);
    Summary.mean_b_contraction_pair_ratio = meanFinite(Core.b_contraction_pair_ratio);

    Summary.mlp_due_events = sum(double(Core.mlp_due) > 0);
    Summary.mlp_can_train_events = sum(double(Core.mlp_can_train) > 0);
    Summary.mlp_trained_events = sum(double(Core.mlp_trained) > 0);
    Summary.mlp_degraded_events = sum(double(Core.mlp_degraded) > 0);
    Summary.final_mlp_train_acc = lastFinite(Trained.mlp_train_acc);
    Summary.mean_mlp_train_acc = meanFinite(Trained.mlp_train_acc);
    Summary.final_train_size = scalarValue(Last,'train_size');
    Summary.mean_train_size = meanFinite(Core.train_size);
    Summary.final_train_pos = scalarValue(Last,'train_pos');
    Summary.final_train_neg = scalarValue(Last,'train_neg');
    Summary.final_train_src_b = scalarValue(Last,'train_src_b');
    Summary.final_train_src_refinement = scalarValue(Last,'train_src_refinement');
    Summary.final_train_src_boundary_band = scalarValue(Last,'train_src_boundary_band');

    Summary.inf_pool_generations = sum(double(Core.inf_pool_size) > 0);
    Summary.inf_selection_generations = sum(double(Core.inf_selected) > 0);
    Summary.inf_selected_total = sumFinite(Core.inf_selected);
    Summary.mean_inf_pool_mean_prob = meanFinite(Core.inf_pool_mean_prob);
    Summary.mean_inf_selected_mean_prob = meanFinite(Core.inf_selected_mean_prob);
    Summary.mean_inf_prob_gain = meanFinite(Core.inf_prob_gain);
    Summary.pos_rate_inf_prob_gain = positiveRate(Core.inf_prob_gain);
    Summary.inf_carry_generations = sum(double(Core.inf_carry_selected) > 0);
    Summary.inf_carry_selected_total = sumFinite(Core.inf_carry_selected);
    Summary.mean_inf_carry_pool_mean_prob = meanFinite(Core.inf_carry_pool_mean_prob);
    Summary.mean_inf_carry_selected_mean_prob = meanFinite(Core.inf_carry_selected_mean_prob);
    Summary.mean_inf_carry_prob_gain = meanFinite(Core.inf_carry_prob_gain);
    Summary.pos_rate_inf_carry_prob_gain = positiveRate(Core.inf_carry_prob_gain);
end

function Summary = emptySummary(Meta,runFolder,metaFile,coreFile)
    Summary = struct( ...
        'problem',metaString(Meta,'problem',""), ...
        'family',metaString(Meta,'family',""), ...
        'run',metaDouble(Meta,'run',NaN), ...
        'N',metaDouble(Meta,'N',NaN), ...
        'maxFE',metaDouble(Meta,'maxFE',NaN), ...
        'analysis_folder',string(runFolder), ...
        'analysis_meta_csv',string(metaFile), ...
        'analysis_core_csv',string(coreFile), ...
        'generation_count',0, ...
        'final_generation',NaN, ...
        'final_fe',NaN, ...
        'final_fe_ratio',NaN, ...
        'final_b_pair_count',NaN, ...
        'final_b_mean_pair_gap',NaN, ...
        'mean_b_mean_pair_gap',NaN, ...
        'p90_b_mean_pair_gap',NaN, ...
        'final_b_p90_pair_gap',NaN, ...
        'final_b_mean_front_gap',NaN, ...
        'mean_b_mean_front_gap',NaN, ...
        'final_b_mean_infeasible_boundary_dist',NaN, ...
        'mean_b_mean_infeasible_boundary_dist',NaN, ...
        'final_b_p90_infeasible_boundary_dist',NaN, ...
        'final_b_max_infeasible_boundary_dist',NaN, ...
        'final_b_far_infeasible_boundary_ratio',NaN, ...
        'mean_b_far_infeasible_boundary_ratio',NaN, ...
        'final_b_inf_unconstrained_src_ratio',NaN, ...
        'mean_b_inf_unconstrained_src_ratio',NaN, ...
        'final_b_overlap_popc_ratio',NaN, ...
        'mean_b_overlap_popc_ratio',NaN, ...
        'final_b_overlap_popu_ratio',NaN, ...
        'mean_b_overlap_popu_ratio',NaN, ...
        'final_b_inf_src_popu',NaN, ...
        'final_b_inf_src_offu',NaN, ...
        'final_b_inf_src_refinement',NaN, ...
        'final_b_active_sector_ratio',NaN, ...
        'mean_b_active_sector_ratio',NaN, ...
        'mean_b_changed_pair_count',NaN, ...
        'mean_b_changed_pair_ratio',NaN, ...
        'mean_b_added_pair_count',NaN, ...
        'mean_b_replaced_pair_count',NaN, ...
        'mean_b_dropped_pair_count',NaN, ...
        'mean_b_contracted_pair_count',NaN, ...
        'mean_b_global_change_pair_ratio',NaN, ...
        'mean_b_contraction_pair_ratio',NaN, ...
        'mlp_due_events',NaN, ...
        'mlp_can_train_events',NaN, ...
        'mlp_trained_events',NaN, ...
        'mlp_degraded_events',NaN, ...
        'final_mlp_train_acc',NaN, ...
        'mean_mlp_train_acc',NaN, ...
        'final_train_size',NaN, ...
        'mean_train_size',NaN, ...
        'final_train_pos',NaN, ...
        'final_train_neg',NaN, ...
        'final_train_src_b',NaN, ...
        'final_train_src_refinement',NaN, ...
        'final_train_src_boundary_band',NaN, ...
        'inf_pool_generations',NaN, ...
        'inf_selection_generations',NaN, ...
        'inf_selected_total',NaN, ...
        'mean_inf_pool_mean_prob',NaN, ...
        'mean_inf_selected_mean_prob',NaN, ...
        'mean_inf_prob_gain',NaN, ...
        'pos_rate_inf_prob_gain',NaN, ...
        'inf_carry_generations',NaN, ...
        'inf_carry_selected_total',NaN, ...
        'mean_inf_carry_pool_mean_prob',NaN, ...
        'mean_inf_carry_selected_mean_prob',NaN, ...
        'mean_inf_carry_prob_gain',NaN, ...
        'pos_rate_inf_carry_prob_gain',NaN);
end

function Names = coreMetricColumns()
    Names = { ...
        'generation','fe','fe_ratio', ...
        'b_pair_count','b_mean_pair_gap','b_p90_pair_gap','b_mean_front_gap','b_p90_front_gap', ...
        'b_active_sector_ratio','b_changed_pair_count','b_changed_pair_ratio', ...
        'b_added_pair_count','b_replaced_pair_count','b_dropped_pair_count','b_contracted_pair_count', ...
        'b_global_change_pair_ratio','b_contraction_pair_ratio', ...
        'b_mean_mid_boundary_dist','b_p90_mid_boundary_dist', ...
        'b_mean_infeasible_boundary_dist','b_p90_infeasible_boundary_dist', ...
        'b_max_infeasible_boundary_dist','b_far_infeasible_boundary_ratio', ...
        'b_overlap_popc_count','b_overlap_popc_ratio','b_overlap_popu_count','b_overlap_popu_ratio', ...
        'b_overlap_any_population_ratio', ...
        'b_src_b','b_src_popc','b_src_popu','b_src_offc','b_src_offu','b_src_refinement', ...
        'b_inf_src_b','b_inf_src_popc','b_inf_src_popu','b_inf_src_offc','b_inf_src_offu','b_inf_src_refinement', ...
        'b_inf_unconstrained_src_ratio', ...
        'mlp_due','mlp_can_train','mlp_trained','mlp_acc_before','mlp_train_acc','mlp_degraded', ...
        'train_size','train_pos','train_neg', ...
        'train_src_b','train_src_refinement','train_src_boundary_band', ...
        'inf_pool_size','inf_selected','inf_pool_mean_prob','inf_selected_mean_prob','inf_prob_gain', ...
        'inf_carry_pool_size','inf_carry_applicable_count', ...
        'inf_carry_selected','inf_carry_pool_mean_prob','inf_carry_selected_mean_prob','inf_carry_prob_gain'};
end

function requireColumns(T,Names,filePath)
    Missing = setdiff(string(Names),string(T.Properties.VariableNames));
    assert(isempty(Missing), ...
        'summarize_PRBCCMO_t_run:MissingColumns', ...
        'Missing columns in %s: %s', filePath, strjoin(cellstr(Missing), ', '));
end

function value = scalarValue(T,Name)
    value = double(T.(Name)(1));
end

function value = lastFinite(values)
    values = finiteValues(values);
    if isempty(values)
        value = NaN;
    else
        value = values(end);
    end
end

function value = meanFinite(values)
    values = finiteValues(values);
    if isempty(values)
        value = NaN;
    else
        value = mean(values);
    end
end

function value = percentileFinite(values,p)
    values = sort(finiteValues(values));
    if isempty(values)
        value = NaN;
    else
        idx = max(1,min(numel(values),ceil(p/100*numel(values))));
        value = values(idx);
    end
end

function value = sumFinite(values)
    values = finiteValues(values);
    if isempty(values)
        value = 0;
    else
        value = sum(values);
    end
end

function rate = positiveRate(values)
    values = finiteValues(values);
    if isempty(values)
        rate = NaN;
    else
        rate = mean(values > 0);
    end
end

function values = finiteValues(values)
    values = double(values);
    values = values(isfinite(values));
end

function value = metaString(Meta,Name,Default)
    if hasColumns(Meta,{Name}) && height(Meta) > 0
        value = string(Meta.(Name)(1));
    else
        value = string(Default);
    end
end

function value = metaDouble(Meta,Name,Default)
    value = Default;
    if hasColumns(Meta,{Name}) && height(Meta) > 0
        raw = Meta.(Name);
        parsed = str2double(string(raw(1)));
        if ~isnan(parsed)
            value = parsed;
        elseif isnumeric(raw)
            value = double(raw(1));
        end
    end
end

function Flag = hasColumns(T,Names)
    Flag = all(ismember(string(Names),string(T.Properties.VariableNames)));
end

function T = numericizeTable(T)
    Names = T.Properties.VariableNames;
    for i = 1 : numel(Names)
        Value = T.(Names{i});
        if iscell(Value) || isstring(Value)
            Num = str2double(string(Value));
            if any(~isnan(Num))
                T.(Names{i}) = Num;
            end
        elseif islogical(Value)
            T.(Names{i}) = double(Value);
        end
    end
end
