function [RunTable,ProblemTable,FamilyTable] = summarize_PRBCCMO_t_data(inputPath,outDir)
% Aggregate PRBCCMO_t runs using only the three core observations.

    if nargin < 1 || isempty(inputPath)
        rootDir = fileparts(which('platemo'));
        inputPath = fullfile(rootDir,'Data','PRBCCMO_t');
    end
    if nargin < 2 || isempty(outDir)
        outDir = inputPath;
    end
    if ~isfolder(outDir)
        mkdir(outDir);
    end

    runFolders = resolveRunFolders(inputPath);
    Summaries = cellfun(@summarize_PRBCCMO_t_run,runFolders,'UniformOutput',false);
    RunTable = struct2table([Summaries{:}]');
    writetable(RunTable,fullfile(outDir,'run_summary.csv'));

    ProblemTable = aggregateRunTable(RunTable,"problem");
    writetable(ProblemTable,fullfile(outDir,'problem_summary.csv'));

    FamilyTable = aggregateRunTable(RunTable,"family");
    writetable(FamilyTable,fullfile(outDir,'family_summary.csv'));
end

function runFolders = resolveRunFolders(inputPath)
    if ischar(inputPath) || (isstring(inputPath) && isscalar(inputPath))
        folder = char(string(inputPath));
        if isfolder(folder) && isfile(fullfile(folder,'core_metrics.csv'))
            runFolders = {folder};
            return;
        end
        assert(isfolder(folder), ...
            'summarize_PRBCCMO_t_data:MissingInputFolder', ...
            'Input path not found: %s', folder);
        dirs = dir(folder);
        dirs = dirs([dirs.isdir]);
        dirs = dirs(~ismember({dirs.name},{'.','..'}));
        candidates = fullfile({dirs.folder},{dirs.name});
        keep = cellfun(@(p)isfile(fullfile(p,'core_metrics.csv')),candidates);
        runFolders = reshape(candidates(keep),[],1);
    else
        folders = cellstr(string(inputPath(:)));
        keep = cellfun(@(p)isfolder(p) && isfile(fullfile(p,'core_metrics.csv')),folders);
        runFolders = folders(keep);
    end

    assert(~isempty(runFolders), ...
        'summarize_PRBCCMO_t_data:NoRunFolders', ...
        'No PRBCCMO_t core_metrics.csv run folders were found.');
end

function SummaryTable = aggregateRunTable(RunTable,groupField)
    Keys = unique(string(RunTable.(groupField)),'stable');
    MetricNames = aggregateMetricNames();
    Names = [cellstr(groupField),{'num_runs'},composeMetricColumns(MetricNames)];
    Types = [{'string'},repmat({'double'},1,numel(Names)-1)];
    SummaryTable = table('Size',[numel(Keys),numel(Names)], ...
        'VariableTypes',Types,'VariableNames',Names);

    for i = 1 : numel(Keys)
        Mask = string(RunTable.(groupField)) == Keys(i);
        SummaryTable.(char(groupField))(i) = Keys(i);
        SummaryTable.num_runs(i) = sum(Mask);
        col = 3;
        for m = 1 : numel(MetricNames)
            Values = RunTable.(MetricNames{m})(Mask);
            SummaryTable{i,col} = meanFinite(Values);
            SummaryTable{i,col+1} = stdFinite(Values);
            col = col + 2;
        end
    end
end

function Names = aggregateMetricNames()
    Names = { ...
        'final_b_mean_pair_gap', ...
        'mean_b_mean_pair_gap', ...
        'p90_b_mean_pair_gap', ...
        'final_b_p90_pair_gap', ...
        'final_b_mean_front_gap', ...
        'mean_b_mean_front_gap', ...
        'final_b_mean_infeasible_boundary_dist', ...
        'mean_b_mean_infeasible_boundary_dist', ...
        'final_b_p90_infeasible_boundary_dist', ...
        'final_b_max_infeasible_boundary_dist', ...
        'final_b_far_infeasible_boundary_ratio', ...
        'mean_b_far_infeasible_boundary_ratio', ...
        'final_b_inf_unconstrained_src_ratio', ...
        'mean_b_inf_unconstrained_src_ratio', ...
        'final_b_overlap_popc_ratio', ...
        'mean_b_overlap_popc_ratio', ...
        'final_b_overlap_popu_ratio', ...
        'mean_b_overlap_popu_ratio', ...
        'final_b_inf_src_popu', ...
        'final_b_inf_src_offu', ...
        'final_b_inf_src_refinement', ...
        'final_b_active_sector_ratio', ...
        'mean_b_active_sector_ratio', ...
        'mean_b_changed_pair_count', ...
        'mean_b_changed_pair_ratio', ...
        'mean_b_added_pair_count', ...
        'mean_b_replaced_pair_count', ...
        'mean_b_dropped_pair_count', ...
        'mean_b_contracted_pair_count', ...
        'mean_b_global_change_pair_ratio', ...
        'mean_b_contraction_pair_ratio', ...
        'mlp_due_events', ...
        'mlp_can_train_events', ...
        'mlp_trained_events', ...
        'mlp_degraded_events', ...
        'final_mlp_train_acc', ...
        'mean_mlp_train_acc', ...
        'final_train_size', ...
        'mean_train_size', ...
        'final_train_pos', ...
        'final_train_neg', ...
        'final_train_src_b', ...
        'final_train_src_refinement', ...
        'final_train_src_boundary_band', ...
        'inf_selection_generations', ...
        'inf_selected_total', ...
        'mean_inf_pool_mean_prob', ...
        'mean_inf_selected_mean_prob', ...
        'mean_inf_prob_gain', ...
        'pos_rate_inf_prob_gain', ...
        'inf_carry_generations', ...
        'inf_carry_selected_total', ...
        'mean_inf_carry_pool_mean_prob', ...
        'mean_inf_carry_selected_mean_prob', ...
        'mean_inf_carry_prob_gain', ...
        'pos_rate_inf_carry_prob_gain'};
end

function Columns = composeMetricColumns(MetricNames)
    Columns = cell(1,2*numel(MetricNames));
    Columns(1:2:end) = strcat('mean_',MetricNames);
    Columns(2:2:end) = strcat('std_',MetricNames);
end

function value = meanFinite(values)
    values = finiteValues(values);
    if isempty(values)
        value = NaN;
    else
        value = mean(values);
    end
end

function value = stdFinite(values)
    values = finiteValues(values);
    if numel(values) < 2
        value = NaN;
    else
        value = std(values,0);
    end
end

function values = finiteValues(values)
    values = double(values);
    values = values(isfinite(values));
end
