function test_PRBCCMO_semantics()
% Static guard for the PRBCCMO-v2 objective-boundary contract.

    rootDir = fileparts(mfilename('fullpath'));
    mainText = normalizeCode(fileread(fullfile(rootDir,'PRBCCMO.m')));
    traceText = normalizeCode(fileread(fullfile(rootDir,'PRBCCMO_t.m')));
    coreText = normalizeCode(fileread(fullfile(rootDir,'PRBCCMO_objective_core.m')));

    requireContains(mainText, ...
        '[Params{:}]=Algorithm.ParameterSet(40,80,0.05,4,0.1,20,150);', ...
        'test_PRBCCMO_semantics:MainParameters', ...
        'PRBCCMO must default to the selected IGD-tuned parameter set.');
    requireContains(traceText, ...
        '[Params{:}]=Algorithm.ParameterSet(40,80,0.05,4,0.1,20,150,0);', ...
        'test_PRBCCMO_semantics:TraceParameters', ...
        'PRBCCMO_t must default to the selected IGD-tuned parameter set.');
    requireContains(traceText,'Algorithm.metric.analysis_core_csv=Observer.core_file;', ...
        'test_PRBCCMO_semantics:AnalysisCoreCsv', ...
        'PRBCCMO_t must expose core_metrics.csv.');
    requireContains(coreText,'''core_file'',fullfile(RunFolder,''core_metrics.csv'')', ...
        'test_PRBCCMO_semantics:CoreFile', ...
        'The observer must use core_metrics.csv.');

    Fields = coreMetricColumns();
    for i = 1 : numel(Fields)
        requireContains(coreText,['''',Fields{i},''''], ...
            ['test_PRBCCMO_semantics:CoreField_',Fields{i}], ...
            ['core_metrics.csv is missing required field ',Fields{i},'.']);
    end
    requireContains(coreText,'[BatchDec,RefineInfo]=InjectBoundaryRefinementIntoHelperOffspring', ...
        'test_PRBCCMO_semantics:RefineInfoReturned', ...
        'Helper refinement must return RefineInfo for same-pair contraction.');
    requireContains(coreText,'Kbis=3;', ...
        'test_PRBCCMO_semantics:FixedKbis', ...
        'Boundary refinement must use internal Kbis=3.');
    requireContains(coreText,'ContractBoundaryPairsByRefinedSamples', ...
        'test_PRBCCMO_semantics:SamePairContraction', ...
        'Refined samples must attempt strict bracket same-pair contraction.');
    requireContains(coreText,'IsBracketTighter', ...
        'test_PRBCCMO_semantics:BracketTighterGate', ...
        'Same-pair contraction must accept only tighter brackets.');
    requireContains(coreText,'BuildTrainingBufferT', ...
        'test_PRBCCMO_semantics:TrainingBufferT', ...
        'MLP training must use T = B + recent refinement + small real boundary-band.');
    requireContains(coreText,'BalanceTrainingDataset', ...
        'test_PRBCCMO_semantics:BalancedTraining', ...
        'MLP training must use 1:1 feasible/infeasible balanced batches.');
    requireContains(coreText,'Key=[Meta.frontGap(idx),-Meta.prob(idx),Meta.supportDistObjToB(idx),idx];', ...
        'test_PRBCCMO_semantics:UnifiedInfeasibleKey', ...
        'Infeasible selection must use [FrontGap, -prob, DistToB, index].');
    requireContains(coreText,'Carry=min(max(1,round(0.01*N)),numel(Infeasible));', ...
        'test_PRBCCMO_semantics:CarrySlot', ...
        'Model-ready selection must reserve a one-percent infeasible carry slot.');
    requireNotContains(coreText,'ModelDegraded=IsBoundaryModelDegradedForCarry(MLPDiag);', ...
        'test_PRBCCMO_semantics:NoCarryDegradationCheck', ...
        'Carry gate must not be hard-disabled by training accuracy degradation.');
    requireNotContains(coreText,'NeedGeometry', ...
        'test_PRBCCMO_semantics:NoNeedGeometrySwitch', ...
        'Boundary geometry must be computed for infeasible selection even when the model is ready.');
    requireNotContains(coreText,'BuildDatasetFromBoundaryArchive', ...
        'test_PRBCCMO_semantics:NoBOnlyDatasetBuilder', ...
        'MLP training must no longer be pure B-only.');
    requireNotContains(coreText,'CarryPick=Population([]);', ...
        'test_PRBCCMO_semantics:NoUnusedCarryPickInit', ...
        'Carry selection must not keep an unused CarryPick initialization.');
    requireNotContains(coreText,'ifnumel(Feasible)>=NPopulation=ObjectiveSelectionWithLastSectorTruncation(Feasible,N,W);return;', ...
        'test_PRBCCMO_semantics:NoFeasibleEarlyReturn', ...
        'Feasible>=N must not bypass the model-ready carry slot.');
    requireNoForbiddenCoreFields(coreText);
    requireNoPairwiseRankLoss(coreText);
end

function Fields = coreMetricColumns()
    Fields = { ...
        'generation','fe','fe_ratio', ...
        'b_pair_count','b_mean_pair_gap','b_p90_pair_gap','b_mean_front_gap','b_p90_front_gap', ...
        'b_active_sector_ratio','b_changed_pair_count','b_changed_pair_ratio', ...
        'b_added_pair_count','b_replaced_pair_count','b_dropped_pair_count','b_contracted_pair_count', ...
        'b_global_change_pair_ratio','b_contraction_pair_ratio', ...
        'b_mean_mid_boundary_dist','b_p90_mid_boundary_dist', ...
        'b_mean_infeasible_boundary_dist','b_p90_infeasible_boundary_dist', ...
        'b_max_infeasible_boundary_dist','b_far_infeasible_boundary_ratio', ...
        'b_overlap_popc_count','b_overlap_popc_ratio','b_overlap_popu_count','b_overlap_popu_ratio', ...
        'b_overlap_any_population_ratio', ...
        'b_src_b','b_src_popc','b_src_popu','b_src_offc','b_src_offu','b_src_refinement', ...
        'b_inf_src_b','b_inf_src_popc','b_inf_src_popu','b_inf_src_offc','b_inf_src_offu','b_inf_src_refinement', ...
        'b_inf_unconstrained_src_ratio', ...
        'mlp_due','mlp_can_train','mlp_trained','mlp_acc_before','mlp_train_acc','mlp_degraded', ...
        'train_size','train_pos','train_neg', ...
        'train_src_b','train_src_refinement','train_src_boundary_band', ...
        'inf_pool_size','inf_selected','inf_pool_mean_prob','inf_selected_mean_prob','inf_prob_gain', ...
        'inf_carry_pool_size','inf_carry_applicable_count', ...
        'inf_carry_selected','inf_carry_pool_mean_prob','inf_carry_selected_mean_prob','inf_carry_prob_gain'};
end

function requireNoForbiddenCoreFields(coreText)
    Forbidden = { ...
        'b_size','b_sector_coverage','b_mean_age', ...
        'train_brier_after','train_logloss_after', ...
        'inf_supportdistobj_gain','inf_frontgap_gain','inf_selected_sector_coverage'};
    for i = 1 : numel(Forbidden)
        requireNotContains(coreText,Forbidden{i}, ...
            ['test_PRBCCMO_semantics:NoCore_',Forbidden{i}], ...
            ['core_metrics.csv must not expose non-core field ',Forbidden{i},'.']);
    end
end

function requireNoPairwiseRankLoss(coreText)
    lowerText = lower(coreText);
    Forbidden = {'pairwise','rank_lambda','rankloss','rank_loss','rankingloss','ranking_loss'};
    for i = 1 : numel(Forbidden)
        requireNotContains(lowerText,Forbidden{i}, ...
            ['test_PRBCCMO_semantics:No_',Forbidden{i}], ...
            ['MLP code must not depend on pairwise/rank-loss text: ',Forbidden{i}]);
    end
end

function requireContains(text,pattern,id,message)
    assert(contains(text,normalizeCode(pattern)),id,message);
end

function requireNotContains(text,pattern,id,message)
    assert(~contains(text,normalizeCode(pattern)),id,message);
end

function text = normalizeCode(text)
    text = lower(regexprep(text,'\s+',''));
end
