function test_PRBCCMO_t_metrics()
% Contract test for minimal PRBCCMO_t core metrics.

    rootDir = fileparts(mfilename('fullpath'));
    repoDir = fileparts(fileparts(fileparts(rootDir)));
    addpath(genpath(repoDir));

    traceText = normalizeCode(fileread(fullfile(rootDir,'PRBCCMO_t.m')));
    coreText = normalizeCode(fileread(fullfile(rootDir,'PRBCCMO_objective_core.m')));
    benchText = normalizeCode(fileread(fullfile(rootDir,'benchmark_PRBCCMO_t_suite.m')));

    requireContains(traceText,'Algorithm.metric.analysis_core_csv=Observer.core_file;', ...
        'test_PRBCCMO_t_metrics:CoreCsvExposed', ...
        'PRBCCMO_t must expose analysis_core_csv.');
    requireContains(benchText,'N=100;', ...
        'test_PRBCCMO_t_metrics:DefaultN', ...
        'Benchmark default N must remain 100.');
    requireContains(benchText,'maxFE=200000;', ...
        'test_PRBCCMO_t_metrics:DefaultFE', ...
        'Benchmark default maxFE must remain 200000.');
    requireContains(traceText,'Algorithm.ParameterSet(40,80,0.05,4,0.1,20,150,0)', ...
        'test_PRBCCMO_t_metrics:DefaultTunedParameters', ...
        'PRBCCMO_t must default to the selected IGD-tuned parameter set.');

    Fields = coreMetricColumns();
    requireContains(coreText,'core_metrics.csv', ...
        'test_PRBCCMO_t_metrics:CoreMetricsCsv', ...
        'The trace file must be core_metrics.csv.');
    for i = 1 : numel(Fields)
        requireContains(coreText,['''',Fields{i},''''], ...
            ['test_PRBCCMO_t_metrics:CoreField_',Fields{i}], ...
            ['core_metrics.csv must expose ',Fields{i},'.']);
    end
    requireNoForbiddenCoreFields(coreText);
    requireNoPairwiseRankLoss(coreText);

    runFolder = createSyntheticRun();
    Core = readtable(fullfile(runFolder,'core_metrics.csv'),'TextType','string');
    requireColumns(Core,Fields);

    RunSummary = summarize_PRBCCMO_t_run(runFolder);
    requireStructFields(RunSummary,{ ...
        'problem','family','run','analysis_folder','analysis_core_csv', ...
        'final_b_mean_pair_gap','mean_b_mean_pair_gap','p90_b_mean_pair_gap','final_b_p90_pair_gap', ...
        'final_b_mean_infeasible_boundary_dist','mean_b_mean_infeasible_boundary_dist', ...
        'final_b_far_infeasible_boundary_ratio','mean_b_far_infeasible_boundary_ratio', ...
        'final_b_inf_unconstrained_src_ratio','mean_b_inf_unconstrained_src_ratio', ...
        'final_b_overlap_popc_ratio','mean_b_overlap_popc_ratio', ...
        'final_b_overlap_popu_ratio','mean_b_overlap_popu_ratio', ...
        'final_b_active_sector_ratio','mean_b_active_sector_ratio', ...
        'mean_b_changed_pair_count','mean_b_changed_pair_ratio', ...
        'mean_b_replaced_pair_count','mean_b_contracted_pair_count', ...
        'mean_b_global_change_pair_ratio','mean_b_contraction_pair_ratio', ...
        'mlp_due_events','mlp_can_train_events', ...
        'mlp_trained_events','final_mlp_train_acc','mean_mlp_train_acc', ...
        'mlp_degraded_events', ...
        'final_train_size','mean_train_size', ...
        'final_train_pos','final_train_neg', ...
        'final_train_src_b','final_train_src_refinement','final_train_src_boundary_band', ...
        'mean_inf_pool_mean_prob','mean_inf_selected_mean_prob', ...
        'inf_selection_generations','inf_selected_total','mean_inf_prob_gain','pos_rate_inf_prob_gain', ...
        'inf_carry_generations','inf_carry_selected_total', ...
        'mean_inf_carry_pool_mean_prob','mean_inf_carry_selected_mean_prob', ...
        'mean_inf_carry_prob_gain','pos_rate_inf_carry_prob_gain'});
    assert(RunSummary.mlp_trained_events == 2, ...
        'test_PRBCCMO_t_metrics:TrainedEventCount', ...
        'Synthetic core trace must report two trained MLP events.');
    assert(abs(RunSummary.final_mlp_train_acc - 0.86) < 1e-12, ...
        'test_PRBCCMO_t_metrics:FinalTrainAccuracy', ...
        'Final MLP accuracy must use the latest trained event.');
    assert(RunSummary.final_train_size == 40 && RunSummary.final_train_pos == 20 && ...
            RunSummary.final_train_neg == 20, ...
        'test_PRBCCMO_t_metrics:FinalTrainingBufferCounts', ...
        'Summary must expose final T buffer size and balanced labels.');
    assert(RunSummary.final_train_src_b == 10 && ...
            RunSummary.final_train_src_refinement == 24 && ...
            RunSummary.final_train_src_boundary_band == 6, ...
        'test_PRBCCMO_t_metrics:FinalTrainingSources', ...
        'Summary must expose final T source composition.');
    assert(abs(RunSummary.mean_inf_prob_gain - mean([0.02 -0.01 0.03])) < 1e-12, ...
        'test_PRBCCMO_t_metrics:MeanInfGain', ...
        'Infeasible probability gain mean must ignore NaN and average finite rows.');
    assert(RunSummary.inf_carry_selected_total == 2, ...
        'test_PRBCCMO_t_metrics:CarrySelectedTotal', ...
        'Carry summary must count only model-ready carry selections.');
    assert(abs(RunSummary.mean_inf_carry_prob_gain - mean([0.05 0.01])) < 1e-12, ...
        'test_PRBCCMO_t_metrics:MeanCarryGain', ...
        'Carry probability gain mean must ignore non-carry rows.');

    outDir = fullfile(tempdir,'prbccmo_t_core_metrics_test');
    if ~isfolder(outDir)
        mkdir(outDir);
    end
    [RunTable,ProblemTable,FamilyTable] = summarize_PRBCCMO_t_data(runFolder,outDir);
    assert(height(RunTable) == 1 && height(ProblemTable) == 1 && height(FamilyTable) == 1, ...
        'test_PRBCCMO_t_metrics:SummaryTableShape', ...
        'Core summary helpers must produce run/problem/family tables.');
    requireColumns(ProblemTable,{ ...
        'mean_final_b_mean_pair_gap','mean_mean_b_active_sector_ratio','mean_mlp_trained_events', ...
        'mean_final_b_mean_infeasible_boundary_dist','mean_final_b_inf_unconstrained_src_ratio', ...
        'mean_final_train_size','mean_final_train_src_refinement', ...
        'mean_mean_inf_selected_mean_prob','mean_mean_inf_prob_gain','mean_pos_rate_inf_prob_gain', ...
        'mean_inf_carry_selected_total','mean_mean_inf_carry_prob_gain'});

    traceListFile = fullfile(outDir,'trace_list.txt');
    fid = fopen(traceListFile,'w');
    cleaner = onCleanup(@()fclose(fid));
    fprintf(fid,'%s\n',runFolder);
    clear cleaner;
    [CompletedRuns,CompletedProblems,CompletedFamilies] = ...
        analyze_PRBCCMO_t_completed_traces(traceListFile,outDir);
    assert(height(CompletedRuns) == 1 && height(CompletedProblems) == 1 && height(CompletedFamilies) == 1, ...
        'test_PRBCCMO_t_metrics:CompletedTraceSummary', ...
        'Completed trace analysis must summarize listed core trace folders.');

    assertExternalResultIsFeasibleOnly();
end

function runFolder = createSyntheticRun()
    [~,token] = fileparts(tempname);
    runFolder = fullfile(tempdir,['prbccmo_t_core_contract_',token]);
    mkdir(runFolder);

    Meta = table( ...
        "PRBCCMO_t","DASCMOP1_BC","DASCMOP_BC",1,2,30,40,800, ...
        40,80,0.05,4,0.1,20,150,string(runFolder), ...
        'VariableNames',{ ...
        'algorithm','problem','family','run','M','D','N','maxFE', ...
        'hidden','epoch','lr','betaB','etaB','Tretrain','Gstart','output_folder'});
    writetable(Meta,fullfile(runFolder,'run_meta.csv'));

    Core = table();
    Core.generation = (1:4)';
    Core.fe = [100; 200; 300; 400];
    Core.fe_ratio = Core.fe ./ 800;
    Core.b_pair_count = [2; 3; 4; 5];
    Core.b_mean_pair_gap = [0.40; 0.32; 0.25; 0.20];
    Core.b_p90_pair_gap = [0.70; 0.55; 0.42; 0.31];
    Core.b_mean_front_gap = [0.12; 0.10; 0.08; 0.07];
    Core.b_p90_front_gap = [0.20; 0.16; 0.12; 0.10];
    Core.b_active_sector_ratio = [0.20; 0.30; 0.35; 0.40];
    Core.b_changed_pair_count = [2; 1; 1; 0];
    Core.b_changed_pair_ratio = [0.20; 0.10; 0.10; 0.00];
    Core.b_added_pair_count = [2; 0; 0; 0];
    Core.b_replaced_pair_count = [0; 1; 0; 0];
    Core.b_dropped_pair_count = [0; 1; 0; 0];
    Core.b_contracted_pair_count = [0; 0; 1; 0];
    Core.b_global_change_pair_ratio = [1.00; 0.33; 0.00; 0.00];
    Core.b_contraction_pair_ratio = [0.00; 0.00; 0.25; 0.00];
    Core.b_mean_mid_boundary_dist = [0.30; 0.20; 0.16; 0.12];
    Core.b_p90_mid_boundary_dist = [0.40; 0.32; 0.25; 0.18];
    Core.b_mean_infeasible_boundary_dist = [0.42; 0.28; 0.20; 0.14];
    Core.b_p90_infeasible_boundary_dist = [0.50; 0.36; 0.26; 0.18];
    Core.b_max_infeasible_boundary_dist = [0.60; 0.45; 0.34; 0.21];
    Core.b_far_infeasible_boundary_ratio = [0.50; 0.33; 0.25; 0.20];
    Core.b_overlap_popc_count = [2; 2; 2; 2];
    Core.b_overlap_popc_ratio = [0.50; 0.33; 0.25; 0.20];
    Core.b_overlap_popu_count = [1; 2; 3; 3];
    Core.b_overlap_popu_ratio = [0.25; 0.33; 0.38; 0.30];
    Core.b_overlap_any_population_ratio = [0.75; 0.67; 0.63; 0.50];
    Core.b_src_b = [4; 3; 2; 1];
    Core.b_src_popc = [0; 1; 1; 1];
    Core.b_src_popu = [0; 1; 2; 3];
    Core.b_src_offc = [0; 0; 1; 1];
    Core.b_src_offu = [0; 1; 1; 2];
    Core.b_src_refinement = [0; 0; 1; 2];
    Core.b_inf_src_b = [2; 1; 1; 0];
    Core.b_inf_src_popc = [0; 0; 0; 0];
    Core.b_inf_src_popu = [0; 1; 2; 2];
    Core.b_inf_src_offc = [0; 0; 0; 0];
    Core.b_inf_src_offu = [0; 1; 1; 2];
    Core.b_inf_src_refinement = [0; 0; 0; 1];
    Core.b_inf_unconstrained_src_ratio = [0.00; 0.67; 0.75; 0.80];
    Core.mlp_due = [0; 1; 0; 1];
    Core.mlp_can_train = [0; 1; 0; 1];
    Core.mlp_trained = [0; 1; 0; 1];
    Core.mlp_acc_before = [NaN; NaN; 0.75; 0.78];
    Core.mlp_train_acc = [NaN; 0.75; NaN; 0.86];
    Core.mlp_degraded = [0; 0; 0; 0];
    Core.train_size = [20; 30; 36; 40];
    Core.train_pos = [10; 15; 18; 20];
    Core.train_neg = [10; 15; 18; 20];
    Core.train_src_b = [20; 12; 12; 10];
    Core.train_src_refinement = [0; 14; 20; 24];
    Core.train_src_boundary_band = [0; 4; 4; 6];
    Core.inf_pool_size = [0; 20; 20; 20];
    Core.inf_selected = [0; 5; 4; 6];
    Core.inf_pool_mean_prob = [NaN; 0.50; 0.52; 0.54];
    Core.inf_selected_mean_prob = [NaN; 0.52; 0.51; 0.57];
    Core.inf_prob_gain = [NaN; 0.02; -0.01; 0.03];
    Core.inf_carry_pool_size = [0; 20; 20; 20];
    Core.inf_carry_applicable_count = [0; 18; 0; 15];
    Core.inf_carry_selected = [0; 1; 0; 1];
    Core.inf_carry_pool_mean_prob = [NaN; 0.51; NaN; 0.53];
    Core.inf_carry_selected_mean_prob = [NaN; 0.56; NaN; 0.54];
    Core.inf_carry_prob_gain = [NaN; 0.05; NaN; 0.01];
    Core = Core(:,coreMetricColumns());
    writetable(Core,fullfile(runFolder,'core_metrics.csv'));
end

function Fields = coreMetricColumns()
    Fields = { ...
        'generation','fe','fe_ratio', ...
        'b_pair_count','b_mean_pair_gap','b_p90_pair_gap','b_mean_front_gap','b_p90_front_gap', ...
        'b_active_sector_ratio','b_changed_pair_count','b_changed_pair_ratio', ...
        'b_added_pair_count','b_replaced_pair_count','b_dropped_pair_count','b_contracted_pair_count', ...
        'b_global_change_pair_ratio','b_contraction_pair_ratio', ...
        'b_mean_mid_boundary_dist','b_p90_mid_boundary_dist', ...
        'b_mean_infeasible_boundary_dist','b_p90_infeasible_boundary_dist', ...
        'b_max_infeasible_boundary_dist','b_far_infeasible_boundary_ratio', ...
        'b_overlap_popc_count','b_overlap_popc_ratio','b_overlap_popu_count','b_overlap_popu_ratio', ...
        'b_overlap_any_population_ratio', ...
        'b_src_b','b_src_popc','b_src_popu','b_src_offc','b_src_offu','b_src_refinement', ...
        'b_inf_src_b','b_inf_src_popc','b_inf_src_popu','b_inf_src_offc','b_inf_src_offu','b_inf_src_refinement', ...
        'b_inf_unconstrained_src_ratio', ...
        'mlp_due','mlp_can_train','mlp_trained','mlp_acc_before','mlp_train_acc','mlp_degraded', ...
        'train_size','train_pos','train_neg', ...
        'train_src_b','train_src_refinement','train_src_boundary_band', ...
        'inf_pool_size','inf_selected','inf_pool_mean_prob','inf_selected_mean_prob','inf_prob_gain', ...
        'inf_carry_pool_size','inf_carry_applicable_count', ...
        'inf_carry_selected','inf_carry_pool_mean_prob','inf_carry_selected_mean_prob','inf_carry_prob_gain'};
end

function requireNoForbiddenCoreFields(coreText)
    Forbidden = { ...
        'b_size','b_sector_coverage','b_mean_age', ...
        'train_brier_after','train_logloss_after', ...
        'inf_supportdistobj_gain','inf_frontgap_gain','inf_selected_sector_coverage'};
    for i = 1 : numel(Forbidden)
        requireNotContains(coreText,Forbidden{i}, ...
            ['test_PRBCCMO_t_metrics:NoCore_',Forbidden{i}], ...
            ['core_metrics.csv must not expose non-core field ',Forbidden{i},'.']);
    end
end

function requireNoPairwiseRankLoss(coreText)
    Forbidden = {'pairwise','rank_lambda','rankloss','rank_loss','rankingloss','ranking_loss'};
    for i = 1 : numel(Forbidden)
        requireNotContains(coreText,Forbidden{i}, ...
            ['test_PRBCCMO_t_metrics:No_',Forbidden{i}], ...
            ['MLP core text must not depend on ',Forbidden{i},'.']);
    end
end

function requireContains(text,pattern,id,message)
    assert(contains(text,normalizeCode(pattern)),id,message);
end

function requireNotContains(text,pattern,id,message)
    assert(~contains(text,normalizeCode(pattern)),id,message);
end

function requireColumns(T,Names)
    Missing = setdiff(string(Names),string(T.Properties.VariableNames));
    assert(isempty(Missing), ...
        'test_PRBCCMO_t_metrics:MissingColumns', ...
        'Missing columns: %s', strjoin(cellstr(Missing), ', '));
end

function requireStructFields(S,Names)
    Missing = setdiff(string(Names),string(fieldnames(S)));
    assert(isempty(Missing), ...
        'test_PRBCCMO_t_metrics:MissingStructFields', ...
        'Missing summary fields: %s', strjoin(cellstr(Missing), ', '));
end

function assertExternalResultIsFeasibleOnly()
    rng(1,'twister');
    Algorithm = PRBCCMO_t( ...
        'save',0, ...
        'run',1, ...
        'outputFcn',@(varargin)[], ...
        'parameter',{40,80,0.05,4,0.1,20,150,0});
    Problem = DASCMOP1_BC('N',20,'maxFE',200);
    Algorithm.Solve(Problem);
    ResultPopulation = Algorithm.result{end,2};
    assert(~isempty(ResultPopulation), ...
        'test_PRBCCMO_t_metrics:ExternalResultEmpty', ...
        'External PRBCCMO_t result must contain feasible display solutions for this smoke case.');
    assert(all(all(ResultPopulation.cons <= 0,2)), ...
        'test_PRBCCMO_t_metrics:ExternalResultFeasibleOnly', ...
        'Algorithm.result must not expose internal infeasible carry points.');
end

function text = normalizeCode(text)
    text = lower(regexprep(text,'\s+',''));
end
