function test_PRBCCMO_t_metrics()
% Regression test for traced PRBCCMO_t boundary-band metrics and summaries.

    rootDir = fileparts(mfilename('fullpath'));
    repoDir = fileparts(fileparts(fileparts(rootDir)));
    addpath(genpath(repoDir));

    traceText = normalizeCode(fileread(fullfile(rootDir,'PRBCCMO_t.m')));
    requireContains(traceText, ...
        'Dataset.Source=Buffer.Source(Ranked);', ...
        'test_PRBCCMO_t_metrics:DatasetSourceTags', ...
        'PRBCCMO_t must preserve exact source tags in the boundary-band dataset.');
    requireContains(traceText, ...
        'Diag.src_b=sum(Dataset.Source==1);', ...
        'test_PRBCCMO_t_metrics:ExactSrcB', ...
        'src_b must be counted from dataset source tags.');
    requireContains(traceText, ...
        'Diag.src_recent_boundary=sum(Dataset.Source==2);', ...
        'test_PRBCCMO_t_metrics:ExactSrcRecent', ...
        'src_recent_boundary must be counted from dataset source tags.');
    requireContains(traceText, ...
        'Diag.src_pop_c=sum(Dataset.Source==3);', ...
        'test_PRBCCMO_t_metrics:ExactSrcPopC', ...
        'src_pop_c must be counted from dataset source tags.');
    requireContains(traceText, ...
        'Diag.src_pop_u=sum(Dataset.Source==4);', ...
        'test_PRBCCMO_t_metrics:ExactSrcPopU', ...
        'src_pop_u must be counted from dataset source tags.');
    requireContains(traceText, ...
        'Diag.mean_opp_dist=MeanOrNaN(Dataset.OppDist);', ...
        'test_PRBCCMO_t_metrics:BoundaryBandDistanceMetric', ...
        'Training distance diagnostics must summarize boundary-band opposite distances.');
    requireContains(traceText, ...
        'Stats.margin_oppdist_corr=SafeCorr(Meta.margin,OppDist);', ...
        'test_PRBCCMO_t_metrics:BoundaryFitCorrelation', ...
        'Traced metrics must record whether MLP margin tracks opposite-side boundary distance.');
    requireContains(traceText, ...
        'Diag.lowmargin_ratio_gain=Diag.selected_lowmargin_ratio-Diag.pool_lowmargin_ratio;', ...
        'test_PRBCCMO_t_metrics:InfeasibleLowMarginGain', ...
        'Infeasible selection diagnostics must compare selected low-margin ratio against the pool.');
    requireContains(traceText, ...
        'OppDist=SupportDistance(CandidateMeta.oppSupport(idx));', ...
        'test_PRBCCMO_t_metrics:BoundaryEventOppDist', ...
        'Boundary event rows must log opposite-side support distance for generated offspring.');
    requireContains(traceText, ...
        'objective_snapshot.csv', ...
        'test_PRBCCMO_t_metrics:ObjectiveSnapshotCsv', ...
        'PRBCCMO_t must emit objective-space snapshots for visual innovation evidence.');
    requireContains(traceText, ...
        'Algorithm.metric.analysis_objective_csv', ...
        'test_PRBCCMO_t_metrics:ObjectiveMetricPath', ...
        'PRBCCMO_t must expose the objective snapshot CSV path in Algorithm.metric.');
    requireContains(traceText, ...
        'LogObjectiveSnapshot', ...
        'test_PRBCCMO_t_metrics:ObjectiveSnapshotLogger', ...
        'PRBCCMO_t must log objective-space populations, archive members, and boundary offspring.');
    requireContains(traceText, ...
        'WriteContext=WriteContext||WriteBoundaryOff;', ...
        'test_PRBCCMO_t_metrics:BoundaryOffContextSnapshot', ...
        'A generation with MLP-selected boundary offspring must also log same-generation C/U/archive context.');
    requireNotContains(traceText, ...
        'AnchorRows', ...
        'test_PRBCCMO_t_metrics:NoAnchorRows', ...
        'Traced metrics must not depend on the old anchor/pair row dataset.');
    requireNotContains(traceText, ...
        'PairRows', ...
        'test_PRBCCMO_t_metrics:NoPairRows', ...
        'Traced metrics must not depend on the old anchor/pair row dataset.');

    Algorithm = PRBCCMO_t('save',0,'run',1);
    Problem   = DASCMOP1_BC('N',40,'maxFE',800);
    Algorithm.Solve(Problem);

    runFolder = Algorithm.metric.analysis_folder;
    assert(isfolder(runFolder), ...
        'test_PRBCCMO_t_metrics:MissingRunFolder', ...
        'PRBCCMO_t must emit a trace run folder under Data/PRBCCMO_t.');

    summaryFile  = fullfile(runFolder,'generation_summary.csv');
    boundaryFile = fullfile(runFolder,'boundary_event.csv');
    archiveFile  = fullfile(runFolder,'archive_members.csv');
    objectiveFile = fullfile(runFolder,'objective_snapshot.csv');
    mlpFile      = fullfile(runFolder,'mlp_events.csv');
    metaFile     = fullfile(runFolder,'run_meta.csv');

    assert(isfile(summaryFile) && isfile(boundaryFile) && isfile(archiveFile) && ...
           isfile(objectiveFile) && isfile(mlpFile) && isfile(metaFile), ...
        'test_PRBCCMO_t_metrics:MissingCsvFiles', ...
        'PRBCCMO_t must emit the traced CSV files.');

    Summary = readtable(summaryFile,'TextType','string');
    requireColumns(Summary, { ...
        'boundary_sector_coverage','boundary_mean_pair_dist','boundary_lowmargin_pair_hit', ...
        'boundary_seg_cross_dist','helper_skip_duplicate','seed_b_mean_pair_dist', ...
        'boundary_margin_oppdist_corr','boundary_lowmargin_mean_opp_dist', ...
        'boundary_highmargin_mean_opp_dist','boundary_lowmargin_oppdist_gain', ...
        'boundary_lowmargin_mean_opp_support','boundary_highmargin_mean_opp_support', ...
        'boundary_survive_c_rate','boundary_survive_u_rate', ...
        'seed_b_lowmargin_pair_hit','b_mean_pair_dist','b_lowmargin_pair_hit', ...
        'b_margin_oppdist_corr','b_lowmargin_mean_opp_dist','b_highmargin_mean_opp_dist', ...
        'b_lowmargin_oppdist_gain','b_lowmargin_mean_opp_support','b_highmargin_mean_opp_support', ...
        'train_size','train_pos','train_neg','train_sector_coverage', ...
        'train_anchor_count','train_pair_count','train_mean_pair_dist','train_can_train', ...
        'train_brier_after','train_logloss_after', ...
        'inf_pool_mean_margin','inf_selected_mean_margin','inf_margin_gain', ...
        'inf_pool_mean_obj_score','inf_selected_mean_obj_score','inf_obj_score_gain', ...
        'inf_pool_lowmargin_ratio','inf_selected_lowmargin_ratio','inf_lowmargin_ratio_gain'});

    Boundary = readtable(boundaryFile,'TextType','string');
    requireColumns(Boundary, { ...
        'anchor_feasible','helper_feasible','anchor_prob','anchor_score', ...
        'helper_prob','helper_score','beta_pred_cross','pair_dist','seg_cross_dist','opp_dist'});

    Archive = readtable(archiveFile,'TextType','string');
    requireColumns(Archive, {'opp_dist','score'});

    Objective = readtable(objectiveFile,'TextType','string');
    requireColumns(Objective, { ...
        'generation','fe','fe_ratio','role','index','sector','feasible', ...
        'prob','margin','opp_support','opp_dist','obj_score','score', ...
        'survive_c','survive_u','obj1','obj2'});
    assert(any(Objective.role == "pop_c") && any(Objective.role == "pop_u") && ...
           any(Objective.role == "archive_b"), ...
        'test_PRBCCMO_t_metrics:MissingObjectiveRoles', ...
        'Objective snapshots must include current feasible/infeasible populations and the boundary archive.');
    assert(all(isfinite(Objective.obj1)) && all(isfinite(Objective.obj2)), ...
        'test_PRBCCMO_t_metrics:InvalidObjectiveValues', ...
        'Objective snapshots must contain finite objective coordinates.');
    BoundaryGenerations = unique(Objective.generation(Objective.role == "boundary_off"));
    for g = reshape(BoundaryGenerations,1,[])
        Stage = Objective(Objective.generation == g,:);
        assert(any(Stage.role == "pop_c") && any(Stage.role == "pop_u") && ...
               any(Stage.role == "archive_b"), ...
            'test_PRBCCMO_t_metrics:BoundaryOffMissingSameGenerationContext', ...
            'Every generation with boundary_off rows must include same-generation pop_c/pop_u/archive_b rows.');
    end

    MLP = readtable(mlpFile,'TextType','string');
    requireColumns(MLP, { ...
        'train_size','pos_count','neg_count','sector_coverage', ...
        'src_b','src_recent_boundary','src_pop_c','src_pop_u'});

    RunSummary = summarize_PRBCCMO_t_run(runFolder);
    requireStructFields(RunSummary, { ...
        'problem','family','analysis_folder','final_b_size', ...
        'analysis_objective_csv', ...
        'final_boundary_lowmargin_pair_hit','final_boundary_seg_cross_dist', ...
        'final_boundary_margin_oppdist_corr','final_boundary_lowmargin_oppdist_gain', ...
        'final_boundary_survive_c_rate','final_boundary_survive_u_rate', ...
        'final_b_margin_oppdist_corr','final_b_lowmargin_oppdist_gain', ...
        'final_inf_margin_gain','final_inf_obj_score_gain','final_inf_lowmargin_ratio_gain', ...
        'final_train_pair_count','first_can_train_generation', ...
        'first_trained_generation','stable3_generation'});

    outDir = fullfile(tempdir,'prbccmo_t_metrics_test');
    if ~isfolder(outDir)
        mkdir(outDir);
    end
    [RunTable,ProblemTable,FamilyTable] = summarize_PRBCCMO_t_data(runFolder,outDir);
    assert(~isempty(RunTable) && ~isempty(ProblemTable) && ~isempty(FamilyTable), ...
        'test_PRBCCMO_t_metrics:EmptySummaryTables', ...
        'The summary script must produce run/problem/family tables.');
    requireColumns(ProblemTable, { ...
        'avg_final_boundary_margin_oppdist_corr','avg_final_boundary_lowmargin_oppdist_gain', ...
        'avg_final_inf_lowmargin_ratio_gain','avg_final_inf_margin_gain','avg_final_inf_obj_score_gain'});
    assert(isfile(fullfile(outDir,'run_summary.csv')) && ...
           isfile(fullfile(outDir,'problem_summary.csv')) && ...
           isfile(fullfile(outDir,'family_summary.csv')), ...
        'test_PRBCCMO_t_metrics:MissingSummaryCsv', ...
        'The summary script must write run/problem/family CSV files.');

    plotDir = fullfile(outDir,'objective_plots');
    PlotFiles = plot_PRBCCMO_t_objective_evidence(runFolder,plotDir);
    assert(~isempty(PlotFiles) && all(isfile(string(PlotFiles))), ...
        'test_PRBCCMO_t_metrics:ObjectivePlotMissing', ...
        'The objective-space plotting helper must create figure files from objective_snapshot.csv.');
    RegionPlot = plot_PRBCCMO_t_generation_region_evidence(runFolder,plotDir);
    assert(isfile(string(RegionPlot)), ...
        'test_PRBCCMO_t_metrics:GenerationRegionPlotMissing', ...
        'The generation-level region plotting helper must create one-generation feasible-region evidence figures.');

    benchCsv = fullfile(outDir,'benchmark_smoke.csv');
    Results = benchmark_PRBCCMO_t_suite({'DASCMOP1_BC'},1,benchCsv,40,800);
    assert(istable(Results) && height(Results) == 1 && isfile(benchCsv), ...
        'test_PRBCCMO_t_metrics:BenchmarkSmokeFailed', ...
        'The benchmark helper must emit a one-row CSV for the smoke case.');
    requireColumns(Results, { ...
        'problem','family','run','igd','hv','feasible_rate','runtime', ...
        'analysis_folder','analysis_objective_csv','final_b_size','final_boundary_lowmargin_pair_hit', ...
        'final_boundary_seg_cross_dist','final_boundary_margin_oppdist_corr', ...
        'final_boundary_lowmargin_oppdist_gain','final_boundary_survive_c_rate', ...
        'final_inf_lowmargin_ratio_gain','final_inf_margin_gain','final_inf_obj_score_gain', ...
        'stable3_generation'});
end

function requireColumns(T,Names)
    Missing = setdiff(string(Names),string(T.Properties.VariableNames));
    assert(isempty(Missing), ...
        'test_PRBCCMO_t_metrics:MissingColumns', ...
        'Missing expected columns: %s', strjoin(cellstr(Missing), ', '));
end

function requireStructFields(S,Names)
    Missing = Names(~isfield(S,Names));
    assert(isempty(Missing), ...
        'test_PRBCCMO_t_metrics:MissingStructFields', ...
        'Missing expected fields: %s', strjoin(Missing, ', '));
end

function requireContains(text,pattern,id,msg)
    assert(contains(text,normalizeCode(pattern)),id,msg);
end

function requireNotContains(text,pattern,id,msg)
    assert(~contains(text,normalizeCode(pattern)),id,msg);
end

function text = normalizeCode(text)
    text = regexprep(text,'%[^\n\r]*','');
    text = strrep(text,'...','');
    text = regexprep(text,'\s+','');
end
