function test_PRBCCMO_t_smoke()
% Smoke test for the traced PRBCCMO variant.

    RootDir = fileparts(which('platemo'));
    if isempty(RootDir)
        error('test_PRBCCMO_t_smoke:NoPlatEMO','Cannot locate platemo.m on the MATLAB path.');
    end

    DataDir = fullfile(RootDir,'Data','PRBCCMO_t');
    Before = dir(fullfile(DataDir,'PRBCCMO_t_LIRCMOP1_BC_*'));
    BeforeNames = {Before.name};

    platemo( ...
        'algorithm', @PRBCCMO_t, ...
        'problem',   @LIRCMOP1_BC, ...
        'N',         20, ...
        'maxFE',     200, ...
        'save',      0);

    After = dir(fullfile(DataDir,'PRBCCMO_t_LIRCMOP1_BC_*'));
    NewMask = ~ismember({After.name},BeforeNames);
    NewRuns = After(NewMask);
    assert(~isempty(NewRuns), ...
        'test_PRBCCMO_t_smoke:NoRunFolder', ...
        'PRBCCMO_t did not create a new Data/PRBCCMO_t run folder.');

    [~,idx] = max([NewRuns.datenum]);
    RunFolder = fullfile(DataDir,NewRuns(idx).name);

    Required = { ...
        'run_meta.csv', ...
        'generation_summary.csv', ...
        'boundary_event.csv', ...
        'archive_members.csv', ...
        'mlp_events.csv'};
    for i = 1 : numel(Required)
        FilePath = fullfile(RunFolder,Required{i});
        assert(exist(FilePath,'file') == 2, ...
            'test_PRBCCMO_t_smoke:MissingCsv', ...
            'Missing expected CSV file: %s', FilePath);
    end

    MatFiles = dir(fullfile(RunFolder,'*.mat'));
    assert(isempty(MatFiles), ...
        'test_PRBCCMO_t_smoke:UnexpectedMat', ...
        'PRBCCMO_t should not save MAT analysis files.');
end
