function test_PRBCCMO_semantics()
% Static regression guard for the boundary-band fix.md semantics.

    rootDir = fileparts(mfilename('fullpath'));
    mainText  = normalizeCode(fileread(fullfile(rootDir,'PRBCCMO.m')));
    traceText = normalizeCode(fileread(fullfile(rootDir,'PRBCCMO_t.m')));

    verifyBoundaryBandSemantics(mainText,'Main');
    verifyBoundaryBandSemantics(traceText,'Trace');
end

function verifyBoundaryBandSemantics(text,prefix)
    requireContains(text, ...
        'ModelState.trainBuffer=InitTrainingBuffer();', ...
        [prefix 'TrainingBufferState'], ...
        'Model state must keep a rolling training buffer.');
    requireContains(text, ...
        '[ModelState.trainBuffer,BufferDiag,ModelState.lastCandidateDec]=UpdateTrainingBuffer(', ...
        [prefix 'UpdateTrainingBuffer'], ...
        'Training evidence must be updated through a rolling boundary-band buffer.');
    requireContains(text, ...
        'Band=CollectSectorBoundaryBand(', ...
        [prefix 'CollectSectorBoundaryBand'], ...
        'Dataset construction must collect pair-centric boundary-band samples.');
    requireContains(text, ...
        'BuildBoundaryDatasetFromBuffer(', ...
        [prefix 'DatasetFromBuffer'], ...
        'MLP training data must be built from the buffer, not fixed pairs.');
    requireContains(text, ...
        'Model=TrainBoundaryMLP(Model,Dataset,hidden,epoch,lr,Mode);', ...
        [prefix 'WarmStartSignature'], ...
        'TrainBoundaryMLP must accept the previous model and an explicit cold/finetune mode.');
    requireContains(text, ...
        'CanWarmStartBoundaryMLP(Model,D,Hidden)', ...
        [prefix 'WarmStartGuard'], ...
        'MLP training must reuse compatible weights instead of always random restarting.');
    requireContains(text, ...
        'Summary.new_sample_ratio>=0.20', ...
        [prefix 'BufferChangeTrigger'], ...
        'Retraining must be triggered by meaningful training-buffer change.');
    requireContains(text, ...
        'Summary.mixed_sector_gain>0', ...
        [prefix 'MixedSectorExpansionTrigger'], ...
        'Retraining must react to mixed-sector expansion.');
    requireContains(text, ...
        'Summary.validation_brier>ModelState.lastValidationBrier+0.02', ...
        [prefix 'ValidationDropTrigger'], ...
        'Retraining must react to boundary validation degradation.');
    requireContains(text, ...
        'Pairs=BuildBoundaryPairs(PairPool,W,max(4*size(W,1),2*numel(PairPool)));', ...
        [prefix 'BoundaryPairs'], ...
        'Boundary archive updates must discover cross-label pair brackets before sector assignment.');
    requireContains(text, ...
        'Support=KeepUniquePopulation([BoundarySamples,PopulationC,PopulationU]);', ...
        [prefix 'CurrentStageArchiveSupport'], ...
        'Boundary archive support must be current-stage only, without old B self-support.');
    requireContains(text, ...
        '[Candidates,CandidateSource]=BuildArchiveCandidateSet(BoundarySamples,TightEndpoints,RevalidatedB);', ...
        [prefix 'CurrentStageArchiveCandidates'], ...
        'Boundary archive candidates must preserve source priority across boundary offspring, tight endpoints, and revalidated memory.');
    requireContains(text, ...
        'B=SelectTopKPerSector(Candidates,Meta,CandidateSource,kappa,~isempty(Model));', ...
        [prefix 'ArchiveSourcePriority'], ...
        'Boundary archive retention must pass candidate source priority into per-sector selection.');
    requireContains(text, ...
        'SortByArchiveSourcePriority(Meta,idx(Meta.feasible(idx)==1),Source,SideQuota);', ...
        [prefix 'ArchiveSourceTieredFeasibleSide'], ...
        'Boundary archive feasible-side selection must prefer BoundaryOff before tight endpoints and old-B memory.');
    requireContains(text, ...
        'SortByArchiveSourcePriority(Meta,idx(Meta.feasible(idx)==0),Source,SideQuota);', ...
        [prefix 'ArchiveSourceTieredInfeasibleSide'], ...
        'Boundary archive infeasible-side selection must prefer BoundaryOff before tight endpoints and old-B memory.');
    requireContains(text, ...
        'Eligible=BoundaryEligible(Meta,ModelReady,''archive'');', ...
        [prefix 'ArchiveEligibilityGate'], ...
        'Archive retention must use strict pair-gap eligibility before per-sector selection.');
    requireContains(text, ...
        'LocalPair=Meta.localPairExists>0;', ...
        [prefix 'BoundaryEligibleLocalPair'], ...
        'BoundaryEligible must explicitly require local feasible/infeasible witness-pair evidence.');
    requireContains(text, ...
        'Meta.boundaryGap<=GapGate', ...
        [prefix 'BoundaryEligibleBoundaryGap'], ...
        'BoundaryEligible must gate on the unified pair gap.');
    requireContains(text, ...
        'functionTau=BoundaryGapTau(Mode)', ...
        [prefix 'StableBoundaryGapTau'], ...
        'Boundary gap admission must use stable tau_B/tau_E thresholds instead of relative quantiles.');
    requireContains(text, ...
        'Tau=1.25;', ...
        [prefix 'EvidenceTau'], ...
        'Evidence admission must use the loose fixed tau_E threshold.');
    requireContains(text, ...
        'Tau=0.55;', ...
        [prefix 'ArchiveTau'], ...
        'Archive admission must use the strict fixed tau_B threshold.');
    requireNotContains(text, ...
        'Meta.margin<=MarginGate', ...
        [prefix 'NoMarginAdmissionGate'], ...
        'BoundaryEligible must not use calibrated margin as an archive/training admission gate.');
    requireContains(text, ...
        'Meta=BuildBoundaryMetaFromBuffer(Buffer,W);Eligible=BoundaryEligible(Meta,false,''evidence'');', ...
        [prefix 'TrainingDatasetUsesEvidenceEligibility'], ...
        'BuildBoundaryDatasetFromBuffer must use loose pair-centric evidence eligibility, not strict archive admission.');
    requireContains(text, ...
        'Buffer.Obj=Band.Obj;', ...
        [prefix 'TrainingBufferCarriesObjectives'], ...
        'Training buffer must retain objective values so dataset eligibility can compute objective-side boundary scores.');
    requireContains(text, ...
        'Relevant=BoundaryEligible(CandidateMeta,~isempty(Model),''evidence'');', ...
        [prefix 'PostEvaluationChildEligibility'], ...
        'Boundary offspring must be accepted by loose evidence eligibility only after real evaluation.');
    requireContains(text, ...
        'EvaluatedCandidate=Problem.Evaluation(CandidateDec);', ...
        [prefix 'EvaluatedChildObjectiveMeta'], ...
        'Boundary offspring objective relevance must be checked after child evaluation.');
    requireContains(text, ...
        'CandidateMeta=BuildBoundaryMeta(EvaluatedCandidate,W,Model,PopulationC,PopulationU,CandidateSupportBase);', ...
        [prefix 'ChildObjectiveFromEvaluation'], ...
        'Candidate objective score must come from evaluated child objectives, not the parent proxy.');
    requireContains(text, ...
        'NewRows=~ismember(Buffer.Dec,OldDec,''rows'');', ...
        [prefix 'BufferReplacementChange'], ...
        'Buffer-change retraining must count replacement rows even when buffer size is unchanged.');
    requireContains(text, ...
        '[W1,b1,W2,b2]=RebaseBoundaryMLPNormalization(Model,Mu,Sigma);', ...
        [prefix 'WarmStartNormalizationRebase'], ...
        'Warm-start must rebase old weights into the new normalization space.');
    requireContains(text, ...
        'Trusted=FindSupportedBoundaryCandidates(Meta,W,~isempty(Model))&Meta.feasible==0;', ...
        [prefix 'SupportedInfeasibleGate'], ...
        'Infeasible selection must hard-gate candidates by the same BoundaryEligible semantics.');
    requireContains(text, ...
        'AnchorPool=KeepUniquePopulation([B,PopulationC,PopulationU]);', ...
        [prefix 'WitnessAnchorPool'], ...
        'Boundary offspring must use B plus current-stage populations as witness-pair anchors.');
    requireContains(text, ...
        'Pair=BuildBoundaryPairs(AnchorPool,W,max(Problem.N,2*Budget));', ...
        [prefix 'BoundaryPairBootstrap'], ...
        'Boundary offspring must bootstrap from current-stage cross-label boundary pairs.');
    requireContains(text, ...
        'FirstDec=0.5*(Pair.FeasibleDec(1:PairCount,:)+Pair.InfeasibleDec(1:PairCount,:));', ...
        [prefix 'WitnessMidpointContraction'], ...
        'Boundary offspring must start with witness-pair midpoint contraction.');
    requireContains(text, ...
        'SecondDec(i,:)=0.5*(double(FirstEval(i).decs)+Pair.InfeasibleDec(i,:));', ...
        [prefix 'WitnessShortBisectionFeasibleSide'], ...
        'Boundary offspring must do short bisection after evaluated feasible midpoint probes.');
    requireContains(text, ...
        'SecondDec(i,:)=0.5*(Pair.FeasibleDec(i,:)+double(FirstEval(i).decs));', ...
        [prefix 'WitnessShortBisectionInfeasibleSide'], ...
        'Boundary offspring must do short bisection after evaluated infeasible midpoint probes.');
    requireContains(text, ...
        '[hidden,epoch,lr,~,rho]=Algorithm.ParameterSet(20,20,0.01,10,0.12);', ...
        [prefix 'KappaFixedTen'], ...
        'Boundary archive must keep the widened fixed kappa setting.');
    requireContains(text, ...
        'kappa=10;', ...
        [prefix 'KappaHardFixedTen'], ...
        'Boundary archive must hard-fix kappa=10 so each sector keeps a denser boundary shell.');
    requireContains(text, ...
        'MaxPairsPerSector=2;', ...
        [prefix 'PairEvidenceTraining'], ...
        'MLP training data must be narrowed to top pair-centric evidence endpoints per sector.');
    requireContains(text, ...
        'Z=ComputeIdealPoint(', ...
        [prefix 'IdealPointOnly'], ...
        'Sector association must use ideal points instead of unique reference objective matrices.');
    requireContains(text, ...
        'SupportBase=BuildOppositeSupportBase(Support,W);', ...
        [prefix 'OppositeSupportBase'], ...
        'Opposite-side support must cache support labels, neighbors, and distance scale before meta reuse.');
    requireContains(text, ...
        'SupportCache=ResolveOppositeSupportCache(Support,W,RefObj);', ...
        [prefix 'OppositeSupportResolve'], ...
        'Boundary meta must resolve sectors from a reusable support cache instead of rebuilding all support data.');
    requireContains(text, ...
        'OppSupport=ComputeOppositeSupportFromCache(', ...
        [prefix 'OppositeSupportFromCache'], ...
        'Opposite-side support queries must reuse cached support data.');
    requireContains(text, ...
        'Temperature=FitBoundaryTemperature(Z,Y);', ...
        [prefix 'BoundaryTemperatureCalibration'], ...
        'MLP output must be temperature-calibrated before margin is used as boundary uncertainty.');
    requireContains(text, ...
        'if~HaveDecisionRowsChanged(LastCandidateDec,PreviousCandidateDec)', ...
        [prefix 'TrainingBufferCandidateChangeGate'], ...
        'Training buffer update must skip sector/opposite-distance rebuild when the candidate set is unchanged.');
    requireContains(text, ...
        'Eligible=ResolveTrainingCandidateEligibility(', ...
        [prefix 'TrainingBufferIncrementalEligibility'], ...
        'Training buffer update must restrict opposite-distance work to new/core boundary candidates.');
    requireContains(text, ...
        'Band.BoundaryGap=[Pairs.BoundaryGap(SelectedPairIdx);Pairs.BoundaryGap(SelectedPairIdx)];', ...
        [prefix 'TrainingBufferPairGap'], ...
        'Training buffer must carry pair graph boundary gaps instead of recomputing nearest-opposite gaps.');
    requireContains(text, ...
        'Buffer.PairId=Band.PairId;', ...
        [prefix 'TrainingBufferPairId'], ...
        'Training buffer must preserve pair membership for evidence rows.');
    requireContains(text, ...
        'Band=OffsetTrainingPairIds(Band,Buffer.PairId);', ...
        [prefix 'TrainingPairIdUniqueOffset'], ...
        'Training buffer must make PairId globally unique before appending new evidence rows.');
    requireContains(text, ...
        'Add=SelectReplayPairsInSector(Buffer,Meta,Eligible,s,MaxPairsPerSector);', ...
        [prefix 'TrainingReplayPairPreserving'], ...
        'Training replay must select feasible/infeasible endpoints by PairId.');
    requireContains(text, ...
        '[BoundaryOff,BoundaryEvidence', ...
        [prefix 'BoundaryEvidenceReturned'], ...
        'Boundary offspring generation must return all evaluated contraction probes as evidence.');
    requireContains(text, ...
        'Evidence=KeepUniquePopulation([FirstEval,EvaluatedCandidate]);', ...
        [prefix 'RejectedContractionProbesKept'], ...
        'Rejected or unselected contraction probes must remain available to the evidence buffer.');
    requireContains(text, ...
        '[Population,Source]=MergeTrainingSourcePopulations(B,BoundaryEvidence,PopulationC,PopulationU);', ...
        [prefix 'TrainingSourceDirectTags'], ...
        'Training candidate source tags must be carried during concatenation instead of recovered by repeated ismember.');
    requireContains(text, ...
        'CandidateSupportBase=BuildOppositeSupportBase(', ...
        [prefix 'ChildSupportIncludesContractionProbes'], ...
        'Boundary offspring acceptance must evaluate child support against current witness probes.');
    requireContains(text, ...
        'RecentBoundaryOff=BoundaryOff;B=UpdateBoundaryArchive(B,RecentBoundaryOff,PopulationC,PopulationU,W,Model,kappa);', ...
        [prefix 'EndOfGenerationArchiveUpdate'], ...
        'Boundary archive must be updated once at the end of the generation with the selected populations.');
    requireContains(text, ...
        'B=UpdateBoundaryArchive(B,RecentBoundaryOff,PopulationC,PopulationU,W,Model,kappa);[Model,ModelState', ...
        [prefix 'ArchiveBeforeModelUpdate'], ...
        'Boundary model updates must use the end-of-generation archive and populations.');
    requireContains(text, ...
        'B,BoundaryEvidence,PopulationC,PopulationU,W,', ...
        [prefix 'ModelUsesFullBoundaryEvidence'], ...
        'Boundary model updates must train from all evaluated boundary evidence, not only selected BoundaryOff.');

    requireNotContains(text, ...
        'CollectLocalBoundaryPairs(', ...
        [prefix 'NoPairCollector'], ...
        'Fixed feasible/infeasible pair collectors must be removed.');
    requireNotContains(text, ...
        'Summary.pair_ready', ...
        [prefix 'NoPairReadyTrigger'], ...
        'Retraining must not use pair-ready gates.');
    requireNotContains(text, ...
        'CurrentFE-ModelState.lastTrainFE>=2*Problem.N', ...
        [prefix 'NoFEOnlyTrigger'], ...
        'Retraining must not be controlled by a fixed FE interval.');
    requireNotContains(text, ...
        'Model=TrainBoundaryMLP(Dataset,hidden,epoch,lr);', ...
        [prefix 'NoColdOnlyTrainCall'], ...
        'MLP training must not use the old cold-start-only signature.');
    requireNotContains(text, ...
        'ProxyObjScore=ParentMeta.objScore(BaseIdx);', ...
        [prefix 'NoParentProxyObjectiveGate'], ...
        'Boundary offspring objective relevance must not reuse the anchor objective score as the child score.');
    requireNotContains(text, ...
        'Added=max(0,NewSize-OldSize);', ...
        [prefix 'NoSizeOnlyBufferChange'], ...
        'Buffer-change retraining must not depend only on buffer size growth.');
    requireNotContains(text, ...
        'W1=Model.W1;', ...
        [prefix 'NoRawWarmStartWeights'], ...
        'Warm-start must not reuse first-layer weights without normalization rebasing.');
    requireNotContains(text, ...
        'BuildReferenceObj(', ...
        [prefix 'NoReferenceObjMatrix'], ...
        'Code must not build unique reference objective matrices when only the ideal point is needed.');
    requireNotContains(text, ...
        'PickRepresentativeInSector(', ...
        [prefix 'NoPerSectorRepresentativeRecompute'], ...
        'Representative selection must not recompute sectors, fronts, and crowding inside each sector.');
    requireNotContains(text, ...
        'BuildBoundaryRepresentatives(', ...
        [prefix 'NoRepresentativeRefill'], ...
        'Boundary archive must not refill sectors with objective representatives.');
    requireNotContains(text, ...
        'Support=KeepUniquePopulation([B,BoundarySamples,PopulationC,PopulationU]);', ...
        [prefix 'NoOldBSelfSupport'], ...
        'Boundary archive update must not let old B provide self-support.');
    requireNotContains(text, ...
        'Candidates=KeepUniquePopulation([B,BoundarySamples,Witnesses]);', ...
        [prefix 'NoOldBCandidates'], ...
        'Boundary archive update must not carry old B forward as a candidate pool.');
    requireNotContains(text, ...
        'BuildRepresentativeIndexBySector(', ...
        [prefix 'NoRepresentativeIndex'], ...
        'Boundary archive must not use front/crowding representatives as boundary evidence.');
    requireNotContains(text, ...
        'NeedsRepresentativeRefill(', ...
        [prefix 'NoRepresentativeRefillGate'], ...
        'Boundary archive must allow empty sectors instead of forcing representative refill.');
    requireContains(text, ...
        'Pairs=BuildBoundaryPairsFromArrays(PairDec,PairObj,PairLabel,[],max(2*N,2*size(PairDec,1)));', ...
        [prefix 'MetaUsesPairGraph'], ...
        'Boundary meta must derive shell metrics from the pair graph, not nearest opposite samples.');
    requireNotContains(text, ...
        'Feasible=double(Prob>=0.5);', ...
        [prefix 'NoPredictedSidePreEval'], ...
        'Unevaluated boundary children must not use predicted MLP side as geometric truth.');
    requireNotContains(text, ...
        'CandidateMeta.oppSupport>=AnchorOppSupport', ...
        [prefix 'NoAnchorRelativeSupportGate'], ...
        'Boundary offspring acceptance must not be relative to a possibly stale anchor support.');
    requireNotContains(text, ...
        'CandidateMeta.objScore<=CandidateAnchorObjScore+0.10', ...
        [prefix 'NoAnchorRelativeObjectiveGate'], ...
        'Boundary offspring acceptance must not be relative to a possibly stale anchor objective score.');
    requireNotContains(text, ...
        'PoolMeta=BuildBoundaryMeta(Pool,W,[],PopulationC,PopulationU,Pool);', ...
        [prefix 'NoStableParentMetaInLoop'], ...
        'Stable parent selection must not rebuild pool meta inside the anchor loop.');
    requireNotContains(text, ...
        'ifisempty(Model)||isempty(B)', ...
        [prefix 'NoModelOrArchiveDeadlock'], ...
        'Boundary offspring must not deadlock when B or Model is empty.');
    requireNotContains(text, ...
        'BuildBoundaryWitnesses(', ...
        [prefix 'NoPointWitnessPrimitive'], ...
        'Boundary witness point primitives must be removed in favor of BuildBoundaryPairs.');
    requireNotContains(text, ...
        'BuildLocalWitnessPairs(', ...
        [prefix 'NoLocalWitnessPairPrimitive'], ...
        'Local sector-first witness pairing must be removed in favor of global cross-label pair discovery.');
    requireNotContains(text, ...
        'Meta.objScore<=ObjGate', ...
        [prefix 'NoObjScoreHardGate'], ...
        'Objective score must be a tie-breaker, not a hard boundary eligibility gate.');
    requireNotContains(text, ...
        'idx=(1:min(size(Pairs.BoundaryGap,1),Limit))'';', ...
        [prefix 'NoLooseEndpointFallback'], ...
        'ExtractTightPairEndpoints must not fall back to non-tight pair endpoints.');
    requireNotContains(text, ...
        'ComputeBufferBetweenScoreObj(', ...
        [prefix 'NoBufferNearestOppositeRebuild'], ...
        'Training buffer meta must use stored pair gaps instead of rebuilding nearest-opposite scores.');
    requireNotContains(text, ...
        'ComputeOppositeDistanceForCandidates(', ...
        [prefix 'NoNearestOppositeDistanceHelper'], ...
        'Unused nearest-opposite helper must be removed.');
    requireNotContains(text, ...
        'ResolveFiniteQuantileGate(', ...
        [prefix 'NoRelativeBoundaryGapQuantileGate'], ...
        'Boundary admission must not use relative quantile gates for tau_B/tau_E semantics.');
    requireNotContains(text, ...
        'ResolveOppSupportGate(', ...
        [prefix 'NoOppSupportGateHelper'], ...
        'Unused opp-support gate helper must be removed.');
    requireNotContains(text, ...
        'Need>0&&~isempty(Model)&&~isempty(Infeasible)', ...
        [prefix 'NoModelRequiredForInfeasibleBoundarySelection'], ...
        'Pop_C must retain pair-supported infeasible boundary candidates before the model is trained.');
    requireNotContains(text, ...
        'Source(ismember(Population.decs', ...
        [prefix 'NoSourceRecoveryIsmember'], ...
        'Training source recovery must not use repeated row-wise ismember calls.');
    requireNotContains(text, ...
        'SupportCache=BuildOppositeSupportCache(Support,W,RefObj);', ...
        [prefix 'NoMetaLocalSupportCacheBuild'], ...
        'BuildBoundaryMeta must not rebuild the full support cache on every call.');
    requireNotContains(text, ...
        'Pick(end+1,:)', ...
        [prefix 'NoRoundRobinDynamicPickGrowth'], ...
        'Sector round-robin selection must preallocate its pick matrix.');
    requireNotContains(text, ...
        'Dist=[Dist;', ...
        [prefix 'NoDistanceScaleDynamicGrowth'], ...
        'Distance-scale estimation must preallocate pairwise distance storage.');
    requireNotContains(text, ...
        'Ranked=[Ranked;', ...
        [prefix 'NoDatasetRankedDynamicGrowth'], ...
        'Boundary dataset construction must preallocate ranked replay indices.');
    requireNotContains(text, ...
        'B=UpdateBoundaryArchive(B,BoundaryOff,PopulationC,PopulationU,W,Model,kappa);', ...
        [prefix 'NoPreSelectionBoundaryArchiveUpdate'], ...
        'Boundary archive must not be rebuilt with boundary offspring before environmental selection.');
end

function requireContains(text,pattern,id,msg)
    assert(contains(text,normalizeCode(pattern)),id,msg);
end

function requireNotContains(text,pattern,id,msg)
    assert(~contains(text,normalizeCode(pattern)),id,msg);
end

function text = normalizeCode(text)
    text = regexprep(text,'%[^\n\r]*','');
    text = strrep(text,'...','');
    text = regexprep(text,'\s+','');
end
