function test_PRBCCMO_t_metrics()
% Regression test for traced PRBCCMO_t metrics, summaries, and benchmark hooks.

    rootDir = fileparts(mfilename('fullpath'));
    repoDir = fileparts(fileparts(fileparts(rootDir)));
    addpath(genpath(repoDir));

    Algorithm = PRBCCMO_t('save',0,'run',1);
    Problem   = DASCMOP1_BC('N',40,'maxFE',800);
    Algorithm.Solve(Problem);

    runFolder = Algorithm.metric.analysis_folder;
    assert(isfolder(runFolder), ...
        'test_PRBCCMO_t_metrics:MissingRunFolder', ...
        'PRBCCMO_t must emit a trace run folder under Data/PRBCCMO_t.');

    summaryFile  = fullfile(runFolder,'generation_summary.csv');
    boundaryFile = fullfile(runFolder,'boundary_event.csv');
    archiveFile  = fullfile(runFolder,'archive_members.csv');
    mlpFile      = fullfile(runFolder,'mlp_events.csv');
    metaFile     = fullfile(runFolder,'run_meta.csv');

    assert(isfile(summaryFile) && isfile(boundaryFile) && isfile(archiveFile) && ...
           isfile(mlpFile) && isfile(metaFile), ...
        'test_PRBCCMO_t_metrics:MissingCsvFiles', ...
        'PRBCCMO_t must emit the traced CSV files.');

    Summary = readtable(summaryFile,'TextType','string');
    requireColumns(Summary, { ...
        'boundary_sector_coverage','boundary_mean_pair_dist','boundary_lowmargin_pair_hit', ...
        'boundary_seg_cross_dist','helper_skip_duplicate','seed_b_mean_pair_dist', ...
        'seed_b_lowmargin_pair_hit','b_mean_pair_dist','b_lowmargin_pair_hit', ...
        'train_anchor_count','train_pair_count','train_mean_pair_dist','train_can_train','train_brier_after', ...
        'train_logloss_after'});

    Boundary = readtable(boundaryFile,'TextType','string');
    requireColumns(Boundary, { ...
        'anchor_feasible','helper_feasible','anchor_prob','anchor_score', ...
        'helper_prob','helper_score','beta_pred_cross','pair_dist','seg_cross_dist'});

    Archive = readtable(archiveFile,'TextType','string');
    requireColumns(Archive, {'opp_dist','score'});

    MLP = readtable(mlpFile,'TextType','string');
    requireColumns(MLP, { ...
        'anchor_count','pair_count','mean_pair_dist'});

    RunSummary = summarize_PRBCCMO_t_run(runFolder);
    requireStructFields(RunSummary, { ...
        'problem','family','analysis_folder','final_b_size', ...
        'final_boundary_sector_coverage','final_boundary_lowmargin_pair_hit', ...
        'final_boundary_seg_cross_dist','final_train_pair_count','first_can_train_generation', ...
        'first_trained_generation','stable3_generation'});

    outDir = fullfile(tempdir,'prbccmo_t_metrics_test');
    if ~isfolder(outDir)
        mkdir(outDir);
    end
    [RunTable,ProblemTable,FamilyTable] = summarize_PRBCCMO_t_data(runFolder,outDir);
    assert(~isempty(RunTable) && ~isempty(ProblemTable) && ~isempty(FamilyTable), ...
        'test_PRBCCMO_t_metrics:EmptySummaryTables', ...
        'The summary script must produce run/problem/family tables.');
    assert(isfile(fullfile(outDir,'run_summary.csv')) && ...
           isfile(fullfile(outDir,'problem_summary.csv')) && ...
           isfile(fullfile(outDir,'family_summary.csv')), ...
        'test_PRBCCMO_t_metrics:MissingSummaryCsv', ...
        'The summary script must write run/problem/family CSV files.');

    benchCsv = fullfile(outDir,'benchmark_smoke.csv');
    Results = benchmark_PRBCCMO_t_suite({'DASCMOP1_BC'},1,benchCsv,40,800);
    assert(istable(Results) && height(Results) == 1 && isfile(benchCsv), ...
        'test_PRBCCMO_t_metrics:BenchmarkSmokeFailed', ...
        'The benchmark helper must emit a one-row CSV for the smoke case.');
    requireColumns(Results, { ...
        'problem','family','run','igd','hv','feasible_rate','runtime', ...
        'analysis_folder','final_b_size','final_boundary_lowmargin_pair_hit', ...
        'final_boundary_seg_cross_dist','stable3_generation'});
end

function requireColumns(T,Names)
    Missing = setdiff(string(Names),string(T.Properties.VariableNames));
    assert(isempty(Missing), ...
        'test_PRBCCMO_t_metrics:MissingColumns', ...
        'Missing expected columns: %s', strjoin(cellstr(Missing), ', '));
end

function requireStructFields(S,Names)
    Missing = Names(~isfield(S,Names));
    assert(isempty(Missing), ...
        'test_PRBCCMO_t_metrics:MissingStructFields', ...
        'Missing expected fields: %s', strjoin(Missing, ', '));
end
