function test_PRBCCMO_semantics()
% Static regression guard for current fix.md anchor-pair semantics.

    rootDir = fileparts(mfilename('fullpath'));
    mainBlocks = loadSemanticBlocks(fullfile(rootDir,'PRBCCMO.m'));
    traceBlocks = loadSemanticBlocks(fullfile(rootDir,'PRBCCMO_t.m'));

    requireContains(mainBlocks.mainBlock, ...
        'SeedPool = KeepUniquePopulation([B,OffspringC,OffspringU]);', ...
        'test_PRBCCMO_semantics:MainSeedPool', ...
        'PRBCCMO.m must narrow SeedPool to B plus fresh offspring only.');
    requireContains(traceBlocks.mainBlock, ...
        'SeedPool = KeepUniquePopulation([B,OffspringC,OffspringU]);', ...
        'test_PRBCCMO_semantics:TraceSeedPool', ...
        'PRBCCMO_t.m must narrow SeedPool to B plus fresh offspring only.');
    requireNotContains(mainBlocks.mainBlock, ...
        'SeedPool = KeepUniquePopulation([B,PopulationC,PopulationU,OffspringC,OffspringU]);', ...
        'test_PRBCCMO_semantics:MainNoWideSeedPool', ...
        'PRBCCMO.m must not keep the old wide SeedPool.');
    requireNotContains(traceBlocks.mainBlock, ...
        'SeedPool = KeepUniquePopulation([B,PopulationC,PopulationU,OffspringC,OffspringU]);', ...
        'test_PRBCCMO_semantics:TraceNoWideSeedPool', ...
        'PRBCCMO_t.m must not keep the old wide SeedPool.');

    requireContains(mainBlocks.trainGate, ...
        'AnchorCnt = sum(TrainArchive.Label == 1);', ...
        'test_PRBCCMO_semantics:MainAnchorCount', ...
        'PRBCCMO.m must train against anchor counts, not trusted sectors.');
    requireContains(traceBlocks.trainGate, ...
        'AnchorCnt = sum(TrainArchive.Label == 1);', ...
        'test_PRBCCMO_semantics:TraceAnchorCount', ...
        'PRBCCMO_t.m must train against anchor counts, not trusted sectors.');
    requireContains(mainBlocks.trainGate, ...
        'PairCnt   = sum(TrainArchive.Weight(TrainArchive.Label == 0));', ...
        'test_PRBCCMO_semantics:MainPairCount', ...
        'PRBCCMO.m must count opposite pairs from weighted negatives.');
    requireContains(traceBlocks.trainGate, ...
        'PairCnt   = sum(TrainArchive.Weight(TrainArchive.Label == 0));', ...
        'test_PRBCCMO_semantics:TracePairCount', ...
        'PRBCCMO_t.m must count opposite pairs from weighted negatives.');
    requireContains(mainBlocks.trainGate, ...
        'Flag = AnchorCnt >= max(2,M) && PairCnt >= max(4,2*M);', ...
        'test_PRBCCMO_semantics:MainPairTrainGate', ...
        'PRBCCMO.m must gate training by anchor count and pair count.');
    requireContains(traceBlocks.trainGate, ...
        'Flag = AnchorCnt >= max(2,M) && PairCnt >= max(4,2*M);', ...
        'test_PRBCCMO_semantics:TracePairTrainGate', ...
        'PRBCCMO_t.m must gate training by anchor count and pair count.');
    requireNotContains(mainBlocks.trainGate, ...
        'Flag = sum(TrainArchive.Label == 1) >= minPos && sum(TrainArchive.Label == 0) >= minNeg;', ...
        'test_PRBCCMO_semantics:MainNoWideTrainGate', ...
        'PRBCCMO.m must not keep the old label-count-only train gate.');
    requireNotContains(traceBlocks.trainGate, ...
        'Flag = sum(TrainArchive.Label == 1) >= minPos && sum(TrainArchive.Label == 0) >= minNeg;', ...
        'test_PRBCCMO_semantics:TraceNoWideTrainGate', ...
        'PRBCCMO_t.m must not keep the old label-count-only train gate.');

    requireContains(mainBlocks.trainArchive, ...
        '[Candidates,Source,Weight] = BuildAnchorPairTrainPopulation(', ...
        'test_PRBCCMO_semantics:MainAnchorPairArchive', ...
        'PRBCCMO.m must build the train archive from anchor-pair populations.');
    requireContains(traceBlocks.trainArchive, ...
        '[Candidates,Source,Weight] = BuildAnchorPairTrainPopulation(', ...
        'test_PRBCCMO_semantics:TraceAnchorPairArchive', ...
        'PRBCCMO_t.m must build the train archive from anchor-pair populations.');
    requireContains(mainBlocks.trainArchive, ...
        'Keep = ReserveAnchorPairs(TrainArchive,MaxTrain,kNeg);', ...
        'test_PRBCCMO_semantics:MainReserveAnchorPairs', ...
        'PRBCCMO.m must trim the train archive by anchor-pair reservation.');
    requireContains(traceBlocks.trainArchive, ...
        'Keep = ReserveAnchorPairs(TrainArchive,MaxTrain,kNeg);', ...
        'test_PRBCCMO_semantics:TraceReserveAnchorPairs', ...
        'PRBCCMO_t.m must trim the train archive by anchor-pair reservation.');

    requireContains(mainBlocks.buildMeta, ...
        'Support = BuildBoundarySupportSet(TrainArchive);', ...
        'test_PRBCCMO_semantics:MainCoreOnlySupport', ...
        'PRBCCMO.m must build archive support from the train archive only.');
    requireContains(traceBlocks.buildMeta, ...
        'Support = BuildBoundarySupportSet(TrainArchive);', ...
        'test_PRBCCMO_semantics:TraceCoreOnlySupport', ...
        'PRBCCMO_t.m must build archive support from the train archive only.');

    requireContains(mainBlocks.probeGeneration, ...
        'Support = AppendSupportPair(Support,Anchor,AnchorMeta,Helper,HelperMeta);', ...
        'test_PRBCCMO_semantics:MainProbeSupportPair', ...
        'PRBCCMO.m must add only the real anchor/helper pair for probe support.');
    requireContains(traceBlocks.probeGeneration, ...
        'Support = AppendSupportPair(Support,Anchor,AnchorMeta,Helper,HelperMeta);', ...
        'test_PRBCCMO_semantics:TraceProbeSupportPair', ...
        'PRBCCMO_t.m must add only the real anchor/helper pair for probe support.');

    requireContains(mainBlocks.bridgeMask, ...
        'BridgeMask = true(numel(Meta.sector),1);', ...
        'test_PRBCCMO_semantics:MainBridgeMask', ...
        'PRBCCMO.m must not keep sector-based archive admission gates.');
    requireContains(traceBlocks.bridgeMask, ...
        'BridgeMask = true(numel(Meta.sector),1);', ...
        'test_PRBCCMO_semantics:TraceBridgeMask', ...
        'PRBCCMO_t.m must not keep sector-based archive admission gates.');

    requireContains(mainBlocks.helperSelect, ...
        'Allowed  = ~ismember(Pool.decs,Anchor.decs,''rows'');', ...
        'test_PRBCCMO_semantics:MainGlobalHelperPool', ...
        'PRBCCMO.m must select helpers from the whole P_C union P_U pool.');
    requireContains(traceBlocks.helperSelect, ...
        'Allowed  = ~ismember(Pool.decs,Anchor.decs,''rows'');', ...
        'test_PRBCCMO_semantics:TraceGlobalHelperPool', ...
        'PRBCCMO_t.m must select helpers from the whole P_C union P_U pool.');

    requireContains(mainBlocks.referenceMask, ...
        'Mask = true(numel(RefSector),1);', ...
        'test_PRBCCMO_semantics:MainGlobalSupportMask', ...
        'PRBCCMO.m must not restrict opposite support by sector neighborhoods.');
    requireContains(traceBlocks.referenceMask, ...
        'Mask = true(numel(RefSector),1);', ...
        'test_PRBCCMO_semantics:TraceGlobalSupportMask', ...
        'PRBCCMO_t.m must not restrict opposite support by sector neighborhoods.');

    requireContains(mainBlocks.mlpTrain, ...
        'BatchIdx = BuildBalancedReplayBatch(PosIdx,NegIdx);', ...
        'test_PRBCCMO_semantics:MainReplayBatch', ...
        'PRBCCMO.m must use balanced replay batches for BCE training.');
    requireContains(traceBlocks.mlpTrain, ...
        'BatchIdx = BuildBalancedReplayBatch(PosIdx,NegIdx);', ...
        'test_PRBCCMO_semantics:TraceReplayBatch', ...
        'PRBCCMO_t.m must use balanced replay batches for BCE training.');

    requireNotContains(mainBlocks.supportBuilder, ...
        'Support = AppendSupportPopulation(Support,Candidates,W,RefObj);', ...
        'test_PRBCCMO_semantics:MainNoCandidateSupport', ...
        'PRBCCMO.m must not add Candidates into the opposite-support set.');
    requireNotContains(traceBlocks.supportBuilder, ...
        'Support = AppendSupportPopulation(Support,Candidates,W,RefObj);', ...
        'test_PRBCCMO_semantics:TraceNoCandidateSupport', ...
        'PRBCCMO_t.m must not add Candidates into the opposite-support set.');
    requireNotContains(mainBlocks.supportBuilder, ...
        'Support = AppendSupportPopulation(Support,PopulationC,W,RefObj);', ...
        'test_PRBCCMO_semantics:MainNoPopulationCSupport', ...
        'PRBCCMO.m must not add PopulationC into the opposite-support set.');
    requireNotContains(traceBlocks.supportBuilder, ...
        'Support = AppendSupportPopulation(Support,PopulationC,W,RefObj);', ...
        'test_PRBCCMO_semantics:TraceNoPopulationCSupport', ...
        'PRBCCMO_t.m must not add PopulationC into the opposite-support set.');
    requireNotContains(mainBlocks.supportBuilder, ...
        'Support = AppendSupportPopulation(Support,PopulationU,W,RefObj);', ...
        'test_PRBCCMO_semantics:MainNoPopulationUSupport', ...
        'PRBCCMO.m must not add PopulationU into the opposite-support set.');
    requireNotContains(traceBlocks.supportBuilder, ...
        'Support = AppendSupportPopulation(Support,PopulationU,W,RefObj);', ...
        'test_PRBCCMO_semantics:TraceNoPopulationUSupport', ...
        'PRBCCMO_t.m must not add PopulationU into the opposite-support set.');

    requireNotContains(mainBlocks.mainBlock, ...
        'ResolveTrustedSectorsFromTrainArchive', ...
        'test_PRBCCMO_semantics:MainNoTrustedSectorCalls', ...
        'PRBCCMO.m must not pull trusted-sector gates into the main algorithm path.');
    requireNotContains(traceBlocks.mainBlock, ...
        'ResolveTrustedSectorsFromTrainArchive', ...
        'test_PRBCCMO_semantics:TraceNoTrustedSectorCalls', ...
        'PRBCCMO_t.m must not pull trusted-sector gates into the main algorithm path.');
    requireNotContains(mainBlocks.trainArchive, ...
        'ReserveCoreSideCoverageBySector', ...
        'test_PRBCCMO_semantics:MainNoSectorCoreQuota', ...
        'PRBCCMO.m must not keep sector-side core reservation.');
    requireNotContains(traceBlocks.trainArchive, ...
        'ReserveCoreSideCoverageBySector', ...
        'test_PRBCCMO_semantics:TraceNoSectorCoreQuota', ...
        'PRBCCMO_t.m must not keep sector-side core reservation.');
    requireNotContains(mainBlocks.trainArchive, ...
        'CountCorePairedSectors', ...
        'test_PRBCCMO_semantics:MainNoPairedSectors', ...
        'PRBCCMO.m must not keep paired-sector training diagnostics.');
    requireNotContains(traceBlocks.trainArchive, ...
        'CountCorePairedSectors', ...
        'test_PRBCCMO_semantics:TraceNoPairedSectors', ...
        'PRBCCMO_t.m must not keep paired-sector training diagnostics.');
    requireNotContains(mainBlocks.helperSelect, ...
        'ismember(PoolMeta.sector,unique(Neighbor))', ...
        'test_PRBCCMO_semantics:MainNoNeighborHelperGate', ...
        'PRBCCMO.m must not gate helper selection by neighboring sectors.');
    requireNotContains(traceBlocks.helperSelect, ...
        'ismember(PoolMeta.sector,unique(Neighbor))', ...
        'test_PRBCCMO_semantics:TraceNoNeighborHelperGate', ...
        'PRBCCMO_t.m must not gate helper selection by neighboring sectors.');
    requireNotContains(mainBlocks.referenceMask, ...
        'Allowed = unique([Sector;SectorNeighbors{Sector}(:)])', ...
        'test_PRBCCMO_semantics:MainNoNeighborSupportGate', ...
        'PRBCCMO.m must not gate support references by neighboring sectors.');
    requireNotContains(traceBlocks.referenceMask, ...
        'Allowed = unique([Sector;SectorNeighbors{Sector}(:)])', ...
        'test_PRBCCMO_semantics:TraceNoNeighborSupportGate', ...
        'PRBCCMO_t.m must not gate support references by neighboring sectors.');
    requireNotContains(mainBlocks.probeGeneration, ...
        'if AnchorMeta.trusted <= 0', ...
        'test_PRBCCMO_semantics:MainNoTrustedProbeGate', ...
        'PRBCCMO.m must not gate probe margins by trusted sectors.');
    requireNotContains(traceBlocks.probeGeneration, ...
        'if AnchorMeta.trusted <= 0', ...
        'test_PRBCCMO_semantics:TraceNoTrustedProbeGate', ...
        'PRBCCMO_t.m must not gate probe margins by trusted sectors.');
end

function requireContains(text,pattern,id,msg)
    assert(contains(normalizeText(text),normalizeText(pattern)),id,msg);
end

function requireNotContains(text,pattern,id,msg)
    assert(~contains(normalizeText(text),normalizeText(pattern)),id,msg);
end

function blocks = loadSemanticBlocks(filePath)
    text = fileread(filePath);
    blocks = struct( ...
        'mainBlock',extractBetweenMarkers(text, ...
            '^\s*function\s+main\s*\(\s*Algorithm\s*,\s*Problem\s*\)', ...
            '^%%\s*=+\s*Main-population offspring\s*=+\s*$'), ...
        'trainGate',extractFunctionBlock(text,'CanTrainBoundaryModel'), ...
        'trainArchive',extractFunctionBlock(text,'UpdateTrainArchive'), ...
        'buildMeta',extractFunctionBlock(text,'BuildBoundaryMeta'), ...
        'supportBuilder',extractFunctionBlock(text,'BuildBoundarySupportSet'), ...
        'probeGeneration',extractFunctionBlock(text,'GenerateBoundaryOffspringModelDriven'), ...
        'bridgeMask',extractFunctionBlock(text,'ResolveBridgeBoundaryMask'), ...
        'helperSelect',extractFunctionBlock(text,'SelectBoundaryHelper'), ...
        'referenceMask',extractFunctionBlock(text,'ResolveReferenceMask'), ...
        'mlpTrain',extractFunctionBlock(text,'TrainBoundaryMLP'));
end

function block = extractBetweenMarkers(text,startPattern,endPattern)
    lines = splitSourceLines(text);
    startIdx = findLine(lines,startPattern,1);
    endIdx = findLine(lines,endPattern,startIdx);
    block = strjoin(lines(startIdx:endIdx),newline);
end

function block = extractFunctionBlock(text,name)
    lines = splitSourceLines(text);
    startPattern = ['^function.*' regexptranslate('escape',name) '\s*\('];
    startIdx = findLine(lines,startPattern,1);
    endIdx = numel(lines);
    for i = startIdx + 1 : numel(lines)
        if ~isempty(regexp(lines{i},'^(function\b|%%\s*=+)','once'))
            endIdx = i - 1;
            break;
        end
    end
    block = strjoin(lines(startIdx:endIdx),newline);
end

function idx = findLine(lines,pattern,startIdx)
    idx = [];
    for i = startIdx : numel(lines)
        if ~isempty(regexp(lines{i},pattern,'once'))
            idx = i;
            return;
        end
    end
    assert(~isempty(idx), ...
        'test_PRBCCMO_semantics:MissingBlock', ...
        'Failed to locate source block for pattern: %s', ...
        pattern);
end

function lines = splitSourceLines(text)
    lines = regexp(text,'\r\n|\n|\r','split');
end

function text = normalizeText(text)
    text = stripMatlabComments(text);
    text = strrep(text,'...','');
    text = regexprep(text,'\s+','');
end

function text = stripMatlabComments(text)
    lines = splitSourceLines(text);
    for i = 1 : numel(lines)
        lines{i} = stripLineComment(lines{i});
    end
    text = strjoin(lines,newline);
end

function line = stripLineComment(line)
    inString = false;
    i = 1;
    while i <= length(line)
        if line(i) == ''''
            if inString && i < length(line) && line(i+1) == ''''
                i = i + 2;
                continue;
            end
            inString = ~inString;
            i = i + 1;
            continue;
        end
        if line(i) == '%' && ~inString
            line = line(1:i-1);
            return;
        end
        i = i + 1;
    end
end
