function test_CBS_pair_guide_training_observation
%TEST_CBS_PAIR_GUIDE_TRAINING_OBSERVATION Verify formal-run observers.

    rootPath = fileparts(fileparts(fileparts(fileparts(fileparts( ...
        mfilename('fullpath'))))));
    addpath(fullfile(rootPath,'Algorithms','Multi-objective optimization', ...
        'CBS-CGAN','Support'),'-begin');
    addCBSPaths(rootPath);

    seed = 1;
    schedule = struct('initialEpoch',2,'retrainEpoch',1,'nCritic',2);
    parameters = {500,6,2,64,4,32,1};
    rng(seed,'twister');
    PlainProblem = LIRCMOP5_BC('N',100,'D',30,'maxFE',8000, ...
        'maxRuntime',Inf);
    Plain = PairGuide('parameter',parameters, ...
        'save',1,'run',1,'outputFcn',@silentOutput);
    Plain.configurePairGuideTrainingExperiment(schedule);
    Plain.Solve(PlainProblem);
    plainRNG = rng;

    metricFE = zeros(0,1);
    metricIGD = zeros(0,1);
    feasibleCount = zeros(0,1);
    rng(seed,'twister');
    ObservedProblem = LIRCMOP5_BC('N',100,'D',30,'maxFE',8000, ...
        'maxRuntime',Inf);
    Observed = PairGuide('parameter',parameters, ...
        'save',1,'run',1,'outputFcn',@recordMetric);
    Observed.configurePairGuideTrainingExperiment(schedule);
    Observed.configureCutoffDiagnostics(struct('enabled',true, ...
        'stopAtCGANEnd',false,'disableOracleAudit',false));
    Observed.configureObjectiveSpaceSnapshots(struct('enabled',true, ...
        'targetFE',800:800:8000,'expectedRawCount',500, ...
        'expectedGuidedCount',20));
    Observed.Solve(ObservedProblem);
    observedRNG = rng;

    assert(PlainProblem.FE == 8000 && ObservedProblem.FE == 8000);
    assert(isequaln(plainRNG,observedRNG), ...
        'Metric/snapshot observation changed the terminal RNG.');
    assert(isequaln(double(Plain.result{end,2}.decs), ...
        double(Observed.result{end,2}.decs)) && ...
        isequaln(double(Plain.result{end,2}.objs), ...
        double(Observed.result{end,2}.objs)) && ...
        isequaln(double(Plain.result{end,2}.cons), ...
        double(Observed.result{end,2}.cons)), ...
        'Metric/snapshot observation changed the final population.');
    assert(~isempty(metricFE) && metricFE(end) == 8000 && ...
        all(diff(metricFE) > 0) && numel(metricIGD) == numel(metricFE) && ...
        numel(feasibleCount) == numel(metricFE));
    Snapshots = Observed.objectiveSpaceSnapshots();
    assert(numel(Snapshots) == 10 && ...
        isequal([Snapshots.targetFE],800:800:8000) && ...
        all(isfinite([Snapshots.actualFE])) && ...
        all(isfinite([Snapshots.poolFE])) && ...
        all([Snapshots.rawCount] == 500) && ...
        all([Snapshots.requestedCount] == 20) && ...
        all([Snapshots.guidedCount]+[Snapshots.fallbackCount] == 20));
    for i = 1 : numel(Snapshots)
        S = Snapshots(i);
        assert(size(S.archiveFeasibleDecs,1) == S.trainingPairCount && ...
            size(S.archiveInfeasibleDecs,1) == S.trainingPairCount && ...
            size(S.archiveFeasibleDecs,2) == ObservedProblem.D && ...
            size(S.archiveInfeasibleDecs,2) == ObservedProblem.D && ...
            size(S.archiveFeasibleObjs,1) == S.trainingPairCount && ...
            size(S.archiveInfeasibleObjs,1) == S.trainingPairCount && ...
            all(sum(max(0,S.archiveFeasibleCons),2) <= 0) && ...
            all(sum(max(0,S.archiveInfeasibleCons),2) > 0), ...
            'A snapshot has malformed or mislabeled active pair endpoints.');
    end
    Audit = Observed.guideExperimentSnapshot();
    assert(Audit.pairInitialEpoch == 2 && ...
        Audit.pairRetrainEpoch == 1 && Audit.nCritic == 2 && ...
        ~isempty(Audit.pairTrainingLog) && ...
        Audit.pairTrainingLog(1).kind == "initial" && ...
        Audit.pairTrainingLog(1).epochs == 2 && ...
        isfinite(Audit.pairTrainingLog(1).postAllEndpointRMSE) && ...
        isfinite(Audit.pairTrainingLog(1).postPairDifferenceRMSE) && ...
        isfinite(Audit.pairTrainingLog(1).postSameConditionThickness) && ...
        all([Audit.pairTrainingLog(2:end).epochs] == 1));
    assert(max(abs(Audit.checkpointTargets-(800:800:8000))) <= 1e-9 && ...
        numel(Audit.checkpointFE) == 10 && ...
        all(isfinite(Audit.checkpointFE)) && ...
        all(Audit.checkpointFE >= Audit.checkpointTargets) && ...
        Audit.checkpointFE(end) == 8000, ...
        'The 10%%--100%% checkpoint schedule is incomplete.');
    checkpointFields = {'checkpointPairActive', ...
        'checkpointPairGapMedian','checkpointPairGapP90', ...
        'checkpointPairArchiveAdded','checkpointPairTightenedFeasible', ...
        'checkpointPairTightenedInfeasible', ...
        'checkpointPairGuidedTightened','checkpointPairTrainingEvents', ...
        'checkpointPairGenerationEvents','checkpointPairUseEvents', ...
        'checkpointPairDonors','checkpointPairFallback', ...
        'checkpointPairObjectiveFE'};
    for i = 1 : numel(checkpointFields)
        assert(numel(Audit.(checkpointFields{i})) == 10, ...
            'A PairGuide checkpoint series has the wrong length.');
    end
    cumulativeFields = {'checkpointPairArchiveAdded', ...
        'checkpointPairTightenedFeasible', ...
        'checkpointPairTightenedInfeasible', ...
        'checkpointPairGuidedTightened','checkpointPairTrainingEvents', ...
        'checkpointPairGenerationEvents','checkpointPairUseEvents', ...
        'checkpointPairDonors','checkpointPairFallback', ...
        'checkpointPairObjectiveFE'};
    for i = 1 : numel(cumulativeFields)
        values = Audit.(cumulativeFields{i});
        assert(all(isfinite(values)) && all(values >= 0) && ...
            all(diff(values) >= 0), ...
            'A cumulative PairGuide checkpoint series decreased.');
    end
    finiteGap = isfinite(Audit.checkpointPairGapMedian) & ...
        isfinite(Audit.checkpointPairGapP90);
    assert(all(Audit.checkpointPairActive >= 0) && ...
        all(Audit.checkpointPairGapMedian(finiteGap) >= 0) && ...
        all(Audit.checkpointPairGapP90(finiteGap) >= ...
            Audit.checkpointPairGapMedian(finiteGap)), ...
        'Checkpoint pair counts or gap quantiles are invalid.');

    assert(~isempty(Audit.pairArchiveLog) && ...
        ~isempty(Audit.pairGenerationLog) && ...
        ~isempty(Audit.pairUseLog), ...
        'Compact PairGuide event logs are missing.');
    ArchiveLog = Audit.pairArchiveLog;
    assert(all(isfinite([ArchiveLog.fe])) && ...
        sum([ArchiveLog.added]) == Audit.pairArchiveAdded && ...
        sum([ArchiveLog.tightenedFeasible]) == ...
            Audit.pairArchiveTightenedFeasible && ...
        sum([ArchiveLog.tightenedInfeasible]) == ...
            Audit.pairArchiveTightenedInfeasible && ...
        sum([ArchiveLog.guidedTightenedFeasible]) == ...
            Audit.pairGuidedTightenedFeasible && ...
        sum([ArchiveLog.guidedTightenedInfeasible]) == ...
            Audit.pairGuidedTightenedInfeasible, ...
        'Archive event logs disagree with cumulative counters.');
    GenerationLog = Audit.pairGenerationLog;
    assert(all([GenerationLog.rawCount] == 500) && ...
        isequal([GenerationLog.rawCount], ...
            [GenerationLog.invalidCount]+[GenerationLog.matchFailures]+ ...
            [GenerationLog.sphereRejectCount]+ ...
            [GenerationLog.spherePassCount]) && ...
        all([GenerationLog.objectiveCandidateCount] <= ...
            [GenerationLog.spherePassCount]) && ...
        all([GenerationLog.objectiveCandidateCount] <= 40) && ...
        all([GenerationLog.jointPassCount] <= ...
            [GenerationLog.objectiveCandidateCount]) && ...
        all([GenerationLog.keptCount] <= [GenerationLog.jointPassCount]) && ...
        all([GenerationLog.keptCount] <= 20) && ...
        isequal([GenerationLog.objectiveFE], ...
            [GenerationLog.objectiveCandidateCount]), ...
        'A raw-to-donor funnel log violates its count bounds.');
    UseLog = Audit.pairUseLog;
    assert(all([UseLog.selected]+[UseLog.fallback] == ...
            [UseLog.requested]) && ...
        all([UseLog.feasible] <= [UseLog.selected]) && ...
        all([UseLog.dominating] <= [UseLog.selected]) && ...
        all([UseLog.feasibleDominating] <= [UseLog.selected]) && ...
        all([UseLog.survivedP1] <= [UseLog.selected]) && ...
        isequal([UseLog.fe],[UseLog.useFE]), ...
        'A donor-to-child use log violates its count bounds.');
    linked = isfinite([UseLog.poolFE]);
    assert(all([UseLog(linked).poolFE] < [UseLog(linked).useFE]), ...
        'A use event is not linked to an earlier generated pool.');
    fprintf('PairGuide formal observation smoke test passed.\n');

    function recordMetric(Algorithm,Problem)
        savedFE = Problem.FE;
        savedRNG = rng;
        cleanup = onCleanup(@()restoreSearchState( ...
            Problem,savedFE,savedRNG));
        Population = Algorithm.result{end,2};
        if isempty(metricFE) || metricFE(end) ~= Problem.FE
            metricFE(end+1,1) = double(Problem.FE);
            metricIGD(end+1,1) = double( ...
                Problem.CalMetric('IGD',Population));
            feasibleCount(end+1,1) = nnz(all(Population.cons <= 0,2));
        end
        clear cleanup;
    end
end

function restoreSearchState(Problem,FE,RNG)
%RESTORESEARCHSTATE Keep diagnostic callbacks behavior neutral.

    Problem.FE = FE;
    rng(RNG);
end

function silentOutput(~,~)
end
