classdef CBS_RegionWGAN_GP < CBS_RegionGAN_Base
    % <multi> <real> <constrained>
    % Region-conditioned boundary WGAN-GP mainline.
    % The sole query policy allocates round(nGen/6) samples to one-hop
    % unsupported frontier references and the remainder to populated refs.
%
% trainGap --- 1 --- WGAN retraining interval in generations
% archiveGap --- 1 --- Boundary-cloud refresh interval in generations
% nGen --- 30 --- Maximum generated offspring evaluated per refresh
% zDim --- 6 --- Latent dimension (noise z, sampled N(0,sigma))
% sampleSigma --- 0.3 --- Sampling-only latent noise scale
% ganIter --- 100 --- Generator update iterations per refresh
% ganMiniBatch --- 32 --- WGAN mini-batch size
% ganLrD --- 0.0001 --- Critic learning rate
% ganLrG --- 0.0001 --- Generator learning rate
% frontDepth --- 2 --- Feasible objective-space fronts kept as cloud anchors
% pairNeighborRefRadius --- 2 --- Coarse-region neighborhood radius for pairing
% refDivisor --- 2 --- Coarse references = round(N/refDivisor)
% minBoundaryLength --- 2 --- Minimum cloud size kept by the gap cap
% gpLambda --- 10 --- WGAN-GP gradient penalty coefficient
% nCritic --- 2 --- Critic updates per generator update
% maxAnchorsPerRef --- 5 --- Max feasible front anchors retained per region
% minGANTrainCount --- 32 --- Minimum TrainX rows required to train/sample GAN

    methods
        function Algorithm = CBS_RegionWGAN_GP(varargin)
            Algorithm@CBS_RegionGAN_Base(varargin{:});
        end

        function main(Algorithm,Problem)
            Defaults = CBS_RegionWGAN_GP.mainlineDefaults();
            [trainGap,archiveGap,nGen,zDim,ganIter,ganMiniBatch, ...
                ganLrD,ganLrG,frontDepth,pairNeighborRefRadius, ...
                refDivisor,minBoundaryLength,gpLambda,nCritic, ...
                maxAnchorsPerRef,minGANTrainCount] = ...
                Algorithm.ParameterSet( ...
                Defaults.trainGap, ...
                Defaults.archiveGap, ...
                Defaults.nGen, ...
                Defaults.zDim, ...
                Defaults.ganIter, ...
                Defaults.ganMiniBatch, ...
                Defaults.ganLrD, ...
                Defaults.ganLrG, ...
                Defaults.frontDepth, ...
                Defaults.pairNeighborRefRadius, ...
                Defaults.refDivisor, ...
                Defaults.minBoundaryLength, ...
                Defaults.gpLambda, ...
                Defaults.nCritic, ...
                Defaults.maxAnchorsPerRef, ...
                Defaults.minGANTrainCount);
            Config = struct( ...
                'trainGap',trainGap, ...
                'archiveGap',archiveGap, ...
                'nGen',nGen, ...
                'zDim',zDim, ...
                'ganIter',ganIter, ...
                'ganMiniBatch',ganMiniBatch, ...
                'ganLrD',ganLrD, ...
                'ganLrG',ganLrG, ...
                'frontDepth',frontDepth, ...
                'pairNeighborRefRadius',pairNeighborRefRadius, ...
                'refDivisor',refDivisor, ...
                'minBoundaryLength',minBoundaryLength, ...
                'maxAnchorsPerRef',maxAnchorsPerRef, ...
                'minGANTrainCount',minGANTrainCount, ...
                'sampleSigma',Defaults.sampleSigma, ...
                'gpLambda',gpLambda, ...
                'nCritic',nCritic);
            Algorithm.runRegionGAN(Problem,Config);
        end
    end

    methods(Static)
        function Defaults = mainlineDefaults()
        %MAINLINEDEFAULTS Validated RegionGAN WGAN-GP mainline parameters.
            Defaults = struct( ...
                'trainGap',1, ...
                'archiveGap',1, ...
                'nGen',30, ...
                'zDim',6, ...
                'ganIter',100, ...
                'ganMiniBatch',32, ...
                'ganLrD',1e-4, ...
                'ganLrG',1e-4, ...
                'frontDepth',2, ...
                'pairNeighborRefRadius',2, ...
                'refDivisor',2, ...
                'minBoundaryLength',2, ...
                'gpLambda',10, ...
                'nCritic',2, ...
                'maxAnchorsPerRef',5, ...
                'minGANTrainCount',32, ...
                'sampleSigma',0.3);
        end
    end
end
