classdef CBS_RegionWGAN_GP < CBS_RegionGAN_Base
% <multi> <real> <constrained>
% Region-conditioned boundary WGAN-GP mainline.
%
% Fixed configuration: full warm-start, Batch32, 100 generator updates,
% nCritic4, trainGap1, and 32-by-32 generator/critic hidden layers.

    methods
        function Algorithm = CBS_RegionWGAN_GP(varargin)
            Algorithm@CBS_RegionGAN_Base(varargin{:});
        end

        function main(Algorithm,Problem)
            if ~isempty(Algorithm.parameter)
                error('CBSRegionGAN:FixedMainlineParameters', ...
                    ['CBS_RegionWGAN_GP has no tunable algorithm ', ...
                    'parameters; configure only the Problem and runner.']);
            end
            Algorithm.runRegionGAN(Problem, ...
                CBS_RegionWGAN_GP.mainlineDefaults());
        end
    end

    methods(Static)
        function Defaults = mainlineDefaults()
        %MAINLINEDEFAULTS Validated fixed mainline configuration.
            Defaults = struct( ...
                'trainGap',1, ...
                'archiveGap',1, ...
                'nGen',30, ...
                'zDim',6, ...
                'ganIter',100, ...
                'ganMiniBatch',32, ...
                'ganLrD',1e-4, ...
                'ganLrG',1e-4, ...
                'frontDepth',2, ...
                'pairNeighborRefRadius',2, ...
                'refDivisor',2, ...
                'minBoundaryLength',2, ...
                'gpLambda',10, ...
                'nCritic',4, ...
                'maxAnchorsPerRef',5, ...
                'minGANTrainCount',32, ...
                'sampleSigma',0.3, ...
                'generatorHidden',[32 32], ...
                'criticHidden',[32 32]);
        end
    end
end
