classdef CBS_RegionCGAN < CBS_RegionGAN_Base
% <multi> <real> <constrained>
% Region-conditioned boundary CGAN control branch.
% Learns p(decision | coarse objective region) with random z and the
% original BCE/sigmoid CGAN loss. This is the control branch for comparing
% against CBS_RegionWGAN_GP; the boundary cloud and region dataset are shared.
%
% trainGap --- 1 --- CGAN retraining interval in generations
% archiveGap --- 1 --- Boundary-cloud refresh interval in generations
% nGen --- 30 --- Maximum generated offspring evaluated per refresh
% zDim --- 6 --- Latent dimension (noise z, sampled N(0,sigma))
% ganIter --- 50 --- CGAN training iterations per refresh
% ganMiniBatch --- 32 --- CGAN mini-batch size
% ganLrD --- 0.0001 --- Discriminator learning rate
% ganLrG --- 0.0001 --- Generator learning rate
% frontDepth --- 2 --- Feasible objective-space fronts kept as cloud anchors
% pairNeighborRefRadius --- 2 --- Coarse-region neighborhood radius for pairing
% refDivisor --- 2 --- Coarse references = round(N/refDivisor)
% minBoundaryLength --- 2 --- Minimum cloud size kept by the gap cap
% queryPerCondition --- 2 --- Maximum random-z samples per populated region
% conditionDiagGap --- 10 --- Condition-control diagnostic interval
% conditionDiagMaxConditions --- 8 --- Max query regions probed per diagnostic
% conditionDiagZSamples --- 8 --- Latent samples per diagnostic condition
% conditionDiagAllWZPerRef --- 2 --- Diagnostic-only samples per reference
% maxAnchorsPerRef --- 5 --- Max feasible front anchors retained per region
% minGANTrainCount --- 32 --- Minimum TrainX rows required to train/sample GAN

    methods
        function Algorithm = CBS_RegionCGAN(varargin)
            Algorithm@CBS_RegionGAN_Base(varargin{:});
        end

        function main(Algorithm,Problem)
            [trainGap,archiveGap,nGen,zDim,ganIter,ganMiniBatch, ...
                ganLrD,ganLrG,frontDepth,pairNeighborRefRadius, ...
                refDivisor,minBoundaryLength,queryPerCondition, ...
                conditionDiagGap,conditionDiagMaxConditions, ...
                conditionDiagZSamples,conditionDiagAllWZPerRef, ...
                maxAnchorsPerRef,minGANTrainCount] = ...
                Algorithm.ParameterSet( ...
                1,1,30,6,50,32,1e-4,1e-4,2,2,2,2,2,10,8,8,2,5,32);
            Config = struct( ...
                'trainGap',trainGap, ...
                'archiveGap',archiveGap, ...
                'nGen',nGen, ...
                'zDim',zDim, ...
                'ganIter',ganIter, ...
                'ganMiniBatch',ganMiniBatch, ...
                'ganLrD',ganLrD, ...
                'ganLrG',ganLrG, ...
                'frontDepth',frontDepth, ...
                'pairNeighborRefRadius',pairNeighborRefRadius, ...
                'refDivisor',refDivisor, ...
                'minBoundaryLength',minBoundaryLength, ...
                'queryPerCondition',queryPerCondition, ...
                'conditionDiagGap',conditionDiagGap, ...
                'conditionDiagMaxConditions',conditionDiagMaxConditions, ...
                'conditionDiagZSamples',conditionDiagZSamples, ...
                'conditionDiagAllWZPerRef',conditionDiagAllWZPerRef, ...
                'maxAnchorsPerRef',maxAnchorsPerRef, ...
                'minGANTrainCount',minGANTrainCount, ...
                'gpLambda',NaN, ...
                'nCritic',NaN);
            Algorithm.runRegionGAN(Problem,"cgan",Config);
        end
    end
end
