function test_CBS_region_training_diagnostics_domain_plot_default()
%TEST_CBS_REGION_TRAINING_DIAGNOSTICS_DOMAIN_PLOT_DEFAULT Verify domain plots.

    repoRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
    addpath(genpath(repoRoot));

    sourceFile = fullfile(repoRoot,'Algorithms', ...
        'Multi-objective optimization','CBS-CGAN','Support', ...
        'run_CBS_RegionCGAN_training_diagnostics.m');
    sourceText = fileread(sourceFile);
    assert(~contains(sourceText,'Infeasible samples'), ...
        'Diagnostics plotter must not contain the samples-background branch.');
    assert(~contains(sourceText,'Feasible samples'), ...
        'Diagnostics plotter must not contain the samples-background branch.');
    assert(~contains(sourceText,'CGAN generated'), ...
        'Diagnostics plotter must use the domain-background GAN label.');

    outDir = fullfile(tempdir,sprintf('cbs_region_diag_domain_plot_%s', ...
        char(java.util.UUID.randomUUID)));
    opts = struct( ...
        'algorithmClass',"CBS_RegionWGAN_GP", ...
        'queryMode',"boundary_populated", ...
        'prevBMemMode',"prev1_fair_union", ...
        'plotRun',1, ...
        'captureRun',1, ...
        'drawFigures',true, ...
        'stageTargets',200, ...
        'algorithmParams',{{1,1,2,2,1,8,1e-4,1e-4,2,2,2,2,1,10,1,4,1}}, ...
        'sampleZMode',"random", ...
        'trainZMode',"random", ...
        'sigma',1.0);
    [Summary,~,~,~,Figures,Stages] = ...
        run_CBS_RegionCGAN_training_diagnostics(outDir,1, ...
        "DASCMOP1_BC",20,[],300,1,opts);

    assert(height(Summary) == 1 && Summary.status == "ok", ...
        'Diagnostics smoke run must finish successfully.');
    assert(height(Stages) == 1, ...
        'Diagnostics smoke run must capture one stage snapshot.');
    assert(height(Figures) == 1, ...
        'Diagnostics smoke run must produce one figure.');
    figureFile = char(Figures.figure_file(1));
    assert(contains(figureFile,'_domain_boundary.png'), ...
        'Diagnostics default plot filename must identify domain-background figures.');
    assert(isfile(figureFile), ...
        'Diagnostics domain-background figure must exist.');

    fprintf('CBS RegionGAN diagnostics domain plot default passed: %s\n', ...
        figureFile);
end
