function test_CBS_region_query_group_diagnostics()
%TEST_CBS_REGION_QUERY_GROUP_DIAGNOSTICS Verify query group classification.

    repoRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
    addpath(genpath(repoRoot));

    testOffspringSurvivalMasksConsumeDuplicateRows();
    testQueryGroupDiagnosticsExposeCountsAndGeometry();
    testQueryGroupDiagnosticsReturnNaNForEmptyGroups();
    testQueryGroupDiagnosticsRejectInvalidInputs();
    testObjectiveRefAssignmentUsesDatasetScale();
    testMatchedFrontierDiagnosticsStayOnSameRef();
    testMatchedFrontierDiagnosticsHandleNoFrontier();
    testMatchedFrontierRefEqualMetricsIgnoreSampleImbalance();
    testSolutionHandleSurvivalSeparatesIdenticalSourceDecisions();
    testMatchedFrontierDiagnosticsRejectInvalidRows();
    fprintf('CBS region query-group diagnostics passed.\n');
end

function testOffspringSurvivalMasksConsumeDuplicateRows()
    GDec = [0 0;0 0;1 1];
    P1 = [0 0;1 1];
    P2 = [0 0];

    [InP1,InP2,InUnion] = RunRegionGAN_RC( ...
        'offspringgsurvivalmasks',GDec,P1,P2);

    assert(isequal(InP1,[true;false;true]), ...
        'P1 survival masks must consume duplicate selected rows once.');
    assert(isequal(InP2,[true;false;false]), ...
        'P2 survival masks must consume duplicate selected rows once.');
    assert(isequal(InUnion,[true;true;true]), ...
        'Union survival masks must match against the combined multiset.');
end

function testQueryGroupDiagnosticsExposeCountsAndGeometry()
    GeneratedObj = [0 0;0.25 0;0.5 0;0.75 0;1 0];
    GeneratedCon = [-1;1;-1;1;-1];
    Groups = [1;1;2;2;3];
    InP1 = logical([1;0;1;0;0]);
    InP2 = logical([0;1;0;1;0]);
    InUnion = InP1 | InP2;
    PF = GeneratedObj;

    Metrics = RunRegionGAN_RC('querygroupdiagnostics', ...
        GeneratedObj,GeneratedCon,Groups,InP1,InP2,InUnion,PF, ...
        struct('coverEpsilon',0.02));

    assert(Metrics.query_populated_sample_count == 2, ...
        'Populated diagnostics must count group-1 samples.');
    assert(Metrics.query_frontier_sample_count == 2, ...
        'Frontier diagnostics must count group-2 samples.');
    assert(Metrics.query_remote_sample_count == 1, ...
        'Remote diagnostics must count group-3 samples.');
    assert(Metrics.query_frontier_survive_P1_count == 1, ...
        'Frontier diagnostics must count P1 survivors from the supplied mask.');
    assert(isfinite(Metrics.query_frontier_bdist50_true), ...
        'Frontier true-boundary distance must use the existing geometry diagnostic.');
end

function testQueryGroupDiagnosticsReturnNaNForEmptyGroups()
    GeneratedObj = [0 0;0.5 0];
    GeneratedCon = [-1;1];
    Groups = ones(2,1);
    InP1 = logical([1;0]);
    InP2 = logical([0;1]);
    InUnion = true(2,1);
    PF = [0 0;0.5 0;1 0];

    Metrics = RunRegionGAN_RC('querygroupdiagnostics', ...
        GeneratedObj,GeneratedCon,Groups,InP1,InP2,InUnion,PF,struct());

    assert(Metrics.query_remote_sample_count == 0 && ...
            Metrics.query_remote_feasible_count == 0 && ...
            Metrics.query_remote_survive_P1_count == 0 && ...
            Metrics.query_remote_survive_P2_count == 0 && ...
            Metrics.query_remote_survive_union_count == 0, ...
        'Empty query groups must report zero counts.');
    EmptyRatesAndGeometry = [ ...
        Metrics.query_remote_feasible_rate, ...
        Metrics.query_remote_survive_P1_rate, ...
        Metrics.query_remote_survive_P2_rate, ...
        Metrics.query_remote_survive_union_rate, ...
        Metrics.query_remote_bdist50_true, ...
        Metrics.query_remote_bwidth90_10_true, ...
        Metrics.query_remote_bcover_eps_true];
    assert(all(isnan(EmptyRatesAndGeometry)), ...
        'Empty query groups must report NaN rates and geometry.');
end

function testQueryGroupDiagnosticsRejectInvalidInputs()
    GeneratedObj = [0 0;1 0];
    GeneratedCon = [-1;-1];
    ValidMasks = true(2,1);
    PF = GeneratedObj;
    Options = struct();

    assertThrowsIdentifier(@() RunRegionGAN_RC('querygroupdiagnostics', ...
        GeneratedObj,GeneratedCon,1,ValidMasks,ValidMasks,ValidMasks, ...
        PF,Options),'CBSRegionGAN:BadQueryGroupRows');
    assertThrowsIdentifier(@() RunRegionGAN_RC('querygroupdiagnostics', ...
        GeneratedObj,GeneratedCon,[1;4],ValidMasks,ValidMasks,ValidMasks, ...
        PF,Options),'CBSRegionGAN:BadQueryGroupCode');
    assertThrowsIdentifier(@() RunRegionGAN_RC('querygroupdiagnostics', ...
        GeneratedObj,GeneratedCon,[1;2],true,ValidMasks,ValidMasks, ...
        PF,Options),'CBSRegionGAN:BadQueryMaskRows');
end

function testObjectiveRefAssignmentUsesDatasetScale()
    W = [1 0;0.75 0.25;0.5 0.5;0.25 0.75;0 1];
    ObjMin = [10 -4];
    ObjSpan = [2 5];
    ObjN = W([1;3;5],:);
    Obj = ObjMin + ObjN.*ObjSpan;
    Refs = RunRegionGAN_RC('assignobjectivequeryrefs', ...
        Obj,W,ObjMin,ObjSpan);
    assert(isequal(Refs,[1;3;5]), ...
        'Objective ref assignment must use the supplied dataset scale.');
end

function testMatchedFrontierDiagnosticsStayOnSameRef()
    W = [1 0;0.75 0.25;0.5 0.5;0.25 0.75;0 1];
    PF = W;
    GAN = struct( ...
        'obj',W([2;3],:), ...
        'con',[-1;1], ...
        'ref',[2;3], ...
        'group',[2;2], ...
        'survive_P1',logical([1;0]), ...
        'survive_P2',logical([0;1]), ...
        'survive_union',true(2,1));
    DE = struct( ...
        'obj',[W(2,:);W(2,:) + [0.01 -0.01];W(5,:)], ...
        'con',[-1;1;-1], ...
        'ref',[2;2;5], ...
        'survive_P1',logical([1;0;1]), ...
        'survive_P2',logical([0;1;0]), ...
        'survive_union',true(3,1));

    M = RunRegionGAN_RC('matchedfrontierdiagnostics', ...
        GAN,DE,PF,struct('coverEpsilon',0.02));
    assert(M.frontier_query_ref_count == 2 && ...
            M.frontier_matched_de_available_ref_count == 1 && ...
            M.frontier_matched_de_unavailable_ref_count == 1, ...
        'Only one of the two queried frontier refs has same-ref DE support.');
    assert(M.frontier_matched_gan_sample_count == 1 && ...
            M.frontier_matched_de_sample_count == 2, ...
        'Matched subsets must include only the shared ref and never ref 5.');
    assert(M.frontier_matched_de_feasible_count == 1 && ...
            M.frontier_matched_de_survive_P1_count == 1 && ...
            isfinite(M.frontier_matched_gan_bdist50_true) && ...
            isfinite(M.frontier_matched_de_bdist50_true), ...
        'Same-ref GAN and DE subsets must expose feasibility, survival, and geometry.');
end

function testMatchedFrontierDiagnosticsHandleNoFrontier()
    Empty = struct( ...
        'obj',zeros(0,2),'con',zeros(0,1),'ref',zeros(0,1), ...
        'group',zeros(0,1),'survive_P1',false(0,1), ...
        'survive_P2',false(0,1),'survive_union',false(0,1));
    M = RunRegionGAN_RC('matchedfrontierdiagnostics', ...
        Empty,rmfield(Empty,'group'),zeros(0,2),struct());
    assert(M.frontier_query_ref_count == 0 && ...
            M.frontier_matched_de_sample_count == 0 && ...
            isnan(M.frontier_matched_de_feasible_rate) && ...
            isnan(M.frontier_matched_de_bdist50_true), ...
        'No-frontier diagnostics must return stable zero/NaN fields.');
end

function testMatchedFrontierRefEqualMetricsIgnoreSampleImbalance()
    PF = [0 0];
    DE = struct( ...
        'obj',[0.1 0;0.3 0],'con',[-1;-1],'ref',[2;4], ...
        'survive_P1',true(2,1),'survive_P2',false(2,1), ...
        'survive_union',true(2,1));
    GAN1 = struct( ...
        'obj',[0 0;0.2 0],'con',[-1;-1],'ref',[2;4], ...
        'group',[2;2],'survive_P1',true(2,1), ...
        'survive_P2',false(2,1),'survive_union',true(2,1));
    GAN2 = GAN1;
    GAN2.obj = [repmat([0 0],9,1);0.2 0];
    GAN2.con = -ones(10,1);
    GAN2.ref = [2*ones(9,1);4];
    GAN2.group = 2*ones(10,1);
    GAN2.survive_P1 = true(10,1);
    GAN2.survive_P2 = false(10,1);
    GAN2.survive_union = true(10,1);

    M1 = RunRegionGAN_RC('matchedfrontierdiagnostics', ...
        GAN1,DE,PF,struct());
    M2 = RunRegionGAN_RC('matchedfrontierdiagnostics', ...
        GAN2,DE,PF,struct());
    assert(M1.frontier_matched_gan_sample_count == 2 && ...
            M2.frontier_matched_gan_sample_count == 10 && ...
            abs(M1.frontier_matched_gan_refeq_bdist50_true - ...
            M2.frontier_matched_gan_refeq_bdist50_true) <= 1e-12, ...
        'Ref-equal geometry must not change when one ref is duplicated.');
end

function testSolutionHandleSurvivalSeparatesIdenticalSourceDecisions()
    GAN = SOLUTION([0 0],[0 0],0);
    DE = SOLUTION([0 0],[0 0],0);
    [GanP1,~,GanUnion] = RunRegionGAN_RC( ...
        'offspringsurvivalhandlemasks',GAN,GAN,GAN([]));
    [DeP1,~,DeUnion] = RunRegionGAN_RC( ...
        'offspringsurvivalhandlemasks',DE,GAN,GAN([]));
    assert(GanP1 && GanUnion && ~DeP1 && ~DeUnion, ...
        'Identical decisions from different source handles must not share survival.');
end

function testMatchedFrontierDiagnosticsRejectInvalidRows()
    Good = struct( ...
        'obj',[0 0],'con',zeros(1,0),'ref',2,'group',2, ...
        'survive_P1',true,'survive_P2',false,'survive_union',true);
    BadCon = Good;
    BadCon.con = [];
    BadMask = rmfield(Good,'group');
    BadMask.survive_P1 = NaN;
    assertThrowsIdentifier(@() RunRegionGAN_RC( ...
        'matchedfrontierdiagnostics',BadCon,rmfield(Good,'group'), ...
        [0 0],struct()),'CBSRegionGAN:BadMatchedDataRows');
    assertThrowsIdentifier(@() RunRegionGAN_RC( ...
        'matchedfrontierdiagnostics',Good,BadMask,[0 0],struct()), ...
        'CBSRegionGAN:BadMatchedSurvivalMask');
end

function assertThrowsIdentifier(Call,ExpectedIdentifier)
    DidThrow = false;
    try
        Call();
    catch Error
        DidThrow = strcmp(Error.identifier,ExpectedIdentifier);
    end
    assert(DidThrow,'Expected error identifier %s.',ExpectedIdentifier);
end
