function test_CBS_region_wgan_mainline()
%TEST_CBS_REGION_WGAN_MAINLINE Verify the sole production algorithm.

    repoRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
    addCBSPaths(repoRoot);
    algorithmFile = which('CBS_RegionWGAN_GP');
    algorithmRoot = fileparts(algorithmFile);
    assert(exist('CBS_RegionWGAN_GP','class') == 8);
    companions = dir(fullfile(algorithmRoot,'CBS_RegionWGAN_GP_*.m'));
    assert(isempty(companions), ...
        'No experimental CBS_RegionWGAN_GP companion class may remain.');

    Defaults = CBS_RegionWGAN_GP.mainlineDefaults();
    assert(Defaults.nGen == 20 && Defaults.zDim == 6 && ...
        Defaults.ganIter == 100 && Defaults.ganMiniBatch == 32 && ...
        Defaults.nCritic == 4 && Defaults.minGANTrainCount == 32 && ...
        Defaults.sampleSigma == 0.3 && ...
        Defaults.ganStopFraction == 0.5 && ...
        Defaults.guideCandidatesPerSlot == 5 && ...
        Defaults.calibrationBudget == 20);

    source = string(fileread(algorithmFile));
    dataSource = string(fileread(which('BuildBoundaryDataset_RC')));
    querySource = string(fileread(which('RunRegionGAN_RC')));
    selectionSource = string(fileread(which('EnvironmentalSelection_CBS')));
    assert(contains(dataSource,'ones(numel(refs),1)') && ...
        contains(dataSource,'zeros(sum(keepI),1)'));
    assert(contains(source,'QueryC = [SampleC,ones') && ...
        contains(querySource,'0.3*totalBudget') && ...
        contains(source,'ladder = [0.4,0.65,0.85]') && ...
        contains(source,['Union = [Population1,Population2,', ...
            'Offspring1, ...']) && ...
        contains(selectionSource,'truncateByObjectiveDistance') && ...
        contains(selectionSource, ...
            'Distance = pairDistance(PopObj,PopObj);'));
    forbidden = ["operatorMode","p2Operator","generatorMode", ...
        "trainData","scoutMode","metricsMode","guideRecord", ...
        "guideMode","guideAlloc","guideSelect","blsWindow", ...
        "blsFeed","initDecs","criticscore","copynoise", ...
        "consensusshuffle","gapseed","guideFPolicy", ...
        "PlanGuideF_CBS","LateDifference","CutoffState", ...
        "pbestOrdinaryDE","randomGuideSlots"];
    sourceTree = source+newline+dataSource+newline+querySource+newline+ ...
        string(fileread(which('BoundaryWGAN_RC')));
    assert(~any(contains(sourceTree,forbidden)));
    Parameters = {0,7,50,8,5,9,0.2};
    Algorithm = CBS_RegionWGAN_GP('parameter',Parameters,'save',0, ...
        'outputFcn',@(varargin)[]);
    assert(isequal(Algorithm.parameter,Parameters));
    Problem = DASCMOP1_BC('N',10,'D',5,'maxFE',100);
    Algorithm.Solve(Problem);
    assert(Algorithm.result{end,1} == Problem.maxFE);
    testDistinctOrdinaryDE();
    testFrozenPathIsolation(repoRoot,algorithmFile);
    fprintf('CBS sole-mainline structure passed.\n');
end

function testFrozenPathIsolation(repoRoot,algorithmFile)
    frozenDir = fullfile(repoRoot,'Data', ...
        'CBS_bt0_vs_nobt_gate_source_snapshot','Algorithms', ...
        'Multi-objective optimization','CBS-CGAN','Experimental');
    if ~isfolder(frozenDir)
        return;
    end
    addpath(frozenDir,'-begin');
    assert(~isempty(which('CBS_RegionWGAN_GP_BT0F0')), ...
        'Frozen-source isolation fixture is not visible.');
    addCBSPaths(repoRoot);
    assert(isempty(which('CBS_RegionWGAN_GP_BT0F0')) && ...
        isempty(which('CBS_RegionWGAN_GP_NoBT')) && ...
        strcmp(which('CBS_RegionWGAN_GP'),algorithmFile), ...
        'addCBSPaths must expose only the live CBS mainline.');
end

function testDistinctOrdinaryDE()
    rng(73,'twister');
    Problem = DASCMOP1_BC('N',6,'D',5,'maxFE',20);
    Population = Problem.Initialization();
    Fitness = (1:numel(Population))';
    [Offspring,Parents] = OperatorDEDistinct_CBS( ...
        Problem,Population,Fitness,4,{1,0.5,0,20});

    assert(all(Parents(:,1) ~= Parents(:,2)) && ...
        all(Parents(:,1) ~= Parents(:,3)) && ...
        all(Parents(:,2) ~= Parents(:,3)));
    Decs = Population.decs;
    expected = Decs(Parents(:,1),:) + ...
        0.5*(Decs(Parents(:,2),:)-Decs(Parents(:,3),:));
    expected = min(max(expected,Problem.lower),Problem.upper);
    assert(isequal(Offspring.decs,expected));
end
