function test_CBS_region_boundary_populated_branch()
%TEST_CBS_REGION_BOUNDARY_POPULATED_BRANCH Verify exact-mainline query branch.

    repoRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
    addpath(genpath(repoRoot));

    runnerFile = fullfile(repoRoot,'Algorithms', ...
        'Multi-objective optimization','CBS-CGAN','Support', ...
        'run_CBS_RegionWGAN_GP_boundary_populated_branch.m');
    assert(isfile(runnerFile), ...
        'Boundary-populated exact-mainline runner must exist.');

    sourceText = string(fileread(runnerFile));
    requiredText = [ ...
        "C_query_boundary_populated", ...
        "'queryMode',""boundary_populated""", ...
        "'conditionMode',""region""", ...
        "'prevBMemMode',Defaults.prevBMemMode", ...
        "'bmemBandMode',Defaults.bmemBandMode", ...
        "'sampleSigma',Defaults.sampleSigma", ...
        "'ganIterSchedule',""fixed""", ...
        "'prescreenMultiplier',1", ...
        "'trainTriggerMode',""off""", ...
        "wganParams(Defaults,Overrides)", ...
        "Overrides.algorithmParams"];
    for i = 1 : numel(requiredText)
        assert(contains(sourceText,requiredText(i)), ...
            'Boundary-populated runner missing contract text: %s.', ...
            requiredText(i));
    end

    forbiddenText = [ ...
        "region_slocal", ...
        "region_rho", ...
        "trainGap2", ...
        "two_level_data_change", ...
        "prescreen8"];
    for i = 1 : numel(forbiddenText)
        assert(~contains(sourceText,forbiddenText(i)), ...
            'Boundary-populated runner must not mix in %s.', ...
            forbiddenText(i));
    end

    fprintf('CBS RegionWGAN-GP boundary-populated branch contract passed.\n');
end
