function test_CBS_region_condition_modes()
%TEST_CBS_REGION_CONDITION_MODES Verify local/radial region conditions.

    repoRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
    addpath(genpath(repoRoot));

    testSLocalConditionMode();
    testSLocalIgnoresPureRadialVariation();
    testRhoConditionMode();
    testRandomAllWUsesExtendedRegionConditions();
    testRandomAllWPreservesUniformRefSampling();
    testConditionAblationRunnerDefinesBranches();
    testConditionAblationRunnerSmokeWritesModeColumns();
    fprintf('CBS region condition mode regressions passed.\n');
end

function testSLocalConditionMode()
    [BMem,Samples,W,Problem,Options] = conditionModeFixture();
    Options.conditionMode = "region_slocal";

    [TrainX,TrainC,QueryC,~,Info] = BuildBoundaryDataset_RC( ...
        BMem,Samples,W,Problem,Options);

    assert(isequal(size(TrainX),[4 Problem.D]), ...
        'S-local mode must keep all valid boundary decisions.');
    assert(string(Info.condition_mode) == "region_slocal", ...
        'Dataset info must record the active condition mode.');
    assert(size(TrainC,2) == size(W,2) + 1, ...
        'S-local training conditions must append one scalar to W(ref,:).');
    assert(max(abs(TrainC(:,1:2) - W(BMem.ref,:)),[],'all') < 1e-12, ...
        'S-local mode must preserve the reference-direction prefix.');
    assert(max(abs(TrainC(:,3) - [0;0.5;1;0.5])) < 1e-12, ...
        'S-local scalar must be a per-ref local [0,1] coordinate.');
    assert(isequal(size(QueryC),[3 3]), ...
        'S-local populated query set must use two bins for multi-point refs and one for singleton refs.');
    assert(max(abs(QueryC(:,3) - [0.25;0.75;0.5])) < 1e-12, ...
        'S-local query scalars must cover the observed local support.');
    assert(isfield(Info,'allQueryConditions') && ...
            size(Info.allQueryConditions,2) == 3, ...
        'S-local mode must expose all-ref query conditions for random_all_w sampling.');
end

function testSLocalIgnoresPureRadialVariation()
    Problem = struct('D',2,'M',2);
    W = [0.5 0.5];
    BMem = struct();
    BMem.x_b = [0 0;1 0;2 0];
    BMem.y_b = [0 0;1 1;2 2];
    BMem.ref = [1;1;1];
    Samples = struct('objs',BMem.y_b);
    Options = struct( ...
        'conditionMode',"region_slocal", ...
        'conditionScale',struct('objMin',[0 0],'objSpan',[2 2]));

    [~,TrainC,QueryC] = BuildBoundaryDataset_RC( ...
        BMem,Samples,W,Problem,Options);

    assert(max(abs(TrainC(:,3) - 0.5)) < 1e-12, ...
        'S-local must not encode pure radial variation already represented by W/rho.');
    assert(isequal(size(QueryC),[1 3]) && abs(QueryC(1,3) - 0.5) < 1e-12, ...
        'Pure radial refs must expose one neutral local query position.');
end

function testRhoConditionMode()
    [BMem,Samples,W,Problem,Options] = conditionModeFixture();
    Options.conditionMode = "region_rho";

    [~,TrainC,QueryC,~,Info] = BuildBoundaryDataset_RC( ...
        BMem,Samples,W,Problem,Options);

    assert(string(Info.condition_mode) == "region_rho", ...
        'Dataset info must record the active radial condition mode.');
    assert(size(TrainC,2) == size(W,2) + 1, ...
        'Rho training conditions must append one scalar to W(ref,:).');
    assert(max(abs(TrainC(:,3) - [0;0.5;1;0.75])) < 1e-12, ...
        'Rho scalar must be the normalized projection along the reference direction.');
    assert(max(abs(QueryC(:,3) - [0.25;0.75;0.75])) < 1e-12, ...
        'Rho query scalars must stay inside the observed per-ref radial range.');
    assert(any(Info.allQueryRegions == 3) && ...
            any(abs(Info.allQueryConditions(Info.allQueryRegions == 3,3) - 0.5) < 1e-12), ...
        'Rho all-ref queries must give unpopulated refs a neutral scalar.');
end

function testRandomAllWUsesExtendedRegionConditions()
    [BMem,Samples,W,Problem,Options] = conditionModeFixture();
    Options.conditionMode = "region_slocal";
    [~,~,QueryC,~,Info] = BuildBoundaryDataset_RC( ...
        BMem,Samples,W,Problem,Options);

    rng(123,'twister');
    [SampleC,Counts,SampleRefs,DiagQueryC,DiagQueryRefs] = ...
        RunRegionGAN_RC('regionquerysamples',"random_all_w", ...
        QueryC,Info,W,2,6);

    assert(isequal(size(SampleC),[6 3]), ...
        'random_all_w must sample the full extended condition dimension.');
    assert(numel(Counts) == size(Info.allQueryConditions,1), ...
        'random_all_w counts must map to the all-ref extended query pool.');
    assert(isequal(DiagQueryC,Info.allQueryConditions), ...
        'random_all_w diagnostics must expose the extended all-ref query pool.');
    assert(isequal(DiagQueryRefs,Info.allQueryRegions), ...
        'random_all_w diagnostics must keep refs aligned with all-ref conditions.');
    assert(all(ismember(SampleRefs,[1;2;3])), ...
        'random_all_w sample refs must be drawn from the all-ref query pool.');
end

function testRandomAllWPreservesUniformRefSampling()
    Info = struct();
    Info.allQueryConditions = [ ...
        1 0 0.25; ...
        1 0 0.75; ...
        0 1 0.50; ...
        0.5 0.5 0.50];
    Info.allQueryRegions = [1;1;2;3];
    QueryC = Info.allQueryConditions(1:2,:);
    W = [1 0;0 1;0.5 0.5];

    rng(917,'twister');
    [~,~,SampleRefs] = RunRegionGAN_RC('regionquerysamples', ...
        "random_all_w",QueryC,Info,W,2,3000);

    RefCounts = accumarray(SampleRefs,1,[3 1],@sum,0);
    RefRates = RefCounts./sum(RefCounts);
    assert(max(abs(RefRates - 1/3)) < 0.05, ...
        'random_all_w with scalar bins must sample refs uniformly before choosing a scalar bin.');
end

function testConditionAblationRunnerDefinesBranches()
    repoRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
    runnerFile = fullfile(repoRoot,'Algorithms', ...
        'Multi-objective optimization','CBS-CGAN','Support', ...
        'run_CBS_RegionWGAN_GP_condition_true_boundary_branches.m');
    assert(isfile(runnerFile), ...
        'Condition true-boundary runner must exist for C/control/s_local/rho comparison.');
    sourceText = fileread(runnerFile);
    required = [ ...
        "C_control_region", ...
        "C_region_slocal", ...
        "C_region_rho", ...
        "conditionMode", ...
        "region_slocal", ...
        "region_rho", ...
        "bdist50_true", ...
        "bwidth90_10_true"];
    for i = 1 : numel(required)
        assert(contains(sourceText,required(i)), ...
            'Condition true-boundary runner missing required token: %s.', ...
            required(i));
    end
end

function testConditionAblationRunnerSmokeWritesModeColumns()
    outDir = fullfile(tempdir,sprintf('cbs_condition_runner_smoke_%s', ...
        char(java.util.UUID.randomUUID)));
    Params = {1,1,3,4,1,8,1e-4,1e-4,2,2,2,2,1,10,1,4,2};
    Overrides = struct( ...
        'stageTargets',220, ...
        'branchNames',["C_region_slocal","C_region_rho"], ...
        'algorithmParams',{Params}, ...
        'captureRun',1, ...
        'plotRun',0, ...
        'drawFigures',false);

    BranchSummary = run_CBS_RegionWGAN_GP_condition_true_boundary_branches( ...
        outDir,1,"DASCMOP1_BC",20,[],600,1,Overrides);

    assert(height(BranchSummary) == 2 && ...
            all(string(BranchSummary.status) == "ok"), ...
        'Condition runner smoke must complete selected branches.');
    EventSummary = collectBranchTable(outDir,BranchSummary.branch, ...
        'event_summary_all.csv');
    StageSummary = collectBranchTable(outDir,BranchSummary.branch, ...
        'stage_snapshots_all.csv');
    assert(all(ismember(["condition_mode","bdist50_true", ...
        "bwidth90_10_true"],string(EventSummary.Properties.VariableNames))), ...
        'Condition runner event summary must include mode and true-boundary fields.');
    assert(all(ismember(["condition_mode","bdist50_true", ...
        "bwidth90_10_true"],string(StageSummary.Properties.VariableNames))), ...
        'Condition runner stage summary must include mode and true-boundary fields.');
    assert(all(ismember(["region_slocal","region_rho"], ...
        unique(string(EventSummary.condition_mode)))), ...
        'Condition runner event summary must contain both selected condition modes.');
end

function T = collectBranchTable(rootDir,branches,fileName)
    T = table();
    branches = string(branches(:));
    for i = 1 : numel(branches)
        file = fullfile(rootDir,char(branches(i)),fileName);
        Part = readtable(file,'TextType','string');
        T = [T;Part]; %#ok<AGROW>
    end
end

function [BMem,Samples,W,Problem,Options] = conditionModeFixture()
    Problem = struct('D',2,'M',2);
    W = [1 0;0 1;0.5 0.5];
    BMem = struct();
    BMem.x_b = [0 0;1 0;2 0;0 1];
    BMem.y_b = [0 0;1 1;2 2;0 3];
    BMem.ref = [1;1;1;2];
    Samples = struct('objs',[BMem.y_b;2 4]);
    Options = struct('conditionScale',struct( ...
        'objMin',[0 0], ...
        'objSpan',[2 4]));
end
