function test_CBS_region_query_tracker()
%TEST_CBS_REGION_QUERY_TRACKER Verify cross-generation query attribution.

    repoRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
    addpath(genpath(repoRoot));

    testRefConversionAndDirectEntryStayDistinct();
    testRefConversionDoesNotRequireDirectGANMatch();
    testNonSurvivingGANDecisionCannotEnterDirectly();
    testRepeatedAndDuplicateBMemRowsAreMultisetSafe();
    testPopulatedSamplesAreExcludedFromRefExposure();
    testRepeatedExposureKeepsFirstQueryAndAccumulatesCounts();
    testEmptyAndInvalidInputs();
    fprintf('CBS region query tracker regressions passed.\n');
end

function testRefConversionAndDirectEntryStayDistinct()
    S = RegionQueryTracker_RC('init',2);
    [S,Event] = RegionQueryTracker_RC('register',S,3,1000, ...
        [2;3],[2;2],[0.1 0.2;0.3 0.4], ...
        logical([1;0]),logical([0;1]));
    assert(Event.ref_exposure_count == 2 && ...
            Event.eligible_sample_count == 2, ...
        'Register must report two ref exposures and two survivor-eligible samples.');

    [S,Update] = RegionQueryTracker_RC('updatebmem',S,5,1400, ...
        struct('ref',[2;4],'x_b',[0.1 0.2;0.8 0.9]));
    assert(Update.ref_conversion_count == 1, ...
        'Ref 2 must convert independently of decision attribution.');
    assert(Update.direct_bmem_entry_count == 1, ...
        'The surviving GAN decision must be attributed as a direct entry.');
    assert(Update.ref_conversion_lag_gen(1) == 2 && ...
            Update.ref_conversion_lag_fe(1) == 400, ...
        'Ref conversion lag must use first query generation and FE.');
    assert(Update.direct_bmem_entry_lag_gen(1) == 2 && ...
            Update.direct_bmem_entry_lag_fe(1) == 400, ...
        'Direct-entry lag must use the originating GAN event.');

    X = RegionQueryTracker_RC('export',S);
    assert(X.direct_entries(1).query_ref == 2 && ...
            X.direct_entries(1).query_group == 2 && ...
            X.direct_entries(1).survive_P1 == 1 && ...
            X.direct_entries(1).survive_P2 == 0, ...
        'Direct entry must retain query and P1/P2 attribution.');
end

function testRefConversionDoesNotRequireDirectGANMatch()
    S = RegionQueryTracker_RC('init',2);
    [S,~] = RegionQueryTracker_RC('register',S,1,100,5,2, ...
        [0.2 0.3],false,false);
    [~,Update] = RegionQueryTracker_RC('updatebmem',S,2,200, ...
        struct('ref',5,'x_b',[0.9 0.9]));
    assert(Update.ref_conversion_count == 1 && ...
            Update.direct_bmem_entry_count == 0, ...
        'Ref conversion must not be reported as direct GAN contribution.');
end

function testNonSurvivingGANDecisionCannotEnterDirectly()
    S = RegionQueryTracker_RC('init',2);
    [S,~] = RegionQueryTracker_RC('register',S,1,100,7,2, ...
        [0.25 0.75],false,false);
    [~,Update] = RegionQueryTracker_RC('updatebmem',S,2,200, ...
        struct('ref',9,'x_b',[0.25 0.75]));
    assert(Update.direct_bmem_entry_count == 0, ...
        'A GAN decision that entered neither population is ineligible.');
end

function testRepeatedAndDuplicateBMemRowsAreMultisetSafe()
    S = RegionQueryTracker_RC('init',2);
    Dec = [0.4 0.6;0.4 0.6];
    [S,Event] = RegionQueryTracker_RC('register',S,2,300, ...
        [4;4],[2;2],Dec,true(2,1),false(2,1));
    assert(numel(unique(Event.sample_id)) == 2, ...
        'Duplicate generated decisions must keep distinct sample IDs.');

    [S,U1] = RegionQueryTracker_RC('updatebmem',S,3,400, ...
        struct('ref',4,'x_b',[0.4 0.6]));
    [S,U2] = RegionQueryTracker_RC('updatebmem',S,4,500, ...
        struct('ref',4,'x_b',[0.4 0.6]));
    [S,U3] = RegionQueryTracker_RC('updatebmem',S,5,600, ...
        struct('ref',[4;4],'x_b',Dec));
    assert(U1.direct_bmem_entry_count == 1, ...
        'One BMem row may consume only one duplicate GAN sample.');
    assert(U2.direct_bmem_entry_count == 0, ...
        'A persistent BMem row must not be counted again next generation.');
    assert(U3.direct_bmem_entry_count == 1, ...
        'A newly observed second duplicate BMem row may consume the second sample.');

    X = RegionQueryTracker_RC('export',S);
    assert(numel(X.direct_entries) == 2 && ...
            numel(unique([X.direct_entries.sample_id])) == 2, ...
        'Each eligible duplicate sample may enter BMem at most once.');
end

function testPopulatedSamplesAreExcludedFromRefExposure()
    S = RegionQueryTracker_RC('init',2);
    [S,~] = RegionQueryTracker_RC('register',S,1,100, ...
        [1;2;3],[1;2;3],[0.1 0.1;0.2 0.2;0.3 0.3], ...
        true(3,1),false(3,1));
    X = RegionQueryTracker_RC('export',S);
    assert(numel(X.ref_exposure) == 2 && ...
            isequal(sort([X.ref_exposure.group]),[2 3]), ...
        'Only frontier and remote groups may create ref exposures.');

    [~,U] = RegionQueryTracker_RC('updatebmem',S,2,200, ...
        struct('ref',1,'x_b',[0.1 0.1]));
    assert(U.ref_conversion_count == 0 && U.direct_bmem_entry_count == 1, ...
        'A populated GAN sample may enter directly but is not a ref conversion exposure.');
end

function testRepeatedExposureKeepsFirstQueryAndAccumulatesCounts()
    S = RegionQueryTracker_RC('init',2);
    [S,~] = RegionQueryTracker_RC('register',S,2,200, ...
        [8;8],[2;2],[0.1 0.2;0.2 0.3],false(2,1),false(2,1));
    [S,~] = RegionQueryTracker_RC('register',S,4,500, ...
        8,2,[0.3 0.4],false,false);
    X = RegionQueryTracker_RC('export',S);
    E = X.ref_exposure;
    assert(isscalar(E) && E.first_query_gen == 2 && ...
            E.first_query_fe == 200 && E.exposure_count == 2 && ...
            E.generated_count == 3, ...
        'Repeated ref+group exposure must keep first query and accumulate events/samples.');

    [S,U] = RegionQueryTracker_RC('updatebmem',S,7,900, ...
        struct('ref',8,'x_b',zeros(0,2)));
    assert(U.ref_conversion_count == 1 && ...
            U.ref_conversion_lag_gen(1) == 5 && ...
            U.ref_conversion_lag_fe(1) == 700, ...
        'Conversion lag must remain anchored to the first exposure.');
    Summary = RegionQueryTracker_RC('summary',S);
    assert(Summary.ref_exposure_count == 1 && ...
            Summary.ref_converted_count == 1 && ...
            Summary.ref_generated_count == 3, ...
        'Summary must expose stable aggregate ref counts.');
end

function testEmptyAndInvalidInputs()
    S = RegionQueryTracker_RC('init',2);
    [S,Event] = RegionQueryTracker_RC('register',S,1,10, ...
        zeros(0,1),zeros(0,1),zeros(0,2),false(0,1),false(0,1));
    [S,Update] = RegionQueryTracker_RC('updatebmem',S,2,20,struct());
    X = RegionQueryTracker_RC('export',S);
    assert(Event.ref_exposure_count == 0 && ...
            Event.eligible_sample_count == 0 && ...
            Update.ref_conversion_count == 0 && ...
            Update.direct_bmem_entry_count == 0, ...
        'Empty register/update paths must return stable zero counts.');
    assert(isfield(X.ref_exposure,'ref') && ...
            isfield(X.direct_entries,'sample_id'), ...
        'Empty exports must preserve their row schemas.');

    assertThrowsIdentifier(@() RegionQueryTracker_RC('init',0), ...
        'CBSRegionQueryTracker:BadDimension');
    assertThrowsIdentifier(@() RegionQueryTracker_RC('register',S,1,10, ...
        1,[2;2],[0.1 0.2],true,false), ...
        'CBSRegionQueryTracker:BadRegisterRows');
    assertThrowsIdentifier(@() RegionQueryTracker_RC('register',S,1,10, ...
        1,4,[0.1 0.2],true,false), ...
        'CBSRegionQueryTracker:BadGroupCode');
    assertThrowsIdentifier(@() RegionQueryTracker_RC('register',S,1,10, ...
        1,2,[0.1 0.2 0.3],true,false), ...
        'CBSRegionQueryTracker:BadDecisionColumns');
end

function assertThrowsIdentifier(Call,ExpectedIdentifier)
    DidThrow = false;
    try
        Call();
    catch Error
        DidThrow = strcmp(Error.identifier,ExpectedIdentifier);
    end
    assert(DidThrow,'Expected error identifier %s.',ExpectedIdentifier);
end
