function test_CBS_region_query_loop_diagnostics()
%TEST_CBS_REGION_QUERY_LOOP_DIAGNOSTICS Verify loop-level attribution wiring.

    repoRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
    addpath(genpath(repoRoot));
    cleanupControl = isolateExperimentControl(); %#ok<NASGU>

    First = runTinyInstrumentedCase();
    verifyEventSchemaAndInvariants(First.Algorithm.metric.region_wgan_gp_history);
    verifyTrackerAndFinalExports(First);

    Second = runTinyInstrumentedCase();
    assert(isequaln(First.Algorithm.metric.region_wgan_gp_final.p2_dec, ...
            Second.Algorithm.metric.region_wgan_gp_final.p2_dec), ...
        'The newly exported P2 population must be deterministic for a fixed seed.');
    fprintf('CBS region query-loop diagnostics passed.\n');
end

function Result = runTinyInstrumentedCase()
    rng(4242,'twister');
    Problem = DASCMOP1_BC('N',20,'D',6,'maxFE',800);
    Params = {1,1,6,2,1,4,1e-4,1e-4,2,2,2,4,10,1,5,4};
    Algorithm = CBS_RegionWGAN_GP('save',0,'run',1, ...
        'outputFcn',@(varargin)[],'parameter',Params);
    Algorithm.Solve(Problem);
    Result = struct('Algorithm',Algorithm,'Problem',Problem);
end

function verifyEventSchemaAndInvariants(H)
    Required = { ...
        'query_populated_sample_count', ...
        'query_frontier_sample_count', ...
        'query_remote_sample_count', ...
        'query_populated_unique_ref_count', ...
        'query_frontier_unique_ref_count', ...
        'query_remote_unique_ref_count', ...
        'query_populated_bdist50_true', ...
        'query_frontier_bwidth90_10_true', ...
        'query_remote_bcover_eps_true', ...
        'offspringG_survive_P1_count', ...
        'offspringG_survive_P2_count', ...
        'offspringG_survive_union_count', ...
        'bmem_bdist50_true', ...
        'bmem_bwidth90_10_true', ...
        'bmem_bcover_eps_true', ...
        'ref_conversion_new_count', ...
        'direct_bmem_entry_new_count', ...
        'frontier_matched_de_available_ref_count', ...
        'frontier_matched_gan_sample_count', ...
        'frontier_matched_de_sample_count', ...
        'frontier_matched_de_bdist50_true', ...
        'frontier_matched_gan_refeq_bdist50_true', ...
        'frontier_matched_de_refeq_bdist50_true', ...
        'time_bmem_dataset_query', ...
        'time_gan_train_sample', ...
        'time_gan_evaluation', ...
        'time_selection_P1', ...
        'time_selection_P2', ...
        'time_diagnostics_serialization'};
    for i = 1 : numel(Required)
        assert(isfield(H,Required{i}), ...
            'Event history is missing required field %s.',Required{i});
    end
    grouped = [H.query_populated_sample_count]' + ...
        [H.query_frontier_sample_count]' + [H.query_remote_sample_count]';
    assert(isequal(grouped,[H.raw_generated_count]'), ...
        'Query-group sample counts must sum to raw generated count per event.');
    p1Grouped = [H.query_populated_survive_P1_count]' + ...
        [H.query_frontier_survive_P1_count]' + ...
        [H.query_remote_survive_P1_count]';
    p2Grouped = [H.query_populated_survive_P2_count]' + ...
        [H.query_frontier_survive_P2_count]' + ...
        [H.query_remote_survive_P2_count]';
    unionGrouped = [H.query_populated_survive_union_count]' + ...
        [H.query_frontier_survive_union_count]' + ...
        [H.query_remote_survive_union_count]';
    assert(isequal(p1Grouped,[H.offspringG_survive_P1_count]') && ...
            isequal(p2Grouped,[H.offspringG_survive_P2_count]') && ...
            isequal(unionGrouped,[H.offspringG_survive_union_count]'), ...
        'Group survival counts must reproduce P1/P2/union event totals.');
    TimerNames = Required(startsWith(Required,'time_'));
    for i = 1 : numel(TimerNames)
        assert(all([H.(TimerNames{i})] >= 0), ...
            'Timer %s must be nonnegative.',TimerNames{i});
    end
end

function verifyTrackerAndFinalExports(Result)
    Metric = Result.Algorithm.metric;
    assert(isfield(Metric,'region_gan_query_tracker') && ...
            isfield(Metric,'region_wgan_gp_query_tracker'), ...
        'Generic and WGAN-specific tracker exports are required.');
    Tracker = Metric.region_wgan_gp_query_tracker;
    assert(all(isfield(Tracker, ...
            {'ref_exposure','ref_conversions','samples','direct_entries','summary'})), ...
        'Tracker export is missing required row sets.');
    assert(isfield(Metric,'region_gan_query_samples') && ...
            isfield(Metric,'region_wgan_gp_query_samples'), ...
        'Generic and WGAN-specific per-sample query logs are required.');
    QuerySamples = Metric.region_wgan_gp_query_samples;
    assert(isequal(size(QuerySamples.rows,2),8) && ...
            size(QuerySamples.rows,1) == ...
            sum([Metric.region_wgan_gp_history.raw_generated_count]), ...
        'Per-sample query log must contain one eight-field row per generated decision.');
    assert(all(ismember(QuerySamples.rows(:,5),[1;2;3])), ...
        'Per-sample query log must retain populated/frontier/remote group codes.');

    assert(isfield(Metric,'region_gan_final') && ...
            isfield(Metric,'region_wgan_gp_final'), ...
        'Generic and WGAN-specific final-population exports are required.');
    Final = Metric.region_wgan_gp_final;
    Required = {'p1_dec','p1_obj','p1_con','p2_dec','p2_obj','p2_con', ...
        'p1_feasible_nd_dec','p1_feasible_nd_obj','p1_feasible_nd_con'};
    assert(all(isfield(Final,Required)), ...
        'Final-population export is missing required numeric arrays.');
    assert(isequaln(Final.p1_dec,double(Result.Algorithm.result{end,2}.decs)), ...
        'Final P1 export must equal the population returned by ALGORITHM.');
    assert(size(Final.p2_dec,2) == Result.Problem.D, ...
        'Final P2 export must preserve decision dimension.');
end

function cleanup = isolateExperimentControl()
    key = 'CBS_RegionGAN_ExperimentControl';
    hadValue = isappdata(0,key);
    if hadValue
        oldValue = getappdata(0,key);
        rmappdata(0,key);
        cleanup = onCleanup(@()setappdata(0,key,oldValue));
    else
        cleanup = onCleanup(@()removeControlIfPresent(key));
    end
end

function removeControlIfPresent(key)
    if isappdata(0,key)
        rmappdata(0,key);
    end
end
