function test_CBS_region_wgan_mainline()
%TEST_CBS_REGION_WGAN_MAINLINE Verify mainline and its sole approved ablation.

    repoRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
    addpath(genpath(repoRoot));
    algorithmFile = which('CBS_RegionWGAN_GP');
    algorithmRoot = fileparts(algorithmFile);
    assert(exist('CBS_RegionWGAN_GP','class') == 8);
    companions = dir(fullfile(algorithmRoot,'CBS_RegionWGAN_GP_*.m'));
    assert(isequal(string({companions.name}), ...
        "CBS_RegionWGAN_GP_NoCGAN.m"), ...
        'Only the approved no-CGAN ablation may accompany the mainline.');

    Defaults = CBS_RegionWGAN_GP.mainlineDefaults();
    assert(Defaults.nGen == 20 && Defaults.zDim == 6 && ...
        Defaults.ganIter == 100 && Defaults.ganMiniBatch == 32 && ...
        Defaults.nCritic == 4 && Defaults.minGANTrainCount == 32 && ...
        Defaults.sampleSigma == 0.3 && ...
        Defaults.ganStopFraction == 0.5 && ...
        Defaults.guideShare == 0.2 && ...
        Defaults.guideCandidatesPerSlot == 5 && ...
        Defaults.calibrationBudget == 20);

    source = string(fileread(algorithmFile));
    dataSource = string(fileread(which('BuildBoundaryDataset_RC')));
    querySource = string(fileread(which('RunRegionGAN_RC')));
    assert(contains(dataSource,'ones(numel(refs),1)') && ...
        contains(dataSource,'zeros(sum(keepI),1)'));
    assert(contains(source,'QueryC = [SampleC,ones') && ...
        contains(querySource,'0.3*totalBudget') && ...
        contains(source,'ladder = [0.4,0.65,0.85]'));
    forbidden = ["operatorMode","p2Operator","generatorMode", ...
        "trainData","scoutMode","metricsMode","guideRecord", ...
        "guideMode","guideAlloc","guideSelect","blsWindow", ...
        "blsFeed","initDecs","criticscore","copynoise", ...
        "consensusshuffle","gapseed","guideFPolicy", ...
        "PlanGuideF_CBS"];
    sourceTree = source+newline+dataSource+newline+querySource+newline+ ...
        string(fileread(which('BoundaryWGAN_RC')));
    assert(~any(contains(sourceTree,forbidden)));
    Parameters = {0,7,50,8,5,9,0.2};
    Algorithm = CBS_RegionWGAN_GP('parameter',Parameters,'save',0, ...
        'outputFcn',@(varargin)[]);
    assert(isequal(Algorithm.parameter,Parameters));
    Problem = DASCMOP1_BC('N',10,'D',5,'maxFE',100);
    Algorithm.Solve(Problem);
    assert(Algorithm.result{end,1} == Problem.maxFE);
    fprintf('CBS mainline and approved-ablation structure passed.\n');
end
