function test_CBS_region_gan_branches()
%TEST_CBS_REGION_GAN_BRANCHES Verify region BCE/WGAN comparison branches.

    repoRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
    addpath(genpath(repoRoot));

    assert(exist('CBS_RegionCGAN','class') == 8, ...
        'Region BCE-CGAN control algorithm must exist.');
    assert(exist('CBS_RegionWGAN_GP','class') == 8, ...
        'Region WGAN-GP comparison algorithm must exist.');

    testRegionWGANMainlineDefaults();
    testBalancedQueryAllocation();
    testDynamicGANIterSchedule();
    testFixmdTrainingTriggerAndTwoLevelIter();
    testFixmdExperimentRunnerBranchCoverage();
    testOffspringGSurvivalCountsDuplicateDecisionsOnce();
    testBoundaryCGANRecordsTrainingHistory();
    testBoundaryWGANTrainsAndSamples();
    testBoundaryWGANSampleZAndPrescreen();
    fprintf('CBS region GAN branch regressions passed.\n');
end

function testRegionWGANMainlineDefaults()
    Defaults = CBS_RegionWGAN_GP.mainlineDefaults();
    assert(Defaults.ganKind == "wgan-gp", ...
        'RegionGAN mainline must use the WGAN-GP branch.');
    assert(Defaults.queryMode == "random_all_w", ...
        'RegionGAN mainline must use fully random QueryC over all refs.');
    assert(Defaults.prevBMemMode == "prev1_fair_union", ...
        'RegionGAN mainline must retain previous BMem as fair competitors.');
    assert(Defaults.bmemBandMode == "current" && ...
            isempty(Defaults.bandMaxAnchorsPerRef), ...
        'RegionGAN mainline must keep the current mixed BMem cloud by default.');
    assert(Defaults.ganMiniBatch == 32, ...
        'RegionGAN mainline must keep ganMiniBatch=32.');
    assert(Defaults.minGANTrainCount == 32, ...
        'RegionGAN mainline must keep minGANTrainCount=32.');
    assert(Defaults.nGen == 30, ...
        'RegionGAN mainline must generate at most 30 GAN offspring per refresh.');
    assert(Defaults.maxAnchorsPerRef == 5, ...
        'RegionGAN mainline must keep the ref-cap quality gate at five anchors.');
    assert(Defaults.ganIter == 100 && Defaults.nCritic == 2, ...
        'RegionGAN mainline must promote C_iter100_ncritic2 as the default training dose.');
    assert(Defaults.gpLambda == 10, ...
        'RegionGAN mainline must retain the WGAN-GP gradient penalty.');
    assert(isfield(Defaults,'sampleSigma') && Defaults.sampleSigma == 0.3, ...
        'RegionGAN mainline must use sampleSigma=0.3 for sampling Z.');
end

function testBalancedQueryAllocation()
    rng(219,'twister');
    QueryC = [(1:20)' zeros(20,1)];
    [SampleC,Counts] = RunRegionGAN_RC('allocatequery',QueryC,2,30);
    assert(size(SampleC,1) == 30, ...
        'Allocated query rows must respect the nGen hard cap.');
    assert(numel(Counts) == size(QueryC,1), ...
        'Allocation counts must map back to every original QueryC row.');
    assert(all(Counts >= 1) && all(Counts <= 2), ...
        'With nGen=30, K=20, qpc=2, every region gets 1 or 2 samples.');
    assert(sum(Counts) == 30, ...
        'Allocation counts must sum to the sampled QueryC row count.');

    [SmallSampleC,SmallCounts] = RunRegionGAN_RC('allocatequery',QueryC(1:2,:),2,30);
    assert(size(SmallSampleC,1) == 4 && all(SmallCounts == 2), ...
        'Small region counts should use qpc as a per-region cap, not fill nGen.');
end

function testFixmdTrainingTriggerAndTwoLevelIter()
    Options = struct( ...
        'trainTriggerMode',"deltaTrainCount20", ...
        'trainTriggerDelta',0.20, ...
        'iter',50, ...
        'ganIterSchedule',"two_level_data_change", ...
        'ganIterStart',75, ...
        'ganIterEnd',50);
    State = RunRegionGAN_RC('inittraintriggerstate');

    [flag,Info] = RunRegionGAN_RC('traintrigger',Options,State,2, ...
        40,10,false);
    assert(flag && Info.trigger_first_train == 1, ...
        'First ready training set must trigger training even off-cycle.');
    Resolved = RunRegionGAN_RC('resolveganoptions',Options,10000, ...
        100000,Info);
    assert(Resolved.iter == 75 && ...
            Resolved.gan_iter_schedule == "two_level_data_change", ...
        'Two-level ganIter must use the boosted iter on first/data-change training.');

    State = RunRegionGAN_RC('updatetraintriggerstate',State,Info);
    [flag,Info] = RunRegionGAN_RC('traintrigger',Options,State,3, ...
        43,10,false);
    assert(~flag && Info.trigger_data_changed == 0, ...
        'Small train_count changes below threshold must not trigger off-cycle.');
    Resolved = RunRegionGAN_RC('resolveganoptions',Options,30000, ...
        100000,Info);
    assert(Resolved.iter == 50, ...
        'Two-level ganIter must use the base iter when data did not change.');

    [flag,Info] = RunRegionGAN_RC('traintrigger',Options,State,4, ...
        49,10,false);
    assert(flag && Info.trigger_train_count_delta >= 0.20, ...
        'Train count changes at or above threshold must trigger off-cycle.');
    Resolved = RunRegionGAN_RC('resolveganoptions',Options,30000, ...
        100000,Info);
    assert(Resolved.iter == 75, ...
        'Two-level ganIter must use the boosted iter on delta-triggered training.');

    OffOptions = struct('trainTriggerMode',"off");
    [flag,Info] = RunRegionGAN_RC('traintrigger',OffOptions,State,5, ...
        80,12,false);
    assert(~flag && Info.trigger_reason == "waiting_period", ...
        'trainTriggerMode=off must preserve periodic-only training.');
end

function testFixmdExperimentRunnerBranchCoverage()
    repoRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
    runnerFile = fullfile(repoRoot,'Algorithms', ...
        'Multi-objective optimization','CBS-CGAN','Support', ...
        'run_CBS_RegionWGAN_GP_fixmd_branches.m');
    assert(isfile(runnerFile), ...
        'FixMD experiment runner must exist for unified validation runs.');
    sourceText = fileread(runnerFile);
    expectedRoot = fileparts(fileparts(fileparts(fileparts( ...
        fileparts(runnerFile)))));
    oldRoot = fileparts(fileparts(fileparts(fileparts(runnerFile))));
    assert(isfile(fullfile(expectedRoot,'platemo.m')) && ...
            ~isfile(fullfile(oldRoot,'platemo.m')), ...
        'Test setup must distinguish PlatEMO root from Algorithms/.');
    assert(contains(sourceText,'platemo.m'), ...
        'FixMD runner must validate the PlatEMO root instead of stopping at Algorithms/.');
    requiredBranches = [ ...
        "fixmd_diag_baseline", ...
        "fixmd_train_gap1_iter50", ...
        "fixmd_train_gap2_iter50", ...
        "fixmd_train_gap1_iter75", ...
        "fixmd_train_gap2_iter75", ...
        "fixmd_train_gap2_delta20_iter50", ...
        "fixmd_train_gap2_delta20_boost75", ...
        "fixmd_prescreen1_fixed50", ...
        "fixmd_prescreen8_fixed50", ...
        "fixmd_prescreen8_delta20_boost75"];
    for i = 1 : numel(requiredBranches)
        assert(contains(sourceText,requiredBranches(i)), ...
            'FixMD runner missing branch: %s.',requiredBranches(i));
    end
    requiredControls = [ ...
        "trainTriggerMode", ...
        "trainTriggerDelta", ...
        "two_level_data_change", ...
        "prescreenMultiplier", ...
        "random_all_w"];
    for i = 1 : numel(requiredControls)
        assert(contains(sourceText,requiredControls(i)), ...
            'FixMD runner missing control: %s.',requiredControls(i));
    end
end

function testOffspringGSurvivalCountsDuplicateDecisionsOnce()
    GDec = [0 0;0 0;1 1];
    GCon = [-1;-1;1];
    SelectedDec = [0 0;2 2];
    Metrics = RunRegionGAN_RC('offspringgsurvivaldiagnostics', ...
        GDec,GCon,SelectedDec);
    assert(Metrics.offspringG_count == 3 && ...
            Metrics.offspringG_survive_count == 1, ...
        'Survival diagnostics must consume matched selected rows for duplicate generated decisions.');
    assert(abs(Metrics.offspringG_survival_rate - 1/3) < 1e-12, ...
        'Duplicate generated rows must not all survive when one selected copy exists.');
    assert(Metrics.offspringG_feasible_count == 2 && ...
            Metrics.offspringG_feasible_survive_count == 1 && ...
            abs(Metrics.offspringG_feasible_survival_rate - 0.5) < 1e-12, ...
        'Feasible survival diagnostics must use the same one-to-one matching.');
end

function testBoundaryWGANTrainsAndSamples()
    rng(211,'twister');
    Problem = DASCMOP1_BC('N',8,'D',6,'maxFE',100);
    TrainX = repmat(Problem.lower,8,1) + rand(8,Problem.D).* ...
        repmat(Problem.upper - Problem.lower,8,1);
    TrainC = rand(8,2);
    Options = struct( ...
        'zDim',6, ...
        'iter',1, ...
        'miniBatch',4, ...
        'lrD',1e-4, ...
        'lrG',1e-4, ...
        'nCritic',1, ...
        'gpLambda',10, ...
        'generatorHidden',[32 32], ...
        'criticHidden',[32 32], ...
        'sigma',1.0);

    GAN = BoundaryWGAN_RC('train',[],TrainX,TrainC,Problem,Options);
    assert(isfield(GAN,'netG') && isfield(GAN,'netC'), ...
        'BoundaryWGAN_RC must return generator and critic networks.');
    assert(layerOutputSize(GAN.netG,'g_fc1') == 32 && ...
            layerOutputSize(GAN.netG,'g_fc2') == 32, ...
        'WGAN generator must follow the small [32 32] hidden layers.');
    assert(layerOutputSize(GAN.netC,'c_fc1') == 32 && ...
            layerOutputSize(GAN.netC,'c_fc2') == 32, ...
        'WGAN critic must follow the small [32 32] hidden layers.');
    assert(~hasLayer(GAN.netC,'c_sigmoid'), ...
        'WGAN critic output must stay linear, not sigmoid/BCE.');
    assert(GAN.critic_holdout_count > 0 && ...
            GAN.critic_train_diag_count + GAN.critic_holdout_count <= ...
            size(TrainX,1), ...
        'WGAN holdout diagnostics must use a split disjoint from the training diagnostic pool.');

    QueryC = TrainC(1:2,:);
    [Dec,Info] = BoundaryWGAN_RC('samplebycondition',GAN,QueryC,3,Options);
    assert(isequal(size(Dec),[6 Problem.D]), ...
        'WGAN sampling must return queryPerCondition decisions per query.');
    assert(isequal(size(Info.z),[6 Options.zDim]), ...
        'WGAN sample info must expose the latent z used for each sample.');
end

function testDynamicGANIterSchedule()
    Options = struct( ...
        'iter',75, ...
        'ganIterSchedule',"linear_fe", ...
        'ganIterStart',150, ...
        'ganIterEnd',30);

    AtStart = RunRegionGAN_RC('resolveganoptions',Options,0,100000);
    At10k = RunRegionGAN_RC('resolveganoptions',Options,10000,100000);
    At50k = RunRegionGAN_RC('resolveganoptions',Options,50000,100000);
    AtEnd = RunRegionGAN_RC('resolveganoptions',Options,100000,100000);
    PastEnd = RunRegionGAN_RC('resolveganoptions',Options,120000,100000);

    assert(AtStart.iter == 150, ...
        'Linear ganIter schedule must use ganIterStart at FE=0.');
    assert(At10k.iter == 138, ...
        'Linear ganIter schedule must interpolate by current FE/maxFE.');
    assert(At50k.iter == 90, ...
        'Linear ganIter schedule must be midpoint at FE=0.5*maxFE.');
    assert(AtEnd.iter == 30 && PastEnd.iter == 30, ...
        'Linear ganIter schedule must clamp at ganIterEnd.');

    Fixed = RunRegionGAN_RC('resolveganoptions',struct('iter',75), ...
        50000,100000);
    assert(Fixed.iter == 75, ...
        'Absent ganIterSchedule, resolveganoptions must preserve fixed iter.');
end

function testBoundaryWGANSampleZAndPrescreen()
    rng(223,'twister');
    Problem = DASCMOP1_BC('N',8,'D',6,'maxFE',100);
    TrainX = repmat(Problem.lower,8,1) + rand(8,Problem.D).* ...
        repmat(Problem.upper - Problem.lower,8,1);
    TrainC = rand(8,2);
    Options = struct( ...
        'zDim',3, ...
        'iter',1, ...
        'miniBatch',4, ...
        'lrD',1e-4, ...
        'lrG',1e-4, ...
        'nCritic',1, ...
        'gpLambda',10, ...
        'generatorHidden',[32 32], ...
        'criticHidden',[32 32], ...
        'sigma',0.25, ...
        'sampleZMode',"zero", ...
        'prescreenMultiplier',3);

    GAN = BoundaryWGAN_RC('train',[],TrainX,TrainC,Problem,Options);
    QueryC = TrainC(1:2,:);
    [Dec,Info] = BoundaryWGAN_RC('samplebycondition',GAN,QueryC,2,Options);

    assert(isequal(size(Dec),[4 Problem.D]), ...
        'Prescreened WGAN sampling must preserve the final sample count.');
    assert(isequal(size(Info.z),[4 Options.zDim]) && ...
            all(Info.z(:) == 0), ...
        'sampleZMode=zero must use zero latent vectors only for sampling.');
    assert(Info.prescreen_multiplier == 3, ...
        'WGAN sample info must record the critic prescreen multiplier.');
    assert(Info.prescreen_candidate_count == 12 && ...
            Info.prescreen_selected_count == 4, ...
        'Prescreen diagnostics must count raw candidates and selected rows.');
    assert(isequal(size(Info.prescreen_selected_score),[4 1]), ...
        'Prescreen diagnostics must expose one selected critic score per row.');
    assert(isfield(Info,'generated_critic_score') && ...
            isequal(size(Info.generated_critic_score),[4 1]), ...
        'WGAN sample info must expose one critic score for each generated row.');
    assert(isfield(Info,'prescreen_raw_score') && ...
            isequal(size(Info.prescreen_raw_score),[12 1]), ...
        'Prescreen diagnostics must retain raw candidate critic scores.');

    Options.sampleZMode = "random";
    Options.trainZMode = "random";
    Options.trainSigma = 1.0;
    Options.sampleSigma = 0.01;
    Options.prescreenMultiplier = 1;
    [~,SmallZInfo] = BoundaryWGAN_RC('samplebycondition',GAN,QueryC,4, ...
        Options);
    assert(any(abs(SmallZInfo.z(:)) > 0) && ...
            max(abs(SmallZInfo.z(:))) < 0.1, ...
        'sampleSigma must control sampling Z scale independently.');
end

function testBoundaryCGANRecordsTrainingHistory()
    rng(217,'twister');
    Problem = DASCMOP1_BC('N',8,'D',6,'maxFE',100);
    TrainX = repmat(Problem.lower,8,1) + rand(8,Problem.D).* ...
        repmat(Problem.upper - Problem.lower,8,1);
    TrainC = rand(8,2);
    Options = struct( ...
        'zDim',6, ...
        'iter',2, ...
        'miniBatch',4, ...
        'lrD',1e-4, ...
        'lrG',1e-4, ...
        'dSteps',1, ...
        'gSteps',1, ...
        'advWeight',1.0, ...
        'trainMode',"iter", ...
        'realLabel',0.9, ...
        'generatorHidden',[32 32], ...
        'discriminatorHidden',[32 32], ...
        'sigma',1.0);

    GAN = BoundaryCGAN_CBS('train',[],TrainX,TrainC,Problem,Options);
    assert(isfield(GAN,'train_history') && numel(GAN.train_history) == 3, ...
        'CGAN training must record initial and per-iter diagnostics.');
    required = {'step','loss_d','loss_g','d_real_acc','d_fake_acc', ...
        'd_bal_acc','g_fool_rate','score_real_mean','score_fake_mean', ...
        'score_random_mean'};
    for i = 1 : numel(required)
        assert(isfield(GAN.train_history,required{i}), ...
            'CGAN training history missing field: %s.',required{i});
    end
    assert(all([GAN.train_history.d_real_acc] >= 0 & ...
            [GAN.train_history.d_real_acc] <= 1), ...
        'D real accuracy must stay in [0,1].');
    assert(all([GAN.train_history.d_fake_acc] >= 0 & ...
            [GAN.train_history.d_fake_acc] <= 1), ...
        'D fake accuracy must stay in [0,1].');
    assert(all([GAN.train_history.g_fool_rate] >= 0 & ...
            [GAN.train_history.g_fool_rate] <= 1), ...
        'G fool rate must stay in [0,1].');
    assert(isfinite(GAN.last_discriminator_loss) && ...
            isfinite(GAN.last_generator_loss), ...
        'CGAN must expose final D/G losses as scalar fields.');
    assert(GAN.last_g_fool_rate == GAN.train_history(end).g_fool_rate, ...
        'Final G fool rate must mirror the last training-history row.');
end

function tf = hasLayer(net,name)
    tf = any(string({net.Layers.Name}) == string(name));
end

function value = layerOutputSize(net,name)
    idx = find(string({net.Layers.Name}) == string(name),1,'first');
    assert(~isempty(idx),'Missing layer: %s.',name);
    value = double(net.Layers(idx).OutputSize);
end
