function test_CBS_boundary_wgan_mapping_diagnostics()
%TEST_CBS_BOUNDARY_WGAN_MAPPING_DIAGNOSTICS Verify behavior-neutral probes.

    repoRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
    addpath(genpath(repoRoot));

    rng(401,'twister');
    Problem = DASCMOP1_BC('N',12,'D',6,'maxFE',100);
    TrainX = repmat(Problem.lower,12,1) + rand(12,Problem.D).* ...
        repmat(Problem.upper - Problem.lower,12,1);
    TrainC = repelem([0.1 0.9;0.3 0.7;0.5 0.5;0.7 0.3;0.9 0.1], ...
        [2;3;1;4;2],1);
    Base = struct( ...
        'zDim',4, ...
        'iter',3, ...
        'miniBatch',6, ...
        'lrD',1e-4, ...
        'lrG',1e-4, ...
        'nCritic',1, ...
        'gpLambda',10, ...
        'generatorHidden',[32 32], ...
        'criticHidden',[32 32], ...
        'trainSigma',1.0, ...
        'sampleSigma',0.3, ...
        'captureTrainHistory',false, ...
        'mappingDiagnostics',false, ...
        'mappingDiagMaxConditions',2, ...
        'mappingDiagZSamples',4);

    rng(911,'twister');
    feBefore = Problem.FE;
    GANControl = BoundaryWGAN_RC('train',[],TrainX,TrainC,Problem,Base);
    rngControl = rng;
    SampleOptions = Base;
    SampleOptions.sampleZ = zeros(4,Base.zDim);
    ControlDec = BoundaryWGAN_RC('samplebycondition',GANControl, ...
        TrainC(1:2,:),2,SampleOptions);

    Diagnostic = Base;
    Diagnostic.captureTrainHistory = true;
    Diagnostic.mappingDiagnostics = true;
    rng(911,'twister');
    GANDiagnostic = BoundaryWGAN_RC('train',[],TrainX,TrainC, ...
        Problem,Diagnostic);
    rngDiagnostic = rng;
    DiagnosticDec = BoundaryWGAN_RC('samplebycondition',GANDiagnostic, ...
        TrainC(1:2,:),2,SampleOptions);

    assert(isequal(rngControl,rngDiagnostic), ...
        'Mapping diagnostics must not consume random numbers.');
    assert(isequaln(ControlDec,DiagnosticDec), ...
        'Enabling mapping diagnostics must not change generated decisions.');
    assert(Problem.FE == feBefore, ...
        'WGAN mapping diagnostics must not perform active evaluations.');
    assert(numel(GANDiagnostic.train_history) == Diagnostic.iter, ...
        'WGAN training history must retain one row per outer iteration.');
    requiredHistory = {'step','loss_d','loss_g','gradient_penalty', ...
        'score_real_mean','score_fake_mean'};
    assert(all(isfield(GANDiagnostic.train_history,requiredHistory)), ...
        'WGAN training history is missing required loss/score fields.');
    assert(GANDiagnostic.prequential_new_count == size(TrainX,1) && ...
            GANDiagnostic.prequential_seen_count == 0, ...
        'The first prequential event must classify every training row as new.');
    requiredFinite = {'prequential_pre_critic_gap', ...
        'prequential_post_critic_gap','prequential_pre_dec_dist50', ...
        'prequential_post_dec_dist50','same_z_diff_c_dec_median', ...
        'same_c_diff_z_dec_median','condition_effect_ratio_dec'};
    for i = 1 : numel(requiredFinite)
        assert(isfinite(GANDiagnostic.(requiredFinite{i})), ...
            'Diagnostic field %s must be finite.',requiredFinite{i});
    end
    assert(GANDiagnostic.condition_diag_condition_count == ...
            Base.mappingDiagMaxConditions, ...
        'The historical condition diagnostic must retain its condition cap.');

    rngBeforeLatentScale = rng;
    feBeforeLatentScale = Problem.FE;
    [LatentRows,LatentSummary] = BoundaryWGAN_RC( ...
        'diagnoselatentscale',GANDiagnostic,TrainX,TrainC, ...
        Problem,Diagnostic);
    rngAfterLatentScale = rng;
    assert(isequal(rngBeforeLatentScale,rngAfterLatentScale), ...
        'Latent-scale diagnostics must not consume random numbers.');
    assert(Problem.FE == feBeforeLatentScale, ...
        'Latent-scale diagnostics must not perform active evaluations.');
    assert(numel(LatentRows) == size(unique(TrainC,'rows'),1) && ...
            numel(LatentRows) > Diagnostic.mappingDiagMaxConditions, ...
        'Latent-scale diagnostics must cover every populated condition.');
    assert(LatentSummary.latent_scale_ref_count == numel(LatentRows) && ...
            LatentSummary.latent_scale_z_count == ...
            Diagnostic.mappingDiagZSamples && ...
            LatentSummary.latent_scale_train_sigma == 1.0 && ...
            LatentSummary.latent_scale_sample_sigma == 0.3, ...
        'Latent-scale summary must record full condition and sigma metadata.');
    requiredLatentFields = {'condition','train_count','train_dec_pair90', ...
        'train_scale_gen_to_train_dec50', ...
        'train_scale_gen_to_train_dec90', ...
        'train_scale_anchor_utilization_rate', ...
        'train_scale_diversity_ratio90', ...
        'sample_scale_gen_to_train_dec50', ...
        'sample_scale_gen_to_train_dec90', ...
        'sample_scale_anchor_utilization_rate', ...
        'sample_scale_diversity_ratio90'};
    assert(all(isfield(LatentRows,requiredLatentFields)) && ...
            all(isfinite([LatentRows.train_scale_gen_to_train_dec50])) && ...
            all(isfinite([LatentRows.sample_scale_gen_to_train_dec50])) && ...
            all(isfinite([LatentRows.train_scale_anchor_utilization_rate])) && ...
            all(isfinite([LatentRows.sample_scale_anchor_utilization_rate])), ...
        'Latent-scale ref rows are missing finite support-coverage metrics.');

    EqualScale = Diagnostic;
    EqualScale.sampleSigma = EqualScale.trainSigma;
    [EqualRows,EqualSummary] = BoundaryWGAN_RC( ...
        'diagnoselatentscale',GANDiagnostic,TrainX,TrainC, ...
        Problem,EqualScale);
    pairedFields = { ...
        {'train_scale_generated_dec_pair90', ...
        'sample_scale_generated_dec_pair90'}, ...
        {'train_scale_gen_to_train_dec50', ...
        'sample_scale_gen_to_train_dec50'}, ...
        {'train_scale_gen_to_train_dec90', ...
        'sample_scale_gen_to_train_dec90'}, ...
        {'train_scale_anchor_utilization_rate', ...
        'sample_scale_anchor_utilization_rate'}, ...
        {'train_scale_diversity_ratio90', ...
        'sample_scale_diversity_ratio90'}};
    for i = 1 : numel(pairedFields)
        names = pairedFields{i};
        assert(isequaln([EqualRows.(names{1})],[EqualRows.(names{2})]), ...
            'Equal sigmas must reuse the same deterministic Z0 for %s.', ...
            names{1});
    end
    assert(isequaln( ...
            EqualSummary.latent_scale_train_gen_to_train_dec50_median, ...
            EqualSummary.latent_scale_sample_gen_to_train_dec50_median), ...
        'Equal sigmas must produce identical event-level medians.');

    GANDiagnostic = BoundaryWGAN_RC('train',GANDiagnostic,TrainX, ...
        TrainC,Problem,Diagnostic);
    assert(GANDiagnostic.prequential_new_count == 0 && ...
            GANDiagnostic.prequential_seen_count == size(TrainX,1), ...
        'Repeated training rows must be classified as previously seen.');

    TrainX2 = [TrainX;0.25*Problem.lower + 0.75*Problem.upper];
    TrainC2 = [TrainC;0.5 0.5];
    GANDiagnostic = BoundaryWGAN_RC('train',GANDiagnostic,TrainX2, ...
        TrainC2,Problem,Diagnostic);
    assert(GANDiagnostic.prequential_new_count == 1 && ...
            GANDiagnostic.prequential_seen_count == size(TrainX,1), ...
        'Prequential diagnostics must isolate newly introduced rows.');

    fprintf('CBS boundary WGAN mapping diagnostics regressions passed.\n');
end
