function test_CBS_train_quality_sweep_runner_smoke()
%TEST_CBS_TRAIN_QUALITY_SWEEP_RUNNER_SMOKE Verify train-figure sweep runner.

    repoRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
    addpath(genpath(repoRoot));
    testDefaultTrainQualitySweepConfiguration(repoRoot);
    testTrainQualitySweepRunsOnlyTrainFigures();
    fprintf('CBS-CGAN train quality sweep runner smoke passed.\n');
end

function testDefaultTrainQualitySweepConfiguration(repoRoot)
    runnerFile = fullfile(repoRoot,'Algorithms', ...
        'Multi-objective optimization','CBS-CGAN','Support', ...
        'run_CBS_CGAN_train_quality_sweep_lir_online.m');
    assert(isfile(runnerFile), ...
        'Train quality sweep runner file must exist.');
    txt = fileread(runnerFile);
    compact = regexprep(txt,'\s+','');
    compact = erase(compact,'...');
    assert(contains(compact, ...
        "ensureSweepField(Options,'workerCount',10)"), ...
        'Default train-quality sweep workerCount must be 10.');
    assert(contains(compact, ...
        '["LIRCMOP5_BC";"LIRCMOP6_BC";"LIRCMOP7_BC";"LIRCMOP8_BC";"LIRCMOP9_BC";"LIRCMOP10_BC"]'), ...
        'Default train-quality sweep must use all six LIRCMOP BC problems.');
    assert(contains(compact, ...
        "ensureSweepField(Options,'runIds',1)"), ...
        'Default train-quality sweep must use runs=1.');
    assert(contains(compact, ...
        "ensureSweepField(Options,'figureKinds','train_reconstruction')") || ...
        contains(compact, ...
        'ensureSweepField(Options,"figureKinds","train_reconstruction")'), ...
        'Default train-quality sweep must render only training reconstruction figures.');
    expected = ["A_ref_only_adv","B_ref_y_adv"];
    for i = 1 : numel(expected)
        assert(contains(compact,expected(i)), ...
            'Default train-quality sweep missing setting: %s.',expected(i));
    end
end

function testTrainQualitySweepRunsOnlyTrainFigures()
    outDir = fullfile(tempdir,sprintf('cbs_train_quality_sweep_%s', ...
        char(java.util.UUID.randomUUID)));
    Settings = [ ...
        makeSetting("A_ref_only_adv","ref_only",1,0); ...
        makeSetting("B_ref_y_adv","ref_y",1,0)];
    Options = struct( ...
        'workerCount',1, ...
        'problemNames',"DASCMOP1_BC", ...
        'runIds',1, ...
        'N',30, ...
        'maxFE',1500, ...
        'targets',1000, ...
        'settings',Settings, ...
        'plotRun',1, ...
        'visualDiagnostics',true, ...
        'figureKinds',"train_reconstruction");

    [Manifest,~,Summary,StageMetrics,FigureManifest] = ...
        run_CBS_CGAN_train_quality_sweep_lir_online(outDir,Options);

    assert(height(Manifest) == 2 && ...
            all(ismember(["A_ref_only_adv";"B_ref_y_adv"], ...
            string(Manifest.setting))), ...
        'Sweep manifest must include the requested settings.');
    assert(height(Summary) == 2 && all(string(Summary.status) == "ok"), ...
        'Tiny train-quality sweep must complete both settings.');
    assert(all(ismember(["setting","variant","condition_mode", ...
            "ganIter","ganMiniBatch","zDim","trainMode", ...
            "trainZMode","sampleZMode","maxCandidatePairsPerRef"], ...
            string(StageMetrics.Properties.VariableNames))), ...
        'Stage metrics must expose sweep parameter columns.');
    figureFiles = string(FigureManifest.figure_file);
    assert(~isempty(figureFiles), ...
        'Train-quality sweep must write train reconstruction figures.');
    assert(all(contains(figureFiles,"train_reconstruction")), ...
        'Train-quality sweep must suppress non-training figures.');
    assert(all(arrayfun(@(f)isfile(f),figureFiles)), ...
        'Figure manifest must point to existing training reconstruction files.');
    rmdir(outDir,'s');
end

function S = makeSetting(name,conditionMode,advWeight,~)
    S = struct( ...
        'setting',string(name), ...
        'variant',string(name), ...
        'conditionMode',string(conditionMode), ...
        'advWeight',double(advWeight), ...
        'nGen',6, ...
        'zDim',2, ...
        'ganIter',1, ...
        'ganMiniBatch',8, ...
        'trainMode',"iter", ...
        'trainZMode',"zero", ...
        'sampleZMode',"zero", ...
        'maxCandidatePairsPerRef',3, ...
        'networkPreset',"default");
end
