function test_CBS_boundary_wgan_structured_z()
%TEST_CBS_BOUNDARY_WGAN_STRUCTURED_Z Verify categorical-z and MI wiring.

    repoRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
    addpath(genpath(repoRoot));

    rng(417,'twister');
    Problem = DASCMOP1_BC('N',12,'D',6,'maxFE',1000);
    TrainC = repelem([0.2 0.8;0.5 0.5;0.8 0.2],[5;3;2],1);
    TrainX = repmat(Problem.lower,10,1) + rand(10,Problem.D).* ...
        repmat(Problem.upper - Problem.lower,10,1);
    Options = struct( ...
        'zDim',6, ...
        'iter',3, ...
        'miniBatch',8, ...
        'lrD',1e-4, ...
        'lrG',1e-4, ...
        'nCritic',1, ...
        'gpLambda',10, ...
        'structuredZMode',"categorical_mi", ...
        'structuredZMaxModes',5, ...
        'structuredZLambda',1.0, ...
        'queryActiveModeCount',[5;1]);

    feBefore = Problem.FE;
    GAN = BoundaryWGAN_RC('train',[],TrainX,TrainC,Problem,Options);
    [Dec,Info] = BoundaryWGAN_RC('samplebycondition',GAN, ...
        [0.2 0.8;0.1 0.9],5,Options);

    assert(Problem.FE == feBefore, ...
        'Structured-z training and sampling must not perform evaluations.');
    assert(isfield(GAN,'netQ') && isa(GAN.netQ,'dlnetwork') && ...
            GAN.iterQ == Options.iter, ...
        'The minimal mode decoder must receive one update per G update.');
    assert(isfinite(GAN.last_generator_adversarial_loss) && ...
            isfinite(GAN.last_mi_loss) && ...
            isfinite(GAN.last_mode_decoder_accuracy), ...
        'Structured-z training must expose finite adversarial/MI diagnostics.');
    assert(size(Dec,1) == 10 && size(Dec,2) == Problem.D && ...
            isequal(size(Info.z),[10 6]), ...
        'Structured-z sampling returned an invalid decision or latent shape.');
    assert(all(sum(Info.z(:,1:5),2) == 1) && ...
            all(Info.mode_label(1:5) >= 1 & ...
                Info.mode_label(1:5) <= 5) && ...
            all(Info.mode_label(6:10) == 1), ...
        'Categorical codes must honor populated and frontier active-mode caps.');
    assert(all(isfinite(Info.mode_prediction)) && ...
            all(isfinite(Info.mode_confidence)) && ...
            all(Info.mode_confidence >= 0 & Info.mode_confidence <= 1), ...
        'The mode decoder must report finite sample predictions/confidences.');

    Bad = Options;
    Bad.zDim = 5;
    caught = false;
    try
        BoundaryWGAN_RC('train',[],TrainX,TrainC,Problem,Bad);
    catch err
        caught = strcmp(err.identifier,'CBSRegionWGAN:StructuredZTooSmall');
    end
    assert(caught, ...
        'Structured-z must retain one continuous residual latent dimension.');

    fprintf('CBS boundary WGAN structured-z regressions passed.\n');
end
