function test_CBS_region_frontier_anneal_query()
%TEST_CBS_REGION_FRONTIER_ANNEAL_QUERY Verify local frontier query sampling.

    repoRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
    addpath(genpath(repoRoot));

    testFrontierAnnealSplitsPopulatedAndOneHopRefs();
    testFrontierAnnealSupportsScalarConditionPools();
    testFrontierAnnealRunnerDefinesBranch();
    fprintf('CBS region frontier-anneal query regressions passed.\n');
end

function testFrontierAnnealSplitsPopulatedAndOneHopRefs()
    W = [1 0;0.75 0.25;0.5 0.5;0.25 0.75;0 1];
    QueryRefs = [2;4];
    QueryC = W(QueryRefs,:);
    Info = struct( ...
        'queryRegions',QueryRefs, ...
        'allQueryConditions',W, ...
        'allQueryRegions',(1:5)');

    rng(1709,'twister');
    [SampleC,Counts,SampleRefs,DiagQueryC,DiagQueryRefs] = ...
        RunRegionGAN_RC('regionquerysamples',"frontier_anneal", ...
        QueryC,Info,W,99,10);

    assert(isequal(size(SampleC),[10 2]), ...
        'frontier_anneal must draw exactly nGen query conditions.');
    assert(sum(ismember(SampleRefs,QueryRefs)) == 6, ...
        'frontier_anneal must allocate 60%% of samples to populated refs.');
    assert(sum(ismember(SampleRefs,[1;3;5])) == 4, ...
        'frontier_anneal must allocate 40%% of samples to one-hop frontier refs.');
    assert(~any(ismember(SampleRefs,0)), ...
        'frontier_anneal sample refs must be valid region indices.');
    assert(isequal(DiagQueryRefs,[2;4;1;3;5]), ...
        'frontier_anneal diagnostics must list populated rows before one-hop frontier rows.');
    assert(isequal(DiagQueryC,W([2;4;1;3;5],:)), ...
        'frontier_anneal diagnostic conditions must stay aligned with diagnostic refs.');
    assert(numel(Counts) == size(DiagQueryC,1), ...
        'frontier_anneal counts must map to the mixed diagnostic query pool.');
    assert(sum(Counts(1:2)) == 6 && sum(Counts(3:end)) == 4, ...
        'frontier_anneal counts must preserve the 60/40 group split.');
    poolCount = RunRegionGAN_RC('regionquerypoolcount',"frontier_anneal", ...
        QueryC,Info,W);
    assert(poolCount == 5, ...
        'frontier_anneal pool count must include populated and frontier rows.');
end

function testFrontierAnnealSupportsScalarConditionPools()
    W = [1 0;0.75 0.25;0.5 0.5;0.25 0.75;0 1];
    Info = struct();
    Info.allQueryConditions = [ ...
        W(1,:) 0.50; ...
        W(2,:) 0.25; ...
        W(2,:) 0.75; ...
        W(3,:) 0.50; ...
        W(4,:) 0.25; ...
        W(4,:) 0.75; ...
        W(5,:) 0.50];
    Info.allQueryRegions = [1;2;2;3;4;4;5];
    Info.queryRegions = [2;2;4;4];
    QueryC = Info.allQueryConditions([2;3;5;6],:);

    rng(2718,'twister');
    [SampleC,Counts,SampleRefs,DiagQueryC,DiagQueryRefs] = ...
        RunRegionGAN_RC('regionquerysamples',"frontier_anneal", ...
        QueryC,Info,W,99,10);

    assert(isequal(size(SampleC),[10 3]), ...
        'frontier_anneal must preserve extended scalar condition dimensions.');
    assert(sum(ismember(SampleRefs,[2;4])) == 6, ...
        'frontier_anneal scalar pools must still allocate 60%% to populated refs.');
    assert(sum(ismember(SampleRefs,[1;3;5])) == 4, ...
        'frontier_anneal scalar pools must allocate 40%% to one-hop frontier refs.');
    assert(isequal(DiagQueryRefs,[2;2;4;4;1;3;5]), ...
        'frontier_anneal scalar diagnostics must preserve all populated bins plus frontier bins.');
    assert(isequal(size(DiagQueryC),[7 3]) && numel(Counts) == 7, ...
        'frontier_anneal scalar diagnostics and counts must stay row-aligned.');
end

function testFrontierAnnealRunnerDefinesBranch()
    repoRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
    runnerFile = fullfile(repoRoot,'Algorithms', ...
        'Multi-objective optimization','CBS-CGAN','Support', ...
        'run_CBS_RegionWGAN_GP_frontier_anneal_branch.m');
    assert(isfile(runnerFile), ...
        'Frontier-anneal WGAN-GP runner must exist.');
    sourceText = fileread(runnerFile);
    required = [ ...
        "C_query_frontier_anneal", ...
        "frontier_anneal", ...
        "queryMode", ...
        "conditionMode", ...
        "region", ...
        "bdist50_true", ...
        "bwidth90_10_true"];
    for i = 1 : numel(required)
        assert(contains(sourceText,required(i)), ...
            'Frontier-anneal runner missing required token: %s.', ...
            required(i));
    end
    assert(~contains(sourceText,"region_slocal"), ...
        'Frontier-anneal runner must not reintroduce s_local conditioning.');
end
